### ISSUE TITLE
Suspension enhancements

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1001]
Details-Button in column "suspension" is not needed. Edit button is enough to see the details of the suspension. Then we have one button less on this page. 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/

I would still rename the button "cancel" in the column "suspension" to "remove". It's short and "removing a suspension" is correct. The word "unsuspend"does not exist.
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/

**Comment by DrTom** [comment]
Suspension in inventory-pool/users/:user 
* default not in edit mode
* inline edit on click

**Comment by DrTom** [comment]
I believe what is pushed to master and on test resolves now all of this or makes it not applicable anymore.
