### ISSUE TITLE
User Page in Inventory Pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1002]
- Make suspension fields shorter, so Roles and Suspension fit next to each other. 
- Button "Suspension" is not needed because editing suspension is already enabled when navigating to the users page. 
- If a role via groups is listed, write "via the group XY EDIT". It's much easyier then for the eye if all buttons are in the end of the line. 
- The reason field of the section "suspension" can be smaller.

https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/f23ca963-a2d5-59db-bef8-9998ba40520d

**Comment by DrTom** [comment]
All resolved or not applicable any more.
