### ISSUE TITLE
Group page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1003]
Remove button should be yellow
https://test.leihs.zhdk.ch/admin/groups/6e062a15-72cf-4179-b737-bd49af07582a/users/?page=1&membership=yes

Search field is too short:
https://test.leihs.zhdk.ch/admin/groups/

![Bildschirmfoto 2021-01-14 um 21 28 28](https://user-images.githubusercontent.com/3356016/104645401-4ca3c980-56af-11eb-9a4d-bcf906603f98.png)

What does the helping text on field "Org Id" mean? --> true or false?

**Comment by DrTom** [comment]
Color and search field fixed. 

Org ID 
empty: any
true: has a org id
false: does not have a org id
value: exact match

I very rarely use the org filter; e believe we can just remove it?
