### ISSUE TITLE
Entitlement Group

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1005]
Remove the colum "Member" on the list https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b582d569-05c1-5d60-aeb8-b67a10bb2957/users/?account_enabled=&is_admin=&org_id=&page=1&per-page=50&term=&membership=member

The group names are missing on this list: 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b582d569-05c1-5d60-aeb8-b67a10bb2957/groups/?page=1&per-page=50&org-member=&term=itz&including-user=&membership=any

Would be a huge help if the user could search for a specific user (or model) included in a entitlement group.
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/

**Comment by DrTom** [comment]
I kept the column Member. We could remove it but some tests depend on it and I believe the information is useful. 
We can remove it later but the tests need refactoring and more over they get more complicated. 

I added the include-user filter but I don't know how the model filter should look like.
