### ISSUE TITLE
Legacy tab Users

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1006]
- [x] When pressing the "edit" button (on all role tabs) navigate to the users page in admin section. 
User:
From https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users
To https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/f23ca963-a2d5-59db-bef8-9998ba40520d
- [x] Delegation:
To https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/8b340513-d63a-4305-b301-7f730dd0aa75

- [x] Same behaviour from this page (navigating to user and delegation page editing the user or delegation): 
https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/search?search_term=weisskopf

- [x] And same from here:
https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/search/users?search_term=weisskopf

---

<del>Do we navigate the user to the admin section if he presses "new user" or "new delegation"? The functions do not exist yet in Admin section.
https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users
</del>

**Comment by eins78** [comment]
solution for last item, as discussed:
* on `Manage > Inventory-Pool > Users` page, add a "Create User" button
* opens` Manage > Users > New` form, with parameter `for_pool=$id`
* the form shows a notice "Creating a new user for pool XXX. Roles can added after saving"
* after saving, redirect to `Manage > Inventory-Pool > Users > User # Roles`

**Comment by eins78** [comment]
Users and delegations are still not strictly separated (in legacy-manage and new-admin) and in new-admin they are split between users and delegations views.
So for now the menu offers all options: delegations have a link to both views in the new-admin.
It has the added benefit that in "mixed" lists, one can check quickly if a line is a delegation ;)

![Screen Shot 2021-01-21 at 19 55 23](https://user-images.githubusercontent.com/134942/105398574-ce04da00-5c22-11eb-9134-53bcc55c6ec6.png)

**Comment by eins78** [comment]
Also, the notice above the pool users list is now styled like the default notice, also everything is translated.

![Screen Shot 2021-01-21 at 19 59 20](https://user-images.githubusercontent.com/134942/105398885-2a67f980-5c23-11eb-8da0-99d347a4fc5d.png)

**Comment by eins78** [comment]
fix: also show menu for users with no access right!
