### ISSUE TITLE
Error: Could not find item or License with xxxx

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#101]
Having upgraded to 3.31.0 yesterday we're having a few issues with scanning certain items.  When we scan them we get this error:

![image](https://cloud.githubusercontent.com/assets/299919/10755223/374e3e30-7c94-11e5-86b5-cdfc58d2369d.png)

The item dies exist in the items table and the database consistency passes as all clear.  If we refresh the page the item appears in the order.

I'm still checking if there's anything consistent about the items this fails on, but its appears about a 30% success rate.

Oh...... and I think it's only happening the first time an item is scanned..... If i refresh the page, remove the item, I can scan it and it appears.  If I refresh the page after removing the item it fails again. 

Thanks,

Anthony.

**Comment by psy-q** [comment]
I tried to reproduce this here and did 10 scans and deletes, so far they all went well. What is the browser and browser version in use? We know we might have some issues with Safari, Internet Explorer and Edge because those are the least tested ones for us.

**Comment by AnthonyHunt** [comment]
hmm, ok.  This is via Firefox and Chrome on Mac.  And still seems to be manifesting itself.  I've just tried it on my brand new fork.  This has no problems with the database either.  Here's what a non working record looks like:

![image](https://cloud.githubusercontent.com/assets/299919/10880298/082a3592-8152-11e5-867f-d765816f95af.png)
![image](https://cloud.githubusercontent.com/assets/299919/10880302/14b8332c-8152-11e5-8ccd-465eeff423f4.png)
![image](https://cloud.githubusercontent.com/assets/299919/10880313/1e48e904-8152-11e5-9bbe-408e361dbf60.png)

**Comment by AnthonyHunt** [comment]
Ok, I can confirm that this is only happening with items already on a booking.  If I try to add a new item to the booking from directly scanning the bardcode; the item is added.  Any item already on the booking when the page is loaded results in the above error when scanned?

I'm guessing that theres a code difference in the lookup between a new item and an existing item?  Could this be related to a piece of js code missing? like the timline problem I had?

Ant.

**Comment by psy-q** [comment]
I don't think this is related to the timeline problem. I am hearing of a similar issue from another user and we'll try to investigate it this week. It might be that an issue with the item lookup was introduced in one of the recent versions.

**Comment by AnthonyHunt** [comment]
Happy to email you a database if you need.

Ant.

**Comment by psy-q** [comment]
For the other party that also seemed affected, it turned out not to be that problem (they were using an older version of leihs that had a bug that would not show all possible models after a scan).

**Comment by AnthonyHunt** [comment]
Git Hub seems to stopped emailing me updates.... oh ok. We are at 3.21.1 as far as i can tell having checked the commits and the code.  Is there anything I could look for that could point to stale code?  This is however a completely fresh install from our previous erroneous one.  Happy to send a DB.

**Comment by AnthonyHunt** [comment]
fixed in current release
