### ISSUE TITLE
logo_url works again -> check leihs instances if it looks ok

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1014]
`settings.logo_url`, meaning the Logo-URL which one can set in the settings was not shown in the legacy navbar. This is fixed now. For some leihs instances it may not look nice, they would notice now. Example: FFZH.

Check it and notify the respective organisation.

**Comment by nadjaweisskopf** [comment]
@nimaai could you please describe the steps how I can upload an image?

**Comment by nadjaweisskopf** [comment]
- either upload the picture online and place an URL - which is the best solution
- or place the image in a specific folder
