### ISSUE TITLE
Feature-Refactoring: Automatic customer rolle for pools

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1016]
Wie besprochen im https://madek.slack.com/archives/D03F8H2FW/p1611156747001300

To Do:
* neue Gruppe “All users”
* der alte trigger verschwindet anstatt wirkt er auf “All users”
* alle Pools die das Häkchen gesetzt Haben: jeder der nur Customer ist ist nichts mehr und dafür wird diese Gruppe dem Pool zugeordnet
* das Häkchen Feature wird entfernt

Irgendwann müssen wir noch den Pools hinterher putzen wenn die nicht mehr das mit dem Häkchen wollen; mit dieser Gruppe können sie alles selbst machen.

**Comment by nadjaweisskopf** [comment]
Deploy before/with Admin-Enhancements go live

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/pull/1020

**Comment by nimaai** [comment]
https://github.com/leihs/zhdk-sync/issues/2

**Comment by nadjaweisskopf** [comment]
all automatic, nothing to be done manually
