### ISSUE TITLE
new admin: "Edit User Data" button when viewing user in inventory pool

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1019]
On `/admin/inventory-pools/:pool-id/users/:user-id` it would be nice to have a nav item to directly edit the user. 
It could just link to `/admin/users/:user-id`, but similar to #1013 it could also be `/admin/inventory-pools/:pool-id/users/:user-id/edit`.

<img width="1076" alt="Screen Shot 2021-01-21 at 17 16 33" src="https://user-images.githubusercontent.com/134942/105379882-950e3a80-5c0d-11eb-8b0c-a9e92339381e.png">

--

Background: We will link to the new admin section from the "legacy" user list when managing an inventory pool (#1006). 
![Screen Shot 2021-01-21 at 17 21 38](https://user-images.githubusercontent.com/134942/105379448-20d39700-5c0d-11eb-9acc-ce7c7d680073.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/bc5583bccfc7daee5962b6b879563a3040b21702
