### ISSUE TITLE
Scale user photos so they look uniform

### ISSUE THREAD

**Issue by psy-q** [leihs/leihs#102]
Extracted from @AnthonyHunt's comment on #93: Can the image be set to scale properly? like it does in the toolbar? The images that are stored are all sorts of sizes (not done by us) and it would be great if they could be set to a size.

**Comment by psy-q** [comment]
[Added to the ZHdK's Pivotal Tracker](https://www.pivotaltracker.com/story/show/110956416), but this is no guarantee that this will get done anytime soon. If you want to pick up this ticket, please comment in here before you start work, then I'll remove it from the ZHdK's Pivotal again.

**Comment by nadjaweisskopf** [comment]
Ask Tom if this problem is solved with newest API development

**Comment by nadjaweisskopf** [comment]
In future the picture will have a fixed size - we are currently on other implementation concerning this matter. Please view future release texts.
