### ISSUE TITLE
Timeline not displaying

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#103]
Since the update last week the timeline appears to have stopped working with the error:

F, [2015-11-02T10:57:51.729960 #8667] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/scripts/l10n/en/timeline.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/scripts/l10n/en/labellers.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/timeline-bundle.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/timeline-bundle.css"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/timeline-bundle.css"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/scripts/l10n/en/timeline.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

ActionController::RoutingError (No route matches [GET] "/assets/simile_timeline/timeline_js/scripts/l10n/en/labellers.js"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

looking at the compiled assets these file do appear to be missing: 
![image](https://cloud.githubusercontent.com/assets/299919/10880482/61bdc942-8153-11e5-965f-d9efc15fb218.png)

I've deleted the assets folder and recompiled it:
  RAILS_ENV=production bundle exec rake assets:precompile

but still have the same error.

Any thoughts?

Thanks.

**Comment by psy-q** [comment]
This seems to be an issue in newer Rails versions, perhaps try this workaround in your leihs directory:

```
cp -r vendor/assets/javascripts/simile_timeline/timeline_js public/assets/simile_timeline/
```

Then reload the server (if using Phusion Passenger);

```
touch tmp/restart.txt
```

**Comment by AnthonyHunt** [comment]
This has worked. Thanks.  I'll make a note in my deployment/upgrade docs too.

Ant.
