### ISSUE TITLE
Add "suspension" button to delegation in new admin

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1035]
@DrTom @nimaai

**Comment by DrTom** [comment]
Was that not "cancle" suspension?

**Comment by DrTom** [comment]
No something different entirely ;-)  
https://github.com/leihs/leihs/issues/1039

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f4c5cfc2628ffe0425b907ce855d0358f1a78f6d
