### ISSUE TITLE
Disallow Edit of Users/Delegations in Legacy

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1036]
- [x] controller
- [x] dropdown menu user line index
- [x] dropdown menu user line search results

**Comment by nimaai** [comment]
I will also remove the "New user" and "New delegation" buttons, ok? @eins78 

Also I we need a second banner for delegations with the link to new admin on the users index page (legacy).

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/8b42bab597d25beadfbce4f2ce7e20cc3b02a8fa

**Comment by nadjaweisskopf** [comment]
The new user and new delegation buttons will lead to the Admin-user and -delegation pages. So no change here.
But the edit user and edit delegation button leading to the edit pages in legacy shall be removed. We only provide an edit button leading to the admin-view pages of the user and the delegation.
