### ISSUE TITLE
ZHdK: cleanup users before enhancing sync job

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1043]
There are still many old user accounts in the DB, which leads to errors in the sync that need to be solved manually.

task: for all `users` where `organisation` is `local` (e.g. not `zhdk.ch`), if the `email` ends in `@zhdk.ch`: delete `email` field, and add the old value to `extended_info` hash under the key `old_email`.

**Comment by eins78** [comment]
had a quick look. affects 1708 users. `.*@zhdk.ch$` and not just `.*zhdk.ch` is an important distinction, because it would match `@netzhdk.ch` users.

```sql
SELECT * FROM "users"  WHERE ("organization" = 'local') AND ("email" ILIKE '%@zhdk.ch');
```

**Comment by eins78** [comment]
@nimai script vorbereiten und auf staging testen. kann sql oder ruby sein.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/147e0c487856dadccd0ec4df9ec76051ceacb906

@eins78 just in case, please have a look. 🙏
