### ISSUE TITLE
serve user images via http

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1047]
currently user images are directly embeded in HTML as base64 strings, as they are stored the same way in the DB.

instead, those should be served from an HTTP endpoint, so that caching etc applies.
when doing so, we can also take care of image transformations like resizing to smaller sizes (instead of running a standalone service like [`imgproxy`](https://imgproxy.net) which is more generic than we need and has overhead we dont want).

- [ ] decide which service (suggestion: `my`)
- [ ] implement http endpoint (see new borrow)
- [ ] integrate `libvips` for image transformations (via a nodejs wrapper)

**Comment by DrTom** [comment]
* +1 for `my` 
* not sure yet about `libvips`,  maybe yes; maybe there is something more convenient and performant enough 
* we can make browser caching very efficient if we use the `img_digest` as part of the URL and set the corresponding headers; determining URL is slightly more complex but seems within reason;

**Comment by eins78** [comment]
Note about the caching: there are actually 2 levels to consider. 
* apache server: keep the resized files so dont calculate them for every single request
* browser cache: use the right headers so we dont even get any requests for already downloaded images

And yes, the `digest` should be used. Maybe when we change the fields around (only one large image instead of big and smalll) we can make that even better (like having at least an autoincrementing integer in there,  if its not filled out by the API client).

**Comment by neoheat** [comment]
won't change
