### ISSUE TITLE
Resetting suspension is buggy

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1050]
CASE I: When resetting the suspension the reason is not deleted. 

Steps to reproduce: 
1. go to pool
2. show a user
3. suspend user with a reason
4. save
5. edit suspension
6. reset suspension by pressing button on the right
7. save
8. date has been deleted but text is still shown
9. edit suspension --> text is not shown anymore

same behaviour when pressing "reset" directly without editing. 

CASE II: When saving a suspension without a reason the suspension is not saved. The user receives an OK message but the user is not suspended. I couldn't always reproduce this bug.

**Comment by eins78** [comment]
can not reproduce anymore
