### ISSUE TITLE
Error when showing delegations page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1052]
When navigating to the delegations page in Admin I get an error. 

I believe it has to do with the roles. If the delegation has no role assigned, the error pops up. 

How to reproduce:
1. go to pool
2. go to users list
3. Press button "Delegation anzeigen" 
4. I get an error

<img width="1071" alt="Bildschirmfoto 2021-03-08 um 11 22 02" src="https://user-images.githubusercontent.com/3356016/110309164-4a9c1e00-8001-11eb-87dc-c63b6fff73d4.png">

https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/87f5344b-7ae4-4dfc-bd60-57be698cca0f

**Comment by eins78** [comment]
in legacy: 
* when delegation has "no access", link to the `index` views
* link by name-filter <https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/?membership=any&page=1&term=XXX&including-user=>

better would be to link by uuid, but need extension in admin (new ticket)

**Comment by eins78** [comment]
@nadjaweisskopf 

* in the users list, for the example case the link now points to https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/?membership=any&page=1&term=19.004.EXT%20Schmocker%20Helferei%20
* I also looked if the same fix is needed in the search results, but Delegations dont appear at all in the search results, even in the "Users" tab, which has the heading "Users/Delegations". Now I dont know if the feature or the heading is wrong: https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/search/users?search_term=Schmocker

**Comment by nadjaweisskopf** [comment]
@eins78 
- The first link in the comment above still produces an error. Should this already be solved?
- To the second question: in the search results, only delegations appear which at least have the role "customer"

**Comment by eins78** [comment]
> @eins78
> 
> * The first link in the comment above still produces an error. Should this already be solved?

to be clear:
* the link in *your* first comment (start of the issue) still does not work and never will, but we wont use this link anymore
* instead, now the link in [_my_ last comment](https://github.com/leihs/leihs/issues/1052#issuecomment-805811707) is now used and works. If you got an error you might need to log in. If you get a different error, please attach a screenshot so i can investigate.

> * To the second question: in the search results, only delegations appear which at least have the role "customer"

ok, then this problem can not happen for delegations in search results, we dont need to do anything.

**Comment by eins78** [comment]
@nadjaweisskopf will be on `test` soon
