### ISSUE TITLE
borrow: Add a "reset filters" affordance when there are no search results

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1054]
- extend the "no results" message 
- only if there are any filters set
- triggers same event like the "clear" button in the filter panel

**Comment by neoheat** [comment]
to be discussed.

<img width="1042" alt="Bildschirmfoto 2023-06-26 um 13 37 07" src="https://github.com/leihs/leihs/assets/123965725/d9926648-ed7d-41e4-bf76-0a9821c4d4ca">
