### ISSUE TITLE
admin: find by UUID

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1061]
in new admin, for Users, Delegations, … preferably everywhere.
special case: when UUID is entered into "fuzzy" search, match by DB id.

**Comment by nadjaweisskopf** [comment]
When adding an ID in fuzzy termin in audited changes, I get an error: 

![grafik](https://user-images.githubusercontent.com/3356016/205160989-d0af48a8-cfd8-48f6-9733-b9309ad58fd5.png)

How to reproduce: 
- go to new admin
- go to audited changes
- enter UUID in fuzzy term field
- error pops up

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/cc8196a8195fad657b350540234927e2917ed8c6
