### ISSUE TITLE
manage: expert search broken for "checkbox" fields

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1066]
The field type "checkbox" is not implemented in the expert search and crashes when such a field is selected.
Same is true for the Inventory Helper, since the same code to handle fields is used for both.

thrown error: ` "Unexpected type: checkbox"`
source: https://github.com/leihs/leihs_legacy/blob/7ba7b4ee0d9dbb30871b2a3e6f3d9a9b8cb47704/app/assets/javascripts/components/expert/field-switch.jsx#L6

**Comment by nimaai** [comment]
as discussed with @neoheat : 

don't implement this in legacy. will be done in the new inventory app.

_workaround_: remove all custom fields of type `checkbox` from the select box in inventory helper and advanced search.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d45ca2cc63bea7f11be84c4ab8a77fda54f44a87

**Comment by neoheat** [comment]
tested positive
