### ISSUE TITLE
Unable to add inventory

### ISSUE THREAD

**Issue by mozqto** [leihs/leihs#107]
I am using the latest version 3.32.1.
But I have a problem, I am unable to add inventory as an inventory manager.
Whenever I click save, it reloads the page with all the information deleted.

**Comment by psy-q** [comment]
Are you running in production mode? What appears in `log/production.log`? Does adding other things (creating inventory pools etc.) work?

**Comment by mozqto** [comment]
Hi psy-q

As the inventory manager, creating inventory pool and adding group works but others doesn't.
As the admin, everything works.

Attached is the production.log.

[production.log.txt](https://github.com/leihs/leihs/files/86611/production.log.txt)

**Comment by mozqto** [comment]
I also tried to import the csv file that I exported from the demo but it doesn't work.
The message below appears.

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

**Comment by psy-q** [comment]
In the log it looks like it's hitting uncompiled assets. Did you precompile the assets?
```
RAILS_ENV=production bundle exec rake assets:precompile
```
Are you running behind e.g. Phusion Passenger on Apache or are you starting the Rails server on the command-line?

**Comment by mozqto** [comment]
Yes, I've precompile the assets.

**Comment by mozqto** [comment]
I am starting the rails server on the command-line

**Comment by mozqto** [comment]
But this message appears whenever I start the rails server.

Warning: fuzzy message was used.
  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'
Warning: fuzzy message was used.
  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'
Warning: fuzzy message was used.
  : msgid 'Delegation'
Warning: fuzzy message was used.
  : msgid 'A package item must belong to a package model'

**Comment by psy-q** [comment]
The warning is harmless, that's just because some of the strings haven't been translated yet. Is there any error in your JavaScript error console log in your browser when you press save?

**Comment by mozqto** [comment]
GET http://10.19.1.188:3000/assets/manage-a9d26c6f9087ef90e2a67649d01e67d7.js 
new?model[product]=&model[version]=&model[manufacturer]=&model[description]=&model[technical_detail…:200 Uncaught TypeError: App.TopBarController is not a function

**Comment by mozqto** [comment]
TypeError: App.TopBarController is not a constructor new:200:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by psy-q** [comment]
I am still not able to reproduce this. What version of Ruby is  in use? Which distribution? Using rbenv, rvm, chruby or some other Ruby manager?

**Comment by nimaai** [comment]
> I also tried to import the csv file that I exported from the demo but it doesn't work.
 The message below appears.

> We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

The bug has been fixed and will be available in the next release.

**Comment by nadjaweisskopf** [comment]
I expect this issue to be solved by now? If not, please reopen the ticket.
