### ISSUE TITLE
Deployment instructions - Deployment errors

### ISSUE THREAD

**Issue by flh-Admin** [leihs/leihs#1075]
Please update the deployment instructions. Every time I try to install Leihs on a Debian 10 machine, it fails. There seem to be incompatibilities with the deployment script and the Debian repositories.

Maybe it is possible for you to provide a Docker image with Leihs?

**Comment by eins78** [comment]
Leihs version 6.0.0 has been release and the self-hosting GUIDE has been updated. It has been tested against Debian 10, but in case it still does not work for you please report and errors to this repository: https://github.com/leihs/leihs-instance/blob/943994496d0017a5dea03026dff08efa0b3e3350/GUIDE.md
