### ISSUE TITLE
Text korrigieren

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1076]
In den Gruppen eines Geräteparks sollte folgender Text stehen: 

**Die Gruppen werden im neuen Admin-Bereich verwaltet.** 

![Bildschirmfoto 2021-05-06 um 15 34 20](https://user-images.githubusercontent.com/3356016/117307154-9b54b980-ae80-11eb-9995-8fa92606e74c.png)

**Comment by eins78** [comment]
Du meinst den Text im blauen Kasten ersetzen, ja?

**Comment by nadjaweisskopf** [comment]
Ja genau. Der passt zu den Anspruchsgruppen aber wir sind ja hier nicht im Reiter der Anspruchsgruppen.
