### ISSUE TITLE
deploy: split up inventories

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1077]
* hosting inventory for `ausleihe.zhdk.ch` based on the template https://github.com/leihs/leihs-instance
* rename `zhdk-inventory` to `developer-inventory`
  * `test`- and developer servers stay there 
  * add more test servers (to check against different kinds of prod data)

open questions:
* in general, how should the hosting handle prod/staging servers. options:
  * 1 submodule per env? https://github.com/functional-swiss/leihs.uni-muster.ch_hosting/tree/mfa/fg-inv/deps-by-env/prod
  * 1 subodule total, but dont use the checked-in version of the leihs submodule. instead persist it in some other config and check that out that version in a script before deploy 
  * use branches? (like `deploy/prod` and `deploy/staging`, have not thought it through) 

maybe: rename the servers to make them more understandable for non-developers?
* `test` -> `dev`, `canary`, …?
* `staging` -> `next`, `preview`, …?

**Comment by neoheat** [comment]
@DrTom is this still something we plan to change?

**Comment by DrTom** [comment]
@neoheat you can close this ticket. We implemented the more important parts of it a while ago.
