### ISSUE TITLE
Missing mail templates

### ISSUE THREAD

**Issue by DenAutonomePirat** [leihs/leihs#1089]
#### Expected behaviour
At admin/inventory_pools we try to create a new pool, expected behavior is that the new pool is created - given the needed info. 

#### Actual behaviour
Missing mail templates pops up, nor are we able to edit mail templates.

#### Steps to reproduce
logged in as admin go to admin/inventory_pools fill form -> create  ---> BAM
same for admin/mail_templates/order/approved -> BAM

Is it possible to fix this staying on version 4.19.5? 

![Screenshot from 2021-05-31 12-04-56](https://user-images.githubusercontent.com/8817337/120181183-fcb44200-c20c-11eb-8659-4fc8a3c88bc7.png)

#### Specifications
- Leihs version: 4.19.5
- Browser version: chrome
- MySQL/PostreSQL version: ?

**Comment by eins78** [comment]
> Is it possible to fix this staying on version 4.19.5?

No, older versions of Leihs (before v6) are not supported anymore and should be upgraded. See the self-hosting docs: https://github.com/leihs/leihs-instance/blob/master/GUIDE.md
