### ISSUE TITLE
fresh installed 3.32.1 only admin works

### ISSUE THREAD

**Issue by stellaf** [leihs/leihs#109]
Fresh installed Leihs 3.32.1 only "Admin" works. The "Borrow", or "User data", "My document" will direct the user back to login screen.
used:
Centos7, passenger5.0.23, Ruby 2.4.8, RVM 2.3.0.

one more bug: the field has no any border, and the border is white color on the white background.

**Comment by stellaf** [comment]
sorry, has to add the user to the inventory pool first. my fault.
the other problem still remaining. but I will close this issue and create another one.

**Comment by psy-q** [comment]
By the way, what do you mean by Ruby 2.4.8? The latest Ruby available is 2.3.0, but leihs currently supports only 2.1.x (e.g. 2.1.7)

**Comment by stellaf** [comment]
Hi
The Passenger 5.0.23 is only compatible with Ruby 2.4.8, the RVM 2.3.0 has
Ruby 2.5.1, so I have to use Ruby 2.4.8 to get the passenger 5.0.23 work.

Regards
Stella Fredö
