### ISSUE TITLE
New borrow crashes when looking at returns

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1093]
https://test.leihs.zhdk.ch/app/borrow/returns

As user uvanbins (urs.vanbinsbergen@zhdk.ch)

```
ERROR :(
RELOAD

{
  "message": "Non-nullable field was null.",
  "locations": [
    {
      "line": 10,
      "column": 7
    }
  ],
  "path": [
    "returns",
    0,
    "reservations",
    0,
    "model"
  ]
}{
  "message": "Non-nullable field was null.",
  "locations": [
    {
      "line": 10,
      "column": 7
    }
  ],
  "path": [
    "returns",
    0,
    "reservations",
    1,
    "model"
  ]
}{
  "message": "Non-nullable field was null.",
  "locations": [
    {
      "line": 10,
      "column": 7
    }
  ],
  "path": [
    "returns",
    0,
    "reservations",
    2,
    "model"
  ]
}
```

**Comment by eins78** [comment]
@nimaai also look at "returns" in legacy borrow - the model images are also broken. maybe a permissions issue?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/375aa501f157746f9d4b3fe5e258a8f33707093f

@urs-van-binsbergen please test after the [deploy to test is over](https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/7318ab46-bf95-4ad0-818a-2aa4ead50481)

**Comment by urs-van-binsbergen** [comment]
https://test.leihs.zhdk.ch/app/borrow/returns works now as excpected (no error, JSON of my returns is visible).
