### ISSUE TITLE
new borrow API: "Ausleihen" data

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1094]
### background

The design concept shows customer orders, pickups and returns in a single combined "Meine Ausleihen" view.

This does not match the "old" data model and therefore not represented in the API. While we could combine the data in a query for this view, it might be simpler to define a new "entity" (aka "model" or "type" in the API).

The main mis-match is that customers can lend things without having ordered them. Common Scenarios: Spontaneous visit by a customer at a lending desk; lending out "unreservable" items; issued devices ("Mitarbeitergeräte").

This flexibility can also lead to confusion, both on the customer and staff side): Customers can have "returns" without having a corresponding order (but i could find it under Documents/Contracts).
Staff can "pepare a handover" which is handled like a reservation (regarding availabilty) but also has no order and can only be found in the UI by opening the correct users' handover view.

### proposal

* combine the data for all customer orders + all "orderless" reservations.
* mark in the UI where it comes from

### open questions

- [ ] english term for "Ausleihen". Should be non-confusing for leihs novices and experts but also not clash with existing terminology 
- [ ] GraphQL: schema reuse with Interface, Units, …?

**Comment by eins78** [comment]
examples from current views (with my real data)

<img width="1005" alt="Screen Shot 2021-06-11 at 12 52 41" src="https://user-images.githubusercontent.com/134942/121685628-73c8c080-cac0-11eb-8f8f-3cd9e2c8b2c4.png">

<img width="999" alt="Screen Shot 2021-06-11 at 12 52 52" src="https://user-images.githubusercontent.com/134942/121685636-762b1a80-cac0-11eb-9a34-d3a1e9180d94.png">

<img width="837" alt="Screen Shot 2021-06-11 at 14 19 05" src="https://user-images.githubusercontent.com/134942/121685648-79bea180-cac0-11eb-8333-8c8125180968.png">

**Comment by eins78** [comment]
@nimaai as discussed:

* "orderless orders" should be separated by contracts (if they exist)
  * when not yet picked up: all reservations from the user that have no order are combined as one single "orderless order", they cant be grouped by anything because there are no contracts
  * when picked up: show 1 "orderless order" per contract

prod data example:
* in the screenshot above, A-E should be separate "orders".
  * A: orderless order `A`
  * B: orderless order `B`
  * C: orderless order `C`
  * D: customer order `5c9b9b08-3d9a-4476-b871-b48aa65654cf`
  * E: customer order `cbeadf82-6a31-4954-bafe-d63b6708e235`

**Comment by nimaai** [comment]
@eins78 Do we want to at least `GROUP BY reservations.inventory_pool_id` for `approved` reservations without contracts and orders?

**Comment by eins78** [comment]
> @eins78 Do we want to at least `GROUP BY reservations.inventory_pool_id` for `approved` reservations without contracts and orders?

I think you mean that they would appear as 2 unified orders, 1 per pool? I think that should be that case (but I am not 100% sure that they should be listed at all).

**Comment by eins78** [comment]
> but I am not 100% sure that they should be listed at all

🤔 I checked the current behaviour and luckily "direct reservations" (even with no item assigned) are already listed under pickups, so its consistent to also include them in the "unified orders", and they should be grouped by inventory pool.

<img width="1054" alt="Screenshot 2021-07-06 at 17 16 04" src="https://user-images.githubusercontent.com/134942/124625550-31579100-de7e-11eb-86dd-25b5886fa047.png">

**Comment by eins78** [comment]
@nimaai check contract with id `603b1b61-988e-5335-b0b8-f75ea7a046b4` (has deactivated pools!)

**Comment by eins78** [comment]
@nimaai include all fields of `InventoryPool` everywhere

**Comment by nimaai** [comment]
@eins78 how to deal with a customer order which got extended with orderless reservations? in such a case we have a contract, which includes both types of reservations. i think we can't "extract" them from the contract and "create" a stand-alone customer order for them, but on the other hand if we don't do that, there won't be any customer order which has the orderless reservations under its `reservations` field (one would still find them under its `contracts -> reservations` field though.

**Comment by eins78** [comment]
@nimaai In such cases I'd expect there to only be 1 order (because its one "lending" from the customers perspective. I see you point about not having those reservations by part of an order, but it seems to me that is a minor detail that we can solve in the API. 
Lets revisit soon this when implementing the view, but I am thinking of something simple like an `order.allReservations` field. Another possibility would be to "create" an "orderless pool-order" (inside `order.subOrdersByPool`) but I hope we dont need this complication.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c284cc8e4f59cb556a89c7071e55e54780f154fa
