### ISSUE TITLE
legacy: changes to mail templates are not applied until app is restarted

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1095]
* in `/manage/$pool/mail_templates`
* should be fixed or documented
* i dont see any explicit caching
  * [app/models/mailer/order.rb](https://github.com/leihs/leihs_legacy/blob/6f1a2033a02ef1e2f645a5fe1acb965069d9c5a4/app/models/mailer/order.rb#L53)
  * [app/models/mail_template.rb](https://github.com/leihs/leihs_legacy/blob/6f1a2033a02ef1e2f645a5fe1acb965069d9c5a4/app/models/mail_template.rb#L95)
* because there is only 1 action where they can be updated, maybe a simple fix could be to "reload" them after saving?

**Comment by nimaai** [comment]
Could not be reproduced.
