### ISSUE TITLE
[SOLVED] Fields have white borader, invisible in Microsoft Internet Explore

### ISSUE THREAD

**Issue by stellaf** [leihs/leihs#110]
Fresh installed Leihs 3.32.1 Centos7, Apache2.4.6, passenger 5.0.23, Ruby 2.4.8, RVM 2.3.0.
Fields have white borader, invisible in Microsoft Internet Explore.
The border is white color on the white background.

The fields look normal in the Chrome browser.

**Comment by psy-q** [comment]
Which version of MSIE is this? We do not officially recommend MSIE, but it should work in Microsoft Edge. Does the problem appear in Edge as well?

**Comment by stellaf** [comment]
MSIE version 11.0.9600.18163
updated version 11.0.27 (KB3124275)
on Windows 7 64bits.
fields show 
![login](https://cloud.githubusercontent.com/assets/6710014/12556953/d1a31fce-c388-11e5-888c-93993cb97a96.JPG)
no border, and page have light gray border.

**Comment by stellaf** [comment]
where is the css file that define the boader for entire leihs application?

**Comment by psy-q** [comment]
That's reasonably old CSS and might get replaced with Bootstrap at some point (and Bootstrap should have polyfills to make it work even in older MSIEs). I think it's not worth investing time in this right now depending on when the redesign to Bootstrap might come along. I will check with people at ZHdK if they plan to do that soonish, otherwise it's of course open for anyone to start with.

**Comment by stellaf** [comment]
Thank you, please do provide us status for the Bootstrap for Leihs.

**Comment by stellaf** [comment]
In these two files
app/views/layouts/_head.html.haml ,
engines/leihs_admin/app/views/layouts/leihs_admin/admin.html.haml 
the code 
%meta{:"http-equiv" => 'XA-UA-Compatible', :content => 'IE=edge'}
shall be 
%meta{:"http-equiv" => 'X-UA-Compatible', :content => 'IE=edge'}

After changed it, then the application stylesheet is working properly in the MSIE. 
Thanks!

**Comment by psy-q** [comment]
Thanks! I've commited 833d4af8ac13b0f5822475b6c5172112e9374504 to fix this but it's not sure which version of leihs this will end up in.

**Comment by nadjaweisskopf** [comment]
Please reopen if this is still a problem.
