### ISSUE TITLE
Live Demo server down

### ISSUE THREAD

**Issue by NevPalmer** [leihs/leihs#1103]
It appears that the Live Demo server has a fault.

If I navigate to https://demo.leihs.zhdk.ch/ which returns an almost blank page with the text "Unclassified error, see the server logs for details."

I have attempted using Firefox 89.0.2 (32-bit) and also Chrome 91.0.4472.114 (Official Build) (32-bit)

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by eins78** [comment]
thanks for the notice, it works again.
