### ISSUE TITLE
Terms of Use and Privacy Statement

### ISSUE THREAD

**Issue by Tettsch** [leihs/leihs#1104]
Hello,
we would like to set up leihs at our university department but we have to add Terms of Use and a Privacy Statement. Is there a possibility to do that at the bottom of each page in leihs? 

#### Expected behaviour
- Modify the links in the footer within the Admin Panel

#### Specifications
- Leihs version: 6.1.1

**Comment by eins78** [comment]
There are no settings to configure the the bottom links. We currently have no plans to implement this but would accept pull request.

For "Terms of Use" there is a setting to show a link to some externally hosts "lending terms" and requires acceptance by ticking a checkbox _for each order_. Maybe this an option for you. For details on how to use it, see this feature spec: https://github.com/leihs/leihs-integration-tests/blob/8a7e757c176c3ef1c86239855b2d5052de708cb6/spec/features/settings/lending_terms_acceptance.feature
