### ISSUE TITLE
No mails sent when submitting/approving/... an order

### ISSUE THREAD

**Issue by MatKDA** [leihs/leihs#1105]
#### Expected behaviour
After submitting/approving/rejection/receiving an order, I expect to be notified by mail.

Not tested: reminder.

#### Actual behaviour
After submitting/approving/rejecting/receiving an order, no mail is sent.

However, "password reset" works, so mail delivery works.

#### Steps to reproduce
Customer: Log in as customer, submit an order.
Or as Lending manager: Approve/Reject an order.

#### Specifications
- Leihs version: 6.1.1 (updated from 5.3.1)
- Browser version: Firefox 78 ESR, Edge 91

As always, I kindly appreciate any help.

**Comment by eins78** [comment]
things to check:

* in the inventory, have you set `leihs_send_mails: Yes`? (see example config https://github.com/leihs/leihs-instance/blob/cb847365197c94313c282bd1e7fe99452be0dffa/examples/host_vars_example.yml#L8)
  this applies to all mails _except_ the passwort resets.

* was this setting applied correctly? 
  ```
  root@leihs:~# grep LEIHS_SEND_MAILS /etc/systemd/system/leihs-legacy.service 
  Environment=LEIHS_SEND_MAILS=True
  ```

**Comment by MatKDA** [comment]
Thank you for your quick reply. I think the settings seem to be ok:

Inventory:
```
$ grep leihs_send_mails host_vars/DOMAIN.yml
leihs_send_mails: Yes
```
and leihs:
```
$ grep LEIHS_SEND_MAILS /etc/systemd/system/leihs-legacy.service 
Environment=LEIHS_SEND_MAILS=True
```

**Comment by eins78** [comment]
In that case, there should be some kind of error in the logs when the mail is attempted to be sent:

```
journalctl -efu leihs-legacy.service
```

In general, if you're having problems with either configuring or debugging the mail sending in Leihs, I'd recommend to install a local MTA on the server. For example, you could install abnd configure [`postfix`](http://www.postfix.org) and set the `smtp_settings.address` in Leihs to be `localhost`.

**Comment by MatKDA** [comment]
Hello,

thank you, your hint (```journalctl -efu leihs-legacy.service```) was very helpful.
In the logs, there was this line ```leihs-legacy[2708]: uninitialized constant OpenSSL::SSL::VERIFY_0```.
So I have tried several values for "openssl_verify_mode" in the SMTP Settings (was "0"). After setting the value to "NONE" mail delivery is working.
Perhaps it’s possible to check the SMTP settings when saving?

Thank you for your kind support!
Matthias
