### ISSUE TITLE
db translation: add translations to prebuilt artefact

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1108]
part of #1072 

right now only used in new borrow (so the problem is not relevant for regular deploy as long as new borrow is not stable).

* problem: currently the "extract translations" step runs in deploy
* soultion: it should be part of the build step (`bin/build`) be in the "prebuilt artifact"
  * *either* make it part of the `jar` (maybe `java -jar target/leihs-borrow.jar get-translations` could print them to stdout? or there is an easy way to extract resources from a `jar` since they are also just a `zip`?)
  * *or* change prebuilt/cached artefact to not be a `jar`, but a `tar`, with the translations file and the `jar` inside

I kind of prefer the first solution because everything else is contained in the `jar`, but both are fine.

There is currently this workaorund in deploy: https://github.com/leihs/leihs_deploy/commit/f09fde2e8e160c3c6e39a3eff813007c097b8b6b (which can stay as is, we only want to add translations for the apps that are actually installed)

**Comment by nimaai** [comment]
- [x] borrow (Matus)
- [x] int-tests (Matus)
- [ ] deploy (Max)

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/ab7f160a46369f9a499afdbfb662e299b211d103
