### ISSUE TITLE
api: cancel an order

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1109]
- new status for orders and reservations "cancelled" 
- allow cancellation as long as order is not (partially) approved or rejected

**Comment by nimaai** [comment]
> canceled / cancelled (AE / BE)

Which one do we want to use internally @eins78?

**Comment by eins78** [comment]
@nimaai when in doubt always use AE for consistency

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/005fe503de5aa598bc4040b059c2e3ce9fe82d89
