### ISSUE TITLE
new borrow: api fixes

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1110]
- [x] `contract.createdAt`
   see https://github.com/leihs/leihs-borrow/commit/a23e60c00dcb51ade7c1916fe6372dd518cad077#diff-84cb9febcb4c371ed3fd038123c5f074e04e0b6c113f556475baa449395152c4R27-R30

- [x] `contract.printUrl` link to legacy contract#show 

- [x] `contract.inventroyPool` nullability ( should be listed even if `isActive=false`)

```
query getCurrentUserShow {
  currentUser {
    user {
      contracts {
        edges {
          node {
            inventoryPool { id }}}}}}}
```

=>

```
  "errors": [
    {
      "message": "Non-nullable field was null.",
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "path": [
        "currentUser",
        "user",
        "contracts",
        "edges",
        11,
        "node",
        "inventoryPool"
      ]
    }
  ],
```

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f922341ce78692968826c07442b46ab9e3408e7d
