### ISSUE TITLE
Fix deploy to staging

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1112]
https://ci.zhdk.ch/cider-ci/ui/workspace/trials/c2c3d3fb-3d22-4a65-9634-ecafd25bc37d

**Comment by eins78** [comment]
+ demo has the same problem with demo server, the "Reset Dump Demo" job is not triggered https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/f1affde8-1141-418a-b1d0-2e633cae1302

**Comment by DrTom** [comment]
I am a bit confused what is exactly not supposed to work here? 

Looks good to me https://ci.zhdk.ch/cider-ci/trees/f52981f1e5138eb902ff4c6d358834f1c2eaac0e

**Comment by eins78** [comment]
> I am a bit confused what is exactly not supposed to work here?
> 
> Looks good to me https://ci.zhdk.ch/cider-ci/trees/f52981f1e5138eb902ff4c6d358834f1c2eaac0e

Yes, you are confused ;) this is the wong project.

Have a look here, the last 2 trials i triggered manually but were never dispatched. May traits are missing?
https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/c5314c36-652d-421d-a145-0de05a75efcf

**Comment by DrTom** [comment]
Two things with that: 

* So it is not the triggers, but it is not dispatched? Yes most likely traits; can be tested without triggers. 

* In this particular case it says orphaned; either it is stale or there is no brach associated with the trigger. That should never work then.

**Comment by eins78** [comment]
I have now started a job for a more sensible branch and it is dispatching: https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/b8e3aac8-c991-49a2-a1f1-dec629bba44b

Maybe we were all confused and _there is no trigger_ for nightly deploy to `staging`? (Unlike Madek, hence the confusion).
If so, we can close this once the above job ran through.
