### ISSUE TITLE
theme: upgrade mobile theme to bootstrap 5

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1113]
https://getbootstrap.com/docs/5.0/migration/

- [x] split build env of regular and mobile theme @eins78 
- [x] migrate mobile theme to bootstrap 5 @urs-van-binsbergen 
- [x] implement new skin (could be new ticket) @urs-van-binsbergen

**Comment by urs-van-binsbergen** [comment]
Steps:
- [ ] fix bootstrap-theme-leihs build ok? only 1 error:
  - [ ] missing reference to mixin `bg-variant` -> trivial
- [ ] check/fix rendering in _leihs-ui_ Storybook components:
  - [ ] _Features_ (HomePage, LoginPage, PasswordReset)
  - [ ] _Components_ (DatePicker, Navbar)
  - [ ] _MobileApp_ (WIP)
- [ ] check/fix rendering in sub apps
  - [ ] _admin_
  - [ ] _procure_
  - [ ] _my_
  - [ ] _borrow_ (WIP)

**Comment by eins78** [comment]
decision: because we already splitted the theme into regular and mobile, we'll keep it simple and use bootstrap 5 in the mobile theme only. that we we can defer upgrading the regular theme until both themes are supposed to be combined anyways.
todo for me: split the theme even further (right now its 2 sass files in 1 project dir, but it needs 2 project dirs)

**Comment by eins78** [comment]
split is done

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/67be6fdb9a9cf366c0951643f25d82493d31372b
