### ISSUE TITLE
"Meine Ausleihen" prepare query & data

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1116]
- [x] extend schema, new type for "UnifiedOrder" (naming TBD)
  - [x] `:Order` -> `:Rental`
  - [x] `query orders` -> `query rentals`
- [x] nest in current user for convenience `current_user.user.unifiedOrders` (part of https://github.com/leihs/leihs/issues/1118)
- [x] API specs

- filters

  - [x] by "open/closed" states: "open" are unapproved + anything with a pickup or return, "closed" is all the rest
  - [x] by date from/until
  - [x] by pool
  - [x] by delegation (already implemented via the general delegations setup)
  - [x] by text (match string on model names, purpose, title, contract notes, *other text …*)

- "summary data" - check if we can reuse (deeply nested) fields or do we need to provide specialized fields for this purpose on the top level type
  - [x] "${totalDays} days from ${earliestStartDate} to ${latestEndDate}"
    - `totalDays: Int!`
    - `fromDate: Date!`
    - `untilDate: Date!`
  - [x] "1 of 3 inventory pools approved" , something like: "1 of 3 pools accepted, 1 rejected, 1 pending"
    - `approvedPoolOrdersCount: Int`
    - `rejectedPoolOrdersCount: Int`
    - `submittedPoolOrdersCount: Int`
    - `poolOrdersCount: Int!`
  - [x] "3 of 4 items picked up"
    - `pickupQuantity: Int!`
    - `totalQuantity: Int!` 
  - [x] "3 of 4 items picked returned"
    - `returnQuantity: Int!`
    - `totalQuantity: Int!`  

- sort
  - [x] `from_date` 

- more filters - not in design spec but needed to implement "pickups" and "returns" in the same view. could be a kind of "state". there will be links from other parts in the app to a filtered list (e.g. "Show all your pickups" -> `/borrow/orders?state=toPickup`)
  - [x] filter "with pickups" 
  - [x] filter "with returns"

### screens

| list             |  filter panel |
:-------------------------:|:-------------------------:
| <img width="298" alt="Screen Shot 2021-07-16 at 11 39 30" src="https://user-images.githubusercontent.com/134942/125927921-dd628c61-f6e3-46ff-9ae6-283aa244e667.png"> | <img width="306" alt="Screen Shot 2021-07-16 at 11 40 26" src="https://user-images.githubusercontent.com/134942/125927902-966dc676-129a-44d4-9fee-42a7883361b1.png"> |

**Comment by eins78** [comment]
zu beachten beim schema und den zusammenfassungen: die einzel-anzeige der bestellung zeigt die gleichen zusammenfassungen an, und zusätzlich dazu auch sehr ähnliche zusammenfassungen separiert pro pool und pro modell.

<img width="302" alt="Screen Shot 2021-07-16 at 14 11 14" src="https://user-images.githubusercontent.com/134942/125953174-fa5e3291-086d-4bda-8af9-d960f8b72577.png">

**Comment by nimaai** [comment]
@eins78 
> by pool

or "by pools" ? just to be on the save side I would say "pools", right? One can always ask for `[b8807edd-304c-47d9-ab24-86e53b1b34b0]`...

**Comment by eins78** [comment]
> @eins78
> 
> > by date from/until
> 
> do you have an example? not sure what you mean...

"show me all Rentals that happened between 2001-01-01 and 2002-01-01"

> 
> > by pool
> 
> or "by pools" ? just to be on the safe side I would say "pools", right?

yes! (`pool OR another_pool`)

> 
> > by delegation
> 
> If you mean that the `unified_customer_orders` should contain all from users and their delegations then this would bloat the complexity and performance quite a bit. I assume that switching the current user context as we do all over the app already should be enough.

yes, that what this is supposed to mean – show it for my user; or for my delegation (not multiple)

**Comment by nimaai** [comment]
>"show me all Rentals that happened between 2001-01-01 and 2002-01-01"

@eins78 What do you mean with "happened"? `customer_orders.created_at`, `contracts.created_at`, `reservations.start_date`, `reservations.end_date`...?

What all the parts of the unified view have in common are `from` and `until` which is an aggregate from different tables depending on the structure of the subquery.

So let's say there is a rental with `from: "2021-07-19", until: "2021-07-23"`. 

1. Would a query `(from: "2021-07-16", until: "2021-07-20")` include this rental?
2. Would a query `(from: "2021-07-20", until: "2021-07-26")` include this rental?
3. Or only the query `(from: "2021-07-16", until: "2021-07-26")`

**Comment by eins78** [comment]
@nimaai so there are two questions: 

1. what dates are relevant? i think it should only look at the reservations (that would also match the "from X until Y" summary in th UI)

2. how should the "range intersection" be interpreted? i am unsure but leaning towards "when there is any overlap", that would be all 3 of your examples. for anything more tricky i'd prefer a more specialized filter like "start date is this range" and "end date is in this range" (not yet needed but maybe there is a simple but general solution)

**Comment by nimaai** [comment]
@eins78 

1. Yes, only reservations.
2. Yes, intersection makes sense (for now).

Will implement it accordingly.

**Comment by nimaai** [comment]
In the searchable fields I suggest to include also:
- [ ] `models.manufacturer`
- [ ] `models.description`
- [ ] `options.manufacturer`
- [ ] `options.inventory_code`
- [ ] `items.inventory_code`
- [ ] `items.serial_number`

@eins78 more ideas?

**Comment by eins78** [comment]
- [ ] `contract.note`
- [ ] `contract.purpose`
- [ ] `contract.compact_id`
- [ ] `reservations.line_purpose` (if its actually used)

I have some reservations (no pun intended) against `models.description` – that can include lots of prose and might lead to "false positives".

Also, the question got me thinking, i think a `model.id` filter would also be useful to have.

**Comment by eins78** [comment]
also, to state the implicit: no searching in flexible fields ;)

**Comment by nimaai** [comment]
@eins78 

> `reservations.line_purpose`

I thought about that, but I think rather not. Not sure if we want to expose it to the customer in any way. It is something which is temporarily added to the lines by the lending managers and normally becomes part of the contract's purpose later on.

> `model.id`

What use case do you have in mind?

**Comment by eins78** [comment]
@nimaai 
> > `model.id`
> 
> What use case do you have in mind?

* on model show, display "you have rented this in the past"
* link from model show to "your past rentals of this model"

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c5a89cdbea29b1930176598d45c6d213845a90ce
