### ISSUE TITLE
fixes for Rentals API

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1121]
* [x] fix migrations for view (first version was already rolled out, need to drop and recreate)

* [x] `rentalState` is wrong for some of @eins78 orders
  * approved/rejected http://localhost:3250/app/borrow/rentals/70379cec-9c37-4f35-912f-6fd2c0eaef08
  * open/rejected http://localhost:3250/app/borrow/rentals/98510838-a6ec-4752-823e-5a3db2282775

* [ ] ~~specs für alle cases [aus dem mockup](https://leihs-styleguide-pn6bb792a-leihs1.vercel.app/?path=/story/mobileapp-wireframes-meineausleihen-liste--liste)~~ (will be done later together with all other tests)

* [x] totalDays should be minimum 1 (exact definition: total lenght in minutes, minum 1 minute, rounded up to number of days with`Math.ceil`)

* [x] new "progress bar data" (to be defined/named)
  ```graphql
  pickupFulfillment {
    fulfilledQuantity
    toFulfillQuantity
  }
  returnFulfillment {
    fulfilledQuantity
    toFulfillQuantity
  }  
  ```

**Comment by nimaai** [comment]
@eins78 

apropos `totalDays` I am starting to like the following definition the most: 

*number of **calendar** days*, means on how many calendar days did I have the item

then we also don't need the "minimum 1" hack and the following 2 rental periods are also clearly distinguished:
1. from today until today -> `totalDays = 1`
2. from today until tomorrow -> `totalDays = 2`

what do you think?

**Comment by eins78** [comment]
@nimaai Sounds good, lets do it. Not sure if it matches the expectation of users but we'll find out soon enough and this solution is at least easily explainable and internally consistent.

**Comment by nimaai** [comment]
possible `PoolOrderRentalState` (different from `PoolOrderState`!) enums:
- IN_APPROVAL
- TO_PICK_UP
- BORROWED
- PARTIALLY_RETURNED
- RETURNED
- REJECTED
- EXPIRED
- OVERDUE

`RefinedRentalState` (different from `RentalState` -> `OPEN, CLOSE`!) will be technically a distinct (or not) array of `PoolOrderRentalState`. Question is what will be made out of this array to display to the user as the overall state of his or her rental.

**Comment by eins78** [comment]
did some UI sketching and data structure drafting yesterday. now topic is on hold until next week (holiday), here are my progress notes: https://github.com/leihs/leihs-ui/blob/f451b8f00575aa8e5c0cafc56597a69cf7bf0129/src/components/MobileApp/constants/fulfillmentStates.js#L14

**Comment by nimaai** [comment]
@eins78 

In regards to `APPROVED` and `TO_PICKUP` I would merge them together to `TO_PICKUP`. We want to draw the attention of the customer to the fact that he/she has to pickup up something already before the pickup date arrives, I think (the same now in old borrow).

In regards to `EXPIRED`: as far as I have seen, the reservations are not invalidated if `CURRENT_DATE > reservations.start_date`. The items just "sit there" and wait to be pickup up. In this case I would reframe `EXPIRED` to `CURRENT_DATE > reservations.end_date`, because then the reservations are obviously invalidated.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d85aa713671d35c95e5c4c5867e33ba9e4dc0d19
