### ISSUE TITLE
Elaborate stories (and components)

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1123]
Stories
- [x] Design components and Bootstrap stories: add a title and an inline description (marked with `.text-muted`). Remove layout where there is/was one. Generally more stories and more details, improved visualization. 
- [x] Add generic page typology wireframes
- [x] Restructure stories (using metadata, no file renames). Use `storySort` option to control the sort order of stories. Divide Design components in three groups. Rename `Components` to `Integrated Components`
- [x] Add an overview page explaining the design and storybook structure.
- [x] `AppLayout` stories: `ErrorBoundary` demo on click only, not on load. Fix some React warnings coming from fake markup.
- (moved to separate card) Add stories declaring which Bootstrap classes are to be used directly (bypassing design components). Namely buttons. Maybe ditch Bootstrap direct usage altogether? 

Component refactoring and optimization
- [x] Decouple `Stack` from `PageLayout`. Unify `Stack1`, `Stack2` and `DividedStack`
- [x] Rename `KeyValueTable` to `PropertyTable` 
- [x] Rename `DialogCard` to `DialogLayout`
- [x] Decouple `FormButtonGroup` (fka `DialogLayout.`) from `DialogLayout`
- [x] `DownloadLink`: wrap with indent
 
Forms
- [x] Harmonize existing form views (orthogonal, WIP)
  - [x] Wireframe prototypic form
  - [x] Bootstrap sample form
  - [x] ModelFilter
  - [x] OrderFilter
  - [x] OrderPanel
- [x] `InputWithClearButton` Fix clash of button with invalid icon
- [x] Use `<label for>` everywhere (no "input in label" nesting)
- [x] Add visually hidden labels where the visual label is a `Section` title (which is not suitable to be a label)
- [x] Add `LabelInside`components
- [x] Use select icon from design
- [x] Use date icon from design

New design components
- [x] Implement correct design for `ListCard` (was `SimpleCard`), refactor it, include its own stack rendering
- [x] Implement correct design for state progressbar. Add design component `ProgressInfo`
- [x] Implement correct design for the pill badges. Add design component 'Badge'
- [x] Add `PageLayout.Metadata` component

Other
- [x] Remove pseudo logic around Orders (OrderStateInfo, OrderDetail, OrderList)

Add wireframe stories:
- (moved to separate task) Shopping Cart

**Comment by urs-van-binsbergen** [comment]
Thoughts about the "label around input" pattern
- It is convenient, we don't have to deal with naming and uniqueness
- But:
  - Bootstrap does not really support it, at least there is no documentation
  - HTML spec says: only phrasing content and controls in labels - so how to layout? Of course we can apply display:block...

**Comment by eins78** [comment]
merged in https://github.com/leihs/leihs/pull/1126
