### ISSUE TITLE
Implement shopping cart wireframes

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1124]
modifications to design components:
- [x] ActionButtonGroup: add errorMessage slot
- [x] Badge: apply default variant not only when className is undefined, but also when falsish ('classnames' always passes an empty string)

fixes:
- [x] form page story had wrong spacings because of classes I forgot to remove in the last task

new stories (basically done):
- [x] "Keine Gegenstände" (cart empty)
  - only occurence of a link with text-decoration underline in the wireframes -> just use Bootstrap utility 
- [x] "Neue Ausleihe" (cart containing items)
- [x] "Gegenstand bearbeiten" (edit item)
  - very similar to OrderPanel - don't integrate in the wireframe, show info and link
- [x] "Ausleihe bestätigen" (confirm)

**Comment by eins78** [comment]
- [ ] validate on "de-focus" (`blur` event) 
- [ ] textarea rows = (line length of value + 1)
- [ ] integrate ModalDialog (when done)

**Comment by urs-van-binsbergen** [comment]
storybook config:
[ ] reorder addons in main.js: 
  - 'story' as first tab
  -  add 'controls' (so they can also be seen and used in canvas view)

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs-ui/commit/bdff0d73adad701f28661cd527ab1a13da0ca99d
