### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1125]
### components 

- [x] Finalize ModalDialog (remove DialogLayout)
  - [x] Design fine tunings
  - [x] Body and Footer as sub components 
  - [x] Wire buttons to form with `form` attribute
  - INFO: OrderPanel story (`BookingCalendar.stories.js`) has some debugging information which is not visible now because it's behind the modal
  - INFO: Snapshots tests disabled for all affected stories because they don't work with ModalDialog, see comment below

- [x] add DatePicker component and add to ModelFilter and CatalogFilter

- [x] improve gallery bullets

- [x] Stack: no margin-bottom after the last element, only between

- [x] decorate `UserProfilePage` component (already prepared, see https://test.leihs.zhdk.ch/app/borrow/current-user)
  - [x] `PageLayout.Header` has now a `subTitle` option
  - [x] Align top and more controlled column widths in `PropertyTable`

- [x] Calendar
  - [x] General styling (light gray, blue, red, with crosses, ...)
  - [x] block & decorate when not loaded yet. Test with network throttle.
  - [x] set fixed height (maximum number of weeks), don’t jump around when navigations months
  - INFO: some issues are left, see https://github.com/leihs/leihs/issues/1136
- [x] Inputs: no autocompletes! (even in chrome!)

- [x] Navbar icon zahl in die mitte rücken (see comment below)

- [x] ListCard support href links (now only onClick), Boostrap "stretched link" if possible (added uvb 10.08.2021)

- [x] PageLayout maxWidth (added uvb 11.08.2021)

**Comment by urs-van-binsbergen** [comment]
Calendar issues
- [ ] Dates which are not selectable as start are also not selectable as end and vice versa
- [ ] Dates which are not selectable as start or end but ok as part of the range should not be marked with `.disabled`, otherwise we can't highlight those correctly which are ALSO not ok as part of the range.

**Comment by urs-van-binsbergen** [comment]
Info: snapshots disabled for all stories which include `ModalDialog`, otherwise the snapshot test fails. This is OK since the testing strategy for the UI components is yet to be determined. 

```
Warning: An invalid container has been provided. This may indicate that another renderer is being used in addition to the test renderer. (For example, ReactDOM.createPortal inside of a ReactTestRenderer tree.) This is not supported.
        at BackdropTransition
        at Modal (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/node_modules/react-overlays/cjs/Modal.js:74:24)
        at Modal (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/node_modules/react-bootstrap/cjs/Modal.js:85:3)
        at ModalDialog (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/src/components/MobileApp/DesignComponents/ModalDialog.js:11:3)
        at div
        at PageLayoutHeader (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/src/components/MobileApp/DesignComponents/PageLayout.js:13:49)
        at div
        at div
        at PageLayout (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/src/components/MobileApp/DesignComponents/PageLayout.js:4:38)
        at PageLayoutMock (/Users/uvanbinsloc/dev/leihs/borrow/leihs-ui/src/components/MobileApp/StoryUtils/PageLayoutMock.js:5:42)
        at storyFn
```

**Comment by urs-van-binsbergen** [comment]
Vertical align of number in cart badge: Was quite hard to do, probably I'm missing something. It's easy to adjust it for 200% browser zoom or so, but in original size it's always either one pixel too low or too high. Kind of solved by setting the circle height to 19px instead of 18px. However in Firefox still too low.

Helper for a visual control of the alignment, put this inside the `cart-badge`:
```
<div style={{ position: 'absolute',
                  top: '3px', left: '0', right: '0', bottom: '3px',
                  border: '1px solid white',
                  overflow: 'hidden'
                }}
              ></div>
```

**Comment by eins78** [comment]
> Vertical align of number in cart badge: Was quite hard to do, probably I'm missing something.

We should check the sizing and alignment of the icon *inside* the SVG – maybe it *impossible* to properly align at all sizes due to antialiasing and rounding errors.

**Comment by eins78** [comment]
> Calendar issues which need modification of `@leihs/calendar`
> 
> Non-pickup-days are also unselectable as return days, and vice versa. If this a use case at all this should be fixed. If not we could simplify the API.

From the description I am not sure how it is currently, but yes, we need a distinction between "can not pick up" and "can not return". I am not 100% sure if we already use it that way.

> * [ ]  Dates which are only no-pickup/return have the classes `disabled disabled-start disabled-end` (pseudo code) no matter if the item is generally available or not. E.g. in the 'Contraints" select 20 to 22: the 21 should get red but won't (false negative). The fix for this would lead to false positives (e.g. for 9 to 12).

Lets look at this interactively. It sounds like the underlying problem is that its complicated to style the "selection range bar" and I am not sure if we _want_ it this way. It could also be argued that if the selection is invalid for any reason the whole bar should be red?
Also the (very good!) constraints story makes me think we need some kind of chart legend… When I look at it _I_ dont get what going on. A message at the bottom would be consistent with the form styling (and the old calendar), but lets discuss that with the rest of the team.

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/3327f9126b6d6b9a2934a44c28c07ce27ddb8f94
