### ISSUE TITLE
borrow: translations: flip map

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1128]
* nest the languages under the keys, not vice versa
* ex. `{:greeting {:de "hallo" :fr "bonjour"}`
* to keep the lang-keys short, have a top-level mapping like `{:en :en-GB}`
* resulting SQL file and DB structure stays as is

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9a099144b28f95d48905592c53fa986cf3d80492
