### ISSUE TITLE
Wiping audit tables OK?

### ISSUE THREAD

**Issue by MatKDA** [leihs/leihs#1129]
Hello,
we have privacy concerns considering the audit feature of leihs. As we can’t find a way to disable this feature we’re wondering if we could just periodically wipe the audit* tables? Are there any side effects to this?
Thank you!

**Comment by eins78** [comment]
Yes, anything audit-related tables can be cleaned as the operator sees fit and we expect instances to do so according to their policies.
The only parts of Leihs that rely on the audit data is the audit viewer itself, no other features rely on it.
