### ISSUE TITLE
new borrow: testing strategy for UI library

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1130]
*status: to be done after first version of new borrow mobile app goes live*

---

currently we only have simple snapshot tests in `leihs-ui` and browser-based integration (end-to-end) tests in the various apps.

* snaphot tests
  * built using `jest`
  * protects against accidental change of DOM structure yielded by UI components
  * are **not** run in a real browser (only the virtual DOM is checked)

 * integration tests
   * built using `turnip` (gherkin/cucumeber syntax; optional) → `capybara` → `selenium` → `webdriver` → `firefox`

problems:
* components that interact with the DOM can not be snapshot-tested, we currently exclude them from tests
* no basic unit-tests for JS components
* integration test that interact with more complex components have to rely on the DOM structure and need to be adapted when changed. because the tests are split into several repos that might be lots of duplicate work

possible solutions:

*(either/or)*

1. use more `jest`
  * setup browser-based snapshots (so it works for all the components)
  * add some unit-test for interactive components ("When I click on this button the "onClick" handler is called")

2. use more `rspec`
  * setup "integration tests" like in the app repos, but run it against the *storybook*! 
  * does not add new technology that needs to be herded and learned to the stack
  * per-component helpers (using `capybara/rpec` API) can be developed in the UI repo next to their components

**Comment by neoheat** [comment]
@urs-van-binsbergen please check if this needs to be followed up

**Comment by urs-van-binsbergen** [comment]
My thoughts (WIP): 

Snapshot dirty check - "protects against accidental change of DOM structure yielded by UI components": Good idea, but not very useful in practice. Usually a change in `leihs-ui` components is expected to change the snapshots, so `update-snapshot` is done mechanically on every commit. Thus chances are high that the seldom case of an unwanted change would go unnoticed.

Render all components - very useful, especially when doing some mass change. 

Generally it seems that "React Testing Library" is the way to go if we stick with "direct" testing -> TODO: closer investigation

Test against storybook - Might lead to testing noise. Stories should be quickly changeable without the hassle of fixing tests. The advantage is that all "typical" states of the components are covered. Maybe a good way if there is something like an schematic "all stories can render without crashing and without console errors".

**Comment by urs-van-binsbergen** [comment]
Leihs-UI is now integrated in Borrow (`borrow/ui`). 

No snapshot tests anymore. Instead: https://storybook.js.org/docs/react/writing-tests/test-runner

Disadvantage: needs a running storybook instance and a browser. Is not yet installed on CI. 

Not sure whether it is a good solution.

**Comment by neoheat** [comment]
install on CI to be checked with @DrTom
