### ISSUE TITLE
translations: support ICU message syntax

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1132]
general:

- current setup of how the translation strings are managed (in the DB etc) stays the same
- how the translation function (& macros) are used in the app also stays as is
- we want to change how the strings are evaluated, e.g. what syntax we support for interpolations, how to handle plurals, etc
- we want to use [ICU format](https://unicode-org.github.io/icu/userguide/format_parse/messages/)
- we can use the [`intl-messageformat` lib](https://formatjs.io/docs/intl-messageformat)

example:
* https://github.com/leihs/leihs-borrow/tree/mfa/i18n
* translation definition: https://github.com/leihs/leihs-borrow/blob/mfa/i18n/src/server/leihs/borrow/resources/translations/definitions.clj#L5-L9
* translation usage: https://github.com/leihs/leihs-borrow/blob/mfa/i18n/src/client/leihs/borrow/features/home_page/core.cljs#L50-L52

tasks
- [ ] `keys.are.dot.separated` not `key.with/slashes` – nesting maps is only a shortcut: `{:a {:b "c"}}` same as `{:a.b "c"}`
- [ ] support ICU syntax

**Comment by eins78** [comment]
timebox 1 workday, if its more work than expected we'll keep on using simple strings and work around the limitations until https://github.com/leihs/leihs/milestone/48

**Comment by eins78** [comment]
@nimaai i realized that the "map as dot" shortcut might complicate things when we want to sync back contributions from a user to the repo (we get the dump of the `translations_user` table and need to put it into the `.edn` file). to keep it simple, lets forbid dots in the map-keys of the definitions? as in, to make a dot you _need_ to use a map – this way we can have simple 2-way transformation

**Comment by nimaai** [comment]
@eins78 Do we want to show english translation if available in case a translation for the desired language does not exist? Or rather `missing translation: ...` ?

**Comment by nimaai** [comment]
As discussed, we will hard-code language fallbacks in frontend for now.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/543cfd1f9bd598597e379908f0254335e1374f25
