### ISSUE TITLE
review new borrow

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1139]
### Seite "Meine Ausleihen" 

- links
  - app https://staging.leihs.zhdk.ch/app/borrow/rentals/
  - wireframe https://leihs-styleguide-7538fw3st-leihs1.vercel.app/?path=/story/mobileapp-wireframes-meine-ausleihen-liste--liste

  
- zeigt Bestellungen und "Direkausleihen", soll mit möglichst vielen Nutzern angeschaut werden ob es Bugs hat und die Daten sinnvoll erscheinen.
- Zeilen korrekt und sinnvoll?  **- für Tests ok**
- Aufteilung nach offen/abgeschlossen korrekt? **- für Tests ok - solange man oben den Filter bedienen kann.** 
- Status (progress bars) korrekt - besonders auf "gemischte" zustände achten, z.B. noch nicht alles abgeholt aber schon teilweise zurückgebraucht **- sieht ok aus für Tests**

- Detailansicht ist noch nicht fertig, aber die wichtigsten Infos sind drauf um die Liste nachvollziehen zu können - **Für Tests fehlen die folgenden Infos: Vertragsansicht, Welche Gegenstände wurden bereits zurückgebracht in Liste markieren, Unterscheidung Option/Gegenstand - weil Optionen können nicht erneut bestellt werden.** 

- welche Daten sollen noch angezeigt werden (z.B. bei Gegenständen auch der Inventarcode?) **Die Info ist im Vertrag z zuhen. Ich würde die Ansicht nicht überladen mit Infos die nicht zwingend sind.** 

### Seite "Benutzerkonto"

- links
  - app https://staging.leihs.zhdk.ch/app/borrow/current-user
  - wireframe https://leihs-styleguide-7538fw3st-leihs1.vercel.app/?path=/story/mobileapp-integrated-components-userprofilepage--user-profile-page

- Daten OK? **- Ja OK für Tests**
**- Delegationen:Beim Klick auf eine Delegation müssten wir auf die Infos der Delegation verlinken.**
- nicht testen: Logout-Button. Dieser ist aktuell noch im Hauptmenü und wird dorthin verschoben wenn das Menü gemacht wird

### Booking Calendar

- links
  -  app ex. https://staging.leihs.zhdk.ch/app/borrow/models/1c18b3d3-88e8-57ac-8c28-24d3f8f77604
  - design spec https://www.sketch.com/s/0650689d-b551-418f-913f-e598933e5f7f/a/zxkjER5
  - wireframes ff. https://leihs-styleguide-7538fw3st-leihs1.vercel.app/?path=/story/mobileapp-design-components-form-controls-daterangepicker--date-range-picker

- is now styled according to design spec
- interaction is improved
- talk to @urs-van-binsbergen for details/demo

**Comment by eins78** [comment]
@nadjaweisskopf i listed everything to be tested above. for obvious bugs create new issues, for everything else i suggest you collect your notes here in the comments and than we look at it together (also with rest of team).

**Comment by eins78** [comment]
@nadjaweisskopf neue Stati die "Ausleihen (Bestellungen und Direktausleihen)" haben können (relevant für filter und progress bars)
![flowchart-2](https://user-images.githubusercontent.com/134942/132237182-c2848968-a49a-44fd-8f72-f8ffb15c7c57.png)

**Comment by eins78** [comment]
@nadjaweisskopf neuester stand (inkl. fix contract view for delegations) ist nun auf staging https://staging.leihs.zhdk.ch

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen what is the difference between the status "overdue" and "expired"?

**Comment by nadjaweisskopf** [comment]
All comments above have been checked and will be tested with the users asap. I will close the ticket.

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf "expired" = item was not picked up in time, "overdue" = item was not returned in time. So in both cases the reservation end date is over, but in the first case the item was not even picked up.
