### ISSUE TITLE
bug report: Leihs 3.32.1 missing search field "used & not used" under Inventory-> Models

### ISSUE THREAD

**Issue by stellaf** [leihs/leihs#114]
bug report: Leihs 3.32.1 missing search field "used & not used" under Inventory-> Models
see enclosed picture.
Server linux Centos 7, PHP5.6, Ruby-2.3.0, Passenger5.0.23, Apache 2.4.6
rvm install 2.3.0
rvm rubygems current #passenger 5.0.23 works only with ruby 2.4.8
Freshly installed Leihs  3.32.1, no any change in Code.
![capture](https://cloud.githubusercontent.com/assets/6710014/12731750/ab11ec0a-c932-11e5-8a12-30003c3d45dd.JPG)

**Comment by psy-q** [comment]
That's not a bug, that was designed that way to prevent combinations of search filters that create impossible results. If you change to "retired & not retired", the field will show up.

But we're aware that this can be confusing and I will suggest that if this section gets redesigned, some time is spent on making those fields clearer.
