### ISSUE TITLE
Catalog: hide categories not having items matching the current filter

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1140]

**Comment by nimaai** [comment]
This is not so easy, especially when the availability filter is involved. One would effectively need to ask legacy for the availability of each and every model of each and every child category to find out whether it is empty or not. That would be quite a performance issue I expect. Even old borrow does not do that. There are also all child categories displayed whether the model list is then empty or not (in case of old borrow the unavailable models are simply greyed out).

What to do? Ideas?

@eins78 @urs-van-binsbergen

**Comment by eins78** [comment]
We can not offer this at the moment (not until availability calculation is ported). We know from similar features in the past that this is really hard to optimize in the best case, currently we have no chance.
Note that we likely will collapse the sub-categories by default, which will make this a little less worse.
