### ISSUE TITLE
Shopping cart

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1141]
Build on existing `shopping-cart/core.cljs` (etc.) in `master`, taking implementation details from `shopping-cart2` in `mk/shopping-cart`.

**Comment by urs-van-binsbergen** [comment]
To discuss
[ ] Notion of "delegation": currently switching delegation means switching to another shopping cart (like switching identity). The design rather suggests that the selection of a delegation is a subsequent decision (like selecting the delivery address in an shop order). Just moving the select field in top does not help IMO.

**Comment by urs-van-binsbergen** [comment]
- [ ] Sometimes the cart icon shows a wrong number of items, and sometimes the cart initially shows the "cart empty" view although it is not empty (unclear: how to reproduce; are these two issues related; are they related to the shopping cart view?)

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/fe3b3451d8c7d8cdbc945ae5e64d8f38bc50ed14
