### ISSUE TITLE
re-frame `bad dispatch value` error in console when quickly navigating

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1142]
Steps to reproduce:
- Open catalog 
- Then open a model, then immediately go back to catalog using browser back (so that the loading of the model is interrupted)

Browser console shows an error message: "re-frame: ignoring bad :dispatch value. Expected a vector, but got (...)"

![image](https://user-images.githubusercontent.com/25439444/133102235-fd9c259e-1699-4ae9-b0c0-aa7aaf272c93.png)

**Comment by nimaai** [comment]
@urs-van-binsbergen I cannot reproduce it. :man_shrugging:

**Comment by eins78** [comment]
@urs-van-binsbergen timebox 2 days ⛑️

**Comment by urs-van-binsbergen** [comment]
Problem analysis:

We use the "Aborting queries" feature of re-graph, which is available in API, but is a not a working feature, see unclosed feature request issue: https://github.com/oliyh/re-graph/issues/50

Core problem: __the HTTP Request is not aborted__. (The reason is not clear but I suspect the following line is never called: https://github.com/oliyh/re-graph/blob/2a1a06fdba6e458c1637a6922944061d422e633e/src/re_graph/core.cljc#L125. Or there is a problem with `abort!` in `cljs-http`: https://github.com/r0man/cljs-http/issues/46)

What happens as a consequence of this:
- `re-graph/abort` will dissoc `:re-graph.internals/default :http :requests <request-id>` and therefore also `:callback` is lost
- Then `http-complete` will fire, and the handler in `re-graph` will dispatch `(conj nil data)` which gives `(data)` (where `(conj [:callback] data)` is expected, which gives `[:callback data]`)

Solution: TBD. The "Aborting queries" feature of re-graph can not be used. Of course we could try to submit a fix PR. But do do we even have to cancel the queries? The author of re-graph suggests other solutions like using subscriptions (which can be cancelled), or handle the aborts in the own handler implementations, as far as necessary.

**Comment by eins78** [comment]
@urs-van-binsbergen thanks for the analysis. we'll discuss it in the next dev meeting. if it really does not work, we can just disable the avort feature in the frontend router for now.
if we want to fix it (including fixing bugs in the upstream libs if necessary) we should do it after "go live".
1 detail should be looked into: we have a "aborting requests" spec that tests if the requests (including the running queries in the DB!) are really aborted. that spec was always a bit flaky. maybe it never really worked – but if it did we should find out what happened.
