### ISSUE TITLE
DB seeds: fix list of available/built-in languages

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1144]
* list of built in languages here: https://github.com/leihs/leihs_legacy/tree/36168206a628d379a4f1fc5112616a3e05b6bc19/locale
* in DB seeds, French (`fr-CH`) and Spanish (`es-ES`) are missing
- [x] add `fr-CH` and `es-ES` to languages in DB seeds (with `active: false` so new instances have the same active languages like they would have now, we only want to give the option to enable them)

---

  ![Screen Shot 2021-09-06 at 15 04 48](https://user-images.githubusercontent.com/134942/132222049-8764cd12-d7ed-4d58-a15d-d4424c7d6153.png)

**Comment by nimaai** [comment]
database: https://github.com/leihs/leihs_database/tree/mk/missing-langs-1144

**Comment by nimaai** [comment]
todo:
- [ ] add mail templates too

**Comment by nimaai** [comment]
WIP: https://github.com/leihs/leihs/tree/mk/missing-langs-1144

`languages.feature` int-test is still red.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/b564e23ba3425f59c2414b523dac009ca2737ebf

**Comment by nadjaweisskopf** [comment]
- activate and test if the language changes. 
- also test new borrow and test if new languages appear in menu.

**Comment by nadjaweisskopf** [comment]
In New borrow, if I switch to "French", the titles are not translated - and the default English is not used. 

![grafik](https://user-images.githubusercontent.com/3356016/190641012-cfc20a7f-c1b8-4dd9-aa70-9f31f6116558.png)

@urs-van-binsbergen I thought we already handled this in another ticket.

**Comment by neoheat** [comment]
My tests show that the `fr-CH`can be enabled. No more variable placeholders are displayed.
Therefore, I close this ticket as resolved.
