### ISSUE TITLE
Force "Take back"

### ISSUE THREAD

**Issue by AnthonyHunt-UoW** [leihs/leihs#1147]
Update to 6.2.1 and DB looks okay.

We have several users that have had keys issued to them for doors. This booking has continually (3,300 days) been extended for a number of years.

I've come to return them and when doing the "Take Back" the screen dims but doesn't complete the take back.  

Is there a way to "force" the take back of a contract?

**Comment by nimaai** [comment]
Any log or something?

**Comment by AnthonyHunt-UoW** [comment]
Where would it log this in v6? Apache?

**Comment by AnthonyHunt-UoW** [comment]
I get this from the journal

`Sep 10 14:25:01 uw-leihs CRON[5986]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 10 14:25:01 uw-leihs CRON[5987]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep 10 14:25:01 uw-leihs CRON[5986]: pam_unix(cron:session): session closed for user root
Sep 10 14:25:40 uw-leihs leihs-legacy[884]:   
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: NoMethodError (undefined method `log' for Rails:Module):
Sep 10 14:25:40 uw-leihs leihs-legacy[884]:   
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:216:in `rescue in take_back'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:191:in `take_back'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:17:in `block in call'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:14:in `call'
`

**Comment by nimaai** [comment]
First I'd be interested in `journalctl -u leihs-legacy`

**Comment by nimaai** [comment]
Is this all? I am missing more context, especially the exception message from Rails which should be logged too.

**Comment by AnthonyHunt-UoW** [comment]
Sep 10 09:59:10 uw-leihs systemd[1]: Started Leihs Legacy Service.
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] Puma starting in cluster mode...
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Version 3.9.1 (ruby 2.6.6-p146), codename: Private Caller
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Min threads: 1, max threads: 2
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Environment: production
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Process workers: 2
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Phased restart available
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] * Listening on tcp://localhost:3210
Sep 10 09:59:13 uw-leihs leihs-legacy[884]: [884] Use Ctrl-C to stop
Sep 10 09:59:33 uw-leihs leihs-legacy[884]: Creating scope :open. Overwriting existing method Contract.open.
Sep 10 09:59:33 uw-leihs leihs-legacy[884]: Creating scope :open. Overwriting existing method Contract.open.
Sep 10 09:59:33 uw-leihs leihs-legacy[884]: [884] - Worker 1 (pid: 933) booted, phase: 0
Sep 10 09:59:33 uw-leihs leihs-legacy[884]: [884] - Worker 0 (pid: 931) booted, phase: 0
Sep 10 10:01:21 uw-leihs leihs-legacy[884]:   
Sep 10 10:01:21 uw-leihs leihs-legacy[884]: NoMethodError (undefined method `log' for Rails:Module):
Sep 10 10:01:21 uw-leihs leihs-legacy[884]:   
Sep 10 10:01:21 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:216:in `rescue in take_back'
Sep 10 10:01:21 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:191:in `take_back'
Sep 10 10:01:21 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:17:in `block in call'
Sep 10 10:01:21 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:14:in `call'
Sep 10 10:02:16 uw-leihs leihs-legacy[884]: Validation failed: User is suspended for inventory pool: Digital Arts Centre
Sep 10 11:19:49 uw-leihs leihs-legacy[884]:   
Sep 10 11:19:49 uw-leihs leihs-legacy[884]: NoMethodError (undefined method `log' for Rails:Module):
Sep 10 11:19:49 uw-leihs leihs-legacy[884]:   
Sep 10 11:19:49 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:216:in `rescue in take_back'
Sep 10 11:19:49 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:191:in `take_back'
Sep 10 11:19:49 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:17:in `block in call'
Sep 10 11:19:49 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:14:in `call'
Sep 10 11:32:01 uw-leihs leihs-legacy[884]:   
Sep 10 11:32:01 uw-leihs leihs-legacy[884]: NoMethodError (undefined method `log' for Rails:Module):
Sep 10 11:32:01 uw-leihs leihs-legacy[884]:   
Sep 10 11:32:01 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:216:in `rescue in take_back'
Sep 10 11:32:01 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:191:in `take_back'
Sep 10 11:32:01 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:17:in `block in call'
Sep 10 11:32:01 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:14:in `call'
Sep 10 12:45:16 uw-leihs leihs-legacy[884]:   
Sep 10 12:45:16 uw-leihs leihs-legacy[884]: ActionController::RoutingError (No route matches [GET] "/mailman/listinfo/mailman"):
Sep 10 12:45:16 uw-leihs leihs-legacy[884]:   
Sep 10 12:45:16 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:22:in `call'
Sep 10 12:51:53 uw-leihs leihs-legacy[884]:   
Sep 10 12:51:53 uw-leihs leihs-legacy[884]: ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-precomposed.png"):
Sep 10 12:51:53 uw-leihs leihs-legacy[884]:   
Sep 10 12:51:53 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:22:in `call'
Sep 10 12:51:53 uw-leihs leihs-legacy[884]:   
Sep 10 12:51:53 uw-leihs leihs-legacy[884]: ActionController::RoutingError (No route matches [GET] "/apple-touch-icon.png"):
Sep 10 12:51:53 uw-leihs leihs-legacy[884]:

**Comment by AnthonyHunt-UoW** [comment]
ahhhh there's a clue here.... It says the user is suspended, which they all were, but I unsuspended them prior to extending and trying to return.

**Comment by AnthonyHunt-UoW** [comment]
Just noticed that I'd missed the end of that log

Sep 10 14:25:40 uw-leihs leihs-legacy[884]: NoMethodError (undefined method `log' for Rails:Module):
Sep 10 14:25:40 uw-leihs leihs-legacy[884]:   
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:216:in `rescue in take_back'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: app/controllers/manage/reservations_controller.rb:191:in `take_back'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:17:in `block in call'
Sep 10 14:25:40 uw-leihs leihs-legacy[884]: lib/leihs/middleware/audit.rb:14:in `call'

**Comment by AnthonyHunt-UoW** [comment]
Any update? We can't take back some items which it becoming a significant issue.

**Comment by nimaai** [comment]
Ok. I have just noticed something. I still don't see what the actual problem is because the rails logger is not functioning properly: `NoMethodError (undefined method log' for Rails:Module)`. Please change line 216 of `/leihs/legacy/app/controllers/manage/reservations_controller.rb` to:

```
Rails.logger.warn e.message
```
and then restart the leihs-legacy service.

Then please post the log again.

**Comment by AnthonyHunt-UoW** [comment]
Bingo. We have a winner. Looks like there are old records with "null" contract purpose?

Sep 15 10:35:05 leihsv5-01 leihs-legacy[871]: PG::RaiseException: ERROR:  Contract's purpose can't be NULL for this inventory pool.
Sep 15 10:35:05 leihsv5-01 leihs-legacy[871]: CONTEXT:  PL/pgSQL function check_contracts_purpose_is_not_null_f() line 7 at RAISE
Sep 15 10:35:05 leihsv5-01 leihs-legacy[871]: : UPDATE "contracts" SET "state" = $1, "updated_at" = $2 WHERE "contracts"."id" = $3

**Comment by AnthonyHunt-UoW** [comment]
Confirmed. Removed the "purpose" check from the pool and the take back works correctly.
