### ISSUE TITLE
API Search with new admin interface ( account enabled defaults to null)

### ISSUE THREAD

**Issue by AnthonyHunt-UoW** [leihs/leihs#1149]
The new admin interface "search" for users defaults to true when searching in the API.

Example fragment:

$search_term = array(
	'page' => 1,
	'per-page' => 10,
	'term' => $user_to_check['org_id'] . '@'
);

is only returning users where "account_enabled" is true. Accounts which exist but "account_enabled=false" do not exist and I cannot see how to set "any"?  

I have tried various permutations to "account_enabled=>" as below but nothing seems to return records? 

$search_term = array(
	'page' => 1,
	'per-page' => 10,
	'term' => $user_to_check['org_id'] . '@',
	'account_enabled' => 'yes'
);

This is obviously possibly in the admin interface and URL like "/admin/users/?page=1&term=robn1&account_enabled="

How can this be achieved in the API?

Thanks.

**Comment by eins78** [comment]
@AnthonyHunt-UoW just to make sure I understand the question: You want to search using the Admin API and include enabled and disabled accounts in the same result?
In any case @DrTom should have some insight.

**Comment by AnthonyHunt-UoW** [comment]
That's correct. The API is used for adding/updating users from an external source (AD/LDAP).  This used to work correctly in 5.2.1 but now a search only returns user that are enabled, meaning that disabled users don't get re-enabled - as the add/update logic doesn't appear to "update" a user if "add" is used.

**Comment by AnthonyHunt-UoW** [comment]
Is there a fix for this? I am currently unable to update "disabled" accounts "enabled" via script.

**Comment by eins78** [comment]
@AnthonyHunt-UoW you wrote:

> This is obviously possibly in the admin interface 

If that is the case, then it must be possible to achieve this via the API, because the Admin UI exclusivley uses the Admin API.
Check the Developer Tools in your browser (Network Tab) to see the requests that are sent.

**Comment by AnthonyHunt-UoW** [comment]
Yes... It should be. But it is not. You need to test this.

When the account_enabled parameter is NOT passed to the API in a call the API returns ONLY accounts that are enabled by default. It should be returning ALL accounts. This is because you cannot pass an empty parameter array element in most scripting languages like the "account_enabled=" url does.

I don't care about either account_enabled=yes or account_enabled=no options. It is specifically account_enabled=any that doesn't work via the API scripting.

Please. make an API call without account_enabled and see that no disabled accounts are shown.

**Comment by eins78** [comment]
The API works as expected – the parameter has a default value and to disable that you need to pass an emtpy value,
resulting in an URL like: `/admin/users/?page=1&account_enabled=' `, This string should be possible to create in any scripting language, example for PHP which you seem to use:

```
❯ php -r "echo http_build_query(array('page' => 1, 'account_enabled' => '', 'term' => 'hello'));"
page=1&account_enabled=&term=hello
```

**Comment by AnthonyHunt-UoW** [comment]
Thanks for the reply. But this is what isn't working? It seems that passing 'account_enabled' => '' in PHP is still only returning enabled accounts. Unless something else funky has changed?

I have logic that says:

search for account by org_id
  if account returned from API search
    update the account from new data
  else
    add new account

All of my disabled accounts fail to return from the search and try to get added as new. Enabled accounts update as logic dictates.

Happy to share the code/script but it essentially as above.

**Comment by AnthonyHunt-UoW** [comment]
ahhhhhhhhhhhh.

Headache!!! the problem is actually that the fuzzy term no longer accepts the @ symbol for accounts being searched for that appear to be disabled. My enabled account get returned by the GET but not the disabled.  This is odd because the Admin UI doesn't return anything with @.
