### ISSUE TITLE
TIPS: How to connect Leihs with Active Directory

### ISSUE THREAD

**Issue by stellaf** [leihs/leihs#115]
I got leihs connected with LDAP. I write down what I have gone through in hope to save someone time. I did read through the [Leihs LDAP configuration document](https://github.com/leihs/leihs/wiki/LDAP-configuration).
Tested in both Leihs 3.32.1 and 3.33.2 version, 

In the linux CENTOS7 server,
install the net-ldap gem
$**gem install net-ldap**

In your normal windows PC, 
Now find out the user and admin account DN. As a normal user in a normal Window PC, open a "cmd" window command window, type 
**whoami /FQDN**
it provides me the the information for base_dn
for example, I may got "CN=AnnaKarin Karlsson, OU=Helpdesk, OU=IT Users,DC=auto,DC=company,DC=com

Then logoff, and log in your own computer using the ADadminaccount,  open a "cmd" window command window, type 
**whoami /FQDN**
It provides me the information for admin_dn and the master_bind_dn.

so back to your linux server,
update the config/LDAP.yml file.
unique_id_field: sAMAccountName
  log_file: log/ldap_server.log
search_field: sAMAccountName
then it works.

I then login the leihs with db login, and see that the account actually created through  the LDAP, and change some account to admin, then it is done!
Hope this will save you sometime!

**Comment by psy-q** [comment]
Thanks! I've updated the wiki to include these tips.
