### ISSUE TITLE
Contract does not open

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1150]
When opening a contract in the my lendings section, I get an error. 

https://staging.leihs.zhdk.ch/borrow/user/contracts/50a42a3a-3f8d-464e-b70d-3c2891683482

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ece3289240331bb6d6b0216be6980d4fc402f12c

**Comment by eins78** [comment]
@nadjaweisskopf fix is on `test`. I verified that it works:
* log in as the user
* DO NOT switch to the delegation
* contract can be opened: https://test.leihs.zhdk.ch/borrow/user/contracts/50a42a3a-3f8d-464e-b70d-3c2891683482
