### ISSUE TITLE
error when selecting my user in filter

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1151]
How to reproduce: 

1. go to "my lendings"
2. check filter "FOR" --> my user is not shown
3. when switching to a delegation and back to my user (which is grey and not shown), I get an error.

<img width="628" alt="filter_borrow" src="https://user-images.githubusercontent.com/3356016/134006382-fbf6678e-8047-4ccb-87ba-4324a63d3816.png">

<img width="536" alt="borrow_error_1" src="https://user-images.githubusercontent.com/3356016/134006200-719a3993-fcae-4fc4-b116-5237d1e3bf74.png">

**Comment by nimaai** [comment]
Can not be reproduced anymore.
