### ISSUE TITLE
buggy behaviour when opening the model view

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1152]
How to reproduce: 
1. use mobile
2. go to "my lendings" 
3. click on a model line
4. model view should be opened but the display shows the calender, then the model view then the calender again - very quickly after each other

**Comment by eins78** [comment]
@nadjaweisskopf I can not reproduce this on any device. can you make a video of this happening? 
also, what do you mean by "it shows the calendar"? there is only a calendar in the reservation panel, is that what you see?
![Screen Shot 2021-09-21 at 11 18 06](https://user-images.githubusercontent.com/134942/134145549-299f5d7e-cde7-4502-9b71-0a93a290366d.png)

**Comment by eins78** [comment]
more stable repro:
* after step 3, quickly click on 'add to order' button
* order panel will open / close / open
