### ISSUE TITLE
Leihs beim Blick

### ISSUE THREAD

**Issue by sn0west** [leihs/leihs#116]
Hallo zusammen,

Wir haben bei uns Leihs installiert und sind sehr froh darüber. 
Nun haben wir ein paar Fragen und Anregungen für die Leihs Profis.

Kann mir jemand eine Nachricht schreiben? Wir sind in Zürich und würden uns auch über ein Treffen freuen.

NS

**Comment by psy-q** [comment]
Ich versuche gerade, über redaktion@blick.ch an deine Kontaktdaten zu kommen :)  Melde mich dann gern.

**Comment by sn0west** [comment]
ähm sorry wollte noch meine email reinschreiben
spc(at)ringier.ch
