### ISSUE TITLE
implement language switch (menu)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1163]
When language switch is ready...

Enhance the Benutzerkonto with the option to change the language --> then Benutzerkonto should be renamed to "Profile"

OR

Add the Language switch to the menu section "User name"

**Comment by nadjaweisskopf** [comment]
we leave it as designed - in the main menu, not under user profile

**Comment by nimaai** [comment]
@eins78 short understanding check: language switch is handled backend-wise by `my`. that will be the case for borrow too. what about dev environment? fixed `en-GB` ?

**Comment by eins78** [comment]
> @eins78 short understanding check: language switch is handled backend-wise by `my`. that will be the case for borrow too. what about dev environment? fixed `en-GB` ? no possibility to switch or what?

ideally the backend route would move to `shared` and be served from `borrow` app in dev mode, just like the sign-in routes.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/63b819b69f5075ee2ff06d16f7cd2e1e615b8a39

Integration test is ready but commented out due to failing attempts to solve a capybara wait_until issue. TBD in future.

**Comment by eins78** [comment]
@nimaai problem: the menu items are links and not buttons (`<a>` instead if `<button>`). That it works at all (after reload) is a funny side effect.
In short, those menu items should be implemented like the Logout-Button, which `POST`s a hidden `<form>` that also includes the CSRF-Token.

**Comment by nadjaweisskopf** [comment]
also test: Language fallback from Castellano to English (currently user sees "missing: text-foo" etc. instead of meaningful texts)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/bb68d7dbabb8980c56bc7e78caab6cec5c645c6e

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen implementation is ok now - switching works. It' very hard on my mobile to see which language is selected at the moment though.
