### ISSUE TITLE
Write stories for cart

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1168]
- [ ] edge cases
- [ ] conflicts
- [ ] time out
- [ ] read happy part scenarios from max
- [ ] in the cart it is not possible to switch the user - might be possible to switch if possible, if not possible then we need to specify what happens next
- [ ] check draft in https://github.com/leihs/leihs/issues/1091

**Comment by eins78** [comment]
@nadjaweisskopf imo this can be closed/deleted. all the tasks are either done as part of https://github.com/leihs/leihs/issues/1215 or the "delegation concept".

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf test whole cart - all scenarios

**Comment by nadjaweisskopf** [comment]
error when
1. reserve 3 models A/D-Converter Behringer ADA-8000  for the time frame 16. - 18.
2. go to lending and add A/D-Converter Behringer ADA-8000  to a hand over for the same time frame
3. go back to cart
4. refresh cart
5. overbooking is shown
6. open calender
7. go to free day and then choose the same time frame as before
8. error is shown

**Comment by nadjaweisskopf** [comment]
new issues create new tickets
