### ISSUE TITLE
Any future plans for PostgreSQL?

### ISSUE THREAD

**Issue by RandieM** [leihs/leihs#117]
Hello everyone,

This is obviously more of a question/feature request than an issue. Do you have any plans to support PostgreSQL in the future?

Many thanks.

**Comment by psy-q** [comment]
There have been murmurings but nothing serious as of yet :)  We'll keep this question open and will add to it if it looks like something can be decided.

**Comment by RandieM** [comment]
Thanks a lot for your quick reply and I hope that the "murmurings" will eventually become a little louder in the future ;-)

**Comment by psy-q** [comment]
The murmurings have become louder already, but no definite dates still.

**Comment by nadjaweisskopf** [comment]
latest leihs Upgrade (4.0) to PostgreSQL documented in Github! 
Please check the upgrade desciption: https://github.com/leihs/leihs/wiki/Deployment
