### ISSUE TITLE
my rentals: detail page - development

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1175]
#904 

- [x] wire "Cancel Rental" (Bestellung stornieren), with confirmation dialog & success notification
- [x] list of inventory pools + progress bars
  - [ ] ensure nadjas special test case is handled correctly https://madek.slack.com/archives/C023U6C505S/p163637832402030

**Comment by eins78** [comment]
* @urs-van-binsbergen made a demo of the concept in form of storries. concept was approved by the team 👍 
* @nimaai will now implement the concept

**Comment by urs-van-binsbergen** [comment]
@nimaai
- commit: https://github.com/leihs/leihs-borrow/commit/77098e3e8a2086fe9072229954b9067457c6adbd
- spec for rental detail: `spec/features/rentals/rentals_show.feature`
- Storybook path Wireframes / Meine Ausleihen / Status Summary

**Comment by urs-van-binsbergen** [comment]
Implemented status summary views and feature specs: 
https://github.com/leihs/leihs/commit/1fd5c3e5a26ae06bad3413f4d30a385ad37798e0

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen can you please show me what has been done on the second point "list of inventory pools ....."?

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf We decided to remove list of inventories (at least for this milestone). So its only about the progress bars: implementation of these stories: https://ui.leihs.app/?path=/story/mobileapp-wireframes-meine-ausleihen-status-summary--structure

**Comment by nadjaweisskopf** [comment]
nadjas test case: create a reservation in lending app (without order)

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen I did not get an acceptance msg. after deleting the not yet accepted order.

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf So far we don't have messages when the effect of a command is clear from the context (e.g. here Status changes from "Confirm..." to "Rental was canceled"). Maybe we should discuss principle this in general.
