### ISSUE TITLE
new borrow: Image Thumbnails

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1188]
* use `imgproxy` as local resizing proxy
* API generates the image-urls to be used in the frontend
* decide how to constrain the possible sizes (either size classes, or allowed parameter ranges(
* apache needs to be setup as a caching proxy in front of `imgproxy`

**Comment by neoheat** [comment]
not really necessary

**Comment by neoheat** [comment]
@nadjaweisskopf is it not already possible to switch the person of the order in lending?
