### ISSUE TITLE
HTML attachments.

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#119]
We used to be able to add an attachment with a .html or .htm address. This allowed us to make a javascript redirect file with a URL.  ie. We could use it to redirect to a video hosted on an internal server.

This now appears to save correctly, but doesn't get attached to the model.  Some digging in the log shows that it rolls back?

Command :: file -b --mime '/tmp/36fd2ec3934fbe1fe8b9b4d00cf47ca720160321-27822-24c34g.html'
[paperclip] Content Type Spoof: Filename 
[1m 35m (0.1ms) 0m  ROLLBACK
Completed 200 OK in 390ms (ActiveRecord: 0.7ms)

The paperclip line is stupidly long and breaks this form if I try and load it at it's full length, but it appears to contain lists of approved MIME types.

Is there another way around this?

Thanks,

Anthony.

**Comment by nimaai** [comment]
This seems to be related to: https://github.com/leihs/leihs/issues/128

**Comment by nadjaweisskopf** [comment]
@AnthonyHunt Does the problem still persist or could the problem be solved --> see ticket #128 ?

**Comment by nadjaweisskopf** [comment]
Will close this ticket, please reopen if still a problem.
