### ISSUE TITLE
Order Panel: add delegation selector

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1199]
```
i go to catalog
i select my user in delegation filter
open order panel
my user is pre-selected in delegation select

i go to catalog
i select delegation x in filter
the availability data for the calendar is refreshed
app-db saves current filter and last selected delegation
open order panel
delegation x is pre-selected in delegation select
i add to order

now i have a cart with a reservation for delegation x,
that means i can not add reservations for another user.
i can filter tho!

i go to catalog
i select my user in delegation filter
i open order panel
delegation x is pre-selected in delegation select
delegation select can not be changed!
```

---

ui

![Screen Shot 2021-10-20 at 09 43 28](https://user-images.githubusercontent.com/134942/138049763-16475c1e-9f2e-4d8d-8324-b2811a27f4e4.png)

* https://github.com/leihs/leihs-ui/commit/78161fce184d03e1c8344edadac59ac9f56802a0
* https://github.com/leihs/leihs-borrow/commit/751c6fb7978a9b477d1ef686c320c149c30b61d2

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/794c113edafe1f7ca59eda9340129bf2e176f337

most parts of the spec covered already in various (already existing) tests.

**Comment by nadjaweisskopf** [comment]
The ticket as it is is tested and ok. But I have some problems understanding the error msg. and the behaviour of the button "Hinzufügen". I have created new tickets for these cases.
