### ISSUE TITLE
Consolidate error handling in UI

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1203]
- Inventory:
    - The blue box from `ErrorBoundary` (triggered from component rendering)
    - The salmon `[error-screen]` (bound to app db `:meta :app :fatal-errors`, triggered by some features)
    - The salmon `[error-view]` (directly displayed by some features)
    - the bright turquoise `[retry-banner]` (interceptor in `requests.cljs` `::retry-mutation`...)
    - The red `ConfirmDialog isError=true` (not used yet)
  - Thought cloud:
    - Harmonize look & feel
    - Centralize error state or not?
    - "Request framework"?

**Comment by nadjaweisskopf** [comment]
needs a concept UI, technical
typical example: #1303

**Comment by nadjaweisskopf** [comment]
Discussion in group: technical information should at least be collapsable to give information for problem solving. According to how often a problem arises, the solution should be designed.

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen will begin with printscreens, cleanup, concept proposal

**Comment by urs-van-binsbergen** [comment]
Since #1303 as such is closed, but is a typical case to be better handled, I will describe it here:
- User had a cart with valid items
- After some waiting he sends the cart

**Comment by urs-van-binsbergen** [comment]
Suggested Measures:
  - 1) More proactive validation
  - validate the cart when the action button "Send order" is clicked and before submitting the "Send order" dialog
  - re-check availability before submitting the "Add item" and "Edit item" dialog
  - (etc. where meaningful)
- 2) Consolidate UI
  - Story: https://leihs-styleguide-git-uvb-error-ui-leihs1.vercel.app/?path=/story/mobileapp-wireframes-errors--errors
  - 2 error components:
    - __Errors in render__: like the existing inline-alert with buttons "Reload page" and "Go to start page" (+ add german translation)
    - __Event-triggered errors__: Error notification (modal dialog style). Buttons: "OK" + "Retry" when available (mutations).
  - No inline banners anymore (like the "salmon" message)
- 3) Optimize handling of event-triggered errors:
  - General error queue in app db (not persistent)
  - General error interceptor
  - Detect general well known errors, i.e. when no connection to server (differentiate between server not reachable and "you are offline")
  - Maybe detect expectable specific errors (although proactive validation should prevent most of them)

**Comment by urs-van-binsbergen** [comment]
Ready for demo... 

- Concept:
  - ✅ Story: https://leihs-styleguide-git-uvb-error-ui-leihs1.vercel.app/?path=/story/mobileapp-wireframes-errors--errors
  - Three error components:
    - ✅ __Errors in render__: like the existing inline-alert with buttons "Reload page" and "Go to start page"
    - ✅ __Routing-triggered errors__: like the existing inline-alert with buttons "Reload page"
    - ✅ __Event-triggered errors__: Error notification (modal `ConfirmDialog` style)
- What is done:
  - ✅ Localize all error components
  - ✅ Harmonize the design of error components
  - ✅ Make sure loading state goes go away when a error happens 
  - ✅ Make sure error state goes away when action is repeated with success
  - ✅ Handle unauthenticated requests (status 401) in error views, remove the separate component `login-error-screen`
  - ✅ Hide "retry banner" (more ) 
  - ✅ Replace all calls to JS `alert()`
  - ✅ Finetune all routes and actions to conform with the concept 
  - ✅ (Tech) Establish global error queue in `:meta :app :errors` (formerly `:meta :app :fatal-errors`), with centralized event handlers (`lib/errors.cljs`)
  - ✅ Fix failing specs https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/f39d63b3-fb5d-4911-a792-f4be2935f0a7
    - `request_framework.feature`
    - `search_results.feature`, but only because of https://github.com/leihs/leihs/issues/1373 (already fixed)
- Advanced (not done):
  - ℹ️ Opt: More helpful error messages
    - Specific human readable messages like "Verfügbarkeit konnte nicht geladen werden"
    - HTTP status 0 = server could not be reached
    - HTTP status 404 = resource not found (would need some work on server side resolvers)
  - ℹ️ Opt: Prevent well-known errors via proactive validation (not done in this round)
    - e.g. validate the cart when the action button "Send order" is clicked and before submitting the "Send order" dialog
    - e.g. re-check availability before submitting the "Add item" and "Edit item" dialog
  - ❓ `ErrorBoundary`: Is it possible to recover on routing navigate? (Currently only on hard reload)
- Findings
  - ✅ ErrorBoundaryView auf Windows hat Scrollbars (overflow-scroll, s.a. scrollbar-gutter)
  - ✅ `category-show/view`: Remove second query which only gets the path sensitive label (i.e. "Video > Stative" instead of "Video > Stative Video"). This never really worked (random and flickery behaviour).

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen seems to be ok. I tested as far as I could - and in the two languages G/E. But - could you please change the text to "..... nicht angemeldet" instead of ".... nicht eingeloggt"? Thanks  

![grafik](https://user-images.githubusercontent.com/3356016/180246710-573c300f-4b0b-4dda-be9e-12d3fc0dd501.png)
