### ISSUE TITLE
Creator information e.g. for Models and Item 

### ISSUE THREAD

**Issue by ClaesFredo** [leihs/leihs#121]
Our LEIHS database contains many different and technical Categories. When using temporary employees to add Model and Item information, things frequently go wrong and finding faults can take time. 

It would therefore be a very useful QA feature to be able to see/filter on the Creator ID, possibly also in the Helper section.

Sincerely
Claes

**Comment by ClaesFredo** [comment]
Hi

On the same note. A timestamp as to when information was added/modified is useful for QA purposes. 

/C

**Comment by nimaai** [comment]
Items and models are being audited in leihs. Under `/admin/audits` you can see, who and when created which model/item.

Please take a look and let us know why you wouldn't be able to get the information you need with the help of this already existing feature.

**Comment by nadjaweisskopf** [comment]
I'll reopen the issue, if the information in the admin-section does not suit your purpose.
