### ISSUE TITLE
Order panel: never-ending loading state when re-opened

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1211]
Steps to reproduce: 
- Open detail page of a model
- Add item to cart
- Click "Add item" again
- Dialog opens, but calendar says "Loading" forever and is not clickable

**Comment by nimaai** [comment]
https://github.com/leihs/leihs-borrow/blob/83057ce10e5d571833b654e2b488b795890c8e25/src/client/leihs/borrow/features/model_show/core.cljs#L237-L242
