### ISSUE TITLE
OpenID Connect auth adapter?

### ISSUE THREAD

**Issue by tmulzer** [leihs/leihs#1213]
For some reasons we'd like to use keycloak as an authentication source for leihs. We're in a university environment, either.

But ..
The examples of authentication adapters in the leihs main repo don't work for us. 
The one most close to our environment is that one:

https://github.com/leihs/azure-active-directory-leihs-authentication-system

But that one is written very specifically to microsoft azure active directory - and I'm not able to adapt it to the OpenID Connect standard, provided by keycloak.

Is there anyone in the community, who already adapted this example to keycloak?

Kind regards,
Tasso

**Comment by DrTom** [comment]
There is a updated and slightly improved version of this adapter https://github.com/functional-swiss/leihs-aad-auth
But this is still only for the Protocol Microsoft uses and we are not aware of any generalization. 

It should be not too hard to extend this or write something new which covers what you need.

**Comment by neoheat** [comment]
We don't provide a general OIDC authentication adapter. But as @DrTom has mentioned, there is an uptodate adaptation of the Microsoft Azure AD connector available.
