### ISSUE TITLE
models filter: modal fine tuning

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1216]
- [x] `(t :!borrow.rental-show.user-or-delegation-personal-postfix)` - this is a cross reference to a translation key belonging to another feature, which I would avoid. We should move this expression to "GENERAL PHRASES".

UI/Design improvements (as discussed: probably in a separate pull request, partly by frontend dept.):
- [x] Wrap form elements in a `form` tag, submittable by enter
- [x] Reset button: Not in design spec, but maybe useful; breaks button layout however.
- [x] Improve Availability filters (from, to, quantity).  
- [x] Discuss placeholder attributes (not clear from design spec), in general. Here specifically for the keyword field. "Suchbegriff eingeben" is a call to action which is not ideal imo. - Remark uvb: This is a nitpick and controversial, so I check it "done".
- [x] X icon for reseting search term does not work. we are using plain `input` element instead. (leihs/leihs#880)

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen It's hard for me to test this ticket. Can you please set the label "accepted" if you have tested the points above or we go through the points again in Demo.
