### ISSUE TITLE
favorites do not open

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1219]
How to reproduce

- open menu
- choose "favorites"
- I get an endless spinner with no error

**Comment by urs-van-binsbergen** [comment]
Same here. Service delivers `nil` instead of `[]`, when the user never marked a favorite I guess (a workaround would be to add/remove a favorite).

**Comment by urs-van-binsbergen** [comment]
More issues
- The current catalog filter is applied, which does not make sense
- The query does not filter by user ;)
