### ISSUE TITLE
When handing over an item, only the first 20 items in each model can be selected

### ISSUE THREAD

**Issue by samhsuqld** [leihs/leihs#122]
As shown here, we have 51 x HP 4320s in the system:

![selection_163](https://cloud.githubusercontent.com/assets/7960885/15312585/c774de8e-1c48-11e6-9454-634e38ad3e14.png)

However, when doing the hand over, you can only select from the first 20 (there should be another 31 laptops after 10199).

![selection_164](https://cloud.githubusercontent.com/assets/7960885/15312591/e08e05bc-1c48-11e6-9110-a26a61a7a2c4.png)

Manually typing in the asset name doesn't work, as it needs to be selected from the dropdown. This makes it impossible to hand over laptop 10220, for example.,

**Comment by samhsuqld** [comment]
I've discovered a workaround: it's possible to type the inventory code into the 'Add/Assign' box, although it requires a refresh of the page for it to show up. It's not as convenient though, as it requires you to type the exact code and there's no dropdown to choose from (for individual items)

**Comment by psy-q** [comment]
Which version of leihs is this on? This shouldn't be the case, you should be able to see all of them even initially.

**Comment by pape-io** [comment]
If you know the items code '10220' just enter it. The list will filter accordingly. Showing all items is not a solution that scales. You should fix your offline process. There should be a way to enter any kind of information to the field that helps you to narrow down the results and find the actual item in the end.

Can you elaborate on "why" it has to be selected from the autocomplete manually?

**Comment by samhsuqld** [comment]
Although I tried entering the item code directly, I didn't realise that you had to hit Enter to 'lock it in'. This solves the main problem we were having.

You can see in [this video]([https://www.youtube.com/watch?v=uYCm4Msljls) that once I type 102, the dropdown disappears instead of showing 10200, 10201, etc. I'm not sure if this is intended behaviour or not. If it is, please close this issue and accept my apologies.

We are currently running the latest version (3.37.4).

**Comment by nimaai** [comment]
Yes, it is the intended behaviour. The autocomplete box disappears as it can not find what you have typed ("10220") inside of the 20 items (the last one ending with "SUQLD-10199"). But, you can assign the desired item to the reservation line by typing in the **whole** inventory code (I assume "SUQLD-10220") and pressing enter. 

We are planning to completely refactor the hand over page in future and thus might be having an opportunity for a scalable solution which would deal with your initial problem/question.
