### ISSUE TITLE
inconsistent spec step precedence

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1223]
Affected scenario/step: 

https://github.com/leihs/leihs-borrow/blob/91852b1da9800ad79bd9a4a1bbd579a1ef990cc6/spec/features/rentals/rentals_index.feature#L98

The step `And I enter "day after tomorrow" in the "Until" field` is defined here: 

https://github.com/leihs/leihs-borrow/blob/91852b1da9800ad79bd9a4a1bbd579a1ef990cc6/spec/features/rentals/rentals_index.steps.rb#L8

This works on localhost and CI.  

However if we move the step definition into `features/rentals/shared/common.steps.rb`, the equally named step from `features/shared/common.steps.rb` will have precedence _when run on CI_, which is unexpected. On my dev host (osx) the behaviour is as expected.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/54d9833c1846cae49950471948806c82d294daef
