### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1225]
Check wiki in github NWE

* User Manual https://github.com/leihs/manual
* Developer Docs https://github.com/leihs/leihs_documentation
* Wiki https://github.com/leihs/leihs/wiki

**Comment by eins78** [comment]
* manual will be moved to wiki
* technical specs - gherkin/cucumber scenarios
* docs must be part of "definition of done"

**Comment by nadjaweisskopf** [comment]
Desicribes New Borrow in documentation
