### ISSUE TITLE
cart/calendar: error msg. doesn't give enough information

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1227]
The error msg. in the cart does not help me to solve the problem. It says "an item is not valid" - but what exactly is the problem? I could add it to the cart so I would have assumed everything is ok. 

How to reproduce: 
1. go to catalog with you own user
2. search for model "Astera Titan Tube FP1-Set mit 8Stk. ..."
3.  add the model at a valid date
4. check the cart --> error msg. saying the item is invalid

**Comment by eins78** [comment]
* errors from calendar(s) also in cart overview
* ther error cases also with message (from https://github.com/leihs/leihs/issues/1215)
