### ISSUE TITLE
cart: reservations lines sometimes not clickable

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1232]
How to reproduce: 
- run `bundle exec rspec spec/features/shopping_cart/edit_reservations.feature` in `borrow`
- sometimes the step on line 34 `And I see the "Edit reservation" dialog` will fail, the dialog in fact not being shown.

**Comment by urs-van-binsbergen** [comment]
What happens (found by running the spec in dev mode with reframe-10x enabled and analyzing the events):
- The event `:timeout/refresh-timeout` is fired by the `:routing/change-view` (as in every view, not only in the cart) 
- Sometimes refresh-timeout takes longer then the cart view's own loading routine, so that `:timeout/on-refresh` fires after things were loaded and the test runner already has opened the dialog (:cart/data :edit-mode in db)
- `:timeout/on-refresh` will overwrite the :cart/data key in db then, :edit-mode will be lost and the dialog be closed
- Sometimes the dialog will not even open on repeated click. This is the case when the `:on-fetched-availability` fires after the cart was overwritten, because it will assoc `:edit-mode` again, but only part of it. The dialog would open again, but crashes. When the user clicks again on the reservation line, the dialog will not open because there is a check whether the :edit-mode key already is in db (to prevent double loading).

**Comment by eins78** [comment]
@urs-van-binsbergen according to your description, this bug might be related/have the same cause: https://github.com/leihs/leihs/issues/1152
