### ISSUE TITLE
Some ui fixes and cleanups

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1234]
- HTML/CSS bugs
  - [x] The cart shows a disabled `select` for the delegation, which has class `form-control` instead of `form-select`, this looks terrible in Safari and older Firefoxes. Anyway, the `select` is unnecessary, just use plain text
  - [x] Loading screen of model detail view (and some others) is weird
    - [x] Unify all view loading indicators: `[ui/loading]`
- Design improvement (spec conformity)
  - [x] `SquareImageGrid`
    - Brand name should have light font, not gray font (gray font is foreign to the design spec)
  - [x] `Warning`
    - Must not have `margin top`. Components never should have hardwired margins, especially not margin top. Better solutions: margin bottom on the element above / set margin top from outside with `className` (or control the gap the two elements with Stack or flex gap, but this might be over the top here).  
  - [x] `OrderPanel`
    - Hint "Can't change delegation": Is not a `Warning` (+ fix typo "delegation" lower case in german) 
- Wrong PropTypes
  - [x] Cart, edit reservation: Failed prop type: The prop `userDelegations` is marked as required in `OrderPanel`, but its value is `undefined`. in OrderPanel 
  - [x] Story "Meine Ausleihen/Details/Details Return": Invalid prop `title` of type `object` supplied to `ProgressInfo`, expected `string` (sollte wie immer auch JSX zulassen)
- Story-only issues
  - [x] Story "Wireframes ... Gegenstand bearbeiten": Crash "Missing locales"
  - [x] Story "Integrated Components ... ModelShow": Crash "Cannot read properties of undefined (reading 'addItemToCart')"
  - [x] Story "Design Components/Content/DownloadLink": validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`
  - [x] Story "Overview" and "Translations": Cannot find "defaultViewport" of "false" in addon-viewport configs, please check the "viewports" setting in the configuration (should be `'reset'`).
  - [x] Menu story has a broken animation. Remove bootstrap `Collapse`, implement story as in the app. 
  - [x] Mark "integrated components" in stories which are not used anymore
  - [x] Change descriptions in "Overview" to better match reality  
  - [x] Add story for `CategoryBreadcrumbs`

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen I can not test this ticket... it's too technical and cryptic. Could you please set the label as "accepted" or show me what I can test?
