### ISSUE TITLE
Possibility to mark as "procured" 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1235]
#### Expected behaviour or future wish

The roles Admin, Inspector and Viewer need the possibility, to mark an order as "procured" and set a comment. 
Rollout of feature would be beginning Jan, after the budeting phase has ended. 

Procured-Checkbox shall always be visible, even though the budget phase has not ended. 

Betrachter sollen nicht Beschaffungsfelder anpassen können
Beschaffungskommentar soll mandatory sein, sobald der Status nicht "nicht beschafft" ist. Mind 3 Zeichen? 

```gherkin
Scenario: Mark order as procured and set a comment as Admin, Inspector or Viewer??
When I log in as Admin
And I navigate to the procurement
And I open an order
And Then the procured status is set to "not procured" by default
And the procured comment field is empty
When I choose the procured status "procured"
And I enter a comment
And I save the order
Then the order has been saved as "procured" with a comment

Scenario: Changing the procured status
When I log in as Admin
And I navigate to the procurement
And I open an order which has been marked as "procured"
And a procure comment has been entered
And I choose the procured status "not procured"
And I save the order
Then the order is saved as "not procured"
And the comment is still shown -- deleted??

Scenario: Set filter procured as Admin
When I log in as Admin
And I navigate to the procurement
And I choose the order status "accepted"
And I choose the procured status "procured"
Then all accepted orders which have the status "procured" are shown

Scenario: Set filter procured as Insptector or Viewer
When I log in as Inspector or Viewer
And I navigate to the procurement
And I set the procured status filter to "procured"
Then all orders of the categories are shown, where I have access to and which are marked as procured

Scenario: procurement comment in search field 
When I log in as Viewer
And I navigate to the procurement
And I search for a procurement comment in the search field
Then all orders of categories are shown where I have access to and where the procurement comment matches the text are shown

Scenario: Export to Excel or CSV
When I log in as Admin
And I navigate to the procurement
When I export to excel or CSV
Then the status "procured" is exported
And the procurement comment is exported


*************FOR A FUTURE RELEASE*************
Scenario: Enter default procurement comments
When I log in as Admin
And I navigate to the procurement
When I export to excel or CSV




#### Issue or wish reported by
ITZ- SUSO

#### Current behaviour
There is no possibility to mark an order as procured

#### Acceptance Criteria
- new checkbox - procured
- new comment field
- new filter
- enhance the search field with new search criteria
- check that budget phase has ended
- all roles but the requester should have the possibilies above
- reuse style of existing fields
- aut. tests are written

#### Specifications
- Leihs version: 6.2.3

Possible prototype:


<img width="956" alt="142874029-d9f01ac8-f54f-4e3b-ae3c-6b40066ad316" src="https://user-images.githubusercontent.com/134942/143456435-f7d44262-de3c-4dc0-9236-9edf78d7e4ba.png">

**Comment by eins78** [comment]
@nadjaweisskopf I am not sure about the showing/hiding of the comment field. Especially if we keep the value when the box is selected. Instead, the field could be enabled/disabled according to the checkbox, so the user can still see the saved value.
But: I am not sure why we need to restrict to comment to only be editable when the box is checked. E.g. it could contain a link to the shop where we *plan* to order something, but haven't yet.

**Comment by nadjaweisskopf** [comment]
Change the scenario, so the comment field is always shown.
New idea: status "procured" is not a status but a new filter section which could be enhanced through other filters in future.

**Comment by eins78** [comment]
<img width="214" alt="Screen Shot 2021-11-29 at 14 42 33" src="https://user-images.githubusercontent.com/134942/143878549-75f83847-101f-4bfb-bc7e-389c0b900aa5.png">

**Comment by eins78** [comment]
Question to ponder: we already have 3 quantity fields: `requested`/`approved`/`order`. how does the `order_quantity ` relate to this feature? 
This might just be more about documentation, technically all those fields have no relation yet. 

I interpret it thusly:
* exisiting field `order_quantity` = how much will be or was procured?
* new field `is_procured` = was it actually ordered yet or not?

**Comment by eins78** [comment]
Work in Progress

* UI done, with some changes to make it simpler and extendable
* API schema done

TODO in the backend:
- [ ] DB migration, add the 2 fields
- [ ] API: implement fields
- [ ] API: implement request filter by `order_state`

TODO general:
- [ ] specs
- [ ] review translations

---

![Screen Shot 2021-12-09 at 09 29 59](https://user-images.githubusercontent.com/134942/145389431-c7ae9fd3-7512-4845-8cd9-012d38da183d.png)

**Comment by nadjaweisskopf** [comment]
@eins78 @nimaai We need a third status called "In Bearbeitung" / "In Progress" (In dropdown and in filter)
And would be great if we finish the development until mid. Jan 2022

**Comment by nadjaweisskopf** [comment]
Input from L. sometimes a different product is bought - would be nice to see this in a status. something like "procured but different product"

**Comment by eins78** [comment]
OK. Ideally we'll have a final list of those states before implementing the backend, or it will be more work than neccessary. Later additions need an API extension, and a DB migration (but no frontend changes other than translations).

* all states would all be filters in the sidebar as well. they can have a different label if needed.
* each request **can only have 1 state**, or it will get too complex (meaning for example that only one of "PROCUED" or "ALTERNATIVE_PROCURED" can be true at the same time)

table of current wishes:

| enum | German  | English |
| ----------------- | - | - |
| `NOT_PROCURED` | Nicht Beschafft | Not Procured |
| `IN_PROGRESS` | In Bearbeitung | In Progress |
| `PROCURED` | Beschafft | Procured |
| `ALTERNATIVE_PROCURED` | Ersatz Beschafft | Alternative Procured |

**Comment by nimaai** [comment]
Open questions:
* What about all the existing requests (budget period in all phases). Should we set any order status or leave the field empty? It's not a required field anyway, as far as I have understood.

**Comment by nadjaweisskopf** [comment]
@nimaai Good point - I need to enhance the scenarios to make sure, the field is mandatory and the default when creating an order is "not procured". But I need to check with the stakeholder, will give you a feedback until latest monday.

**Comment by eins78** [comment]
dev notes: still lots to do in backend…

* renaming `order_state` to `order_status` to align with backend
* permissions in relation to budget phase unclear
* required comment not yet implemented 
* `order_status` is implemented as "postgres enum", which are uppercase. needs to be handled in backend (similar to but slightly different from `(inspector_)priority`

**Comment by eins78** [comment]
@nimaai here is my WIP commit where I a) renamed to field and b) tried to fix some of the issues https://github.com/leihs/leihs-procure/commit/f0480b71dc4b8903adc71fa9d145818bf79535ab

**Comment by eins78** [comment]
@nadjaweisskopf please define the permissions so we can implement them. concrete questions:
* can role `category viewer` edit those fields or not?
* "requester can not edit" when requester has also higher roles like inspector or admin – which has precedence? meaning, does it matter at all if I am editing "my" request?

**Comment by nadjaweisskopf** [comment]
@eins78 let's leave the role "viewer" as it is. The viewer can only read, not write. 
The requester should not be able to edit the fields. Same behaviour as with the accounting fields. 
The admin can edit these fields, no matter who the request is from. 
The inspector can edit the fields but only of requests which belong to categories he needs to manage. 

this should be the same logic we already have for several other fields - with the big change, that the fields are editable even though the budget page has ended.

**Comment by eins78** [comment]
@nadjaweisskopf thanks, i think now all cases are defined.
@nimaai please my code check the above comment:


```clojure
; used for order{_status,comment}.{read,write}
can-edit-order-status-fields (and existing-request (or admin category-inspector))
can-read-order-status-fields (or can-edit-order-status-fields (requester own-request) category-viewer)
```

compare with current permissions for accounting fields: https://github.com/leihs/leihs-procure/blob/d093c99db7ff08923f126752715f4bdbf6721bf1/server/src/all/leihs/procurement/permissions/request_fields.clj#L48-L71

**Comment by eins78** [comment]
@nadjaweisskopf one more detail question about the excel export. Should the status field have the "constant" value we use internally, or should we translate/map it like in the UI?
E.g. by default it says `IN_PROGRESS` but we could also output `In Bearbeitung`.

<img width="298" alt="Screen Shot 2022-02-02 at 13 59 14" src="https://user-images.githubusercontent.com/134942/152159088-d5dbcb6a-9e16-4c62-bf31-90f2ded94033.png">

**Comment by eins78** [comment]
UI-only detail, not important, but i asked lenny for input: what colors should the stati have? One could argue "replacement ordered" is either success-green or warning-yellow…

images show current and available colors

---

<img width="302" alt="Screen Shot 2022-02-02 at 14 36 20" src="https://user-images.githubusercontent.com/134942/152173218-6d7fe519-051b-472c-b1b4-bc57b17e9e94.png">

---

<img width="547" alt="Screen Shot 2022-02-02 at 14 36 47" src="https://user-images.githubusercontent.com/134942/152173267-3b375083-d9c0-4f1e-95e7-886c272a15f5.png">

**Comment by eins78** [comment]
@nadjaweisskopf ready to test on https://nimaai.ruby.zhdk.ch/procure/

**Comment by nadjaweisskopf** [comment]
@eins78 Ich würde "In Bearbeitung" ins Export-Excel schreiben.

**Comment by nadjaweisskopf** [comment]
Test Feedback

The new feature looks great. I have asked Lenny to test and give me feedback as soon as possible. I found following strange behaviours but that shouldn't keep Lenny from testing. 

1. The title of the text field should not have a "*", it is not mandatory.
2. If a status is set, f.e. "In Bearbeitung" but the checkbox of the filter "In Bearbeitung" is not marked, I got an error but couldn't reproduce it - so it might have been just temporary: 

<img width="846" alt="Filter_error" src="https://user-images.githubusercontent.com/3356016/152423122-0203e533-c909-42ce-a3ab-a6e373168316.png">

3. When I save the order as "Beschafft" and the checkbox "Beschafft" is not selected, then the question is, if the order should disapear from the list after saving or still stay listed for the user to see the last change. 

<img width="817" alt="filter not set but saved as in bearbeitung" src="https://user-images.githubusercontent.com/3356016/152423441-3ed50faf-c36c-47e1-b396-ec777a6caaf9.png">

**Comment by eins78** [comment]
> Test Feedback
> 
> The new feature looks great. I have asked Lenny to test and give me feedback as soon as possible. I found following strange behaviours but that shouldn't keep Lenny from testing.
> 
> 1. The title of the text field should not have a "*", it is not mandatory.

It is mandatory when any other status than "NOT_PROCURED" is set. But, currently the field is always marked as mandatory, will look inot that.

> 2. If a status is set, f.e. "In Bearbeitung" but the checkbox of the filter "In Bearbeitung" is not marked, I got an error but couldn't reproduce it - so it might have been just temporary:
> 
> <img alt="Filter_error" width="846" src="https://user-images.githubusercontent.com/3356016/152423122-0203e533-c909-42ce-a3ab-a6e373168316.png">

It says "Network Error", so most likely it was a connection error. In case that happens again, try click on the line (above the error) again to close it, then click again to open. If the error comes again, its a bug.
 
> 3. When I save the order as "Beschafft" and the checkbox "Beschafft" is not selected, then the question is, if the order should disapear from the list after saving or still stay listed for the user to see the last change.

Current behavior is: The line stays in the list after it is saved, even if it does not match the filters anymore. This is because we dont do a full reload for performace reasons (we just refetch the "sums and amounts"). The line will then vanish on any next change of filters (if its still excluded of course).
I can see if we can change so the line immediately disappears, that would more match the "this is my todo list" mental model of the person handling the ordering.

**Comment by eins78** [comment]
> It is mandatory when any other status than "NOT_PROCURED" is set. But, currently the field is always marked as mandatory, will look inot that.

@nadjaweisskopf this is a tricky detail in any case, maybe we just want to remove it (making this field never mandatory)? I dont see why we would need to enforce text entry, even for simple cases where the status is sufficient.

to be clear, i mean this requirement: 

> Beschaffungskommentar soll mandatory sein, sobald der Status nicht "nicht beschafft" ist.

**Comment by nadjaweisskopf** [comment]
@eins78 yes, the requirement came from Lenny but I am sure, not all users will want to write something. I wouldn't enforce it either. So we should take away the * and give the possibility to leave it empty.

**Comment by eins78** [comment]
@nadjaweisskopf 
* the comment is now never mandatory
* regarding the question if the line should vanish if the state changes to not match the filter anymore: I compared to the regular status and it behaves the same (As an inspector, I filter for only new and approved request. When I reject an request, the line stays until I refresh/do something else). I suggest we leave it as is for consistency (I also like that the line stays because in case of an accidental edit I can fix my error quickly.

**Comment by nadjaweisskopf** [comment]
@eins78 yes ok. let's leave it that ways. I will test with Lenny on monday morning.

**Comment by eins78** [comment]
@nadjaweisskopf all done, ready to test on `nimaai` server.

ref: https://github.com/leihs/leihs/commit/1a105ebb0f490ab08dc404126b45200bb477d37c

**Comment by nadjaweisskopf** [comment]
Test restults from Mike, Lenny and Adi: 

- The status "Ersatz beschafft" is not needed
- Lenny would very much like the text field to be mandatory. The other stakeholders don't always write a text. We need to decide. I would say we leave it as it is now - not mandatory. 
- We need an additional status called "unknown" or "open" as default.

**Comment by eins78** [comment]
renaming:


| enum | German  | English |
| ----------------- | - | - |
| `NOT_PROCURED` | Nicht Bearbeitet | Not Processed |
| `IN_PROGRESS` | In Bearbeitung | In Progress |
| `PROCURED` | Beschafft | Procured |
| `ALTERNATIVE_PROCURED` | Alternative Beschafft | Alternative Procured |

**Comment by nadjaweisskopf** [comment]
wait for debian update on server to release this feature.

**Comment by nadjaweisskopf** [comment]
1. The label "Nicht beschafft" and the value in the drop down inside the request are not the same. 

Filter: is "Nicht bearbeitet"
Value in request: "Nicht beschafft"

Please set both to "Nicht bearbeitet"

<img width="1263" alt="Procured_filter_value" src="https://user-images.githubusercontent.com/3356016/156589295-ce36cbff-29d1-4a91-9079-6c302c8afc2f.png">


I assume we will need an additional status called "wird nicht beschafft" but let's wait for the feedbacks from stakeholders in production. 

2. The requester can see the filter and the text even though the phase has not ended. This is not the same behaviour as with the accounting fields as far as I can see https://github.com/leihs/leihs-procure/blob/d093c99db7ff08923f126752715f4bdbf6721bf1/server/src/all/leihs/procurement/permissions/request_fields.clj#L48-L71

{:accounting_type
       {:read (or (and requester own-request (or inspection-phase past-phase))

Can we discuss this tomorrow morning? We could also leave it as it is for the moment but If you anyway have to adjust for point 1 above than this might be a quick change.

**Comment by eins78** [comment]
@nadjaweisskopf I am not working this Friday, we can discuss next week. 
Point 1 is a simple copy/paste error that can be fixed easily.
Point 2 would be a change but also easy (visibility for requester was not specified yet as the ticket just says "Procured-Checkbox shall always be visible, even though the budget phase has not ended.")

**Comment by nadjaweisskopf** [comment]
@eins78 @nimaai will create a new release with the typo change and the changed behaviour for requester.

**Comment by eins78** [comment]
@nimaai please check this change. its a tiny change but should fulfil the requirement "The requester can see the filter and the text even though the phase has not ended.", right?

```diff
can-edit-order-status-fields (and existing-request (or admin category-inspector))
can-read-order-status-fields (and existing-request 
                                  (or can-edit-order-status-fields category-viewer 
-                                       (and requester own-request)))]
+                                       (and requester own-request past-phase)))]
```
