### ISSUE TITLE
configure pools to reserve from query in regards to max visits

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1236]
Change [this query](https://github.com/leihs/leihs-borrow/blob/master/resources/all/sql/pools_to_reserve_from.sql#L46) to acommodate different use scenarios (`<` vs. `<=`). Before creating a reservation we need `<` but when checking validity of an existing reservation in cart we need `<=`.

**Comment by urs-van-binsbergen** [comment]
Visits do not contain unsubmitted orders. So I guess there is no difference before and after creating the reservation in cart?
