### ISSUE TITLE
Terminologie

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1241]
Wir wollen für core Entitäten und Konzepte fixe Begriffe festlegen und konsequent verwenden.
Dazu müssen wir es an zentraler Stelle gemeinsam diskutieren.
Die Begriffe werden in UI und Dokumentation verwendet. In der technischen Umsetzung sind teilweise notwendigerweise andere Begriffe verwendet (z.B. weil historisch so festgelegt; oder ein technischer Standardbegriff klarer ist, etc.). Umso wichtiger ist auch das mit zu dokumentieren (eine "Bestellung").

---

liste

* "Neue Ausleihe" oder "Warenkorb" oder "Pendente Ausleihe" // Entscheidung: **Warenkorb - Cart**
* "Meine Ausleihen" oder "Meine Bestellungen" // Entscheidung: **Meine Bestellung - My Order**
* "Geräteparks" oder "Verleiher" // Entscheidung: **Inventarpark - Inventory Pool** -- mit User testen und befragen (Tilo/Patrice, Roger)
* "Delegation" oder "Benutzer" // Entscheidung: Entitätenbenamsung bleiben gleich aber Anzeige: **Ausgeliehen an: / Rückgabe für: - Nadja geht alle Screens durch zusammen mit dem Delegationskonzept**
* Titel im Menü "Nadja Weisskopf" - schreiben wir **"Benutzer"** hin.
* Alle Begriffe "Modelle" austauschen mit "Gegenstände" / "Items"
* [ ] Check upper / lower cases - titlecase.com (@nadjaweisskopf )

---

ziel: glossar für docs. im wiki, alles auf 1 Seite, aber mit cross-references.
beispiel:

### *staff*

a user that has a more privileged role than `customer` for an [*Inventory Pool*][pool]: _Lending Managers_, _Inventory Managers_, _Admins_ and _System Admins_

[pool]: #inventory-pool

**Comment by nadjaweisskopf** [comment]
discuss in Jan - when everyone is back

**Comment by eins78** [comment]
zu den Bindestrichen im Englischen: https://www.grammarly.com/blog/hyphen/

**Comment by eins78** [comment]
Gedanken im Nachhinein: "Delegationen" könnten auch "Teams" heissen (in beiden Sprachen). So wie in Microsoft365 (wobei die auch "Groups" haben), GitHub, Jira, etc. Vielleicht auch eher ein Thema für später/lending, kommt drauf an wie wir es modellieren ob es eher ein "Team" ist oder ein "shared account". Unterscheidungen z.B. ob man die anderen Team-Mitglieder überhaupt sieht, etc.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf test on UVB before merging

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen can be merged, thanks!
