### ISSUE TITLE
zhdk: upgrade to Debian 11

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1245]
currently: v9 LTS. has end of life this summer, leihs master already has dropped support for it.

- [x] `test`
- [x] `staging`
- [x] `prod`
- [ ] `leihs-gw` (not strictly needed now because only no leihs installed there)
- [x] `$dev.ruby` (already done)
- [x] `next`

**Comment by eins78** [comment]
* @DrTom will coordinate with the linux team. M
* MO: snapshot - inplace upgrade - reboot - check systemd.
* for test-servers it needs to be done after 7pm, and more verification post upgrade (apps, sync, auth systems)
* `leihs-gw` could be posponed until 03.06.2022 (EOL Debian 9 LTS)

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf test procurement ticket. As soon as accepted production can be updated to debian 11.

**Comment by nadjaweisskopf** [comment]
Matus needs to solve two issues in new borrow - then tom will deploy to staging, then nadja will test and tom will coordinate with Roman. Auth-Adapters will probably need to be deployed again. Ansible needs to be upgraded too.

**Comment by nadjaweisskopf** [comment]
We will be informed by Linux-Team as soon as they will upgrade the leihs-gw. I'll close the ticket until then. All other work is done.
