### ISSUE TITLE
New translations not loaded when running specs in debug mode

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1247]
When running the specs in _prod mode_ against the test db (called `leihs_test` on my machine), all translations from `definitions.clj` are inserted into the db. However this is not the case in _dev mode_. The translations which were already inserted by the last run in prod mode are available, but not the newly changed ones. 

I would expect hot reloading of translations to work here, as it is the case when developing with the dev db (called `leihs_dev` on my machine).

**Comment by nadjaweisskopf** [comment]
@nimaai  please check if quickly done - otherwise leave as it is

**Comment by nimaai** [comment]
Reload of translations is now part of our new build/dev setup. As of now there is no hot loading whatsoever. Every change of the code base, including `definitions.clj` requires a restart of the backend server.
