### ISSUE TITLE
Can not handover to delegation if the responsible user is not a member of the delegation

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1248]
* support Case from ITZ
* the error message is not clear, so the user can not fix the problem
* in any case this situation should not be allowed, and rather handled by the `admin` app and a DB constraint

code:  https://github.com/leihs/leihs_legacy/blob/42cb3c8d60816832028b94402a63455056ea1ac4/app/models/reservation.rb#L100-L103

solution proposal:
* DB constraint: `delegation.responsible_user` must be member of the delegation
* DB Migration: add all responsibles as members to their delegation if not already (to be discussed, I do not adverse effects)
* Admin UI or DB trigger: when changing responsibles, add them as members to the delegation

**Comment by DrTom** [comment]
Yes this is a bug. 

I believe there was a bug that the responsible users was not added automatically for a short duration. Possibly this state occured then. 

It seems there a few ways to fix that.

**Comment by nadjaweisskopf** [comment]
Open questions - input from @urs-van-binsbergen: 
- If a group has been added and the responsible is not part of the group any more ... what happens with the sync? 

We will wait for @nimaai

**Comment by nadjaweisskopf** [comment]
@nimaai we should have a look at this ticket in the next iteration. We had another case at ITZ this week.

**Comment by nadjaweisskopf** [comment]
Solutions: 

- If the responsible delegation user is replaced by a new one, the old one should be deleted from the list of users and the new one should be automatically added to the user list (this should already be part of the code).
- It should no be possible to delete the responsible delegation user from the user list.

**Comment by DrTom** [comment]
@nimaai 

 I believe for the new constraint `responsible_user` we should require "direct_users"; if we would use groups managing those becomes to brittle. 

The migration should also just add every `responsible_user` to the direct users. In this way we should not have any problems with it.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/49e4df3b9837e9fc1bc15f64016c9c050196867b

**Comment by neoheat** [comment]
tested positive in https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/2e296a2a-a90f-4e0c-bb97-92b7e18409ea

- changed responsible user via selection menu 
- changed responsible user via entering the email address

what happens, if a user is deactivated and responsible for a delegation?
