### ISSUE TITLE
Delegation inconsistencies

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1249]
There are several bugs or major usability issues which stem from the mismatch between the ui concept and the actual model of the delegation feature (see list of findings below). 

Discuss:

- [x]  Extend/enhance the ui concept in order to work better with the given mechanics
- [x]  For the first going live we might disable the delegation feature (delegation users should use legacy in the first phase)

List of findings:
1. The app shows the personal user's inventory pools only. When has a delegation which has access to an additional pool, the user will not be able to order items from this pool.
2. Our concept says there should only be one cart, but there are issues in the implementation (https://github.com/leihs/leihs/issues/1246). The cart disappears when selecting delegation in filter. And, the case that another user of the delegation creates a cart is not handled.
3. Crash when cart exists and user tries to add an item which is not available for the owner of the cart.  
4. A user can add a model to his favorites which is not visible for him but for one of his delegations. But the model will not appear in his favorites list. 
5. When a user filters the model list for a delegation, his favorites are not marked. However in the model detail it is.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check every screen - which screens potentially generate problems with personal / delegation cart, screen, filter, etc.

**Comment by urs-van-binsbergen** [comment]
Draft story for a solution which works similar to the one in old borrow: 

https://leihs-styleguide-git-uvb-delegation-story-leihs1.vercel.app/?path=/story/mobileapp-wireframes-delegationen-draft-profile-switch--profile-switch

**Comment by nadjaweisskopf** [comment]
Pages with dependencies: 
<img width="660" alt="Add item" src="https://user-images.githubusercontent.com/3356016/148391126-140423c2-f34d-4551-aaf8-5f60dbfbf800.png">
<img width="401" alt="entry page" src="https://user-images.githubusercontent.com/3356016/148391130-292ede33-ca83-4847-a12b-c88b9da1df75.png">
<img width="517" alt="Kategorien" src="https://user-images.githubusercontent.com/3356016/148391132-d4f95c00-fd1f-444f-a0e3-93783eed539a.png">
<img width="814" alt="Menü" src="https://user-images.githubusercontent.com/3356016/148391135-f66cd36d-26a8-4011-bac4-f0694e5211cc.png">
<img width="563" alt="my rentals - bestellung reaktivieren" src="https://user-images.githubusercontent.com/3356016/148391137-a08a29b3-018a-4009-9cc5-18e57e13296a.png">

**Comment by nadjaweisskopf** [comment]
question: should we show a msg. when delegation user klicks on button "add favorite"? Or should the button be greyed out with an info?
question: we might need a migration, that a delegation order is dedicated to a user of a delegation, so I am not blocked as personal user to order items. 
bug: when filtering as delegation user and a cart exists for my personal user, then when navigating to the cart, the delegation user is shown in the cart. 
check: if I order an item for my user and change the user in the add item window, then I can order an item for the delegation user even though I can't.

**Comment by nimaai** [comment]
Estimates:
1. 1d
2. Disappearing cart cannot be reproduced. Sharing of the cart between multiple members of a delegation is indeed the case now. There is already a column `reservations.delegated_user_id` which is set when submitting an order. This needs to be changed to be set when creating a reservation (adding something to the cart) -> 1-2d
3. Don't understand how this should be possible.
4.-5. Basically, allow favorites only for the proper user not a delegation. Depending on which solution is chosen ->  2-3d

**Comment by nadjaweisskopf** [comment]
We decided we will drop the concept of united screens for all my users (personal and delegation). Instead we will provide the possibility to switch between the users on each screen. 

The following screens need to be changed accordingly: 

<img width="660" alt="Add item" src="https://user-images.githubusercontent.com/3356016/150329972-c51b8d94-33b2-4150-9a8d-f7b8eb09bb56.png">
<img width="401" alt="entry page" src="https://user-images.githubusercontent.com/3356016/150329981-51f4ed1e-dfb7-4465-bbed-83eb899206d6.png">
<img width="517" alt="Kategorien" src="https://user-images.githubusercontent.com/3356016/150329983-b838270d-84ef-496e-b9ff-309fb6f4c4ff.png">
<img width="814" alt="Menü" src="https://user-images.githubusercontent.com/3356016/150329985-03aa7440-9ee8-4fff-8466-0c03bd994fc2.png">
<img width="563" alt="my rentals - bestellung reaktivieren" src="https://user-images.githubusercontent.com/3356016/150329986-a69e2d4a-928c-4014-959b-2152318a8121.png">

**Comment by urs-van-binsbergen** [comment]
[Profile switch story](https://leihs-styleguide-git-uvb-delegation-switch-leihs1.vercel.app/?path=/story/mobileapp-wireframes-profile-switch--profile-switch)

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen 
@urs-van-binsbergen 
First test results - until now, and I have tested nearly all cases, it looks good and I just found these two cases:

Test results: 

1. change delegation from my user to aai ail artists in lab
<img width="604" alt="error when changing to delegation" src="https://user-images.githubusercontent.com/3356016/156052812-c19d2ac5-13d1-4dc6-a503-5ad478e0ab3a.png">

2. If I choose a pool, for which my user is suspended, we need to show an info msg. (1) like we do when adding an item to the cart (2)

(1)
<img width="397" alt="filter msgs suspended pool" src="https://user-images.githubusercontent.com/3356016/156058075-1b57cd75-35f0-40cf-97cc-ee3439cb087d.png">

(2)
<img width="418" alt="gegenstand hinzufügen msg" src="https://user-images.githubusercontent.com/3356016/156058164-ba16a481-abbb-4b6b-ad0f-07b3f46e70c9.png">

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf Thanks for the quick feedback! 

Yes, Nr. 1 (crash when switching to "ail artists in lab") is known and documented by a card,  see https://github.com/leihs/leihs/projects/15#card-78098528. The issue is not directly related to delegations, it affects also some "normal" users (who would not be able to login at all). 

Nr. 2 relates to suspensions https://github.com/leihs/leihs/issues/1252
I will implement this then (in a separate pull request).

**Comment by nadjaweisskopf** [comment]
Ticket accepted, several new tickets created
