### ISSUE TITLE
Cannot delete user: crash / unhandled exception

### ISSUE THREAD

**Issue by DerBachmannRocker** [leihs/leihs#125]
I am testing login with LDAP at the moment. User was created and upgraded to admin status. Gave user permission to use inventory pool. Removed both inventory pool admin admin rights. Cannot delete user: Leihs crashes when I click on "delete User" and throws me back to
https://leihs.my.domain/admin/users/7
The user is still there when I log back in.

There is obviously some unhandled exception going on.

In the web GUI, the user has:
Administrator: NO
Access rights: (blank)

The problem is reproducible. Clearing the browser cache did not help.

I am running Apache with Phusion Passenger. Leihs 3.34.0

![leihscrash1](https://cloud.githubusercontent.com/assets/8947781/15652019/9b2f8186-2683-11e6-94d3-888891f9bb12.png)
![leihscrash4](https://cloud.githubusercontent.com/assets/8947781/15652093/096396e2-2684-11e6-8545-40238fbc092a.png)

![leihscrash2](https://cloud.githubusercontent.com/assets/8947781/15652021/9b33f004-2683-11e6-985c-46c696428ddb.png)
![leihscrash3](https://cloud.githubusercontent.com/assets/8947781/15652020/9b31d418-2683-11e6-906f-cb3a32854e2c.png)

Here the full backtrace from production.log:
`F, [2016-05-30T16:01:40.576416 #23049] FATAL -- : 
ActiveRecord::DeleteRestrictionError (Cannot delete record because of dependent access_rights):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:14:in`handle_dependency'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/builder/association.rb:146:in `block in add_destroy_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:448:in`instance_exec'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:448:in `block in make_lambda'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in`each'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in`**run_callbacks**'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:292:in`destroy'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:281:in `block in destroy'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in`block in with_transaction_returning_status'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in`within_new_transaction'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in`transaction'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:281:in`destroy'
  engines/leihs_admin/app/controllers/leihs_admin/users_controller.rb:81:in `destroy'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in`process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  vendor/bundle/ruby/2.1.0/gems/rails-observers-0.1.2/lib/rails/observers/action_controller/caching/sweeping.rb:73:in`around'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:455:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:455:in`block in make_lambda'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in`block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in`block in around'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in`_run_process_action_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in`process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in`process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in`call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in`serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in`each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in`call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in`public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:51:in`serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in`each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in`call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in`call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.1.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in`call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in`call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in`call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in`call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:73:in`call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in`call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in`block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in`tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in`call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in`call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in`call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in`call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in`public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.27) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in`process_request'
  passenger (5.0.27) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  passenger (5.0.27) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in`main_loop'
  passenger (5.0.27) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.0.27) src/ruby_supportlib/phusion_passenger/utils.rb:113:in`block in create_thread_and_abort_on_exception'`

**Comment by nadjaweisskopf** [comment]
@nimaai can you please show me how you reproduced this bug? I couldn't reproduce it with 4.12.0

**Comment by nimaai** [comment]
@DrTom I am not sure here. In regards to our future plans and also in general, is it a good idea to delete a user even if he has *only* deactivated `access_rights` to other pools, otherwise no reservations, contracts, etc...?

**Comment by nadjaweisskopf** [comment]
Will be solved in V5 by deactivating user. Deleting will not be an option.
