### ISSUE TITLE
Search field on entry page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1251]
Evaluate, if it is possible to place a search field on the entry page, so the user can start searching straight away instead of having to open the filter bubble.

**Comment by nadjaweisskopf** [comment]
wait until ticket #1279 is finished

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/c61d309623fe44cc23d8c283e0eb8ac5ff238c51

**Comment by nadjaweisskopf** [comment]
The search terms have to be in the same order as the title itself. So f.e. if I am searching for 

Kabelrolle XLR multicore 

the search feature will not find the item if I type "XLR Kabelrolle"

Would it be possible to change this behaviour, so have an OR condition in between the search terms instead?
