### ISSUE TITLE
Suspension

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1252]
Notes from @eins78 
> * The `customer` role of a user on an inventory pool can be "suspended" for a limited amount of time or "forever", meaning until the suspension is lifted manually.
> * Suspensions have a "reason" (untranslated) and an end-date (where > year 2099 means "forever").
> * Suspensions can be created automatically if items are not returned in time, or manually by an inventory manager.

[to be specified]

- [ ] scenario "what happens when user is suspended"
  - warning on start page
  - not allowed to reserve
  - not allowed to order

- [x] API

- [ ] UI

---

legacy specs:
- https://github.com/leihs/leihs_legacy/blob/7ba7b4ee0d9dbb30871b2a3e6f3d9a9b8cb47704/spec/features/borrow/submit_order.feature#L7-L16

- https://github.com/leihs/leihs_legacy/blob/7ba7b4ee0d9dbb30871b2a3e6f3d9a9b8cb47704/spec/features/borrow/inventory_pools.feature#L15

**Comment by nadjaweisskopf** [comment]
Wait for @nimaai 

Define - what should be shown on entry page if you are suspended for certain pools
Define - should you be able to fill your cart - but the models should no block the availability

**Comment by urs-van-binsbergen** [comment]
Already implemented in https://github.com/leihs/leihs/pull/1274:

When P1 is the pool the user is suspended in:

- User can search in P1, see the model details, but he can not order the model. The "add item" dialog shows a message saying he is suspended under the pool select field. The calendar (and the availability) is not shown. 
- When an unsubmitted reservation exists from before the user was suspended, the "edit reservation" dialog shows the same, with a button to remove the item. 
- [ ] Not implemented yet in the above-mentioned PR: The reservation must be marked invalid and the order can not be put.

**Comment by eins78** [comment]
@nadjaweisskopf @nimaai @urs-van-binsbergen We talked about this in standup, matus is ready to implement as soon as the open questions are answered.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check with the lending dept. 
Do they ever set a date manually?
What if a delegated user is suspended - or a delegation? 
Should a user be able to lend items for after the suspension until date?
If not, he should get an error msg. in cart saying you are suspended. 
The dates in the calender would then be shown as holidays or weekend - grey.

**Comment by eins78** [comment]
from the "lending terms" of PZ:

> 12. Sperre
> 
> Bei wiederholter mangelhafter oder verspäteter Rückgabe können die Sektorenleitenden eine Ausleihsperre von bis zu sechs Monaten verhängen.

<https://intern.zhdk.ch/fileadmin/data_subsites/data_intranet/02_how_to/01_Campus/04_Audio-Video-Foto/03_Ausleihe_ZHdK/20210601_Ausleihreglement_PZ.pdf>

**Comment by nadjaweisskopf** [comment]
sent a mail to Roger

**Comment by nadjaweisskopf** [comment]
answers from Roger - I agree with all point. 
- A suspended user should not be able to reserve items for a delegation.
- A suspended user should not be able to send a reservation for AFTER the suspension
- A suspended user should be informed about his suspension for a pool as soon as possible. He should not be able to place items into the cart.

**Comment by nadjaweisskopf** [comment]
The catalog filter should inform the user about his suspension.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf give feedback: at the moment the user could go to borrow legacy and lend for a delegation. So we might want to allow a suspended user to order for a delegation - anyway, the responsible person is in charge of reservations for a delegation.

**Comment by nadjaweisskopf** [comment]
test on test server
