### ISSUE TITLE
model filter "max. Quantity" is unclear to users

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1254]
When adding an item to the cart, change the text in the inventory pool filter to

f.e. 

Ausleihe Toni-Areal (max. items 3)
Ausleihe Toni-Areal (max. Gegenstände 3)

<img width="960" alt="Hinzufügen" src="https://user-images.githubusercontent.com/3356016/145393291-48c61b31-3362-41d2-9086-b30819f6a76e.png">

**Comment by nadjaweisskopf** [comment]
rename to (max. Gegenst. 1)
or legend (description) underneath drop down field
or (max. Bestand 1)
check with long pool names

**Comment by urs-van-binsbergen** [comment]
Storybook

Created an `InfoMessage` component: 
https://leihs-styleguide-git-uvb-explain-max-quantity-leihs1.vercel.app/?path=/story/mobileapp-design-components-content-warning-info--info-message

Added to "Add item" component (aka `OrderPanel`):
https://leihs-styleguide-git-uvb-explain-max-quantity-leihs1.vercel.app/?path=/story/mobileapp-integrated-components-orderpanel--order-panel

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf @eins78 New flavour: https://leihs-styleguide-git-uvb-explain-max-quantity-leihs1.vercel.app/?path=/story/mobileapp-integrated-components-orderpanel--order-panel

**Comment by nadjaweisskopf** [comment]
merge the following solution: https://leihs-styleguide-q3e2c3i5w-leihs1.vercel.app/?path=/story/mobileapp-integrated-components-orderpanel--order-panel
