### ISSUE TITLE
JVM Projects build stack clean-up

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1258]
State: one shared library included via submodule into several services with different build systems: lein, tools-deps, shadow-clj and probably boot (mailer). 

The dependencies defined in the shared module are integrated into each other service with some custom hacks. Unfortunately there none of the existing automation tools work to upgrade the dependencies or even only show them. 

Solution: 

Upgrade to unified build system. `tools-deps` for back and uberjar, and `shadow-clj` are the current state of the art. lein is still used but the support for frontend is poor. Since we have a frontend everywhere this is not good choice. Boot is pretty much dead. `tools-deps` and `shadow-clj` integrate quite nicely with each other. 

So: upgrade to `tools-deps` + `shadow-clj` everywhere. Make the dependency easily inspectable. Probably integrate the shared module in a different way, `tools-deps` supports `git` dependencies and much more. The custom hacks should not be necessary.

**Comment by eins78** [comment]
FYI we have put part of this on the roadmap for new `borrow`, between first "go live" of the app and finishing the project (see https://github.com/leihs/leihs/issues/1159),along with some other cleanup and generalisation (like https://github.com/leihs/leihs/issues/1072 and https://github.com/leihs/leihs/issues/1137).
This cleanup can of course start before that, would be even better if there is already a clear path of where we're heading when we also do this in the `borrow` app. I'd suggest starting with `mail` (no UI), then `admin` (only SPA UI), then `my` (SPA and Server-Side-Rendering).

**Comment by DrTom** [comment]
Closing this one. Most of it is resolved when we did the log4j upgrades.
