### ISSUE TITLE
Syntax Error in item.rb

### ISSUE THREAD

**Issue by tmulzer** [leihs/leihs#127]
The content of the passenger-logfile:

```
/home/leihs-test/leihs/app/models/item.rb:164: syntax error, unexpected ':', expecting ')'
...      .where("model_groups.id": [Category.find(params[:categ...
...                               ^
[...]
```

**Comment by nimaai** [comment]
Which Ruby version?

**Comment by tmulzer** [comment]
2.1.5

**Comment by nimaai** [comment]
2.3.0 is fine. 

The hash spec must have changed somewhere between 2.1.5 and 2.3.0. While `{"foo": "bar"}` is invalid in 2.1.5 it is valid in 2.3.0.

Upgrade to 2.3.0 should fix it for you.
