### ISSUE TITLE
Grey out the "Add" button in the calender if for example the calender has errors.

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1276]
(Created originally by Nadja as a project card)

Put more generally: `OrderPanel` (i.e. the "add item" and "edit reservation" dialog) should give the user better feedback when the form is not submittable because validation issues are present (especially when "remove" is the only possible action).  

Currently the submit button is always active (except when loading or saving, but this is a different concern). When the form is in invalid state and the user clicks on it, just nothing happens. Of course there are red warning messages in the form, but this is not enough. 

The submit button should be visually disabled, and, more important, clicking on it should trigger some feedback.

Disabling the button is somewhat tricky because the form state is managed by OrderPanel.js, but the buttons are managed by the app (CLJS). Solution: Context API?

**Comment by nadjaweisskopf** [comment]
needs discussion how to solve technically
