### ISSUE TITLE
Concept and Spec: Search & Model Filter (story / ui)

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1279]
Goal: More intuitive and usable filter flow

Intersecting issues: 
  - Issue:  https://github.com/leihs/leihs/issues/1250
  - Issue:  https://github.com/leihs/leihs/issues/1251
  - Issue:  https://github.com/leihs/leihs/issues/1164

Done:
- Interactive story showing the navigation and filter flow
  - https://leihs-styleguide-git-uvb-model-filter-leihs1.vercel.app/?path=/story/mobileapp-wireframes-katalog-filter--filter
  - Fill in default availability dates
  - Store filter form state (including section collapse state), so after changing categories the filter can easily be re-applied 
  - Rename button to "Filter"
  - Show filter state in bubble 
  - Add experimental inline search field
  - Leverage collapsed section to simplify keyword search in filter modal (just as an idea... is maybe more confusing then helpful)
  - Default scenario without delegations, which makes the filter much more graspable. Most users see it like this. Also we might solve the delegation feature in a different way so this goes away totally.
- `SquareImageGrid`: add support for `onClick` in the items (to support navigating to a category in story)

Next steps:
- Validate in team
- Implement in app

**Comment by nadjaweisskopf** [comment]
let's see after other important tickets have been solved from new borrow and check what needs to be done. One example would be to list all filters one by one with the possibility to discard the criterias one by one.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check when filter is kept when navigating through borrow and in which cases the filter is deleted.

**Comment by nadjaweisskopf** [comment]
@eins78 In earlyer discussions we said the filter would be saved when navigating through the sub categories. According to the tests on next this is not the case. Will this be solved when you merge to test/next?

**Comment by eins78** [comment]
@nadjaweisskopf yes! and thanks for the reminder ;) i almost forgot to add a test for this…

**Comment by nadjaweisskopf** [comment]
@eins78 we said we need this feature for the user tests. When do you think it will be available on next or test?

**Comment by eins78** [comment]
@nadjaweisskopf yes, it will be delivered today. there are still some specs to fix in the CI (which now works again).

**Comment by eins78** [comment]
> @eins78 In earlyer discussions we said the filter would be saved when navigating through the sub categories. 

Not sure if we discussed it back then, but this now works in both directions, so the filters are also kept when navigation to a parent category:


<img width="836" alt="Screen Shot 2022-03-25 at 15 59 06" src="https://user-images.githubusercontent.com/134942/160146278-6c1d50d8-3abd-426f-bd97-e44752489ad7.png">

**Comment by nadjaweisskopf** [comment]
search needs a lot of time

1. open filter
2. set from date 14.4.22
3. set to date 21.4.22
4. set amount to 3
5. I get the results after around 90 seconds

Also after choosing a category the search takes very long. 


It's not possible to search in the categories if at least one search criteria is chosen. So I can't say I want to search in sub category "Audio" but only see the items from pool "XY".

**Comment by nadjaweisskopf** [comment]
will create a new ticket for test results.
