### ISSUE TITLE
Misc UI optimizations

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1280]
Done:
- `InputWithClearButton`: 
  - Clear button should appear only when field contains text (common behaviour in those kind of search fields)
  - Clear button click must not focus the field (otherwise the virtual keyboard pops up)
  - It's not a drop-in replacement for input text anymore (controlled mode not being supported).
- `FilterButton` should not stay dark blue after being clicked 
  - Theme: reduced "focus bg shade", enabled "active bg shade" in Bootstrap theme (for all buttons)
- `FilterButton` increase height from 25px to 30px
- `Badge` increase height from 27px to 30px
- `Stack` omit empty elements (otherwise something like `{false && <div>don't show this</div>}` occupies vertical space)
  - This also solves: Rental index too much space between order title and status bars
- `ModelShow`: attachments (`DownloadLink`) must have more line height
- `DatePicker` issues
  - on mobile devices the virtual keyboard pops in, covering the calendar partly. When the user closes the keyboard and taps on a date in the calendar, the keyboard is shown again.
    - There was a simular issue with `DateRangePicker`, solved in https://github.com/leihs/leihs/pull/1274
    - Here it's a bit different, because the visual calendar can open and close. Place a transparent button over the calendar indicator, allowing to open the calendar without focusing the input.
  - Once an invalid input was made, the red warning does not go even if the input is valid again

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen The points I can test seem to be ok.
