### ISSUE TITLE
My Rentals: Show expired orders as expired, not approval

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1284]
**Expired orders must be listed in the closed orders.** 

If an order has not been approved before the hand out date, then the items are expired. I would like the order in my rentals to have the "expired" status. At the moment it is still shown as "Approval".

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf Write scenarios for both cases:
- approved and not fetched
- not approved and past end date

the scenario should contain the group (open / closed) and the status of the order, f.w. expired

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf I will start implementing already, knowing that some finetuning will be necessary according to your input.

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf 

> third case: If the lending mgr. deletes an order which has not been fetched and the hand over date has passed - what happens?

As far as I can see the reservations are physically deleted. If the containing order does not contain any other reservations, it's also deleted. So it's not just a status change.

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen PZ deletes the order of not picked up items the next day. Could we keep the information of these orders and set a status f.e. expired?

**Comment by nimaai** [comment]
@nadjaweisskopf @urs-van-binsbergen 

In regards to 3. case: A lending manager can't delete an order. He/she can only reject it.

**Comment by nimaai** [comment]
>approved and not fetched

Strictly speaking, this does not fall under `expired` category. Expired means, past until date of the rental. This particular case means, one is just late in picking up things but the rental is valid and open.

**Comment by eins78** [comment]
> > approved and not fetched
> 
> Strictly speaking, this does not fall under `expired` category. 

correct, but if I remember correctly this was supposed to mean "approved and not fetched until end date". at least that was is covered in this issue, just "approved and not fetched" of course has the state `TO_PICKUP` :)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/cac97b99c89607b79ef1b128ef5213dd9d5dc876

**Comment by nadjaweisskopf** [comment]
don't test before @nimaai informs.

**Comment by nadjaweisskopf** [comment]
Created an order "Ghh" and title "Hhz" which should be expired tomorrow and shown in the closed orders.
