### ISSUE TITLE
Migrations 610 and 613 can fail

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1295]
Solution: use `drop` and `create` instead of `replace`

**Comment by winampdevil** [comment]
@DrTom, thank you for this hint.
It solves the issue #1271

**Comment by eins78** [comment]
@nimaai FYI this is what we talked about earlier.

**Comment by nimaai** [comment]
database: https://github.com/leihs/leihs_database/tree/mk/fix-migrations-1295

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/54658688645cc57848462b1e50d38b43373b543b
