### ISSUE TITLE
error when editing a calender with overbooking

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1303]
give exact steps!

error when
1. reserve 3 models A/D-Converter Behringer ADA-8000  for the time frame 16. - 18.
2. go to lending and add A/D-Converter Behringer ADA-8000  to a hand over for the same time frame
3. go back to cart
4. refresh cart
5. overbooking is shown
6. open calender
7. go to free day and then choose the same time frame as before
8. error is shown

<img width="368" alt="error Kalender" src="https://user-images.githubusercontent.com/3356016/152792304-2ad2d6fe-e197-4f7a-890c-4d33983a6730.png">

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf 

Could reproduce step 1-6, but not 7/8. In other words: the reduced availability which is caused by step 2 is handled correctly by the calendar.

**Comment by nadjaweisskopf** [comment]
general behaviour is ok. If a user has reserved an item but not sent it and a lending mgr. reservs the same item in the meantime, then the user should get the msg. saying the item is not available anymore. At the moment this item pops up with a confusing error text and the msg. is not designed - very low level error msg. Therefor we will close this ticket and discuss the design of the msg. in ticket #1203
