### ISSUE TITLE
dev: upgrade clojure build tooling

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1308]
mostly done by @DrTom, finishing up frontend stuff by @eins78 

- [x] admin
- [x] mail
- [x] my
- [x] procure
- [x] (new) borrow
- [x] integration tests

**Comment by nadjaweisskopf** [comment]
@DrTom check if it is really necessary to update borrow at this point. max. 1 day for downgrade

**Comment by nadjaweisskopf** [comment]
two tests in new borrow broken and inplicite conversion.
