### ISSUE TITLE
Show info and hide filter when user has no reservable items

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1322]
Primary finding (to be solved by hiding the filter in this situation): 

When filtering the inventory pools in the catalog for the delegation "Ausstellung Unterirdisch 2014" then the filter says "All" but doesn't list any pools. 

None of the pools, which the user has access to, has reservable items. 

How to reproduce: 
1. go to new borrow
2. choose delegation "Ausstellung Unterirdisch 2014" 
3. go to catalog
4. open filter
5. choose filter "inventory pools"
6. Only the option "Alle" is listed - no list of the pools. 

<img width="679" alt="filter_delegation" src="https://user-images.githubusercontent.com/3356016/159248195-ce941ad7-63dc-4df4-9a07-39669b26b383.png">

**Comment by eins78** [comment]
seems to me there are two problems:
* we should not show the "All" option when there are no pools
* this specific Delegation is "broken", also in Admin UI. It seems like the Responsible User is missing which causes cascading errors. https://next.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/e19cbf44-3502-5993-9ffe-c23f383a76a9

**Comment by nadjaweisskopf** [comment]
delegation is not broken. 
Solution: 
- don't show the filter or filter should not be clickable
- show msg. "There are no items lendable for the pools you have access to. Please contact the lending desk for further questions"
