### ISSUE TITLE
Show the sum of items if date and model is the same

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1326]
If I order 19 times the same item for the same day, I see the line 19 times in the order. I would like to see instead

19 x item name

How to reproduce
1. go to new borrow
2. choose item "Studiokopfhörer AKG K245"
3. order 19 items for the 25.3.22
4. send cart
5. check the order - the items are listed one by one 19 times

<img width="668" alt="item one by one" src="https://user-images.githubusercontent.com/3356016/159346691-d09609f9-dc53-4ddf-8015-1e7c1d4ab083.png">

**Comment by nadjaweisskopf** [comment]
we might leave it as it is at the moment and discuss after go live.

**Comment by urs-van-binsbergen** [comment]
Naive solution: item lines grouped by start date, end date, pool, model/option name, status, inventory code

<img width="769" alt="Screenshot 2022-04-28 at 12 12 14" src="https://user-images.githubusercontent.com/25439444/165730528-1dda7dd0-d2a0-41b6-9aa7-90a16c3b5586.png">

Other solution: nested lines -> needs re-design

**Comment by urs-van-binsbergen** [comment]
uvb/draft/my-order-grouped-lines
