### ISSUE TITLE
Show reject reason

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1327]
Is there a possibility to show the reason why an order has been rejected? Is it techn. possible to make the bubble "Abgelehnt" in the order clickable and show the reason as popup or similar?

**Comment by nadjaweisskopf** [comment]
It's shown in the mails but not in the app.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf design spec needed

**Comment by neoheat** [comment]
to be discussed

![Image](https://github.com/leihs/leihs/assets/123965725/dd0a9828-eb90-46a9-a5b3-309184c20276)

**Comment by neoheat** [comment]
do not show on list, only in detail view

**Comment by neoheat** [comment]
ideas:
- own view "My appointments" 
- info on homepage
- main menu "My appointments" (place "help" somewhere else)
