### ISSUE TITLE
Delegation's cart with invalid items shows wrong name under "Order for"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1333]
Cart for a delegation shows personal users name instead of delegation's name when no valid items are contained (because `refreshTimeout` returns `unsubmittedOrder.userId` = null then).

How to reproduce: 
- Switch to a delegation
- Add 1 item to cart
- Do something to make the item invalid (i.e. retire the model in inventory pool administration)
- Reload
- Cart will wrongly show "Your Name (personal)" in the "Order for" section
- Now add another item
- Cart will now correctly show the delegation name in the "Order for" section
- Remove the valid item again
- Cart will show the wrong name again

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/abca5ede48d2e67a4b593904fd659be6a4a1a95e
