### ISSUE TITLE
optimise search 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1336]
The search terms have to be in the same order as the title itself. So f.e. if I am searching for

Kabelrolle XLR multicore

the search feature will not find the item if I type "XLR Kabelrolle"

Would it be possible to change this behaviour, so have an AND condition in between the search terms instead?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ea7747876054bb24bbd811f44b33f8685e5fa755
