### ISSUE TITLE
Cart time limit zero after "repeat order" 

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1339]
This is not directly related to the "repeat order" feature, but is generally case _when only invalid items are in the cart_. Invalid items are not reservated, so there is no such thing as a reservation timeout. 

The UI should handle this situation. Suggestion: Replace "Time limit" with "Invalid", hide progress bar, hide "0 minutes left"

**Comment by nadjaweisskopf** [comment]
We'll leave the time line and change the text to something like "time not relevant - items invalid".
