### ISSUE TITLE
Reorder sections in filter and dialog

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1345]
- [x] Reorder the catalog filter: place the availability section in between the search term section and the inventory pool section. 
- [x] Reorder the add item dialog: move quatity section towards calender

**Comment by eins78** [comment]
@nimaai @urs-van-binsbergen btw, this was done with 1 paredit command 😆 (put cursor at start of the availability section, `Paredit: Drag Sexp Backward`)
