### ISSUE TITLE
Change text "Plus" and "Minus" to "+" / "-"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1346]
Change text "Plus" and "Minus" to "+" / "-"

- [x]  In the category filter
- [x]  In the add item panel

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/593368dd1a0a4fa91a8d3c246b5f6760edaeb3e7

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check with one user if the signes are ok and understood.
