### ISSUE TITLE
Don't show user info if not assigned to any delegation

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1347]
The following description has been reproduced with FFZH. I can't reproduce it anymore. 
If a user is not assigned to any delegation, then don't show user info (order for) in "add item" page 
When testing with the ffzh user, the user info was empty, only the title "order for" was shown. 

For further instructions to what shall be developed please view the comments section of the ticket.

**Comment by nadjaweisskopf** [comment]
- [ ] remove info "order for" in orders of "my orders"
- [ ] remove info "order for" in cart

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ec815805838a97b53c7a8800143b1dee9a5b795d
