### ISSUE TITLE
bug in filter behaviour is related with language settings

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1348]
1. choose language swiss german or castellano
2. go to catalog
3. enter a search term
4. close the keyboard on the mobile
5. I get an error

![error_keyboard](https://user-images.githubusercontent.com/3356016/161624694-7111a994-4d24-4b51-93f4-b7e885dffa14.jpg)

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs/commit/3e1897495ae9f8e7d9c19ad00b9aadcec21a690f
