### ISSUE TITLE
Invalid username/password

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#135]
local leihs server at http://localhost:3000. I log in with username "admin" and password "password".
It's give me
**Invalid username/password**

**Comment by psy-q** [comment]
Did seeding the database work correctly?

```
bundle exec rake db:seed
```

Afterwards it should say "The administrator user 'admin' has been created with password 'password'"

**Comment by nkuhan** [comment]
I got this message
```
Settings created: {:smtp_address=>"localhost", :smtp_port=>25, :smtp_domain=>"example.com", :local_currency_string=>"GBP", :contract_terms=>nil, :contract_lending_party_string=>nil, :email_signature=>"Cheers,", :default_email=>"your.lending.desk@example.com", :deliver_order_notifications=>false, :user_image_url=>nil, :logo_url=>nil, :mail_delivery_method=>"smtp"}
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Field 'user_id' doesn't have a default value: INSERT INTO `database_authentications` (`login`, `salt`, `crypted_password`, `created_at`, `updated_at`) VALUES ('admin', '3a96652a98cf998a02e2cea8427c9dc71173a8e3', '6efe88a892f9314e016064af7b8bd7ef9149b949', '2016-10-19 06:48:28', '2016-10-19 06:48:28')
```
and more

**Comment by psy-q** [comment]
Hmm, that's a bug that was fixed in 3.40.0. Are you using something newer? If yes, then the bug might not be completely fixed yet.

**Comment by nkuhan** [comment]
I am using 3.38.0,How to upgrade it

**Comment by nkuhan** [comment]
Can I download and run it on a different folder 3.42.0

**Comment by psy-q** [comment]
Yes, that should work. You can use the same database config file and database if you want. Remember to migrate the database to the new version:

```
bundle exec rake db:migrate
```

Please see also the the ["Performing upgrades" section](https://github.com/leihs/leihs/wiki/leihs-Admin-Guide#performing-upgrades) of the admin guide.

**Comment by nkuhan** [comment]
`bundle exec rake db:migrate`

It didn't gives any error
