### ISSUE TITLE
my orders - loading forever when filter is re-applied 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1351]
1. go to my orders
2. open filter
3. set search term
4. press enter
5. reopen filter
6. press apply again (without changing any value)
7. searches for ever

**Comment by eins78** [comment]
@nimaai urs said: if we dont change anything in the form and then submit, in the submit event we set `loading=true`. but because the route does not change, there is no fetch event that completes and sets `loading=false`

**Comment by urs-van-binsbergen** [comment]
@eins78 

> I suggest to always trigger the (re-)fetch, so current data is loaded. So it should be dispatched explicitly (not relying on the router).

I suggest to keep the behaviour consistent with the model filter, i.e. submitting an unchanged filter just does nothing. I implemented this in the last commit -> [f5b79ec](https://github.com/leihs/leihs/commit/f5b79ecab6d4b1d16b82470ee85a8623655d9e5d).

**Comment by eins78** [comment]
@urs-van-binsbergen I like consistency, so go for it. nit-picky: I would like it more if the the result is re-fetched, so the user can get fresh results without reloading the window.
