### ISSUE TITLE
Enhance the search results

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1352]
- [ ] when entering a search criteria that matches a category, the user would have the possibility to set the category

- [ ] It would be nice to see results to categories and items when entering a search term, similar to digitec. 

![grafik](https://user-images.githubusercontent.com/3356016/161626830-320e33a6-622b-4cf5-8cb7-a31c9def3e54.png)

---

original suggestion:

It's not possible to search in the categories if at least one search criteria is chosen AND you are not yet in a sub category. So I can't say I want to search in sub category "Audio" but only see the items from pool "XY" unless I FIRST go to the sub category and then choose the pool.

**Comment by neoheat** [comment]
would be a total switch from the current search concept an general UX. Therfore closed.
