### ISSUE TITLE
Apply Search Params when Adding to cart

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1353]
Steps:
* I filter for Pool, Date-Range and Quantity 
* I see search Results
* I click on an item
* I click on "Add Item"
* The Dialog is pre-filled with the previously chosen Pool, Date-Range and Quantity
* should also apply to link on the modal-detail links (e.g. to recommended models)

Technical Solution:
* A. links to model-detail from search results contain the query params for the search (like sub-categories)
  * (can also be *in the future* used to provide a "back to search results" link)
* B. if model-detail page has query params (Pool, Date-Range and Quantity), profill those values in the "Add Item" panel

**Comment by eins78** [comment]
@nimaai here the search-params are added to the sub-category links: https://github.com/leihs/leihs-borrow/commit/70cee87de6599e6ef392412f24d8895a73c45d1e#diff-0487f5ebf4b5708e6b93b8298f2a13ea4a6ef9cb38836037a38aba6b6f0450a0R137

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7394aae7886204a3296d76d8fc115e973ec60b3c
