### ISSUE TITLE
new borrow: show notice when no access to any pools

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1358]
* this feature is currently in `/my` service - can be removed there
* can be done when new borrow is "stable" (always enabled)
* needs an integration test

(followup from https://github.com/leihs/leihs/issues/1322)

**Comment by neoheat** [comment]
@urs-van-binsbergen  is this an already existing feature? Where could it be implemented, in which screen?

**Comment by urs-van-binsbergen** [comment]
@neoheat 

It's not a feature, but kind of "anomaly handling". If a user can login, but has no permissions to any inventory pool - what happens? 

You can craft such a user and then login. I'm not sure what happens. According to the description above there is an error message even before the user gets into Borrow (`/borrow/` path). As part of the login process (this is the "My" service).

If he would get into Borrow, he would see a message "No reservable items found", with a link to the list of his pools "Check available inventory pools". There he would see "No inventory pool available". This is probably OK

**Comment by eins78** [comment]
Hi all, the existing feature is implemented in `my` (because that's where the login is handled). 
See https://github.com/leihs/leihs-my/commit/40736069aeb58a8a0fe94124a8fb8245b607206c
