### ISSUE TITLE
How to modify the database.yml file

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#136]
I am new to Ruby on Rails,Could anyone tell me  
where I have to add this code in the below yml  file or How to modify this yml file

production:
   adapter: mysql2
   database: leihs_production
   encoding: utf8
   username: root
   password:
   host: localhost
   port: 3306

**leihs/config/database_local.yml**
```
# MySQL. Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
# gem install mysql2
#
# And be sure to use new-style password hashing:
# http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &DEVEL
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: leihs2_dev
  pool: 5
  username: root
  password:
  # for Debian and Ubuntu:
  #socket: /var/run/mysqld/mysqld.sock
  # for Mac OS X:
  #socket: /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &TEST
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: leihs2_test
  pool: 5
  username: root
  password:
  #socket: /tmp/mysql.sock

production:
  <<: *DEVEL

cucumber: &CUCUMBER
  <<: *TEST

profiling:
  <<: *DEVEL

culerity:
  <<: *CUCUMBER
```

**Comment by psy-q** [comment]
These are general questions about Rails and ActiveRecord configuration. Please [see the appropriate Rails guides](http://guides.rubyonrails.org/configuring.html) for more information. I think the leihs community is the wrong place to ask about such general things, but leihs-specific questions can be answered here.
