### ISSUE TITLE
new borrow: cleanup lodash

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1364]
* only use lodash if really needed, use the granular packages (no split bundle config needed, also granular updates). e.g. `lodash.debounce` -> sammelticket

**Comment by urs-van-binsbergen** [comment]
Some findings
- Analysis of usage: about involved 20 JS files, 20 different methods, 100 calls
- 3 JS files are in scope of Borrow Mobile -> rewrite to not use lodash anymore
- It seems that the granular packages are not recommended anymore: https://lodash.com/per-method-packages 
- However we must make sure that our bundle does only contain the code we use (maybe we have to modify the import statements)
