### ISSUE TITLE
CI: reduce flakyness

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1365]
Top 5 according to the last 10 runs around 01.05.2022: 
- search_results
- rentals/rentals_show
- rentals/rentals_show_status
- rentals/repeat_order
- rentals/rentals_index

Look in CI at which step they usually fail. Reproduce locally. Improve wait behaviour.

**Comment by urs-van-binsbergen** [comment]
First try to solve the general issue that often the test runner can not connect to the browser:

```
Failure/Error: page.driver.browser.manage.window.resize_to(*BROWSER_WINDOW_SIZE)

     Errno::ECONNREFUSED:
       Failed to open TCP connection to 127.0.0.1:4445 (Connection refused - connect(2) for "127.0.0.1" port 4445)
     # ./spec/config/features.rb:38:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for "127.0.0.1" port 4445
     #   ./spec/config/features.rb:38:in `block (2 levels) in <top (required)>'
```

**Comment by nadjaweisskopf** [comment]
see after rails upgrade how this ticket is developed.

**Comment by nadjaweisskopf** [comment]
seems to be better. Will close the ticket according to Matus.
