### ISSUE TITLE
My order detail: different dates shown in summary and item lines

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1367]
<img width="390" alt="start-end-date" src="https://user-images.githubusercontent.com/25439444/167651232-2118cb4b-2657-43ff-b27b-4132217356b9.png">

The summary line relies on the dates coming from the SQL view `unified_customer_orders` (which provides the core data of rentals) prefers `contract.created_at` over the `reservations.start_date`, and also `reservations.returned_date` over the `reservations.start_date`. This makes sense because after the pickup/return the effective dates are more interesting than the original booking dates. 

Problems:
- The list of items in "Rental details" on the contrary does not care about effective pickup and return dates. So users could be confused by the difference in dates.  
- Generally the SQL view has too much logic which rather should be placed in the app?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6f660eb84ae38fc7e014ff8b10376b91dfe8050c
