### ISSUE TITLE
Didn't fetch, Got struck

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#137]
When I run 
`/leihs-3.42.0$ bundle install --deployment --without cucumber development
`
Got struck with here 
```
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from http://rubygems.org/
Fetching version metadata from https://rails-assets.org/
```
**Didn't go beyond this**

**Comment by psy-q** [comment]
This doesn't seem to have anything to do with leihs. Is your network connection OK, can you reach https://rails-assets.org/ via a browser? Can you look at your network traffic with a network sniffer to see what's going on there and whether your request is getting through?

Also see the [Bundler website](http://bundler.io/) and the [Rails-Assets one](https://rails-assets.org), maybe there is some troubleshooting info.

**Comment by nkuhan** [comment]
finally, I solve it, Thanks

If you are behind a proxy you can use the https_proxy environment variable:

`https_proxy=https://myproxy:123 bundle install --deployment --without cucumber development`
Note that if there is no https_proxy env variable, Bundler will also look for a http_proxy env variable.
