### ISSUE TITLE
Sub-categories not loaded for some categories

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1373]
How to reproduce:
- On the index page, click through categories until you find one which does not have sub-categories (only items)
- On the category details page, open F12-tools -> Network. 
- You should see 4 XHR requests labelled "graphql"
- The first XHR request should have the payload "query getCategories (...)" (if not, check the other XHR entries)
- The response will contain the error message "Not all categories where found among the reservable ones." (if not, try other categories) 

The issue occurs also in the borrow feature test spec `search_results.feature` on line 108 'Then the title of the page is "Analog Cameras"'. The test does not fail currently because the error is silently ignored so far (which will change in https://github.com/leihs/leihs/issues/1203)

**Comment by urs-van-binsbergen** [comment]
Hypothesis: This happens when the category does not have any directly assigned borrowable models (only via sub-categories).

**Comment by nadjaweisskopf** [comment]
1. use "Leihs Delegation"
2. go to "Film / DCI"
3. f the bug is fixed, then I see the sub categories
