### ISSUE TITLE
showing order in wrong user profile

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1374]
CHANGING THE ORDERER

1. Behaviour in borrow legacy:

If a lending mgr. (user A) creates an order in borrow section and changes the requester in lending section to user B, 
- user A he does not see the order in his user profile
- user B see the order in his profile under "orders" on the top of the page

2. Behaviour in new borrow:

- user A sees the order in the open orders
- user B does not see the order in open orders

In future, I can imagine the following behaviour to be correct:
Correct would be 
- user A should see the order in "Abgeschlossen" and we need to show the that the user has been changed by a lending mgr. 
- user A should have the possibility to reactivate the order
- user B should see the order and have the possibility to reactivate the order

But at the moment, if we want to keep the same behaviour as in legacy, we need to adapt to the behaviour as described in "1. Behaviour in borrow legacy:".

Screens for **legacy:**

User A
![LEGACY_USER_A](https://user-images.githubusercontent.com/3356016/169893227-4d56a03f-6301-4c4e-9ca1-f3f9127487f5.png)

User B
![LEGACY_USER_B](https://user-images.githubusercontent.com/3356016/169893245-f17ff186-2769-471b-b0eb-c796cd57e619.png)

Screens for **New Borrow**

User A
![new borrow_user_a](https://user-images.githubusercontent.com/3356016/169894479-b162f02a-1376-401a-b0e2-ddb0c8e84b9c.png)

User B
![new borrow_user_b](https://user-images.githubusercontent.com/3356016/169893693-d7af7ccd-4d85-4639-a379-af982e601e81.png)

#### Specifications
- Leihs version: staging
- Browser version: safari

**Comment by eins78** [comment]
@nimaai @urs-van-binsbergen http://localhost:3250/app/borrow/rentals/5bbde77f-5a6c-4d2c-bacb-cdee50e0e5f7

**Comment by nimaai** [comment]
@nadjaweisskopf @eins78 We also need to check what happens when single reservation line(s) are transferred to a new user on the hand over page.

**Comment by eins78** [comment]
* when the `user_id` of an `order` changes 
  * if it is the only `order` in its `customer_order` (there is only one `order` with the same `order.costumer_order_id`)
    * then also change `customer_order` to have the same `user_id`
  * if there is more than 1 `order` in its `customer_order` (there is more than 1 `order` with the same `order.costumer_order_id`)
    * then "split" the `customer_order` by creating a new one with the same data but the new `user_id`


* rules
  * constraint that all `order`s related to `customer_order`s need to have a matching user_id
  * maybe: each `customer_order` needs to have a related `order`

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/3790c4ff7754927968af1974b65ed4ddc0a65e84
