### ISSUE TITLE
Incorrect behaviour when reactivating order

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1375]
User A as described in ticket #1374 can reactivate an order which should be shown in profile of user b. Nevertheless, he can reactivate the order without having any items. Leihs then gives an error saying "Optionen können nur durch die Verleihstelle hinzugefügt werden". But the order does not have any options, only items. 

Could you please have a look if we have overseen a problem? If ticket #1374 has been solved, this problem should not pop up anymore. But still, we might be missing something. 

![keine optionen hinzufügen](https://user-images.githubusercontent.com/3356016/169895280-7f8758cf-d5f0-437c-92b6-c498f138d2a1.png)

#### Specifications
- Leihs version: staging 6.3.1
- Browser version: safari
- MySQL/PostreSQL version:

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf This situation is handled now by the "Repeat order" not being shown at all when there are no visible reservations in the order.

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen ah yes, sorry, I thought the issue seemed familiar. On test-env. that would have been solved in that case.
