### ISSUE TITLE
change link text

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1377]
According to user feedbacks they have difficulties finding the page to change the users password. It would help them if

- we would have two links on the top saying "change password" and "add API-Token"
- go directly to the pages "password" and "api-token" insteady of showing an empty user page and then the meaningful links. 

![link to change pw](https://user-images.githubusercontent.com/3356016/169897607-f22bd8bd-5ad2-4795-b31c-dbcd8fc4a5a4.png)
 

In German: "Passwort ändern" / "API-Token"

**Comment by DrTom** [comment]
There is an old ticked about the password feature itself: https://github.com/leihs/leihs/issues/1027 we should fix this

**Comment by neoheat** [comment]
should be solved with the optimized user interface of the user detail page

![Image](https://github.com/user-attachments/assets/fdc845ed-c247-480a-b23d-71898e361f64)
