### ISSUE TITLE
Creating a subcategory crashes "Audits legacy"

### ISSUE THREAD

**Issue by MatKDA** [leihs/leihs#1382]
#### Expected behaviour or future wish
"Audits Legacy" shouldn't crash.

#### Current behaviour
After creating subcategories, "Audits Legacy" crashes with the following error: Internal Server Error: undefined local variable or method `model_group' for #<ModelGroupLink:0x00007f8458f5dc30>

Serverlog:
```
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:   
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]: ActionView::Template::Error (undefined local variable or method `model_group' for #<ModelGroupLink:0x00007f526971f210>):
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     12:       - if klass == Setting
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     13:         = app_settings.label_for_audits
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     14:       - elsif entity = klass.find_by_id(row['auditable_id'])
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     15:         = "#{entity.label_for_audits}"
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     16:       %br
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     17:   %small= row['auditable_id']
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:     18: - else
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]:   
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]: app/models/model_group_link.rb:19:in `label_for_audits'
Jun 03 12:00:01 leihsInstance leihs-legacy[1630]: lib/leihs/middleware/audit.rb:22:in `call'
```

#### Steps to reproduce
1. Create a category "X".
1. Create another category "SubX" and select category "X" as parent category.
1. Open "Audits Legacy".

Without these steps, "Audits legacy" works fine.

#### Specifications
- Leihs version: 6.2.4 and 6.3.0. Not tested on 6.3.1 as the update still fails, see issue in repository "leihs-instance" ( leihs/leihs-instance#23 ).
- Browser version: Firefox 91, Chrome 102

Regards,
Matthias

**Comment by neoheat** [comment]
audits legacy is not supported anymore and is removed in future releases.
