### ISSUE TITLE
chown leihs return invalid user

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#139]
`chown -R leihs` ...
gives invalid user

**Comment by psy-q** [comment]
Did you create the user?

If you're still installing locally on macOS, please note that the admin guide assumes a production install on GNU/Linux using a new system user called 'leihs'. This might not be what you want to do on macOS. The best and supported way to use leihs is to use [Ansible](https://github.com/leihs/ansible-leihs-setup) to install on a Debian system. For anything else you are on your own.

**Comment by nkuhan** [comment]
sorry , **I successfully installed through Debian Virtual Box**.
but codon't login with user name admin and password password.
when I run 
 
`bundle exec rake db:seed --trace` give this error

** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations

**Comment by nkuhan** [comment]
I am using Debian virtualBox/VM to install.
Sorry, I don't have experience in  use Ansible to install.
