### ISSUE TITLE
Upgrade Rails 7.x

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1391]
https://endoflife.date/rails

- [x] 7.0
- [x] 7.1
- [x] 7.2

**Comment by urs-van-binsbergen** [comment]
Rails 7.0 merged: 9df959abfab46e9a9e88d08c86f758cf4632f89e

**Comment by urs-van-binsbergen** [comment]
Rail 7.1: aef3b1523f6569144552392d25e9a0f330c1a12f

**Comment by urs-van-binsbergen** [comment]
Rails 7.2: 94f183b3c285bad6422d6b06ba54c86043d1bfd7
