### ISSUE TITLE
In Q3 2023: Update Frontend-Stack

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1396]
- Procurement
- Borrow (again)
- Admin
- My

F.e. 
- React
- Bootstrap
- Shadow CLJS
- div. Libraries and Node versions (basic technology for frontend stack)

**Comment by urs-van-binsbergen** [comment]
Maybe separate task, but the technical README files should be reviewed and updated.

**Comment by urs-van-binsbergen** [comment]
Further steps are:
[ ] Decouple `my` from `leihs-ui`
[ ] Decouple `admin` from `leihs-ui`
[ ] Decouple `procure` from `leihs-ui`

SSR will generally be replaced. This means that `my` will get an actual client side app. 

There is also an impact on `shared-clj`.

**Comment by neoheat** [comment]
follow the new spin off tasks

**Comment by neoheat** [comment]
waiting for release
