### ISSUE TITLE
New status in Procurement

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1400]
In Procurement a new status is needed called "Nicht Beschafft".

Following adjustments are needed: 

- In Status filter
- In List on request

![nicht_beschafft](https://user-images.githubusercontent.com/3356016/180214991-7b3e942f-38ab-443a-9159-8f2753b01355.png)

Requirement from ITZ.

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf I found that requesters do not see the "Status Beschaffung" field in their requests, but they see the corresponding filter, so that they can find out the status by probing. Is this OK?

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen can we have a look at your input? Either they see both or nothing.

**Comment by nadjaweisskopf** [comment]
we said: the requester always sees the filters and the status but can't edit the status.
