### ISSUE TITLE
API: Images/Thumbs

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1405]
Would help a bit to improve the velocity when loading f.e. the model list. 

* first step: compare against `gatsby-image` @eins78

* can we get widths? otherwise we cant really use the thumbs… see how it will be used: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

* maybe Interface for "ViewableImage" (common props)

**Comment by neoheat** [comment]
not required at the moment
