### ISSUE TITLE
Send submitted mails from new borrow

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1408]
After submitting an order, the submitted mail is not sent to the user. 

Mail sent out of legacy works.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d1727fb5b4e0cd3a55e1da23cc5310c8665855da

**Comment by nadjaweisskopf** [comment]
@nimaai I didn't get an email from new borrow. Could you please retest?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f657a44a8dd71049c142c52e4a836bcdb4de4890

btw, received mail notifications were also not working in new borrow. needs to be verified too on staging.
