### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by nkuhan** [leihs/leihs#141]
RAILS_ENV=production bundle exec rails s

=> Booting WEBrick
=> Rails 4.2.6 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in <top (required)> at /home/kuhan/leihs/leihs-3.42.0/config/environments/production.rb:84)
Warning: fuzzy message was used.
  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'
Warning: fuzzy message was used.
  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'
Warning: fuzzy message was used.
  : msgid 'Delegation'
Warning: fuzzy message was used.
  : msgid 'A package item must belong to a package model'

**Comment by psy-q** [comment]
Thanks! They are harmless, by the way, but we should get rid of them.

**Comment by eins78** [comment]
will be fixed as part of #216
