### ISSUE TITLE
Leihs offers password sign-in when external auth system email matches but user  account does not even exist yet

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1411]

**Comment by DrTom** [comment]
So this page is rendered by the shared ui via SSR. 

see `(js-engine/render-react "SignInPage" sign-in-page-params)` in `leihs.core.sign-in.back`

relevant data within
```
:authFlow {:user "foo.bar@example.com", :forgotPasswordLink "/forgot-password"}
```

it is yet unclear to me on what condition the reset link appears, if I remove `:forgotPasswordLink` it is still there

**Comment by DrTom** [comment]
There seem to be two Problems here

* the UI always shows the password reset link, no matter on the condition of the user account

* the dispatch logic seems not to work properly because it should immediatelly redirecto to external since there is excatly one external auth system, see line 175 ff in `leihs.core.sign-in.back`

**Comment by DrTom** [comment]
Reproduce @ZHdK instance: 

1. find a user which is enabled for both external authentication system 
2. disable the `password_sign_in_enabled` property for the user 

Then the UI shows the password reset button. This is wrong. Also the user might not event exists, in which case the button should also not be shown.

**Comment by DrTom** [comment]
yet another problem with this feature https://github.com/leihs/leihs/issues/1055

**Comment by urs-van-binsbergen** [comment]
It seems that the following Leihs UI story also show the issue:
https://ui.leihs.app/?path=/story/features-login-page--step-2-2-external-auth-options-and-no-password

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e5e7b742fa157e737f4c84716ab55d16af684014 except for #1055

**Comment by nadjaweisskopf** [comment]
test UI Login and translations - as soon as ticket is finished

**Comment by nadjaweisskopf** [comment]
test cases: check that user is enabled, to be able to change password.

**Comment by nadjaweisskopf** [comment]
@DrTom all tests were ok except this one use case: 
User: https://test.leihs.zhdk.ch/admin/users/3ad16207-44d6-5c87-8c68-253f70aedda8/edit
User does not have a primary email address, only a secondary. The user is enabled and pw-sign-in is active.
But for this user I can not change the password. I guess because the primary email is missing. 

This case is very rare.

**Comment by nadjaweisskopf** [comment]
Accepted. the code only checks if there is a primary email, not a secondary. It would be too much effort to change the code, so it also checks for the secondary email address. We'll leave it as it is just now.
