### ISSUE TITLE
Demo-Version not working

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1415]
Leihs-Demo is not working: https://demo.leihs.zhdk.ch/

**Comment by DrTom** [comment]
Server is outdated resp. OS too old.

We are waiting of a new VM with current OS.

**Comment by GitCurio** [comment]
any idea of the timeframe?

**Comment by DrTom** [comment]
Status: 

✅  Server has been updated, 
✅  deploy itself works again,
☑️ demo restore: is broken; reset script seems to reference the wrong ruby environment

**Comment by DrTom** [comment]
Status: 

✅  Server has been updated, 
✅  deploy itself works again,
✅  demo restore: is broken; reset script seems to reference the wrong ruby environment
 
https://github.com/leihs/demo.leihs.zhdk.ch/commit/d39dea948d371f56e090eb0731caaf1c8423cafc
