### ISSUE TITLE
Bug in View entitlement_groups_users

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1418]
```
SELECT entitlement_groups_users.*
FROM entitlement_groups_users

QUERY:  SELECT uuid_generate_v3(uuid_nil(), user_id::TEXT || inventory_pool_id::TEXT)
CONTEXT:  PL/pgSQL function entitlement_groups_users_id_agg_f(uuid,uuid,uuid,uuid) line 4 at RETURN
```

**Comment by nadjaweisskopf** [comment]
If you open the timeline in certain models with entitlement group there is a bug.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/4bf27d35700777cf3659c9d02d875aafe9014eb8

**Comment by nadjaweisskopf** [comment]
tests: tested on external schools environment --> Test was OK. Tested on ZHdK environment if everything is still the same as in production --> Test was OK.
