### ISSUE TITLE
Create 100 items threw an error - URLs didn't show

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1424]
SUSO created 100 items of model "SAMSUNG Portable SSD T7". After pressing "save" on create item page, an error was shown: 

![Bild eingefügt am 2022-8-22 09-33](https://user-images.githubusercontent.com/3356016/185867169-f64b6456-cfdf-4c7e-a3bb-4b57ff007857.jpg)

They would be glad ot have the URL-page after creating items in a batch.

**Comment by nadjaweisskopf** [comment]
@DrTom enhance webserver because of limit length

**Comment by DrTom** [comment]
@nimaai ich hab das gerade auf staging 4x hochgesetzt; kannst du überprüfen ob es hilft? 

(nach einem Deploy wäre das wieder weg!)

**Comment by nimaai** [comment]
@DrTom 👍
