### ISSUE TITLE
Borrow desktop version - check design spec and next steps

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1426]
- UI for desktop
- templates 
- batch editing

**Comment by urs-van-binsbergen** [comment]
### Unported features from Classic Borrow

(Port or not?)

- (yes) Templates
- (?) Search as you type
- (?) Sort order of search results configurable (by model ascending/descending, manufacturer ascending/descending)
- (?) Filter: select multiple inventory pools
- (?) Search results: Model details per mouseover 
- (?) Model details: thumbnails when multiple images
- (?) Calendar: show count of available items for each day 

### New features

- Batch editing in cart
- (Dashboard? "your next pickups" etc.)

### UI Optimizations according to feedback

- Submit vs. filter button (currently people constantly click on the blue filter button when they want to submit their search term)
- People expect user data, logout and such stuff under the initials button in the navbar (now only delegation switcher)
- Hamburger menu is generally overloaded. Separate out language menu
- (Nadja has collected several more)

**Comment by urs-van-binsbergen** [comment]
https://xd.adobe.com/view/7c8101e9-9819-4a00-ade4-181dd6f29b03-29d2/grid

**Comment by nadjaweisskopf** [comment]
- Create a new board
- Create first tickets

**Comment by nadjaweisskopf** [comment]
We said we would not create a new board, there are too few tickets.
