### ISSUE TITLE
Borrow app on IPhone: Dates with 0 availability not indicated in cart item edit form initially

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1428]
Reproduce:
- Open Borrow App on  IPhone
- Add item to cart (make sure the item is inavailable on some days of the current month, indicated by pink hatching)
- Confirm
- Go to cart
- Click on the item
- The calendar will not indicate dates of insufficient av. with pink hatching
- As soon as a any date is tapped the hatching will appear (also on month navigate or submit)

**Comment by neoheat** [comment]
@urs-van-binsbergen behavior in iPhone Simulator not reproducable, only on physical iPhones. Unfortunately, no console errors outputs either.
The behavior is indeed very strange. On the iphone the pink hatched background appears after ~30sec (without any user action).

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf test on iphone. Solution is not yet clear. Decide if really that important. Otherwise we'll archive the card.

**Comment by urs-van-binsbergen** [comment]
This problem seems to be fixed on the latest "design fix" prototype! Unclear why. Maybe the hatching was the problem, or the general refactoring of the calendar fixed it.

**Comment by neoheat** [comment]
retested today. I can't reproduce this issue anymore. Therefore I'll close the card
