### ISSUE TITLE
HTTP header based authentication and authorization

### ISSUE THREAD

**Issue by ctr49** [leihs/leihs#1433]
#### Expected behaviour or future wish
Is it possible to use HTTP header based authentication and authorization? I need to install leihs behind a reverse proxy (oauth2-proxy or Apache with mod_auth_openidc). So I'll have the username and groups in HTTP header. Reading through some other issues it looks like this was supported (through Shibboleth?) at some point, but it is not obvious if it still works or not.

If it's not working out-of-the-box, could this be implemented using a (simple) external authentication handler or is external authentication JWT-only?

Any help would be appreciated!

#### Issue or wish reported by
@ctr49

#### Current behaviour
Only oauth based external authentication is described.

#### Steps to reproduce

n/a

#### Acceptance Criteria

Run behind reverse proxy with HTTP header based auth.

#### Specifications
n/a

**Comment by neoheat** [comment]
hi @ctr49 
sorry for the late reply on this ticket. Our feedback on this is the following:
- generally, it is possible to write an own adapter for HTTP-header based authentication and authorization 
- ensure that headers only come from libapache2-mod-shib and not from the client  

best, lukas
