### ISSUE TITLE
Batch Editing for Fundus

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1434]
Fundus needs a batch editing of their inventory for following items: 

ALL ITEMS STARTING WITH "N......" WHICH ARE IN INVENTORY PARK "FUNDUS-DDK"

Changes:
- Building = Niederhasli
- Room = Möbellager
- Shelf = unbestimmt
- Remove the inventory nr. from the model name
- Responsible inventory park AND Owner = "Fundus Niederhasli-DDK"
- "Ausleihbar" = YES
- Category = Fundus / Möbel NIHA

Delete main category "Fundus LÖSCHEN"

**Comment by nimaai** [comment]
> Shelf = unbestimmt

Really `unbestimmt` as value or simply empty?

**Comment by nadjaweisskopf** [comment]
Shelf= Leave empty
Model name: can you say, only take the nr. away if still unique otherwise leave as it is?

**Comment by nadjaweisskopf** [comment]
Script is OK. Maria will inform us as soon as we can run the script on Prod.

**Comment by nimaai** [comment]
executed on staging. @neoheat ok?

**Comment by neoheat** [comment]
execute script on 5.9.2023

**Comment by neoheat** [comment]
script was executed, until GO from Fundus, the inventory park stays inactive.
Group `DDK.alle` will get `customer` role as soon as the park goes live.
