### ISSUE TITLE
Improve Admin-UI

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1437]
1. Page https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/1538de5a-d5bb-5e55-8065-7d7681a6e739
Move following lines below line "responsible user"
- number of users
- number of direct users
- number of groups

✅ 

2. Page https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/1538de5a-d5bb-5e55-8065-7d7681a6e739/users/
- Move the filter "member" between filter "search" and "enabled"
- Write "user" instead of "fuzzy term" in filter "search"
- Change column title "Group member" to "Add/Remove whole Group"
- Cnange column title "Direct member" to "Add/Remove person"

✅ 

3. Page https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/delegations/1538de5a-d5bb-5e55-8065-7d7681a6e739/groups/?org-member=&per-page=50&membership=any&page=1&term=&including-user=
- Write "group" instead of "fuzzy term" ✅ 
- Change the filter per default to "members and non-members" (is it possible to show "members and non-members" only if there is not a direct group added yet?)

> see in comments 

4. Page https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b392ddbb-3586-544d-bbd4-348d078cab83/groups/?page=1&per-page=50&org-member=&term=&including-user=&membership=any
- Write "group" instead of "fuzzy term"

5. https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b392ddbb-3586-544d-bbd4-348d078cab83/users/
- Write "user" instead of "fuzzy term"
- Change column title "Group member" to "Add/Remove whole Group"
- Cnange column title "Direct member" to "Add/Remove person"

✅

**Comment by DrTom** [comment]
About the "membership" filter and its default: 

> is it possible to show "members and non-members" only if there is not a direct group added yet?

possible yes, but not trivial; might be necessary to extend the API; might be possible to do it only in the frontend only for the first page and only "directly" after the component has been mounted and the data has been loaded; would need some thinking, playing, and checking if there are unintended  side-effects and corner cases 

> Change the filter per default to "members and non-members"

That would be possible, but: right now this is a shared component which affects every place where membership of groups is used; so changing that would affect all those places, I guess that would be consistent. Is it meant to change everywhere? 

Note: the user membership is a different component and would not be affected, but should that one be changed, too? Like with groups it is a shared component and would affect every place it is used.

**Comment by DrTom** [comment]
How about not an automatic reload but button to click when there are no members, like: 

<img width="1441" alt="Screenshot 2022-09-20 at 09 11 13" src="https://user-images.githubusercontent.com/526053/191191748-00d3684d-145a-4023-ac4f-76097fcece88.png">

This is should be not too complex to implement and it does not have any adverse side effects.

**Comment by nadjaweisskopf** [comment]
@DrTom I like the solution you suggest with the button. I think that could help indeed. Shall I create a new ticket for this? 

I could not find the new solution on test for points 4 and 5 from this ticket above.

**Comment by neoheat** [comment]
follow-up in https://github.com/leihs/leihs/issues/1590
