### ISSUE TITLE
don't create old audits anymore

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1440]
- [ ] remove `audited` from rails models
- [ ] put a disclaimer on the legacy audits page with a link to new audits

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/18e8dfa99cb8b0aa28192966f4a964c554076d53

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check if changes are not adjusted in old audit, just in new audit.
