### ISSUE TITLE
contract validation fails when containing lines with different start dates

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1443]
A take back cannot be performed when contract contains reservations with different `start_date`s:

https://github.com/leihs/leihs_legacy/blob/6e03d993d0152334e031a062fb28363c86087f15/app/models/contract.rb#L82-L84

An [issue](https://service.functional.swiss/#ticket/zoom/289) has been reported from HKB where this is the case.

@nadjaweisskopf FYI

**Comment by nadjaweisskopf** [comment]
ZHdK has reported the same issue. The start date of the Reservation ID 6bd38660-32cf-47da-835d-aa704f6565d7 from contract 64HR8 had to be adjusted.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/fb4a3ed864861a375a54a726f188015a6e14f385

**Comment by nadjaweisskopf** [comment]
Can not be tested.

**Comment by nadjaweisskopf** [comment]
Not merged yet!! Do not test until @nimaai says so.
