### ISSUE TITLE
move `mail-templates` from old to new admin

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1445]
to-do:

- [x]  create in new admin
- [x]  tests
- [x]  delete from old admin (controller, views, routes, tests, etc.)
- [x]  change apache conf

**Comment by nimaai** [comment]
The global mail templates live in the DB as `SELECT * FROM mail_templates WHERE is_template_template = TRUE`.

Example of a specific template type:
```
                  id                  |   name   | type  | language_locale | is_template_template 
--------------------------------------+----------+-------+-----------------+----------------------
 db8d5508-ca73-5d82-b39c-ee45575d9fe1 | rejected | order | es              | t
 f94f2014-e41e-5541-8db5-033eb09869a4 | rejected | order | gsw-CH          | t
 4c196597-07a2-5e94-90f4-9a98278f11aa | rejected | order | de-CH           | t
 8ca7bfa0-69aa-53b3-8500-67a0811b12ab | rejected | order | en-GB           | t
 bdf25867-490e-4fb0-afac-8b8399a2a869 | rejected | order | en-US           | t
 ae1e6782-7c00-4a62-b2e0-ad9ae89442a7 | rejected | order | fr-CH           | t
(6 rows)
```

In old admin there is only one edit page for all language flavours of a specific template type (due to convenience reasons I assume): https://leihs.zhdk.ch/admin/mail_templates/order/rejected

I tend to do it differently in new admin, means analogous to how other resources are implemented there, means an individual show/edit page for each mail template (row in DB).

Similarly, I would list them individually on the index page too. One can offer better additional filter possibilities (language, type) for the user to find and edit templates more conveniently.

It might sound as a bad tradeoff in comparison the the old solution, but is less confusing in the context of the whole admin section and how it is conceptually intended to be.

OK @nadjaweisskopf ?

@DrTom I assume you agree too.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d90191abd2819e4b7a0aa504cc41aba697448abf

**Comment by nadjaweisskopf** [comment]
@nimaai test ist ok, everything looks really good, thanks for the good implementation! It's much more user friendly than it was before. 
Just one thing for after the release: Spelling mistake "initial" instead of "intial" in the description of the setting page on the top.
