### ISSUE TITLE
Besetzungszeit lässt sich erneuern

### ISSUE THREAD

**Issue by aysesoy** [leihs/leihs#1446]
Falls man im leihs am bestellen ist und bei der Bestellung auf den Zähler klickt, fängt der Zähler erneut von 30:00 an. Somit wäre es möglich die Sachen im Warenkorb länger als 30 Minuten zu besetzen.

![image](https://user-images.githubusercontent.com/111506180/193081629-695bcec0-2ce4-41e5-861a-27f3d8109234.png)

Kann das aufgehoben werden?

**Comment by nimaai** [comment]
Dies ist so gewollt. Mehr Details auf: https://github.com/leihs/leihs/wiki/Borrow:-basket-and-timeout
