### ISSUE TITLE
Bug: User deletion does not cascade to procurement authorization tables

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1456]
This issue was observed in context of the LDAP sync at ZHdK, but might also happen when a user is deleted via Leihs Admin UI. 

When a record in table `users` is deleted, there is a cascade to `groups_users` (maybe also to related tables), but not to `procurement_requesters_organizations` (and most likely neither to `procurement_category_viewers`, `procurement_category_inspectors` and `procurement_admins`). An orphaned record is left behind there, causing the procure admin UI to crash because of a GraphQL not null constraint violation. 

Also, it is probably not OK that there is no referential integrity (FK constraint) on `procurement_requesters_organizations.user_id`

**Comment by nimaai** [comment]
current foreign keys on `users`:
```
TABLE "procurement_admins" CONSTRAINT "fk_rails_7f23ec3f14" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
TABLE "procurement_category_viewers" CONSTRAINT "fk_rails_9e16e3bd5d" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "procurement_users_filters" CONSTRAINT "fk_rails_ecc9c968b6" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
TABLE "procurement_requests" CONSTRAINT "fk_rails_f365098d3c" FOREIGN KEY (user_id) REFERENCES users(id)
TABLE "procurement_category_inspectors" CONSTRAINT "fk_rails_f80c94fb1e" FOREIGN KEY (user_id) REFERENCES users(id)
```

to-do:
- [ ] `procurement_requesters_organizations` FK
- [ ] `procurement_requesters_organizations` ON DELETE CASCADE
- [ ] `procurement_category_viewers` ON DELETE CASCADE
- [ ] `procurement_category_inspectors` ON DELETE CASCADE

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/a9f524663820f18216ea54e74cd4c684b6a3a89a

**Comment by nadjaweisskopf** [comment]
can be tested on test

**Comment by nadjaweisskopf** [comment]
@neoheat 
to test: 
- on user page
- and on category page
