### ISSUE TITLE
Procure admin UI: Crash when user search field is cleared

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1457]
Steps to reproduce: 
- Open procurement with admin rights
- Open "Admin" -> "Benutzer"
- In the bottom of the section "Antragsteller/innen" type something into the "Suchen" field
- Delete what you typed
- Crash / white screen. Browser console shows "Error: Ambiguous result!"

**Comment by nadjaweisskopf** [comment]
Same behaviour in templates when adding an inspector or viewer

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/edefd7a3f42cf2c9c49b1cbfe77477a5427acffe
