### ISSUE TITLE
New Borrow: Model detail shows "Add item" button although model is not reservable for the current user 

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1458]
How to reproduce in ZHdK instance, Ausleihe Toni:
- Login as a user which is not in entitlement groups
- View one of the templates titled with "NUR FFI ..." (Note: as of 20.10.2022 this feature is not yet merged but on the branch `uvb/templates`) 
- Most models will show as "not reservable" (grey), as expected (these are models which are also not findable in categories and search by this user, as expected)
- Click on one of the non-reservable models to show its detail page 
- The button "Add item" is visible. The booking calendar will open, but it correctly will show availability zero for all dates) 

The model detail page currently uses the "pool availability" (the number labelled "Maximum available amount" shown in the order dialog) to decide whether the "Add item" button is shown or not. Probably "pool availability" should be calculated the same as in templates, categories and search. Or the check should use a different method to find about reservability, i.e. the same as in templates, categories and search.

**Comment by nadjaweisskopf** [comment]
Will be refined in a technical meeting.

**Comment by nadjaweisskopf** [comment]
@nimaai please review!

**Comment by nadjaweisskopf** [comment]
Specs to be done, then the ticket can be merged.
