### ISSUE TITLE
Empty property-key error message misleading, model created anyway

### ISSUE THREAD

**Issue by andypillip** [leihs/leihs#147]
When creating a model one can add _properties_, key-value pairs.

Leaving those inputs empty results in an error message, something like
> key is empty

These key-value-input boxes don't have any label and are not marked faulty, so it's not clear where the error actually is.

In my opinion an empty key-value-pair should just be ignored. One might add several at once and only fill out part of them.

**Definitely the faulty input needs to be marked**.

Biggest problem: **The model is created anyway**, but the user is still presented with the form.

In my case I corrected several other fields before finding out the real problem, and after that the model was created 4 times. It's not possible to distinguish the faulty ones from the real one.

**Comment by psy-q** [comment]
You are right, and what's worse is that the model is even created twice, three times, however many times you press "save", despite the error. I can reproduce this on 3.44.0.

**Comment by nadjaweisskopf** [comment]
scenario might need to be updated in order to have tests.

**Comment by nadjaweisskopf** [comment]
Reproduce: 

1. go to pool
2. open "create new model page"
3. enter a model name
4. press on the button "Add property"
5. do not enter a key or a value
6. save the model
7. you get an error but the model has been saved

The model should either be saved without giving an error msg. - just do not save any properties
OR the error msg. should show but the model should not be saved.

**Comment by eins78** [comment]
fixed in backend, if there are any errors the model is not saved.

**Comment by nadjaweisskopf** [comment]
Test create a model generally
