### ISSUE TITLE
Problems with multiple hostnames for the same instance  

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1474]
The links of an instance which is configured for multiple hostnames while technically correct can lead to errors hard to comprehend for normal users because the current session is only valid for one of the other hostnames. 

While there are many ways to fix that; the simplest way is to always force the user to use the `base_url` configured in the settings. All external authentication systems do that (because this is how it works) but password sign in works with any of the domain names. So we enforce the  password sign in also to do a redirect to the domain as set in `base_url`.  That needs to be done before the cookie is set.

**Comment by neoheat** [comment]
not an issue for Leihs
