### ISSUE TITLE
Analyse case

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1478]
According to lending dept. the user could lend an item even though there was no availability.

Following was the case in October: 

- All users are in group DFA_VFO
- One of three items was defect and not lendable. Therefor two items were lendabe for customers.
- According to the time table there was an overbooking.

<img width="1261" alt="Bildschirmfoto 2022-10-25 um 08 58 17" src="https://user-images.githubusercontent.com/3356016/201631772-ad2f4431-a4aa-457e-a75c-a817ab36823a.png">

Question: Could the user lend the item even though there was no availability?

**Comment by neoheat** [comment]
closed due to no further reports in this regard
