### ISSUE TITLE
Compatible Model without Items are listed in frontend

### ISSUE THREAD

**Issue by andypillip** [leihs/leihs#148]
When assigning a Model without Items under _Compatibles_, the link is output in the frontend anyway.

Of course clicking the link will result in a 404,
> The page you were looking for doesn't exist.

**Comment by psy-q** [comment]
That sounds like a bug, thanks :)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7fb2109bbea94774b22959ea9434279eded23c5e
