### ISSUE TITLE
Legacy: update node version used in assets compile (currently v10/dubnium)

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1482]
Maybe this requires and/or facilitates further improvements:
- get rid of yarn
- get rid of git-tracked node modules

**Comment by urs-van-binsbergen** [comment]
Updated to v16/gallium
https://github.com/leihs/leihs/commit/5a16011af7c8dfa0cb982e00bbd4802ab95b7bed

Nothing changed about the above mentioned issues (yarn and git-tracked node modules)

**Comment by nadjaweisskopf** [comment]
@DrTom Overall test as soon as release has been created.
