### ISSUE TITLE
New Borrow: Language switch does not appear anymore

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1485]
(The issue is on `master`, but not in production)

Steps to reproduce: 
- Open new Borrow
- Click on the user menu button
- There will be no language buttons

The problem probably is a unwanted side effect of 2280e9cdaed1e6ba82f657d3a5ea363e501b6a93

There were no __specs__ covering the language switch! Several specs actually _do_ a language switch, but by writing into the database, not via UI -> this must be changed! The irony is that I added a spec in my latest push which checks for the presence of the language switch, that's why I discovered the issue.

**Comment by nadjaweisskopf** [comment]
@urs-van-binsbergen I can't reproduce this bug on production. Could you give further steps on how to reproduce this issue?

**Comment by urs-van-binsbergen** [comment]
@nadjaweisskopf I added the "accepted" label. The issue never was in production, and is fixed on `master` now. So not possible to reproduce anymore.
