### ISSUE TITLE
Remove SSR 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1487]
What it does: rendering some parts (of the Navbar, ...) on the server. 

Why it does that: ? 

Costs: complexity in Code, complexity within the deploy code and on the server

Alternative: render in the browser as iy is done with everything else.

**Comment by neoheat** [comment]
will be changed with
https://github.com/leihs/leihs/issues/1580
https://github.com/leihs/leihs/issues/1581
https://github.com/leihs/leihs/issues/1582
