### ISSUE TITLE
Pool-manage description shown instead of pool name

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1491]
#### Expected behaviour or future wish
When searching for "weisskopf", in the section "items" and "licenses", the pool manage description is shown instead of the pool name. 

#### Issue or wish reported by
NW, when testing the tickets

#### Current behaviour
When searching for "weisskopf", in the section "items" and "licenses", the pool manage description is shown instead of the pool name. 

#### Steps to reproduce
1. Go to test environment
2. search for "Weisskopf"
3. scroll down to items and licenses
4. Instead of the pool name the pool desciptions including mail etc. are shown. 

![grafik](https://user-images.githubusercontent.com/3356016/206476059-eb61f931-02cd-42a1-8c64-50ffac5cf2df.png)

#### Acceptance Criteria
Show pool name

Show show
![grafik](https://user-images.githubusercontent.com/3356016/206476243-d7ac02f8-4e3e-4206-9d22-4cb4539431c9.png)

#### Specifications
- Leihs version: 6.7.0 - test version
- Browser version: firefox

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/00ec412a6ad3ba3a81afeb2e1dc5cf607359b93e
