### ISSUE TITLE
Availability problem

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1492]
#### Expected behaviour or future wish
Case: 
- 16 items (of a package model), 7 are available, not in an entitlement group
- 5 items, which are not available (flag) have been lended
- These visits should not change the availability number of 7

F.e. https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/inventory?flash[success]=Modell%20gespeichert

#### Current behaviour

- There are only 2 available after 5 (flagged not available) have been handed out

#### Steps to reproduce
- see above

#### Specifications
- Leihs version: 6.7.0
- Browser version: safari

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/77c8dbc7beabd25521d20cc4f52b61340d771079
