### ISSUE TITLE
Error in new borrow

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1495]
#### Expected behaviour or future wish
I would expect to see my orders after I have sent the cart. 

#### Issue or wish reported by
me

#### Current behaviour
I get an error after submitting the cart. 
Time: 23.12.22 at 22.00 (to view the log)

#### Steps to reproduce
- I added the item 4K-Vollformatkamera Sony ILME-FX3 Cinema Line to the cart
- I had to delete three other items which were already in the cart in order to submit the cart
- I submitted the cart after entering reason, title, contact details
- I get an error as soon as Leihs tries to load the orders. 
- If I set the filter of the orders to "in Genehmigung" then the new order is shown.  

Error: 
![grafik](https://user-images.githubusercontent.com/3356016/209405460-8473448e-8333-4a51-a4e6-c63e82d9e16e.png)

![grafik](https://user-images.githubusercontent.com/3356016/209405507-f559cca3-7ec9-42cd-a72a-ad856582b0e4.png)

#### Specifications
- Leihs version: 6.8.0 (Release candidate)
- Browser version: safari

**Comment by nadjaweisskopf** [comment]
@nimaai this is the same error as the lending mgr had at the external school.

**Comment by neoheat** [comment]
after a joint testing between @nadjaweisskopf and @neoheat yesterday, the error couldn't be reproduced

**Comment by nadjaweisskopf** [comment]
will be opened again if needed.
