### ISSUE TITLE
Setting `enable_starttls_auto` crashes mailer

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1496]
Background: #1497 

This temporary patch makes the setting `enable_starttls_auto` ineffective, to avoid crashing the mailer. However it should be made effective again.

**Comment by nadjaweisskopf** [comment]
step to solve problem
1. keep templates in legacy
2. do not use rails to send mails in legacy, use existing mail service (leihs-mail)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/issues/1498

**Comment by nadjaweisskopf** [comment]
doesn't need to be tested, should be solved with #1498
