### ISSUE TITLE
New borrow: optimize layout and typography

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1508]
Typography and colors: 
- Use font weight 400 (normal) instead of 600 (semi bold) for buttons, titles and labels. Semi bold for content
- Links blue, not underlined

Nav/layout
- Nav on top instead left, no buttons (see screenshot)
- New icon for user menu (+ tooltip)
- Redesign cart and area nav (+ tooltip)
- "My Orders" > "Orders", "Documentation" > "Help"
 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/25439444/232525001-42088c02-208d-4aaa-8e50-74ade43b191d.png">

![image](https://user-images.githubusercontent.com/25439444/232524770-66bef76d-9a74-403c-89b1-813386d015d7.png)

Modal: 
- wider
- dark background
- more padding in md+
- top border for bottom bar

Category breadcrumbs: blue, light and horizontal: "Audio / Recorder"

Calendar: redesign according to screenshot

![image](https://user-images.githubusercontent.com/25439444/232524494-ea54c156-8931-459c-8c62-157c5c6bb3c2.png)

Collapsers (angles) only for lists, or, for content one would actually like to hide... for instance not for model list

Toggler for "Choose date" in filter: Switch style instead of checkbox

Model filter redesign + change "X" icon of "FilterButton" (see screenshot)

![image](https://user-images.githubusercontent.com/25439444/232527062-cc6f3f89-bee0-4e1e-ab19-613f7964fcee.png)
![image](https://user-images.githubusercontent.com/25439444/232524559-a7eb6b22-b910-42da-aaa2-99f7d74d78a2.png)

Icons for Minus/Plus buttons (see screenshot)

![image](https://user-images.githubusercontent.com/25439444/232524714-14b7491d-2875-4370-bb5a-99402d20603d.png)

Orders list: progressbar max width and float right if enough width available

**Comment by neoheat** [comment]
tested positive in test.leihs.zhdk.ch
