### ISSUE TITLE
Correct behaviour in regards to visibility of information in request and export

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#151]
How it should be for an existing request:

Admin can view everything but can not edit.
Inspector can always view everything but edit in his own categories. 

**Approved quantity / Inspection comment:**
Requesting Phase / Inspection Phase:
- inspector in own categories: editable
- requester: label shown, value not shown

Budget Period has ended: 
- requester and inspector: label shown, value shown (not editable)

**order amount / Inspector's Priority:**
Requesting Phase / Inspection Phase:
- inspector in own categories: editable
- requester: label not shown, value not shown

Budget Period has ended: 
- inspector: label shown, value shown (not editable)
- requester: label not shown, value not shown

**Comment by nimaai** [comment]
I assume that an inspector **cannot** edit order amount / inspector's priority of a request where he can inspect its category **BUT** request's budget period is past?

**Comment by nimaai** [comment]
@nadjaweisskopf  another question: currently one can edit a request only if one is a procurement requester. this is wrong, right? one can possibly be an inspector without having to be a requester...?

**Comment by nadjaweisskopf** [comment]
No, this is not quite correct. 
Franco didn't want hierarchical roles. So we defined that an inspector always has to be assigned to the list of requesters. And if he is inspector too, he is also assigned to a category.

**Comment by nadjaweisskopf** [comment]
BUT - an inspector can always edit any request which belongs to a category he inspects.

**Comment by nimaai** [comment]
@nadjaweisskopf you can check and adjust scenarios in the pull request for this branch: #154

**Comment by nadjaweisskopf** [comment]
Correct. One can not edit an order if the budget period has passed, no matter which role you have.

**Comment by nadjaweisskopf** [comment]
one wrong behaviour for **requester**:
- Overview shows "approved amount" when
- requesting phase is active or inspection phase has started

All other test cases are fine, including exports CSV and Excel

one wrong behaviour for **inspector**:
- Fields "approved amount" and "inspector's comment" are writeable even though
- budget period has ended. 

All other test cases are fine, including exports CSV and Excel
