### ISSUE TITLE
References (Who uses leihs?)

### ISSUE THREAD

**Issue by HoMeMartin** [leihs/leihs#1514]
Hi leihs Comunity,

at the site https://github.com/leihs/leihs/wiki#references-who-uses-leihs 
stands "Please create an issue if you would like to be listed here.".

So hear I am, the admin of the SMK department of the Hochschule Merseburg 
responsible for the leihs implementation, with the wish to be listed on the project page :-).

[https://leihs.hs-merseburg.de/](url) Hochschule Merseburg, Germany

P.S.: 
 Leihs is so great, we use it every Day and not just for lends 
 I use it also as an inventory system for all IT Hardware of the employees.

**Comment by neoheat** [comment]
Dear @HoMeMartin 
Thank you for your message about being added to the list of universities that use Leihs - which we did immediately. And we really appreciate you using the app and look forward to more feedback and contributions.

Herzliche Grüsse nach Meresbur vom Leihs-Team der ZHdK
