### ISSUE TITLE
Features list not usable

### ISSUE THREAD

**Issue by mimosel** [leihs/leihs#1515]
On https://github.com/leihs/leihs/wiki under the headline "Features" the link goes to https://relishapp.com/leihs/ which unfortunately throws an application error: "An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail"

Having a readable feature list would be nice.

**Comment by neoheat** [comment]
dear @mimosel 
thanks for the message, we will take care of it.

**Comment by neoheat** [comment]
@neoheat for now not required, but change link to /leihs/manuals
