### ISSUE TITLE
Release Notes: broken link

### ISSUE THREAD

**Issue by mimosel** [leihs/leihs#1516]
On https://github.com/leihs/leihs/wiki under the headline "Release Notes" a link goes to https://github.com/leihs/leihs/blob/master/config/releases.yml which unfortunately throws an 404: "The 'leihs/leihs' repository doesn't contain the 'config/releases.yml' path in 'master'.  "

**Comment by neoheat** [comment]
link changed in https://github.com/leihs/leihs/wiki
