### ISSUE TITLE
Borrow Desktop Enhancement - category menu

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1523]
Task
- change the category menu from a collapse state into an opened menu, left aligned to the search and list view
- reduce font-size and elipsis to have a minimal appearance of the category menu
- navigation to a parent category can be done by using the links in the breadcrumb
- decide if the breadcrumb could possibly be aligned left above the category menu

make sure, the changes do not affect the mobile view 
<img width="1787" alt="subcategories left navigation2" src="https://user-images.githubusercontent.com/123965725/232779272-5c6e04d1-9cc6-43ae-aa31-323445ff5ec1.png">

**Comment by neoheat** [comment]
**Feedback from Joel**
<img width="1947" alt="MontageKategorien" src="https://user-images.githubusercontent.com/123965725/234796441-dcabb23f-2480-42c1-8c6d-9771699a3018.png">

@urs-van-binsbergen can you implement joel's implementation suggestion on a test basis so that we can check the behavior accordingly

use case
> if there is any more subcategory in a active category, the sibling categories should be displayed. The active category is bold

**Comment by urs-van-binsbergen** [comment]
Wir haben aktuell zwei Versionen:
- Branch `uvb/cat-nav`, auf NEXT deployed: erste Version von lb/uvb. Auf der jeweils untersten Ebene (so es keine Unterkategorien mehr gibt) werden nur noch die Breadcrumbs gezeigt
- Branch `uvb/cat-nav-deep` (on top of `uvb/cat-nav`). Gemäss Vorschlag jg: Auf der untersten Ebene kann man in den den Siblings navigieren, d.h. man sieht (fast) immer eine Navigation. 

(Achtung, beide Branches sind quick & dirty Prototypen - do not merge!)

Bei uvb/cat-nav-deep werden neu bei jeder neu aufgerufenen Kategorie deren Children + Grandchildren geladen! Das erhöht die Serverzeit (z.B. auf localhost uvb, Kategorie Audio von ca. 200ms auf 1.5s). Das ist problematisch, einerseits wegen der Serverlast, aber auch weil es aus Sicht des Users spürbar hakelig wird. 

Lösungsansatz: 
- Normalerweise ist es effizienter einen Baum als ganzes zu laden, als N+1-mässig runterzudrillen. Die Anzahl ist nicht sehr gross (bei ZHdK ca. 500). Die Hierarchie muss nicht unbedingt per SQL erzeugt werden, sondern kann applikatorisch gebaut werden, so dass 1-2 Queries ausreichen, um alles zu laden.  
- Als erstes ist zu prüfen, wie performant sowas ist. Ich vermute, dass das mit 200ms gehen würde.
- Ob performant oder nicht, man kann den ganzen Baum beim ersten Aufruf auf Home oder auf eine Kategorie laden, somit würde die Navigation für den User extrem flüssig, da alles sofort in der App DB ("Client Cache", Session Storage) verfügbar ist
- Die Frage ist dann noch, wie oft man die App DB refreshen möchte. Änderungen gibt es nur, wenn im Inventar gearbeitet wird, oder wenn Berechtigungen vergeben werden. Denkbar wäre sowas wie: einmal pro Minute wird neu geladen (nicht automatisch; nur wenn in den Kategorien navigiert wird). Ausserdem könnte man ermöglichen, dass ein Browser Reload das Neuladen erzwingt (indem man die Kategorien nicht mehr in der Session Storage hält, sondern nur im flüchtigen Speicher)
- Unklar ist mir derzeit, wie man das mit GraphQL löst. Ausserdem, wie man die Daten neu in der App DB verwaltet.

**Comment by neoheat** [comment]
Feedback aus Kommunikation mit Joel:

- er meint es gäbe weiterhin Optimierungspotential, der iterative Ansatz der Verbesserungen solle aber nicht weitergeführt werden. Dies müsse in einem ganzheitliches Design entwickelt werden.
- da wir derzeit kein Design geplant haben, noch das Budget vorhanden ist, werden vorerst darauf verzichten
- die aktuelle Lösung wie in http://uvb.ruby.zhdk.ch deployed, soll für das Golive genutzt werden

somit muss final geprüft werden, wie diese verbesserte Darstellung der Unterkategorien technisch optimiert werden muss, bevor wir live gehen können. 
Weitere Task zur Vorbereitung des Golive New Borrow Desktop ist in https://github.com/leihs/leihs/issues/1527 aufgeführt.

**Comment by neoheat** [comment]
✅ tested positive
