### ISSUE TITLE
Bug in Software License

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#153]
See OTRS-Ticketnr. ZHDK#2016110710001695
https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=136159

How to reproduce: 
1. Open Pool "IT-Software"
2. Search for "INV18474"
3. Open License
4. Add a new line in "Quantity Allocations" section
5. Enter Amount and name
6. Save
7. You get the error msg. sorry, but something went wrong. 

******

I could reproduce the or at least "an" error. Please find attached the printscreens. The exact times for the log: 

FINALE 2014 (retired)
1. error 09.07 - 6.12.16
2. error 09.09 - 6.12.16 (probably because first error was not yet resolved)

**Comment by nimaai** [comment]
in TEST log I see:

> F, [2016-12-06T09:04:51.017404 #3660] FATAL -- :
ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'audited_changes' at row 1: INSERT INTO `audits` (`action`, `audited_changes`, `auditable_id`, `auditable_type`, `created_at
`, `version`, `request_uuid`, `user_id`, `user_type`, `remote_address`) VALUES

seems that the value we want to persist in `audits.audited_changes` of type `text` is too long.
