### ISSUE TITLE
Switch to new borrow: port remaining missing availability functionality for booking calendar

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1530]
The core logic of the availability computation has already been ported from legacy to new borrow. The data for the booking calendar are still being fetched from old borrow though via `/borrow/booking_calendar_availability` though. This should now also be implemented in the new borrow.

**Comment by nimaai** [comment]
@neoheat to be tested:
* compare calendar data between new and old borrow

**Comment by neoheat** [comment]
✅ tested positive
