### ISSUE TITLE
Inventory: Error, when saving edited model description

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1554]
#### Expected behaviour or future wish

A change in a model of the inventory can be saved without error

#### Issue or wish reported by
neoheat

#### Current behaviour

Error appears when saving a change in a model in inventory pool

```
{"error":{"code":422,"message":"Unprocessable Entity","details":["ActionController::InvalidAuthenticityToken","/home/leihs-legacy/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'","/home/leihs-legacy/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'","/home/leihs-legacy/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'","/home/leihs-legacy/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'","/home/leihs-legacy/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'"]}}
```

#### Steps to reproduce
- login as a inventory pool manager
- go to an inventory pool
- open a model in inventory
- edit anything
- save change

#### Acceptance Criteria
The changes made in the input mask of an model can be saved.

#### Specifications
- Leihs version: RC 7.0
- Browser version: any
- MySQL/PostreSQL version: any

**Comment by nimaai** [comment]
This concerns all XHR POST etc. requests.

**Comment by neoheat** [comment]
Same (?) Error just popped up in `borrow` while approving an order
<img width="1083" alt="Bildschirmfoto 2023-06-20 um 13 29 20" src="https://github.com/leihs/leihs/assets/123965725/2978a13a-54ca-4ce4-996a-cf15ce3f5eb2">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9dd8b3292d3f35bb1b6cf71ae125dfb2a7d1cab3

**Comment by neoheat** [comment]
tested positive every form in `manage`
