### ISSUE TITLE
Timelimit bar not working

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1565]
**Expected behaviour or future wish**

The timelimit bar shows the leftover time, until the order in the basket expires

**Issue or wish reported by**

neoheat

**Current behaviour**

- the blue timeline bar does appear in Safari / Chrome / Brave browser
- works in Firefox 102.12.0esr

**Steps to reproduce**

– Add item in basket
– view basket and see the missing timeline bar

**Acceptance Criteria**

If the order has items with assigned values, the total should be calculated and shown to the user on the contract

**Specifications**

Leihs version: 7.0 RC
Browser version: Safari Version 16.5 (18615.2.9.11.4), Chrome Version 114.0.5735.133, Safari (iPhone)
MySQL/PostreSQL version: any

**Comment by neoheat** [comment]
Style Attribute is not set
![Isseue Style attribute](https://github.com/leihs/leihs/assets/123965725/50f5d5b6-2b57-4a67-8ba2-9013df84ce62)

Issue in Safari (no timeline bar)
![Safari](https://github.com/leihs/leihs/assets/123965725/bdb976f2-3531-437f-814a-b02ee766665d)

**Comment by urs-van-binsbergen** [comment]
85935e0b9ee12e107d0154e05eb5a7e8e7335a89

**Comment by neoheat** [comment]
tested positive
