### ISSUE TITLE
Fork https://github.com/eins78/post_office to https://github.com/leihs

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1570]
The fork https://github.com/eins78/post_office  should be forked to https://github.com/leihs ensure this repo is still accessible by the Leihs development team instead of private repositories

**Comment by neoheat** [comment]
procedure
1. Check, if not the original repo can be used
2. if not, fork repo https://github.com/eins78/post_office

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/b7716da9356c3e63b451497a35d65b01e6b97bdc
