### ISSUE TITLE
Error in borrow order overview after order owner change

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1571]
**Expected behaviour or future wish**
No error in order overview, when order owner is changed

**Issue or wish reported by**
@neoheat 

**Current behaviour**

**Steps to reproduce**
- User places an order
- User can see the order in order overview
- Lending manager changes the order owner
- Original order owner reloads the order overview and sees the attached error
- Error appears even when user logout and relogin (but does not appear, in another browser)

![MicrosoftTeams-image (1)](https://github.com/leihs/leihs/assets/123965725/f108b49a-108e-4ff3-85c8-e92a99b812c5)

Maybe connected to issue #1495.

**Comment by neoheat** [comment]
quick fix with excluding orders with `empty  from_date` and `until_date`  for [7.0.RC2](https://github.com/leihs/leihs/pull/1578) works well, I'll leave this issue opened to fix it the right way in next release

**Comment by nimaai** [comment]
current situation:
- If the last reservation of the order is _deleted_ in the hand over then the order is deleted too.
- If the last reservation of the order is _moved_ to another user in the hand over then the order is not deleted.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/901782bc5ae9b54142ccec34c311247324f389de

**Comment by neoheat** [comment]
tested positive.
