### ISSUE TITLE
CSV export of models for inventory

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1576]
#### Expected behavior or future wish
CSV export of all models of an inventory park

- Modell ID  `unique id and model name`
- Modell `model name`
- Anzahl Gegenstände `count of items of the corresponding model`
- Letzte Inventur `last_check`
- Erste Anschaffung `creation date of the first item`
- Anzahl Ausleihverträge [[Jahr]] `count of contracts of the corresponding model`

The number of contracts per year should be visible.
The script should be easily adaptable to other inventory parks

#### Issue or wish reported by
Angelo Brem, Werkstatt Ausleihe

#### Current behaviour
not possible via Inventory / Admin

#### Steps to reproduce
-

#### Acceptance Criteria
- Script can be executed by a Leihs developer
- Data of export contains the columns as defined in `Expected behavior`
- CSV can be opened in Excel

**Comment by nimaai** [comment]
Nur Anzahl nicht ausgemusterten Gegenstände oder alles @neoheat ?

**Comment by neoheat** [comment]
@nimaai Gute Frage. Vielleicht würde es mehr Sinn machen die Anzahl Gegenstände aufzuteilen auf Aktiv / ausgemustert als zwei Spalten anzubieten:
- Anzahl Gegenstände Aktiv [count of items of the corresponding model Aktive]
- Anzahl Gegenstände Inaktiv [count of items of the corresponding model Inactive]

**Comment by nimaai** [comment]
[all-items.csv](https://github.com/leihs/leihs/files/12429000/all-items.csv)
[all-unretired-items.csv](https://github.com/leihs/leihs/files/12429001/all-unretired-items.csv)
[contracts-per-year.csv](https://github.com/leihs/leihs/files/12429002/contracts-per-year.csv)

https://github.com/zhdk/leihs-server-inventory/commit/894b8dd8f373203950ff8d8322e5b3929d8c50b2

**Comment by neoheat** [comment]
danke. werde den Auszug weiterleiten.

**Comment by nimaai** [comment]
[all-items.csv](https://github.com/leihs/leihs/files/12473540/all-items.csv)
[all-unretired-items.csv](https://github.com/leihs/leihs/files/12473541/all-unretired-items.csv)
[contracts-per-year.csv](https://github.com/leihs/leihs/files/12473542/contracts-per-year.csv)
