### ISSUE TITLE
procurement: suboptimal interplay between requests and templates

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1579]
There is a reference from the requests to the templates via `procurement_requests.template_id`. This means, once a request has been created using a particular template, such a template can't be deleted although it is not supposed to be used anymore. Moreover, one can still change the details of such a template which creates data inconsistence between the request and the template. This inconsistence is not visible in the UI though, because the request has its own columns for that data.  

One possible optimisation request from stakeholder:

> idealerweise könnten Standarvorlagen auch gelöscht werden, nachdem sie verwendet wurden oder aber zumindest ausgeblendet werden. Da hat es zur Zeit ein paar ganz alte Dinge drin, welches heute gar nicht mehr gekauft werden können.

**Comment by nimaai** [comment]
Solution as discussed with @urs-van-binsbergen:

- Introduce new column `procurement_templates.is_archived (boolean)`.
- As soon as a template has been used for requests (`EXISTS (SELECT TRUE FROM procurement_requests WHERE template_id = procurement_templates.id`), then make the template readonly in UI (+ corresponding validation in backend).
- If the template is used, provide possibility to archive it (UI + backend mutation).
- If the template is not used, there is still the possibility to delete it.
- Collapse the archived templates per default.

**Comment by belafonte** [comment]
https://github.com/leihs/leihs/commit/93fce2eb8ab300c49097284cf1ac6ef05174c2ea
