### ISSUE TITLE
Frontend Updates 2023 - Procurement

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1580]
- Modernize stack
  - Move from CRA/Webpack to Vite
  - General package updates (especially: React Router, Apollo Client, React 18)
  - (Bootstrap 5 -> no)
- Detach from `leihs-ui`
  - Integrate theme 
    - Add SASS to project (`sass` not `node-sass`!)
    - Remove all unneeded SCSS (probably most)
  - Integrate Navbar component
    - Approach: to discuss (minimal effort or refactor or rebuild without dependencies etc.)
- Remove SSR

**Comment by urs-van-binsbergen** [comment]
## Review

### Funktionale Tests

- Anträge
  - Probleme bei Dev-Applikation (Port 4000) -> ggf. prüfen, ob das vorher schon kaputt war. Es könnte mit dem Proxy zu tun haben (der von Port 4000 auf 3230 weiterleitet), gibt es den noch?
    - Kategorienbilder erscheinen nicht
    - Export crasht (Button oben rechts)
    - Hochladen von Anhängen funktioniert nicht
  - Antrag erstellen: Die Budgetperiode muss vorselektiert sein (man klickt ja bereits in der Liste auf das Plus bei einer bestimmten Budgetperiode)
- Admin - Budgetperioden
  - Falsche Datumsformatierung US statt CH
- Admin - Kategorien
  - JS Error Alert nach Erstellung neue Hauptkategorie
- Dev-Menu > UI-Catalog > alle Sub-Views funktionieren nicht (fehlen offenbar in Routes)

**Comment by urs-van-binsbergen** [comment]
2b0cab760e094897589027a0bea52fb8c1ff97c4

**Comment by neoheat** [comment]
@belafonte 
There is an bug in procure/admin when you add a new category. However, the category gets created, but an error is displayed.

![Image](https://github.com/leihs/leihs/assets/123965725/953772d1-d17b-4c7a-a7e4-781a37f09432)


When a category gets deleted, in PROD a (not so meaningful) success message "OK" is displayed. In the current version on TEST, this is no message anymore. But we'll leave it as it is...

**Comment by belafonte** [comment]
[a4666fb](https://github.com/leihs/leihs/commit/a4666fbc9a7be485d4de1eae30ab6660a85c31aa)
