### ISSUE TITLE
Update demo.leihs.zhdk.ch to Version 7.0

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1584]

**Comment by nimaai** [comment]
https://github.com/leihs/demo.leihs.zhdk.ch
https://ci.zhdk.ch/cider-ci/trees/3d3f8a74dd2cda035a76b19155c38b97bcd14c53

**Comment by neoheat** [comment]
@nimaai move to repo `zhdk/leihs-server-inventory`
