### ISSUE TITLE
New order e-mail notification

### ISSUE THREAD

**Issue by Inoutik** [leihs/leihs#1587]
Hi leihs team! Thanks for great product :) 
Please advise with this problem:

**Expected behaviour**
Send to all pool managers letter about new received order according to received order e-mail template

**Issue**
When customer makes new order he receives letter about it (and all changes after), but pool managers not.  

**Steps to reproduce**
Customer makes new order and complete it.

Please where to look to make it work? 

Specifications
- Leihs version: 6.9.1
- Browser version: Mozilla 116.0.2 
- MySQL/PostreSQL version: PostgreSQL 15.3

**Comment by neoheat** [comment]
Hi @Inoutik 
did you check if the boolean `deliver_received_order_notifications` in Admin/Settings/Miscellaneous is `true`?

<img width="806" alt="Setting received_order_notifications" src="https://github.com/leihs/leihs/assets/123965725/ee8370a9-9a16-449a-a513-061522bd2835">

**Comment by Inoutik** [comment]
Wow, it's works now, thank you! 
This setting apparently appeared or was reseted after the update since everything worked before :)
