### ISSUE TITLE
Borrow: `submitted` email uses template `received`

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1589]
#### Expected behaviour or future wish
A user with places an order should receive an order confirmation email with the content defined in the mail template type = `submitted`

the body of the email should contain 
`Ihre Bestellung der folgenden Artikel wurde vom Verleiher genehmigt:`

#### Issue or wish reported by: 
Roger, Ausleihe

#### Current behaviour
The user receives an email with the correct header (sender, receiver, subject), but wrong body. The body of the email is coming from the mail template `received`.

#### Steps to reproduce
1. Login as a user
2. Create an and send an order
3. Check the body of the email which is sent out after the placed order.

the line appears
`Eine Bestellung für die folgenden Gegenstände ist in einem Gerätepark eingetroffen, für den Sie zuständig sind:`

#### Specifications
- Leihs version: production 7.0
- Browser version: any

**Comment by neoheat** [comment]
tested positive in 7.0.1RC2

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d17d034816ef177c7bfa0b5b6c623d02ccddb921
