### ISSUE TITLE
Analysis needed: Success Mail from an order of a delegation

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1593]
#### Analysis needed

When a member (not the responsible person of the delegation) of a delegation makes an order, the person that triggers the order get no email. Instead, the responsible person of the delegation gets one. This email has no name in the salutation.

Please analyse, if this behaviour is the same as in legacy

<img width="1195" alt="Bildschirmfoto 2023-08-31 um 13 16 27" src="https://github.com/leihs/leihs/assets/123965725/54c064d6-d452-45ea-82d8-6280a5dabf43">

#### Steps to reproduce

1. User that creates an order must be a member of a delegation (and must not be the responsible person)
2. Order is sent
3. Success mail is sent to the responsible person of the delegation
4. 

#### Specifications

Leihs version: 7.0.1
Browser version: any
MySQL/PostreSQL version: current

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c137dd07e0526a999b0606c7aeae18156ccf13b1

**Comment by neoheat** [comment]
Order delegation mail type `success` is now correct, this mail is sent to the person that submit the orders for a delegation.
