### ISSUE TITLE
Borrow: Bad Performance when lot of items in basket

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1594]
#### Expected behaviour
The speed of interface operation should not be influenced by the quantity of items in the basket.

#### Actual behaviour
as the number of items in the basket increases, the speed of interface operation decreases.

#### Steps to reproduce
1. login as a user
2. add lots of items (> 30) in the basket
3. check decreasing interface speed

#### Specifications

Leihs version: 7.0.1
Browser version: any
MySQL/PostreSQL version: current

**Comment by urs-van-binsbergen** [comment]
Hintergrund: GraphQL-Abfragen auf den Warenkorb sind relativ langsam (z.B. für 20 Gegenstände 3s). Diese Abfrage wird bei jedem Request gemacht ("refreshTimeout"), auch wenn nicht der Warenkorb angezeigt wird. 

Das allein würde aber nur dazu führen, dass das Warenkorb-Icon mit Verzögerung aktualisiert wird (das sollte auf jeden Fall optimiert werden, ist aber in diesem Kontext nur ein Nebenthema).

Das eigentliche Problem liegt darin, dass der Server offenbar nicht mehrere Requests parallel bearbeitet. Die Browser senden normalerweise 6 Requests gleichzeitig. Der Server bearbeitet zuerst die langsame GraphQL-Query, dies blockiert die folgenden 5 Requests:

<img width="1458" alt="Screenshot 2023-08-31 at 16 55 25" src="https://github.com/leihs/leihs/assets/25439444/6bff0b63-3283-4dbb-8959-3d2c53013bcc">

Das Problem konnte lokal nicht reproduziert werden.

**Comment by DrTom** [comment]
Wie verhält es sich wenn lokal der Reverse-Proxy verwendet wird?

**Comment by urs-van-binsbergen** [comment]
@DrTom wie besprochen: Bitte patchen auf Server. CLJ Server soll mit 4 Threads gestartet werden (--http-threads 4).

**Comment by neoheat** [comment]
### Tasks
- [ ] Change to 4 Threads in CLJ Server
- [ ] check https://github.com/http-kit/http-kit

**Comment by nimaai** [comment]
`refresh-timeout` hook optimized: https://github.com/leihs/leihs/commit/b973097f3631f44adaf4a80eec8493919a592650

**Comment by nimaai** [comment]
concerted solution:

- **no automatic extension of the timeout** upon navigation
- **validation of the availability** of cart's reservations **only on cart load and only if expired** (during countdown the quantity is reserved for the user and cannot be snatched away by someone else)
- **validation of other criteria** in regards to start and end dates (e.g. holidays, max. amount of visits) **only on creating/updating a reservation or on submitting the order** (it's a less frequent case that something changes)

**Comment by neoheat** [comment]
Addition:
- the upcoming timeout (< 5 minutes before expiration), the basket icon gets a red flashing icon with the remaining minutes

**Comment by urs-van-binsbergen** [comment]
Blinking cart icon now integrated in the actual app:
https://github.com/leihs/leihs-borrow/commit/302b7009e99f0e02e9c584bc6fafea0e3ca529aa

**Comment by neoheat** [comment]
✅ Blinking cart icon is working and looking good on TEST.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/4b186d3dd5be7bef874d330328a06c5cd2e83002
