### ISSUE TITLE
Inventary export for `Ausleihe Toni` and entitlement group `DDK-FFI`

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1596]
@nimaai 

Could you please make another inventory export like https://github.com/leihs/leihs/issues/1576 for the DDK-FFI with an additional query statement `entitlement_groups.name = DDK - FFI` and the `inventory pool = Ausleihe Toni-Areal`.

---

Tabelle: **entitlement_groups**
| id                                   | name      | inventory_pool_id                    |
|--------------------------------------|-----------|--------------------------------------|
| 4647e9b8-316f-5cd4-937b-ab0a5ba83ceb | DDK - FFI | 8bd16d45-056d-5590-bc7f-12849f034351 |

**Comment by SeduroDotCom** [comment]
@nimaai Nachstehend befinden sich die Changes (`git apply Inventory.export.SQL.patch`)

[Inventory export SQL.patch](https://github.com/leihs/leihs/files/13111452/Inventory.export.SQL.patch)

**Comment by nimaai** [comment]
[ausleihe-toni_all-items.csv](https://github.com/leihs/leihs/files/13114004/ausleihe-toni_all-items.csv)
[ausleihe-toni_all-unretired-items.csv](https://github.com/leihs/leihs/files/13114005/ausleihe-toni_all-unretired-items.csv)
[ausleihe-toni_contracts-per-year.csv](https://github.com/leihs/leihs/files/13114006/ausleihe-toni_contracts-per-year.csv)

@neoheat

**Comment by neoheat** [comment]
danke. habs an FFI geschickt.
