### ISSUE TITLE
My: trim the value in login field from emtpy whitespace

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1602]
#### Expected behaviour
When a user enters the login field and adds accidentally a whitespace, all leading and trailing whitespaces should be removed by submitting the login form.

#### Actual behaviour
The whitespaces will be submitted by click on button `login`. This can lead to confusion for the user if the whitespace is not recognised.

![Image](https://github.com/leihs/leihs/assets/123965725/4761461f-a567-464e-8f6b-2545703ac864)

![Image](https://github.com/leihs/leihs/assets/123965725/d6403f54-0cf7-4bcd-a9ac-5f43a7b92223)

#### Steps to reproduce
- open https://leihs.zhdk.ch
- enter the login name with leading and/or trailing whitespace
- hit button `login`
- check if whitespace in following login screen appears

#### Specifications

Leihs version: 7.0.1
Browser version: any
MySQL/PostreSQL version: current

**Comment by belafonte** [comment]
https://github.com/leihs/leihs-my/commit/2ca1525a5132bfc161106b9f8c51e314a802e7b0
