### ISSUE TITLE
Inventory `Möbel- und Grossrequisitenfundus DDK ` category change needed by script

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1605]
The inventory pool `Möbel- und Grossrequisitenfundus DDK` (ID `561c02a0-e7e1-404b-aafe-c4d5d63da8a3 `) has all models in one category `Möbel NIHA`. Because no other categories are available, this might lead to confusion.

#### Task
- Change the category of all models in category `6849fe50-d5f8-440b-ab66-928729805e8b` (Möbel NIHA) to `82cbbf1c-09f4-5e6e-a599-5d2ac9086f9d ` (Möbel- und Grossrequisitenfundus DDK)

**Comment by SeduroDotCom** [comment]
Tabelle: **model_groups**
| id                                   | type     | name                                 |  |
|--------------------------------------|----------|--------------------------------------|---------|
| 6849fe50-d5f8-440b-ab66-928729805e8b | Category | Möbel NIHA                           | old |
| 82cbbf1c-09f4-5e6e-a599-5d2ac9086f9d | Category | Möbel- und Grossrequisitenfundus DDK | new |

<br/><br/>
ToAsk @nimaai 
- Es existieren Models.product - Einträge mit leading/trailing spaces, Cleanup-ticket nötig oder ist dies gewollt?
```sql
-- LOCAL-DEV-DATA
-- 51 entries
select * from models m where m.product like ' %'

-- 433 entries
select * from models m where m.product like '% '

-- 11'973
select count(*) from models

-- Liefert jeweils 2 Einträge
select * from models where product like '%Objektiv Nikon AF-S Nikkor 24-70mm f/2.8G (ED N)%';
select * from models where product like '%Arduino USB-Controller%';
```

**Comment by neoheat** [comment]
@SeduroDotCom Query sieht meines Erachtes korrekt aus. Bitte führe das doch einmal auf TEST aus.

**Comment by nimaai** [comment]
@neoheat done auf test

**Comment by neoheat** [comment]
@nimaai, @SeduroDotCom Passt. Bitte auf PROD ausführen.

**Comment by nimaai** [comment]
@neoheat done auf prod

**Comment by neoheat** [comment]
tested postitive

**Comment by nimaai** [comment]
https://github.com/zhdk/leihs-server-inventory/commit/e54470e97ce016b11f47b4bf0dd79f3be1897439
