### ISSUE TITLE
Procurement: missing mime types for js and css files

### ISSUE THREAD

**Issue by belafonte** [leihs/leihs#1611]
#### Expected behaviour or future wish
include mime type for js files in response header:

current quick fix in routes.clj

```
 wrap-accept
      ((fn [handler]
         (fn [request]
           (-> request
               handler
               (cond->
                 (-> request
                     :uri
                     (clojure.string/ends-with? "js"))
                 (assoc-in [:headers "Content-Type"] "application/javascript"))))))
```

#### Current behaviour
css and js files are served without mime type. This was not a problem previously, but is now because of js module strict mime type check.

#### Steps to reproduce
js files do not have a content-type in their response header

#### Specifications
- Leihs version: current
- Browser version: all
- MySQL/PostreSQL version: current

**Comment by nimaai** [comment]
https://github.com/leihs/leihs-procure/commit/ae65428f934ef1723f84227179c0d8fbbbf7e6fc

will be merged to master through the respective branch
