### ISSUE TITLE
borrow: no more images shown

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1613]
**Application**
borrow

**Describe the bug**
no more images are shown in the frontend, only when the browser has cached them already

**To Reproduce**
1. Login into borrow as a normal user
2. see if images are shown
3. maybe delete the browser cache first

**Expected behavior**
the images should be shown

**Screenshots**

![Image](https://github.com/leihs/leihs/assets/123965725/7017529a-bdff-429d-b85a-ec13b82a6476)

**Desktop (please complete the following information):**
- Device: Desktop &  Mobile
- OS & Version: any
- Browser & Version: all

**Additional context**

maybe because of https://github.com/leihs/leihs/issues/1597

**Comment by nimaai** [comment]
reproducible also on staging:
```
ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 45
  ```

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e2d0a6fa041ce9ab2a329e5b09be6b3abceb4840

**Comment by neoheat** [comment]
tested positive
