### ISSUE TITLE
clojure(-script) code formatting setup

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1625]
candidate tool: https://github.com/weavejester/cljfmt

requirements:
* should work on cider as well as on local machine
* should be able to use with git hooks
* additionally: should be able to integrate with code editors

linting functionality in code editors is optional.

**Comment by belafonte** [comment]
@nimaai why not using clojure-lsp? 
Also supports formatting and has other functionality too.
Also seems actively maintained.

https://clojure-lsp.io/features/#format-a-whole-file-or-range
https://github.com/clojure-lsp/clojure-lsp/

**Comment by DrTom** [comment]
So, Umsetzung am Beispiel der Madek API-V2

1. Clojure source formatting: add cljfmt command. https://github.com/Madek/madek-api-v2/commit/428a7ba03850b8550e79fb40af0f68a65d1fecc3
2. Clojure source formatting: enforce it on CI https://github.com/Madek/madek-api-v2/commit/3966d5fbbea2fa172748efe59fbf1f64e034db81
3. Clojure source formatting: reformat with cljfmt fix https://github.com/Madek/madek-api-v2/commit/e7befdbf88f160c18dbdce2da93cadfd13f2fccc

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7ad131cc1071ab55eb14438af33d1385e4a8793d

**Comment by nimaai** [comment]
borrow: https://github.com/leihs/leihs/commit/339ca1f6864e94fccb6166f8b457d04761b8ab45

**Comment by nimaai** [comment]
procure: https://github.com/leihs/leihs/commit/21e6ca85351b9616b04930d22f677369710dee02
