### ISSUE TITLE
Cleanup buildings and rooms

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1631]
### Task
Cleanup of buildings and rooms that are multiple times in the database.

### Task
- merge buildings with same building code 
- merge rooms with same room name AND same building ID
- other database tables (like items) that have relations to buildings and rooms must be changed accordingly

### Dependencies

This cleanup relates to bugfix https://github.com/leihs/leihs/issues/1568. This fix introduced a constraint check on building codes. The cleanup job to merge buildings and rooms must be executed **before** a new release to PROD.

### Attachment

[2023-12-07 Leihs cleanup Buildings and rooms.xlsx](https://github.com/leihs/leihs/files/13599719/2023-12-07.Leihs.cleanup.Buildings.and.rooms.xlsx)

**Comment by nimaai** [comment]
@neoheat do you know of any use case for the building code? because i haven't found any in the codebase...

**Comment by neoheat** [comment]
@nimaai no, not to my knowledge. Will ask Nadja.

**Comment by neoheat** [comment]
@nimaai so far, the code is probably not used by now. But we shouldn't delete it. Maybe we once need a short identification instead of a longer name.

**Comment by nimaai** [comment]
```
# Merge duplicate buildings with the following strategy:
# - Randomly keep one of the duplicate buildings (to_keep_building).
# - For the rest of the duplicate buildings do as follows:
# -- Go through a united list of all their rooms and do the following for each of them (to_delete_room):
# --- If the to_delete_room is a general one, move all its items and procurement_requests to the general_room of the to_keep_building (It can't be deleted on its own due to a constraint).
# --- Otherwise:
# ---- Find a room with the same name from the to_keep_building or create one if it doesn't exist (target_room).
# ---- Move the items and procurement_requests from the to_delete_room to the target_room.
# ---- Delete the to_delete_room.
# - Delete all the duplicate buildings except for the to_keep_building. This will also delete all their rooms including the general_room.
```
@neoheat this is the merge strategy. please double check

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6eb29b259f8e8d6b5e75dda88ce6b3573e52ffac

**Comment by neoheat** [comment]
@nimaai 
please check in attached excel in sheet "Räume korrigiert". There are several Rooms with same name and same building after executing the merge script
[2023-12-13.Leihs.cleanup.Buildings.and.rooms.xlsx](https://github.com/leihs/leihs/files/13658425/2023-12-13.Leihs.cleanup.Buildings.and.rooms.xlsx)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/66ed36c0648a98b69e7ef0834e58f659703bd6fe
