### ISSUE TITLE
Accessories checkboxes get unchecked

### ISSUE THREAD

**Issue by kleinphi666** [leihs/leihs#1634]
**Application**
Inventory > Edit Model

**Describe the bug**
While the model editing is open reloading or clicking on anything (even just 'save model') will uncheck the checkboxes.

**To Reproduce**
1. Go to an inventory pool.
2. Click on Inventory in the above line.
3. Click on a model which has checkboxes in the Accessories area.
4. Click on Edit Model.
5. If the checkboxes are checked just click on Save Model.
6. Open the model again and see the error in form of unchecked checkboxes.
7. If you need to click the checkboxes and then save the model they will be checked when you open the Edit Model dialogue again.  
(My guess would be something with the variable 'inventory_pool_toggle'.)

**Expected behavior**
When checking the boxes for existing accessories while adding a new model you want the checkboxes to be active until you uncheck them and not them being inactive everytime you e.g. change a description and click save. 

**Screenshots**
![before_saving](https://github.com/leihs/leihs/assets/122459759/b6715604-f627-42f5-8334-aa913b015bcb)
![after_saving](https://github.com/leihs/leihs/assets/122459759/e7cdb230-c0c5-4063-9544-4032a0c78607)

**Desktop (please complete the following information):**
- Device: Lenovo Thinkpad E14, Dell Lattitude 5340, iPad Air 5th Generation
- OS & Version: Ubuntu LTS 22.04.3 , Windows 11 22H2, iPadOS 17.2
- Browser & Version: Firefox 119.0.1, Microsoft Edge 120.0.2210.61, Safari 17.2

**Comment by sbaecker** [comment]
toggle_val contains if the accessory is checked or not.
Accessory gets deleted if it is checked and already set in the database.
Please find patch below.

--- /leihs/legacy/app/models/accessory.rb~      2024-03-20 07:20:10.000000000 +0000
+++ /leihs/legacy/app/models/accessory.rb       2024-03-22 12:48:19.039860883 +0000
@@ -25,7 +25,8 @@

     if toggle_val == '1' and not self.inventory_pool_ids.include?(ip_id)
       self.inventory_pools = self.inventory_pools + [ip]
-    else
+    end
+    if toggle_val == '0' and self.inventory_pool_ids.include?(ip_id)
       self.inventory_pools = self.inventory_pools - [ip]
     end
   end

**Comment by neoheat** [comment]
@nimaai could you please review

**Comment by nimaai** [comment]
merged to master: https://github.com/leihs/leihs/commit/7fd63682b556ac254587a3dbfd9d77f34f7dc011

will be part of the next release.

thanks @sbaecker @kleinphi666 !
