### ISSUE TITLE
Check issues without project assignment

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1637]
Please check these issues and mark them if still relevant, close them if they are no longer needed

**Comment by neoheat** [comment]
https://github.com/leihs/leihs/issues?q=is%3Aissue+is%3Aopen+no%3Aproject+author%3ADrTom

**Comment by nimaai** [comment]
I have gone through my list and that of Max too. The only issues remaining in Max's list should be considered by @DrTom .

**Comment by nimaai** [comment]
the remaining issues of max closed as per @DrTom request.
