### ISSUE TITLE
Admin: Remove Breadcrumps everywhere

### ISSUE THREAD

**Issue by belafonte** [leihs/leihs#1646]

**Comment by belafonte** [comment]
https://github.com/leihs/leihs/commit/8770b381849df43efc9a388a6bae7563a08c4fd0

**Comment by neoheat** [comment]
@belafonte As discussed, please remove the implemented logic in the breadcrumb that "merges" an already existing breadcrumb link with the same name. We are aware of the fact that a loop can occur if the user navigates deep into the structure
