### ISSUE TITLE
Procurement - New role "Viewer"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#165]
We need to seperate the role Inspector in two roles where one can only read and one can have the current inspector privileges.

- [x] New role called "Viewer / Betrachter"
- [x] The viewers are not displayed in the requests
- [x] The viewers only have reading priveleges
- [x] The viewer can see all requests
- [x] The viewer can access all filters
- [x] The viewer can export the request list

check ticket https://github.com/leihs/leihs/issues/539

**Comment by nadjaweisskopf** [comment]
first steps for Matus: 
- check if Procurement needs to be a standalone application
- check if pundit is necessary
- check if refactoring of request page is necessary
- think about testing the roles

**Comment by nimaai** [comment]
@nadjaweisskopf who gives this role to a user? procurement admin, right?

**Comment by nadjaweisskopf** [comment]
Should the viewer see only some categories or all?

**Comment by nadjaweisskopf** [comment]
@nimaai 

- [ ] The viewer should be created by the inspector and should only see the categories the inspector has access to.

- [ ] The viewer can see the requests during ALL phases

**Comment by nadjaweisskopf** [comment]
@nimaai @nimaai Role-file for procurement: smb://filer.ad.zhdk.ch/applications/Leihs/02_Anforderungen/Procurement/Rollen und Rechte Procurement.xlsx

Please can you check if the content is sufficiently described?

**Comment by nimaai** [comment]
@nadjaweisskopf Admin should be able to manage the viewers for a particular of category too, as he is allowed do anything else, right?

**Comment by nimaai** [comment]
@nadjaweisskopf Shall a viewer be in some form aware of the other viewers of the same category? Shall there be a page for this?

**Comment by nadjaweisskopf** [comment]
Test all field priveleges

**Comment by eins78** [comment]
2 open questions:

1. how should the Viewers be configured. Proposal: In Admin > Categories, like the Inspectors.

![screen shot 2018-07-18 at 17 01 19](https://user-images.githubusercontent.com/134942/42890195-7f2e2d40-8aac-11e8-8011-7fb1b5c3d404.png)

2. how can non-Admin users see the Category-Viewers? Idea: Could be a new Page, shows a simple list (like "Organisations of the requesters" in the Admin)
