### ISSUE TITLE
Import script for pool ITZ-Network

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1665]
## Tasks 

develop import script for new inventory pool **ITZ-Network** according to attached excel file. The columns are more or less the names of the database fields.

[Inventory ITZ network bereinigt.xlsx](https://github.com/leihs/leihs/files/14052910/Inventory.ITZ.network.bereinigt.xlsx)

**Comment by SeduroDotCom** [comment]
Dev-Setup in leihs/l
- Changes: https://github.com/leihs/leihs_legacy/compare/master...mr/model-items-import
- PR:
- Workflow
   1. Try to create models, if failures occur cache them
   2. Try to create, if failures occur cache them
   3. Validate error-result
      1. No errors _> commit transaction
      2. errors exist _> log error-count & log issues as json

CSV-Prerequisites & namings
- **model-import.csv**
  ```
  model,supplier,technical_detail,description
  LES1532A,Black Box,LES1532A,Serial Console Server
  ```
- **items-import.csv**
  ```
  note,serial_number,retired,is_broken,owner,inventory_pool,building,room,properties_installation_status,model
  APIC1,WZP23260T35,false,false,ITZ-Ausstellungen,ITZ-Ausstellungen,Toni-Areal (TONI),Unbekannter Raum,inStorage,APIC-SERVER-M3
  ```

![import-logs-with-and-without-failures](https://github.com/leihs/leihs/assets/32426621/c6e824fc-9500-4927-9f4d-e102040f8609)

![properties-mapping2](https://github.com/leihs/leihs/assets/32426621/cb8bbded-7755-44ee-83bc-5ff9ab10fb5d)

![model-mapping](https://github.com/leihs/leihs/assets/32426621/5590d443-9707-4141-89e0-2e55ac44f1a6)

Excel-Template (revision of header-titles)
[UI-DB-Mapping-v2.xls](https://github.com/leihs/leihs/files/14099998/UI-DB-Mapping-v2.xls)

**Comment by SeduroDotCom** [comment]
ToClarify:
The script currently sets a default text a la **"retired"for retired=true** ,
as there is no **retired(bool)** but only **retired(date) & retired_reason(var)**

![2024-02-01 at 15 29](https://github.com/leihs/leihs/assets/32426621/ccf6dd39-2f17-43c6-94fa-51840f8921bf)

**Comment by SeduroDotCom** [comment]
FYI: @neoheat @nimaai Waiting for script-enhancement to support multiple csv's: 
- https://github.com/leihs/leihs_deploy/issues/26
