### ISSUE TITLE
make personal test servers accessible from outside or behind vpn

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1666]
Je ein Dev Server pro Entwickler:  `https://tom.leihs.rubydev.zhdk.ch/`, `https://tom.madek.rubydev.zhdk.ch/`, ....

TODOs Leihs: 
✅  Support Debian 12 https://github.com/leihs/leihs/issues/1704
✅  Fix Maintenance Page 
✅  Basic Auth https://github.com/leihs/leihs/issues/1707 (weitgehend erledigt)
✅  Rework Leihs internal reverse-proxy setup
✅   Upgrade, Rework, Fix Ansible Deploy (bis auf gelegentliche Ansible Warnungen erledigt)
✅   Transition from  `git-crypt` to `transcrypt`
✅   Inventory (neue Grundstruktur für Dev Server erledigt, Rest zusammen mit CI Setup)
✅  CI Setup

Zu überlegen: Es gibt ein neuen Reverse-Proxy für prod|staging|test; kommt das Setup gleich mit hier rein? 

TODOs Madek: 
☑ Rework Madek  internal reverse-proxy setup
☑ Upgrade, Rework, Fix Ansible Deploy
☑ Setup Maintenance Page
☑ Inventory
☑ CI Setup

**Comment by neoheat** [comment]
to Roman about the setup, he recommends

- setup a new gateway with HAProxy for ruby servers
- configure basic authentication on servers
- adapt deploy scripts for private test servers

Ticket for Roman is created

**Comment by DrTom** [comment]
https://github.com/leihs/leihs/issues/1754
