### ISSUE TITLE
New manage: explore frontend technologies via prototype app

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1671]
### Goal

Explore frontend technologies for the new app `new manage` according to article
https://medium.com/@nnnsadeh/how-to-integrate-tailwind-into-your-react-native-clojurescript-expo-app-61bf97afd6b9

Technologies:
- React Native
- Expo
- NativeWind (Tailwind)
- Reagent

 
Write down experiences, pro's and con's for the technologies and present to the team in planning event.

**Comment by neoheat** [comment]
- [ ] Analyse issue reagent vs react (keyboard entries)

**Comment by urs-van-binsbergen** [comment]
Zum anschauen gemäss heutiger Besprechung:
- Doppel-Reload bei Änderung eines CLJS-Files
- Evtl. index.js in .gitignore? Verschieben nach public/? Evtl. aussagekräftiger Name wie “externals.js”?
- Error-Handling bei Mutationen implementieren
- Filestruktur Client vs. Server (vs. Common) überlegen -> mein Task: ich machen einen Versuchs-Branch mit Unterordner als “Root”

**Comment by belafonte** [comment]
App angepasst siehe:

https://github.com/belafonte/shadowcljs-vite/commit/2e19c96bd68d0ab3a8da8d50a8c626032e48174a
https://github.com/belafonte/shadowcljs-vite/commit/bcb1ed190238a8258764ab653ddf7dcb027f9cb1
https://github.com/belafonte/shadowcljs-vite/commit/e3fab486ba9bea689e13a25a40da994d23f18422
