### ISSUE TITLE
E-Mail-Authentication

### ISSUE THREAD

**Issue by eiclu** [leihs/leihs#1693]
In the [Leihs Wiki](https://github.com/leihs/leihs/wiki/authentication) there is a mention of "e-mail authentication" as an internal authentication method, but I cannot seem to find a reference to that anywhere else in the Wiki. Is this authentication method available in Leihs?

**Comment by DrTom** [comment]
Pure E-Mail authentication was considered but never implemented.  We need to update the documentation. 

There is a somewhat cumbersome workaround: users can reset (and initially set up)  their password via E-Mail. To this end the account must have the settings `account_enabled` and `password_sign_in_enabled` set to true and of course the `email` property must be set properly.
