### ISSUE TITLE
Statistics not accessible

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#170]
URL: http://leihs-v4-test.zhdk.ch/admin/statistics

How to reproduce:
1. Go to admin section/statistics
2. Access any statistic but the first one
3. an error is shown "We're sorry, but something went wrong..."

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/89e89e10a3b4bff4924db299f1f3168eb4ff5770

https://github.com/leihs/leihs_legacy/commit/059d959f4cf1ad5618633c85aba6c62dd229ee27

**Comment by nadjaweisskopf** [comment]
All statistics open and are readable. 

The statistics nr. 1, nr. 4 and nr. 6 don't show the user name.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/4a0706b984e050da92ef9430ab136d6d3943efd3
https://github.com/leihs/leihs_legacy/commit/2948c65d04ca8767d25c81190e32067a4df76f54

I fixed the user name, but only for 1. The other statistics' sections do not involve the display of user's name. I compared it to production (btw 3. is broken there).

As a note: Our statistics scenarios seem to be outdated; they are all marked as `@upcoming`:  https://github.com/leihs/leihs_legacy/blob/master/engines/leihs_admin/features/statistik.feature#L26-L61

**Comment by nadjaweisskopf** [comment]
Nr. 1 and nr. 4 are ok. Nr. 6 shows the users but still without the name. In Production this works. 
![statistics](https://cloud.githubusercontent.com/assets/3356016/23461711/4ee82e64-fe8b-11e6-95ca-2427355c36be.png)

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/cae3094bbb4ba066051a0597a462c1d2ee958cd9
https://github.com/leihs/leihs_legacy/commit/71c7a95ed6b7710d2a3d3609f6fe09bb333fa6cf
