### ISSUE TITLE
Borrow: Optimize Filters

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1700]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

From the New Borrow user survey among the students, one conclusion was that the filter function – which is currently placed in the search field – is not recognised as this.

## **Describe the solution you'd like**

- Remove the filter button in search bar
- split the filter option:
  - filter in inventory parks (dropdown - only visible, when more then one Park available)
  - fiter for availability date (modal window as current solution)

![Image](https://github.com/leihs/leihs/assets/123965725/66c458f8-d1ce-45f1-bb60-68ceb9dbd6d9)
![Image](https://github.com/leihs/leihs/assets/123965725/9e4c38fc-1882-47c6-b967-539e0639091c)
![Image](https://github.com/leihs/leihs/assets/123965725/9cfa17cf-7009-400f-ac49-cb468de0287c)
![Image](https://github.com/leihs/leihs/assets/123965725/a9a8d574-9406-4b55-9774-24c036bf6fe6)

**Comment by urs-van-binsbergen** [comment]
Opportunistic fix: ESLint was under-configured. Had only "prettier/prettier" (formatting issues), but no functional issue detection. Added "eslint:recommended" and "plugin:react/recommended". Fixed some issues found by ESLint.

**Comment by urs-van-binsbergen** [comment]
a35a2a37d206195e5cc373380dcb611eb8f43af1

**Comment by neoheat** [comment]
Small design Issue: left dropdown has no rounded corners

![Image](https://github.com/leihs/leihs/assets/123965725/6faf3267-d464-4060-8806-6a721bbd9cfb)

**Comment by urs-van-binsbergen** [comment]
d64387d4f6559c06a6228b5c7cd2266cb6a95318

**Comment by neoheat** [comment]
tested positive
