### ISSUE TITLE
Borrow: Item with availability 1 can be reserved several times

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1708]
**Application**
borrow

**Describe the bug**
A item can be booked multiple times if it is already in an expired shopping cart and an overlapping period is selected. 

**To Reproduce**
1. Search for a model which has an available amount of 1 item (e.g. 59c8d2b0-3717-5317-ba1d-de09206c42d2)
2. Make a reservation for this item by adding it to the basket, choose a date range (2 days, Wednesday–Thurday)
3. Wait until the basket expires (30')
4. Search for the same model as before and add this model to the basket, choose a date range in the same week as before, but from Monday-Friday (time range must be overlapping, but not exactly the same)
5. Submit the basket

Result: 2 reservations in 2 orders of an item which is only available once

**Expected behavior**
If there are models in an expired shopping cart, the shopping cart should be reactivated and thus validated when a new model is added (by clicking on Add item or Repeat order).

**Comment by nimaai** [comment]
the overbooked reservations are marked invalid in the cart now and the order can't be submitted

https://github.com/leihs/leihs/commit/9859340ad384d529974bdc19aa614865daa08941

**Comment by neoheat** [comment]
tested positive
