### ISSUE TITLE
Adding a model to an order does not work

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#172]
http://leihs-v4-test.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/contracts/submitted_3d677c34-3cde-523f-8e07-a3cd6faeafac_8bd16d45-056d-5590-bc7f-12849f034351_2017-02-20/edit

How to reproduce: 
1. go to lending section
2. open an order
3. add a model
4. model is not added

**Comment by nadjaweisskopf** [comment]
Same for templates in reservation

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/2495aa84bc439f07ba991debdfc9dce3c1cd9238

**Comment by nadjaweisskopf** [comment]
test ok
