### ISSUE TITLE
Admin: Audit - optimize links / search of requests

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1720]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

a) In order to find the audit requests of a specific user, the administrator must first determine the user's UID and use this information to search for the corresponding request.

b) the administrator should be able to search for the `TX ID` and `HTTP-UID` in the Audited Requests

## **Describe the solution you'd like**

a) Add a link from the user detail page to the audited requests. In the link, the url parameter `user-uid` with the user's UID is passed
![Image](https://github.com/leihs/leihs/assets/123965725/e5119151-c2a4-487e-8dbd-207063f943de)

b) Add two new search fields `TX ID` and `HTTP-UID` on `admin/audited/requests/ `

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/0b8bb81f4dd3ddd2e17a714be8ce356160021cc0

**Comment by neoheat** [comment]
tested 👍
