### ISSUE TITLE
Upgrade Ruby 3.2

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1721]

**Comment by nimaai** [comment]
https://github.com/Compass/compass-rails makes problems after upgrade. the gem is end of life. it needs to be analyzed how it can be replaced something else.

**Comment by urs-van-binsbergen** [comment]
Substituted `compass-rails`: 

https://github.com/leihs/leihs_legacy/commit/49e6e4e0adb65689364c5bbc5a3ffbf572d6c47b

However there are other problems coming with the Ruby Update: 

https://ci.zhdk.ch/cider-ci/trees/3b58a3ca62c24a910d50ce27bfa9373012faa00e

app/models/entitlement.rb:22 

ArgumentError: wrong number of arguments (given 1, expected 0)

Reproduce: Open "Bestellungen", it will say "Verfügbarkeit wird geladen" forever.

**Comment by urs-van-binsbergen** [comment]
@nimaai please take over

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/2acdee25e2ed30c13ff4834bc17396032b92da68
