### ISSUE TITLE
Database: sorting of strings different in local and official test servers

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1728]
**Application**
admin

**Describe the bug**
On the personal development servers, the database uses the locals from the underlaying OS. This causes a different sorting (visible in the list view of admin/inventory pools) as in the official test or productive servers.

On the personal development servers, the data entries beginning with capital letters are higher prio and therfore listed before lower case.

Example 

**To Reproduce**
> Steps to reproduce the behavior:
1. Login into personal test server
2. go to inventory pools list view
3. check sorting (example: `AV-Services` is sorted before `Ausleihe Toni-Areal`)
4. Login in offical test server
5. go to inventory pools list view
6. check sorting (example: `Ausleihe Toni-Areal` is sorted before `AV-Services`) -> which is correct
7. compare the two sortings

**Expected behavior**
The sorting should be as in the official test servers. The sorting should not favour capitalised letters.

**Screenshots**
![Image](https://github.com/leihs/leihs/assets/123965725/133efa44-faec-4106-a825-6ee06af64925)
![Image](https://github.com/leihs/leihs/assets/123965725/cc141a3c-6a43-4671-80ec-57190cb19822)

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Comment by DrTom** [comment]
<img width="1881" alt="Screenshot 2024-08-21 at 10 19 52" src="https://github.com/user-attachments/assets/d2b0f6e2-af97-4053-9dec-bebd650e9701">

**Comment by neoheat** [comment]
changed in ansible setup
