### ISSUE TITLE
Managing a users API-Tokens is no longer possible since the link has been removed from the admin app

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#1729]
The users section in the Admin-App contained a link to the users `my` page. 

The users `my` page contains two features 

* password reset (this feature has been rebuild in the admin app and is no longer required), and
* users token management. 

The latter is now not accessible anymore.

There are two at least ways to fix this: 

* (fairly quick) add a link from the users page in admin to `/my/user/{{USER-ID}}/api-tokens/`
* (more effort but also more consistent) rebuild the feature in the admin app

**Comment by neoheat** [comment]
we'll rebuild the function to manage token inside `admin`. The function should be in the user detail placed in a new tab `tokens`. the new tab should only be accessible by "me" (the actually logged in user)

**Comment by urs-van-binsbergen** [comment]
1bd4b22691e727efb953b2fe40b72d51b463628c
