### ISSUE TITLE
Timeline does not show

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#173]
http://leihs-v4-test.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/inventory?filters=reset

How to reproduce:
1. Open Inventory
2. Access the model list
3. Open timeline on model line
4. timeline is not shown

Timeline is accessible from several places - it is not shown anywhere.

**Comment by DrTom** [comment]
Wir muessen das morgen zusammen anschauen. Ich weiss gar nicht wie das ausschauen soll. Ich sehe keinen Fehler wenn ich den request anschaue. Das muesste aber sein falls wir ein problem mit den Assets haben. Ich habe geschaute wo das `simile_timeline` js included wird. Aber nur eine stelle gefunden ... 😕

**Comment by nadjaweisskopf** [comment]
test ok
