### ISSUE TITLE
admin: (new GUI) Group relation is not displayed in user detail

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1734]
**Application**
admin (new GUI)

**Describe the bug**
In the user detail page in `admin`, the group relation is not displayed, when selecting the tab `group`

**To Reproduce**
> Steps to reproduce the behavior:
1. Login into test.leihs.zhdk.ch as an administrator
2. search for a user
3. select tab `groups`
4. message `No (more) groups found.` appear
5. ---> compare to old admin GUI (staging or prod system). The groups are displayed in a table

**Expected behavior**
the group relation data table should be shown in tab `groups`

**Screenshots**
![Image](https://github.com/leihs/leihs/assets/123965725/6f478b5f-6706-4162-a788-426c012e13ad)

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Additional context**
> Add any other context about the problem here.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/22c62e32c90ffdc1345c98998fed2e72a8feb425

**Comment by neoheat** [comment]
tested positive
