### ISSUE TITLE
Wrong Title in Edit Dialogs

### ISSUE THREAD

**Issue by belafonte** [leihs/leihs#1736]
Should be Edit Field, not Edit Room

<img width="1324" alt="image" src="https://github.com/leihs/leihs/assets/2737673/0302a236-ec5b-43fa-aa75-db9a563a567c">

Should be Edit System and Security Settings

<img width="1324" alt="image" src="https://github.com/leihs/leihs/assets/2737673/bad2002a-19c3-451b-89c6-991f5f83168f">

**Comment by neoheat** [comment]
tested 👍
