### ISSUE TITLE
In the Wiki page, it would be nice to have a heading for Installation, and a link to the leihs-instance repo

### ISSUE THREAD

**Issue by GreyGnome** [leihs/leihs#1738]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* I needed to use AI to figure out where your install instructions are.

---

## **Describe the solution you'd like**

* A link from the leihs wiki.

---

## **Describe alternatives you've considered**

* I went to Gemini and asked it.

---

### **Additional context**

* No further information, Your Honor.

**Comment by neoheat** [comment]
there is no specific installation documentation, please read

- https://github.com/leihs/leihs_deploy
- https://github.com/leihs/leihs_zhdk-inventory
