### ISSUE TITLE
contractnr. is shown as UUID but should be a shorter id

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#174]
- For communication reason with students and between employees the long UUID is not user friendly. It needs to be shortened. 
- The old IDs need to be kept for legal reasons.

![vertragsnummer_uuid_2](https://cloud.githubusercontent.com/assets/3356016/23127479/7ff3bcec-f77b-11e6-89c8-fe5fb57d94d2.png)
![vertragsnummer_uuid_3](https://cloud.githubusercontent.com/assets/3356016/23127482/800c75f2-f77b-11e6-8c2a-f3ecfd221489.png)
![vertragsnummer_uuid](https://cloud.githubusercontent.com/assets/3356016/23127481/800a24d2-f77b-11e6-93fa-31adbc4c008c.png)
![vertragsnummer_uuid_4](https://cloud.githubusercontent.com/assets/3356016/23127480/80067986-f77b-11e6-97c1-326e711cae72.png)

**Comment by nadjaweisskopf** [comment]
Following sites still have the long UUID:

**contracts/--> tabs all/open/closed**
https://test.leihs-v4.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/contracts?status[]=signed&status[]=closed

**when searching for a user which has a contract:**
https://test.leihs-v4.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/search?search_term=honegger

**Inside the tab "contracts" when searching for a user:**
https://test.leihs-v4.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/search/contracts?search_term=honegger

**searching for a contract id does not show any results, for example:**
- conract id 143883 should show "Daniel Barnbeck"
https://ausleihe.zhdk.ch/manage/169/search?search_term=143883 (search from production)

**Button "change entry" in Take back shows UUID:**
https://test.leihs-v4.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users/f23ca963-a2d5-59db-bef8-9998ba40520d/take_back

**Button "Contract" when take back has completed shows UUID**
- see printscreen
![take back](https://cloud.githubusercontent.com/assets/3356016/23406717/b47cc13e-fdc0-11e6-9fd4-37160d43d5a3.png)


Old contract IDs have been stored succssfully.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/0545314498fdca36c9ff5f7469f34e21c1721e63
https://github.com/leihs/leihs/commit/9d488706fd27628c385e2b2efbed9784b145f1d5

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/33423824e0e843a1fce7dc113b721ef2ff287972

Barcode shortened according to contract's `compact_id`.
