### ISSUE TITLE
admin: the detail view of custom fields can't be displayed

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1741]
**Application**
admin

**Describe the bug**
The detail view of a field with "umlaute" charcters can't be displayed

**To Reproduce**
1. Go to 'https://test.leihs.zhdk.ch/admin/inventory-fields/'
2. Choose the custom field `[properties_Ampère]` (https://test.leihs.zhdk.ch/admin/inventory-fields/properties_Amp%C3%A8re)
3. see error

**Expected behavior**
A detail view of a field can be opened despite an "Umlaut" in the name

**Screenshots**
![Image](https://github.com/leihs/leihs/assets/123965725/78e0e27e-704f-4afe-a986-96e40d460c18)

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Comment by neoheat** [comment]
suppress entering accents in GUI. Maybe url-encode the url

**Comment by belafonte** [comment]
dynamic route params should not have non ascii characters.
should potentially be prevented by db constraint @nimaai

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f2022596165c395ec42c7912e8206dc31bd024e9

**Comment by neoheat** [comment]
tested 👍
