### ISSUE TITLE
Admin: set default state of new inventory fields to `disabled`

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1744]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
When a new inventory field is created, the field is `enabled` in all inventory pools

## **Describe the solution you'd like**
Set the status of a new inventory field to `disabled` in all inventory pools

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d345b0b10ee067074eaa7358a13ac1240202024a
