### ISSUE TITLE
admin: (new GUI) creating a delegation in an inventory pool without flag `pool_protected` fails

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1745]
**Application**
admin (new GUI)

**Describe the bug**
creating a delegation in an inventory pool without flag `pool_protected` fails

**To Reproduce**
1. Go to an inventory pool in admin
2. select tab "Delegations"
3. click button "Add Delegation"
4. Enter a name, select a responsible user and deactivate the checkbox `Protected`
5. Click "Add"

strange is, that this error only appears occasionally. A few minutes later I could create an other delegation with the same settings without any issues.

**Expected behavior**
A new delegation with deactivated field  `Protected` = false can be created

**Screenshots**
![Image](https://github.com/leihs/leihs/assets/123965725/c3a5168e-7358-4c16-910d-2bac0115e711)

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Comment by belafonte** [comment]
cannot reproduce. 
Maybe an auth issue?

**Comment by neoheat** [comment]
@belafonte not that i know of. I still can reproduce it, but not everytime. that's the strange thing.
Could it have something to do with this issue? https://github.com/leihs/leihs/issues/1746

**Comment by neoheat** [comment]
issue not reproducable anymore
