### ISSUE TITLE
Cleanup: item of FUNDUS inventory pool in wrong room

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1747]
### Description

In FUNDUS inventory pool, over 4000 items have the wrong room appointed. 

### Task

According to attached excel file, change the room of the items

[Fundus-Inventar-Korrektur.csv](https://github.com/user-attachments/files/15953129/Fundus-Inventar-Korrektur.csv)

**Comment by nimaai** [comment]
done on staging. @neoheat please check

**Comment by neoheat** [comment]
looks good, please execute script on PROD

**Comment by nimaai** [comment]
done 

https://github.com/zhdk/leihs-server-inventory/commit/032b0872d8081af883e0a8bd72328172395dae88
