### ISSUE TITLE
Opening a category in borrow section takes very long

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#175]
http://leihs-v4-test.zhdk.ch/borrow

How to reproduce: 
1. Go to borrow section
2. chose a category
3. It takes up to 10 seconds or more to show the models of this category

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/4ac41bbafbcc34446cf7708cd839aab2efffff39
https://github.com/leihs/leihs_legacy/commit/02fbe772382d2848ffc345194b96365876a64dae

**Comment by nadjaweisskopf** [comment]
I could not see a difference in the behaviour, opening "Audio" still takes about 4 seconds longer than in production.
