### ISSUE TITLE
New Inventory: Setup OpenAPI v3

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1752]

**Comment by urs-van-binsbergen** [comment]
Note that I introduced a demo endpoint `leihs.inventory.backend.resources.models.main` already. This is for testing purposes only, and can be removed of course after the "real" endpoint is in place.

**Comment by SeduroDotCom** [comment]
- [x] Implementation supports swagger & openapi
- [x] PR https://github.com/leihs/leihs-inventory/pull/1



![Image](https://github.com/user-attachments/assets/b3a8f163-971e-4cf7-bca1-06368e6ae860)

**Comment by SeduroDotCom** [comment]
![Image](https://github.com/user-attachments/assets/a2aab67f-20c3-4177-b7fe-c2d999c11ca4)
