### ISSUE TITLE
Search in modellist overview in category is case sentitive

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#176]
inventory, model list: http://leihs-v4-test.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/inventory?filters=reset

borrow section, model list: http://leihs-v4-test.zhdk.ch/borrow/models?_bc[]=78920f6d-57c1-5231-b0c4-f58dcddc64cf&category_id=78920f6d-57c1-5231-b0c4-f58dcddc64cf

How to reproduce: 
1. Go to borrow section
2. enter a category
3. enter a model name with lower case letters
4. the model is not found
5. write the model again chosing lower and upper case letters
6. the model is found

Same behaviour in inventory/modellist.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/76043c7d0dbbe27f037c5b31e662dce2df026bbb

**Comment by nadjaweisskopf** [comment]
test ok
