### ISSUE TITLE
Inventory: loading the category tree fails

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1761]
**Application**
manage

**Describe the bug**
the list of categories in "inventory" does not load. A infinite loading spinner is visible.
The network analysis shows a 304 redirect on https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/categories?include%5Bused%3F%5D=true, follow by a 404 on https://test.leihs.zhdk.ch/category_links

**To Reproduce**
1. Login as role "admin" in https://test.leihs.zhdk.ch/
2. change to inventory "Ausleihe Toni-Areal"
3. select "inventory"
4. click on tab "categories

**Expected behavior**
the list of catagories is loading

**Screenshots**

![Image](https://github.com/user-attachments/assets/144103ac-bf49-49d9-be73-8d7682490124)

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Comment by neoheat** [comment]
maybe an issue from ruby update  https://github.com/leihs/leihs/issues/1721

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ebbfb66bb2bf5486f0579d60ff03aa08804a39c9
