### ISSUE TITLE
Leihs 7.6.0: Missing Build Artefacts

### ISSUE THREAD

**Issue by mritzmann** [leihs/leihs#1763]
**Application**

Overall.

**Describe the bug**

Build Artefacts are missing for the 7.6.0 release, see:

https://github.com/leihs/leihs/releases/tag/7.6.0

For this reason, the update will fail unless you have installed all dependencies so that a local build is possible.

**Expected behaviour**

Build artefacts should be available as described here: 

https://github.com/leihs/leihs-instance/blob/master/GUIDE.md#build-cache

**Comment by nimaai** [comment]
the build artifact are no more necessary starting from `7.6.0`. the deployment recipes which are part of this release have been adjusted accordingly.

do you still need build artifact? if yes, why?

**Comment by mritzmann** [comment]
Hhm, maybe I made the wrong assumptions then. I updated git and then executed `./scripts/deploy`. First, the script stopped because `asdf` was missing. I then installed `asdf` and ran the script again, whereupon the script stopped because `clojure` was missing. I then installed `clojure`. Then the script stopped with `caniuse-lite is outdated` ...

I found it a bit strange that all this was not necessary before (I have been updating this way for a few releases) and then came across the missing build artefacts. I then assumed that the dependencies previously were not necessary because a build cache was available. Does version 7.6.0 have more dependencies that are not automatically installed by Ansible?

**Comment by DrTom** [comment]
You will need the `asdf-vm` installed on the control machine; everything else should be handled automatically. The README in https://github.com/leihs/leihs_deploy has more details. The `clojure` thing was a bug and is fixed with the 7.7.0 release.
