### ISSUE TITLE
New Inventory: integrate frontend app (according to existing prototype)

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1766]

**Comment by urs-van-binsbergen** [comment]
Some hints @belafonte 
- Source within namespace `leihs.inventory.client`
- Ignore `common.routes.cljc` for now
- Integrate into the deps system as already present. Alias `:frontend`, with `:deps` (meaning backend deps are ignored). No additional `dev` Alias ("-A:dev") (except there is compelling reason for it)
- Prettier Rules consistent with other apps: WITH `semi: false`, NO `singleQuote: false` (or discuss 😉)
- ESLint Config as you prefer (take over from prototype). Might be subject to later finetuning. Not too many, not too few. 
- React Router with data defined routes
- Please keep the "inventory/debug" route (but the reitit and js integ stuff in `debug/index.cljs` can be removed)

**Comment by neoheat** [comment]
https://github.com/leihs/leihs/issues/1780
https://github.com/leihs/leihs/issues/1781

**Comment by belafonte** [comment]
https://github.com/leihs/leihs-inventory/commit/36bdd5327c900f7dd658afa713d7b34088401f25
