### ISSUE TITLE
tab supplier in manage section shows error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#177]
http://leihs-v4-test.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/suppliers

How to reproduce:
1. Go to manage section in inventory pool
2. Access tab "suppliers"
3. Error is shown

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/dceb4f760c5bdde38a46d220791920136b76d683

**Comment by nadjaweisskopf** [comment]
test ok
