### ISSUE TITLE
Set the max. lending time per pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1783]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
Each pool has different requirements of the max. lending time. Depending on holidays, amount of lending mgr. available, amount of concurrent student projects or amount of items, which are defect, the max. lending time can vary. 

Specific requirement: 
Before the summer holidays, which is the period when students are on holidays and not many reservations are created, the lending mgr. would like to set the max. lending time to "30 days" instead of f.e. "14 days". He would like to set the max. lending time from 1. August until 31. August. Beeing able to set the "from" and "until" date gives the lending mgr. the possibility to set the max. lending time before he himself goes on holidays.

---

## **Describe the solution you'd like**

-  When an instance is newly created, the standard max. lending time is either unlimited or set to a standard value of for example 30 days for all pools. 
- Each pool can set the standard max. lending time. 
- Each pool can set a deviating max. lending time for a specific time period. As soon as the time period is over, the standard max. lending time of the pool takes effect again. 
- The max. lending time has an impact on the calender in the borrow section. Depending on the pool which is selected in the calender, the max. lending time can vary. 

---

**Comment by neoheat** [comment]
this is already planned in https://github.com/leihs/leihs/issues/1701, but we'll discuss the point 3 in the list to overwrite the default setting in a certain time frame.

**Comment by nimaai** [comment]
@nadjaweisskopf @neoheat i am reframing the given example for myself in order to ensure that i understand it correctly.

given:
- the standard `maximum_reservation_time` of pool X is set to `14` days.
- the pool changes it to `30` days valid **only** in the timespan from `1st of August` until `31st of August`.
- when a student opens the booking calendar on `10th of August` then he can set the end date maximum `30` days in future.
- when a student opens the booking calendar on `1st of September` then he can set the end date maximum to `14` days in future.

correct?

**Comment by neoheat** [comment]
@nimaai sounds credible to me. But let's discuss the additional effort to implement the "overwrite" feature based on a certain timeframe.

**Comment by neoheat** [comment]
Feature with temporary change of the lending duration will be postponed, due to high efforts and impact on legacy code. But the individual lending durations per pool will be realized.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/3f7cf7d68e06ea65d68b7cebe11c094864df2abc

**Comment by neoheat** [comment]
Feature will be release with the next Release 7.9.x
