### ISSUE TITLE
New user for references

### ISSUE THREAD

**Issue by korwisi** [leihs/leihs#1784]
Dear leihs maintainers and developers,

we, the Mainz University of Applied Sciences ([Hochschule Mainz](https://www.hs-mainz.de/)), have been using leihs successfully for over a year now. You more than welcome to add us to your reference list.

Yours sincerely
Kristof Korwisi
Werkstattleiter Medientechnik

**Comment by neoheat** [comment]
Dear Kristof
We're happy to do so!
best regards, Lukas
