### ISSUE TITLE
build_artefact missing from 7.6.0 and above

### ISSUE THREAD

**Issue by AnthonyHunt-UoW** [leihs/leihs#1785]
Unable to './scripts/deploy' as build_artefact is missing from release. Unable to manually compile as no instructions in how to do so.

curl: (22) The requested URL returned error: 404 
++ echo 'ERROR: Could not download build artefacts for LEIHS_VERSION='\''7.6.0'\'''
ERROR: Could not download build artefacts for LEIHS_VERSION='7.6.0'
++ exit 1

**Comment by neoheat** [comment]
Hi @AnthonyHunt-UoW 
Please see issue https://github.com/leihs/leihs/issues/1763
Best, Lukas

**Comment by AnthonyHunt-UoW** [comment]
the deploy script still fails though. How do we get around the script trying to download the build artefacts?

**Comment by DrTom** [comment]
OK, there were some outdated documents or document fragments around. I cleaned that up.
