### ISSUE TITLE
Filter menu should be left aligned

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#179]
http://leihs-v4-test.zhdk.ch/procurement/requests/overview

Filter menu on the left hand side should be left aligned.

**Comment by eins78** [comment]
Sehr lustig: diese server-seitige Fehlermeldung bringt auch global styles mit 😂 
`body { text-align: center; }`

Könnt ihr ignorieren, geht von alleine weg wenn die Bug gefixed wird. 
Alternativ: fight fire with fire: `html body {text-align: initial !important}` im CSS oder als inline style im template.

**Comment by nimaai** [comment]
fixed by https://github.com/leihs/leihs/issues/180

**Comment by nadjaweisskopf** [comment]
I can not access procurement, I get an error "We're sorry, but something..."

**Comment by nadjaweisskopf** [comment]
test ok

**Comment by nadjaweisskopf** [comment]
test ok
