### ISSUE TITLE
Legacy "Show User" and Inventory Pool User Page blank

### ISSUE THREAD

**Issue by AnthonyHunt-UoW** [leihs/leihs#1792]
After updating to 7.0.0 we find the "Show User" page returns a blank screen. 

The url is /admin/inventory-pools/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.

The page navigation appears to render momentarily before being replaced with a blank screen.

Same is happening in all 4 instances of LEIHS.

**Comment by neoheat** [comment]
Hi @AnthonyHunt-UoW 
Are you really using 7.0.0? This is not the latest version. There was once a bug with the user detail page, but was fixed in a later version. 

Latest version is 7.7.0. https://github.com/leihs/leihs/releases/tag/7.7.0

**Comment by AnthonyHunt-UoW** [comment]
Sorry, that was a typo. We are on 7.7.0






Anthony Hunt

Senior Technical Coordinator - Digital Arts Centre

✉️ ***@***.******@***.***>  | 📞  01905 855320<tel:01905855320> | EE1086 Edward Elgar | ∞ LinkedIn<https://www.linkedin.com/in/anthony-hunt-95565836/>

Microsoft ***@***.***>



University of Worcester | Henwick Grove | Worcester | WR2 6AJ



Get status updates on current support issues at -

Facebook<http://www.facebook.com/DigitalArtsCentre> | Twitter<https://twitter.com/Worc_DAC>  | Sharepoint<https://uniworcac.sharepoint.com/teams/DigitalArtsCentre>



For further information about opportunities to study at the University of Worcester please visit our website<https://www.worcester.ac.uk/>



This email and any files attached are confidential and intended solely for the addressee. If you have received this email in error please notify the sender immediately and destroy all copies. Any views or opinions expressed in this email or attached files are solely those of the individual and not necessarily those of the company. The recipient should check this email and any attachments for the viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

________________________________
From: Lukas Brupbacher ***@***.***>
Sent: Monday, September 16, 2024 9:06:20 AM
To: leihs/leihs ***@***.***>
Cc: Anthony Hunt ***@***.***>; Mention ***@***.***>
Subject: [External] - Re: [leihs/leihs] Legacy "Show User" and Inventory Pool User Page blank (Issue #1792)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi @AnthonyHunt-UoW<https://github.com/AnthonyHunt-UoW>
Are you really using 7.0.0? This is not the latest version. There was once a bug with the user detail page, but was fixed in a later version.

Latest version is 7.7.0. https://github.com/leihs/leihs/releases/tag/7.7.0

**Comment by belafonte** [comment]
I just checked FF, Chrome and Safari and wasn't able to reproduce the issue.
Could you elaborate a bit on the circumstances? 

The following would be interesting:

- Browser + version.
- Mobile / Desktop?
- Are there any errors in the console? ( Screenshot )
- Does it also happen when all browser plugins are disabled, such as in Chrome's incognito mode?
- Does it happen to all users, or only to this one?
- Does it also happen to the same user regardless of the inventory pool? -> /admin/users/:user-id instead of  /admin/inventory-pools/:pool-id/users/:user-id

**Comment by AnthonyHunt-UoW** [comment]
Yes. Seems to be affecting all four instances here. Same result on Chrome and Safari in both normal and incognito mode, internally and externally.

Seems to be happening with all users. Nothing written to console but not been able to check the leihs.log yet. 

This only happens inside on an inventory pool. I'll try and research some more today. At first I thought it might be an index? We were populating Extended_Info via script until the update to 7.6.0. This might have run on the overnight? but surely it would have been disregarded by the API?

**Comment by AnthonyHunt-UoW** [comment]
This is what was written to apache.log... sanitized

10.101.91.2 - - [16/Sep/2024:10:45:02 +0100] "GET /admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab HTTP/1.1" 200 2318 "https://uw-leihs/admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "Zuf-Htoi31jxyOA_NsoRbwAAAIE" 4821fb47b0
10.101.91.2 - - [16/Sep/2024:10:45:02 +0100] "GET /admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e HTTP/1.1" 200 1378 "https://uw-leihs/admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "Zuf-Htoi31jxyOA_NsoRcAAAAJM" 4821fb47b0
10.101.91.2 - - [16/Sep/2024:10:45:02 +0100] "GET /admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e/roles HTTP/1.1" 200 89 "https://uw-leihs/admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "Zuf-Htoi31jxyOA_NsoRbgAAAJA" 4821fb47b0
10.101.91.2 - - [16/Sep/2024:10:45:02 +0100] "GET /admin/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e HTTP/1.1" 200 1261 "https://uw-leihs/admin/inventory-pools/040f275a-cbc2-5c21-9e98-8613fde1ccab/users/88dee3c2-1d9b-42f6-adde-849b2c173e5e" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "Zuf-Htoi31jxyOA_NsoRcQAAAI8" 4821fb47b0

**Comment by belafonte** [comment]
We indeed removed the functionality to edit the extended Info in the ui and are actually planning to remove it entirely.
The main reason for extended info was to store some authentication information that can now be added to predefined fields.

What kind of info is the script writing to extended_info?

I might have found an issue related to this and will check if i can fix it.

**Comment by AnthonyHunt-UoW** [comment]
It was writing tuples of info that we couldn't access outside of leihs, such as student module lists, dates they started etc. I We have decided that if we can no longer support the extended_info we'll have to do it another way.... So, we can hapily loose it now... but there might have been a rouge couple of nights where the script tried to write it.

**Comment by belafonte** [comment]
@AnthonyHunt-UoW could you please try with the latest Patch Release 7.7.1 if there is still an error with the user page.

**Comment by AnthonyHunt-UoW** [comment]
Yes that's working now. As I said, we have dropped the usage of the field now, but the existing old data is still in the DB and possible needs purging at some point.

**Comment by belafonte** [comment]
Ok great to hear!
I think the field will stick around for backwards compatibility for a while.

fixed: https://github.com/leihs/leihs-admin/commit/d110eeae816574f948a278e11429fbde186e523c
