### ISSUE TITLE
Add badge_id to JSON on "Users"

### ISSUE THREAD

**Issue by AnthonyHunt-UoW** [leihs/leihs#1793]
To aid programming functionality outside of LEIHS it would be useful to return badge_id from the admin/users api without having to return specific users.

For instance, we use a unique barcode or card number as well as a user id to identify accounts. If I want to access this barcode from a username search via the API I have to search first for the username, parse the JSON to get the account ID and then re-read the individual account ID. 

Does this make sense?

**Comment by DrTom** [comment]
Let me try to rephrase your question to ensure we understand each other correctly:

You would like to retrieve properties of an user account by its `badge_id`. The way to do this currently would be to retrieve all users and then filter within your client.

I guess we could add an query-parameter `badge_id` to the `/admin/users/` resource, like `/admin/users/?badge_id=12345ABC`. This will always return a list of users (there is no unique constraint in the database on `badge_id`). However if your `badge_id`s are unique the list will contain (at most) one account.

**Comment by AnthonyHunt-UoW** [comment]
Ummm not quite.

Imagine I have users:

User 1 badge id eng1234
User 2 badge id eng1235
User 3 badge id sci1234

The badge id is already searchable via URL and API. So a search “term=eng” returns two users…

If I want to do something programmatically with the badge id, like add them to a group based on it, I have to search for "term=eng" to get the list of two users and then get the user id from the results and read each user individually . I'd like to have the badge_id returned in the initial JSON.

The admin/users API JSON currently returns something like
{id = xxx-yyy, name = user, email = ***@***.***}

What I’d like is to include the badge id here like
{id = xxx-yyy, name = user, email = ***@***.***, badge_id = eng1224}

Does that make sense?

________________________________
From: Thomas Schank ***@***.***>
Sent: Wednesday, September 18, 2024 5:19:09 PM
To: leihs/leihs ***@***.***>
Cc: Anthony Hunt ***@***.***>; Author ***@***.***>
Subject: [External] - Re: [leihs/leihs] Add badge_id to JSON on "Users" (Issue #1793)


Let me try to rephrase your question to ensure we understand each other correctly:

You would like to retrieve properties of an user account by its badge_id. The way to do this currently would be to retrieve all users and then filter within your client.

I guess we could add an query-parameter badge_id to the /admin/users/ resource, like /admin/users/?badge_id=12345ABC. This will always return a list of users (there is no unique constraint in the database on badge_id). However if your badge_ids are unique the list will contain (at most) one account.

**Comment by DrTom** [comment]
Ah, I see. The resource `/admin/users/` returns a default set of attributes. There is the query parameter `fields` by which you can customize the attributes; try to pass a JSON encoded array of attributes.   See: 
* https://github.com/leihs/leihs-admin/blob/master/src/leihs/admin/resources/users/main.clj#L58-L63
* https://github.com/leihs/leihs-admin/blob/master/src/leihs/admin/resources/users/shared.cljc#L17-L46

**Comment by AnthonyHunt-UoW** [comment]
Oh That’s brilliant! Although I’m struggling a little to implement. I’m sending this JSON to the API

{
  "per-page": "1000",
  "account_enabled": "yes",
  "organization": "******.uk",
  "page": "1",
  "term": "JOUR1",
  "fields": "{'groups_count', 'pools_count', 'email', 'img32_url', 'key', 'account_enabled', 'index', 'lastname', 'org_id', 'organization', 'page-index', 'login', 'firstname', 'open_contracts_count', 'id', 'closed_contracts_count', 'admin_protected', 'badge_id'}"
}

Which seems to return the same output as

{
  "per-page": "1000",
  "account_enabled": "yes",
  "organization": "******.uk",
  "page": "1",
  "term": "JOUR1"
}

I took the content of the fields field from the JSON returned from the empty query.

**Comment by AnthonyHunt-UoW** [comment]
Anyone know the format of the query parameter? I'm sending the request in Power Automate, but I can translate/figure it out with an example. Every permutation I've tried so far gets ignored with the default set being returned.

**Comment by DrTom** [comment]
Firstly back to the fields of the `/admin/users` resource. Your request looks correct but then the response should really include all those fields. Wir are using this feature ourselfs in API clients. Could you provide a `curl` example?

**Comment by AnthonyHunt-UoW** [comment]
I think that thats the problem I have, formatting the query. This is how I have tried it (which is the same as above). 

https://leihsv5-01.******.uk/admin/users/?page=1&term=huna1&fields={%27groups_count%27,%20%27pools_count%27,%20%27email%27,%20%27img32_url%27,%20%27key%27,%20%27account_enabled%27,%20%27index%27,%20%27lastname%27,%20%27org_id%27,%20%27organization%27,%20%27page-index%27,%20%27login%27,%20%27firstname%27,%20%27open_contracts_count%27,%20%27id%27,%20%27closed_contracts_count%27,%20%27admin_protected%27,%20%27badge_id%27}

but I have tried enclosing with [] and using "" instead of ''. Have you any examples of what it should look like?

**Comment by AnthonyHunt-UoW** [comment]
@DrTom Any thoughts? Anything I can go from that not the two source code files?

**Comment by AnthonyHunt-UoW** [comment]
I think I've tried about every permutation I can think of now in the "fields="
{:badge_id}
{badge_id}
{badge_id:}
badge_id
badge_id:
:badge_id
\"badge_id\"
'badge_id'


Nothing. Anyone have any ideas how this parameter is supposed to work?

I can see from leihs-sync repository that it says ":fields (cheshire/generate-string fields)" - but I can't see anything else that can help me create the structure of the query.

**Comment by DrTom** [comment]
@AnthonyHunt-UoW 

You need to send the value of fields as an array of strings/ first json encoded and then URL encoded. Maybe unfortunate but the filter work in a way that doing something wrong here is unlikely to result in an error but discarding them and then just sending the default fields. I suspect that happened with your trials. 

Note that the requested fields will be added to the default set of fields. 

Here is an minimal curl example which works: 

```
curl -i -H 'accept: application/json' -H "Authorization: token YOUR_API_TOKEN"   'https://YOUR_HOST/admin/users/?fields=%5B%22badge_id%22%5D'
```
