### ISSUE TITLE
Admin: category management

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1794]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.

The management of the category tree is currently accessible for the inventory managers. As the categories in the inventory pool are used across all users, too many people have the opportunity to customize them.

---

## Describe the solution you'd like

Management of the category tree should only be possible for Leihs admins in order to keep the number of people who can make changes to a minimum.

The administration is to take place in a new “Categories” area in the admin area.

#### Category tree view

![Image](https://github.com/user-attachments/assets/e7c78a98-f8bd-45ae-993b-eb39b1658483)

- In the “Categories” menu, the categories should be displayed using the tree structure. 
- The tree can be expanded or collapsed using the “+” and “-” buttons. 
- The name of the category is a link that leads to the “show” view of the corresponding category. 
- The number of assigned models is displayed for each category. If a category has no models, these should be marked in red.

#### Category show view

![Image](https://github.com/user-attachments/assets/ec3380b9-2e8e-4e81-8b44-46c9c52b7a1f)

The “show” view shows the data of the selected category and an overview of the assigned models

- The navigation history is shown as a breadcrumb
- The Name of the category is displayed as a heading
- The data of the category is displayed as a table
- (multiple) parent categories are displayed as a bullet list
- The primary button "Edit" leads to the edit view of the category

followed by a section "Models assigned to category"
- List of models in a table view, which are related to this category
- Each model lists the appropriate inventory pool as a link to the model `/inventory/:pool_UUID/models/:model_UUID`, they are listed as a bullet list

#### Category edit view

![Image](https://github.com/user-attachments/assets/50e0048e-aab4-4968-b2d3-8f702145ba6f)
![Image](https://github.com/user-attachments/assets/9870ae68-d8f0-44e7-a07f-868e33d30547)

opens in modal window

- text input for category name (mandatory)
- image upload (optional) - same component as in user image
- right side: parent categories
	- list of parent categories, if set
	- parent category shows breadcrumb path of category tree
	- parent category can be removed by button "remove"
	- button "Add parent category" to add a new parent category -> opens category tree
- opened category tree (same component as in Category tree view)
	- while hovering a parent category, the button "select" is shown
	- by clicking "select", the parent category gets added to the list above, the category tree is hidden
- Changes in the edit view can be saved by button "Save"
- Changes can be discarded by button "Cancel"
- The category can be deleted by button "Delete"
	- deletion is not possible, when
		- models are assigned to this category
		- category is used as a parent category
	-  a tooltip with appropriate message and deactivated button, prevent deletion

### Description of the filter option in category tree component

- search for corresponding categories by entering a term in field "search", the filter applies by typing
- "x" deletes the value in field "search"
- The name of the category should be searched. 
- If a category is found (at any hierarchy level), the category tree is expanded accordingly so that the categories found are displayed. 
- The entire depth of the tree up to the category found should always be expanded. Purpose: Traceability of the position in the tree.
- The entire category tree can be opened or closed using the “open all” and “close all” buttons

**Comment by nimaai** [comment]
@neoheat "Assigned in inventory pool". Shall it only inlude items of that particular model which are *not retired*.?

**Comment by belafonte** [comment]
@nimaai 

- [ ] category endpoint ( GET ) is missing a "label" field in parents vector
- [ ] category endpoint ( GET ) is missing a "image" field
- [ ] category endpoint ( POST ) data structure as following:

```json
{
    "category_id": "string - id",
    "name": "string",
    "image": "string - base64 | null"
    "parents": [
        [
            {
                "category_id": "string - id",
                "name": "string"
                "label": "string | null"
            }
        ]
    ]
}
```

**Comment by nimaai** [comment]
@belafonte 

```
                            Table "public.images"
    Column    |       Type        | Collation | Nullable |      Default       
--------------+-------------------+-----------+----------+--------------------
 id           | uuid              |           | not null | uuid_generate_v4()
 target_id    | uuid              |           |          | 
 target_type  | character varying |           |          | 
 content_type | character varying |           |          | 
 filename     | character varying |           |          | 
 size         | integer           |           |          | 
 parent_id    | uuid              |           |          | 
 content      | text              |           |          | 
 thumbnail    | boolean           |           |          | false
 metadata     | json              |           |          | 
```

**Comment by nimaai** [comment]
@belafonte i would expand the tree immediately if there are matches, not only if one presses "enter". what do you think? also would i notice is that when one presses "enter" and the field is empty then the tree quickly expands and collapses again. not sure if this is intended behavior.
