### ISSUE TITLE
Requests are not shown (error)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#180]
http://leihs-v4-test.zhdk.ch/procurement/requests/overview

How to reproduce:
1. Go to Procurement module
2. On requests overview an error is shown "We're sorry, but something went wrong.... "

**Comment by nimaai** [comment]
The problem is: 
`ActionDispatch::Cookies::CookieOverflow - ActionDispatch::Cookies::CookieOverflow`

**Comment by nimaai** [comment]
After discussion @eins78 the best and simplest solution would probably be to store the filter settings in DB, like in Cider.

**Comment by nadjaweisskopf** [comment]
@nimaai I think attaching the filter settings to the user would even make sense. The users were astonished every time the filter settings were set back to the current year. They would be glad, if we would update the last filter settings for every user.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/42a5536318f74480ca8bdfe949723c0d0f9a61ee

https://github.com/leihs/leihs_legacy/commit/3eea798f686ff4c66e6416a355ac88855c903975

**Comment by nadjaweisskopf** [comment]
test ok
