### ISSUE TITLE
Create ERM diagram

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#182]
Our database diagram is out-of-date. We need to update it.

**Comment by nadjaweisskopf** [comment]
This issue is important but has a lower priority!

**Comment by nimaai** [comment]
Yes, that's why I've put it at the bottom. But it is definitely part of the milestone. We have changed the schema of our entities in DB and we need to have it documented for further work.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_documentation/commit/51895ee9b7e4294db86cc46b71a13acf8204eba3
