### ISSUE TITLE
Bug: Admin -> Label in Fields detail view wrong

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1827]
**Application**
admin

**Describe the bug**
The label "name" at Property `Active` in a field detail page, e.g. https://leihs.zhdk.ch/admin/inventory-fields/attachments is wrong
 
**To Reproduce**
1. Login as leihs admin in /admin
2. select menu "Fields"
3. Choose a field from the list
4. See label "name" from property `Active`

**Expected behavior**
The label should be "active" instead of "name"

**Screenshots**
![Image](https://github.com/user-attachments/assets/2ea3ff52-869a-4514-8b58-c9955a1c179c)

**Leihs version**
7.8.x

**Desktop (please complete the following information):**
- Device: all
- OS & Version: all
- Browser & Version: all

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/87640f2ee14acae53a7cde695f6a9362ccabe4e5
