### ISSUE TITLE
Status "Verify and Approve" is not shown

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#183]
The group manager sees the status "Verify and Approve" if
- the user of the order is in a group
- the model the user has ordered is in the group
- the group is flagged as "verification required"
- the verifying user has the privelege "group manager"

BUT the status "verify and approve" is not shown. Only the status "verify" is shown. 

The other rules inside the hand over work as specified.

![prufen und genehmigen kopie](https://cloud.githubusercontent.com/assets/3356016/23356223/548cec96-fcd9-11e6-89b3-e6d7715a1c9d.png)

**Comment by nadjaweisskopf** [comment]
@nimaai I retested the group-manager-feature and found the one bug I had already seen in the earlyer test.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/4d415aa76546fe071ba4a21b08d0bbfc94cd54fc
https://github.com/leihs/leihs_legacy/commit/1fc084fdccc9511dcd79ffedca3440373e06ddfb

**Comment by nadjaweisskopf** [comment]
test ok
