### ISSUE TITLE
Bug: validation of custom fields must allow numbers 

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1832]
**Application**
`admin`

**Describe the bug**
The user-defined field `properties_p4u` cannot be changed as there is a validation of the field `data:attribute` and no numbers are allowed.

**To Reproduce**
1. Go to 'admin/fields'
2. Search for field `properties_p4u`
3. Change Minimum role required for view to `inventory_manager`

**Expected behavior**

field `data:attribute` does allow
- lower letters without accents
- numbers
- underscore

** Solution **

Change code to (already changed in database by @urs-van-binsbergen 
```
CREATE OR REPLACE FUNCTION fields_validate_id_f()
      RETURNS TRIGGER AS $$
      BEGIN
        IF NEW.id !~ '^[a-z0-9_]+$' THEN
          RAISE EXCEPTION 'ID must contain only lowercase letters without accents, numbers or underscore' ;
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
```

**Screenshots**
<img width="842" alt="error_field-validation" src="https://github.com/user-attachments/assets/93f91469-b169-4d5e-8402-d2fb5dbceb5d">

**Leihs version**
7.8.x

**Desktop (please complete the following information):**
- Device: Desktop, Mobile
- OS & Version: all
- Browser & Version: all

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/55e9edf3ea94ce13697c3ed08377ef06630e4b66
