### ISSUE TITLE
admin: missing default values for some field shows

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#1837]
- [x] `Required (data:required)`
- [x] `Unique ID-Attribute (data:attribute)` (empty makes sense here perhaps...)
- [x] `Minimum role required for view (data:permissions:role)`
- [x] `Type (data:type)`

**Comment by nimaai** [comment]
even wrong values are shown in some cases. because we are using `@core/data*` (which is meant for update) instead of the `@core/inventory-field-data*`.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/87640f2ee14acae53a7cde695f6a9362ccabe4e5

FYI @belafonte

**Comment by neoheat** [comment]
tested 👍
