### ISSUE TITLE
Changing orderer does not work

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#184]
How to reproduce:

1. Create an order as delegation
2. Open order as manager
3. change orderer
4. save --> error msg. pops up
![change orderer](https://cloud.githubusercontent.com/assets/3356016/23358701/5662ab8c-fce3-11e6-913c-944af1b3d2ee.png)

URL: http://test.leihs.zhdk.ch/manage/169/contracts/submitted_9435_169/edit

**Comment by nimaai** [comment]
@nadjaweisskopf Changing borrower works, but changing the contact person of a delegation does not.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/4a70603769618be42e9bcfdbcbb14edbdea75c82
https://github.com/leihs/leihs_legacy/commit/856072a87743c1b3d40f27825ea001f82345c085
