### ISSUE TITLE
BUG: Fix "Set-new-password" workflow if request returns 409/Conflict

### ISSUE THREAD

**Issue by SeduroDotCom** [leihs/leihs#1840]
Password reset doesn't redirect to "Set new password-View" correctly if new password is invalid (409 Conflict)

**To Reproduce**
1. Leihs Login
2. Passwort vergessen?
3. Passwort-Reset-Link anklicken
4. Neues Passwort eingeben
   1. Bei ?Invalider Eingabe? wird ein 409 Conflict zurückgegeben und man sieht "Website  ist nicht erreichbar" / https://leihs-zhdk.ch/reset-password nicht erreichbar

**Expected behavior**
If "Set-new-password-Request" returns 409 then user should return to "Set-new-password-View"

**Leihs version**
- 7.8.0

**Desktop (please complete the following information):**
- Chrome 130.0.6723.92

**Comment by SeduroDotCom** [comment]
Used pw=12345

![Image](https://github.com/user-attachments/assets/b68b9c19-8dd3-4b2d-b5da-f16e16f4016e)
![Image](https://github.com/user-attachments/assets/3d19518b-ba42-4251-a559-8c1aea98caf4)
![Image](https://github.com/user-attachments/assets/f5bb4e07-955e-43e6-80e7-d59cf71526b8)

**Comment by DrTom** [comment]
I can not reproduce this, neither could @nimaai. It works as expected.

**Comment by neoheat** [comment]
Same here, no issues while resetting password

**Comment by SeduroDotCom** [comment]
To reproduce by numeric password

https://github.com/leihs/leihs/pull/1851

**Comment by SeduroDotCom** [comment]
- FYI: Tested on manuel.leihs.*-sever
