### ISSUE TITLE
Legacy Inventory: Remove action `delete item`

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1841]
**Application**
inventory (legacy)

**Describe the bug**
an item, in the following conditions can be deleted
 - is not a package
 - has no children
 - has no reservations
 - has no hard overbookings

An item can even be deleted 
- by a lending manager
- if not owner of the item

**To Reproduce**

--- Example: item with no reservations ---
1. Login as lending manager
2. go to inventory
3. create a new item
4. fill item form and save
5. search for the new created item
6.  in from list view, choose action `delete item` from dropdown-actions on button `Edit Model`

alternate scenario: go into detail view of item and choose action `delete item` from dropdown-actions on green button `Save Item`

--- Example: not the owner of the item ---
1. Login as lending manager
2. go to inventory
3. Search for a item `INV47564`
4.  in from list view, choose action `delete item` from dropdown-actions on button `Edit Model`

alternate scenario: go into detail view of item and choose action `delete item` from dropdown-actions on green button `Save Item`

**Expected behavior**
The item deletion function should be removed completely.

**Screenshots**
![delete item List view](https://github.com/user-attachments/assets/1d343b7e-5f2a-4b7a-aab4-7058809278dc)
![delete item detail view](https://github.com/user-attachments/assets/381b81d4-1732-4438-b3d9-476a1b1fbaaf)

**Leihs version**
[> Provide a tag, branch, or other gitref.
](https://github.com/leihs/leihs/releases/tag/7.7.0)

**Desktop (please complete the following information):**
> - Device: all
> - OS & Version: all
> - Browser & Version: all

**Comment by nimaai** [comment]
@neoheat what about licenses?

**Comment by nimaai** [comment]
@neoheat and what about future API?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/b839e262b812c2104f27487b6059c2b2d74dd147

**Comment by neoheat** [comment]
tested 👍
