### ISSUE TITLE
Admin: Bug when entering more than one holiday date range

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1852]
**Application**
admin

**Describe the bug**
I get an error when entering more than one holiday on the inventory pool in the admin section. 

**To Reproduce**
> Steps to reproduce the behavior:
1. go to admin section
2. choose a pool
3. choose tab "opening times"
4. edit the holidays
5. enter at least two holidays
6. save
7. error appears

**Expected behavior**
I should be able to enter more than one holiday at a time. 

**Screenshots**
<img width="787" alt="Bildschirmfoto 2024-12-10 um 18 40 18" src="https://github.com/user-attachments/assets/e0c8d048-c67d-45d4-abbc-6563f13a5797">

**Leihs version**
7.8.0

**Desktop (please complete the following information):**
safari

**Comment by neoheat** [comment]
I can confirm the Bug.

**Comment by urs-van-binsbergen** [comment]
addace7a6cfb0d3aa97e4605d3f23bd8b09e1a71

**Comment by neoheat** [comment]
tested 👍
