### ISSUE TITLE
Error msg. not mentioned, just a red line is shown

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#186]
How to reproduce:

1. Go to pool
2. Approve an order with conflicts
3. Screen "approval failed" shows a red line without showing the error msg.
 
![fehlermeldung wird nicht angezeigt](https://cloud.githubusercontent.com/assets/3356016/23463774/0ae19996-fe93-11e6-84b9-29f02ac508f7.png)

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/5076c4b6b6e09352526b68c3d97d81bd8da9cdbc
https://github.com/leihs/leihs_legacy/commit/89a52c47769bfd0ac7cddec4f08cb11471127a30
