### ISSUE TITLE
double contracts in global search and tab "contracts"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#188]
How to reproduce:
1. case
1. search for "häring" in the global search
3. as shown in printscreen a contract is listed twice

https://test.leihs-v4.zhdk.ch/manage/a02b8163-9a16-5066-b48e-9eb74cf8b791/search?search_term=häring

2. case
1. go to lending section
2. go to tab "contracts"
3. search for "häring" in the search field
4. as shown in printscreen a contract is listed twice

https://test.leihs-v4.zhdk.ch/manage/a02b8163-9a16-5066-b48e-9eb74cf8b791/contracts?status%5B%5D=signed&status%5B%5D=closed

Same behaviour for user "Rodrigo Cortes Guadarrama"

![doppelte vertrage suche](https://cloud.githubusercontent.com/assets/3356016/23703569/dfadba98-0400-11e7-90ae-60403da940e7.png)
![doppelte vertragslinien](https://cloud.githubusercontent.com/assets/3356016/23703568/df8fe892-0400-11e7-998e-e061720ef6f0.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/703c25946198a173e0264d8bab9d851d17a12750
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/6f4b072b4ba413c6953961e2f56f350aad2d9567
