### ISSUE TITLE
Import option list for Fundus

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#189]
[Fundusliste Nr.2_bearbeitet.xlsx](https://github.com/leihs/leihs/files/840762/Fundusliste.Nr.2_bearbeitet.xlsx)
Please import the attached document for the inventory pool "Fundus-TdK"
- as options
- starting with the highest option nr. in the format FUNOXXXXX

As far as I know Ramon has imported the last option list for Fundus. You might be able to reuse his import-script?

**Comment by nimaai** [comment]
@nadjaweisskopf I have found out that there are 2 options without an inventory code in "Fundus-TdK". For all pools there are 287. Is this a bug or feature?

**Comment by nimaai** [comment]
[import.txt](https://github.com/leihs/leihs/files/850268/import.txt)

File in CSV format to be imported.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/d2c694db3aae98abdcfa0ad22bb3e67f941435be

**Comment by nimaai** [comment]
Import instructions for PROD:

1. copy `import.txt` to `script/leihs/`
2. `RAILS_ENV=production bundle exec rails runner script/leihs/import_options_for_fundus.rb`

**Comment by nimaai** [comment]
imported on 5.4.2017 at about 11:50
