### ISSUE TITLE
Add more exact timestamp / due dates for rental process

### ISSUE THREAD

**Issue by tilllt** [leihs/leihs#19]
Hey, 

this probably fits more as enhancement part of Leihs. With the structure of the rental system how it is now, it is not possible to schedule short term lendings (short term = shorter than one day). Also the whole system only works with workarounds if your equipment rental is only open one day a week.

Specifially in our case, the students are supposed to bring back equipment on Mondays before 3pm, while the ones taking out equipment are supposed to show up at 4-6pm. Since we have the rental place only opened one day a week, thats the only way we can handle the take back / give out process.

Our problem with leihs is the following: If somebody rents a piece of equipment from Monday to Monday, it will be marked as rented out for next monday. So if somebody wants to make a reservation for next week, it will show up as rented. As a workaround we will now schedule the rentals until sunday and know that anyone with 1day overdue for takebacks is within the allowed timeframe. That works, but once the email reminders start working for us too, we will have the problem, that people receive a mail on saturday that they are supposed to bring back their equipment on sunday...

So for us it would be great if you could rent equipment from and to a specific date AND time. this also would help for short term rentals where somebody just takes out a camera for a couple of hours and brings it back the same day...

cheers,
till

@gissues:{"order":66.66666666666666,"status":"backlog"}

**Comment by herzogmedia** [comment]
Has there been any further action regarding this issue / feature and its implementation? We (Dept. of Journalism at University of Mainz) would be quite interested in that.

**Comment by nadjaweisskopf** [comment]
This feature has never showed up on the ZHdK-Change list and therefor our priorities were somewhere else. Our main lending departments are happy with the day-to-day reservations. But we have institutions asking regularly for a more precise lending time. I will have a look at all the changes needed and how to best approach this feature.

**Comment by multiflexi** [comment]
We at University of Economics, Prague are considering this system for lending of our equipment and this feature is quite crucial. If I understand it correctly, now it is only possible to return equipment in day x and lend it again in day x+1. We need to be able to lend equipment on hourly basis so it does not have to just lie here unused when students are in a hurry when filming. It would be also possible to pitch in with development but we are not using leihs at the moment.

**Comment by nadjaweisskopf** [comment]
@multiflexi thanks for your input. The state is still the same - check my comment from January and the comment "psy-q commented on 18 Nov 2013". So unfortunately due to recources (and money) lending on hourly basis will not be possible in some time (years). But just to say - you can also rent stuff from today. Each inventory pool can decide, if the student can pick up the stuff on the same day the order has been place or order day + X days (see printscreen).

![bildschirmfoto 2018-08-15 um 13 04 20](https://user-images.githubusercontent.com/3356016/44145503-1d41eb30-a08c-11e8-9226-5fb924dae4c8.png)
