### ISSUE TITLE
Do not delete filter settings when switching to another category

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#191]
How to reproduce:

1. go to borrow section
2. Chose a category
3. set the filter "in list", "start-date", "end-date" and "a pool"
4. switch to another category in the list on the left hand side
5. the filter settings are deleted and the user has to enter the settings again

How it should be: 

The settings should be saved if the user 
- switches to another category
- changes one or more settings

detail spec needs to be defined together with the lending mgr.

**Comment by nimaai** [comment]
@nadjaweisskopf I have deployed the feature to https://test.leihs-v4.zhdk.ch/. Please test.

The new scenario is as follows: https://github.com/leihs/leihs_legacy/blob/a9a5a1c9cedf02747cee0049e624d2d928fb6414/spec/features/borrow/model_list.feature#L194-L228

**Comment by nadjaweisskopf** [comment]
Bug not always reproducable:

1. enter category audio and set a date and time
2. Navigate to "start" tab
3. enter category "Elektromaterial"
4. Date is not shown correctly (see printscreen)

![bug bei datum](https://cloud.githubusercontent.com/assets/3356016/24741102/d4c8e1ba-1aa4-11e7-86bc-54b7b8096207.png)

**Comment by nadjaweisskopf** [comment]
Bug not always reproducable:

1. enter category audio and set a date and time
2. Navigate to "start" tab
3. enter category "Elektromaterial"
4. Delete all filters
5. Error "the page you were looking for doesn't exist" appears
![page doesn t exist](https://cloud.githubusercontent.com/assets/3356016/24741255/74aa92b4-1aa5-11e7-8406-935b7f4abd30.png)

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/30b082716f15a0b98eb88fe03e0e14e2e5d1a478

**Comment by nadjaweisskopf** [comment]
test passed!
