### ISSUE TITLE
Category browser for options' inventory always empty and thus superfluous

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#195]
1. Go to "Inventory"
2. Click on "Options"
3. Click the category browser icon next to "Search..."
4. Click on any category and it will show empty results

Reason: options don't belong to any categories and can't be assigned to any neither.

@nadjaweisskopf Let's remove the category browser toggle from here.

**Comment by nadjaweisskopf** [comment]
@phiku Don't use filter setting when switching to options tab

**Comment by phiku** [comment]
@nadjaweisskopf Should work now.
