### ISSUE TITLE
Delete item if not yet used

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#196]
Item should be deletable if it has no conract yet.

If items have been created by mistake and not yet used in a contract, then they sould be deletable.  
If the item has already been placed in a basket, the items should still be deletable. 

If already attached to an order, a hand over or a contract I can not delete the item.

Add delete button in following sections in leihs/lending:
- model list of inventory

feature wish by D. Furrer and external schools

Scenario: 
If an item has not yet been added to a contract
and the item is not in a hand over
and the item is not in an order
then as an Inventory Manager I can klick on the delete button in the inventory list
and delete the item.

If an item has been added to a contract
or the item is in a hand over
or the item is in an order
then the delete button is not visible
and I can not delete the item

**Comment by Bekman553** [comment]
Hi,

is this feature already implemented? I would use this... (at least via API)

**Comment by rhizomatic** [comment]
Hello,
I stumbled over this thread. Can't find any option to delete any item in version 5.2.3
Is there truly no option to delete items? I surely must be missing something here...

**Comment by nadjaweisskopf** [comment]
on hold because of rails upgrad

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/79b59cc9684df56913cc36fea780366e61fc9f07

**Comment by neoheat** [comment]
testing blocked because of https://github.com/leihs/leihs/issues/1554. no new model / item can be added

**Comment by neoheat** [comment]
tested positive:
- item can be deleted, when not in order (and in an order or a handover)
- item can't be deleted, when placed in an order or a handover
