### ISSUE TITLE
Global search needs case sensitive contractnr.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#197]
Contractnr. 6RTD is is not found with search string "6rtd"

**Comment by nimaai** [comment]
The same for search in the contracts list.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/372c6a447bc1e093af25c1948b734378656d7883
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/8f34b74ec72bd9d53c699af61afbf81ec68b2f67
