### ISSUE TITLE
Scanning contractnr. adds a letter "C"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#198]
When scanning the contract the string "C 6RTD" is written instead of "6RTD"

**Comment by nimaai** [comment]
@nadjaweisskopf On what page?

**Comment by nadjaweisskopf** [comment]
On any page. MS Word, Wordpad, global search field

**Comment by nimaai** [comment]
This is also the case in PROD, nothing has changed in this regard.
