### ISSUE TITLE
Sorting of fieldgroups in item different than in production

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#200]
1. edit item
2. in production the field group "inventory" is on the left hand side. This is what the users are used to. 

Do you know why the sorting has changed?

**Comment by nimaai** [comment]
There was a new field "test" under "Allgemeine Informationen" which most probably you @nadjaweisskopf created..? 

Anyway, that was the reason why the layout changed, because it is dynamically computed based on the amount of fields defined.

I deleted the "test" field and now it looks like on PROD.

**Comment by nadjaweisskopf** [comment]
Ah ok. I thought so an deleted the field from the item form but that didn't change anything. But perfect in that case. I'll close the ticket, thanks.

**Comment by nimaai** [comment]
Yes, you have to deactivate it in admin fields settings.
