### ISSUE TITLE
Always load Setting from DB

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#202]
Right now our `Setting` is a singleton which is loaded and memoized at server start. This has shown to be a problem with dynamically set settings especially in regards to multiple workers.

@drtom FYI

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e255f5fa4bec85e616950bf34b3fe3275259a5b1

**Comment by nadjaweisskopf** [comment]
Test Admin settings page

**Comment by nadjaweisskopf** [comment]
@nimaai
1. Switching to Admin/settings is really slow - the page is loaded after ca. 10 seconds. 
2. Saving the settings is very slow too, sometimes more than 10 seconds

I can't find any other problems but could we check the settings tomorrow together, to be sure, that the page works as expected?

**Comment by nimaai** [comment]
@nadjaweisskopf I cannot reproduce it for `4.14.0-RC.3` on staging.
