### ISSUE TITLE
Release notes as part of the repository

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#205]
Right now we write and keep release notes on GitHub.

Let's make them additionally as part of the repository itself, like in Madek: https://github.com/Madek/madek/blob/master/config/releases.yml

Advantages:
- independence of GitHub
- possibility of reading and displaying the current release as part of the UI 
- eventually displaying the information as a dedicated page of leihs itself

https://medienarchiv.zhdk.ch/release

We will thus only have to inform the user that there is a new release. They can then read its details in leihs itself.

**Comment by nimaai** [comment]
@nadjaweisskopf FYI

**Comment by nadjaweisskopf** [comment]
Ticket #251 has been implemented (same topic)
