### ISSUE TITLE
adjust items in pool ZHdK-Inventar for Mike Honegger

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#207]
Please adjust all items from the list in pool "ZHdK-Inventar" as following:

set field "Supply Category" to "AV-Technology" (in German AV-Technik)

[ergaenzen_AV-Technik.xlsx](https://github.com/leihs/leihs/files/890312/ergaenzen_AV-Technik.xlsx)

**Comment by nimaai** [comment]
CSV file to be used for import: [gh_207.txt](https://github.com/leihs/leihs/files/970818/gh_207.txt)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c0a6fcae90d8c66ad82d4f7fe2284b5a1cec9a83

`RAILS_ENV=production bundle exec rails runner script/leihs/gh_207.rb` on PROD after deploy

**Comment by nadjaweisskopf** [comment]
Hoi matus

Gibst Du mir Bescheid, wenn ich die Gegenstände von Mike testen kann?


Mein Slack ist zurzeit nicht aktiv. Ich muss ihn updaten, dehalb hier per Mail.


Lieber Gruss

Nadja



________________________________
Von: Matús Kmit <notifications@github.com>
Gesendet: Mittwoch, 3. Mai 2017 13:25
An: leihs/leihs
Cc: Weisskopf Nadja; Author
Betreff: Re: [leihs/leihs] adjust items in pool ZHdK-Inventar for Mike Honegger (#207)


c0a6fca<https://github.com/leihs/leihs/commit/c0a6fcae90d8c66ad82d4f7fe2284b5a1cec9a83>

RAILS_ENV=production bundle exec rails runner script/leihs/gh_207.rb on PROD after deploy

-

**Comment by nimaai** [comment]
@nadjaweisskopf du kannst es auf TEST jetzt testen

**Comment by nadjaweisskopf** [comment]
Ok, hab getestet, die Beschaffungskategorie wurde korrekt abgefüllt.


Danke vielmals. Auf wann wirst Du in die Produktion einspielen können?

________________________________
Von: Matús Kmit <notifications@github.com>
Gesendet: Mittwoch, 3. Mai 2017 13:53
An: leihs/leihs
Cc: Weisskopf Nadja; Mention
Betreff: Re: [leihs/leihs] adjust items in pool ZHdK-Inventar for Mike Honegger (#207)


@nadjaweisskopf<https://github.com/nadjaweisskopf> du kannst es auf TEST jetzt testen

-

**Comment by nimaai** [comment]
jede Zeit. man muss dafür nicht deployen.

**Comment by nimaai** [comment]
Ich mache das mal morgen Abend. Ich will noch was anpassen morgen.

**Comment by nimaai** [comment]
Done on PROD.
