### ISSUE TITLE
Find delegation contract when searching for user

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#208]

**Comment by nadjaweisskopf** [comment]
Scenario:

1. search for user or item nr.
2. contracts section shows the following details: 
 - contracts of a person matching the search string
 - contracts of a delegation where contact person matches the search string
3. the contracts should be sorted in the following order
    1. open user contracts alphabetically
    2.  then open delegation contracts alphabetically
    3. then closed user contracts alphabetically
    4. then closed delegation contracts alphabetically

**Comment by nimaai** [comment]
@nadjaweisskopf A general question: Should we also display contracts (mostly closed) of a user who does not have any access right to the pool anymore? Because currently we have a bug where the name of such a user is not displayed.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e57a087ed487a50b1ece3f8a3c09b9d0f8744a7d

**Comment by nadjaweisskopf** [comment]
Sorting according to the order mentioned above.

**Comment by nimaai** [comment]
As discussed with @nadjaweisskopf we continue showing also contracts for users/delegations who don't have access to the pool anymore.

**Comment by nadjaweisskopf** [comment]
@nimaai Could you please deploy this one to test so I can retest? Thanks.
