### ISSUE TITLE
Date field is buggy

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#209]
1. go to take back in lending section
2. edit item
3. start typing in date field
4. if you type too slowly, the date is set back to the date it was before

How it should be: 
- If you delete the date, then keep the field empty
- If you close the calender without typing a date, then the original date is kept
- Keep all other behaviors as they are now

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/583196674cf4fd69e5d9355235bbaabd540fa9ce

@nadjaweisskopf please test the booking calendar everywhere.
