### ISSUE TITLE
Solution for missing admin user in fresh installation

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#214]
Dump-solution from Remo

This solved the problem of the missing admin-user.
[leihs.dump.sql.zip](https://github.com/leihs/leihs/files/969883/leihs.dump.sql.zip)

1. Install according to Github description
2. Install Demo-DB
3. Delete test-data
4. admin-user exists
5. DB-Dump created by Remo

**Comment by nadjaweisskopf** [comment]
@nimaai @DrTom 
Can you reuse and integrate the Dump from Remo to support other users installing PostgreSQL?

**Comment by nimaai** [comment]
@nadjaweisskopf Rather no.

Our actual desired solution is to provide a GUI for creating one's own admin user (and possibly other data). A subproject for this purpose was already created by @DrTom -> https://github.com/leihs/leihs_system/tree/master.

In short term we should _only_ create the most minimal data required for admin user.

**Comment by nimaai** [comment]
I will check the dump. According to @nadjaweisskopf it should only contain the minimal necessary data for an admin user to login in. If this is the case, then we could temporarily use it in our deployment recipe...

**Comment by nimaai** [comment]
And it's not the case. We can't use Remo's dump.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/0d9361e0785729d90465209119bfe227a3fc1f6e
https://github.com/leihs/leihs_legacy/commit/6c4828b1fa3a2e6feecce7847c9a8ddd65cbe690

As discussed with @DrTom the best and easiest way is to provide a simple UI form to create the initial admin user and password. I have thus implemented it this way. @nadjaweisskopf You can see the new scenarios in the commit link above:
  1. `engines/leihs_admin/spec/features/authentication_systems.feature`
  2. `spec/features/manage/create_first_admin_user.feature`

The 1. can be tested on TEST. For 2. the DB on TEST needs to be cleared. Let me know when you are about to test it and I will do it for you there.

**Comment by nadjaweisskopf** [comment]
I will check this one when leihs is set up for F+F
