### ISSUE TITLE
Hosting for F+F - install leihs on a server (staging)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#215]

**Comment by nadjaweisskopf** [comment]
Hoi alle

Es gibt bereits einen Server:

https://wiki.intern.zhdk.ch/itz/doku.php?id=infrastruktur:ffzh.leihs.zhdk.ch

Matus ist berechtigt, die weiteren Details stehen im (alten)
Ansible-Rezept:

https://github.com/leihs/ansible-leihs-setup/blob/master/site_ffzh.yml

**Comment by nimaai** [comment]
host: http://ffzh-leihs-staging.ruby.zhdk.ch/

**Comment by nimaai** [comment]
external url to access the server is: https://ffzh-staging.leihs.zhdk.ch
