### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#216]
There are still these annoying `Warning: fuzzy message was used.` messages. @psy-q told me some time back that there is no need to fix them as Swiss German is going to be removed anyway. Let's do it then!

**Comment by nadjaweisskopf** [comment]
- [ ] Remove warnings
- [ ] try to make a language report
- [ ] check with bb if we keep spanish, french and swiss german - who translates?
- [ ] we need to show an info that the strings are not always translated

**Comment by nadjaweisskopf** [comment]
At the moment new languages need to be added via database or we need to implement it in Admin-section or deployment. At the moment adding a new language is not "out of the box".
Warning have been fixed.

Decision: In the Admin-section the Admin has the possibility to define which language is the default language and which language is active or inactive. (Own tab for languages)

**Comment by nadjaweisskopf** [comment]
I will create a new ticket for the still due adjustments
