### ISSUE TITLE
LDAP not working in version 4

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#217]
Hi Guys,

I am trying to enable LDAP auth in version v4 according to your documentation [here](https://github.com/leihs/leihs/wiki/LDAP-configuration).

AuthenticationSystem.find_by_class_name("LDAPAuthentication")
=> nil

Does not find the LDAPAuthentication class.

Did this change in version 4?

Thanks for your help,
Jan

**Comment by nimaai** [comment]
Hi Jan,

For some reason it is assumed that the LDAP entry exists already in `authentication_systems`.

try:
```
ldap = AuthenticationSystem.find_or_initialize_by(class_name: 'LDAPAuthentication')
ldap.name ||= 'LDAP Authentication'
ldap.is_default = true
ldap.is_active = true
ldap.save
```

Works?

**Comment by JanWelker** [comment]
Works like a charm. Thanks for your quick reply.

Cheers,
Jan

**Comment by nimaai** [comment]
Wiki updated: https://github.com/leihs/leihs/wiki/LDAP-configuration
