### ISSUE TITLE
Show warning when saving an item or software with already existing serial nr.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#219]
Scenario: 

1. save a new item/software with an already existing serial nr.
2. you receive a warning msg. saying an item/software with the same serial nr. already exists
3. You can then either overwrite the serialnr. and save again 
4. OR you cancel the creation of the item/software

**Comment by nimaai** [comment]
Actually I am thinking of implementing it rather as a modal dialog (pop-up) for following reasons:
1. We already have something similar in another place, namely "Approve anyway".
2. We are even doing something similar on the edit item page where if attachments could not be uploaded, then we show a modal dialog with the error message.

@nadjaweisskopf What do you think?

**Comment by nadjaweisskopf** [comment]
Additional restriction I forgot!

- Please compare the strings **without** empty spaces and **without** capital/small letters.

**Comment by nimaai** [comment]
@nadjaweisskopf  Should this warning come only for the items of the current pool (owner or/and responsible pool) or should be done across all items?

**Comment by nadjaweisskopf** [comment]
I am not sure. I could imagine both solutions would work. I'll ask Mike and Barbara.

**Comment by nadjaweisskopf** [comment]
@nimaai I have an answer from Barbara: 

Für mich passt es wenn es über alle Parks geht, wir schieben doch immer wieder Gegenstände hin und her.
Und es ist ja nur eine Warnung.

So let's check the items throughout all pools. I think that makes sense too.
