### ISSUE TITLE
Tooltip for a model does not open for specific lines in specific browsers

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#220]
Safari:
1. In borrow section navigate to some category 
2. Hover over 2nd model line in the list
=> the model tooltip does not open

Chrome:
1. In borrow section navigate to some category 
2. Hover over 1st model line in the list
=> the model tooltip does not open

Firefox:
- OK

**Comment by nadjaweisskopf** [comment]
I can not reproduce this problem. Safari and Chrome work fine for me. I believe the students would have already opened a ticket if this were the case. We can discuss this tomorrow.

**Comment by nadjaweisskopf** [comment]
Can not be reproduced - we will close the ticket
