### ISSUE TITLE
Possibility to deactivate a pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#223]
It should be possible to deactivate a pool, which is not needed anymore. 

Admin section
- In the edit page of an inventory park the Admin can choose to deactivate the inventory park
- In the list of pools the Admin sees the property "active" or "inactive"

This provokes the following behaviour in active pools:  
- The pool is not listed in the list of pools on the top right side of the page anymore
- The pool is not listed in any list such as "responsible department" or "owner" in edit page of item
- The pool is not listed in any search fields such as "All inventory pools" in inventory list

This provokes the following behaviour in borrow section:  
- The pool is not listed in the list of the pools in the menu on the top of the page
- No items of an inactive pool are listed
- In the model list when choosing a category, the pool is not shown in the filter menu
- When opening the calender of an item no inactive pool should be shown

It should not be possible to deactivate a pool when
- contracts are still open
- at least 1 item is not retired and either owner or responsible pool is current pool 
- an order is pending

Admin can switch to the pool even if deactivated. 

User-priveleges (managers and customers) are not changed.

If the Admin chooses to active a pool again, all settings above need to be adjusted so the pool is shown and can be chosen.

**Comment by nimaai** [comment]
> It should not be possible to deactivate a pool when contracts are still open.

@nadjaweisskopf What about unsubmitted/submitted/approved orders?

**Comment by nimaai** [comment]
@nadjaweisskopf I strongly suggest not to provide and implement the possibility for an admin to access an inactive pool. Such a feature would involve changing LOT OF code for the models, which would also not be that easy. If they temporarily need to do something in an inactive pool, then they need to temporarily enable it. If in this period some order comes in, etc. then they would need to clean up such data by hand.

**Comment by nadjaweisskopf** [comment]
Yes, correct. I don't see the benefit of this either. So let's say the Admin has to reactivate the pool if he wishes to make changes. Nothing in between is possible.

**Comment by nadjaweisskopf** [comment]
Still to be done: 
It should be possible to deactivate a pool even though an order is pending in borrow section (not sent).
I will create a new ticket for this behaviour.

**Comment by nadjaweisskopf** [comment]
Still to be done: 

- [ ] It should be possible to deactivate a pool even though an order is pending in borrow section (not sent). (scenario missing)

- [ ] Scenario for Helper missing

- [ ] Please add Admin-role in existing scenario "Exclusion of inactive inventory pools in the topbar dropdown list"
