### ISSUE TITLE
change of design in borrow section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#225]
get rid of amount of days of lending. (see print screen)
write **from date - to date** on the right hand side (see print screen)
write "main" date in bold (see print screen)

[Design_change_borrow.pdf](https://github.com/leihs/leihs/files/1022312/Design_change_borrow.pdf)

Please note how much time you needed for this change (for invoice HSLU)

**Comment by nimaai** [comment]
@nadjaweisskopf What print screen?

**Comment by nimaai** [comment]
@nadjaweisskopf I will do the same for returns and pickups as well, ok?

**Comment by nadjaweisskopf** [comment]
Yes please --> see printscreens

**Comment by nimaai** [comment]
time effort: 3h
