### ISSUE TITLE
Create a VMWare Demo-Version for Stapo

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#226]
Create an empty DB-Installation on the newest version of leihs. 

They will create the Admin and all following pools, items, etc.

**Comment by nadjaweisskopf** [comment]
@nimaai noch ein Nachtrag von Karl:

"Ich habe kurz mit Olaf Stirnimann gesprochen. Er würde die VMWare Demo Version bei uns in der STAPO aufsetzen.
Er fragt an, ob es möglich wäre leihs im **## OVF Format** zu liefern?
Für technische Belange wendest Du Dich bitte während meiner Abwesenheit direkt an ihn."

**Comment by nimaai** [comment]
VM in requested format was created and download link provided.
