### ISSUE TITLE
Solve mail problem for HKB

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#227]
I will have a look at the settings in the pools and in leihs general. But a developer will probably need to have a look at this ticket. 

 Lieber Ramón
>
> Bei uns im Leihs funktionieren die Mails nicht mehr richtig. Das
> Erinnerungs Mail ein Tag vor dem Rückgabedatum wird nicht mehr versant.
> Und die Mailtexte im Backend wo ich die Texte anpassen kann sind für
> alle Sprachen auf Englisch, doch wenn ich ein Mail erhalte ist es auf
> Deutsch. Ist das normal oder deutet das auch auf einen weiteren Fehler
> hin. Ich wär sehr froh wenn du mir helfen könntest. Vielen Dank.
>
> LG Florian

**Comment by nadjaweisskopf** [comment]
@psy-q Ramon, would it be possible that you could check this bug with HKB?

**Comment by psy-q** [comment]
@nadjaweisskopf I will try to contact BFH to request fresh authorization to connect to the server (my old credentials are long dead). I'm not sure I can figure out what's wrong, though.

**Comment by nadjaweisskopf** [comment]
answer from ramon: 

auf test ist 3.40.1, aber das wurde soweit ich weiss nie für produktiv
abgesegnet, also ist dort noch 3.32.1. 

ich hab gesehen, dass im cronjob, der mails verschickt, die falsche
ruby-version gesetzt war. das hab ich korrigiert. mit etwas glück gehen
die mails heute nacht wieder raus -- ich schaue morgen auf den server,
ob das wirklich funktioniert hat.

**Comment by nadjaweisskopf** [comment]
We'll see tomorrow, if mails have been sent to the user.

**Comment by nadjaweisskopf** [comment]
Configuration of Cron-Job was wrong. An old Ruby-version was addressed. Ramon solved the problem and HKB is informed.
