### ISSUE TITLE
Change of behavior when entering room-information

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#228]
Following changes are needed:

- [ ] Every building should only be listed once in the list of buildings in the admin section (will be dealt with by separate ticket)

- [x] A new register is needed in the Admin section called "Rooms". In this section the user sees all imported rooms and has the possibility to create new rooms. If he creates a new room the room needs to be connected to a building. When creating a room the fields **rname**, **description**, **connecting building** can be be filled. The fields room name and connecting building are mandatory fields.

- [x] Possibility to delete not used rooms

- [x] The room name shall be unique, the description can be left empty

- [x] The fields **building** and **room** in the edit page of an item are connected to each other. So if the user chooses a building, he can choose from all rooms connected to this building

- [x] It is not possible to create a room on the fly. The room information is mandatory. 

- [x] The room field in the edit page of an item shows the room name and the description in brackets, for example 1.D22 (meeting room)

- [ ] We need to import the list of rooms attached to this ticket. (will be dealt with by separate ticket)

- [x] Discuss with Mike, Matus and Barbara Flaad what should happen with existing rooms which are not in the list. 
- Existing rooms and buildings are not deleted or changed. 
- Building names are changed manually. 

- [x] Include room information in CSV Export (also in Procurement)

- [x] Inventory helper: if the user scans a room he needs to select the building first and then the room.

- [x] search for room in inventory list

- [x] procurement rooms and building concept same as on items

- [x] update ERM diagram

IMPORTANT:
- Please use the blue columns.
- Do not import room lines with empty roomnr.

[20170612_Raum_Nr-Bez_Alle-2.xlsx](https://github.com/leihs/leihs/files/1068006/20170612_Raum_Nr-Bez_Alle-2.xlsx)

**Comment by nimaai** [comment]
@nadjaweisskopf Right now in procurement, when creating or editing a request you can either select an existing location (building + room + shelf) or enter some arbitrary text if you don't find what you are looking for in the dropdown. Should we do it in conformity with items, means allowing the user to first choose a building and then depending on that the room? I would prefer it like this.

**Comment by nadjaweisskopf** [comment]
- Procurement: building and room are selected instead of entered (not a freetext field anymore)
- Question for bflaad: shall the building and room be mandatory and shall we set a default? If we set a default, we need to set an empty room to "undefined" or an emtpy building to "undefined" or both to "undefined"
- It will be necessary to have a script general for instances
- ask mike regarding shelf as text field part of location or seperate

**Comment by nadjaweisskopf** [comment]
Answer from bflaad: 
1. it is ok, that the fields building and room are mandatory
2. if user chooses building = undefined, then the room is automatically set to undefined. No other rooms can be chosen.
3. It is ok, that rooms and shelfs are not visible inside the edit page of a building. 
4. When we get rid of all not needed buildings and rooms, she agrees that that rooms, which are not in the list, can be deleted from the items and written to the note-field.

**Comment by nimaai** [comment]
@nadjaweisskopf In regards to the migration of `procurement_requests`, I would suggest to:
1. put `room_id = NULL` and append value from `location_name` inside the `inspection_comment`, for all those requests which don't have a location assigned (`location_id = NULL`)
2. for all others to set `room_id` (and its building) to the newly migrated room (and building) according to the value of `location_id`.

OK?

**Comment by nadjaweisskopf** [comment]
from Matus: 
Bitte folgendes angucken:
- Item edit / create
- Inventarhelfer
- Procurement Request

verschiedene Kombinationen:
- Gebäude leer
- Raum leer
- Gebäude UNDEFINED
- Raum UNDEFINED
- etc. (edited)

**Comment by nadjaweisskopf** [comment]
Still to be done in procurement:
- Fields building and room are not mandatory
- When building is picked, undefined should be set automatically in room information or user can pick a specific room
- When neither building nor room is picked, in both fields "undefined" should be entered
- Field room is too long, after picking a building

Still to be done: 
Include room information in CSV-Export 

Check note "Answer from bflaad:" above, which answers some questions we had.

**Comment by nadjaweisskopf** [comment]
Create a new ticket for building cleanup

**Comment by nadjaweisskopf** [comment]
Ask Roger, if ok, if we sort according to the create date of the contract

**Comment by nadjaweisskopf** [comment]
**Test ok** 

- building undefined, room undefined: 283c6434-bfcc-511b-bca9-4529378ece7a
- building and room have been copied succussfully from old location fields
- List of rooms in Admin section


**Test nok or change of behaviour**

- When creating a room, user should be forced to choose a building. At the moment the field contains the first building in the list.
- When creating a room, the following bug exists: 1. create room and choose "Toni" as building. / 2. Save. / 3. Edit room / 4. The first room of the building is shown instead of "Toni"
- When saving a new item with the building and room information, the endless-loop appears. Saving is not possible. Modifying an item with new building and room information is ok. 

- Please set text "unbekannt" instead of "UNDEFINED" or shall do this manually?

**Comment by nimaai** [comment]
@nadjaweisskopf  For the next testing session please also test the following:
- packages
- value/picking list

**Comment by nimaai** [comment]
> Please set text "unbekannt" instead of "UNDEFINED" or shall do this manually?

@nadjaweisskopf Yes. The name of UNDEFINED building and every UNDEFINED room can be changed manually in the admin user interface.

**Comment by nimaai** [comment]
@nadjaweisskopf Henceforward we will use the term "general" instead of "undefined". "undefined" clashes with some meanings in our code base. That does not mean that we can't label such rooms/buildings as "undefined"/"unbekannt". This can be done in the later migration script.

**Comment by nimaai** [comment]
@nadjaweisskopf In regards to Your test results:

> If a user enters a room name in the edit page which doesn't exist, the text should be deleted when saving the item. Then the error msg. makes sense."

This has nothing to do with the building/room fields, but is a general setting of fields of type "autocomplete". Model field behaves the same way. If it is desired to change this behaviour, then we can do it, but I suggest in another ticket.

> Please set text "unbekannt" instead of "UNDEFINED" or shall do this manually?

Either that, or via the script which we will prepare afterwards, as it affects many rooms.

**Comment by nadjaweisskopf** [comment]
When creating a room, the user should be forced to choose a building. 
If user saves without choosing a building, we show an error.

**Comment by nadjaweisskopf** [comment]
When creating a room, the user should be forced to choose a building.
If user saves without choosing a building, we show an error.

**Comment by nadjaweisskopf** [comment]
**test nok:** In excel-export the UUID is exported instead of the name of the buildings and the rooms.

I will retest the whole feature on wed. or thurs.

**Comment by nimaai** [comment]
> In excel-export the UUID is exported instead of the name of the buildings and the rooms.

@nadjaweisskopf There is also a column "Location" (Ort), like it was before. The columns "Building", "Room", "Shelf" are more there by mistake. I can remove them. But, maybe one want these instead of "Location", because of their filtering possibilities...?

**Comment by nimaai** [comment]
@nadjaweisskopf I have removed building, room and shelf from export for now as they are in the "Location" field, as it was before.

**Comment by nadjaweisskopf** [comment]
@nimaai In the old export building, room and shelf were three different fields. Mike needs these three fields, instead of one location field.

**Comment by nimaai** [comment]
> ... instead of one location field.

@nadjaweisskopf instead of, or in addition to? because there was also a location column before...

**Comment by nadjaweisskopf** [comment]
@nimaai according to the export in production there was no location column.

**Comment by nimaai** [comment]
@nadjaweisskopf Yes, true. Ok, so I will replace it with the desired columns.

**Comment by nadjaweisskopf** [comment]
Yes OK, thanks

**Comment by nadjaweisskopf** [comment]
@nimaai I couldn't find any problems, all tests are good!
