### ISSUE TITLE
Take back for some items not possible

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#229]
HSLU has the following problem:

some items in one take back of one user (delegation) and from one time frame can not be taken back.
The error msg. in the debug-window says "model nr. 75 not found". Model nr. 75 is the last model of this time frame namingly "Timecode Synch, ACL 203 Clockit (V)". I checked the model and it exists and is part of the current pool. 

Strange behaviors: 
- Contract for this timeframe only shows a small number of items.
- Opening time frame is not possible, 
- opening calender is not possible,
- availability calculation spins endlessly

**Comment by nadjaweisskopf** [comment]
@hslu

Please follow the following steps to see if the problem persists. This is the most straight forward solution. If this does not work, we need a dump to reproduce the problem.

To take back this one buggy item V17121 in the database please try the following steps: 

1. First you need to know the correct reservation nr. You can find the reservation nr. by switching to the console in the browser and selecting the line with item nr. V17121 in the take back of this delegation
2. then change to the rails console (in production environment) and type
3. r = Reservation.find(id)
4. r.update_attributes(status: :closed)

**Comment by nadjaweisskopf** [comment]
@nimaai You can find the dump on the filer: filer.ad.zhdk.ch/Applications/Leihs/03_Bugs und Issues/HSLU/leihs_production.sql

I will push the ticket to the current iteration. As soon as you have a spare minute, please have a look what went wrong.

**Comment by nimaai** [comment]
The reason is that those reservations were set to `closed`, but `returned_date` was not set.

This should fix it:

```ruby
item_reservations = Item.where(inventory_code: ['V6331', usw...]).map { |i| i.reservations.closed.where(returned_date: nil) }.flatten
item_reservations.each { |r| r.update_attributes(returned_date: r.end_date) }

option_reservations = Option.where(inventory_code: ['31112.1', usw...]).map { |i| i.option_lines.closed.where(returned_date: nil) }.flatten
option_reservations.each { |r| r.update_attributes(returned_date: r.end_date) }
```

Notice: `['V6331', usw...]` and `['31112.1', usw...]`. They need to adjust these Item/Option lists accordingly.

**Comment by nadjaweisskopf** [comment]
Wrote HSLU to check ticket in github.
