### ISSUE TITLE
LDAP Problem with version 4

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#230]
Hi Guys,

I am having LDAP problems again. LDAP works without a problem as resolved by you in #210. But as soon as I set "ldap.is_default = true" I am receiving the following error:

`App 16074 stdout: Started GET "/session/authenticate" for 131.152.102.80 at 2017-06-01 13:45:37 +0200
App 16074 stdout: Processing by SessionsController#authenticate as HTML
App 16074 stdout: Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.5ms)
App 16074 stdout: 
App 16074 stdout: LoadError (Unable to autoload constant Authenticator::LDAPAuthenticationController, expected /home/leihs/leihs-4.0.0/legacy/app/controllers/authenticator/ldap_authentication_controller.rb to define it):
App 16074 stdout:   app/controllers/sessions_controller.rb:33:in `eval'
App 16074 stdout:   app/controllers/sessions_controller.rb:33:in `eval'
App 16074 stdout:   app/controllers/sessions_controller.rb:33:in `authenticate'
`

Looks like the constant that was missing in the documentation is also missing from the authentication controller.

Thanks for looking into this.
Greetings from Basel,
Jan

**Comment by nimaai** [comment]
`ldap.class_name` must have the same value as in the respective part of the controller class name in https://github.com/leihs/leihs_legacy/blob/master/app/controllers/authenticator/ldap_authentication_controller.rb#L67, namely `LdapAuthentication`.

try: `ldap.update_attributes(class_name: 'LdapAuthentication')`

https://github.com/leihs/leihs/wiki/LDAP-configuration updated.

**Comment by JanWelker** [comment]
Jip. That works. Thanks for the quick reply.

Cheers,
Jan
