### ISSUE TITLE
Clicking on "User data" in top menu results in 500 Internal Server Error for LDAP Users

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#231]
Hi Guys,

there seems to be a problem with the "User Data" page in the top menu. It leads to a 500 if a LDAP user clicks on it:

`App 16074 stdout: Started GET "/borrow/user" for 131.152.102.80 at 2017-06-01 16:21:47 +0200
App 16074 stdout: Processing by Borrow::UsersController#current as HTML
App 16074 stdout: Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.6ms)
App 16074 stdout: 
App 16074 stdout: NoMethodError (undefined method `class_name' for nil:NilClass
App 16074 stdout: Did you mean?  class_eval):
App 16074 stdout:   app/controllers/borrow/users_controller.rb:4:in `current'`

I would suggest to disable this entry for LDAP users entirely since the LDAP access is read only anyways. There is no need for a LDAP user to update this information.

Cheers,
Jan

**Comment by nadjaweisskopf** [comment]
@JanWelker Hi Jan, does this problem still persist?
