### ISSUE TITLE
Leihs deployment in Docker

### ISSUE THREAD

**Issue by tilllt** [leihs/leihs#232]
Before i try to figure this out myself, are there any Docs on how to setup Leihs in a docker using the Ansible playbook deployment?

In this article the advantages of deploying in a docker are outlined nicely:
https://medium.com/@tech_phil/running-ansible-inside-docker-550d3bb2bdff

I think this would be great method to deploy Leihs quickly... any pointers?

**Comment by nimaai** [comment]
We have a test for deploying to a [LXD](https://linuxcontainers.org/lxd/) container, which can be found [here](https://github.com/leihs/leihs_deploy/blob/master/container-test/cider-ci/context.yml).

If and to what extent we will support other container solutions is not decided yet.

**Comment by tilllt** [comment]
My impression was that LXD is a Ubuntu centered container technology... While it's probably possible to run it i.e. on Debian or elsewhere, may I ask why you chose an OS specific solution?

**Comment by DrTom** [comment]
Technically it is LXC. We use it under LXD for convenience (network bridge and so on...). Docker is pretty much a no go. We run more than one service inside the container.

**Comment by tilllt** [comment]
Well, my interest was running a container with leihs. The whole LXD architecture is not available on Debian Stable. You can install a Snap version of LXD but i dont feel comfortable with that. Just so i can understand, how is "We run more than one service inside the container" an argument against Docker? Pretty much every Docker package runs multiple services, i.e. php or ruby, some kind of DB etc.

**Comment by DrTom** [comment]
The reason we use LXC/LXD is that it is very close to what we do when we deploy to a "normal" server. This gives us the possibility to test certain things, like deployment, the services play well together,....  We don't use LXC/LXD for deployment ourself. 
@nimai mentioned it because you asked for container solution. While it is not production ready it is the closest what is available at this time.
We have no incentives and no resources to support Docker. We would consider pull requests.

**Comment by Lejo1** [comment]
Have the plans changed in any way? Are there any docker deployment by someone?

I tried to deploy the project and sadly must say that's it's an quiet extravagant non flexible hard way to achieve the desired deployment. I never had so much trouble to deploy a project.
I understand that you don't need a different deployment on your own but I believe that this hurts the support of the project from other people as you would expect from an open source project. There is nothing like a simple development deployment or test environment.
This is especially hard as there is (as far as I know?) nothing like a "manual" deployment which would allow to understand the deployment. The only way seems to be to use the final ansible deployment or to "decode" ansible yourself.
An docker deployment would be a great way to achieve easy test environments and simple production deployments at once.

Please reconsider this idea!
