### ISSUE TITLE
Question when installing V4

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#233]
Question from Fabio Vecchio: 

**************
Guten Tag Frau Weisskopf

Ich habe Leihs installiert. Nach der Installation der Testumgebung kommt beim Zugriff mittels Browser folgende Password abfrage:
Was ist hier einzugeben? Habe in der Dokumentation nichts gefunden

Danke im Voraus für eine zeitnahe Antwort.

Beste Grüsse und frohes Schaffen!

Fabio Vecchio

**************

![v4_auth](https://user-images.githubusercontent.com/3356016/26869892-6a586094-4b6e-11e7-8d4c-95bb04ba2c05.png)

**Comment by nadjaweisskopf** [comment]
Hallo Herr Vecchio, haben Sie die Demo-Version installiert? Dann wäre die Doku bezüglich Rollen und Anmeldung hier zu finden: https://github.com/leihs/leihs/wiki

Ansonsten geben Sie mir bitte nochmals Bescheid.
Beste Grüsse
Nadja Weisskopf

**Comment by DrTom** [comment]
Können Sie `http://localhost`, oder`https://localhost` bitte ausprobieren?

**Comment by newrulez** [comment]
Guten Tag

Habe ich ebenfalls ausprobiert 
Habe das gleiche Problem.

![bildschirmfoto 2017-06-07 um 11 58 49](https://user-images.githubusercontent.com/5410878/26872981-b3858580-4b78-11e7-8c41-9e6ee2fd8a01.png)

![bildschirmfoto 2017-06-07 um 11 59 35](https://user-images.githubusercontent.com/5410878/26873000-bdddd3b6-4b78-11e7-91b9-6bce3733d806.png)

**Comment by newrulez** [comment]
Anbei noch die ausgabe des ansible deploys auf einer neuinstallierten debian 8 maschine mit python 2.7
[ansible_output.txt](https://github.com/leihs/leihs/files/1057795/ansible_output.txt)

**Comment by DrTom** [comment]
Wir sind recht erstaunt. Dieser Service, der sich da meldet, wird per default überhaupt nicht gestartet. 
Was sagt `git log` auf dem Superprojekt?
Wäre es möglich, dass wir uns auf der Maschine einloggen und uns umsehen?

**Comment by newrulez** [comment]
Guten Tag Herr Tom
Anbei noch das Git-Log
[git_log_leihs.txt](https://github.com/leihs/leihs/files/1057923/git_log_leihs.txt)

>Wäre es möglich, dass wir uns auf der Maschine einloggen und uns umsehen?
Ja logo. welchen key sollte ich adden.

**Comment by DrTom** [comment]
Unsere Keys liegen im Repo, hier sind die direkten links: 
 
https://raw.githubusercontent.com/leihs/leihs_zhdk-inventory/master/ssh_keys/drtom
https://raw.githubusercontent.com/leihs/leihs_zhdk-inventory/master/ssh_keys/nimaai

**Comment by newrulez** [comment]
TipTop.

Ich habe diese Keys hinterlegt. Ich habe Ihnen eine E-Mail an DrTom@schank.ch mit den Serverangaben gesendet.

Beste Grüsse und frohes Schaffen!

Fabio Vecchio

**Comment by DrTom** [comment]
Hallo,

wir haben uns kurz umgeschaut. Die services laufen tatsächlich nicht. Auch nicht jener der sich oben unter localhost eigentlich meldet?

Die nicht laufenden services stimmen nicht mit dem ansible log, das Sie uns geschickt haben überein. 

Wir haben uns kurz die configs angeschaut und sie weichen stark von unseren defaults ab (bezüglich ports, db Benutzer usw). 

Wie sieht Ihr inventory und die Configuration aus? 

Haben sie verschiedene Server deployed? 

Stammen die Outputs von verschiedenen Installationen?

**Comment by nimaai** [comment]
@newrulez please try to install again from scratch by following the updated [deployment instructions](https://github.com/leihs/leihs/wiki/Deployment#installing-from-scratch). Certain things (like services ports, etc.) should not be changed before running the deployment recipe. I tried my best to provide an exact step-by-step install procedure.

**Comment by nadjaweisskopf** [comment]
We will close this ticket. @newrulez Please reopen if problem still persists.
