### ISSUE TITLE
How are "Software" items used?

### ISSUE THREAD

**Issue by DerBachmannRocker** [leihs/leihs#234]
Can someone please explain why there is a separate category for software? I understand "Options" are bulk items that do not have individual inventory codes. In what way are "Software" items different from regular Items?

**Comment by nadjaweisskopf** [comment]
Hi, 
**Software** and **models** as well as 
**software licenses** and **items** are the same concept. The main difference are the fields. Normal items need different field information than software. We have implemented very specific fields with logic to the software. The necessity and the requirements have come from our it department and should fit most it departments of other schools and companies.

**Comment by DerBachmannRocker** [comment]
Thank you, valueable information! Can you please tag this thread as "question" for future reference?
