### ISSUE TITLE
IE 11 does not display the login form fields

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#235]
Hi Guys,

it looks like Leihs 4.0.0 does not display the Login window correctly when Internet Explorer 11 is used for browsing. Do you guys support IE?

Looks like I can not attach a screen shot here. I will send it as an attachment to Matus.

Thanks for your help,
Jan

**Comment by nadjaweisskopf** [comment]
Hi Jan
We support Safari, Chrome and Firefox. All our automated tests are done by firefox but the manual tests are done for Safari and Chrome too. 
Regards
Nadja

**Comment by JanWelker** [comment]
Hi Nadja,

thanks for the info. We will advice our users to use your supported browsers.

Greetings from Basel,
Jan
