### ISSUE TITLE
Image upload <4k

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#238]
Hi Guys,

I am trying to upload pictures for categories. I got the following generic error message in the Web GUI:

`
<!DOCTYPE html> <html> <head> <title>The change you wanted was rejected (422)</title> <style type="text/css"> body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; } div.dialog { width: 25em; padding: 0 4em; margin: 4em auto 0 auto; border: 1px solid #ccc; border-right-color: #999; border-bottom-color: #999; } h1 { font-size: 100%; color: #f00; line-height: 1.5em; } </style> </head> <body>  <div class="dialog"> <h1>The change you wanted was rejected.</h1> <p>Maybe you tried to change something you didn't have access to.</p> </div> </body> </html>
`

The real error in the Apache log tells me that I am not supposed to upload Images smaller than 4k:

`
ActiveRecord::RecordInvalid (Gültigkeitsprüfung ist fehlgeschlagen: Uploaded file must be at least 4KB)
`

Is there a reason why you are discriminating small pictures? If so would it be possible to tell the user so, too? The current error message in the GUI is not very telling.

Thanks for your kind help,
Jan

**Comment by nadjaweisskopf** [comment]
![error_small picture](https://user-images.githubusercontent.com/3356016/27787546-6149207a-5fe5-11e7-8a76-7d51bcf38c45.png)

Uploaded a file which was 1KB

**Comment by nadjaweisskopf** [comment]
Solution: we will discard the limitatio of small pictures in the code

**Comment by nadjaweisskopf** [comment]
Delete the model constraint

**Comment by DrTom** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/b4381f9f28bcd04a8ed22bcd554f7183bac51dd3

**Comment by nadjaweisskopf** [comment]
On staging this problem still persists. I tested a 2k png-file.
