### ISSUE TITLE
"Create new item" shows empty page

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#239]
Hi Guys,

I am trying to create a "new item" (Gegenstand) of an existing model. The "Create new Item" page does not show the expected form to enter the "items" details but a blank page with only the "Save Item" button.

The Apache log does not show any errors or strange entries. What information do you need to debug this problem?

Cheers,
Jan

**Comment by nimaai** [comment]
Please go to the `psql leihs` console and check what is there in the `fields` table:

`select * from fields;`

**Comment by JanWelker** [comment]
Hi Matus,

thanks for your quick reply. The 'fields' table is empty:

leihs_production=# select * from fields;
 id | data | active | position 
----+------+--------+----------
(0 rows)

Cheers,
Jan

**Comment by nimaai** [comment]
That's the cause.

Try this:
```
cd /leihs/legacy
su leihs-legacy
export PATH=$HOME/.rubies/ruby-2.3.3/bin:$PATH
RAILS_ENV=production bundle exec rake app:db:create_fields
```
I will fix it in our deployment recipe. You can then have a look and adopt yours accordingly.

**Comment by JanWelker** [comment]
Hi Matus,

thanks for the quick solution. It works. Thanks. Please be aware that I am not using your Ansible Playbooks. The problem can be on my site, too. I will look into this.

Thanks again,
Jan

**Comment by nimaai** [comment]
@JanWelker please check out the last commit and integrate it into your recipe. Also please take a look at this recent bugfix: https://github.com/leihs/leihs/commit/e709f09d6c3c8c1e282cc50790610ab74e6c0cfa

**Comment by JanWelker** [comment]
Thanks I have added it to my recipe.

Cheers,
Jan

**Comment by nadjaweisskopf** [comment]
I'll set this to accepted - has been tested by Jan.
