### ISSUE TITLE
Login Page removes parts of the Password

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#240]
Hi Guys,

The Leihs login page seems to delete parts of the password that the user already entered when one switches between the Username and Password field using the tab key.
This does not happen always but it happens often.

Cheers,
Jan

**Comment by nimaai** [comment]
I cannot reproduce it with Google Chrome Version 59.0.3071.86 (Official Build) (64-bit) on https://demo.leihs.zhdk.ch.

What browser do you use and can you provide the exact steps to reproduce?

**Comment by JanWelker** [comment]
I am using Firefox ESR 52.1.0 (64-bit)

Steps to reproduce:
1. Enter your user name on the login page
2. Enter your password on the login page
3. Hit enter _really fast_ after you entered your password

Result: You will visually see how something removes most of the password. Only 3-4 characters represented by the dots are left.

Sorry for the weird issue but it happened with multiple people already.

Cheers,
Jan

**Comment by eins78** [comment]
- reproduced in a test scenario (by simulating keypresses)
- found the culprit: it's the BarcodeScanner
- problem: there is no Bug to fix, this is how the barcode scanner is supposed to work. If "Enter" is pressed less than 100ms after typing the last character of the password (or any input field, for that matter) *we can not distinguish between human and barcode scanner*

proposed solution with minimal changes to the specified behaviour:
If any input field has focus, the barcode scanner should not do anything!

- if the field has focus, the scanner plugin is not needed, the hardware already does what we want
- slight change (I think it is an edge case): If user first types something in an input field, then uses the scanner, the field is not cleared anymore before filling in the scanned text
- possible breakage: there might be some input fields that don't do anything on 'enter' and only work with 'submit' events – we should fix those anyhow.

**Comment by eins78** [comment]
There is one other option: the BarcodeScanner's delay could be shortened from 100ms – maybe there is a sweet spot between "long enough for the hardware" and "short enough so that a human can't type faster".

**Comment by JanWelker** [comment]
An solution with no impact for the bar code scanner users would be to add an switch for this functionality in the settings file. That way bar code scanner users can use the scanner as before. Other organisations that do not user bar code scanners could deactivate this functionality.

**Comment by nadjaweisskopf** [comment]
nadja test: everything, that could be scanner and manual field for input/enter. test also options fields in hand over.

**Comment by nadjaweisskopf** [comment]
tested ok: 
- global search
- Optionen mit und ohne Scanner
- Zurücknehmen mit und ohne Scanner
- Aushändigen mit und ohne Scanner


Test NOK:
Borrow section
case 2: (see printscreen)
1. Enter category "Audio"
2. hover over lines
3. The popup is not shown correcty when hovering over lines, where only a picture exists (no text)

case 2: 
1. Enter category "Beleuchtungstechnik"
2. set date filter to start: 21.7.2017 end: 21.7.2017
3. open calender for first line: 22" Touchscreen ...
4. calender does not open correctly - endless loop
5. When now hovering over models in the list, popups are not opened anymore. 
![case 2](https://user-images.githubusercontent.com/3356016/28411425-0149b7ca-6d41-11e7-9cbf-5bf61b4350c8.png)
