### ISSUE TITLE
Popups freeze when moving mouse over hand over, take back, visits, search overview

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#249]
When moving over items or users, the popups freeze and are positioned over each other, one still open even though the mouse is already on a next popup. The user then has to refresh the page, to be able to close the windows. Esc or clicking on the blank page does not help. 

Firefox version 52.1.1. (32 Bit), laptop Yoga 260, Windows 10

(on all laptops of Ausleihe-employees)

![popup-freeze2](https://user-images.githubusercontent.com/3356016/27642382-f0c5ab4e-5c1e-11e7-8af3-949fc36dd713.png)
![popup-freeze1](https://user-images.githubusercontent.com/3356016/27642384-f33b02de-5c1e-11e7-9082-ec3c19d92463.png)

**Comment by nadjaweisskopf** [comment]
Mail to Roger:
*******************
Hallo Roger

Wir haben einen Verdacht und glauben es könnte an der Touch-Funktionalität liegen. Beni wird morgen Vormittag bei Dir vorbeikommen und die Touch-Funktionalität abschalten. 

Ich bin morgen per Mail oder auf dem Handy erreichbar. 

Lieber Gruss und danke Beni!
Nadja

**Comment by nadjaweisskopf** [comment]
Hoi Nadja
 
Ja, der Fehler trat mit einem Firefox Update auf. Sie haben nun eine extra Version, nur für Leihs. So klappt es. Ich kann dir leider nicht sagen ab welcher Version dieser Fehler auftrat.
 
LG_Beni

**Comment by nadjaweisskopf** [comment]
Die Frage ist nun, ob dieser Update irgendwann auch alle anderen User betrifft. Dann müssten wir nämlich dieses Problem lösen. Ich warte auf eine Antwort von Beni.

**Comment by nadjaweisskopf** [comment]
nadja: test on yoga and newest firefox version if problem persists. Would be nice to know, from which version on this problem exists.

**Comment by eins78** [comment]
@nadjaweisskopf please tell when you have a device that can reproduce that bug, I have a few simple things I want to try out locally that hopefully could fix it without to much work.

**Comment by eins78** [comment]
@nadjaweisskopf konnte das Problem nachvollziehen. Das mehrere popups einfrieren kam zwar nur selten vor, aber es ist konsistent so, dass sie jeweils bei 'mouse-hover' erscheinen aber bei 'un-hover' nicht wieder verschwinden.

Grund: ein veraltetes jQuery-plugin (mit dem die popups erzeugt werden). Dem Quelltext nach hat es sehr rudimentären touch-support und kommt daher mit dem speziellen Gerät durcheinander (sowohl touch als auch mouse verfügbar).

Workaround: mit dem Finger den Hintergrund berühren (statt klicken!)

Echte Lösung: Plugin upgraden bzw anderes Plugin benutzen (die aktuelle Version verhält sich korrekt, braucht aber Anpassungen in unserem Code – kommt fast aufs gleiche hinaus wie ein anderes Plugin zu nehmen)

**Comment by nadjaweisskopf** [comment]
nadja Testen: überall wo Pupups verwendet werden, unter Manage (lending und Inventory) und Borrow. Auch Kalender testen. Yoga 260 auch testen!

**Comment by nadjaweisskopf** [comment]
Test NOK:
Borrow section

case 1:
- Enter category "Beleuchtungstechnik"
- set date filter to start: 21.7.2017 end: 21.7.2017
- open calender for first line: 22" Touchscreen ...
- calender does not open correctly - endless loop
- When now hovering over models in the list, popups are not opened anymore.

case 1: (see printscreen)
- Enter category "Audio"
- hover over lines
- The popup is not shown correcty when hovering over lines, where only a picture exists (no text)
![case 2](https://user-images.githubusercontent.com/3356016/28411679-dbe168e2-6d41-11e7-8a03-c1f086761cf7.png)

Further tests to come

**Comment by eins78** [comment]
notes:

- case 2 and 4 seem to be caused by (the same) style issue. needs investigation what is supposed to happen (scale images down or grow the popup)

- case 1 is a bug in handling the tooltips that causes a crash, case 3 likely same cause

**Comment by nadjaweisskopf** [comment]
@eins78 Please can you inform me, when I can retest the bug fix? Thanks.

**Comment by nadjaweisskopf** [comment]
nadja: ask mike/roger/barbara if it is ok, if we only show 1 picuture in the modellist in the borrow section

**Comment by eins78** [comment]
@nadjaweisskopf fixed version now on staging.

**Comment by nadjaweisskopf** [comment]
@eins78 we still have a strange behaviour. If I hover over the model lines, some popups don't show. The models above this model that doesn't show now suddenly don't show anymore either. Check f.e. "Aktivlautsprecher-Paar Genelec 8020A"

**Comment by nadjaweisskopf** [comment]
@eins78 all tests are ok!
