### ISSUE TITLE
Do not lend retired items

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#250]
What I would expect: 

When scanning or entering an inventory code of an item which is retired, I would expect to see an error msg. saying "Dieser Gegenstand ist bereits ausgemustert und kann nicht ausgeliehen werden." / "This item is retired, and can not be handed out."

Current situation: 
It's possible to hand out an item which is already retired by scanning the inventory code. 
The item is not shown in list when entering the inventorynr.

Reproduce:
1. go to pool
2. go to hand over
3. scan a retired item
4. retired item is added to the hand over

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/841f660c0f0d4fd6bfa0833a6a59ee6f84b8076b
