### ISSUE TITLE
http://demo.leihs.zhdk.ch is not accessible

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#254]
Demo in Wiki is not accessible. I receive the msg. "sorry, but something went wrong..."

Link on page: https://github.com/leihs/leihs/wiki

**Comment by nimaai** [comment]
It's fine again: https://demo.leihs.zhdk.ch/

As cautioned at our GitHub homepage, the demo server is not stable. It is a part of our test process, so it may happen again and again that it is temporarily not available.
