### ISSUE TITLE
Search field needed in Admin Audits-section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#256]
The Audit in the Admin section does not suit its purpose at the moment. The user can only search with CTRL-F on the current page, then needs to scroll down and serach again with CTRL-F. 

- [x] We need a search field where the user can search at least in the following fields:
- name of user
- inventory code
- model name
- Changes: Please could you tell me which fields you track in the Audits - which fields are searchable?

- [x] The search field shall be connected with the date-filter.

- [x] Is it possible, to show the real names such as user name, room name, item nr., etc. instead of the UUID? Then the Audits page would be more readable to the user and it would make the search term easyer.

**Comment by nimaai** [comment]
> name of user

@nadjaweisskopf I suppose that they want to search for audited entries, where either the searched user details were changed *OR* the searched user performed a change on any audited entry, right?

**Comment by nimaai** [comment]
> Changes: Please could you tell me which fields you track in the Audits - which fields are searchable?

Currently we track changes of the following entities:

```
     auditable_type     
------------------------
 Workday
 User
 AccessRight
 ModelLink
 MailTemplate
 Holiday
 InventoryPool
 Attachment
 DatabaseAuthentication
 Group
 Item
 Reservation
 Partition
 Property
 Location
 Option
 ModelGroupLink
 Field
 Notification
 Contract
 Building
 Model
 Supplier
 Setting
 Accessory
 Purpose
 HiddenField
 ModelGroup
 Image
```
In case of an `create` or `destroy` action we persist the values of all attributes of the entity. In case of the `update` action, we only persist the old and new values of the changed attributes (which vary between the entities). That does not prevent us to search in other columns of the entities as well; they are "only" a `JOIN` away. But, the more of them, the slower. So, it's good we restrict ourselves to the most important ones right now, at least until we find a better, general solution for the audits feature.

Additionally, for every audited entry we record the ID of the user who performed the change.

**Comment by nimaai** [comment]
@nadjaweisskopf we currently group audits by the `request_uuid`, means changes that were performed together within one browser request. Example: submitting an order (see attached screenshot). Is this desired?

![screen shot 2017-07-26 at 11 49 07](https://user-images.githubusercontent.com/3205913/28615251-c3198fa4-71f8-11e7-9955-37a8fe824d60.png)

**Comment by nimaai** [comment]
On staging server searching with "Kmit" gives error.

**Comment by nadjaweisskopf** [comment]
test all entities. UUID on right hand side (changes) have not been made readable yet. Create ticket for further enhancements to readable UUIDs

**Comment by nadjaweisskopf** [comment]
Only found one small strange behaviour: 
How to reproduce:
1. Search filter: https://staging.leihs.zhdk.ch/admin/audits?search_term=weisskopf&start_date=02.08.2017&end_date=02.08.2017
2. Klick on a link on the left hand side, for example "Master Fine Arts"
3. I would have assumed that I get a result with all changes to this pool. 

![audits](https://user-images.githubusercontent.com/3356016/28919257-fecf0c7c-784c-11e7-8b2c-06ed407ae463.png)

**Comment by nimaai** [comment]
@nadjaweisskopf Fixed. The individual pages for particular entities maintain also the filter settings from the previous page.

**Comment by nadjaweisskopf** [comment]
@nimaai All tests are ok. Just one strange behaviour: When I search for "Nadja Weisskopf" only one result is shown - the one where the search string is an entered text in a item. If I search for "Weisskopf" then several results are shown - also the ones where I am the "changer". I would have expected the same results when searching for "Nadja Weisskopf"

**Comment by nadjaweisskopf** [comment]
When clicking on "Franco Sellitto" no result is shown: 
https://staging.leihs.zhdk.ch/admin/audits?search_term=nadja+weisskopf&start_date=03.04.2017&end_date=07.08.2017

**Comment by nadjaweisskopf** [comment]
When klicking on a name, the filters should not be cleared - in all cases.
