### ISSUE TITLE
Define behaviour when dealing with contributers (for leihs and madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#257]

**Comment by DrTom** [comment]
Notes for later: 

It isn't much about the licenses itself. It is about enabling us to react to certain problems which might arise in the future. I suggest to require contributers to submit to a CLA for the Leihs core libraries/services. Something similar to what MongoDB does.

**Comment by nadjaweisskopf** [comment]
@DrTom What is the solution of this ticket? Do I need to do anything?

**Comment by nadjaweisskopf** [comment]
We will decide what to do with pull requests when the next one arises.
