### ISSUE TITLE
Clicking on the arrowbar (categories with subcategories) causes nirvana link

### ISSUE THREAD

**Issue by newrulez** [leihs/leihs#259]
#### Expected behaviour
Should not be clickable with a hyperlink

#### Actual behaviour
Click on this arrrowbar causes an link to an error page.

#### Steps to reproduce
Click on a category with sub categories on the arrow bar

![bildschirmfoto 2017-07-05 um 14 16 29](https://user-images.githubusercontent.com/5410878/27863968-cf61aa48-618c-11e7-8afe-293aa182ecc9.png)

goes to this 404 page
![bildschirmfoto 2017-07-05 um 14 19 41](https://user-images.githubusercontent.com/5410878/27864008-0d0fc2da-618d-11e7-8a64-0953a90fe3bc.png)

#### Related issues
-

#### Specifications
- Leihs version: 4.3 (masterbranch, 4. July 2017)
- Browser version: every
- MySQL/PostreSQL version: Version Provided with ansible in Leihs 4.3 (masterbranch 4. July 2017)

**Comment by nadjaweisskopf** [comment]
@eins78 new ticket due to your chat msg. Please inform nimaai before you start with this ticket.

**Comment by nimaai** [comment]
This bug happens only if in the URL `session_storage=true`, means if the user has set/used filters in the model list.
