### ISSUE TITLE
Installing from scratch

### ISSUE THREAD

**Issue by tuxflow** [leihs/leihs#260]
#### Expected behaviour
I want to install leihs from scratch with this manual: https://github.com/leihs/leihs/wiki/Deployment

#### Actual behaviour
after "Clone, checkout origin/master and update submodules with Git:"
```
git clone --recursive https://github.com/leihs/leihs.git
cd leihs
git checkout origin/master
git submodule update --init --recursive

```
I want to copy the files: 
```
cp -R zhdk-inventory my-inventory
cp my-inventory/host_vars/leihs-v4-prod.yml my-inventory/host_vars/my-host.yml
cp my-inventory/prod-hosts my-inventory/my-hosts
```

but there is no leihs-v4-prod.yml 

is this the correct branch?

**Comment by nimaai** [comment]
The file you are looking for is `zhdk-leihs-prod.yml`.

I have corrected the deployment instructions.
