### ISSUE TITLE
Take back is case sensitive

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#262]
When taking back an option or an item by hand and typing the inventory code or option nr. in small letters, the item is not found. 

#### Expected behaviour
The inventory code or option nr. should be recognized no matter if it is entered in small letters or capital letters.

#### Actual behaviour
When entering inventory code or option nr. in small letters and pressing enter, the number is not recognised.

#### Steps to reproduce
1. go to take back
2. enter option nr. or inventory code in small letters --> press enter
3. error msg. appears saying item or option does not exist. 
4. enter the same nr. or code in capital letter and press enter
5. correct line is recogised and selected

#### Specifications
- Leihs version: 4.3
- Browser version: firefox

- [ ] Introduce constraints in DB

**Comment by DrTom** [comment]
@nadjaweisskopf Das ist jetzt auf master. "Das war recht sicher kein Bug. Das verhalten dürfte schon lange so gewesen sein.

**Comment by nadjaweisskopf** [comment]
Problem was Javascript. A contstraint was added.

- [ ] A contraint for the options is still needed.

test staging: take back field, hand over, optionen

**Comment by DrTom** [comment]
@nadjaweisskopf  Für die options können wir den Constraint nicht umsetzen. Es gibt schon mehrere options mit dem SELBEN inventory_code und viele davon sind auch null.
@nimaai wieso funktioniert das UX bei dem take-back für options überhaupt?  Oder funktioniert es nur zufällig weil selten oder nie zwei options mit dem selben inventory code zur Auswahl stehen?
 Oder ist es kaputt und keiner hat es bemerkt? 
```
select inventory_code, count(*) from options GROUP BY inventory_code ORDER BY count(*) DESC;
     inventory_code      | count
-------------------------+-------
                         |   294
 xlr5                    |     5
 xlr10                   |     5
 mjcverl                 |     4
 adajckmjm               |     4
 xlr2                    |     4
....
```

**Comment by nimaai** [comment]
It works because take back (as well as hand over) happen always inside a specific inventory pool. According to my research, there are no conflicting inventory codes for options inside a specific inventory pool:
```sql
select inventory_code, inventory_pool_id, count(*)
from options
where inventory_code is not null
group by inventory_code, inventory_pool_id
having count(*) > 1;

 inventory_code | inventory_pool_id | count
----------------+-------------------+-------
(0 rows)
```

We could at least introduce a constraint, which keeps it that way. By the way, in Rails we seem to have such a validation already (`app/models/option.rb`):

```ruby
  validates_uniqueness_of(:inventory_code,
                          scope: :inventory_pool_id,
                          unless: proc { |record| record.inventory_code.blank? })

```

**Comment by DrTom** [comment]
@nimaai I believe there is still a problem with your proposal because auf the many NULLs. 

I think we should make the unique. At least within each inventory pool and probably globally to have some consistency with the items as they are treated in the code many times as the same.

**Comment by DrTom** [comment]
@nimaai es geht nicht:
```
PG::UniqueViolation: ERROR:  could not create unique index "case_insensitive_inventory_code_for_options"
DETAIL:  Key (inventory_pool_id, lower(inventory_code::text))=(7221d339-0064-5bce-b06b-e49387470bd6, kabel 230v) is duplicated.
:       CREATE UNIQUE INDEX case_insensitive_inventory_code_for_options
        ON options (inventory_pool_id, lower(inventory_code));
```

**Comment by DrTom** [comment]
```
select lower(inventory_code), inventory_pool_id, count(*)
from options
where inventory_code is not null
group by lower(inventory_code), inventory_pool_id
having count(*) > 1;

  lower    |          inventory_pool_id           | count
------------+--------------------------------------+-------
 mikstat    | 040f275a-cbc2-5c21-9e98-8613fde1ccab |     2
 kabel 230v | 7221d339-0064-5bce-b06b-e49387470bd6 |     2
 kabel 230v | 3b25f313-a45e-5696-8f29-3cd715a22cc4 |     2
 kabel 230v | 040f275a-cbc2-5c21-9e98-8613fde1ccab |     2
```

**Comment by DrTom** [comment]
```
leihs_v4=# select * from options where lower(inventory_code) = 'mikstat';
                  id                  |          inventory_pool_id           | inventory_code | manufacturer |         product          | version | price
--------------------------------------+--------------------------------------+----------------+--------------+--------------------------+---------+-------
 1945579f-62a7-5cfb-93fe-9c2e9a5f984f | 040f275a-cbc2-5c21-9e98-8613fde1ccab | MikStat        |              | Mikrofonstativ           |         | 80.00
 dffd0de1-50fe-5545-863e-0acaae0db682 | 3b25f313-a45e-5696-8f29-3cd715a22cc4 | MikStat        |              | Mikrofonstativ           |         | 80.00
 0a2ec8eb-f094-5d81-9062-5f198f78be50 | 7221d339-0064-5bce-b06b-e49387470bd6 | MikStat        |              | Mikrofonstativ           |         | 80.00
 032ab1a0-c1da-599b-80f9-8dfc1f335f0c | 040f275a-cbc2-5c21-9e98-8613fde1ccab | mikstat        |              | Stativ Mikrophon einfach |         | 50.00
 6fb8d3a2-ac2d-56aa-a39e-afe2f10b2e33 | 8bd16d45-056d-5590-bc7f-12849f034351 | mikstat        |              | Stativ Mikrophon einfach |         | 50.00
(5 rows)
```

**Comment by DrTom** [comment]
@nadjaweisskopf hier die 4, die sogar innerhal eines pools problematisch sind: 
```
   lower    |          inventory_pool_id           | count
------------+--------------------------------------+-------
 mikstat    | 040f275a-cbc2-5c21-9e98-8613fde1ccab |     2
 kabel 230v | 7221d339-0064-5bce-b06b-e49387470bd6 |     2
 kabel 230v | 3b25f313-a45e-5696-8f29-3cd715a22cc4 |     2
 kabel 230v | 040f275a-cbc2-5c21-9e98-8613fde1ccab |     2
```

**Comment by nadjaweisskopf** [comment]
not relevant pools for Mike: "Verteifung CAST" and pools with "zx_"

**Comment by nadjaweisskopf** [comment]
Check, if the two parks Vertiefung CAST and Vertiefung FILM are not used anymore and do not have any open lendings. Check the 14 codes, which might be in contracts.

**Comment by nadjaweisskopf** [comment]
Answer from Mike: 
Wenn ich das richtig sehe, muss ich ja nur 3 der u.g. 6 Optionen umbenennen, dadurch werden die anderen drei ja einzigartig. Und das habe ich auch schon erledigt

**Comment by nadjaweisskopf** [comment]
@DrTom please migrate with next deploy - according to Mike everything is ok.

**Comment by nadjaweisskopf** [comment]
merge to staging. Then retest (nadja)
