### ISSUE TITLE
Revise the ZHdK offer for customer installations

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#264]
- Installation: Please review the offer for the **installation** of leihs on an **external system** of a customer smb://filer.ad.zhdk.ch/Applications/Leihs/01_Management/Offerten/leihs Offerte Produktiv-Installation.doc
- Upgrade: Please review the offer for the **Upgrade** of leihs on an **external system** of a customer smb://filer.ad.zhdk.ch/Applications/Leihs/01_Management/Offerten/leihs Offerte Upgrade.doc
- Test installation: Please review the offer for the **installation of a test environment (only one instance)** of **leihs on one of our servers** smb://filer.ad.zhdk.ch/Applications/Leihs/01_Management/Offerten/leihs Offerte Testinstallation.doc

**Comment by DrTom** [comment]
@nadjaweisskopf 

Die Quellen der neuen Dokumente sind hier: https://github.com/leihs/leihs_documentation/tree/master/sources/customer-management

Die daraus generierten PDFs hier: https://github.com/leihs/leihs_documentation/tree/master/customer-management

Die Quellen haben sicher noch viele Fehler. Das Format der PDFs kann man noch verbessern. Du kannst die Quellen editieren. Zum erzeugen der PDFs braucht es ein paar Tools, die sicher nicht auf deinem Rechner sind. Eventuell können wir das in Zukunft über den CI machen.
