### ISSUE TITLE
image dimensions in DB

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#265]
We currently don't know the dimensions (height/width) of any images (only the file size).
That makes handling them in the frontend way more complex.

After short talk with @nimaai the most simple way would be: read them all with ExifTool and save the image-metadata in a `jsonb` field (similar to Madek, but simplified/optimized).

**Comment by nimaai** [comment]
NOTE: make exiftool (gem) part of our repo

**Comment by nimaai** [comment]
@mfa No change in UI, but you can check it with `psql leihs` on the respective servers:

```SQL
SELECT metadata FROM images;
SELECT metadata FROM attachments;
SELECT metadata FROM procurement_images;
SELECT metadata FROM procurement_attachments;
```

And what you are especially interested in:

```SQL
SELECT metadata->'Composite:ImageSize' FROM images;
SELECT metadata->'Composite:ImageSize' FROM procurement_images;
```

Some `metadata` in `attachments` is missing, as the respective rows don't have `content` neither.
