### ISSUE TITLE
Please move items from ZHdK-Inventar to AV-Inventar

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#266]
Mail from Mike:

Folgende Gegenstände sollten bitte vom Besitzer-Park ZHdK-Inventar in den Besitzer-Park AV-Inventar verschoben werden:
 
Besitzer: **ZHdK-Inventar**
Ausgemustert: **NEIN**
Inventarrelevant: **WAHR**
Beschaffungsgruppe: **AV-Technik**
 
Nach meiner Kontrolle sollten da keine Pakete und keine Ausgeliehenen Gegenstände sein, welche Probleme machen ( zumindest keine, welche aus dem ZHdK-Inventar direkt ausgeliehen wurden)
 
Stand 21.Juli 2017 waren das 8887 Gegenstände.

**Comment by nadjaweisskopf** [comment]
@nimaai Matus, could you please move these items as first priority in test or staging first, then in production as soon I could check the list?

Thanks!

**Comment by nimaai** [comment]
```ruby
items = Item.where(owner: InventoryPool.find_by_name('ZHdK-Inventar'), retired: nil, is_inventory_relevant: true).select { |i| i.properties[:anschaffungskategorie] == 'AV-Technik' }
items.each_with_index { |item, index| puts "#{index}: #{item.inventory_code}"; item.update_columns(owner_id: InventoryPool.find_by_name('AV-Inventar').id, updated_at: Time.current) }
```

executed on TEST. @nadjaweisskopf please check

**Comment by nadjaweisskopf** [comment]
@nimaai test ok. Please move the items as soon as you can.

**Comment by nimaai** [comment]
DONE. 8912 items moved to "AV-Inventar".

**Comment by nadjaweisskopf** [comment]
informed Mike
