### ISSUE TITLE
Elements not translated

### ISSUE THREAD

**Issue by Oreonax** [leihs/leihs#268]
We find out that the following elements aren't translated from english (in any other language):

- "Startdate" + "Enddate" in Add to order calendar view
- CSV import & export not translated (the whole section)
- "Checked before" placeholder in /inventory
- "Hand Over Purpose" in inventory pool edition can't be translated by mixin word in french in the same order (I've created a new translation in the po file)

**Comment by nadjaweisskopf** [comment]
Please provide translations for the following: 

**Borrow section** - "Startdate" + "Enddate" in Add to order calendar view: D: "Startdatum"/"Enddatum" // E: Start date / End date

**Manage section** - CSV Import (whole page)
Laden Sie eine Komma-separierte CSV-Datei hoch (UTF-8 Kodierung). Jede Zeile muss einen Gegenstand beinhalten.

Akzeptierte Spalten:
inventory_code (zwingend)
model_id (zwingend)
...
Alle weiteren Kolonnen werden ignoriert. 

**Checked before date is already translated to German**

**Comment by Oreonax** [comment]
`"Startdatum"/"Enddatum"` -> `"Date de début"/"Date de fin"`

Actually the CSV Import translation work now (weird as I didn't change anything). Except one sentence : `Accepted columns:` -> `Colonnes acceptées`

`zwingend` -> `requis`

**Comment by nimaai** [comment]
The french translations are part of https://github.com/leihs/leihs_legacy/tree/mfa/translations. They will be available once the opened PR and this branch are merged to master.

**Comment by nadjaweisskopf** [comment]
All translations above are ok. I can't test the implementation of the french translations. We need to adjust the Email-Templates and provide the language settings in the Admin-section. I will create a ticket for these adjustments.
