### ISSUE TITLE
Adding HEIG-VD references

### ISSUE THREAD

**Issue by Oreonax** [leihs/leihs#272]
Our departement (Media engineering) will use leihs starting next semester, you can add our reference:

[School of Business and Engineering Vaud HEIG-VD](http://mei.heig-vd.ch/), Yverdon-les-Bains, Switzerland

Thanks in advance !

**Comment by nadjaweisskopf** [comment]
Thanks for the information! You are now listed in our Wiki: https://github.com/leihs/leihs/wiki
