### ISSUE TITLE
New feature Advanced Search / Erweiterte Suche

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#273]
The managers need an advanced search to search for a list of items with the same "properties". They need to search by

- all fields of the attribute "item" in combination with each other
- name, surname of the lender
- manager can access the fields he needs (similar behavior as in helper)
- manager can set back the search form
- manager can remove each search field seperately (similar behavior as in helper)
- The advanced search shall be a seperate page in the inventory section called "Advanced Search"/"Erweiterte Suche", placed next to the "Helper". 
- All managers shall be able to access the advanced search. 
- The search results shall be listed the same way the inventory list is displayed: https://leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/inventory?filters=reset
- The list can be exported to Excel and CSV

Step 1: choose field by field
Step 2: Show all fields of an item
Step 3: Choose from to date or value higher than
Step 4: Not only item fields

**Comment by phiku** [comment]
@nadjaweisskopf Ich bin mir gar nicht mehr sicher, was wir bezüglich Optionen gesagt haben. Ich habe jetzt mal geschaut, ob ich die hinzunehmen kann, was eigentlich gut funktioniert. Aber sie machen in dieser Ansicht (bis jetzt) noch keinen Sinn, sie ja gar keine der Properties oder Attribute besitzen, welche man mit den Feldern filtern kann.

**Comment by nadjaweisskopf** [comment]
@phiku Ok, we can ask Mike and Barbara this afternoon if options should be listed too. I excpect a "no" from them.

**Comment by nadjaweisskopf** [comment]
Name: Erweiterte Suche / Advanced Search

- kein grösser / kleiner
- von bis Felder //ja
- Tabelle mit werten //nein, vorerst nicht
- frage sollen die meist verwendeten Felder schon eingeblendet werden? //immer leere Seite
- Verfügbarkeit ausblenden
- Inventarcode | Modellname //Sortierung nach Modellname
- Export unverändert
- Buttons sollen da sein oder nicht? / Zeiltleiste? //Buttons ja, kein Gegenstand kopieren, keine Zeitleiste, kein löschen
- Pakete ebenfalls aufführen
- scannen soll möglich sein? z.B. im Inventarfeld? //nein, kein Inventarcode
- SW auch anzeigen? //ja
- Sollen Optionen angezeigt werden? //ja

**Comment by phiku** [comment]
@nadjaweisskopf Ich bin mir nicht mehr sicher, aber ich hab in Erinnerung, dass Optionen nicht angezeigt werde sollen. Was denkst du?

**Comment by nadjaweisskopf** [comment]
@phiku Ich hab auch in Erinnerung, dass Optionen nicht angezeigt werden weil sie nicht inventarrelevant sind aber oben habe ich das anders vermerkt. Ich frage zur Sicherheit nochmals nach und gebe Dir Bescheid.

**Comment by phiku** [comment]
@nadjaweisskopf Mir ist noch aufgefallen, dass beim Export die Inhalte von Paketen nicht exportiert werden. Ist die Regel folgende:

"Exportiere alle Items des Suchresultats, ausser solche, die in einem Paket enthalten sind." ?

**Comment by nadjaweisskopf** [comment]
@phiku Optionen sollen nicht angezeigt werden.

**Comment by nadjaweisskopf** [comment]
@phiku Ich käre das ab. Für die Inventur scheint mir müssten die einzelnen Gegenstände ebenfalls exportiert werden. Das wurde aber nie vermisst. Ich gebe Dir Bescheid.

**Comment by nadjaweisskopf** [comment]
nadja: Pius fragen, ob Export mit oder ohne Paketgegenstände. Ansicht entspricht nicht dem Export.

**Comment by phiku** [comment]
Wir haben ja gesagt, wir möchten bei der Expertensuche eine Ansicht ähnlich zu den Globalen Suchresultaten. Das heisst es gibt keine aufklappbaren Models. Ich habe die Packages auch gerade aufgeklappt. Das könnte wie folgt aussehen (siehe Attachment). 
![bildschirmfoto 2017-08-31 um 11 26 23](https://user-images.githubusercontent.com/16756048/29916601-84a234de-8e3f-11e7-9ac0-ccae5cfebb38.png)

**Comment by nadjaweisskopf** [comment]
@phiku I just spoke to Pius. He says didn't miss the package items in the exported excel but says it would be nice if they were exported. It would have to be very clear in the excel though, that the items belong to a package.

**Comment by nadjaweisskopf** [comment]
@phiku The list on the printscreen looks ok at first glance. As soon as we have a prototype to show on a testserver let me know. Then b. flaad and Mike could test the prototype during my holidays.

**Comment by nadjaweisskopf** [comment]
@phiku Test results:
1. Is it possible, to keep the filter settings when coming from the edit item page back to the expert search?
 ...
