### ISSUE TITLE
Make usage of procurement more efficient

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#275]
inspectors and requesters want to expand the request lines and edit the fields directly on the overview page instead of editing a request in a new page. The inspectors and requesters then stay focused on the category rather than focussing on a requester. 
- When collapsed, the request lines need to show the most important information (same fields as in current implementation) When expanded, all fields of a request are shown.
- The fields are editable and viewable according to the user rights.
- Each line needs to be saved seperately

**Comment by eins78** [comment]
tasks:

- [ ] make edit form inline expandable
- [ ] persist expand state in url param/history
- [ ] make "leave detection" work on closing the line (instead of closing tab/navigating away)
- [ ] make sure saving works

**Comment by eins78** [comment]
@nadjaweisskopf 2 questions
- should the current edit form (single page) still be usable/reachable at all (e.g. open in new tab), or should "expanding the line" should be the only way?

- currently the form "alerts" for confirmation if the way was changed but not saved. I think this behaviour would stay, but be triggered when closing the inline-form (otherwise there might be changes in a collapsed line that might be forgotten). Ok?

**Comment by eins78** [comment]
@nimaai backend: 2 new actions ([dummy](https://github.com/leihs/leihs_legacy/commit/5388d62e58957ee6ba41ef96eebcc7523415f1ce))
- `edit` gives us the edit form standalone (for PJAX)
- `update` does a single update

currently there are only "batch" actions for viewing/editing and updating.

**Comment by nadjaweisskopf** [comment]
@eins78 @nimaai 
2. question: yes, the alert should stay. Do we have the possibility to show in colour which lines have not been saved? For example show the save button in orange, if not yet saved?
1. question: We need to discuss the further functions before we go on. I don't think we should keep the single page but we need more user interactions on the main overview, such as adding a new line for a category. At the moment only the inspectors have the possibility to add a new request through the green + on each line of the category on the main overview. All users should have this feature, if we get rid of the single page. We can discuss this next week.

**Comment by nadjaweisskopf** [comment]
questions: 
1. shall more than one line be expanded? NO
2. Only one line can be edited at a time.

**Comment by nadjaweisskopf** [comment]
@eins78 Please can you deploy the code to test or staging so i can show the current prototype tomorrow afternoon? Thanks.

**Comment by eins78** [comment]
@nadjaweisskopf first version is now delivered (on `test`). 
There is one open question (for the users): What should happen after a request is moved (via the action menu). Right now it's very basic: Moving replaces the line with the success message that is was moved, but it won't be in its new place until the page is refreshed. Like with the sums, we can offer a click-to-reload.
Another option would be to just always refresh after moving, but that could be inconvenient if several requests are moved and user has to wait for many potentially slow reloads.

**Comment by nadjaweisskopf** [comment]
@eins78 I will check this today and give you an answer.

**Comment by nadjaweisskopf** [comment]
- improvement for next ticket: When entering a higher amount of items, the sum is not recalculated.

**Comment by nadjaweisskopf** [comment]
We have created new tickets for small adjustments that are still to be done. I will accept this ticket.
