### ISSUE TITLE
Move items for AV-Services

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#277]
Alle Gegenstände welche:
 
-          Besitzer: Veranstaltungstechnik
-          Inventarrelevant: WAHR
-          Ausgemustert: NEIN

(Beschaffungsgruppe ist dieses Mal irrelevant)
 
Verschieben in Pool: temp_AV-Inventar
 
Stand Heute: 2791 Gegenstände

**Comment by nimaai** [comment]
To be executed:
```ruby
items = Item.where(owner: InventoryPool.find_by_name('Veranstaltungstechnik'), is_inventory_relevant: true, retired: nil)
items.update_all(owner_id: InventoryPool.find_by_name('temp_AV-Inventar').id)
```

**Comment by nimaai** [comment]
Done on PROD. 2762 items concerned.
