### ISSUE TITLE
Room-ticket - cleanup

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#278]
To clean up our inventory, ITZ and PZ need several adjustments to the current item-data.

- [ ] Every building should only be listed once in the list of buildings in the admin section (will be dealt with by separate ticket)
- [ ]  We need to import the list of rooms attached to this ticket. (will be dealt with by separate ticket)
- [ ] Delete all rooms, which are not in the list and copy room information to the note field
- [ ] ...

IMPORTANT:

Please use the blue columns.
Do not import room lines with empty roomnr.

**Comment by nadjaweisskopf** [comment]
@nimaai In two weeks Mike, Bf and I will meet and discuss the clean-up steps. Until then, nothing has to be done. I'll move this ticket to "important"

**Comment by neoheat** [comment]
cleanup necessary, different building

**Comment by nimaai** [comment]
@neoheat still work to be done?
