### ISSUE TITLE
reverse proxy: default hostname might be prod

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#279]
Problem: `https://test.leihs-v4.zhdk.ch` is pointing to `prod`!

Reason: DNS is pointing there, but the host is not configured anymore in any apache vhost so the default is served (first one, in this case prod)

Solutions:
1. don't serve "unknown" hostnames  (in this case `test.leihs-v4.zhdk` would 404) *or*
1. always redirect to "canonical" hostname (in this case `test.leihs-v4.zhdk` would 302 to `leihs.zhdk`)

**Comment by DrTom** [comment]
Ich habe jetzt kein redirect sonder eine page mit etwas blah balh, eingebunden. Redirects sind etwas tricky (mit dem Madek gateway habe ich da Stunden verbraten bis es tat) und ausserdem potentiell verwirrend.

**Comment by nadjaweisskopf** [comment]
@DrTom OK. And why don't we remove the page completely? Do we still need and want to keep it?
