### ISSUE TITLE
Rails 5 

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#281]
Rails 5.1. is out, we should at least try the upgrade to see what possible problems we might need to solve.

**Comment by nadjaweisskopf** [comment]
Borrow, Procurement, Admin sind grün. Manage ist noch rot.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/trees/7e9d14e1c58ee4ba34fdc66eb1f08785a5efdd84
