### ISSUE TITLE
Filter active/inactive pools in Admin section - show active pools per default

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#282]
In the admin-section in the list of inventory-pools the user should have the possibility to choose active, inactive or both pool-states by a drop down. Show default value "active".

**Comment by DrTom** [comment]
@nadjaweisskopf 

https://github.com/leihs/leihs_legacy/blob/ee77e376b5caac22a378d9aae6e5793828caa7df/engines/leihs_admin/spec/features/inventory_pools.feature#L141-L156

Anmerkung: 
* für "Search" gibt es glaube ich keinen Test; ich habe das testen so wie "Search" dann nicht so wörtlich genommen ;-) 
* Search vs Filter, der Button heisst "Search" und ich habe es dabei belassen; technisch gesehen wäre aber Filter korrekt(er); Im  Admin UI nicht so tragisch aber vielleicht einigen wir us irgend wann auf eine Variante für alle "Filter".

**Comment by nadjaweisskopf** [comment]
Das können wir gerne mal anschauen. Technisch ist es sicher ein Filtern... die Benutzeraktion ist aber "Suchen", wenn man den Use Case beschreiben will - denn der Benutzer sucht einen oder mehrere Gegenstände anhand Filterkriterien.... spitzfindig :-).
