### ISSUE TITLE
global setting overwrite

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#286]
Dear LEIHS gurus,

we noticed that one can set settings like the email template on admin-level and in the specific inventory. Can you please describe how LEIHS chooses which one to use? Is there a hierarchy?

Thanks and greetings from Basel,
Jan

**Comment by nadjaweisskopf** [comment]
Normally, inventory park settings are applied, than admin-settings. But we'll check the code to be sure in this case and in case of the email address of an inventory park.

**Comment by nimaai** [comment]
The mail template precedence rules are as follows:
1. inventory pool, specific language
2. inventory pool, all languages (joined together)
3. system-wide, specific language
4. system-wide, all languages (joined together)
5. `app/views/mailer/#{scope}/#{template_name}.text.liquid`
