### ISSUE TITLE
Linebreaks are ignored in model description

### ISSUE THREAD

**Issue by DerBachmannRocker** [leihs/leihs#287]
#### Expected behaviour
Description text of any model may contain line break characters for formating purposes (paragraphs). Entered linebreak characters are shown in "Borrow" view (Detail and Mouse Over), visible to the customer.

#### Actual behaviour
Linebreak characters are shown in "Edit Model" view inside the textbox as expected, no problem there. Linebreak characters are shown as whitespace in Borrow view for both Mouse Over and Detail text. If I check the page sourcecode with Firefox I can see the line break chars are still there, but not displayed.

This is a problem because I'd like to give detailed information to the customer. I have no formating options at all, which makes long text hard to read, and it is impossible to write headlines / paragraphs. I tried inline-HTML, which did not work. It becomes escaped and is shown to the user (probably for very good reason).

Suggestion: Modify CSS so it shows line break chars. Maybe the "pre" tag helps?
https://www.w3schools.com/cssref/pr_text_white-space.asp
Another possibility could be some primitive kind of wiki markup including bullet-lists, etc. which could be included in description texts.

#### Steps to reproduce
Press return key while entering description text for any model :-)

#### Related issues
-

#### Specifications
- Leihs version: Tested this just now with demo.leihs.zhdk.ch
- Browser version: Firefox 54.0.1
- MySQL/PostreSQL version: ?

**Comment by eins78** [comment]
@nimaai fixed. in new borrow it was correct already.

**Comment by eins78** [comment]
Note: Linebreaks are now shown, but only on the Model detail page. In the "mouseover" they are left out on purpose because for many models they would become very large.
