### ISSUE TITLE
Delete unsubmitted contracts in pool ITZ-Ausleihe

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#288]
Please delete all unsubmitted orders of the following pools:

- Vertiefung Interaction Design
- zx_Ausleihe Florhofgasse
- zx_AV-Ausleihe
- ITZ-Ausleihe

**************
Liebe Nadja
 
Ich wollte den ITZ-Ausleihe Gerätepark deaktivieren, das geht aber nicht. Es gibt folgende Fehlermeldung:
Gerätepark kann nicht deaktiviert werden, weil es Bestellungen oder offene Verträge hat.
Ich sehe aber keine Geräte und auch keine Bestellungen mehr im Gerätepark. Ist das ein Bug oder mein Bedienungsfehler?
 
Lg Barbara

**Comment by nimaai** [comment]
```ruby
ip = InventoryPool.find_by_name('ITZ-Ausleihe')
ip.reservations.unsubmitted.destroy_all
```
@nadjaweisskopf done on TEST, please check and deactivate the pool.

**Comment by nimaai** [comment]
@nadjaweisskopf done on PROD. you or they can deactivate the pools now.
