### ISSUE TITLE
location not shown in drop down

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#290]
#### Expected behaviour
In hand over and take back the location should be shown on the line. 

#### Actual behaviour
A number or date is shown instead of the location

#### Steps to reproduce
1. go to hand over
2. klick into drop down on item line
3. the location of the item is not shown

![thumbnail_bildschirmfoto 2017-08-21 um 12 12 07](https://user-images.githubusercontent.com/3356016/29516442-a1b9583a-8670-11e7-97ba-946bd9cd15ee.jpg)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7d926987a3717c6990c00095c318ca6b450b3389
