### ISSUE TITLE
Certain mail to users is not send out ( "order submitted", "deadline soon reminder")

### ISSUE THREAD

**Issue by JanWelker** [leihs/leihs#291]
#### Expected behaviour

- Confirmation mail should be send to client when "order submitted".
- "deadline soon reminder" should be send.

#### Actual behaviour
Both events do not trigger a mail to the user. The Admins do receive emails about these events.

#### Steps to reproduce
As a user "borrow" an item. This should trigger an email called "order submitted". This email is not send and no mail can be found in the logs.

The same problem can be reproduced on the  "deadline soon reminder" mail which is not send.

Other mail is send. The "declined" for example.

#### Related issues
I can reproduce the same problem on all our LEIHS instances. Other mail is send.

#### Specifications
- Leihs version: 4.0.0
- Browser version: FF 52.2.0
- PostreSQL version: 9.6

**Comment by nadjaweisskopf** [comment]
I sent an order in production and did not receive an order submitted confirmation! Please check if we have a general problem with mails for "unsubmitted orders" and "deadline soon reminder".

**Comment by nimaai** [comment]
In regards to "Deadline soon reminder" our log says:
```
Aug 27 03:00:41 zhdk-leihs-prod ruby[40214]: 550 5.1.1 <design.bellerive@zhdk.ch>: Recipient address rejected: User unknown in relay recipient table
```
The email address probably does not exist anymore...

After that error any further emails are not send to remaining users. I am fixing that, so that the error message for a particular email address is logged and the email sending queue processing continues.

**Comment by nimaai** [comment]
In regards to "order submitted":
- first of all the behaviour is not specified
- in code it is disabled: https://github.com/leihs/leihs_legacy/blob/3adc9a4369af8995aa532b46b51db94aa0c5dc34/app/models/reservations_bundle.rb#L429

**Comment by nimaai** [comment]
@JanWelker sorry, I was wrong in my previous comment. The behaviour is already correct in a sense that when sending an email to a user fails for example for "deadline soon reminder" (but for any kind of reminder), then it is just logged and one proceeds with notifying the remaining users. Perhaps You can give us the log from `journalctl -u leihs-legacy-cron.service`...?

**Comment by JanWelker** [comment]
@nimaai:
Reminding and suspending users...
Remind and suspend complete -----------------------------
Maintenance complete ------------------------
Sending a deadline soon reminder...
Deadline soon reminded ----------------------

**Comment by nimaai** [comment]
@JanWelker Right now, I have only one explanation: there are no users to be notified (for "deadline soon reminder"). You can check:
```
Visit.take_back.where('date = ?', Date.tomorrow).flat_map(&:reservations).group_by do |vl| { inventory_pool: vl.inventory_pool, user_id: (vl.delegated_user_id || vl.user_id) } end
```

**Comment by JanWelker** [comment]
> Right now, I have only one explanation: there are no users to be notified (for "deadline soon reminder")

Yep that is true. I thought I was testing the "order submitted" mail. Is that a different mechanism?

**Comment by nimaai** [comment]
> Is that a different mechanism?

As I mentioned earlier, there are no mails sent for submitted orders (although templates for them exist). There is also currently no possibility to change it.

**Comment by JanWelker** [comment]
@nimaai thanks for the clarification. Would it make sense to remove the unused template for submitted orders to avoid confusions?

**Comment by nadjaweisskopf** [comment]
We will check what is best to do.

**Comment by nimaai** [comment]
resolved through https://github.com/leihs/leihs/issues/537
