### ISSUE TITLE
SW: Quantity allocations for all license types

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#294]
#### Expected behaviour
The allocations should be available for all license types. 

#### Actual behaviour
The allocations can only be defined for a software with some specific license types. Not possible for "free" or for "single workplace". 

#### Steps to reproduce
1. go to pool itz-software
2. edit a license
3. choose the licenses "free" or "single workplace"
4. the allocations can not be defined
5. choose any other license
6. the allocations can be entered

To be done for ITZ (Tilo)

**Comment by eins78** [comment]
Example of quantity allocation 

![screen shot 2017-09-07 at 10 44 09](https://user-images.githubusercontent.com/134942/30154250-99fc2068-93b9-11e7-8792-0e3d8b42ba12.png)

It is possible to enter and save "invalid" data, so I suspect there are no constraints in the backend that would hinder enabling it for all types of licenses.

![screen shot 2017-09-07 at 10 44 26](https://user-images.githubusercontent.com/134942/30154306-d34ef8a4-93b9-11e7-9798-72b5013a2160.png)


Tasks

- [ ] Frontend: Adjust Form controller to always show allocation fields
- [ ] Backend: make sure it can be saved
- [ ] test

**Comment by phiku** [comment]
Done.
