### ISSUE TITLE
Import room list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#295]
Please import the list attached. If rooms already exist in the exact same spelling, then do not import a second time. All buildings in the list already exist in leihs.

If a conflict turns up, import the room from file. 

[20170612_Raum_Nr-Bez_Alle-2.xlsx](https://github.com/leihs/leihs/files/1259426/20170612_Raum_Nr-Bez_Alle-2.xlsx)

**Comment by nimaai** [comment]
@nadjaweisskopf There are more columns than needed in the import file. I basically need "building name" and "room name" for the import.

In case of "building name" it is clear: "Liegenschaft".

But what shall I use for "room name": "Raumnummer" ?

**Comment by nadjaweisskopf** [comment]
@nimaai building name = column **Liegenschaft** / room name = column **Raumnummer** // Beschreibung = column **RBez. Reservierung** (all the blue columns)

**Comment by nimaai** [comment]
@nadjaweisskopf and what should be done with those which don't have neither **Raumnummer** nor **RBez. Reservierung**?

**Comment by nadjaweisskopf** [comment]
@nimaai please don't import lines with empty rooms, no matter if there is a descirption or not.

**Comment by nimaai** [comment]
CSV file used for the import:
[import.txt](https://github.com/leihs/leihs/files/1274686/import.txt)

Command:
`ansible-playbook execute-script_play.yml -i ../zhdk-inventory/test-hosts -l zhdk-leihs-test`

**Comment by nimaai** [comment]
@nadjaweisskopf done on TEST. please check.

**Comment by nimaai** [comment]
Done on PROD.
