### ISSUE TITLE
Bug: Inventory -> Create Item -> Attachments -> Select File -> Nothing happens

### ISSUE THREAD

**Issue by phiku** [leihs/leihs#303]

**Comment by nadjaweisskopf** [comment]
@phiku are you working with firefox? With Safari and Chrome it works. This problem is known and really needs to be solved!

**Comment by phiku** [comment]
@nadjaweisskopf No, on Safari

**Comment by nadjaweisskopf** [comment]
Only when **creating** an item the attachment-button is not active. When **editing** an item the button works fine.

**Comment by nadjaweisskopf** [comment]
Please also check if a scenario exists. If not, please create scenario and test.

**Comment by phiku** [comment]
Done.

**Comment by nadjaweisskopf** [comment]
@phiku I will create a ticket to correct the error msg. when uploading other files than allowed.
