### ISSUE TITLE
Upload images is broken

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#304]

**Comment by nadjaweisskopf** [comment]
@DrTom Uploading images works 
- when editing an existing item
- in procurement in a request
- when adding a picture or an attachment to a model

It does **not** work when
- In a category when changing the picture: https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/categories/78920f6d-57c1-5231-b0c4-f58dcddc64cf/edit does not work 
- adding a tiff - but this is a different problem.

**Comment by DrTom** [comment]
OK, das ist weder der 4K Bug noch das Problem, das mit diesem Ticket eingentlich schon gelöst wurde :-( 

Wir bleiben auf diesem Ticket und ich schaue nach was los ist.

**Comment by DrTom** [comment]
This is resolved. 

As for the images in categories Probelm: https://github.com/leihs/leihs/issues/313
