### ISSUE TITLE
disabled editing of flexible field in prod

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#306]
Problem: our prod instance was broken by "invalid field definitions". This is exactly what the big red box on the edit form warns, but it still happened.

Short-Term solution: We disable the edit form by replacing the view with a static message that editing can only be done by developers, change request go to PO.
(Devs can try out changes on staging before applying to prod)

Note: can be delivered without a release.

**Comment by eins78** [comment]
ui proposal

<img width="1273" alt="screen shot 2017-09-05 at 11 21 31" src="https://user-images.githubusercontent.com/134942/30054479-7f3e6210-922c-11e7-9327-28b928f0f946.png">

**Comment by nadjaweisskopf** [comment]
Thanks. Could you please adjust the sentence? 

Editing..... system **a**dministrator if you need to adjust the fileds.

**Comment by nadjaweisskopf** [comment]
Will this be part of milestone 4.5.0?

**Comment by eins78** [comment]
@nadjaweisskopf Typo is fixed. This is not part of any milestone/release, in this special case I would just put it on the server manually. Reasons: a) we don't want it to be dependent on our next deploy b) we don't want to "kill" the feature in general (for other instances)

**Comment by nadjaweisskopf** [comment]
@eins78 yes ok. Perfect. Thanks

**Comment by nadjaweisskopf** [comment]
@eins78 Will you have a german version of the text?
