### ISSUE TITLE
Disable button after declining an order

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#307]
#### Expected behaviour
After I have declined an order in the manage section, I would not expect to see the functionalities "decline" and "edit" anymore. The button should only say "declined" without any other functionalities to choose. 

#### Actual behaviour
Only the functionality "approve" is removed. Both functionalities edit and decline are still visible. When I choose "decline" and then "edit", I get an error saying "The page you were looking for doesn't exist..." 

#### Steps to reproduce
1. go to pool - lending section
2. decline an order
3. decline the same order again, without refreshing the page
4. error pops up

<img width="1135" alt="bildschirmfoto 2017-09-06 um 14 29 06" src="https://user-images.githubusercontent.com/3356016/30111915-d4a0606c-930f-11e7-8225-1ad7200a6007.png">

**Comment by phiku** [comment]
Steps to reproduce:
1. Open pool -> Lending Section -> Orders
4. Reject an order
5. Edit the rejected order
6. Error pops up

**Comment by phiku** [comment]
Done.
