### ISSUE TITLE
Delete tabs "supplier" and "building" in manage section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#310]
Delete or hide the tabs  
- supplier
- buildings

They are not needed by the inventory managers. 

The inventory managers need the supplier especially for the guarantee period.

At the moment, I am not sure if a supplier-db is even wanted, it doesn't seem like it. At least the people I interviewed until now to not need further information in leihs. 
AV for example have all the repair-documents in Filemaker.

**Comment by nadjaweisskopf** [comment]
delete supplier and room tabs in manage section.

**Comment by nadjaweisskopf** [comment]
nadja: ask roger if suppliers should be created ad hoc

**Comment by nadjaweisskopf** [comment]
@nimaai no, suppliers should not be created ad hoc. We will delete the tabs. Suppliers are created in Admin section.

**Comment by phiku** [comment]
Implemented.

**Comment by phiku** [comment]
Demo: 

Tabs "Lieferant" und "Gebäude" sind nicht mehr vorhanden:
https://test.leihs.zhdk.ch/manage/inventory_pools/8bd16d45-056d-5590-bc7f-12849f034351/edit
