### ISSUE TITLE
Rails Error Handling

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#312]
#### Expected behaviour

As a leihs User, I want to see *more specific* reasons why something went wrong.
Like "The change was rejected: Unallowed content type"

#### Actual behaviour

In many places there is only a generic "something went wrong" page,
inline errors (like in alert messages) only show "the change was rejected" or even less.

Minor Sub-Issue: In many places error are show as HTML code.

**Comment by nadjaweisskopf** [comment]
Did we have more specific msg. with the older rails version? So this is new with rails 5?

**Comment by eins78** [comment]
@nadjaweisskopf We are using the default error handling (which is not enough). There were no changes in Rails, it's just mentioned because the framework provides simple hooks to make it better.
