### ISSUE TITLE
An existing image in a category can not be deleted/removed 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#313]
```
Sep 05 09:36:29 zhdk-leihs-staging ruby[89281]: ActiveRecord::RecordNotDestroyed (Failed to destroy the record):
Sep 05 09:36:29 zhdk-leihs-staging ruby[89281]: app/controllers/manage/categories_controller.rb:77:in `update_category'
Sep 05 09:36:29 zhdk-leihs-staging ruby[89281]: app/controllers/manage/categories_controller.rb:34:in `update'
```

**Comment by DrTom** [comment]
from https://github.com/leihs/leihs/issues/304

@nadjaweisskopf  wrote: 

It does **not** work 
- In a category when changing the picture: https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/categories/78920f6d-57c1-5231-b0c4-f58dcddc64cf/edit does not work 
- when adding a tiff - but this is a different problem. 


@drtom amends: 

Uploading an image works (verified on staging). 
It is the removal of the exisitng image which is broken.

**Comment by DrTom** [comment]
Das scheint ein Rails 5.x problem zu sein. 

`
  accepts_nested_attributes_for :images, allow_destroy: true
` 

im Categories Model

**Comment by DrTom** [comment]
Noch ein kleines Nebenproblem: man kann eine Kategorie mit Image nicht mehr löschen. Das war zu erwarten. Aber: er sagt trotzdem, dass die Kategorie gelöscht worden wäre. Da stimmt etwas generell im Controller nicht.

**Comment by DrTom** [comment]
Hier ein Rails 5 bug dazu https://github.com/rails/rails/issues/25198

**Comment by DrTom** [comment]
Argh, einfach `:inverse_of` zu definieren wie oben im Ticket angemerkt reicht in diesem Fall nicht.  Es gibt einen ähnlichen Fall mit Attachments. Der wesentliche unterschied ist, dass die Images polymorphic sind. Ich gebe jetzt hier auf, da ich keinen schnellen fix sehe.

**Comment by nimaai** [comment]
@nadjaweisskopf Please test all possible image/attachment scenarios (add new, delete old, replace existing ones, etc.) in all relevant places (item, model, category, procurement category, procurement request, etc.). If this is the only place which is broken, we will find some dedicated solution for this particular case, so that we can deploy soon.

**Comment by nadjaweisskopf** [comment]
@DrTom @nimaai Same problem as in categories: deleting attachments in **models**
uploading attachments and deleting them in **items** works
software works
**procurement** works

So it seems we have the same problem in models as we have in procurement.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9529cf0f3799a0acffcde7794d49157baef8046c
