### ISSUE TITLE
Dynamic Reservations

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#318]
My notes from the refinement in German. I might have misinterpreted some things but the notes might still help: 

**Ausgangslage**
- Aktuell haben wir eine flache Struktur, es werden contract lines abgebildet mit versch. Stati ohne dass die Entitäten Order und Contract berücksichtigt werden.
- In Tabellen haben wir keine Entität „Bestellungen“ mehr, deshalb haben wir aktuell eine Query die diese Bestellungen nachbildet.
- Weil die Entität Order und Customer Order fehlt, müssen wir dyn. anhand der Abschickten Daten etc. sortieren.
- Matus möchte die Orders zurückhaben um die dyn. Query loszuwerden. Die Query ist komplex. Eine Änderung betrifft ganz viele Stellen wie Take backs, Aushändigungen, etc. Erweiterungen müssen immer komplett getestet werden statt am eigentlich Ort.
- Nachvollziehbarkeit im Code - Wenn die Businesslogik besser auf unser Datenbankschema mappt.
Historie - wann wurde was abgeschickt, genehmigt, etc.

**Problematik**
- Borrow: Purpose wird in der Ausleihe nicht angezeigt - die Gegenstände können nicht nach Purpose sortiert werden
- Borrow: Ich möchte als Student Gegenstände zu einem bestimmten Projekt löschen können
- Lending: Ich sehe in der Bestellung nicht, welche Linie für welchen Grund ausgeliehen wurde.
- Borrow: Zahlen in den Bestellungen sind verwirrend. Einmal heisst es „ich habe heute bestellt“ Einmal heisst es, „zwei Abholungen“
Bestellung dafür genehmigt hat, wäre es schön, es würde die vorbereitete Aushändigung in den Bestellungen beim User auch im Borrow bereich abbilden.
- Frage besprochen mit Entwil.team: bräuchte die Entität "Order"

**Zu klärende Fragen**
Für Ausleihe-Park: Möchten sie einzelne Linien bewilligen und ablehnen oder reicht es ihnen, wenn sie die Bestellung bewilligen oder ablehnen und die Möglichkeiten haben, die Bestellung zu ändern, z.B. einen Gegenstand zu löschen oder die Zeitspanne zu ändern.
- Lending: Frage an die Ausleihe: Müssen sie sehen, welche Bestellungen abgeschickt wurden am gleichen Tag? Also eine Sicht auf die abgeschickten Bestellungen statt auf alle Bestellungen desselben Tages gemeinsam?
- Frage and Ausleihe: Wenn ein User an zwei Tagen eine Bestellung aufgibt, werden die Bestellungen in zwei Linien angezeigt. Macht das Sinn?
- Frage an Ausleihe: In der Aushändigung können alle Linien einer Aushändigung gelöscht werden. Der User kriegt dann aber kein Mail. 
- Frage Mike: Will man in der Aushändigung den Zweck noch ändern können als Ausleihemgr.?
- Frage Mike: Wenn ich eine Aushändigung erstelle für den Benutzer, ohne dass der Benutzer eine Bestellung erstellt hat, kriegt der Benutzer dies nicht mit. Ist das ok so?
- Frage an Mike: purpose könnte vom ausleihemgr. ergänzt werden, ohne den eigentlichen purpose des Studenten abzuändern. 

**Einige Lösungsvorschläge**
- Order Entität und orderline, contract line einführen, statt alles über die Entität reservation und statt zu machen. 
- Table purpose könnte zu "order" umbenannt werden und reservation line könnte zu "order line" umbenannt werden.
- Wenn wir dann in Zukunft die Verfügbarkeit in der DB abbilden wäre es schön, dies nur in einer Tabelle abzubilden.

@nimaai How shall we proceed? Can you start with this project even though several important questions are still open? Can you wait until I am back or do you want to contact Mike and Roger to receive the needed answers in the next two weeks? Could you please make a list of the major steps to solve this ticket? 

- [ ] ...
- [ ] ...
- [ ] ...

**Comment by nadjaweisskopf** [comment]
Next steps: 
- testing (nadja) - borrow / lending / borrow time out / templates / purposes
- solve performance problems (matus)

**Comment by nadjaweisskopf** [comment]
Test results from 16.10.17:

- The list of orders takes longer to show than before (too long)
- tab "open orders" takes even longer if typing a search string into the search field
- what is the sort order in the list of orders? see print screen. I would expect the lines to be sorted according to their create date-time, if we have this information. 

![order list _ newest on top](https://user-images.githubusercontent.com/3356016/31602858-8b2b9adc-b25e-11e7-8fa1-3ea6cfd5d8d0.png)

- The list of orders says I ordered 4 days ago, but my orders are from today.
- Discuss with Roger: When lines have been deleted from hand over, the orders vanish 
- Button "Show more xy" on global search is missing

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/557f69bde15e8abe65ee418bcc7236d40137b088

@nadjaweisskopf:
1. fixed
2. fixed
3. created_at DESC
4. fixed
5. status quo. if change is required, let us make a new ticket.
6. could not be reproduced

**Comment by nadjaweisskopf** [comment]
Tests: 
1. List of all orders is very short. The list does not contain the same orders an in production.
