### ISSUE TITLE
New fields in procurement "Investitionen" oder "Beschaffung"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#319]
(In German)
Neues Wahlfeld "Investitionen" oder "Beschaffung"
Spezifikation: 
- **Berechtigung:** Diese Felder sind nur für Admins und Prüfer sichtbar
- **Berechtigung:** Die Felder sind in jeder Phase der Budgetierung für diese beiden Rollen editierbar bis zum Abschluss der Budgetierung
- **Felderwahl:** Bei der Wahl der Option **"Investitionen"** wird das Sachkonto und der Innenauftrag gewählt
- **Admin-Bereich:** Wie soll dies im Admin-Bereich abgebildet werden? Wird der Admin Sachkonten und Innenaufträge von Hand erfassen und jährlich aktualisieren? Gibt es je eine Liste Sachkonten und eine Liste Innenaufträge unter einem neuen Punkt im Admin-Bereich der heisst "Investitionen"
- **Felderwahl:** Bei der Wahl der Option **"Beschaffung"** wird aut. die Beschaffungskostenstelle der Kategorie zugeteilt. 
- **Admin-Bereich:** Im Admin-Bereich müsste bei den Kategorien ein zusätzliches Feld zwischen "Bild" und "Budgetlimiten" hinzugefügt werden, welches die Beschaffungskostenstelle beinhaltet. Diese wird vom Admin gepflegt. 

Titels in English: 
Investition = Investment
Beschaffung = Procurement
Sachkonto = Impersonal Accounts (Please reassure with with H.U. Gasser)
Innenauftrag = please ask H.U. Gasser
Kostenstelle = Cost Center (Please reassure with with H.U. Gasser)
Beschaffungskostenstelle = Cost Center

**Comment by eins78** [comment]
Notes: 

```
"Investition" / "Beschaffung"

New choice-field, not NULL, default is 'Beschaffung'

Beschaffung -> Kostenstelle from Cat.

Investment -> "Sachkonto" from Category, "Innenauftrag" entered by the inspector

The Sachkonto/Kostenstelle are entered in the Admin section per (Sub-)Category
```

**Comment by nadjaweisskopf** [comment]
Adjust CSV and Excel Export

**Comment by nadjaweisskopf** [comment]
- test CSV and Excel ok

**Comment by nadjaweisskopf** [comment]
@eins78 test ok
