### ISSUE TITLE
New drop-down field for inspectors and admins

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#320]
Inspectors need a dropdown to choose from default texts (like "Canned Responses") to prefil the "Comment" text field. The comment is still fully editable and behaves like before (visibilty/permissions)

Default Comments texts are entered by the Admin in the Admin-section. 

examples (can be entered as-is for zhdk):

```
Vorbezug
Verschoben da kein Budget vorhanden
Wird über Ausleihe ermöglicht
Bitte über Verbrauchsmaterial bestellen
Sammelantrag erfasst
```

**Comment by eins78** [comment]
tasks

- [ ] DB: store presets (`settings` or new table?)
- [ ] UI: dropdown to choose preset and prefil comment field

**Comment by eins78** [comment]
### admin UI

admin can enter default comments in setting (1 per line)

![screen shot 2017-09-18 at 16 36 49](https://user-images.githubusercontent.com/134942/30547488-b3fafcd0-9c8f-11e7-8b39-0bc14453fe3e.png)

### request form UI

new drop down, additional to textarea. both can be filled out or just one, as needed.
if both are filled out, values are combined with `;` (this is how users currently do it manually)

![screen shot 2017-09-18 at 16 36 18](https://user-images.githubusercontent.com/134942/30547503-bc188cd4-9c8f-11e7-9761-f2600602670d.png)

**Comment by nadjaweisskopf** [comment]
@eins78 test ok
