### ISSUE TITLE
Don't show percentage sign and budget limit if budget limit is not filled

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#321]
If budget limit in Admin section of the procurement module is not filled, the percentage sign and the budget limit on every category lign should not be visible.

<img width="1077" alt="procurement" src="https://user-images.githubusercontent.com/3356016/30154693-f827aa1c-93ba-11e7-9e62-360e25b873d6.png">

**Comment by eins78** [comment]
@nadjaweisskopf Edge Case: It is possible to configure the limits for some categories, but not all of them.
In case of the budget period, the "sum of limits" is only shown if **all** categories have a limit set.
For categories, should they be shown **a)** if anything is configured or **b)** if all of them are configured.

Screenshot shows variant **b**, where only the first category is configured.

![screen shot 2017-10-30 at 14 48 26](https://user-images.githubusercontent.com/134942/32174148-6ace565c-bd81-11e7-8696-52f3861e0627.png)

**Comment by nadjaweisskopf** [comment]
@eins78 I would say we go for solution **a**. Otherwise we implement magic which isn't clear to the user or we would have to explain on the settings of the categories why the limit is not shown in case not all are filled.
