### ISSUE TITLE
Staging -> Edit License ITZSW6993 -> Betriebssystem: Input broken

### ISSUE THREAD

**Issue by phiku** [leihs/leihs#322]
![bildschirmfoto 2017-09-12 um 12 20 49](https://user-images.githubusercontent.com/16756048/30327974-487048c8-97ce-11e7-9c96-5631891df093.png)

**Comment by nadjaweisskopf** [comment]
@phiku seems to be ok now? I couldn't reproduce this bug.

**Comment by phiku** [comment]
@nadjaweisskopf Should not be fixed. I only have made the "create item" stuff, not "edit". Was this on test or staging?
