### ISSUE TITLE
can't compile ruby on debian [ cause: ruby 2.3.3 incompatibilty with openssl1.1 ]

### ISSUE THREAD

**Issue by sonoprob** [leihs/leihs#335]
Hello,

Leihs doesn't want to compile ruby on a fresh debian, due to incompatibility of openssl library (1.1)
and leihs ruby version (2.3.3).

see also: https://github.com/rvm/rvm/issues/3862
"openssl 1.1.0 to Ruby 2.3.x and older are not compatible with OpenSSL 1.1.x on Debian"

On my fresh debian:
( Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux )
ruby 2.4.1p111
OpenSSL 1.1.0f

So, leihs installs its own ruby-2.3.3 , which expects the outdated [libssl1.0-dev / openssl (1.0.x) ]

• I wonder whether I can bump the version of ruby to 2.4, arguably a better option then trying to compile against a now outdated openssl library...

• Alternatively, how would I go about compiling leihs without openssl ?

end of log trace compiling ruby

"make[2]: Entering directory '/home/leihs-database/src/ruby-2.3.3/ext/openssl'", "compiling ossl_x509attr.c", "Makefile:301: recipe for target 'ossl_x509attr.o' failed", "make[2]: Leaving directory '/home/leihs-database/src/ruby-2.3.3/ext/openssl'", "exts.mk:209: recipe for target 'ext/openssl/all' failed", "make[1]: Leaving directory '/home/leihs-database/src/ruby-2.3.3'", "uncommon.mk:203: recipe for target 'build-ext' failed"]}
        to retry, use: --limit @/root/leihs/deploy/deploy_play.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
rentals2.snd               : ok=74   changed=30   unreachable=0    failed=1

**Comment by eins78** [comment]
@sonoprob It is not clear if to me if you want to install a development or production environment, but anyway a few pointers:
- Debian 9 (stretch) is not supported yet, we currently only use and test against 8 (jessie)
- In general, bumping the ruby version should be possible without any (additional) problems
- "compiling leihs without openssl" is not possible or desirable

We have started to update the ansible playbooks to work with the newest Debian. We have seen problems with OpenSSL as well, although different errors – so your problem might be solved soon or not ;)

**Comment by sono** [comment]
@eins78 thanks for your reply

> Debian 9 (stretch) is not supported yet, we currently only use and test against 8 (jessie)

I'm trying to install a production env, replacing our ancient leihs 1.9 installation with a modern one.

Following: https://github.com/leihs/leihs/wiki/Deployment ,  I read:
"General prerequisites - Server running Debian or Ubuntu (referred to as managed node from here on)."

To me, this implies Debian 9 is fine (up-to-date libraries), perhaps it would be good if there were a notice of this (<= jessie) ?

> In general, bumping the ruby version should be possible without any (additional) problems

How would one go about that, making sure to get the right ruby in the right place,
does it make sense, if Debian 9 is not supported yet anyway, and you have also seen troubles
with ssl ?

Smth else: I suspect a leihs 1.9 database cannot be resused / migrated in any way (different db formats)?

Thankfull for the pointer to jessie though, as I was starting to pull my hears out, well, almost :-)

I will retry tomorrow, installing on a 'fresh' Debian 8 vm seems the most promising then.

**Comment by sonoprob** [comment]
On jessie (a minimal version) I found that for this task [upgrade pyopenssl package] :

I had to:
apt-get install python-pip python-dev libssl-dev libffi-dev
pip install --upgrade cffi

In order to proceed, then the installation went through, and also compilation of ruby was successful, the process however stalls here (and I'm not sure what to do ....):

TASK [configure : get deploy info] **********************************************************************************************fatal: [rentals2.snd -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/bin/env: ?ruby?: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/root/leihs/deploy/deploy_play.retry

PLAY RECAP **********************************************************************************************
rentals2.snd               : ok=111  changed=46   unreachable=0    failed=1

thanks for a pointer :-)
not sure what it's trying to do here, but both machines can access each other using pubkeys

**Comment by eins78** [comment]
@sonoprob The last error you've described was caused by a workaround that is no longer needed, so I just removed it completely.
Also, the ruby version was bumbed in the deploy and there were no other problems, so it now works and is tested on Debian 9.

**Comment by eins78** [comment]
@sonoprob To answer your other question, importing from v3 is possible, see this playbook: https://github.com/leihs/leihs_deploy/blob/master/import-v3-into-v4_play.yml

**Comment by sonoprob** [comment]
@eins78 
thanks

We're still running leihs 1.9 though, 
and I think that might be a different case, or didn't the db format change from 1.9 to 3 ?

Regarding the other small problem, I had the ruby install dir to env PATH variable.

To resume, on the rentals node (not the controller):

# apt-get install python-pip python-dev libssl-dev libffi-dev
# pip install --upgrade cffi
echo "PATH=/home/leihs-database/.rubies/ruby-2.3.3/bin:$PATH" >> $HOME/.bashrc

I am now greeted with an admin screen, yoohoo 👍 
It may make be good to update your deployment description, as I've been working on cleanly installed vm's, so I suppose others would bump into the same issues ..

And I may bump into others, if I do,  I will keep you posted.

Thanks, pls. send a greet to both Ramon and Roman if you see them :-)

Jan Kees, Amsterdam

**Comment by sonoprob** [comment]
Ok, moving forward, I wonder the following,  when changing configuration
Should I (on the controller, deploying to the node) go through the same:
ansible-playbook -v -i my-inventory/my-hosts /root/leihs/deploy/deploy_play.yml

Or is there a way to only run certains tasks ?
For example, changing config to bind to our ldap server ?
(https://github.com/leihs/leihs/wiki/LDAP-configuration)

**Comment by sonoprob** [comment]
Nevermind, I found it after browsing a bit in the admin interface. Sorry for the noise :-)
