### ISSUE TITLE
API and Sync

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#339]
[Schätzung AD-Integration Use Case 1-3.pdf](https://github.com/leihs/leihs/files/1509212/Schatzung.AD-Integration.Use.Case.1-3.pdf)

**Comment by nadjaweisskopf** [comment]
1. Database rename
2. test nadja

**Comment by nadjaweisskopf** [comment]
Tests:
- close browser and reopen

**Comment by nadjaweisskopf** [comment]
@DrTom 
NOK tests with Roger:
- When adding an option to a hand over and changing the amount from 1 to 15 and then back to 4 the availability calculates endless - endless spinner
- check ticket "Cannot delete group-assignment in edit-user page #450". We could not reproduce this in production. So it might have to do with the renaming of the entitites?

**Comment by nadjaweisskopf** [comment]
@DrTom test nok: Create an order with delegation does not work - I get an error (works in prod): 
<img width="1038" alt="bildschirmfoto 2017-12-11 um 09 50 09" src="https://user-images.githubusercontent.com/3356016/33822670-b86ee730-de58-11e7-94d4-3e829de5b77c.png">

**Comment by DrTom** [comment]
@nadjaweisskopf war ein echter Bug, ist repariert und auf `tom.ruby` aufgespielt.

**Comment by nadjaweisskopf** [comment]
Refinement 9.1.18
- wann implementieren
- migration
- wie weiter
- Übersetzungen
- testen
- zwei Admins
- Passwörter für manuell erstellte (Reset Password via email)
- AAI oder AGW?! Bei Intranet anfragen.
- Planung für API - ZAPI Erweiterung mit Badge-Images (jpg) - motifier date des Fotos - 1 mal wenn neuer Benutzer kommt wird’s hochgeladen. es werden die richtigen Bilder angezeigt und jeder
- Bilder werden im Backend neu berechnet, damit die Bilder nicht zu gross sind (256MB)
- Skalieren der Bilder muss berücksichtigt werden (Image-handling)

**Comment by nadjaweisskopf** [comment]
- no new code at the moment
- wrote tests
- done: ci testing
- deployment to tom server pending

**Comment by gurmir** [comment]
Refinement 20.03.2018
o	API / Shiboleth / Admin Settings / Systems-Settings
•	System-Settings:
Wurde von Thomas eingestampft. Alte Umgebung wurde behalten. In der Testphase waren alle Tests grün, da man die Tests nicht in der Produktiven Umgebung (Produktion) testen konnte. Somit konnte auch nicht getestet werden ob Fehler auftreten und somit war das Risiko viel zu Gross.  --> Eventuell werden wir in Zukunft gezwungen sein, etwas für die System-Settings zu entwickeln. Aber bis dahin ist das Projekt gestoppt. Anmerkungen der Entwickler im Allgemeinen Settings sind immer schwierig aufwendig zu programmieren und der Aufwand dafür kann sehr schwer eingeschätzt werden. 
 
•	Shiboleth:
Log-in geht wirklich nicht (Switch-AI) SSO. Technisch hätte dies von Switch umgesetzt werden können, wurde aber nicht wirklich umgesetzt. 
Cookies underscore-shift ist weg. Dieser konnte nur von der ZHdK-Seite deaktiviert werden. Berechtigung an Änderung bei Switch ist gesperrt. 
Wenn der Browser geschlossen wird, ist das Cookie-Weg. 
 
SwitchAi ist optimal für reine CH-Hochschulen
Thomas fixte die Möglichkeit sich bei einer Leeren DB einzuloggen, die danach automatisch einen User angelegt hat. Probleme bestehen aktuell in Kombination mit anderen Applikationen (nähere Details bei Thomas)
 
Shiboleth ist optimal für internationale Hochschulen (EU, UK und USA). Die Setting Möglichkeiten werden hier aber auch grösser.  Bugfix (kleine Fixes und changes) Browsertests können nicht gemacht werden. Bei Log-in werden Cookies abgerufen um zu schauen ob ein Cookie vorhanden ist. Im Test wurde ein Header gesetzt. Shiboelth-Dienst macht auf dem Apache ein Request. Regression die Thomas gemacht hat fällt nun auf.

Bei E-Mails hat man vergessen den Sensitive Index zu setzen. UID hätte man noch problemlos beheben können. LDAP schreiben (Combine von User - bei Migration lowercase Migration. Thomas weiss noch nicht welcher User geopfert wird.

**Comment by nadjaweisskopf** [comment]
1 Erweiterung der ZAPI um den Zugriff auf Ausweisbilder.

1.1 Ähnlich der bestehenden Photo-URL (Parameter für konsistentes
Farbprofil, ev Skalierung, Crop usw).

1.2 Auslesen von "last modified" bevor das Bild überhaupt herunter
geladen werden muss. Von uns aus gesehen reicht z.B. wie bei der
Photo-URL der bestehende Header (wir würden das dann mit HEAD vorher
holen). Dem PHP Team ist es eventuell lieber wenn diese Info auf andere
Weise geholt wird damit weniger Requests verursacht werden. Wenn sie uns
das so Zugänglich machen werden wir es wie gewünscht verwenden.


Das obige kannst du dann so an Franziska weitergeben.


Das Gespräch mit Michael hat mich noch anderweitig erleuchtet. Die ZAPI
hat alle Informationen die wir brauchen. Auch jene über Benutzer und
Gruppen. Daher ist es zu überlegen, ob wir überhaupt LDAP ansprechen
oder nur die ZAPI.

Wir hätten gerne die Umsetzung auf Ende April. Michael muss schätzen. 
Fallback gäbs, ist aber unschön und aufwändig.

**Comment by nadjaweisskopf** [comment]
Auftrag: Umgang mit Passwörtern

**Comment by gurmir** [comment]
Die neue Admin-Umgebung auf der Testumgebung getestet:
Einige Links funktionieren noch nicht. 
Beispielsweise:
- Procurement erscheint bei mir im Header, ist aber nicht verlinkt. 
- Lending verweist auf Inventory
- Statistics haben keinen Link hinterlegt.

Alle anderen Links verwiesen auf den korrekten Pfad und funktionierten problemlos.

**Comment by gurmir** [comment]
Wenn ich dem Testbenutzer die Admin-Rechte weg nehme erscheint diese Meldung:

![error_message_test](https://user-images.githubusercontent.com/37148448/41025947-84e5335a-6973-11e8-9c3c-d53d57556d1a.png)

Dies ist zwar korrekt, aber ziemlich unschön. Idealer wäre eine kurze Message, "This Section is only for Administrator". Und Fetch Error klinkt auch nicht sehr schön.

**Comment by nadjaweisskopf** [comment]
ldap-connection to be developed before we start with the groups.

**Comment by nadjaweisskopf** [comment]
**Intermediate test result**
- I don't understand this text: "The application with **programming interface** to administrate this instance of leihs." Just say "The application to administrate this instance of leihs."
- Why does "Audits legacy" have the appendix "legacy" and the other links, which link to the old leihs don't?
- In tab Users, the type "org" in the filter is only meaningful to us. But I need to think about a better word.
- Question regarding the filter: "customer" is a role, which is used in a pool. Could a user exist, which does not match the list of filters and therefor is not shown in the list?
- Do I understand correctly, that users which are flagged as manual and do not have an org-id will not be deleted?
- Why would I create an API-Token for a user?
- In basic properties, write "first name" and "last name" instead of "firstname" and "lastname"
- In the user-legacy, when editing the user, we saw the rights belonging to the user. These are missing in the new user page. We were glad to see this information in the past. 
- Do I need to enter an org_id when creating a user? I'm not sure what we discussed.
**Delete User**
- Can we remove the "delete" button on users, which can not be deleted - such which have a contract?
- The coloured texts when deleting a user are very hard to read. Especially for colour blind people this will be a challenge. Please use darker colours at least for the yellow text. 
- Please write the following text: "Deleting this user is not possible if this user is associated to contracts or other entities."
- Write: Related data of this user will be transfered, respectively re-associated with the user entered below. Leihs itself will be consistent after this operation.
![bildschirmfoto 2018-06-20 um 08 57 58](https://user-images.githubusercontent.com/3356016/41642243-0e7166b2-7468-11e8-908c-09139850cde7.png)
- If I delete a new, by hand created user, I get an error:
![bildschirmfoto 2018-06-20 um 09 17 15](https://user-images.githubusercontent.com/3356016/41643180-d38c86f0-746a-11e8-98fa-2d302de365b2.png)
--> resend request
![bildschirmfoto 2018-06-20 um 09 18 25](https://user-images.githubusercontent.com/3356016/41643225-ea548eb4-746a-11e8-9439-9d0399b87e12.png)

**Comment by nadjaweisskopf** [comment]
@DrTom I have created new tickets for all the above enhancements or bugs. Priority according to sort order in lane https://github.com/orgs/zhdk/projects/1. 
Please move the tickets your working on or have fixed to the lane current.

**Comment by nadjaweisskopf** [comment]
Aktueller Stand: Synch der Gruppen über die ZAPI gibt die Gruppen und die User.
