### ISSUE TITLE
Only show active pools in dropdowns of helper and expert search

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#343]
#### Expected behaviour
Dropdowns in helper and expert search should only show active pools. 

#### Actual behaviour
Dropdowns show all pools, even deactivated ones. 

#### Steps to reproduce
1. go to inventory section
2. go to helper and expert search
3. select the fields responsible department and owner
4. the inactive pools are shown too

**Comment by nimaai** [comment]
@nadjaweisskopf I can't reproduce this. All pools shown in the dropdown are active.

**Comment by nadjaweisskopf** [comment]
@nimaai yes you're right, sorry. I must have been mistaken.

**Comment by nadjaweisskopf** [comment]
nadja: check sort order, if not ok then create another ticket

**Comment by nadjaweisskopf** [comment]
@nimaai I can't see a logic in the sort order on staging.

**Comment by nimaai** [comment]
@nadjaweisskopf The same order as in DB.
