### ISSUE TITLE
HSLU LDAP Issues after Upgrade from 3.45.1 to 4.5.1

### ISSUE THREAD

**Issue by HSLUwem** [leihs/leihs#344]
Hi

After updating LEIHS from Version 3.45.1 to 4.5.1, login via LDAP is not possible.

#### Expected behaviour
Successful login to LEIHS via LDAP and Active Directory.

#### Actual behaviour
After entering the login data, an error appears directly (We're sorry, but something went wrong).
The update has been done according to this guide: https://github.com/leihs/leihs/wiki/Deployment#upgrading-from-v3-to-v4
The LDAP configuration was made using this documentation: https://github.com/leihs/leihs/wiki/LDAP-configuration

Unfortunately, I have no log entries in the "production.log" and in the "ldap_server.log", which would take me forward. 
- production.log is attached...
- ldap_server.log is not even created...

After the LDAP guide you should be redirected to "/authenticator/ldap/login". However, we will be redirected to /authenticator/hslu/login. This may help to pinpoint the problem.

#### Steps to reproduce
It is difficult to reproduce the current problem accurately. However, we could provide a remote session for analysis.

#### Specifications
- Leihs version: 4.5.1
- Browser version: Firefox 55.0.3 and Microsoft Edge 38.14393.1066.0
- MySQL/PostreSQL version: 5.7.19 / 9.6.5
- Ubuntu: 16.04.4

Thanks for your help!
Martin

[production.log](https://github.com/leihs/leihs/files/1358642/production.log)

**Comment by eins78** [comment]
@HSLUwem in leihs v4 we use the normal system-logging instead of the text files, you can find the log in systemd's journal. 
Example command: `journalctl -u leihs*`

If you find the actual error, we maybe can help further.

**Comment by HSLUwem** [comment]
Here is the output from journalctl:

-- Logs begin at Tue 2017-10-10 12:37:42 UTC, end at Tue 2017-10-10 12:45:01 UTC. --
Oct 10 12:37:44 as76i systemd[1]: Started Leihs Legacy Cron Service Timer.
Oct 10 12:37:44 as76i systemd[1]: Starting Leihs Migration Service...
Oct 10 12:37:49 as76i ruby[1024]: Database 'leihs' already exists
Oct 10 12:37:49 as76i ruby[1024]: DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Oct 10 12:37:49 as76i ruby[1024]: Please use `config.public_file_server.enabled = false` instead.
Oct 10 12:37:49 as76i ruby[1024]:  (called from block in <top (required)> at /leihs/database/config/environments/production.rb:25)
Oct 10 12:37:50 as76i systemd[1]: Started Leihs Migration Service.
Oct 10 12:37:50 as76i systemd[1]: Starting Leihs Legacy Service...
Oct 10 12:38:01 as76i systemd[1]: Started Leihs Legacy Service.
Oct 10 12:38:02 as76i ruby[1393]: [1393] Puma starting in cluster mode...
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Min threads: 1, max threads: 2
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Environment: production
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Process workers: 1
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Phased restart available
Oct 10 12:38:02 as76i ruby[1393]: [1393] * Listening on tcp://localhost:3210
Oct 10 12:38:02 as76i ruby[1393]: [1393] Use Ctrl-C to stop
Oct 10 12:38:07 as76i ruby[1393]: [1393] - Worker 0 (pid: 1401) booted, phase: 0
Oct 10 12:43:48 as76i ruby[1393]:
Oct 10 12:43:48 as76i ruby[1393]: NoMethodError (undefined method `size' for nil:NilClass):
Oct 10 12:43:48 as76i ruby[1393]:
Oct 10 12:43:48 as76i ruby[1393]: app/controllers/authenticator/hslu_authentication_controller.rb:175:in `create_or_update_user_considering_ldap'
Oct 10 12:43:48 as76i ruby[1393]: app/controllers/authenticator/hslu_authentication_controller.rb:152:in `login'

**Comment by eins78** [comment]
I can see where it goes wrong, but since I am not familiar with the LDAP login in general I have no idea what the cause could be. Hopefully @psy-q has an idea as he originally implemented it.

Anyways, a few details I found out:
- The error happens very early, the LDAP connection return `nil` where we expect a list of users: https://github.com/leihs/leihs_legacy/blob/3e9bba57cb865568a039e940d5d2ea6c965fbfe5/app/controllers/authenticator/hslu_authentication_controller.rb#L175

- there is a AuthenticationController _just_ for your/HSLU setup, so it not using the "normal" LDAP method – which means it is not tested as well/at all because noone else is using it. 
  - This is the reason why you are redirected to `/authenticator/hslu/login`
  - Maybe you can try to use the normal LDAP login? You can see all auth methods for your instance in the admin interface, `https://leihs.exampe.com/admin/authentication_systems`

**Comment by psy-q** [comment]
There used to be some automated tests for this using an embedded Apache DS (I believe) that should have turned red if this stops working. I will take a look at the code but probably I don't remember much, it's been many years and today I'm already happy if I can remember what day of the week it is.

**Comment by psy-q** [comment]
It would be best to get into a debugger [here](https://github.com/leihs/leihs_legacy/blob/3e9bba57cb865568a039e940d5d2ea6c965fbfe5/app/controllers/authenticator/hslu_authentication_controller.rb#L172). Then:

  * Examine the contents of `ldaphelper.ldap_config[Rails.env]['search_field']`. Does it show the correct search_field? If it's blank, then something is going wrong reading the config into ldaphelber
  * Try the search without any filter: `users = ldap.search(base: ldaphelper.base_dn)`. Does this return any users? If so, something about the Net::LDAP filter mechanism might be fishy or perhaps its syntax has changed. Is a new version of Net::LDAP used now?

Those are the only ideas I have right now.

**Comment by psy-q** [comment]
@HSLUwem is there a way I could get access to the server to install a debugger and have a look, maybe?

Or could you add logging statetements to app/controllers/authenticator/hslu_authentication_controller.rb? If so, maybe you could try [this modified hslu_authentication_controller.rb](https://gist.github.com/psy-q/0151485c92ae15ccaebcf9f2653fd275), then restart the Rails server in question, try to log in via LDAP and see what log/production.log says about it.

**Comment by nadjaweisskopf** [comment]
Mail from Ramon: 

Hoi alle

Das Problem ist glaube ich soweit im Griff. Man sollte aber am
leihs-Deployment vielleicht noch zwei Dinge ändern, damit es repariert
bleibt.

Es gab drei Ursachen:

  1. leihs hat statt dem LDAP.yml-Configfile in /leihs/config/LDAP.yml
     dasjenige in /leihs/legacy/config/LDAP.yml verwendet.

  2. Der hslu_authentication_controller scheint Setting::ldap_config zu
     ignorieren.

  3. Die base_dn war so gesetzt, dass nach dem (erfolgreichen!)
     LDAP-Bind keine Benutzer gefunden wurden, also auch niemand
     einloggen konnte.

Ich habe jetzt:

  1. In /leihs/config/LDAP.yml den base_dn und den admin_dn mit
     Martins Hilfe auf den aktuellen Wert gesetzt.

  2. Das File aus Verzweiflung auch nach /leihs/legacy/config/LDAP.yml
     kopiert.

  3. In der folgenden Zeile Setting::ldap_config statt
     Setting::LDAP_CONFIG geschrieben. Ich glaube, das
     Setting-Objekt macht den Trick mit dem Upcasing heutzutage
     nicht mehr? Es scheint aber so oder so keinen Unterschied zu
     machen, er scheint den dort gesetzten Pfad zu ignorieren. 

https://github.com/leihs/leihs_legacy/blob/master/app/controllers/authenticator/hslu_authentication_controller.rb#L14

  4. Den leihs-legacy-Dienst neu gestartet.

Danach gingen die Logins wieder.

Ich würde empfehlen, zu schauen, welches LDAP.yml er nun definitiv
nimmt und warum er Setting::ldap_config zu ignorieren scheint. Wenn
dieser Teil funktioniert und das überall so deployed wird, müsste er mit
den aktuellen Werten aus /leihs/config/LDAP.yml später auch auf dem
Produktionssystem binden und einloggen können.

**Comment by nadjaweisskopf** [comment]
nadja: talk to HSLU and see if we need to make these adjustments or if HSLU would want to wait to decide about LaaS.

**Comment by nadjaweisskopf** [comment]
Are testing and will migrate their date in january
