### ISSUE TITLE
Neue Madek-Hilfe: Webspace einrichten, Domains  (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#345]

**Comment by eins78** [comment]
ticket im OTRS (B2)

**Comment by nadjaweisskopf** [comment]
Susanne geht nochmals auf Mischa Senn zu, falls keine Antwort kommt.

**Comment by nadjaweisskopf** [comment]
@eins78 An OTRS ticket exists. Max will check the OTRS ticket. I will close this ticket.

**Comment by nadjaweisskopf** [comment]
@eins78 OTRS ticket is still open. I am waiting for an answer from Mischa Senn and Christian Wildhaber to know what the status is. 

Further work for Max according to chat with Susanne today: 
- Copy content from gitbook to new website
- not all parts should be open to all readers. One part is closed, one open.
