### ISSUE TITLE
Admin kann User löschen. Abschliessen des Tickets von Michal (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#346]

**Comment by phiku** [comment]
https://www.pivotaltracker.com/story/show/132982429

**Comment by phiku** [comment]
@eins78 Kann das nicht Michal selbst machen? Er hat ja bei der I18n auch alles selbst gemacht im Webapp.

**Comment by nadjaweisskopf** [comment]
@eins78 We'll wait for Max for further information.

**Comment by nadjaweisskopf** [comment]
Fragen, was hier nun der Stand ist (Github geschlossen - Pivotal offen)

**Comment by nadjaweisskopf** [comment]
@eins78 Kannst Du bitte in Pivotal einen Kommentar hierzu eingeben? Dann schliesse ich das Ticket wieder. Danke
