### ISSUE TITLE
flexible fields

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#348]
Notes from refinement:

Flexible Felder
Core-Felder stellen wir sicher, dass sie da sind.

Wenn Felder hinzugeführt werden muss man bedenken, dass sie evtl. auch durchsucht werden sollen, in csv exportiert, importiert, etc.
Felder müssten dann auch in Abhängigkeit aufgeschaltet werden können.
Felder betrifft nur den Inventar-Bereich
Ist die Frage, ob Flexible Felder für Modelle und Gegenstände angewendet werden sollen oder nur für Gegenstände
Welche Felder sollen dann in der Ausleihe angezeigt werden.
fixe felder: label ändern, positiion, ein ausblenden, position, name ändern - alle einblenden können oder ausblenden - pro Gerätepark
Standard-Inventur für ZHdK oder für den einzelnen Gerätepark?
Geräte werden rumgeschoben, wenn dann nicht alle dieselben Felder verwenden, kann es Probleme geben. 

Vorschlag Entwickler / Nadja —> Fixe Felder
Mitarbeiter sind froh, wenn sie minimale Funktionen zur Verfügung gstellt kriegen und nicht. 

Inventurfelder in anderen Tools ansehen - 
Fixe Felder vs. Flexible Felder
Bei fixen Feldern würden die Schulen Felder melden, die per default ausgeblendet würden. 
Bei fixen Feldern wäre das System stabiler, vor allem aus Erfaung von Madek und die Tests wären einfacher, etc. 
Wir können Expertensuche und Inventarliste trennen. Inventarliste hat bestehende Felder, Expertensuche können nach allen Felder gesucht werden.

**Comment by nadjaweisskopf** [comment]
1. step: make flexible fields static - at least the mandatory fields.
2. step: introduce flexible fields for inventory-park.

**Comment by nadjaweisskopf** [comment]
@nadja if felds are added, should they be searchable?

**Comment by eins78** [comment]
@nimaai idea: instead of making the form non-editable by default, we could migrate the json values into the DB. Then the view only has to be changed minimaly (only show values, no editing); we don’t need any deploy config, and root/admins can still edit fields in the DB itself.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6cbccfd3e21d392432a681489de21f6beb999f60

All data related to fields is now only in the database. For the time being, the fields are read-only, except for activating/deactivating them. This action is only possible however for the fields which are not required. Adding new field and deleting and existing ones is also not possible.

Also, for our demo instance we use a dedicated dump now instead of factories.
