### ISSUE TITLE
[procurement] small fixes

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#349]
(extracted from #319)

- [x] Adjust CSV and Excel Export with the new fields 

---

- [ ] Inline-Edit: Close not changed requests when you choose a next request
    - [ ] only block nav for _changed_ forms
    - [ ] auto-close open and unchanged forms

---

- [x]  Do not show accounting fields on requests of requesters

> Only show accounting fields to inspectors, not requesters?

---

- [x] Inspectors should only be allowed to change the accounting type for requests of their your own categories

**Comment by eins78** [comment]
@nadjaweisskopf I made a new ticket for the fixes because they relate to different topics.
Also, I don't understand the last task, and can't find anything like that in my notes.
Maybe it related to the bug that requesters would see a dropdown (but no save button)? If so, it is obsolete because of the tasks before it: If all the fields are hidden, there can't be editable.

**Comment by nadjaweisskopf** [comment]
@eins78 Normalerweise sehen alle Requesters alle Felder der anderen, dürfen diese aber nicht ändern. Aktuell sehen sie aber die Accounting-Felder der anderen Kategorien nicht. Das ist nicht so schlimm, müsste aber noch korrigiert werden. Ich erfasse hierfür ein neues Ticket.
