### ISSUE TITLE
Keep filters in inventory list even after closing or saving an item

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#360]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When filtering the inventory list, editing an item and closing the item again, I need the filters to persist. 

Possible solution could be to open the edited item in a new tab. Then you still have access to the filtered inventory list.

#### Actual behaviour
When saving or closing the edit item page, the filters which were set before editing the item are deleted.

#### Steps to reproduce
1. go to pool - inventory
2. set filters
3. edit an item
4. close edit item page
5. you are rooted back to the inventory list but the filters are set back

Discussed with Roger and Mike

**Comment by nadjaweisskopf** [comment]
Ask Roger if category-filter in inventory list ist needed.

**Comment by nadjaweisskopf** [comment]
@phiku category filters are still needed by the inventory managers of the AV-Ausleihe. So please implemenent the categroy filter as well. Thanks.

**Comment by phiku** [comment]
@nadjaweisskopf Ok then I try to implement them today.

**Comment by phiku** [comment]
@nadjaweisskopf Ok the inventory list should now be 1:1 like before. There is only a little detail in the category menu which is different. The search term is not anymore shown explicitely below the search input.

**Comment by nadjaweisskopf** [comment]
@phiku when setting the filter "owner" I get an endless spin. Does this have anything to do with this ticket?

**Comment by phiku** [comment]
@nadjaweisskopf Yes thats a bug.

**Comment by phiku** [comment]
@nadjaweisskopf The reason is, before the refactoring, the package child items/licenses were loaded not until the package was opened. Now for the moment they are loaded immediately when the package parents are loaded, for simplicity. The problem was, the children were loaded at once, and therefore this were sometimes quite many (> 100) which caused the urls to load them to be too long for the browser. I have now a new version which loads them in chunks.

**Comment by phiku** [comment]
@nadjaweisskopf Builded a new release candidate: release: 4.9.0-RC.2. Deploying to staging now.

**Comment by nadjaweisskopf** [comment]
@phiku 
1. The model should not be deletable if items are attached. Button should not be visible. 
2. the spaces between the numbers are missing - 0 / 1 instead of 0/1 - can you provide a space in between? They're aasyer to read then.
3. Translations missing "No entries found" and "search category" --> see printscreen

![bildschirmfoto 2017-11-28 um 12 52 40](https://user-images.githubusercontent.com/3356016/33318477-12dde0c2-d43b-11e7-8f2b-a6126ac51647.png)

4. After closing choosing a category from the left category filter and closing the filter again, the filter is deleted. I think this behaviour makes more sense then the current behaviour in production, where the filter is kept but the user doesn't even see that the filter is still active. I need to check though that we do not have a scenario, which is not correct anymore. 

5. The list is refreshed with every string I type, even though the search result stays unchanged. Typing a letter in the search field of the category should not reload the list. 

6. Could you please place a space in between the text and the timeline icon / delete icon / copy item?

![bildschirmfoto 2017-11-28 um 13 43 43](https://user-images.githubusercontent.com/3356016/33320330-2e8a0470-d442-11e7-9970-220a7b8f1318.png)

**Comment by phiku** [comment]
4.9.0-RC.4 on Staging
