### ISSUE TITLE
Edit page with React and correct error msg. 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#364]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
The error-text should say:

**Das Modell** wurde gespeichert, beim **hochladen** von Bildern ist es allerdings zu Problemen gekommen. Nur Bilder kleiner als 8MB und vom Typ png, gif und jpg sind erlaubt.

Correct the button-name: "Modell bearbeiten" instead of "n bearbeiten"

#### Actual behaviour
The error msg. contains text parts which are incorrect. See attachment. 

#### Steps to reproduce
1. Edit model
2. upload a tiff
3. check error msg.  

#### Related issues
https://github.com/leihs/leihs/issues/311

#### Specifications
- Leihs version: newest
- Browser version: safari

![leihs_hochladen](https://user-images.githubusercontent.com/3356016/31438587-e976aaac-ae88-11e7-9f47-789ce7cb3302.jpeg)

**Comment by nadjaweisskopf** [comment]
@phiku Do we have to wait for react to solve this error-msg.problem? I'm not sure if we discussed this before.

**Comment by phiku** [comment]
@nadjaweisskopf Ja ich denke das macht erst Sinn das wieder anzuschauen, sobald Edit/Create Item fertig reaktifiziert sind. Sonst muss man es jetzt korrigieren und dann auch noch für die neue React Version.

**Comment by nadjaweisskopf** [comment]
- parse format of chosen language, send alway in same format. 
- Show in which format the user should enter the number (according to language)

**Comment by nadjaweisskopf** [comment]
item and license

**Comment by nadjaweisskopf** [comment]
@phiku load further inventory list when reaching the bottom of the page. Check if performance is better then.

**Comment by nadjaweisskopf** [comment]
@phiku The model should not be deletable if items are attached. Button should not be visible.

**Comment by nadjaweisskopf** [comment]
@phiku 

1. The sort order is not the same as in production. We have a scenario which describes the sort order: Scenario: Order of the fields when editing an item

2.

**Comment by phiku** [comment]
4.9.0-RC.4 on Staging

**Comment by nadjaweisskopf** [comment]
@phiku It looks as though the dates have vanished: last checked, invoice date

**Comment by phiku** [comment]
@nadjaweisskopf Da benötige ich etwas mehr Information.

**Comment by nadjaweisskopf** [comment]
@phiku I've updated the comment.

**Comment by phiku** [comment]
@nadjaweisskopf Ah ok, hoffentlich ist nur die Anzeige kaputt.

**Comment by phiku** [comment]
Fixes on Staging RC 5.

**Comment by nadjaweisskopf** [comment]
@phiku 
When I edit an item and change to "inventory relevant" YES, then choose a group and save the item, I get this popup: 

![bildschirmfoto 2017-12-05 um 09 04 45](https://user-images.githubusercontent.com/3356016/33597142-b9800e10-d99e-11e7-8fb1-ff963f889fc0.png)

**Comment by phiku** [comment]
@nadjaweisskopf Should be ok if the HD is not full. So I close it.

**Comment by nadjaweisskopf** [comment]
@phiku 
Test NOK with licenses: The link, which is shown on the bottom of the page is not shown correctly. The information "film4avz" should not be part of the link. But I'll create a new ticket for this to solve in next release.
