### ISSUE TITLE
First klick does not add the delegation user

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#367]
#### Expected behaviour
When handing over an item to a delegation user, the first klick when chosing the user shown add the user. 

#### Actual behaviour
When first klicking on the users name, nothing happens. When klicking on the users name the second time, the user is added and the hand over can be completed. 

#### Steps to reproduce
1. open hand over for delegation
2. select items and press on "hand over"
3. chose user from user list
4. first klick does not add user

#### Specifications
- Leihs version: newest
- Browser version: safari

**Comment by nadjaweisskopf** [comment]
might be a simple solution: don't expand when opening popup. Show list after first klick in user search field

**Comment by phiku** [comment]
Detail how to reproduce step 1:

1. Reiter Verwalten
2. Sub Reiter Benutzer
3. Dropdown Delegationen
4. Button Aushändigen
5. Zeilen auswählen
6. Button Aushändigen

**Comment by nadjaweisskopf** [comment]
Detail how to reproduce step 1: Or search in the "visits" for hand overs of delegation. There are several of them in pool "Ausleihe Toni-Areal".

**Comment by phiku** [comment]
@nadjaweisskopf Wird diese Funktionalität oft / mehrmals pro Tag verwendet?

**Comment by nadjaweisskopf** [comment]
@phiku ja, wird mehrmals pro Tag verwendet.

**Comment by phiku** [comment]
@nadjaweisskopf Auf Test sind irgendwie alle Delegationen leer bei "Aushändigen", z.B. 

https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users/0055ec61-a510-5614-9d7b-137e13f18f5e/hand_over 
![bildschirmfoto 2017-11-01 um 09 03 03](https://user-images.githubusercontent.com/16756048/32265521-a812d91c-bee3-11e7-8f38-24708b06fee6.png)

Wahrscheinlich sind diese alle veraltet. Wie kann man das wieder füllen?

**Comment by nadjaweisskopf** [comment]
@phiku 
Check this hand over: 
https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users/44ffe7d3-384d-5459-9881-1b7d24817a47/hand_over

Otherwise you can add models by typing a model name in the field "add/assign"

**Comment by phiku** [comment]
Delivered. The dialog is now mostly rewritten in React.
