### ISSUE TITLE
Display reject reason in list of rejected orders

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#374]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
As lending manager I need to see the reason why an order has been rejected.

#### Actual behaviour
Reason is not shown

#### Steps to reproduce
1. go to lending section of pool
2. open tab "orders/rejected"
3. reason is not shown

Implement for users: PZ (Roger and his team)

**Comment by phiku** [comment]
Aus Slack:

Ich muss für das Ticket https://github.com/leihs/leihs/issues/374 den Grund für eine Ablehnung anzeigen in der Liste der Orders. Kann es sein, dass der Grund gar niergends in der DB gespeichert wird, sondern nur in die Mail einfliesst? Der Parameter “comment” enthält den Wert, den man bei der Ablehnung eingibt. Ich finde aber nicht, wo der in die DB gespeichert wird.
```
  .../order.rb:
  def reject(comment, current_user)
    update_attributes(state: :rejected) and
      reservations.all? { |line| line.update_attributes(status: :rejected) } and
      Notification.order_rejected(self, comment, true, current_user)
  end

  .../mailer/order.rb
  def self.order_rejected(order, comment, send_mail = true, _current_user = nil)
    o = Mailer::Order.rejected(order, comment).deliver_now if send_mail
    title = (o.nil? ? _('Order rejected') : o.subject)
    Notification.create(user: order.target_user, title: title)
  end
```

**Comment by phiku** [comment]
Implemented.
