### ISSUE TITLE
Adapt leihs & Madek according to the new AGW test entries

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#375]
Mail von Michael Bürgi:

Hoi zäme

Ich habe nun die AGW-Testeinträge für leihs und madek erstellt. Bitte kontrolliert die Einstellungen im AGW-Admintool und passt sie selbständig an.

https://intern.zhdk.ch/?auth/leihstest
https://intern.zhdk.ch/?auth/leihstest/response
https://intern.zhdk.ch/?auth/madektest
https://intern.zhdk.ch/?auth/madektest/response

https://intern.zhdk.ch/?agw/admin

Viele Grüsse
Michael

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ff10de46b30e365ea8ea8a6e9b67612ff03a08a5

@mfa @drtom This was the best solution I could think of. The following sentence in the AGW admin interface made me decide to make the AGW login information protected:
"Jede Applikation besitzt einen eindeutigen Wert, der als zusätzliches Sicherheitsmerkmal dient. Dieses "Secret" ist wie ein Passwort zu behandeln."

I also made our STAGING instance to use the production AGW leihs entry.

If you find the stuff reasonable, we could make it same way in Madek too, otherwise let me know what to change.

**Comment by eins78** [comment]
@nadjaweisskopf ok for deploy
@nimaai It is slightly more complicated than needed, but we can easily change that once we need to manage more secrets.
I am not sure if `staging` shouldn't better use the `test` AGW as well, can also be changed later. Also we should change the secret as it was previously checked in…

**Comment by eins78** [comment]
(ref: this is how the master secret is configured during deploy right now: https://github.com/leihs/leihs_deploy/blob/c507d6a8cc194d886341ee14ddd942c14b9dbd49/bin/set-leihs-legacy-secrets)
