### ISSUE TITLE
mark groups with too many assignements in red

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#376]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When I check the groups in a pool I would expect to see on the overview which groups contain models which are overbooked.

#### Actual behaviour
The lending or inventory manager needs to edit a goup to see if the group has overbooked models.  

#### Steps to reproduce
1. go to pool 
2. access groups in manage section
3. enter a group which has more models assigned to a goup than available. 
4. The line inside the group is red but in the overview the manager does not get a hint. 

![bildschirmfoto 2017-10-17 um 08 36 07](https://user-images.githubusercontent.com/3356016/31650264-d5f37536-b316-11e7-916e-e85cf41c7bb3.png)

![bildschirmfoto 2017-10-17 um 08 40 45](https://user-images.githubusercontent.com/3356016/31650278-e83c972c-b316-11e7-9d18-2a6f05c73509.png)

**Comment by phiku** [comment]
Delivered
