### ISSUE TITLE
Availability numbers are not calculated correctly in inventory list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#378]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When listing Aluprofil 4Kant 3,2m 4cmx4cm in inventory list, I would expect to see the number 3/3 on the right hand side.

#### Actual behaviour
I see 4/4 for this item, even though one of these four items is retired.
The lending manager should see how many items are available to lend, which is 3 and how many are in stock and would be lendable which is also 3.

#### Steps to reproduce
1. go to pool Ausleihe Toni-Areal
2. go to inventory list
3. search for item Aluprofil 4Kant 3,2m 4cmx4cm
4. check the numbers

![bildschirmfoto 2017-10-17 um 09 21 57](https://user-images.githubusercontent.com/3356016/31651740-18558f44-b31d-11e7-95b4-940089d56f17.png)

**Comment by phiku** [comment]
Der Code ist jedenfalls folgender: 
```
  def in_stock
    @models.each do |model|
      @availabilities.push \
        id: "#{model.id}-#{current_inventory_pool.id}",
        total_rentable: \
          model
            .items
            .where(inventory_pool_id: current_inventory_pool)
            .borrowable
            .count,
        in_stock: \
          model
            .items
            .where(inventory_pool_id: current_inventory_pool)
            .where(retired: nil)
            .borrowable
            .in_stock
            .count,
        inventory_pool_id: current_inventory_pool.id,
        model_id: model.id
    end
    render :index
  end

```

**Comment by nadjaweisskopf** [comment]
Numbers on the right hand side should not change when changing the filters.
The second position (y) from  x / y should not count retired items.

What should the numbers say in inventory list?

x / y - total ausleihbar in diesem Moment / total ausleihbar generell (abzüglich ausgemusterte, aber mit nicht ausleihbaren/defekten/...)?

**Comment by eins78** [comment]
@nadjaweisskopf I changed the availabilty code to only count non-retired items. So this example now shows `3/3`. It did not break any other scenarios.
But I just now saw that you have assigned yourself; so I won't merge yet. But it can be looked at on `mfa.ruby.zhdk.ch` – if everything is at it should be it can be merged.

**Comment by nadjaweisskopf** [comment]
test ok on staging. Code from Max was implemented. 

I tested: 
- inventory list
- Calender
- time line
- borrow calender
