### ISSUE TITLE
Inform the lending manager about assignment problems in groups

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#379]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When retiring an item, I would expect to be informed if this retirement has negative consquences on a group. When saving the retired item I would like to have a warning saying: "Afer retiring this item the groups X, Y, Z, have too many assignments. Please correct the assignments of these groups." / "Nach dem Ausmustern diese Gegenstandes sind zu viele Zuteilungen in den Gruppen X, Y, Z vorhanden. Bitte korrigieren Sie die Zuteilungen dieser Gruppen.

**Comment by nimaai** [comment]
@nadjaweisskopf The item quantities for the partitions on the group page include also retired items right now. 

I assume we want to change that, right?

Do we also want to mark those group with red which have at least one partition which is "overbooked"? I mean this page: https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups

**Comment by nimaai** [comment]
And I have also noticed that the available quantity on a partition line does not consider allocations of the same model in other groups. It does so only if one adds a new partition for a group, before saving. It means that changing the allocations for a model across the groups does not change the available quantity.

**Comment by nadjaweisskopf** [comment]
@nimaai 
Yes, please add both solutions: 
1. The item quantities for the partitions should not consider retired items. 
2. If in one group the quantity is raised for model A and model A is also used in another group, then the overallocation should be shown immediately before saving. AND the other group, using model A should also be marked red (the group list https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups AND inside the group on the line of model A)

**Comment by nadjaweisskopf** [comment]
scenario!

**Comment by nimaai** [comment]
@nadjaweisskopf 

1. I think the available item quantities for an entitlement (partition) should also exclude items which are not borrowable, because the current availabilities in borrow currently exclude them. It we don't do that, then it may lead to unexpected and misleading information.

2. If I understand this requirement correctly then I would suggest not to do it, because (a) it practically never happens that 2 different users edit the partitions for the same model in 2 different groups and (b) it is not trivial to implement.

**Comment by phiku** [comment]
@nimaai Note: item_edit_controller.coffee wird nicht mehr verwendet.

**Comment by nimaai** [comment]
@nadjaweisskopf please see my proposal which was deployed to my server.

look at the tooltips. i have also ***excluded broken and incomplete items*** from the counts.

**Comment by nadjaweisskopf** [comment]
@nimaai I will check this tomorrow morning with Roger but I assume we keep it the same way as they defined it for lending/borrow - include broken and incomplete items.

**Comment by nadjaweisskopf** [comment]
@nimaai feedback from Roger: please 
- include the available items
- include broken items
- include incomplete items
- exclude not available item
- exclude retired items

**Comment by nadjaweisskopf** [comment]
@nimaai check model page and correct the max number - check if retired items are included (shouldn't be included)

**Comment by nadjaweisskopf** [comment]
@nimaai Feedback from Roger: Only not "not borrowable" and "retired" are not included. The rest is included. So we have the same behaviour in borrow and lending - this is correct.

**Comment by nimaai** [comment]
@nadjaweisskopf please check on https://nimaai.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups. ask also roger to check. 

i have also made links for groups on edit model page: https://nimaai.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/models/d2b4a8e7-ddc3-5444-9eec-ae866e0fcfd9/edit

**Comment by nadjaweisskopf** [comment]
@gurmir please can you test this ticket, thanks

**Comment by gurmir** [comment]
@nadjaweisskopf Test is already done. Test ok. No errors

**Comment by nadjaweisskopf** [comment]
@nimaai I got an error when trying these steps for the first time: 
1. created a model "testmodell nadja"
2. create six items for this model (2 borrowable, 1 broken, 1 incomplete, 1 retired, 1 not borrowable)
3. edit group "IAD Forschung"
4. add user "nadja weisskopf"
5. add model "testmodell nadja"
6. type 4 into field
7. save group
8. error

The second time it worked. 

<img width="1243" alt="bildschirmfoto 2018-05-02 um 16 09 30" src="https://user-images.githubusercontent.com/3356016/39528185-afecbb92-4e23-11e8-85cd-e74e9fa396c4.png">

**Comment by nadjaweisskopf** [comment]
@nimaai The error pops up again, when
- edit the group "IAD Forschung" again
- type 2 on the model "testmodell nadja"
- save the group
- edit the group "DMU Ton"
- add the model "testmodell nadja"
- save
- error pops up

<img width="1262" alt="bildschirmfoto 2018-05-02 um 16 16 02" src="https://user-images.githubusercontent.com/3356016/39528416-5427ee5c-4e24-11e8-9a14-c0371c4acd06.png">

**Comment by nadjaweisskopf** [comment]
@nimaai Another error, when
1. deleting the model line "Testmodell nadja" from the group
2. deleting my user "nadja weisskopf" from the list
3. saving the group
4. error

(safari)

<img width="1416" alt="bildschirmfoto 2018-05-02 um 16 34 49" src="https://user-images.githubusercontent.com/3356016/39529387-dd0c3eba-4e26-11e8-9e0d-cd0fabb0ec6f.png">

**Comment by eins78** [comment]
we analyzed the logs and could reproduce it, in a way…

we are 99% sure that you held down the `command` key while klicking on save, possibly in connection with the `shift` key.
this would cause the target of the form/save button to be opened as a link in a new tab, causing the 404 error. 
when pressing shift or having safari settings for it can cause new tabs to open in the foreground, maing it easy to overlook what happened.

- working on the edit page
```
195.176.xxx.yyy- - [02/May/2018:14:09:06 +0000] "GET /manage/8bd16d45-056d-5590-bc7f-12849f034351/availabilities/in_stock?model_ids=368f98eb-695d-45f6-bb63-06986e936
c00 HTTP/1.1" 200 1669 "https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups/f371e285-1903-564a-94e7-8b8cbb79a136/edit" "Mozilla/5.0 (Maci
ntosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
```

- GET the form action (instead of POST). Note there is no refferer (`"-"`), meaning this request did come from another tab or window
```
195.176.xxx.yyy- - [02/May/2018:14:09:15 +0000] "GET /manage/8bd16d45-056d-5590-bc7f-12849f034351/groups/f371e285-1903-564a-94e7-8b8cbb79a136 HTTP/1.1" 404 2854 "-"
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
```

- also, Safari requested a favicon, which is another hint that a new tab was opened.
```
195.176.xxx.yyy- - [02/May/2018:14:09:16 +0000] "GET /favicon.ico HTTP/1.1" 200 1145 "https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/group
s/f371e285-1903-564a-94e7-8b8cbb79a136" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
```

**Comment by nadjaweisskopf** [comment]
@nimaai @eins78 Hi both. I didn't hold any key while pressing on the save button. The error pops up even though I just press the button with the mouse. I wouldn't test such a strange behaviour. I can try to reproduce the error tonight.

**Comment by nadjaweisskopf** [comment]
@gurmir Please can you show Roger Bachmann the solution tomorrow morning (9. Mai). If he is happy with the solution we will implement as soon as the bugs definetely don't show up anymore.

Please explain, that the following has been changed: 
- Additional column (amount) in edit group
- link from model leads to edit model page

**Comment by nadjaweisskopf** [comment]
feedback from Roger: ok, ready to deploy (without testing)

**Comment by nadjaweisskopf** [comment]
@nimaai I believe we still have problems with the availability calculation. But let's implement this feature as it is and solve the other issues separetely.
