### ISSUE TITLE
Adjust items according to excel list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#382]
Please adjust all items from the list according to the values in the yellow columns: 

adjust fields: 
- User/Typical usage --> yellow column "Verwendung"
- building --> yellow column "Gebäude"
- room --> yellow collumn "Raum"

Do not adjust any other fields. 

[neue.Gesamtliste.20171030_ohne_AV.xlsx](https://github.com/leihs/leihs/files/1427400/neue.Gesamtliste.20171030_ohne_AV.xlsx)

**Comment by nadjaweisskopf** [comment]
@nimaii this was the list we were waiting for (see adjusted desciption of ticket)

**Comment by nimaai** [comment]
[leihs-script.log](https://github.com/leihs/leihs/files/1430860/leihs-script.log)

@nadjaweisskopf I made a dry run on TEST. Please take a look at the attached log and either adjust the values in the excel file accordingly or suggest what to do in case of these conflicts.

**Comment by nadjaweisskopf** [comment]
@nimaai please import the list, rename unbekannter Raum to Unbekannter Raum and provide a log for the rest

**Comment by nimaai** [comment]
@nadjaweisskopf Done on TEST. There seems to be only very few problems now. They can fix it by hand:

```
I, [2017-11-08T14:07:10.461420 #8007]  INFO -- : Row 1389
I, [2017-11-08T14:07:10.462310 #8007]  INFO -- : Item ITZ38249 not found
I, [2017-11-08T14:07:45.681364 #8007]  INFO -- : Row 2183
I, [2017-11-08T14:07:45.683157 #8007]  INFO -- : Building GA11 not found
I, [2017-11-08T14:07:45.683797 #8007]  INFO -- : Missing room 'GA11-221' for building 'GA11'.
I, [2017-11-08T14:07:48.337793 #8007]  INFO -- : Row 2244
I, [2017-11-08T14:07:48.339730 #8007]  INFO -- : Building GA 09 not found
I, [2017-11-08T14:07:48.340366 #8007]  INFO -- : Missing room 'Unbekannter Raum' for building 'GA 09'.
```

Should I do it on PROD now?

**Comment by nadjaweisskopf** [comment]
@nimaai Beinhaltet das Error-Log wirklich nur noch diesen einen Gegenstand: Item ITZ38249?

**Comment by nimaai** [comment]
@nadjaweisskopf Yes, there is only one missing item.

**Comment by nadjaweisskopf** [comment]
@nimaai Could you please run the script again and inform me so I can test? Thanks.

**Comment by nimaai** [comment]
@nadjaweisskopf It's on nimaai.ruby.zhdk.ch

**Comment by nimaai** [comment]
done auf prod. 3053 items updated.
