### ISSUE TITLE
Create a list for barbara and mike

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#383]
Please create a list with following conditions: 

**All items, which contain a room OR a building that do not match a room or building from the list (see list attached to ticket).**
compare the fields "building" with the column A (Liegenschaft) 
and the field "room" with the colum G (Raumnummer)

The list should contain all fields which are exported from the inventory list in leihs.

[20170612_Raum_Nr-Bez_Alle-2.xlsx](https://github.com/leihs/leihs/files/1393801/20170612_Raum_Nr-Bez_Alle-2.xlsx)

**Comment by nimaai** [comment]
@nadjaweisskopf We are waiting for something, right...?

**Comment by nadjaweisskopf** [comment]
@nimaai After ticket #382 (just updated) we can create this list.

**Comment by phiku** [comment]
@nadjaweisskopf Checkout http://phiku.ruby.zhdk.ch/manage/rooms_diff

**Comment by phiku** [comment]
- Export an excel instead of a CSV that the mutated vowels are correct. 
- Make sure, that the import works correctly, since the most likely will replace the rooms/buildings in the Excel, save as a CSV (done by Nadja) and import a CSV afterwards.

**Comment by phiku** [comment]
@nadjaweisskopf New version on http://phiku.ruby.zhdk.ch/manage/rooms_diff
- Import CSV with Rooms
- Export Excel with invalid Items

**Comment by phiku** [comment]
Ready on test https://test.leihs.zhdk.ch/manage/rooms_diff

**Comment by nadjaweisskopf** [comment]
@phiku The file room_diff contains items which have a correct room and building. I think the comparison has been done with the wrong columns. I attached another file with only building and room. Or hava another look at the description above. The columns which are meant to be compared are A and G.

**Comment by phiku** [comment]
@nadjaweisskopf Could you please add an example which was wrong.

**Comment by phiku** [comment]
@nadjaweisskopf Ok es erübrigt sich, es wurden genau die richtigen anstatt die falschen ausgegeben.

**Comment by nadjaweisskopf** [comment]
Will be deployed even though the correct items are listed instead of the items with wrong rooms and building. Phiki will solve this problem in the next iteration.

**Comment by nadjaweisskopf** [comment]
@phiku Do you know why the exported list contains entries with "Unbekannter Raum" even though my imported list contains "Unbekannter Raum"? Could you please have look at the list and check if the export is correct?

Here my imported list: 
[Raum_und_Gebäudeliste_der_ZHdK.xlsx](https://github.com/leihs/leihs/files/1714235/Raum_und_Gebaudeliste_der_ZHdK.xlsx)

**Comment by phiku** [comment]
@nadjaweisskopf Since I have delivered this and it will be in the next release, I close this ticket. Then if its not yet enough, we should make a new ticket, because at the moment I cannot do anything for this anymore as far as i know.

**Comment by nadjaweisskopf** [comment]
@phiku New generated file: 
[Raum_und_Gebaudeliste_der_ZHdK.csv.zip](https://github.com/leihs/leihs/files/2026865/Raum_und_Gebaudeliste_der_ZHdK.csv.zip)
