### ISSUE TITLE
scanning badge when changing borrower does not work

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#384]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When changing the orderer by scanning the badge of the person, the orderer should be changed to the  new person. 

#### Actual behaviour
I get an error saying "Ungültige Eingabe" when scanning a badge.

#### Steps to reproduce
1. go to pool
2. edit an order
3. select line
4. choose "change orderer"
5. scan badge
6. error is shown
7. when scanning badge in global search the user is found

**Comment by eins78** [comment]
@nadjaweisskopf I have not started debugging the frontend, but had a look in the DB and there seems to be a problem as well: Many users dont have `badge_id` set. I can not see any pattern, some recently created or updated users have it and some not (so its not a clear case of "it stopped working at this point in time"). For example, for my own user its `NULL`, in some cases its `empty string`.

```yaml
total_users: 9064
users_without_badge_id: 4502
```

**Comment by nadjaweisskopf** [comment]
@eins78 I just talked to Roger. He says normally they have to enter the id when a students lends the first time. So this has never been automated. But he is pretty sure, that with the new semester some ids vanish from leihs, ids from students that have already been entered.

**Comment by eins78** [comment]
@nadjaweisskopf I can not reproduce the exact issue in any browser (Chrome, Safari, Firefox). No error message is shown. Anyway, this feature is so broken I can't even see since when.
Suggested simple workaround: Make sure that when a badge is scanned in this form, it wont be submitted. This would mean the user would have to click in the automcomplete-result and then submit manually (so scanning the badge only saves the typing)

![screen shot 2017-10-31 at 12 24 07](https://user-images.githubusercontent.com/134942/32221608-721b1e6c-be36-11e7-93de-961d54cb2776.png)

**Comment by eins78** [comment]
@nadjaweisskopf I delivered a small fix which is usefull in any case: The "swap user" form can only be submitted when a user is selected in the autocomplete (or delegation).
That solves the problem of the barcode scanner breaking this form, but it does not automatically select the user – please reopen if I should work on that further (but seems expensive).

**Comment by nadjaweisskopf** [comment]
nadja: if needed with klick and enter then possible but only if really needed

**Comment by nadjaweisskopf** [comment]
@eins78 If I scan my badge, the scanner probably presses enter immediately and no user is selected. The user already belonging to this order stays unchanged. 
If I enter the badge nr. I can choose my name.

**Comment by eins78** [comment]
@nadjaweisskopf I can reproduce as described _in Safari only_ (it's the only browser that behaves differently in this case). I'll add a fix for it, should it go into the current release still?

**Comment by nadjaweisskopf** [comment]
@eins78 no, it's more important that we can deploy the procurement stuff, otherwise they can't benefit from the optimisations anymore. I'll test in chrome.

**Comment by nadjaweisskopf** [comment]
@eins78 I will create a new ticket to fix the safari problem.

**Comment by eins78** [comment]
@nadjaweisskopf There is already a fix on `test`, please try it out first.
