### ISSUE TITLE
Analyse: optimise performance on search overview 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#385]
see comments below

**Comment by nadjaweisskopf** [comment]
Check if order makes a difference. 

users, delegations, contracts, orders

Check with Roger which sort order is best.

**Comment by nimaai** [comment]
The bottleneck is contracts' search. On 4.6.0 it takes around 8s. After the orders' and contracts' refactoring (probably 4.7.0) it goes down to 5s, but obviously is still not enough and thus something has to be done.

**Comment by nimaai** [comment]
Should be deployed to nimaai.ruby.zhdk.ch for Roger and Nadja to test.

**Comment by nadjaweisskopf** [comment]
meeting with Roger and Matus

**Comment by nimaai** [comment]
@nadjaweisskopf  Deployed to https://nimaai.ruby.zhdk.ch

**Comment by nadjaweisskopf** [comment]
@nimaai I wanted to test the new global search overview with Roger today but the new code does not seem to be on nimaai.

**Comment by nadjaweisskopf** [comment]
@nadja test on nimaai

**Comment by nadjaweisskopf** [comment]
@nadja test global search

**Comment by nadjaweisskopf** [comment]
@nimaai Please remove the empty sections

**Comment by nimaai** [comment]
@nadjaweisskopf Done. Gaps removed. Due to this everything got close together and it was difficult to discern the sections. So, I have made the titles for the sections grey. Please check on http://nimaai.ruby.zhdk.ch/.

**Comment by nadjaweisskopf** [comment]
@nimaai after tests with Roger, we need to change the order as following: 

1. user
2. delegationen
3. vertrage
4. Bestellungen
5. modell
6. Gegenstände
7. sw
8. sw-license

Could you please change the order of the list so I can show Roger again?

**Comment by nimaai** [comment]
@nadjaweisskopf Done: http://nimaai.ruby.zhdk.ch/

**Comment by nadjaweisskopf** [comment]
@nimaai  Roger will test tomorrow morning.

**Comment by nadjaweisskopf** [comment]
@nimaai I haven't heard anything from Roger yet. I'll meet him on the 10th of Jan and will ask him then.

**Comment by nadjaweisskopf** [comment]
@nadja test and implement

**Comment by nadjaweisskopf** [comment]
@nimaai Sent msg. to Roger: 

Wir möchten gerne die verbesserte Suche diese Woche einführen. Bitte teste auf http://nimaai.ruby.zhdk.ch die globale Suche in eurem Gerätepark. 

Folgendes haben wir verbessert: 

- Leere Bereich werden nun nicht mehr angezeigt - das "Geflacker" ist so nicht mehr ausgeprägt
- Die Reihenfolge der Bereiche haben wir entsprechend Deinem Input geändert
- Die Suchergebnisse werden rascher gefunden und angezeigt

Wir können gerne generell die Seite der globalen Suche verbessern, da hätte ich einige Ideen dazu. Bis dahin würde ich aber gerne diese Version einführen, wenn Dir das recht ist. 

Gibst Du mir bitte Bescheid, ob das für Dich in Ordnung ist?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d1e753c3a56e994e7b618e3d2fa7ad71d004b7df
