### ISSUE TITLE
Shibboleth support in leihs for SWITCHaai

### ISSUE THREAD

**Issue by hostingnuggets** [leihs/leihs#386]
What is the status of the Shibboleth integration in leihs? We would like to use SWITCHaai (www.switch.ch/aai/) for the login into leihs.

Unfortunately I can't find any information on the wiki of leihs or in any documentation of this project.

Thank you for a short feedback.

**Comment by hostingnuggets** [comment]
An answer to my question above would be very much appreciated.

**Comment by DrTom** [comment]
We will most likely add support for this at some time in the future. But probably not before Q2 or Q3 2018.

**Comment by hsssystems** [comment]
Any news on this? Regarding this

https://github.com/leihs/leihs/issues/274

there seems to be some work on AAI / LDAP / Shibboleth integration. However we are planing to integrate leihs into our LDAP / Shibboleth environment and are not sure about the actual possibilities and future features. If we use the current LDAP Authentication, will there be a migration path?
