### ISSUE TITLE
Vorbereiten Michal: Metakey-Labels should be multilingual too (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#394]
#151290301

Max oder Philipp)

**Comment by nadjaweisskopf** [comment]
Bitte für Michal umsetzen.

**Comment by nadjaweisskopf** [comment]
@eins78 needs to review Michals dev.

**Comment by nadjaweisskopf** [comment]
has been reviewed. Some work still needs to be done.

**Comment by nadjaweisskopf** [comment]
important!

**Comment by eins78** [comment]
(already waiting for CI at the moment)

**Comment by nadjaweisskopf** [comment]
- API a seperate ticket if needed
- Switch the language a seperate ticket
