### ISSUE TITLE
Vertrauliche Links (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#395]
(Thomas)
jmd. anderes lieber nicht (max/philipp)
Konzeptarbeit mit Susanne ausarbeiten
(so bald wie möglich)

**Comment by nadjaweisskopf** [comment]
Es soll die Lsg. gem. Token Api's umgesetzt werden - wie vom Thomas im Refinement vorgeschlagen. 
Könnte evtl. Philipp angehen?

**Comment by nadjaweisskopf** [comment]
Ask Susanne, when he should start with this ticket.

**Comment by nadjaweisskopf** [comment]
Michal is on it

**Comment by nadjaweisskopf** [comment]
The question is, how we shall integrate the solution in the UI.

**Comment by nadjaweisskopf** [comment]
Meeting 19.6.18: 
- Place action to share URL on the action button and name it "Befristetete URL verwalten / Manage temporary URL" - or similar text
- navigate to new page
- when creating the URL the user defines the max. time until max. one year

**Comment by nadjaweisskopf** [comment]
Zwei Tests erweitern, ein kleiner Bug beheben

**Comment by eins78** [comment]
merged 
https://github.com/Madek/madek/commit/c20824b739699cc38df17de6ea570a9638ad4958
