### ISSUE TITLE
Button "Verify and approve" is missing

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#399]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I would expect to see the button "verify and approve" when checking orders where the orderer belongs to a verifiable group and his order contains a model from this group. 

#### Actual behaviour
The button does not change, no matter if the order needs to be verified or not. 

#### Steps to reproduce
1. go to pool
2. go to the all orders list
3. the checkbox "to be verified" needs to be checked
4. search for an order where the orderer is part of a verifiable group and has at least one model from this group - or adjust an order so you have this situation 

#### Specifications
- Leihs version: 4.7.0
- Browser version: safari, 11.0

**Comment by nadjaweisskopf** [comment]
@nimaai Scenario for the checkbox "to be verified"

  Scenario: Remove filter that shows orders to be verified
    Given I am Andi
    And I am in an inventory pool with verifiable orders
    And I am listing the orders
    Then I see all verifiable orders
    When I uncheck the filter "To be verified"
    Then I see orders placed by users in groups requiring verification

The scenario is as you said.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/49e096819e3c3b000f6250069500c48de17837d1

**Comment by nadjaweisskopf** [comment]
@nimaai If I klick on "reject" on a "verify and approve" button nothing happens. This problem might have already existed before. In this case we don't have a scenario for this feature? Reject from the edit order page works.

**Comment by nadjaweisskopf** [comment]
@nimaai some rejects work, see printscreen (green works, red does not work)

<img width="1206" alt="bildschirmfoto 2017-11-02 um 12 39 03" src="https://user-images.githubusercontent.com/3356016/32324268-1cf930f4-bfcb-11e7-9b81-0849f22b821b.png">

**Comment by nadjaweisskopf** [comment]
@nimaai searching in the order lists all/pending/approved/rejected takes a very long time - much longer than in the current production. Try to search for "Flavio Luca Marano" in all orders.
