### ISSUE TITLE
The order lists for group managers are emtpy

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#400]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When viewing the order list I would expect to see orders which need to be verified, verified orders which have already been approved or rejected. 

#### Actual behaviour
All lists are empty.

#### Steps to reproduce
1. log in as a group manager to pool Ausleihe Toni-Areal
2. Check the order lists all, pending, approved, rejected
3. They are all empty

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/49e096819e3c3b000f6250069500c48de17837d1

**Comment by nadjaweisskopf** [comment]
@nimaai accepted
