### ISSUE TITLE
The reason is not shown in take backs

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#401]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I would expect to see the reason of the contract on each line in the take back - both for options and items. 

#### Actual behaviour
The reason an item as been lended is not shown anymore. 

#### Steps to reproduce
1. go to pool Ausleihe Toni-Areal
2. Edit a take back with items
3. The reason is missing

#### Specifications
- Leihs version: 4.7.0
- Browser version: safari 11.0

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f324f3d9571c4ed94adeef4027d2a04cd492df86

**Comment by nadjaweisskopf** [comment]
@nimaai I would expect the reasons to be listed seperately per line. So if I have two lines with two different reasons then each line shows a reason. At the moment the reasons are shown as comma seperated list: reason1, reason2
In a hand over we show the reasons per line.

**Comment by phiku** [comment]
@nadjaweisskopf Wo müsste die Reason auftauchen, hier irgendwo (siehe Attachment)?
![bildschirmfoto 2017-11-28 um 08 03 04](https://user-images.githubusercontent.com/16756048/33306379-a5910f4e-d412-11e7-9a1e-d26e8c37659b.png)

**Comment by nadjaweisskopf** [comment]
@phiku Genau, sie taucht in der Sprechblase auf.

**Comment by phiku** [comment]
@nadjaweisskopf Kann man diesen schon schliessen? Dann kann man das neue Ticket referenzieren.
