### ISSUE TITLE
Error when editing an order with overbooked models

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#403]
#### Expected behaviour
If I press the edit button on the popup message of an overbooked order, I would expect to be navigated to the edit order page. 

#### Actual behaviour
When editing an order from the popup message as group manager, I get an error. 

#### Steps to reproduce
1. log in as group manager
2. Go to order list
3. press on button "verify and approve" on an order which has models that are overbooked
4. --> popup opens saying "The order is not approvable..."
5. Klick on "edit"
6. error is shown

#### Specifications
- Leihs version: 4.7.1
- Browser version: safari 11.0

<img width="1414" alt="bildschirmfoto 2017-11-02 um 12 32 02" src="https://user-images.githubusercontent.com/3356016/32324096-73bf1238-bfca-11e7-9606-e5d5054b7af9.png">

**Comment by eins78** [comment]
Link im template falsch: 
`/manage/$ID/contracts/$ID/edit` statt `/manage/$ID/orders/$ID/edit`

https://github.com/leihs/leihs_legacy/blob/039f234d23488e7c8126e6db886b5390001fd45d/app/assets/javascripts/manage/views/orders/approval_failed_modal.jsr.erb#L18-L19

**Comment by nadjaweisskopf** [comment]
@eins78 I can't access the orders. I don't get an error, only a endless spin. I'm not sure if this has anything to do with this ticket.

**Comment by eins78** [comment]
@nadjaweisskopf please try again, staging server was not working correctly (hard disk full)
