### ISSUE TITLE
Reject button does not always work

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#404]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When I reject an order I would expect this order to be rejected straight away. 

#### Actual behaviour
Reject buttons of some orders do not work - nothing happens. I couldn't find a logic yet. 

#### Steps to reproduce
1. go to pool Ausleihe Toni-Areal
2. open the order list
3. try rejected orders which are to be verified
4. try for example the order from Flavio Luca Marano

#### Specifications
- Leihs version: 4.7.0
- Browser version: safari 11.0

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/862badc25cc048070f86c9dbf60430773c738010
