### ISSUE TITLE
[dev] use rails/webpacker

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#405]
see https://github.com/rails/webpacker

- modern way to bundle javascript, now supported by Rails >5 (instead of sprockets)
- use JS dependencies from npm instead of rails-assets (npm-to-gem-bridge)

---

tasks

- [x] add [rails/webpacker](https://github.com/rails/webpacker)
- [x] port over new frontend modules (react etc)
- [x] try to port 'legacy' frontend (separate entry point)
- [x] better CI check ([content-based](https://github.com/Madek/madek-webapp/blob/master/cider-ci/bin/check-precompiled-assets))
- [x] integrate linter?
- [x] wiki: developer docs: add minimal setup, link to webpacker docs

**Comment by nadjaweisskopf** [comment]
@nadja when finished then test all react pages

**Comment by nadjaweisskopf** [comment]
To test:
- Hand Over: autocomplete search field
