### ISSUE TITLE
contracts are shown as open even though they are closed

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#407]
#### Expected behaviour
FIRST CASE
If I search for the item INV35232 I would expect to see on the line of Joan Jordi Oliver Arcos the closed contract Nr. 1D6Q and the status of the contract should say "closed". The item has been taken back - see contract. 

SECOND CASE (production 6.11.17)
Contract nr. 48401 should be shown as closed when searching for "Schwarz" in global search. 

THIRD CASE (staging 5.11.17)
If I search for "nadja weisskopf" in the global search, I would expect the contracts 7SZZ and 5N4X to be shown as closed. 

#### Actual behaviour
FIRST CASE
The line from Joan is shown with the status "signed" and if I press on the take back button another contract is opened. 

SECOND CASE (production 6.11.17)
Contract 48401 is shown as "signed" even though it is already closed. List of contracts does not show the contract when searching for it.

THIRD CASE (staging 5.11.17)
See also on staging two contracts from "nadja weisskopf" which are shown as open but are actually already closed. If you klick on "take back" you are navigated to an empty take back page.
The tab "take back" in the visits list is correct and does not show these two contracts.
So it seems as though we have a problem only on the global search.

#### Steps to reproduce
FIRST CASE
1. go to pool Ausleihe Toni-Areal
2. search for the item INV35232 in the global search
3. Check the line from Joan Jordi Oliver Arcos in the contracts section.  

SECOND CASE (production 6.11.17)
1. go to Pool IT-Zentrum
2. search for "Schwarz" in global search
3. check the contract nr. 48401
4. press on take-back
5. take back is empty

THIRD CASE (staging 5.11.17)
1. I created two orders in borrow
2. Adjusted the group FFI with my name and the item of one of the orders.
3. approved an order
4. handed out the item of this visit
5. approved the other order
6. took back the item of the first order
7. took back the item of the second order
8. searched for "nadja weisskopf" in th global search
9. Both contracts are still shown as "open". 
10. klick on take back
11. take back page is empty

#### Specifications
- Leihs version: 4.7.1
- Browser version: safari 11.0

<img width="1000" alt="bildschirmfoto 2017-11-03 um 21 13 45" src="https://user-images.githubusercontent.com/3356016/32394001-f4abe51c-c0db-11e7-9814-b427836d0e1f.png">

<img width="1006" alt="bildschirmfoto 2017-11-05 um 15 07 46" src="https://user-images.githubusercontent.com/3356016/32415548-c9ebc110-c23b-11e7-9442-aaf2748ff159.png">

<img width="1017" alt="bildschirmfoto 2017-11-05 um 15 13 56" src="https://user-images.githubusercontent.com/3356016/32415562-005e7670-c23c-11e7-903d-8d25bfab7f20.png">

**Comment by nimaai** [comment]
@nadjaweisskopf Indeed, in the first case we have an open contract which have all reservations closed. We need to:
- add an additional DB constraint which will prevent this inconsistency
- analyse our code why this sometimes happens (note: this behaviour is not new)
