### ISSUE TITLE
Search for contract nr. in contracts list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#409]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
Show the contract by typing the contractnr. in the contracts list (All, open, closed)
When searching for the contract nr. in the global show search results

#### Actual behaviour
No search results are shown

#### Steps to reproduce
1. go to contracts tab in lending section
2. type a conract nr. in the search field
3. no result is shown

1. go to global search
2. type a conract nr. in the search field
3. no result is shown

#### Specifications
- Leihs version: 4.7.3
- Browser version: safari 11.0
- MySQL/PostreSQL version:

**Comment by nadjaweisskopf** [comment]
@eins78 searching for a contract in global search: "1MQ6" doesn't give a result and then navigating to the tab "contracts" in global search leads to an endless spin. 

In The contracts itself it works fine.

**Comment by eins78** [comment]
@nadjaweisskopf please try again, staging server was not working correctly (hard disk full)
