### ISSUE TITLE
Make whole line klickable and place the + sign to the front

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#412]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When chosing a category to create a new request, I would expect something to happen when klicking on the category - not just when klicking on the green +. Might also be nice to have a bigger green plus icon.

#### Actual behaviour
Only the green plus opens a new request.

#### Steps to reproduce
1. go to procurement
2. klick on the big green plus
3. Open a main category and klick on the sub category line. 
4. nothing happens

#### Specifications
- Leihs version: 4.7.3
- Browser version: safari 11.0

**Comment by eins78** [comment]
not *quite* as easy as it looked at first: some of those lines have sub-templates which are shown as yet another level of lines in a list.

this is also the reason for the current design: it was assumed that all sub-categories have templates, and the reason to not have the whole line linked was to nudge the user into choosing a template.

so, the view now distinguishes those cases. the link target is always the whole line with the icon at the beginning, but if there are any templates than this header is a bit deemphasised.

screenshot shows all the cases:
![screen shot 2018-01-26 at 14 36 39](https://user-images.githubusercontent.com/134942/35442263-e9e27b52-02a6-11e8-9e2a-72e98dca2410.png)
