### ISSUE TITLE
finish calender in borrow section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#413]

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/14bb926022dfba52c635c83aa28287ca9792ccc3

**Comment by nadjaweisskopf** [comment]
test borrow calendar:
- popup start end
- can not add item if error appears
- cart is still the only calender

**Comment by nadjaweisskopf** [comment]
When chosing a day which is closed, for example "Auffahrt", the user see's a strange error picture: 

<img width="1024" alt="bildschirmfoto 2018-02-19 um 22 12 36" src="https://user-images.githubusercontent.com/3356016/36397265-4cb745e0-15c2-11e8-8137-ca4744d6ae84.png">

**Comment by nimaai** [comment]
1. and 4. resolved: https://github.com/leihs/leihs_legacy/commit/353fec2b03b53255debd2474ebe522296a39bff5

**Comment by eins78** [comment]
2. and 3. "solved" by redesigning it and getting rid of the popup. https://github.com/leihs/leihs/commit/5d72562ba0572f97722c25f427f2482fb2663ae3

buttons now show on 'hover':
![screen shot 2018-02-20 at 16 50 56](https://user-images.githubusercontent.com/134942/36493419-e1b60b9a-172f-11e8-9450-e38bfe679a01.png)

**Comment by nadjaweisskopf** [comment]
@nimaai 
1. Please translate the message to English or do not make days in the past clickable: 

<img width="626" alt="bildschirmfoto 2018-02-26 um 20 55 05" src="https://user-images.githubusercontent.com/3356016/36692143-964c3f88-1b37-11e8-8aea-b30139ba505a.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/1aa4693255103ae22a0ca091f123353d66a45744
