### ISSUE TITLE
Analyse error msg. 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#414]
![bildschirmfoto 2017-11-06 um 19 10 57](https://user-images.githubusercontent.com/3356016/32550753-996d61a6-c48e-11e7-8d9b-d949ba458cb2.png)

**Comment by phiku** [comment]
```
  validates_presence_of :product
  validates_uniqueness_of :version, scope: :product
```

I can create the following in this order:
product: test1, version: abc
product: test2, version: def
product: test2, version: abc
product: test3

But not anymore again the same:
product: test1, version: abc

The check is, if product and version are unique. Its not totally wrong. The question is, what do we want?

**Comment by phiku** [comment]
Auf Test.

**Comment by nadjaweisskopf** [comment]
@phiku Could you please change the error msg. as following: 

Now: There exists already a model with the same product name with empty version.
New: A model with the same product name and empty version already exists.

Now: There exists already a model with the same product name and version.
New: A model with the same product name and version already exists.

**Comment by nadjaweisskopf** [comment]
Created a new ticket
