### ISSUE TITLE
First klick does not add the delegation user in an order

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#415]
Expected behaviour

When changing the orderer in an order for a delegation, then the first klick when chosing the user does not select this user.

Actual behaviour

When first klicking on the users name, nothing happens. When klicking on the users name the second time, the user is added and the hand over can be completed.

Steps to reproduce

1. go to pool AV-Ausleihe
2. search for an order created for a delegation OR change the orderer of an order created from a normal user to "Acoustic Characteristics of Voice IMST"
3. edit the order
4. change the orderer
5. choose another delegation user
6. first klick does not add user

Leihs version: 4.7.3
Browser version: safari 11.0

**Comment by phiku** [comment]
Developer Notes:

Reproduce on localhost with production dump:
Verleih > Bestellungen > Editieren > Bestellende/n wechseln > Enter "Acoustic Characteristics of Voice IMST" > Select Person

Example order for production dump:
http://localhost:3000/manage/8bd16d45-056d-5590-bc7f-12849f034351/orders/f714b20e-04d7-4c4a-a714-7bd08ea8dd1f/edit

Existing code: 
swap_user_modal.jsr.erb
swap_users_controller.coffee

Try to reuse:
hand-over-dialog.jsx

**Comment by phiku** [comment]
@nadjaweisskopf Kann es sein, dass bei swap user sonst noch ein Bug ist? Wenn ich auf Test auf eine Delegation wechsle mit Kontakt Person, und dann nochmals den Dialog öffne, sollte dann nicht unten rechts die Kontakt Person erscheinen?
![bildschirmfoto 2017-11-23 um 11 36 15](https://user-images.githubusercontent.com/16756048/33168879-cf1a7892-d042-11e7-84e5-91ac32bacaa8.png)

**Comment by phiku** [comment]
Developer Note:
Branch: pku_master_swap_user

Needs clarification about:

Delgation user:
order.user().delgator_user() or order.delgatedUser() or ...

Selected User:
swap_users_controller.coffee
user_id = @searchSetUserController.selectedUserId ? @order.user().id

**Comment by phiku** [comment]
Open point: What was it about disabling/enabling the form (changes from Max), why not just remove the form?
