### ISSUE TITLE
Update the rental server to 4.7.3 - Gui does not show a version

### ISSUE THREAD

**Issue by olafstirni** [leihs/leihs#416]
Hello I have updated our server to version 4.7.3.
Unfortunately the GUI is not correct, the Verion is not displayed.
This should be so ..
What am I doing wrong ??

Here is the installlog

root@debian:~/leihs/zhdk-inventory# cd ..
root@debian:~/leihs# ansible-playbook deploy/import-v3-into-v4_play.yml -i zhdk-inventory/stp-leihs
 
PLAY [leihs_server] ************************************************************
 
TASK [setup] *******************************************************************
The authenticity of host 'stp-leihs.XXXX.XXXX (IP Adress)' can't be established.
ECDSA key fingerprint is 92:70:86:f8:39:e6:f9:3d:fd:5a:1............
Are you sure you want to continue connecting (yes/no)? yes
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : dist upgrade] *************************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Install general stuff] ****************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'ruby', u'python-passlib', u'imagemagick'])
 
TASK [os-setup : configure journald ForwardToSyslog] ***************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : reload systemd] ***********************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Set timezone variables] ***************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : reconfigure tzdata] *******************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : apt] **********************************************************
skipping: [stp-leihs.XXXX.XXXX] => (item=[])
 
TASK [os-setup : remove default pool settings] *********************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : configure ntp server] *****************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : stop ntp service] *********************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : run initial ntpdate] ******************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : start ntp service] ********************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Install vim-nox] **********************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Set vim-nox as default editor] ********************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : set the vi mode for the shell] ********************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Etc keeper install packages] **********************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'etckeeper', u'git'])
 
TASK [os-setup : etckeeper uninitialize bzr (in case)] *************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : etckeeper deconfigure bzr] ************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : etckeeper configure git] **************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : setup /etc to be tracked by etc keeper and initialize] ********
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Install apache2] **********************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'apache2', u'libapache2-mod-xsendfile'])
 
TASK [os-setup : Disable default site] *****************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : Enable modules] ***********************************************
ok: [stp-leihs.XXXX.XXXX] => (item=expires)
ok: [stp-leihs.XXXX.XXXX] => (item=headers)
ok: [stp-leihs.XXXX.XXXX] => (item=proxy)
ok: [stp-leihs.XXXX.XXXX] => (item=proxy_http)
ok: [stp-leihs.XXXX.XXXX] => (item=rewrite)
ok: [stp-leihs.XXXX.XXXX] => (item=ssl)
ok: [stp-leihs.XXXX.XXXX] => (item=xsendfile)
 
TASK [os-setup : install monit] ************************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'monit'])
 
TASK [os-setup : configure monit service interval] *****************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : configure monit http port] ************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : configure monit http address] *********************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : configure monit http allow localhost] *************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : reload monit] *************************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : call monit to awake it] ***************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [os-setup : install vmware tools] *****************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'open-vm-tools', u'open-vm-tools-dkms'])
 
TASK [os-setup : authorized_key] ***********************************************
 
TASK [os-setup : authorized_key] ***********************************************
 
TASK [openjdk8 : apt_repository] ***********************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [openjdk8 : apt] **********************************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [openjdk8 : apt] **********************************************************
skipping: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : Add pgdg apt key] *******************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : Add pgdg apt repository] ************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : Remove earlier installations of postgresql] *****************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'postgresql-9.4', u'postgresql-9.5'])
 
TASK [postgresql : Install postgresql] *****************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'sudo', u'libpq-dev', u'postgresql-client', u'postgresql-contrib-9.6', u'postgresql-9.6', u'python-psycopg2'])
 
TASK [postgresql : configure database monitoring] ******************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : reload monit] ***********************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : add root postgresql user] ***********************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [postgresql : Create the a database for root] *****************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [install : dist upgrade] **************************************************
ok: [stp-leihs.XXXX.XXXX]
 
TASK [install : apt] ***********************************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'ruby', u'git', u'imagemagick'])
 
TASK [ruby-install : apt] ******************************************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'autoconf', u'bison', u'build-essential', u'libcurl4-openssl-dev', u'libffi-dev', u'libgdbm-dev', u'libgdbm3', u'libncurses5-dev', u'libreadline-dev', u'libreadline6-dev', u'libssl-dev', u'libyaml-dev', u'zlib1g-dev'])
 
TASK [ruby-install : copy install dir] *****************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [ruby-install : install ruby-install] *************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [ansible : install ansible dependencies] **********************************
ok: [stp-leihs.XXXX.XXXX] => (item=[u'build-essential', u'libffi-dev', u'libssl-dev', u'libyaml-dev', u'python-dev', u'python-pip', u'python2.7', u'python2.7-dev', u'ruby'])
 
TASK [ansible : upgrade pip] ***************************************************
changed: [stp-leihs.XXXX.XXXX]
 
TASK [ansible : install ansible via pip] ***************************************
Segmentation fault
root@debian:~/leihs# reboot

**Comment by eins78** [comment]
@olafstirni According to the log, the deploy did not run through, therefore the new version was not actually installed.

This seems like ansible-related bug that we also encountered in the past. I will try to give some hints how to work around it for now; maybe will lead to a general solution/fix that we can add to our deploy code.

Workaround:
- try setting the variable `install_ansible: false`, e.g. `ansible-playbook deploy/import-v3-into-v4_play.yml -i zhdk-inventory/stp-leihs -e "install_ansible=false"` or in the inventory

Questions towards a real fix:
- What OS are you using? (`cat /etc/issue; uname -a`)
- Is the control machine the same as the target machine? (Are `debian` and `stp-leihs.…` are the same host?)

**Comment by olafstirni** [comment]
Hello

Now I have another error message:
unfortunately still is not ..


root@debian:~/leihs# ansible-playbook deploy/import-v3-into-v4_play.yml -i zhdk-inventory/stp-leihs -e "install_ansible=false"
ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'
to see the full traceback, use -vvv
root@debian:~/leihs# reboot
login as: 
root@131.117.104.83's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Nov 13 06:56:43 2017 from zrhl2815.global.szh.loc
root@debian:~# cat /etc/issue; uname -a
Debian GNU/Linux 8 \n \l

Linux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) i686 GNU/Linux
root@debian:~#


To the question:
The Debian and the STP lending are the same host.

What can I do?

regards
Olaf Stirnimann

**Comment by eins78** [comment]
Current Problem: This error is likely caused by the previous crash, ansible is now in an inconsistent installation state. To fix:

```
pip install -I --upgrade pip
pip install -I --upgrade ansible
pip install -UI pyopenssl
```

General Problem:
Running the playbook from the target host is technically possible, but not really supported, and should be avoided. Is using a different one an option for you?

**Comment by olafstirni** [comment]
Hallo 
Habe den Update gemacht doch leider gibt es einen neuen Fehler:

Nach dem Update komme ich auch nicht mehr auf die WebSeite ..

Error 503

Wie weiter?


TASK [leihs-database-install : extract archive] ******************************************************************************************************
changed: [stp-leihs.stapo.stzh.ch]

TASK [leihs-database-install : install ruby] *********************************************************************************************************
fatal: [stp-leihs.stapo.stzh.ch]: FAILED! => {"changed": true, "cmd": "#/bin/bash\n set eux\n ruby-install --no-install-deps --no-reinstall ruby 2.4.2    ", "delta": "0:00:01.142031", "end": "2017-11-15 11:36:22.607263", "failed": true, "msg": "non-zero return code", "rc": 255, "start": "2017-11-15 11:3    6:21.465232", "stderr": "*** Unknown ruby version 2.4.2. Proceeding anyways ...\n--2017-11-15 11:36:21--  https://cache.ruby-lang.org/pub/ruby/2.4/rub    y-2.4.2.tar.bz2\nResolving cache.ruby-lang.org (cache.ruby-lang.org)... 151.101.13.178, 2a04:4e42:3::434\nConnecting to cache.ruby-lang.org (cache.rub    y-lang.org)|151.101.13.178|:443... failed: Connection refused.\nConnecting to cache.ruby-lang.org (cache.ruby-lang.org)|2a04:4e42:3::434|:443... faile    d: Network is unreachable.\n!!! Download of https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2 failed!", "stderr_lines": ["*** Unknown ruby v    ersion 2.4.2. Proceeding anyways ...", "--2017-11-15 11:36:21--  https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2", "Resolving cache.ruby-l    ang.org (cache.ruby-lang.org)... 151.101.13.178, 2a04:4e42:3::434", "Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|151.101.13.178|:443... fa    iled: Connection refused.", "Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|2a04:4e42:3::434|:443... failed: Network is unreachable.", "!!! D    ownload of https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2 failed!"], "stdout": ">>> Installing ruby 2.4.2 into /home/leihs-database/.rubi    es/ruby-2.4.2 ...\n>>> Downloading https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2 into /home/leihs-database/src ...", "stdout_lines": [">    >> Installing ruby 2.4.2 into /home/leihs-database/.rubies/ruby-2.4.2 ...", ">>> Downloading https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.b    z2 into /home/leihs-database/src ..."]}
        to retry, use: --limit @/root/leihs/deploy/import-v3-into-v4_play.retry

PLAY RECAP *******************************************************************************************************************************************
stp-leihs.stapo.stzh.ch    : ok=73   changed=27   unreachable=0    failed=1

root@debian:~/leihs# reboot

**Comment by DrTom** [comment]
```Connection refused.\nConnecting to cache.ruby-lang.org ```

The ruby install failed because the remote repository could not be reached. This is most likely a temporrary network problem. Please try again. If the problem is persistent check your network and firewall settings.

**Comment by olafstirni** [comment]
I tried again yesterday and today with the same result.
The Proxy settings should be correct because otherwise I achieved everything
is there any other way to hire it so that our users can do it? for any help i am very grateful

**Comment by DrTom** [comment]
From the machine the deploy is performed, what does 

`curl -I https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2` say?

**Comment by olafstirni** [comment]
root@debian:~/leihs# curl -I https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2
-bash: curl: command not found

**Comment by DrTom** [comment]
well `apt install curl` would solve that.

But there is something else, I just steped in and only looked at your recent problem and I don't  know what your state is. But I believe you are using the wrong playbook to begin with. `import-v3-into-v4_play.yml` is to import data from a v3 instance. That is unlikely what you want to do.

**Comment by olafstirni** [comment]
OK and what do I have to do to make everything work?
Unfortunately, I have only a little knowledge about debian and therefore I am grateful for any help

**Comment by olafstirni** [comment]
root@debian:~# curl -I https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.bz2
HTTP/1.1 200 Connection established
Via: 1.1 STPMWIPK13
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

HTTP/1.1 200 OK
Server: nginx/1.2.1
Content-Type: application/octet-stream
Last-Modified: Thu, 14 Sep 2017 13:27:41 GMT
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Via: 1.1 varnish
Fastly-Debug-Digest: eeb58d59996d30c4d7e478aa0cbe25e3beb678c5fa05542a15f4904dd4d3aadb
Content-Length: 12607283
Accept-Ranges: bytes
Date: Fri, 17 Nov 2017 09:38:52 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-itm7421-ITM, cache-ams4427-AMS
X-Cache: HIT, HIT
X-Cache-Hits: 0, 0
X-Timer: S1510911532.108951,VS0,VE3

root@debian:~#

**Comment by nadjaweisskopf** [comment]
We sent a VMWare - installation worked.
