### ISSUE TITLE
Disable "Supply Category"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#420]
ZHdK needs the field "inventory relevant" but does not want the field "supply category" anymore. 

make field not mandatory and disable field.

**Comment by phiku** [comment]
@nadjaweisskopf Do we really want to copy this? Why not just disable it?

**Comment by nadjaweisskopf** [comment]
@phiku I had chaned the text after the last planning but apparently it hasn't been saved. Sorry.

**Comment by phiku** [comment]
Implemented.

**Comment by phiku** [comment]
Demo: 

Anschaffungskategorie darf nicht mehr erscheinen.
