### ISSUE TITLE
Provide a new field in Admin-section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#421]
Provide a new field in Admin-section: 

field: Contact: the leihs-title on the bottom of the page should be linked to an URL which I can enter in the Admin-section
- checkbox to activate or deactivate link: deactivate per default. If deactivated, the title is not clickable.
- field to enter URL such as https://intern.zhdk.ch/?leihs

![bildschirmfoto 2017-11-15 um 16 23 55](https://user-images.githubusercontent.com/3356016/32844225-2131b306-ca22-11e7-995d-f8f28b97ee55.png)

**Comment by eins78** [comment]
@nadjaweisskopf Is there a reason that 2 fields are needed for this? I think its simpler to just have a "url" field and if its filled, the link is active. In any case its easy to implement.

**Comment by nadjaweisskopf** [comment]
@eins78 Yes, you're right, one field is enough.

**Comment by eins78** [comment]
@nadjaweisskopf the screenshot show the logo in `/manage`. I guess it should be the same for `/borrow` and `/admin`? Not `/procurement` only has a logo in the header, top left, and that already links to the dashboard. Ok?
