### ISSUE TITLE
Implement the "take back date" for items

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#424]
#### Expected behaviour
Searching for an item in global search should provide the following search result for the section

Searching for a user - sort order stays unchanged
- open contracts first
- according to the created date

 Searching for an item
sort according to the take back date of an item. If the item has not yet been taken back, it is listed in first place.

#### Actual behaviour
We sort the contracts alphabetically, first the open contracts, then the closed contracts. 

#### Steps to reproduce
1. go to pool "Ausleihe Toni-Areal"
2. search for item AVZ15792 in global search
3. check search result in section "contracts"
4. search result does not make sense for lending managers. The sort order should be different. Mireille Osmieri should be listed on top, she was the last one to have the item. 

#### Specifications
- Leihs version: safari
- Browser version: 11.0

**Comment by nadjaweisskopf** [comment]
@nadja Reference to closed ticket with sort order

**Comment by eins78** [comment]
As suspected, this is not possible within the global search.

- its not technically possible to sort by "when was *this* item taken back last" (bc. its the global search which doesn't know items, just text)
- we *could* sort by "when was any item taken back" (as we decided earlier), but that is wrong for many cases – including the exact example from the ticket(!) I tried it for the "contract that should be on top" as well as the "contract that is currently on top" and their position would be the same. Can be verified manually by looking at the contracts, there just are other items which were taken back last. 

Small aside: Current sorting logic for contracts is already much more complicated ([see code](https://github.com/leihs/leihs_legacy/blob/655e63e899f2245daafb711b97611fb1643ed072/app/models/contract.rb#L246-L266))

**Comment by eins78** [comment]
Proposal: make a new "show" view for Items in manage. That would have helped with several tickets from the last week, including showing "historical data" for Items from inactive pools).
The view would show basic info, link to model, a summary ("where is it and where was it last") and lists of reservations and contracts (which can be sorted relating to the item).

**Comment by nadjaweisskopf** [comment]
nadja: decide what to do

**Comment by nadjaweisskopf** [comment]
We'll leave it as it is.
