### ISSUE TITLE
1 Tage instead of 1 Tag

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#426]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
First see github.com/leihs/leihs/wiki and relishapp.com/leihs. Then provide a short but meaningful description of the expected behaviour.

#### Actual behaviour
Provide a short but meaningful description of the actual behaviour.

#### Steps to reproduce
Please include the role of the logged in user as well as precise steps starting with logging in upto the occurence of the problem.

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by eins78** [comment]
Found the code via plain text search: https://github.com/leihs/leihs_legacy/blob/11287f41807133f56abdd2ddc747241d371b5e4b/app/assets/javascripts/components/hand-over-dialog.jsx#L121

Fixed it, and looked through commits of last months, seems to be the only case where this error was made.

**Comment by nadjaweisskopf** [comment]
Hand over dialogue (time range)

**Comment by nadjaweisskopf** [comment]
@eins78 In a hand over there is still a string which says "1 Tage" instead of "1 Tag". All other places seem to be ok.

![bildschirmfoto 2018-02-05 um 16 51 12](https://user-images.githubusercontent.com/3356016/35813944-2c90ea2e-0a95-11e8-9941-d2863fb685ae.png)

**Comment by nadjaweisskopf** [comment]
@eins78 neu ist der String für mehrere Tage jetzt in Englisch.

![bildschirmfoto 2018-02-07 um 15 09 43](https://user-images.githubusercontent.com/3356016/35920747-010888e6-0c19-11e8-930a-230c09963b74.png)

**Comment by eins78** [comment]
@nadjaweisskopf puh! noch tiefer im Code einen grundsätzlichen Fehler gefunden (~5 Jahre alt ;))
Habe diesmal selbst nochmal kritisch über alles geschaut…

![screen shot 2018-02-08 at 11 44 14](https://user-images.githubusercontent.com/134942/35968939-8f586d94-0cc5-11e8-9482-22cfbc9ada0b.png)

**Comment by nadjaweisskopf** [comment]
@eins78 There is still at least one location, where we write 2 Tag instead of 2 Tage. I'll accept this ticket and create a new one for this specific bug.
