### ISSUE TITLE
Adjustment in list of pools in borrow section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#429]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I would expect to see all pools where I have access to as customer and where at least one item is borrawable AND if a contract for my user exists in a pool

Check the following existing scenario:

  @rack
  Scenario: Inventory pool information
    Given I am Normin
    When I click on the inventory pool link
    Then I see the inventory pools I have access to
    And I see only inventory pools containing borrowable items
    And I see a description for each inventory pool
    And the inventory pools are sorted alphabetically on this page

Following change needed: 

  @rack
  Scenario: Inventory pool information
    Given I am Normin
    When I click on the inventory pool link
    Then I see the inventory pools which have borrowable items
    And I see inventory pools where a contract for my user exists
    And I see a description for each inventory pool
    And the inventory pools are sorted alphabetically on this page

#### Actual behaviour
Pools are not visible if none of there items are "borrowable", even though I have a lended items of this pool.

#### Steps to reproduce
1. go to pool "Fundus"
2. lend something to yourself
3. check the pools in borrow section
4. Fundus is not listed

#### Specifications
- Leihs version: 4.8.0
- Browser version: safari 11.0

**Comment by phiku** [comment]
Actually shouldnt it just be:

Instead of

"Then I see the inventory pools which have borrowable items
And I see inventory pools where a contract for my user exists"

or

"Then I see the inventory pools which have borrowable items
And I see inventory pools where a contract for my user exists"

it should simply be

"Then I see the inventory pools which have borrowable items and a contract for my user exists"

**Comment by phiku** [comment]
@nadjaweisskopf Its unclear, if I only should see the ones where I have borrowable items and where I have a contract, or if I should see all with borrowable items and as an additional information, if I have contracts.

**Comment by nadjaweisskopf** [comment]
@phiku It should say: "Then I see the inventory pools which have borrowable items **OR** a contract for my user exists"
It is possible to create a contract without having borrowable items. I can explain this tomorrow in planning.

**Comment by nadjaweisskopf** [comment]
@phiku I have created an order in pool "Fundus" and can not see the park listed in the list of pools in the borrow section.

**Comment by phiku** [comment]
@nadjaweisskopf We have the following conditions to show a pool
"I see the inventory pools which have borrowable items or a contract for my user exists"
I am not sure, if the order fullfills this.

Btw I wanted to try it out, but Fundus has no borrowable Items, so how can I try this out?

**Comment by phiku** [comment]
@nadjaweisskopf I will remove myself from this Ticket and assign it to you.

**Comment by phiku** [comment]
@nadjaweisskopf Will be in 4.12.0.
