### ISSUE TITLE
Provide a VMWare for Stapo

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#430]
drtom [3:59 PM] 
@mfa ja lokales VMWare ist die Idee. So hat es @nimaai mit ersten Stapo instanz gemacht und ich mit der Chur instanz. Es gibt nur eine Sache zu Beachten: man muss das image exportieren. Die Files, die VMWare auf dem Mac erzeugt kann man warum auch immer nicht direkt auf VSphere (oder wie das Ding wieder heisst) laufen lassen. Es gibt sowas wie export image. (edited)

**Comment by eins78** [comment]
For the record: the 'Export' feature in Fusion GUI does not have any options. In this case, we needed to limit the required "virtual hardware version" of the exported machine. Options like this can only be set using the CLI `ovftool` which comes bundled with fusion. It can work from an already exported `.ovf` file or convert from original VM (`.vmx`) in 1 step:

```shell
$ /Applications/VMware\ Fusion.app/Contents/Library/VMware\ OVF\ Tool/ovftool -tt=OVF --maxVirtualHardwareVersion=13 '/path/to/VMs/leihs.vmwarevm/leihs.vmx' '/path/to/output/'                                                                                                                                              
Opening VMX source: /path/to/VMs/leihs.vmwarevm/leihs.vmx
Opening OVF target: /path/to/output/
Writing OVF package: /path/to/output/leihs/leihs.ovf
Transfer Completed 
Warning:
 - Line 30: The virtual hardware has been lowered from vmx-14 to vmx-13.
Completed successfully
```
