### ISSUE TITLE
Film: New filter on visits tabs

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#435]
- Visierungspflichtiger Filter auf Besuchen (bei allen drei Reiter Alle/Aushändigungen/Rücknahmen)

**Comment by nadjaweisskopf** [comment]
@nadja ask Roger if we should get rid of the role group manager and just have two filters "user in verifyable group" and "user and model in verifyable group"

**Comment by nimaai** [comment]
preparation: visits view https://github.com/leihs/leihs/commit/1cf0883278ed8bcb5d5c4748566d9c65374c69fd

**Comment by nadjaweisskopf** [comment]
@nadja will be refactored to react - test accordingly!

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/bc9afd0fd4bbf46208165e005896e7725b78d523

**Comment by nadjaweisskopf** [comment]
@nimaai I'll show them the new filter - if they want the same filter for orders and contracts, I'll create a new ticket.

**Comment by nadjaweisskopf** [comment]
@nimaai the time frame is shown in a wrong format. 2018-02-21 instead of 21.02.2018

![bildschirmfoto 2018-02-21 um 09 08 27](https://user-images.githubusercontent.com/3356016/36469273-f78c44b4-16e6-11e8-8f35-3feea58e5bcf.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/d2492438b9c678f54c41e6f92af34c42589ab1ac

**Comment by nadjaweisskopf** [comment]
@nimaai in production, the take back icon had an arrow going from right to left. Now both take back and hand over have the same icon. Something small... we could also solve this in the next iteration, then please comment and close the ticket.

**Comment by nadjaweisskopf** [comment]
Will move points 1 - 6 to a new ticket for current iteration.

**Comment by nimaai** [comment]
7. fixed: https://github.com/leihs/leihs/commit/1aa4693255103ae22a0ca091f123353d66a45744
