### ISSUE TITLE
Missing translations on "Create new item" page

### ISSUE THREAD

**Issue by rosstitmarsh** [leihs/leihs#437]
#### Expected behaviour
Buttons in inventory code section on the "Create new item" page should be translated.

[_"zuletzt verwendet +1"_](https://github.com/leihs/leihs_legacy/blame/master/app/assets/javascripts/components/expert/field-inputs/input-inventory-code.jsx#L78) -> _"Last used +1"_

[_"Lücken auffüllen"_](https://github.com/leihs/leihs_legacy/blame/master/app/assets/javascripts/components/expert/field-inputs/input-inventory-code.jsx#L82) -> _"Fill in the gaps"_

 [_"höchstmöglich"_](https://github.com/leihs/leihs_legacy/blame/master/app/assets/javascripts/components/expert/field-inputs/input-inventory-code.jsx#L76) ->_"Highest possible"_

#### Actual behaviour
Buttons in inventory code section on the "Create new item" page are always in German.

#### Steps to reproduce

1. Open the demo
2. Navigate to an inventory
3. Click "Add Inventory" -> "Item"
3. The untranslated text is in the inventory code section

#### Specifications
- Leihs version: 4.8.0 Demo

**Comment by phiku** [comment]
Implemented and ready on test.
