### ISSUE TITLE
Installation is crushing at TASK [leihs-system-install : create jar]

### ISSUE THREAD

**Issue by soma115** [leihs/leihs#438]
#### Expected behaviour
TASK [leihs-system-install : create jar] should finish successfully.

#### Actual behaviour
Following error appears:

TASK [leihs-system-install : create jar] **************************************
fatal: [root@192.168.124.40 -> localhost]: FAILED! => {"changed": true, "cmd": "#/bin/bash\n set -eux\n DEPLOY_DIR='/home/r/Downloads/leihs/deploy'\n cd $DEPLOY_DIR/../system\n $DEPLOY_DIR/bin/lein uberjar", "delta": "0:00:28.721237", "end": "2017-11-26 15:59:28.355619", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-26 15:58:59.634382", "stderr": "+ DEPLOY_DIR=/home/r/Downloads/leihs/deploy\n+ cd /home/r/Downloads/leihs/deploy/../system\n+ /home/r/Downloads/leihs/deploy/bin/lein uberjar\nRetrieving com/cemerick/clojurescript.test/0.2.3-SNAPSHOT/clojurescript.test-0.2.3-20140317.141743-3.pom from clojars\nRetrieving com/cemerick/clojurescript.test/0.2.3-SNAPSHOT/clojurescript.test-0.2.3-20140317.141743-3.pom from clojars\nCould not transfer artifact com.cemerick:clojurescript.test:pom:0.2.3-20140317.141743-3 from/to clojars (https://clojars.org/repo/): Checksum validation failed, could not read expected checksum: Read timed out\nThis could be due to a typo in :dependencies or network issues.\nIf you are behind a proxy, try setting the 'http_proxy' environment variable.\nUberjar aborting because jar failed: Could not resolve dependencies", "stderr_lines": ["+ DEPLOY_DIR=/home/r/Downloads/leihs/deploy", "+ cd /home/r/Downloads/leihs/deploy/../system", "+ /home/r/Downloads/leihs/deploy/bin/lein uberjar", "Retrieving com/cemerick/clojurescript.test/0.2.3-SNAPSHOT/clojurescript.test-0.2.3-20140317.141743-3.pom from clojars", "Retrieving com/cemerick/clojurescript.test/0.2.3-SNAPSHOT/clojurescript.test-0.2.3-20140317.141743-3.pom from clojars", "Could not transfer artifact com.cemerick:clojurescript.test:pom:0.2.3-20140317.141743-3 from/to clojars (https://clojars.org/repo/): Checksum validation failed, could not read expected checksum: Read timed out", "This could be due to a typo in :dependencies or network issues.", "If you are behind a proxy, try setting the 'http_proxy' environment variable.", "Uberjar aborting because jar failed: Could not resolve dependencies"], "stdout": "", "stdout_lines": []}

#### Steps to reproduce
This behavior apeared on:
- ubuntu-16.04.3-server-amd64 with Python 2.7.12 installed (fresh install)
- debian-9.2.1-amd64-netinst (fresh install)
- Control machine is Fedora 26. SFTP, ssh on rsa key is working. 
No other specific circumstances seams to be in place.

#### Related issues
Repository https://clojars.org/repo/ is accessible from managed node but I can't see there "clojurescript.test/0.2.3-SNAPSHOT/clojurescript.test-0.2.3-20140317.141743-3.pom"
Perhapse it is enough to update this path?

#### Specifications
- Leihs version: 4.8.0
- Browser version: n/a
- MySQL/PostreSQL version: n/a

**Comment by nadjaweisskopf** [comment]
@soma115 please reopen this ticket, if problem still persists.
