### ISSUE TITLE
Keep filter settings in inventory

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#439]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
Keep the filter settings in inventory list after

- [ ] editing a model
- [ ] editing a software
- [ ] copying an item

#### Actual behaviour
Filter settings are set back

#### Steps to reproduce
1. go to inventory list
2. set a filter
3. edit a model or a software
4. save or close
5. filters are set back

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Implemented and ready on test.

**Comment by phiku** [comment]
Demo: 

Only if you click on the inventory tab at the top, the filters should be reset, otherwise they should stay. 
<img width="1440" alt="bildschirmfoto 2016-03-01 um 11 07 14" src="https://user-images.githubusercontent.com/16756048/33552712-41afa966-d8f6-11e7-9dde-262945710d8f.png">
