### ISSUE TITLE
Show contact person in swap user dialog

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#440]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
show user in swap user dialog when changing a borrower. 

#### Actual behaviour
Only the delegation is shown on the right but not the contact person

#### Related issues
#415

**Comment by phiku** [comment]
Most likely broken since big order refactoring.

**Comment by phiku** [comment]
Fixed and ready on test.

**Comment by phiku** [comment]
Demo:

1. Open https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/orders
2. Edit one of the orders. 
3. Change order person (search for "Acoustic" to define a Delegation as orderer).
