### ISSUE TITLE
Analyse: Sort order list by date and user

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#441]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
First see github.com/leihs/leihs/wiki and relishapp.com/leihs. Then provide a short but meaningful description of the expected behaviour.

#### Actual behaviour
Provide a short but meaningful description of the actual behaviour.

#### Steps to reproduce
Please include the role of the logged in user as well as precise steps starting with logging in upto the occurence of the problem.

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Implemented and ready on test.

**Comment by phiku** [comment]
Demo:

1. Open https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/orders
2. Find a person who has orders at different days. 
3. The orders should be grouped by the person on the list, not only ordered by creation date.
