### ISSUE TITLE
import expects fields "building" and "room"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#444]
I get following error, when importing items. Probably since the fields room and building are mandatory. 

- [ ] Adjust the GUI and show fields "room" and "building" as mandatory

![bildschirmfoto 2017-11-28 um 13 59 21](https://user-images.githubusercontent.com/3356016/33321040-707788a6-d444-11e7-8a5e-33a3265d92bf.png)

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0
- MySQL/PostreSQL version:

**Comment by nimaai** [comment]
@nadjaweisskopf I would ignore this for the moment, as we want to devise, specify and implement the import functionality from scratch. It is also not (properly) tested at the moment anyways and I think we at ZHdK don't use it also. Ok?

**Comment by nadjaweisskopf** [comment]
@nimaai Don't show tab "Import" anymore - fix bug later

**Comment by nadjaweisskopf** [comment]
@nimaai I will create an own ticket to check which kind of import is needed at ZHdK. In this ticket we will just disable the tab "Import"
