### ISSUE TITLE
Translation needed: item saved / Gegenstand gespeichert

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#445]
See printscreen: 

![bildschirmfoto 2017-11-28 um 14 28 04](https://user-images.githubusercontent.com/3356016/33322361-635918a6-d449-11e7-9253-388606187580.png)

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Implemented.

**Comment by nadjaweisskopf** [comment]
@phiku The message when saving licenses is also "Gegenstand gespeichert" - should I create a new ticket for a seperate text for licenses?
