### ISSUE TITLE
Change scenarios for field supplier

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#447]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
When I edit an item, I want to be able to choose a supplier but not create one. Suppliers should only be created in the Admin section.

Following scenarios need to  be adjusted:

  Scenario: Create new supplier if it does not already exist
    Given I edit an item that belongs to the current inventory pool
    When I enter a supplier that does not exist
    And I save
    Then a new supplier is created
    And the edited item has the new supplier

  Scenario: Do not create a new supplier if one of the same name already exists
    Given I edit an item that belongs to the current inventory pool
    When I enter a supplier
    And I save
    Then no new supplier is created
    And the edited item has the existing supplier

@flapping
  Scenario: Creating a new supplier if it does not already exist
    Given I am Mike
    And I create an item
    And I choose "Investment" as reference
    And these required fields are filled in:
    | Model        |
    | Inventory Code|
    | Project Number |
    | Supply Category |
    When I enter a supplier that does not exist
    And I save
    Then a new supplier is created
    And the created item has the new supplier

#### Actual behaviour
A supplier can be created ad hoc when editing or creating an item. 

#### Steps to reproduce
1. edit an item
2. enter a supplier which does not exist yet
3. save the item
4. a new supplier is created

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
@nadjaweisskopf I think we do not need these tests anymore, since we do not create a supplier anymore in the create/edit item pages.

**Comment by nadjaweisskopf** [comment]
@nadja check with current release
