### ISSUE TITLE
Show inventory code to Lending mgr.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#448]
#### Expected behaviour
Lending mgr. should _see_ the inventory code when editing an item. He should not be able to change the code. 
For items and sw-license

I could not find a scenario for this case but please have another look. 

#### Actual behaviour
The inventory code is not shown to Lending mgrs. when editing an item. 

#### Steps to reproduce
1. log in as lending mgr.
2. edit an item
3. you do not see the inventory code

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari

**Comment by phiku** [comment]
Always show inventory code, independent of role...

**Comment by phiku** [comment]
@nadjaweisskopf How can I login as lending manager?

**Comment by nadjaweisskopf** [comment]
@phiku edit your user, and select "lending mgr.". The role is changed immediately. Afterwards, if you need higher rights again, then go to Admin section, edit the pool and add yourself as Inventory mgr.

**Comment by phiku** [comment]
@nadjaweisskopf Ok now I realize that inventory code is actually mandatory, but on production if you are the lending manager you cannot see it when you create a new item. Now you always see it, independent of your role. Its hardcoded, but i am not yet sure if it should be part of the fields configuration.

**Comment by phiku** [comment]
There is the general question, how to make sure, that you can see all the mandatory fields. Furthermore we must test what happens, if you save and you cannot see the mandatory fields.
