### ISSUE TITLE
Cannot delete group-assignment in edit-user page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#450]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I need to be able to delete a group-assignment when editing a user.

#### Actual behaviour
When editing a user and removing the group assignment, then saving and reediting the user, the group has not been deleted. 

#### Steps to reproduce
1. type "daniel hug" in the global search field
2. edit the user
3. delete the assignment to the group "IAD-Forschung" 
4. save
5. reedit user
6. group has not been deleted and I did not get any message, that deleting the group is not possible

Same behaviour for example with mathias bokor. 

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0 and firefox quantum

**Comment by DrTom** [comment]
@nadjaweisskopf dieser Bug ist auch auf Staging in der Version 4.9.0-RC.7 vorhanden. Wenn ich es richtig sehe, dann ist mein code noch gar nicht auf Staging. Wenn dem so ist, dann hat dieser Bug nichts mit der API und Sync zu tun.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f529d93d2819acaccb8e1be6cb674d622efe778d
