### ISSUE TITLE
Can not take back sw-licenses

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#453]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
Should be able to take back all sw-licenses of contract 11C0

#### Actual behaviour
Endless spinner when editing take back of Stefan Birrer

#### Steps to reproduce
1. go to pool ITZ-Software
2. Edit take back of Stefan Birrer, contract nr. 11C0
3. availability is spinning endlessly

#### Specifications
- Leihs version: 4.8.0
- Browser version: safari 11.0

![bildschirmfoto 2017-12-05 um 09 22 49](https://user-images.githubusercontent.com/3356016/33596987-353856f8-d99e-11e7-9441-6103f67b5bd3.png)

Contract: [CAMPUSPRINT_IO-CP-4C12_4203_001.pdf](https://github.com/leihs/leihs/files/1530235/CAMPUSPRINT_IO-CP-4C12_4203_001.pdf)

**Comment by eins78** [comment]
- there is some server-prepared data the frontend uses for functionality that runs in the browser
- for some reason, Software & Licences were explicitly excluded from this prepared data
- fix removes the exlusion, but I have no idea why it was done in the first place.

**Comment by eins78** [comment]
fixed https://github.com/leihs/leihs_legacy/commit/54376dcbf547fbbb9e55649e0f869c3bd3fc2b80

**Comment by nadjaweisskopf** [comment]
@eins78 the last take back of sw was two month ago, until then, taking back sw-license worked. So the problem can not be older than two month. The error msg. says it can not find the model. Since when is this exclusion in leihs?

**Comment by eins78** [comment]
@nadjaweisskopf It was like this since order/contracts refactoring, 2 months ago https://github.com/leihs/leihs_legacy/commit/7d67b28736bd76c207f431dceee1ab61da5491bb#diff-7e0a8458dc699111426b915f9b9239c8R243
