### ISSUE TITLE
Endless spinner when increasing the amount of an option manually in hand over

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#454]
#### Actual behaviour
When adding an option to a hand over and changing the amount from 1 to 15 and then back to 4 the availability calculates endless - endless spinner

#### Steps to reproduce
Please include the role of the logged in user as well as precise steps starting with logging in upto the occurence of the problem.

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Reproduction: 
1. Open visits https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/visits
2. Click on Tab "Aushändigen"
3. Click on Button "Aushändigen" for one of the visits. 
4. Select an options in the search field.

**Comment by eins78** [comment]
@nadjaweisskopf what is the "expected behaviour"? ;)

- should the spinner not hang? (yes obvs.)
- should the availability for options be calculated, displayed, (validated, enforced, …)?
