### ISSUE TITLE
merge and deploy (Madek)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#455]
For the last four weeks I was working on the following tasks:
- https://www.pivotaltracker.com/story/show/132992383 - ready to merge
- https://www.pivotaltracker.com/story/show/132982429 - my part is done, there is one task left concerning API
- https://www.pivotaltracker.com/story/show/151050582 - the same situation as above
- https://www.pivotaltracker.com/story/show/151290301 - this ticket concerns multilingual metakey’s labels, descriptions & hints, there is one task left, I’m working on in right now

**Comment by eins78** [comment]
to merge/check:

- [ ] https://www.pivotaltracker.com/story/show/132992383 
- [ ] https://www.pivotaltracker.com/story/show/132982429 
- [ ] https://www.pivotaltracker.com/story/show/151050582 
- [ ] https://www.pivotaltracker.com/story/show/151290301
