### ISSUE TITLE
Refinement - Timeline and Calender

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#456]
Create a Prototyp of the new version of a timeline as discussed this morning with Pius and Roger  according to notes below (6.12.17).

**Zeitleiste**
- Scrollen bei vielen Gruppen ist mühsam - müsste alles oder mind. vieles auf einen Blick sichtbar sein. 
- Wenn in eine Genehmigung gewechselt wird, ist das Fenster weg
- Wechseln in Genehmigung/Aushändigung/Rücknahme ist wichtig und wird oft gemacht
- Anzahl 1 pro Zeile ist ok
- Gruppenzuteilungen sind schwierig
- Es ist wichtig zu wissen, weshalb ein Modell an einem bestimmten Datum rot ist
- Die Namen sind schon wichtig
- Erster Blick rot/grün - wichtig, dass die Studis die Zeitleiste nicht sehen, aus Datenschutzgründen
- Es ist wichtig zu wissen, ob es sich um eine Aushändigung, Rücknahme oder Bestellung handelt
- Verspätete Rücknahmen müssen sofort ersichtlich sein
- Verspätete Aushändigungen müssen sofort ersichtlich sein
- Die Besuchsliste wird für die Aushändigung und Rücknahme verwendet - wird für die Vorbereitung verwendet - man sieht die Menge der Gegenstände. Bei vielen Gegenständen wird der Wagen vorbereitet, es wird ein Termin auf den Morgen vereinbart und in eine eigenen Sitzung ausgehändigt. 
- Anhand der Namen weiss man, inwiefern ein Gegenstand evtl. noch zurück kommt. Man kennt die Leute mit der Zeit. 
- Gruppenzuteilungen wäre schön - aber der Mechanismus müsste geklärt werden - woher wird welcher Gegenstand genommen
- Vergangenheit ist in der Zeitleiste nicht wichtig. Diese Info will ich auf einen Blick sehen, wenn ich den Gegenstand in der globalen Suche suche, finde ich die Info schneller
- Farben sind immer schön
- Eine Zeitleiste für die Reservationen eines einzelnen Benutzers wird nicht benötigt
- Zeitleiste wird angeschaut, wenn Kalender rot anzeigt
- Die wichtigste Zahl ist die Total verfügbare. In einem zweiten Schritt werden die Gruppen angeschaut. 
- Farben helfen und müssten auch in der neuen implementiert werden. Bspw. rot bei noch nicht zurückgenommen. 

**Kalender**
- Grün/Rot ist wichtig um zu sehen, kann die Ausleihe erfolgen oder nicht, kann eine Rücknahme erfolgen oder nicht
- Einen ersten Blick entscheidet über Anfragen zu späteren Aushändigungen oder Rücknahmen - rasche Entscheidungen sind am Schalter wichtig
- Dann ist auch wichtig, wenn der Studi mehr als die bestellte Menge benötigt, ob noch weitere Gegenstände ausgehändgit werden können. Dafür ist die Verfügbarkeitszahl wichtig pro Gruppe. 
- Aus dem Kalender die Verfügbarkeitsliste öffnen wäre allenfalls schön.
- Kalender beinhaltet nur ja nein, die Infos von der Zeitleiste brauchts unbedingt

**Comment by phiku** [comment]
Old:
http://phiku.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/models/21c2b7ac-0645-5d7e-8b17-ad8047ca89da/timeline

New:
http://phiku.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/models/21c2b7ac-0645-5d7e-8b17-ad8047ca89da/new_timeline

**Comment by nadjaweisskopf** [comment]
@phiku They are happy with this version of time line but before they start testing they would like to have following changes: 
- red colour when amount is 0
- colour lines which should already have been brought back in red

**Comment by nadjaweisskopf** [comment]
@nadja a hand over or order does not have an assignment to groups

**Comment by nadjaweisskopf** [comment]
@phiku sent an invitation for the 10th of jan to present the new timeline to Pius, Imanol and Roger.

**Comment by nadjaweisskopf** [comment]
@phiku Could you please have a look at packages before I inform Roger? For packages no numbers are applicable.

**Comment by kudi82** [comment]
@nadjaweisskopf I can not close this ticket.
