### ISSUE TITLE
Show status of licenses in inventory list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#458]
#### Expected behaviour
If a license is not lendable or retired, we need to show both states - same behaviour with models. 

#### Actual behaviour
No state is shown. 

#### Steps to reproduce
1. go to inventory list ITZ-Software
2. edit a license
3. retire license
4. check inventory list --> no state is shown
5. set state of license to "not available"
6. check inventory list --> no state is shown

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0

Here an example of a model which is retired and not lendable. 
![bildschirmfoto 2017-12-06 um 12 55 01](https://user-images.githubusercontent.com/3356016/33660616-c3cfab1e-da84-11e7-8029-f70ab1dd5a49.png)

**Comment by phiku** [comment]
Is it correct, that this neither works on production already?

**Comment by nadjaweisskopf** [comment]
nadja: check scenario for models

**Comment by phiku** [comment]
Implemented to work similar like for items.
