### ISSUE TITLE
Create model with attachments results in server error

### ISSUE THREAD

**Issue by phiku** [leihs/leihs#462]
1. Open https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/models/new
2. Select any product name (one which does not yet exist of course).
3. Add one attachment (e.g. a small image). 
4. Save
5. 500 Error

**Comment by phiku** [comment]
@nadjaweisskopf Please assign the right labels (i dont know which ones).

**Comment by nadjaweisskopf** [comment]
@phiku it works, if you attach a pdf as attachment. Pictures don't work.

**Comment by eins78** [comment]
It was a frontend problem. there was some code handling the uploading of images for newly created models/software, but it was not handled for attachments. 
Added the missing code and adapted specs so those cases are tested.
