### ISSUE TITLE
Field Editor

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#465]
Requirements for field editor

1. A leihs instance has a set of fields 
2. The admin can add new field groups 
3. The admin can add new fields of the type string, number, dropdown with values for existing groups--> the field is not automatically active in pools. 
4. The admin can set a field to "search in global search". The field is then added to the searchable fields for global search.
5. The admin can set a field as mandatory --> what shall we do with emtpy (existing) values?
6. The admin can rename fields (apart from mandatory leihs fields)
7. The admin can set fields as active or not active (apart from core fields)
8. The admin can delete fields which have not been used by any item (apart from core fields)
9. The admin can change the order of the fields inside a group (apart from core fields) 
10. The admin can move fields into other groups (apart from core fields)
11. An inventory manager can hide a field from the pools item-fields (apart from core fields)
12. An inventory manager can unhide an existing field from the pools item-fields (apart from core fields)
**13. field settings are per pool, not per user** 
14. Inventory manager should have a view for the fields configuration of his pool.

**Comment by nadjaweisskopf** [comment]
Translations of groups and fields?

**Comment by phiku** [comment]
@nadjaweisskopf Is delivered to master and ready on test.

**Comment by gurmir** [comment]
If I want to test with Firefox I cant edit any fields. When I change to another broser for example Internet Explorer than I can edit the fields. More Information see the Print Screen from Developer Mode by Firefox
![error_message](https://user-images.githubusercontent.com/37148448/37153432-fe503434-22dc-11e8-9066-85b637fa9a9a.PNG)

**Comment by phiku** [comment]
Its actually obvious that it does not work, since the event is called "e" and the passed event ist called "event": 
```
    renderEditButton(fieldId) {
      return (
        <div className='col-sm-4 text-right line-actions'>
          <a onClick={(e) => this.onEditClick(event, fieldId)} className='btn btn-default'>
            Editieren
          </a>
        </div>
      )
    },
```
Why it works on Safari is the riddle :-)

**Comment by gurmir** [comment]
For me eighter. But now I can start running with the testcases.

**Comment by gurmir** [comment]
Tests are completet for this Case. All Tests was successfully done. Some field names does not translate to German in the Backend. Frontend is completely translated.

**Comment by gurmir** [comment]
Additional Information for translating Field Editor Backend:
Please Tranlate dynamic and static fields in the Admin-Interface. The list is not compleatly translated.

**Comment by nadjaweisskopf** [comment]
Test results:
- we need a setting to filter license fields and item fields
- add popups to the titles "dynamic" / "static" which explain the difference of these field types.

**Comment by nadjaweisskopf** [comment]
Will close the ticket and create a new one for all points mentioned above.
