### ISSUE TITLE
Supplier-DB

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#466]
Website und Logins für geschützten Zugang STAPO

Possibly provide 
- a UUID (already exists)
- a name field (already exists)
- Provide a note field
- Links in note field should be klickable

Ask Stapo what they want to do with the information.

**Comment by eins78** [comment]
notiz eintragen:
![screen shot 2018-01-24 at 09 47 51](https://user-images.githubusercontent.com/134942/35322839-f0649026-00eb-11e8-9533-aec00e42882d.png)

notiz anzeigen:
![screen shot 2018-01-24 at 09 48 03](https://user-images.githubusercontent.com/134942/35322844-f235d77a-00eb-11e8-97b1-9ac7c5f3c198.png)

---
---
---

gegenstände nach pool gruppiert

![screen shot 2018-01-24 at 09 48 11](https://user-images.githubusercontent.com/134942/35322847-f42f7b58-00eb-11e8-8c83-309ee8bd8882.png)

---
---
---

Liste mit counts & filter nach pool:

![screen shot 2018-01-24 at 09 46 04](https://user-images.githubusercontent.com/134942/35322822-e2af1b86-00eb-11e8-8d43-90532e701886.png)


![screen shot 2018-01-24 at 09 46 47](https://user-images.githubusercontent.com/134942/35322830-e49fa5aa-00eb-11e8-9162-c03ce4b3de70.png)

---
---
---
