### ISSUE TITLE
When switching to a delegation I get an error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#469]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
Swtiching to a delegation should navigate to the borrow section. 

#### Actual behaviour
I get an error when switching to a delegation. 

#### Steps to reproduce
1. log in to any system (prod, staging... )
2. switch to delegation "itz-test delegation"
3. error shows up

#### Specifications
- Leihs version: 4.9.0
- Browser version: safari 11.0

![bildschirmfoto 2017-12-13 um 10 00 12](https://user-images.githubusercontent.com/3356016/33930296-b1a7dd40-dfec-11e7-88b6-fc946e3a197d.png)

![bildschirmfoto 2017-12-13 um 10 15 18](https://user-images.githubusercontent.com/3356016/33930874-a1b1211a-dfee-11e7-8342-6a14f38110e1.png)

**Comment by DrTom** [comment]
Fixed with https://github.com/leihs/leihs_legacy/commit/f52b407f4b00b46b38a40c55997fa4105de50771

**Comment by nadjaweisskopf** [comment]
Could not reproduce the error
