### ISSUE TITLE
Automatically approve orders for models that have "auto-approve" set

### ISSUE THREAD

**Issue by psy-q** [leihs/leihs#47]
This was requested by two universities who have relatively few collissions on bookings, so that bookings could be automatically approved.

Add a flag "auto-approve" to models for specific inventory pools. When an order contains only such models, automatically approve it. The flag would probably need to be per inventory pool, since not everyone on an instance may agree on this.

There is a story for this in Pivotal but please note that it's **very unlikely** that the ZHdK leihs developers will be allowed to develop this feature, so it would have to be created  by someone else in the community. We're happy to merge it back to vanilla leihs, though.

https://www.pivotaltracker.com/story/show/13851331

**Comment by nadjaweisskopf** [comment]
@timo67 @AnthonyHunt An inventory pool at ZHdK has come up with the same requirement. I will check their need and inform you about any further development or testing on this issue.
