### ISSUE TITLE
Problem Upgrading LEIHS from v3 via Ansible-Playbooks

### ISSUE THREAD

**Issue by HSLUwem** [leihs/leihs#478]
#### Expected behaviour
Update from LEIHS v3.45.1 to LEIHS v4.x with Ansible. Playbook is running until data import.

#### Actual behaviour
Ansible Run stops at task "[import-v3-into-v4 : do import]. See attachment for more details...

#### Steps to reproduce
Remote session possible to show and solve the problem.

#### Specifications OLD Leihs
- OS Host: Ubuntu 16.04
- Leihs version OLD Host: 3.45.1
- MySQL version:  5.7.19-0ubuntu0.16.04.1

#### Specifications New Leihs
- OS Host: Ubuntu 16.04
- Leihs version OLD Host: 4.x (Deploy with Ansible Playbook)
- PostreSQL version:  10.1

[import-v3-into-v4_do_import_failed.txt](https://github.com/leihs/leihs/files/1610991/import-v3-into-v4_do_import_failed.txt)

**Comment by nadjaweisskopf** [comment]
@DrTom HSLU are still trying to upgrade their production to the newest version. They need help on the step described above. Could you please analyse the error as soon as possible? Thanks.

**Comment by nadjaweisskopf** [comment]
@HSLUwem our developer is checking where the problem could be and will get back to you in around 1h.

**Comment by nimaai** [comment]
@HSLUwem I have pushed the fix to the following branch: https://github.com/leihs/leihs/tree/mk_next_fix_leihs_uuid_ns

Please check it out. Then add the following to the ansible vars of your v4 server YAML file:

`leihs_uuid_ns: "leihs"`

Then run the import playbook again.

**Comment by HSLUwem** [comment]
I checked out the fix, added the configuration value to the host_vars of my v4 server and ran the migration again. Same error as before...

**Comment by nimaai** [comment]
@HSLUwem Can you please attach the log?

**Comment by HSLUwem** [comment]
[import-v3-into-v4_do_import_failed_withfix.txt](https://github.com/leihs/leihs/files/1611639/import-v3-into-v4_do_import_failed_withfix.txt)

**Comment by nimaai** [comment]
It seems like you haven't checked out the branch properly. You should do the following from within the `leihs` directory:

```
git fetch --all
git checkout origin/mk_next_fix_leihs_uuid_ns
git submodule update --recursive
```

And then add the following to the ansible vars of your v4 server YAML file again:

`leihs_uuid_ns: "leihs"`

**Comment by nimaai** [comment]
@HSLUwem For security reasons better you take something specific for `leihs_uuid_ns`, something only you know and nobody else.

**Comment by nadjaweisskopf** [comment]
@HSLUwem please reopen the ticket if needed.
