### ISSUE TITLE
Show small preview for attachments (Fundus)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#479]
On inventory list there should be a preview shown for items if there is an attachment. At least it must be shown in edit item.
 
If showing attachments which are images is not possible, we have to think about introducing images in addition to attachments to items.

**Comment by phiku** [comment]
On inventory list there should be a preview shown for items if there is an attachment. At least it must be shown in edit item.

**Comment by phiku** [comment]
@nadjaweisskopf Now for edit item it is shown. If we want to show it on the inventory list, its a bit more complex, but doable. Perhaps make a new ticket for the inventory list, if we want to do this there too.

**Comment by nadjaweisskopf** [comment]
@phiku Ok, thanks. I just tested. Looks good. I would create a ticket it we we need to show the image in the inventory list.
