### ISSUE TITLE
Maximum lending time per model

### ISSUE THREAD

**Issue by psy-q** [leihs/leihs#48]
In the past, there has been some discussion about allowing a model to be booked only for e.g. 10 days in a row, with the system giving appropriate errors if someone tries to book longer.

Of course managers would have to be able to override all this, but they should get a warning.

https://www.pivotaltracker.com/story/show/6627889

**Comment by nadjaweisskopf** [comment]
@wolfgang-reutz @timo67 @AnthonyHunt An inventory pool at ZHdK has come up with the same requirement. I will check their need and inform you about any further development or testing on this issue.
