### ISSUE TITLE
Copy all name-strings into note-field for Fundus

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#480]
Fundus still needs the values of the field "name" which has been deactivated. Therefor they would be very glad if we could create a script and copy these values from the field "name" to the field "note".

**Comment by phiku** [comment]
Make script, where for all items the Field "name" in "General Information" is copied to Notiz:
eg. Name: De Boer
where owner and responsible is "Fundus-TdK"

**Comment by phiku** [comment]
@nadjaweisskopf The script is ready to execute. It seems to work on test. Tell me when you will check it (because if somebody else deploys to test, it will be reverted).

**Comment by phiku** [comment]
![bildschirmfoto 2018-01-10 um 10 34 38](https://user-images.githubusercontent.com/16756048/34765570-2e80229e-f5f2-11e7-8c41-59d579d8f92b.png)
![bildschirmfoto 2018-01-10 um 10 34 43](https://user-images.githubusercontent.com/16756048/34765571-2ea60824-f5f2-11e7-8b7f-1a117d36f3fa.png)
![bildschirmfoto 2018-01-10 um 10 34 47](https://user-images.githubusercontent.com/16756048/34765572-2ed0dbb2-f5f2-11e7-8126-203418cf5722.png)
![bildschirmfoto 2018-01-10 um 10 34 51](https://user-images.githubusercontent.com/16756048/34765573-2ef67f66-f5f2-11e7-89df-2f34ee9e0e1e.png)
![bildschirmfoto 2018-01-10 um 10 34 55](https://user-images.githubusercontent.com/16756048/34765574-2f1b35c2-f5f2-11e7-958f-38f796f64ef0.png)
![bildschirmfoto 2018-01-10 um 10 35 44](https://user-images.githubusercontent.com/16756048/34765576-2f4568f6-f5f2-11e7-9681-3b79ad94cc81.png)
![bildschirmfoto 2018-01-10 um 10 35 48](https://user-images.githubusercontent.com/16756048/34765577-2f6feefa-f5f2-11e7-9316-dc55b36f27a6.png)
![bildschirmfoto 2018-01-10 um 10 35 54](https://user-images.githubusercontent.com/16756048/34765578-2f96b81e-f5f2-11e7-97fb-3ed4843f5c70.png)
![bildschirmfoto 2018-01-10 um 10 35 58](https://user-images.githubusercontent.com/16756048/34765579-2fbd73be-f5f2-11e7-8f90-f8453ffd66d1.png)
![bildschirmfoto 2018-01-10 um 10 36 10](https://user-images.githubusercontent.com/16756048/34765580-2fe300ca-f5f2-11e7-9409-3bef9bd8f7d2.png)

**Comment by phiku** [comment]
```
# run with "rails runner -e production PATH_TO_THIS_FILE"
# WARNING: USE AT YOUR OWN RISK!!!

query = <<-SQL
  with fundus_item_ids
  as (
  	select
  		distinct items.id
  	from
  		items,
  		inventory_pools
  	where
      items.inventory_pool_id = inventory_pools.id
      and items.owner_id = inventory_pools.id
  		and inventory_pools.name = 'Fundus-TdK'
  )
  update
  	items
  set
  	note = (
      select case
        when items.note is null or items.note = '' then
          'Name: ' || name
        else
          items.note || chr(10) || 'Name: ' || name
      end
    )
  where
  	items.id in (select * from fundus_item_ids)
    and items.name is not null
    and items.name <> ''
SQL

ActiveRecord::Base.transaction do
  ActiveRecord::Base.connection.exec_update query
end
```

**Comment by nadjaweisskopf** [comment]
@phiku two changes to the script: 
1. please copy the strings without the prefix "Name:"
2. don't copy the strings "no name" and "ohne Namen"

**Comment by phiku** [comment]
Items to test:
AUS27415
F3513
F1831
FUN5866
FUN9029
FUN9029
FUN665
FUN6364
F2011
FUN6584
FUN6363

**Comment by nadjaweisskopf** [comment]
@phiku ok, perfect, thanks! You can run the script on production as soon as you like.
