### ISSUE TITLE
Include "reason" in global search and visits (Fundus)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#481]
In global search and visits one should be able to search for a string which occurs in purpose/reason and all contracts should be shown.

**Comment by phiku** [comment]
In global search one should be able to search for a string which occurs in purpose/reason and all contracts should be shown.

In "List of orders" and "visits" it is already implemented.

**Comment by phiku** [comment]
@nadjaweisskopf I could search for "Beleuchtungstests" on test and found the contracts. We first have to find a case on test (or better staging or prod) where it occurs again. The search actually at the moment already checks the purpose.

**Comment by phiku** [comment]
@nadjaweisskopf The search for "visits" at the moment only checks the following fields:

```
      sql = sql.where(User.arel_table[:login].matches(q)
                      .or(User.arel_table[:firstname].matches(q))
                      .or(User.arel_table[:lastname].matches(q))
                      .or(User.arel_table[:badge_id].matches(q)))
```

**Comment by phiku** [comment]
@nadjaweisskopf For "global search" it is already on test working. Now the question, should we really check the contracts purposes in visits? I seems, that this is not the idea of "visits".

**Comment by nadjaweisskopf** [comment]
@phiku I found out, that in global search the search result is only shown if the reason has been added through an order. If a contract has been created in the manage section of leihs, without having received an order in advance, the contract is not found. I'll describe the needed more precisely.

**Comment by nadjaweisskopf** [comment]
@nadja check in global search if orders, visits and contracts are searchable

**Comment by nadjaweisskopf** [comment]
orders, visits and contracts are searchable
