### ISSUE TITLE
link in pool-list of borrow sections should be klickable

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#482]
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
First see github.com/leihs/leihs/wiki and relishapp.com/leihs. Then provide a short but meaningful description of the expected behaviour.

#### Actual behaviour
Provide a short but meaningful description of the actual behaviour.

#### Steps to reproduce
Please include the role of the logged in user as well as precise steps starting with logging in upto the occurence of the problem.

#### Related issues
If you have found some already existing issue(s) which this one relates to, then you can mention it (them) here.

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Links in Gerätepark list in borrow should be clickable.

**Comment by phiku** [comment]
ready on test

**Comment by nadjaweisskopf** [comment]
check error https://test.leihs.zhdk.ch/borrow/inventory_pools
![bildschirmfoto 2018-01-10 um 15 32 44](https://user-images.githubusercontent.com/3356016/34979632-28500d12-faa2-11e7-8220-a47cf4342e4b.png)

**Comment by nadjaweisskopf** [comment]
@nadja might change behaviour, check access rights and not contracts
