### ISSUE TITLE
Show correct msg. when saving a sw-license

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#486]
#### Expected behaviour
When saving an item, I expect to see "Gegenstand gespeichert"
When saving a sw-license I expect to see "Lizenz gespeichert"

#### Actual behaviour
behaviour for items is correct. 
When saving a sw-license I also see the msg. "Gegenstand gespeichert"

#### Steps to reproduce
1. save a sw-license
2. check msg.

#### Related issues
https://github.com/leihs/leihs/issues/445

#### Specifications
- Leihs version: 4.11.0
- Browser version: safari 11.0

![bildschirmfoto 2018-01-10 um 15 32 44](https://user-images.githubusercontent.com/3356016/34777730-894b86d6-f61b-11e7-8cfa-e6b40d0d3a90.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/892ce3e276d5f545700ed6f4ce9eefae901ed09e
