### ISSUE TITLE
Remove or constraint entitlements.inventory_pool_id

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#488]
We have `entitlements.inventory_pool_id` and `entitlement_groups.inventory_pool_id` which should have the same value because of `entitlements.entitlement_group_id = entitlement_groups.id`.

It's redundant and more over not consistency safe.

We should either remove `entitlements.inventory_pool_id` and adjust our code accordingly or introduce a consistency check in DB.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/11ef084ac9db4c13b3154d49950205ecc47a6488

`entitlements.inventory_pool_id` removed.

**Comment by nadjaweisskopf** [comment]
test booking calender
