### ISSUE TITLE
Change text of error msg.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#489]
@phiku Could you please change the error msg. as following:

Now: There exists already a model with the same product name with empty version.
New: A model with the same product name and empty version already exists.

Now: There exists already a model with the same product name and version.
New: A model with the same product name and version already exists.

#### Related issues 
https://github.com/leihs/leihs/issues/414

#### Specifications
- Leihs version: 4.11.0
- Browser version: safari

**Comment by phiku** [comment]
Will be in 4.12.0.
