### ISSUE TITLE
Impossible to add inventory, and use other functions on Debian 9

### ISSUE THREAD

**Issue by gcioffi** [leihs/leihs#491]
#### Expected behaviour
System working as expected. 
I installed LEIHS version 4 in July on a Debian 8 server and it worked as expected. Now I have reinstalled on a Debian 9 and only some sections work.

#### Actual behaviour
Some sections, as admin homepage are fine. Others do not work at all. For example in inventory tab, add items, export and user's buttons (top right) do not work.

#### Steps to reproduce
Installation as in Wiki Deployment section.
Created initial user. 
Added new pool.
Inventory tab, impossible to add inventory, export and use other functions.

#### Related issues
Both the current installation as the previous one have been carried out on new servers and  I have not installed any additional program since I thought that LEIHS installation process installs all software needed. 

#### Specifications
- Leihs version: 4.12.0
- Browser version: Mozilla FireFox 58.0 (64-bit)
- MySQL/PostgreSQL version: That installed with LEIHS.

**Comment by eins78** [comment]
Hi, two things:

- can you please try again with a current version (the `stable` branch on https://github.com/leihs/leihs/)? I don't think its the issue, but not knowing the exact version makes debugging even harder.

- please elaborate on what "doesn't work" mean? Is there nothing happening at all, or do you get some kind of error (if so, which)?

As an aside, I just did an manual setup of leihs on a fresh Debian 9 server just last week, when testing our new "deployment inventory template". You might want to check it out, if you are setting up a new leihs anyways it might be of help.

**Comment by nadjaweisskopf** [comment]
@gcioffi Adding an item with the first PostgreSQL version (4.0) did indeed not work. We solved the problem in a further version. So please install the newest version as @eins78 mentioned before. Might really already solve all problems.

**Comment by gcioffi** [comment]
Hi thank you for your help.

I'd have a quick question, what do I need to do to uninstall it so that I can try the current version?

@eins78 It doesn't work means nothing happens. I attached a screenshoot, showing what I get when click on  Add Inventory

![notworking](https://user-images.githubusercontent.com/32298645/35539508-3085a900-0552-11e8-9f7e-d70bb802f57a.PNG)

**Comment by gcioffi** [comment]
Hi,
I am trying to install the current version on branch stable. but I get the attached error. Any idea about it?
![error_screenshot](https://user-images.githubusercontent.com/32298645/35732135-a1ed5b60-0818-11e8-9a91-d2f24f7524da.PNG)

**Comment by gcioffi** [comment]
Hi, 
Issue solved. I was initially a bit confused by the comments in the #335 , but actually the error came from the code get_deploy_info_facts.rb in deploy/library which I think runs on the control node, and not on the managed node as I initially though.

I didn't have ruby installed on the control node, so installing it solved the problem.

I close this issue (and open a new one asking information about LDAP connection).
Thank you.
