### ISSUE TITLE
Update Wiki and Release Guide (self hosted leihs)

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#493]
#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by nadjaweisskopf** [comment]
needs review by matus

**Comment by nadjaweisskopf** [comment]
Asked Panter for help on updating documentation

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs-instance/commit/840a6d4e58b55df6feda911a1d3f65aaf368dc15 and https://github.com/leihs/leihs-instance/commit/c0ab657c0f867eabb85a9c6ec6034c34084a89d8
soliciting feedback here: https://github.com/leihs/leihs-instance/issues/7
