### ISSUE TITLE
Visits are shown twice on visits page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#496]
#### Expected behaviour
Each visit should only be shown once on visits page. 

#### Actual behaviour
The visits page shows each user (at least) twice - check users Rokas Sydeikis or Timofey Matveev

#### Steps to reproduce
1. Go to pool "Ausleihe Toni-Areal"
2. Go to lending/visits page
3. Check users mentioned above, Timofey is listed twice

![bildschirmfoto 2018-02-09 um 09 06 34](https://user-images.githubusercontent.com/3356016/36019381-63929d5a-0d7f-11e8-9ba3-ad61b88ad104.png)

#### Specifications
- Leihs version: 4.12.0
- Browser version: safari

**Comment by nimaai** [comment]
could not reproduce. fixed through https://github.com/leihs/leihs/issues/435
