### ISSUE TITLE
Delete Mail Templates in Admin Section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#497]
Delete the Admin-Mail-Templates and provide more functionality in pools: 

- [x] delete mail templates in Admin section
- [x] delete admin-scenarios
- [x] change scenarios, so only mail templates defined in pools are used. No overruling needed anymore.
- [x] When a pool is created, the templates in all languages are automatically filled.
- [x] All other scenarios stay the same.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/3fd5fe985240eefcff71e752ae7a2fd247e6c5a8

**Comment by nadjaweisskopf** [comment]
test: 

- create new pool
- delete language in template of pool
- language of user
- sending mails

**Comment by nadjaweisskopf** [comment]
@nimaai according to production, when a pool is created, the templates are filled with the correct languages (except for spanish). So German email templates are filled with German text, English template with English text, Züridüüt-template with züridüütsch text. I expext these defaults are parsed from the Admin-templates. 

If a pool is created and we have the different language templates, then it would be great to fill the templates accordingly. Can we do that?

**Comment by nadjaweisskopf** [comment]
@nimaai I have tested several scenarios and am waiting for the mails "deadline soon reminder" and "reminder". All other mails worked fine. 

I didn't get a mail though for "received" so I don't know if these work. Could you please have a look, why the received mails aren't rerouted to our staging-leihs-mailbox?

**Comment by nimaai** [comment]
> I didn't get a mail though for "received" so I don't know if these work. Could you please have a look, why the received mails aren't rerouted to our staging-leihs-mailbox?

This is because in the admin settings `deliver_order_notifications` is not set.

**Comment by eins78** [comment]
we just discussed this and decided:

- no files anymore
- no "fallbacks" anymore
- admin can define "global" templates for all languages, but they will only be used when creating a new Pool (so they are template-templates).
- migration takes care to look for files and fallbacks one last time and put them into the settings for each pool, as well the global config

**Comment by nimaai** [comment]
feature reverted for `4.15.0`: https://github.com/leihs/leihs/commit/02d6193bdb7d5fd790b61cb5bb95da84318db5bc

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ae42a814897e1f4313c6ca9edcf85f971b1b8e68

**Comment by nadjaweisskopf** [comment]
test all mails in all languages
content, format in email
amount of mails
