### ISSUE TITLE
React Borrow booking calender for change reservation

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#499]

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/494332bef71c5371cc8f0ffe356d12d3f8430d2b

**Comment by nadjaweisskopf** [comment]
also check templates-wizard!

**Comment by nadjaweisskopf** [comment]
@nimaai everything looks fine. Just an error msg. which needs to be translated. I created a new ticket so we don't have to reopen this one.
