### ISSUE TITLE
LDAP, Active Directory encryption

### ISSUE THREAD

**Issue by gcioffi** [leihs/leihs#502]
I would like to connect Leihs to a LDAP server, Active Directory at my University and for security reasons I can only do it using a minimum bind with credential method encryption. Is this kind of encryption currently supported?

#### Specifications
- Leihs version: 4.13.0

**Comment by DrTom** [comment]
Direct LDAP support has been removed in favor of a more general authentication API in the meanwhile. See also  https://github.com/leihs/leihs_documentation/blob/master/sources/authentication/index.md
