### ISSUE TITLE
LEIHS Service doesn't start after Upgrade to 4.x

### ISSUE THREAD

**Issue by HSLUwem** [leihs/leihs#504]
#### Expected behaviour
LEIHS 4.x Service is starting and running without any further problems.

#### Actual behaviour
Ansible Migration stops at TASK [start-services : service]. Output of journalctl -xe is in the attachment.

#### Steps to reproduce
Can be reproduced on my migration systems (Remote Session possible).

#### Specifications
**Specifications OLD Leihs**
-     OS Host: Ubuntu 16.04
-     Leihs version OLD Host: 3.45.1
-     MySQL version: 5.7.19-0ubuntu0.16.04.1

**Specifications NEW Leihs**
-     OS Host: Ubuntu 16.04
-     Leihs version OLD Host: 4.x (Deploy with Ansible Playbook)
-     PostreSQL version: 10.1

[leihs4x_servicestarterror.txt](https://github.com/leihs/leihs/files/1727492/leihs4x_servicestarterror.txt)

**Comment by nadjaweisskopf** [comment]
HSLUwem requests support and would prepare the following: 

- Linux-System (Ubuntu) mit der aktuell in der Produktion im Einsatz befindlichen LEIHS-Version (3.22.0) => Startpunkt der kompletten Migration. Ab hier können wir zusammen bis auf Version 3.45.1 aktualisieren.

- Linux-System (Ubuntu) vorbereitet für neue LEIHS-Version (4.5.1 – diese Version wurde im Oktober 2017 von den Usern getestet). Sobald das Migrationssystem mit dem alten LEIHS auf 3.45.1 aktualisiert wurde, können wir vom neuen System aus den Ansible-Run laufen lassen und auftretende Fehler gemeinsam beheben. WICHTIG: Die komplette Migration muss genauso nochmals durchgeführt werden können, sobald wir wieder einen möglichen Migrationstermin fixiert haben. Das heisst, die Probleme müssen nachhaltig gelöst werden oder es muss ganz klar sein (Dokumentation) was beim Auftreten eines Problems während der Migration gemacht werden muss.

**Comment by nimaai** [comment]
@HSLUwem The migration which breaks is most probably the one included in version `4.7.0`. I would suggest you upgrade to `4.6.0`, dump the DB and send it to us. I will then have a look at it and tell you how to proceed further.

**Comment by HSLUwem** [comment]
I did the migration with version 4.5.1. This is the version our users have tested back in september 17. I have an actual dump of the database. How can I transfer it to you? I can send it to you via SWTICHFilesender but I need a mail address for this...

**Comment by nimaai** [comment]
The following fix will be available in the coming version `4.15.0` (not available yet; we will let you know). 

1. Upgrade the leihs source code to `4.15.0` on the control machine following https://github.com/leihs/leihs/wiki/Deployment#upgrading but without the last step of running the deploy playbook.
 
2. On the control machine from within the `leihs` directory do:
`cp deploy/inventories/prototype/script_vars_template.yml /leihs/deploy/inventories/prototype/script_vars.yml`

3. Edit the file `deploy/inventories/prototype/script_vars.yml` to have the following content:
```
---
script_file_path: ../legacy/db/migrate/fixup/204.rb
```

4. Then run: `ansible-playbook -v -i <PATH_TO_YOUR_INVENTORY> deploy/execute-script_play.yml`

5. Then run the actual deploy playbook: `ansible-playbook -v -i <PATH_TO_YOUR_INVENTORY> deploy/deploy_play.yml`

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/3e7ad2aa205283482493475b6c541d115d2043a5

**Comment by nimaai** [comment]
@HSLUwem [v4.15.0](https://github.com/leihs/leihs/releases/tag/4.15.0) is ready now. Please follow the steps as I have described them in comment above. Let us know if it worked.
