### ISSUE TITLE
Don't show the delete button if models are used by another pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#507]
Translate message to German: 

"Modell wird von einem anderen Gerätepark genutzt und kann nicht gelöscht werden. "

![bildschirmfoto 2018-02-20 um 13 42 57](https://user-images.githubusercontent.com/3356016/36424578-06270b4c-1644-11e8-929f-f14823e43231.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9d2668763880d241c82cc5cd22631c49ca56e3bd

**Comment by nimaai** [comment]
I have translated the message instead of hiding the button, as it was much easier.

**Comment by nadjaweisskopf** [comment]
@gurmir please test

**Comment by gurmir** [comment]
Translation is correct. Ticket can be closed. @nadjaweisskopf
