### ISSUE TITLE
Feature Request (or how to do 'same day reservations')

### ISSUE THREAD

**Issue by sonoprob** [leihs/leihs#508]
We recently installed leihs 4, and to start off I'd like to send a big thank you to the leihs team;
we went from 1.9 straight to 4; it was quite a big and positive change for my colleagues.

I wonder how to work around the following situation; in our daily practice we have return and hand out in the same timeslot (first an hour of returns, then an hour of handouts). Our students make the reservations, our pool is obviously limited and some items are in used continuously (the demand is high).

In leihs, before an item is returned (taken back into the pool), it can not be reserved on the same day.

For us it would be very nice if students could reserve an item, from the same day it is due to be returned (so, not wait for the next day), esp. in busy times before graduation.

So, this could be a feature request (being able to make a reservation starting on the day an item is expected to be returned), or maybe a question how to work around the above issue.

How are others doing this, I don't think we're the only ones with this situation ?

thanks for your answer

**Comment by nadjaweisskopf** [comment]
@sonoprob Thanks for your kind reply. Nice to hear, that the update from 1 to 4 worked well! If you have any improvements on the documentation, then please give us a feedback. 

To your feature request: 
We have the opposite need at ZHdK than you do. We would want a timeslot of one to two days for certain models between taking back and handing out. I could imagine a setting in leihs, where the time between taking back and handing out can be entered on the model itself. If for example a time slot of 0 is set, the items of this model can be handed out on the same day as they have been taken back.

If you have other ideas, please reopen the ticket.
