### ISSUE TITLE
Export of item list in Admin section leads to an error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#512]
Dani Fischer needs the list urgently. Please can you send him the list in an Excel and then fix the bug?

#### Expected behaviour
All items should be exported to Excel or CSV when klicking on "export to Excel" or "export to CSV" in Admin section/pools

#### Actual behaviour
After some time an errror shows. 

<img width="745" alt="bildschirmfoto 2018-02-26 um 22 39 29" src="https://user-images.githubusercontent.com/3356016/36697095-57fc1ad2-1b46-11e8-8244-27c012b4dbaf.png">

<img width="1058" alt="bildschirmfoto 2018-02-26 um 22 49 43" src="https://user-images.githubusercontent.com/3356016/36697449-642854b4-1b47-11e8-85d4-667a5af3d5d2.png">

#### Steps to reproduce
1. go to Admin section
2. go to pools
3. export to excel
4. wait for error

#### Specifications
- Leihs version: 4.13.0
- Browser version: safari

**Comment by phiku** [comment]
Takes a long time until the error appears. Perhaps the timeout of the proxy is not long enough for this action.

**Comment by nadjaweisskopf** [comment]
We could give a download link to a file created automatically once a day.

**Comment by eins78** [comment]
- generate file on server (nightly)
- UI has "last generated file" for download
- UI has button to generate new file (async - user has to wait till new version shows up in UI)

**Comment by nadjaweisskopf** [comment]
Answer from Dani: A file created last night or early in the morning is enough. He would then download the file from the Admin-section. A button to create a file on the spot is not needed.

**Comment by nadjaweisskopf** [comment]
We'll start with the button solution. Cron-job is not a nice solution according to dev.

**Comment by nadjaweisskopf** [comment]
test and check if quick csv / quick excel should be visible or not. 
Check in which section importer was.

**Comment by phiku** [comment]
@nadjaweisskopf I added more information to the import (some for example Categories, Accessories, Compatibles, Properties). Missing are for example the Fields (despite Building, Room and Shelf) and Borrower information. Do you know, if Daniel needs all field information too?

**Comment by nadjaweisskopf** [comment]
@phiku The following fields are needed: 

- created at
- updated at
- product
- version
- manufacturer
- description
- technical details
- categories
- inventory code
- serial nr.
- imei-nr.
- retirement
- reason for retirement
- working order
- completeness
- borrowable
- status note
- relevant for inventory
- owner
- responsible department
- last checked
- reference
- project nr.
- invoice nr.
- invoice date
- initial price
- supplier
- warrenty expiration
- building
- room
- shelf

**Comment by phiku** [comment]
@nadjaweisskopf 

Ok i checked. Following need feedback:

Responsible Department -> what is this?
Working Order -> what is this?

The following are not optimal to export:
- imei nr
- reference
- project nr
- warranty expiration
Are they really needed?

**Comment by phiku** [comment]
@nadjaweisskopf I now combined these properties in one column "Additional Data".

**Comment by nadjaweisskopf** [comment]
@gurmir please check if file contains the fields above

**Comment by nadjaweisskopf** [comment]
@phiku I am waiting for Dani Fischers reply. The only problem I see, is that some important fields I mentioned above have been pulled together in the column "additional data". Let's see if Dani can deal with this.

**Comment by nadjaweisskopf** [comment]
@phiku reply from Dani Fischer: 

The CSV-export is really quick now, but he needs the following information in seperate columns in order to filter the data: 

- project nr. 
- Beschaffungsgruppe

don't change anything on other columns please. 

Then we can deliver this ticket.

**Comment by nadjaweisskopf** [comment]
@phiku I have created a new ticket for next iteration: https://github.com/leihs/leihs/issues/582
