### ISSUE TITLE
Booking calendar does wrong check if month back button is enabled.

### ISSUE THREAD

**Issue by phiku** [leihs/leihs#513]
When you are in February 2018, go forth to February 2019, it the booking calendar disables the button for going back in months.

**Comment by phiku** [comment]
@nadjaweisskopf Please take into planning.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c7358a72c1d94597700486bb1ed3f7bc0006270f

**Comment by nadjaweisskopf** [comment]
@gurmir please test

**Comment by gurmir** [comment]
Button to change the month back and thorth is correct function. Ticket can be closed @nadjaweisskopf
