### ISSUE TITLE
Adjustments on Visits page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#514]
- [x] 1. in production, the take back icon had an arrow going from right to left. Now both take back and hand over have the same icon.

<img width="172" alt="bildschirmfoto 2018-02-26 um 20 20 46" src="https://user-images.githubusercontent.com/3356016/36690425-8f48b9dc-1b32-11e8-8189-1961fd074d14.png">

- [x] 2. In the visits list the plural form is missing --> it should say "2 items" instead of "2 item" (check production)

- [x] 3. The icons to scroll from left to right are not shown correctly

<img width="234" alt="bildschirmfoto 2018-02-26 um 20 29 11" src="https://user-images.githubusercontent.com/3356016/36690827-cb8db4a0-1b33-11e8-9d11-9ec6c641f7af.png">

- [x] 4. Please change the filter entries. I think it should say: 
- user to be verified
- user and model to be verified

- [x] 5. Search field needs to be translated to German

<img width="344" alt="bildschirmfoto 2018-02-26 um 20 34 58" src="https://user-images.githubusercontent.com/3356016/36691112-911ef54e-1b34-11e8-9b5c-0f6b4dbdac2e.png">

- [x] 6. problem exists also in production but if it's easy to solve this one with the rest then let's do that: "IN one day" instead of "AT one day" 

<img width="101" alt="bildschirmfoto 2018-02-26 um 20 41 50" src="https://user-images.githubusercontent.com/3356016/36691461-a7141748-1b35-11e8-8fc4-1ef9ed14ef0e.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/e2cd246a231d4124daf9837f082fd4380967d381

**Comment by eins78** [comment]
@nimaai fixed in https://github.com/leihs/leihs/commit/9370a8e68eb8a8b0a534ef608f47555af1166c50

**Comment by nadjaweisskopf** [comment]
@gurmir please test

**Comment by gurmir** [comment]
Test is pass. Calender back and forth have now a good looking design. @nadjaweisskopf
