### ISSUE TITLE
Navigating to Borrow section in Demo-Version of leihs throws error

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#516]
Steps to reproduce: 

1. Go to Demo version of leihs http://demo.leihs.zhdk.ch.
2. Log in as normal user or navigate to borrow section
3. error pops up

![bildschirmfoto 2018-02-28 um 13 13 04](https://user-images.githubusercontent.com/3356016/36787133-4b77d0dc-1c89-11e8-9806-7454d9bc20e9.png)

**Comment by nimaai** [comment]
cannot be reproduced anymore
