### ISSUE TITLE
borrow: simplify list of inventory pools 

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#517]
Currently, the list of pools shown to a customers (`/borrow/inventory_pools`) is very complex and nonsensical, leading to bugs.
It could be very simple: a list of all pools the user has any access rights to (if the access is suspended, it is still listed but a notive about the suspension is given).

**Comment by nadjaweisskopf** [comment]
Ok, so 
1. we show only pools where the user is customer.
2. and the pool is active

**Comment by nadjaweisskopf** [comment]
@nimaai 
- please adjust the msg. so it says "reservierbar" instead of "ausleihbar"
- sort the pools alphabetically
