### ISSUE TITLE
customer can fill up the basket although suspended

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#518]
At the moment, if a user is suspended for all pools he has access to he/she can still use the booking calendar, see as if everything was available, add the things to basket, enter a purpose and then by clicking on submit an error message comes.

It's pretty inconvenient and confusing.

The user should still be able to browse the categories and models from all the pools with borrowable items, he has access to, irrespective whether he/she is suspended or not.

But, all the models and their respective "add to basket" buttons should be displayed as unavailable or disabled, so that the user don't even has a chance to see the booking calendar.

**Comment by nadjaweisskopf** [comment]
at the moment nothing will be changed. At least the user can add all models to the cart and as soon as he is not suspended anymore he can send the order. 

BUT - we need to write a scenario and a test. Appartently no scenario exists.
