### ISSUE TITLE
models' list in borrow should not provide pools without borrowable items

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#519]
Right now, a customer can choose also a pool without borrowable items from the select field of inventory pools on the models' list page.

How to reproduce: 

1. go to borrow section as user which is customer of pool "Ausleihe Toni Areal" and "Fundus"
2. klick on category "Audio"
3. check filter of pools in model list
4. klick on "Fundus"
5. The model list is empty

**Comment by nadjaweisskopf** [comment]
Do not show pools in modellist which have 100% of items set to "not borrowable"

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9b7c8da0e62e866872afa6ef83eabead275617f9
