### ISSUE TITLE
links navigate to wrong visits list

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#521]
#### Expected behaviour
Buttons "hand over" and "take back" on the daily view page should navigate to the correct visits. 

#### Actual behaviour
Button "hand over" and "take back" navigate to the visits list "All" instead of to the specific visits list of the hand overs and the take backs. 

#### Steps to reproduce
1. go to pool
2. go to daily view page
3. press on the hand over button or on the take back button
4. All-tab of the visits page is opened instead of the hand over and take back lists. 

#### Related issues 
https://github.com/leihs/leihs/issues/435

#### Specifications
- Leihs version: 4.14.0
- Browser version: safari 11.0

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/284c4396f6b78e4cca10cde94708885d05a52fa3
