### ISSUE TITLE
Investigate why navigating to model list takes so long

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#522]
#### Expected behaviour
I would expect the model list to be shown in a few seconds after pressing on the category "Audio" in the borrow section. 

#### Actual behaviour
After pressing on "Audio" in borrow section it takes very long until the model list is shown. 

#### Steps to reproduce
1. go to borrow section
2. press on "Audio"
3. model list takes very long to load

#### Specifications
- Leihs version: 4.14.0
- Browser version: safari 11.0

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/4f462c2fbd5438724c324d81a4aa9ff0b012c192

Time needed to load the audio category reduced from ca. 18s to 6s.

**Comment by nadjaweisskopf** [comment]
test all - should be ok though

**Comment by nimaai** [comment]
The [fix](https://github.com/leihs/leihs_legacy/commit/cd8b0d362af4840c575367a520ada30782e799e2#diff-4676c008b11a5480d73d4a6de01e45b9L37) had to be reverted due to #548.

Due to severe inter-dependencies and insufficient (and bad) tests I suggest to postpone it to general borrow refactoring.
