### ISSUE TITLE
Translate error msg. in borrow section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#523]
Correct error msg. in English and translate to German: 
"Gültigkeitsprüfung ist fehlgeschlagen: der Benutzer ist für folgenden den Gerätepark gesperrt: XY"
"Validation check: User is suspended for inventory pool: XY"

![bildschirmfoto 2018-03-04 um 09 54 20](https://user-images.githubusercontent.com/3356016/37034632-3c0bd65a-214a-11e8-8d76-2fd542f8a052.png)

Steps to reproduce: 

1. go to borrow section
2. add item from a pool where you are suspended to cart
3. enter reason
4. send order --> error msg. that you are suspended is in English

**Comment by eins78** [comment]
there were 3 messages in total in this controller action, added all of them: https://github.com/leihs/leihs_legacy/commit/782494387390e1bea097c58428ba3aeacb01be87#diff-758b946ac12da08fedbcba684a38bd3eR3543

**Comment by nadjaweisskopf** [comment]
test english browser and german browser for error msg.

**Comment by nadjaweisskopf** [comment]
@gurmir please test as soon as 4.17.0 is on staging

**Comment by gurmir** [comment]
Error msg. is translated. If user is blocked on a Device-Park is coming the correct translation @nadjaweisskopf
