### ISSUE TITLE
Translate error msg. and change the text in English

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#524]
Correct error msg. in English and translate to German. 
And set field to required.

Steps to reproduce:
1. go to borrow section
2. add an item to cart
3. send order without reason
4. --> error msg. is in English and not very user friendly

Please change the msg. to: "Please enter a purpose" / "Bitte einen Grund angeben"
Or, if this is not possible then at write: "Please enter value: Purpose" / "Bitte Wert angeben: Grund" 

<img width="1137" alt="bildschirmfoto 2018-03-08 um 14 03 43" src="https://user-images.githubusercontent.com/3356016/37152429-8fca35c6-22d9-11e8-919d-6d3cc9916dd5.png">

**Comment by eins78** [comment]
error message is not supposed to be (easily) translatable by rails, but with the added 'required' attribute to the form field a user can't cause (and see) this error anymore.

**Comment by nadjaweisskopf** [comment]
@gurmir please test as soon as 4.17.0 is on staging

**Comment by gurmir** [comment]
Test Result ok. Now is coming a message under the Textfield.

**Comment by gurmir** [comment]
@nadjaweisskopf

**Comment by nadjaweisskopf** [comment]
@eins78 When entering a space the english error msg. still appears. But you mentioned that translating this msg. is not so easy. So let's keep this solution as it is.
