### ISSUE TITLE
timeline - navigate to hand over instead of to take back

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#529]
#### Expected behaviour
When klicking on a user line in the timeline which is a hand over, then the user should be navigated to the hand over.

#### Actual behaviour
The user is navigated to the take back when pressing on "hand over". 

#### Steps to reproduce
1. go to pool
2. open a time line where a hand over existst
3. press on the user line and klick on "hand over"
4. you are navigated to the take back instead of to the hand over

#### Specifications
- Leihs version: 4.14.0
- Browser version: safari 11.0

**Comment by nadjaweisskopf** [comment]
@gurmir please test

**Comment by nadjaweisskopf** [comment]
@gurmir please test

**Comment by gurmir** [comment]
Timline Buttons Handover and Take back are working correct. When you click on the handover button you navigate to Handover orders and when you click on the Take back then navigate to take over items

**Comment by gurmir** [comment]
@nadjaweisskopf Ticket can be closed
