### ISSUE TITLE
max. visits should not restrict the borrow calender if left empty

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#530]
#### Expected behaviour
If the field max. visits in the manage section of the pool is left empty, the borrow calenders should not assume the max visits is 0. It seems this is what happens. 

#### Actual behaviour
If leaving the field max. visits empty, the user in the borrow section can not add a model. The calender thinks, the max visits is 0. 

#### Steps to reproduce
1. go to borrow section
2. open the calender for a model of a pool which has max. visits 0
3. try to add the model --> the button is not active
4. As soon as I type a number in the field "max. visits" in the manage section of the pool, I can add the model to the calender. 

#### Specifications
- Leihs version: 4.14.0
- Browser version: safari 11.0

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d364fc998a94e2b1580ac19c07d8879ab04f367a
