### ISSUE TITLE
Check why Mirco can't access the field settings

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#531]
#### Expected behaviour
Mirco should be able to edit the fields in the field editor in staging.leihs.zhdk.ch. He is Admin and even inventory manager of a pool. 

#### Actual behaviour
Mirco can access the field editor in the admin section but can't edit the fields. Nadja can edit the fields without any problems. 

#### Steps to reproduce
1. Mirco goes to Admin section
2. he navigates to the field editor
3. He tries to edit a field --> nothing happens

#### Specifications
- Leihs version: 4.15.0
- Browser version: ?

**Comment by gurmir** [comment]
That is only with Mozilla Firefox. With Internet Explorer i can edit any fields without problems. But the Tests for the Field Editor is running. So we can closed this ticket
