### ISSUE TITLE
Adjust "reload-message" in borrow calender

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#535]
Adjust error msg. 

Write "reload the calender" or "please reload the calender" - and change design so it fits to the error msg. of leihs. 

<img width="743" alt="bildschirmfoto 2018-03-10 um 21 32 12" src="https://user-images.githubusercontent.com/3356016/37246542-25950cc0-24ab-11e8-8e07-e602209f1aa6.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/07bdcc733be042053d0eab2d604e3711e63bdeaa

The button is called "click here to reload" now.

**Comment by nadjaweisskopf** [comment]
Try to test - hard to reproduce
