### ISSUE TITLE
Picking a room takes very long in edit item page and helper

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#536]
Problem shows up especially in Chrome. Mike just called again today (19.3.18) to ask when this bug will be fixed.

I am waiting for Rogers film. He want's to create it next monday.

**Comment by phiku** [comment]
@nadjaweisskopf Is fixed for create/edit item, but not yet for create package. Create packages are not yet implemented in react. The question is, does this happen often, that somebody is creating a package? We did not change anything there and the problem occured recently, so it seems before nobody has ever realized. Or the other explanation is, they used an older computer now. Its only unusable on slow computers, so perhaps the did it on faster computers before?

**Comment by phiku** [comment]
@nadjaweisskopf Ready on test. Please at to correct milestone.

**Comment by nadjaweisskopf** [comment]
@gurmir Could you please also test this ticketedit item page in chrome and safari

**Comment by nadjaweisskopf** [comment]
test ok. Am waiting for Mircos reply.

**Comment by gurmir** [comment]
@nadjaweisskopf All tests in Firefox and Chrome was successfull. In my opinion we can close this ticket an put this ticket to deployment too.
