### ISSUE TITLE
Send submitted mail to user

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#537]
#### Expected behaviour
When a user sends an order, he should receive a submitted msg.

To do: 

- [x] send submitted msg. to user containing the text which is defined in the mail template of the pool
- [x] Write scenario and tests
- [x] Check that template from Admin-section is used for submitted msg. when creating a new pool

#### Actual behaviour
We have a template for "submitted" but the user does not receive the mail. According to Matus the code is disabled. 

#### Steps to reproduce
1. go to borrow section
2. create an order
3. send an order
4. you do not receive a submitted msg. 

#### Related issues 
https://github.com/leihs/leihs/issues/291

#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by nimaai** [comment]
@nadjaweisskopf should the customer get one email (because he submits once for different pool) or multiple (one per pool he has ordered something from)?

**Comment by nimaai** [comment]
I think multiple, because each pool is possibly using a different template for "submitted" emails.

**Comment by nimaai** [comment]
@nadjaweisskopf and what should admin setting `deliver_order_notifications` from now on refer to? right now, it was only concerning `received` mails. maybe we include both? or make 2 different settings with more concrete names?

**Comment by nadjaweisskopf** [comment]
@nimaai To keep the mail-traffic low, we could send an automated mail to the borrower containing a general information with
- your order has been sent and needs to be accepted first
- amount, model names, time period
- reason

- The mail-content only needs to be edited by the Admin, no template needed in pools
- No setting needed in Admin-section. It is sent automatically, same as all other mails sent during the lending/acceptance process.

What do you think?

**Comment by nimaai** [comment]
> * your order has been sent and needs to be accepted first
> * amount, model names, time period
> * reason

This information is configurable for each template, pool and language. Click on `List of available variables` on the edit page of a particular template and language in a particular pool.

> * The mail-content only needs to be edited by the Admin, no template needed in pools

No. This contradicts our recent change in the mail setup. Each template for each language **is needed** in every pool, because only these ones are possible to use for mail delivery. The admin mail templates just ensure that when you create a new pool you have some templates to start with.

> * No setting needed in Admin-section. It is sent automatically, same as all other mails sent during the lending/acceptance process.

Ok. So we keep `deliver_order_notifications` in admin settings for now as an exception to the above stated. I will rename it to `deliver_received_order_notifications` (or something similar) just to be explicit, because submitted order notifications will be always sent, as you suggested.

That said, we should perhaps think of providing each pool the possibility of deciding which email are sent, in long term...

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e75327e3a399cd633e63d421602914da6f15fd8e

**Comment by nadjaweisskopf** [comment]
@nimaai ok, good solution. So the user gets as many submitted-emails as the amount of pools the  order is sent to? I will create a ticket to give the pools the possibility to decide whether a mail-type should be sent or not. But this has no priority at the moment.

**Comment by nimaai** [comment]
> So the user gets as many submitted-emails as the amount of pools the order is sent to?

Yes.

**Comment by gurmir** [comment]
In submitted Mail in all Languages the modell is missing unter the inventory pool.

**Comment by nadjaweisskopf** [comment]
will reopen this ticket --> check Mirco's comment.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/5ee8945b1af66bfdf18a4107a53a17680ea9e021

good catch @gurmir

**Comment by nimaai** [comment]
Please also test the mail for `received` template. For this you will have to probably enable the delivery in admin settings.

**Comment by gurmir** [comment]
@nimaai Ok. I will test the Mail Templates today.

**Comment by gurmir** [comment]
Mail Template are tested. In submitted mail is all ok, but by received Mail it doesen't come in my Inbox when I'm the the Head of the Inventory pool

**Comment by nimaai** [comment]
@gurmir As i said you have to activate it in admin section. I did so now. You can test again.

**Comment by nadjaweisskopf** [comment]
Tests are ok. 
@nimaai can you please adjust the texts in German, English and Swiss German (and for Spanish) before we go live?

I will create a new ticket to adjust the templates later. 
[Submitted Text.docx](https://github.com/leihs/leihs/files/1897602/Submitted.Text.docx)
