### ISSUE TITLE
Optimise field editor

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#542]
1. we need a setting to filter license fields and item fields
[implemented]
2. add popups to the titles "dynamic" / "static" which explain the difference of these field types.
[implemented]
3. It is not possible to search for groups in German - only in English
[pending]
4. If the user changes the English name, he loses the German translation. How shall we deal with this? 
[pending]
5. The user might be suprised, that in the German Amin-GUI the field names are in English - We might want to place a popup to describe this?
[pending]
6. Owner: It's not clear if this means editable or viewable. Could we adjust the label and write "Owner (edit)
[implemented]
7. Role: It's not clear if this means editable for role .... or viewable. Could we adjust the label and write "Role (display)" or "Role (view)"
[implemented]
8. Can we give the user a dropdown list with attibutes when he creates a new field? Otherwise the user will not know which attributes exist and what to fill. Or just a popup with an explenation? Or maybe we need an additional dropdown with values such as "properties" and if this value is chosen then the string "properties_" is added to the attribute name.
[implemented]
9. Value for type select: could we help the user here and display "unique value stored in database..." / "eindeutiger Begriff" in the value field when not filled out yet?
[implemented]
10. I would expect to be able to delete a radio button line if more than two have been created for a field which has not been used yet.
[implemented]
11. same for checkboxes
[implemented]
12. Where shall the user add the German translation for a new field? Or will we expect that the Admin translates in the translation file/database?
[pending]
13. It is not possible anymore to deactivate the fields in the edit item page of a pool
[delivered earlier]
14. Translations (see note from Mirco)
[pending]

**Comment by phiku** [comment]
@nadjaweisskopf I implemented all the tickets (sometimes a bit different than proposed) which are not related to translations. I think we can make an explicit ticket "Field Editor Translations".

**Comment by phiku** [comment]
@nadjaweisskopf The fix about default selections is already done and should be coming with the first release candidate. So i close this ticket.

**Comment by nadjaweisskopf** [comment]
@gurmir please test as soon as 4.17.0 is on staging

**Comment by nadjaweisskopf** [comment]
@gurmir Could you please test this ticket too, thanks.

**Comment by nadjaweisskopf** [comment]
Tests: 
1. Please rename the content to "Gegenstände und Lizenzen" "Items and licenses" / "Nur Gegenstände" "Only items" / "Nur Lizenzen" "Only licenses"
![bildschirmfoto 2018-04-04 um 11 28 49](https://user-images.githubusercontent.com/3356016/38299787-6a53eef4-37fb-11e8-9645-5b8038e9cd3e.png)
2. ok
6. ok
7. ok
8. ok
9. Please correct spelling: "In GUI angezeigter Wert" "Displayed in GUI" / "In Datenbank gespeicherter Wert" "Value saved in Database"
10. ok
11. ok

For all other points including 1 and 9 I will create a new ticket.
@gurmir as soon as your tests are complete I will accept this ticket.
