### ISSUE TITLE
Sort the pools alphabetically

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#545]
#### Expected behaviour
Pools in borrow section should be sorted alphabetically. 

#### Actual behaviour
Probably sorted according to the pool nr. 

#### Steps to reproduce
1. go to borrow section
2. open list of pools on the top menu
3. pools are not sorted alphabetically

#### Related issues 
https://github.com/leihs/leihs/issues/517

#### Specifications
- Leihs version: 4.16.0
- Browser version: safari 11.0

**Comment by phiku** [comment]
Implemented.

**Comment by nadjaweisskopf** [comment]
@gurmir please test, thanks

**Comment by gurmir** [comment]
It sorted normally. @nadjaweisskopf if your test ok we can close this ticket definitely
