### ISSUE TITLE
Hotfix: Correct handling of retired items

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#548]
Following problem exists: 

1. The one item of the model "Blitzanlage Broncolor Minipuls Location Kit 2" is retired
2. The group "DMK - VFO" in pool Ausleihe Toni-Areal contains this model but the line is not marked red - it should say 1 / 0 (*nothing new, see #379*)
3. The borrower can reserve this model even though the item is retired

The timeline is correct.

![bildschirmfoto 2018-03-27 um 09 01 33](https://user-images.githubusercontent.com/3356016/37951868-3ec70bf8-319e-11e8-880d-809a75113e58.png)

Other example: 
![bildschirmfoto 2018-03-27 um 09 08 15](https://user-images.githubusercontent.com/3356016/37951932-6ec20af6-319e-11e8-8923-d751a8a5cee0.png)

**Comment by nimaai** [comment]
Point 3 will be part of `4.16.1`. Part 2 in future versions.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e8f85a4b4a86b403c6ad8ff5f7fb663faa75a752

**Comment by gurmir** [comment]
Booking calender is ok. All Task I had to test on Staging was looking good. @nadjaweisskopf if your tests are well too, then this ticket can go to Deploy
