### ISSUE TITLE
Preferred Git Checkout / Update workflow

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#55]
Hi All,

I moved to git for updating our install earlier this year.  Whilst I'm still getting my head around the system I wondered if there was a best practice for updating/working with multiple local installs?

Here's the workflow I use.
1. Forked master from this repo.
2. Deploy to test server from my fork.
3. Make any custom changes to my fork.
4. Push my fork to git.
5. Deploy from my fork to production server.
6. Pull remote to my test server.
7. Test/check test server.
   iterate to step 4.

On my production servers I just issue a: 
     git pull
and then restart my server with:
     rvm use 2.1.1
     bundle install --deployment --without cucumber development
     RAILS_ENV=production bundle exec rake db:migrate
     RAILS_ENV=production bundle exec rake assets:precompile
     touch tmp/restart.txt

my test server is a little quirkier.  I used to use:
  git fetch upstream 
  git merge/master
  git push origin master
  git pull

and then restart the server with above.

This might be a little too bleeding edge sometimes (but who likes the boring life?)

Ramon suggested using:
  git fetch upstream
  git merge upstream 3.9.0

This seems to give me the result of:
  fatal: upstream - not something we can merge

This may be because of the way I've been updating until now?

SO, first question:
Is there a better workflow than this which could be followed? Secondly, without breaking things like attachments and images, how would I get to that workflow? (I've considered rm'ing the leihs directory and checking out my fork again but I have to recreate all my attachments etc)

Any advice greatly welcomed... and maybe we can put together a deployment workflow into the wiki based upon it?

Kind regards,

Anthony.

**Comment by nadjaweisskopf** [comment]
This is an old ticket with old behaviours. I will close this ticket. Please reopen, if still needed.
