### ISSUE TITLE
Rethink package concept

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#552]

**Comment by phiku** [comment]
Analysis and Thoughts (not to be reviewed yet): 
- A package is a collection of items. Theoretically, a package is defined by its items. So if you have a camera, a tripod and a box, then the package is a "Camera with Tripod with Box". This would mean, a package does not need a model. However, we perhaps want to give it a name like "Tripodcamera-Set". We therefore need a specific entity which describes this. Thats why a package needs a model too. The question will be, is the model a good entity? Because a model for example needs a "product" name. The package not really is a product, however it consists of products. And for example a package most likely does not have a "producer / hersteller". But perhaps we would like to store an image as attachment where you can see the whole package together, instead of individual pictures which are contained in the package.

**Comment by nimaai** [comment]
> You can create an item, selecting a package model. Then afterwards you can open the model where your item appears as package.

If this is true, then it's a bug.

**Comment by phiku** [comment]
@nimaai No its actually correct, just the UI is not consistent. If you create an item and select a package model, then of course it becomes automatically a package. And then it should also appear as a package in the package model.

**Comment by phiku** [comment]
Straightforward Proposal:
- Create "Inventar hinzufügen -> Package Model" menu entry on inventory page dropdown.
- Use the same page like for create model to a package, or create a specific one, but with an explicit title "Create Package Model".
- Dont list the packages on Edit/Create Model, neither on existing models nor on the new package model page. 
- Create "Inventar hinzufügen -> Package" menu entry on inventory page dropdown.
- Create a specific page like "Create Item" to create a package item. There you can choose child items. 

All the stuff like is a package automatically not borrowable if one of the items is not borrowable etc we have to consider later. First we should cleanup the forms to create the packages.

**Comment by nimaai** [comment]
> If you create an item and select a package model...

Yeah, I thought this is not possible!

**Comment by phiku** [comment]
@nimaai Ah yes this I have thought too: "However, you can create an item and select a package as a model (perhaps this is wrong since the create item refactoring)."

**Comment by nadjaweisskopf** [comment]
test package model -test two links

**Comment by phiku** [comment]
@nadjaweisskopf Its implemented on 
http://phiku.ruby.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/inventory

**Comment by nadjaweisskopf** [comment]
@phiku 
Test results:

- Following fields were text fields where more than one line could be entered:
   - Wichtige Notizen zur Aushändigung
   - Beschreibung
   - Interne Beschreibung
At the moment, the attachment-dialogue is opened instead.

- The filter is not set to "all_models" when returning to the inventory list after saving the model.

**Comment by phiku** [comment]
@nadjaweisskopf 

Was die Felder betrifft (mehrzeilig/einzeilig), das ist schon auf Staging inkonsistent zwischen Modell erstellen und Modell editieren. 

Was das forwarden mit "all_models" betrifft, das sollte schon korrekt funktionieren (das wird nur gemacht bei Modell erstellen, nicht Modell editieren).

**Comment by nadjaweisskopf** [comment]
@phiku meeting on monday with mike, pius and roger with update to package development

**Comment by nadjaweisskopf** [comment]
@phiku 
I commented these test results last week: 

- When editing a model, if checkbox "this is a package" has not been selected, could we grey out the checkbox and the text? Otherwise the user tries to check the box and assumes we have a bug. **//Please can you give a feedback to this proposal and if possible implement for next monday?**
- On page "create package" the button should say "Save Package" / "Paket speichern" **//Please can you give a feedback to this proposal and if possible implement for next monday?**
- The sort order of the fields is different than items usually have ("Ort" is on the left, "Zustand" on the right) - if this is a big effort for you, than please leave it as it is. **//As far as I remenber you said the sort order for packages is not tested. Would you propose to leave it as it is? That would be ok for me. ** 
- Show field "owner"
- It should be able to retire a package.  //input from Roger after meeting on 5.6.18

**Comment by phiku** [comment]
@nadjaweisskopf release: 4.19.0-RC.4 is on Staging with all these changes mentioned above. The sorting is now done for the field groups, not for the groups itself, so they should be the same now (hopefully without side effects for existing forms).

**Comment by nadjaweisskopf** [comment]
@phiku 
Mike, Roger and Pius are happy with the package solution. I will test it a last time - Mike will test too and I'll write the input into the ticket. 

The only thing they wish to change immediately is to not show the field "Relevant for inventory". The default value is to be set to "no".

**Comment by phiku** [comment]
@nadjaweisskopf The "Relevant for inventory" was set to "Yes" until now too. Since it would be quite a change to do this, I would not do this now, or perhaps after this refactoring is successful in a next step.

**Comment by nadjaweisskopf** [comment]
@phiku ok, I see. So there is no change to the behaviour in prod. Then lets leave it that way. I should get Mikes reply today.
