### ISSUE TITLE
Deactivate fields per pool

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#553]
#### Specifications
- Leihs version:
- Browser version:
- MySQL/PostreSQL version:

**Comment by phiku** [comment]
Implemented for inventory pool manager.

**Comment by nadjaweisskopf** [comment]
Get rid of the possibility to deactivate or activate a field as user. --> new Ticket

**Comment by nadjaweisskopf** [comment]
@gurmir please test, thanks

**Comment by nadjaweisskopf** [comment]
Before we deploy, could you please adjust the following: 

Translation is missing for buttons - disable / deaktivieren
Translation is missing for fields - if we have a translation in the selected language, than please show the translated field name
We need a filter for 
- type: license fields and inventory fields
- enabled or disabled

**Comment by nadjaweisskopf** [comment]
I will create a new ticket for the points mentioned above.
