### ISSUE TITLE
Borrow: Selection to max. not up to as possible as Daily availability 

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#554]
Only a problem in following calender: 

1. Search for an item and chose the item
2. press "Zu Bestellung hinzufügen"
3. set a high amount by klicking on the arrow buttons in the calender

In the borrow section on leihs I see by testing some tickts that I can set the amount higher than the max amount. It would be better, if I could only enter not higher than the max. Look at following printscreen.

![screenshot_leihs_borrow](https://user-images.githubusercontent.com/37148448/38013970-55e00eb0-3267-11e8-8f25-418ddebeac87.png)

**Comment by nadjaweisskopf** [comment]
Would be nice, if the "add" button would be greyed out or similar, if the amount is too high.
