### ISSUE TITLE
Bug: Helper rooms

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#557]
#### Expected behaviour
The helper in leihs should be able to deal with the fields building and room without having performance problems. 

#### Actual behaviour
When chosing "Toni" as a building and then picking a room, leihs seems to wait a long time until a next interaction can be done. If then klicking anywhere different on the screen, for example trying to chose a next field, leihs seems to crash.  

#### Steps to reproduce
1. go to pool
2. go to inventory section and open the helper
3. pick "Toni" as building and try to choose a room. 

#### Specifications
- Leihs version: 4.16.0
- Browser version: chrome and safari 11.0

**Comment by nadjaweisskopf** [comment]
test all - owner/responsible / rights / scanner / msg. like serialnr. / edit item  / test if it is strange that the some fields are green but item could not be saved.

**Comment by nadjaweisskopf** [comment]
@gurmir please test this ticket - thanks. The whole helper has been redeveloped, so all functions need to be tested.

**Comment by gurmir** [comment]
Tests are complete. All Function are good and very quick. Changes in difference Fields with Inventory helper are correctly changed. And Back to State is writting too. Also all tests are running right.

Scanner function is running correctly too. So if the Test by you @nadjaweisskopf  are running correctly too we can deploy the new Release

**Comment by nadjaweisskopf** [comment]
@phiku test results: 

- Text still in German: "Kein Gegenstand ausgewählt"

<img width="1064" alt="bildschirmfoto 2018-05-08 um 19 52 52" src="https://user-images.githubusercontent.com/3356016/39773843-7f269638-52f9-11e8-99d7-149b59cc91b6.png">

- The messages are as we discussed in Demo not clear to the user: On one hand we write "item saved" on the other hand the field is marked red. I'm not sure what has happended now. What is the problem in this case?

<img width="1058" alt="bildschirmfoto 2018-05-08 um 19 54 14" src="https://user-images.githubusercontent.com/3356016/39773963-ceed41bc-52f9-11e8-9c6c-3bd135601b4b.png">

- What did we discuss on this point, where text is mixed in German and English? 

<img width="1034" alt="bildschirmfoto 2018-05-08 um 19 59 40" src="https://user-images.githubusercontent.com/3356016/39774164-6f6369b4-52fa-11e8-8991-7330f8659db7.png">

- In the helper before there was a scenario saying something like "if you enter a serialnr. which is already used by another item, you receive a warning msg. (not an error msg.). This behaviour seems to be missing. 

- Please change the naming "Gerät" to "Gegenstand" - we never say "Gerät" in leihs - it could also be a skirt or a table

<img width="532" alt="bildschirmfoto 2018-05-08 um 20 14 09" src="https://user-images.githubusercontent.com/3356016/39774890-862a70be-52fc-11e8-9b97-2aa9c2fbe486.png">

I will test the scanning tomorrow morning.

**Comment by phiku** [comment]
Technical Note:

Inconsistent error message occurs for example for: 
INV8461 with field "Warranty expiration"

The reason is, the backend seems to allow it because of scope owned_or_responsible_by_inventory_pool, however the frontend only checks App.InventoryPool.current.id !== item.owner.id

**Comment by phiku** [comment]
@nadjaweisskopf Fixed the stuff for test.

**Comment by nadjaweisskopf** [comment]
@gurmir test: 
- translations
- and screenshot 2 (warranty field red and saved msg. green - should not appear)

**Comment by gurmir** [comment]
@nadjaweisskopf Test on Google Chrome are successful. If your tests on safari are successful too we can close this ticket definitely

**Comment by nadjaweisskopf** [comment]
@phiku Following test was not successful:

1. scan item INV7637 in the field on the left --> behaviour is correct, item is not found because it belongs to another pool
2. scan item INV7637 or type nr. INV7637 in the right field, then press "and assign fields" --> the data for item INV8452 is shown and adjusted instead.

![bildschirmfoto 2018-06-06 um 13 55 56](https://user-images.githubusercontent.com/3356016/41036938-06618794-6992-11e8-9910-c9d95b6e33c4.png)

**Comment by nadjaweisskopf** [comment]
to test on Phiku

**Comment by nadjaweisskopf** [comment]
@phiku If I type a foreign itemnr. (my pool is not owner or responsible) and press "und weise Felder zu", then I get the error msg. "bitte Gegenstand selektieren". The error should say "Inventarcode nicht gefunden" - same as when scanning this item. 
(this is an edge case, if this is the only problem, we can deliver and solve this in the next iteration)
I'll go on testing. 

![bildschirmfoto 2018-06-12 um 16 22 22](https://user-images.githubusercontent.com/3356016/41296549-77533be4-6e5d-11e8-93bd-29a59012ef61.png)
