### ISSUE TITLE
Order can not be accepted - Borrower can not be changed

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#559]
#### Expected behaviour
It should be possible to accept the order or change the borrower.

#### Actual behaviour
Accepting the order or changing the borrower throw an error. 

#### Steps to reproduce
1. go to production
2. go to pool Ausleihe Toni-Areal
3. search for orders of delegation user "zhdk innovation lab"
4. edit order
5. try to accept --> error
6. try to change the borrower --> error

#### Specifications
- Leihs version: 4.16.0 (production)
- Browser version: safari 11.0

![thumbnail_bildschirmfoto 2018-04-11 um 11 18 39](https://user-images.githubusercontent.com/3356016/38612263-76917a8e-3d86-11e8-8301-cab83854a312.jpg)
![thumbnail_bildschirmfoto 2018-04-11 um 11 15 56](https://user-images.githubusercontent.com/3356016/38612264-76c18f62-3d86-11e8-9684-0019e89f0e86.jpg)

**Comment by nimaai** [comment]
https://leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/orders/c4779e39-377f-447d-959e-6a25c3a0bac3/edit

**Comment by nadjaweisskopf** [comment]
Same case to be tested when adjusting a hand over.

**Comment by nimaai** [comment]
@nadjaweisskopf 
> Same case to be tested when adjusting a hand over.

tested by me. seems to be ok.
