### ISSUE TITLE
Adjustments to current behaviour of accounts information in procurement

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#562]
Change of behaviour how accounting fields work:

Admin-rights: 
Inside the categories the Admin can define two general accounts

- [x] 1. account procurement
- [x] 2. general ledger account (investment account)

- [x] If inspector choses the value "aquisition", then we show **nr. of cost center** and **procurement account**
- [x] If inspector choses the value "investment", then we show **internal order text field** and **general ledger account (investment account)**

Both accounts are defined through the Admin on the sub category. 

- [x] Both fields shall be exported. 

All these fields are only shown to the roles
- Admin
- Inspector
- Viewer

**Comment by nimaai** [comment]
Backend part done: 

- [ ] new column `procurement_categories.procurement_account`
- [ ] request field authorization same as `general_ledger_account`
- [ ] graphql schema

**Comment by eins78** [comment]
@nadjaweisskopf please check the german terms for  those fields. right now it is inconsistent, we have to decide for 1 option and then use that everywhere (code impact minimal, only translations file)

```json
{ 
  "cost_center": "Kostenstelle",
  "general_ledger_account": "Sachkonto",
   "internal_order_number": "Innenauftrag",
  "procurement_account": "Beschaffungskonto"
}
```

we have also seen this variation

```json
{
  "general_ledger_account": "Sachkonto Ⅰ",
  "procurement_account": "Sachkonto Ⅱ",
}
```
