### ISSUE TITLE
Adjustments to field list in manage section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#564]
- [ ] Translation is missing for buttons - disable / deaktivieren

- [ ] Translation is missing for fields - if we have a translation in the selected language, than please show the translated field name

- [ ] We need a filters for
- type / Typ: license fields and inventory fields / Gegenstände oder Software-Lizenzen
- state / Zustand: enabled or disabled / aktiviert oder deaktiviert

**Comment by phiku** [comment]
@nadjaweisskopf I take me out of this ticket, until it is planned again.

**Comment by nadjaweisskopf** [comment]
If anything more is needed I will reopen this ticket.
