### ISSUE TITLE
Remove the deactivation of fields per user on create/edit forms.

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#566]
1. step: deactivate possibility to deactivate field
2. check scenarios and tests so the fields are shown according to the inventory field settings
3. nadja inform the lending mgrs.

**Comment by phiku** [comment]
@nadjaweisskopf Disabled the "x" to hide the fields. Ready on https://test.leihs.zhdk.ch.

**Comment by nadjaweisskopf** [comment]
@phiku please merge so I can test on staging
