### ISSUE TITLE
Create a Inventory List for Mike and Barbara

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#569]
Please create a list with following conditions:

All items, which contain a room OR a building that do not match a room or building from the list (see list attached to ticket).
compare the fields "building" with the column A (Liegenschaft)
and the field "room" with the colum G (Raumnummer)

The list should contain all fields which are exported from the inventory list in leihs.

Input Mike: Please blend retired devices out.
Input Barabara F.: The list like so is unusable and not helpful. For us are the following fields helpfull:
- Product
- Inventory No.
- Owner
- Responsible Department
- Room

For each Inventory No. a speperate field. If it is possible

Reference Ticket https://github.com/leihs/leihs/issues/383

**Comment by phiku** [comment]
Konvertiertes Raum CSV zum Excel welches in Ticket https://github.com/leihs/leihs/issues/383 am 11 Februar hochgeladen wurden.
[Raum_und_Gebaudeliste_der_ZHdK.csv.zip](https://github.com/leihs/leihs/files/2026204/Raum_und_Gebaudeliste_der_ZHdK.csv.zip)

**Comment by phiku** [comment]
@gurmir @nadjaweisskopf Ich habe das Gefühl, bei diesem Ticket drehen wir uns im Kreis. Als letztes hatten wir eine Liste wie folgt: 

<img width="1341" alt="bildschirmfoto 2018-05-22 um 12 43 29" src="https://user-images.githubusercontent.com/16756048/40357891-da41807c-5dbd-11e8-93b1-94b8f22e4a0d.png">

Wir haben da die Inventory Codes zusammengefasst, dass man die Räume besser sieht. Nun soll das wieder Rückgängig gemacht werden. So lange wie wir da schon dran sind, frage ich mich, ob das überhaupt ein wichtiges Feature sein kann, wenn es so lange hin und her geht.

**Comment by phiku** [comment]
Wahrscheinlich ist das inzwischen die Falsche Raumliste. Hier wurden schon einige Dinge angepasst:

[CSV_Räume_und_Gebäude.csv.zip](https://github.com/leihs/leihs/files/2026410/CSV_Raume_und_Gebaude.csv.zip)

**Comment by nadjaweisskopf** [comment]
@phiku New generated file: 
[Raum_und_Gebaudeliste_der_ZHdK.csv.zip](https://github.com/leihs/leihs/files/2026873/Raum_und_Gebaudeliste_der_ZHdK.csv.zip)


I tested it, it works (generated with LibreOffice)

**Comment by phiku** [comment]
@nadjaweisskopf Ich denke, das war nicht die letzte Version. Bei dem, welches ich hinzugefügt hatte, hatten wir bei den Toni Räumen die "ZT" Prefixes entfernt. Mit deiner Version kriegen wir z.B. "4.C12" als Fehler. 

![bildschirmfoto 2018-05-23 um 08 02 58](https://user-images.githubusercontent.com/16756048/40406187-00495ef0-5e60-11e8-872b-100be34d458b.png)

**Comment by phiku** [comment]
@nadjaweisskopf Wenn man im Admin nach 4.c12 sucht, kommen beide Versionen vor.

![bildschirmfoto 2018-05-23 um 08 08 20](https://user-images.githubusercontent.com/16756048/40406325-8ef13164-5e60-11e8-9427-4617479d4012.png)

**Comment by nadjaweisskopf** [comment]
Mirco is doing a comaprison in excel - this ticket is on hold

**Comment by nadjaweisskopf** [comment]
Will send list to Mike and Barbara tomorrow.
