### ISSUE TITLE
Searching for SW in Inventory pool goes in endless spiner

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#577]
When I search for a Software in the global search, the search page shows an endless spinner where software is normally shown. 

More details are in the Screenshot

![test](https://user-images.githubusercontent.com/37148448/40912147-03bbf742-67f1-11e8-80f2-bbfad8048f1f.jpg)

Step to Repruduce:
1. Go to Inventory Pool "ITZ Software"
2. Insert the name of the Software in the global search field
3. Klick Enter
4. SW is not shown
5. go to tab software - then the sw details are shown

**Comment by phiku** [comment]
Has Javascript error:
![bildschirmfoto 2018-07-10 um 13 35 21](https://user-images.githubusercontent.com/16756048/42507640-26f2afe6-8446-11e8-94ec-900f65fe3af8.png)

**Comment by nadjaweisskopf** [comment]
@gurmir please can you retest, thanks

**Comment by gurmir** [comment]
@nadjaweisskopf Tests in Chrome and Firefox are successfully done. Could you please test in Safari?
If your tests successfull too we can deploy
