### ISSUE TITLE
Feature request: per item stats

### ISSUE THREAD

**Issue by transat** [leihs/leihs#58]
In terms of statistics, it would be useful to see how many times a specific item has been booked. When assigning an item to a booking, the natural reflex is to select an available item at the top of the list (e.g.. 'camera 1' as opposed to 'camera 7') but Leihs could use this stat to order the list of assignable items with the least booked items at the top of the list rather than the current asset number based order. This would avoid excessive wear and tear of a specific item.

**Comment by psy-q** [comment]
We now have some statistics on lending processes per item, they're in the statistics screen. If this is not detailed enough (just showing the top 10 of lent items), what else could we add to make it better?

**Comment by nadjaweisskopf** [comment]
@transat If you have further advice for statistics, please reopen the ticket.
