### ISSUE TITLE
Deployment failure - git uncrypt

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#581]
#### Expected behaviour
Debian 9.4

Deployment running:
    ansible-playbook -v -i dac-inventory/dac-hosts deploy/deploy_play.yml

#### Actual behaviour
Deployment fails with the following error:

TASK [leihs-legacy-install : git uncrypt legacy] **************************************************************************
fatal: [dac-leihs02 -> localhost]: FAILED! => {"changed": true, "cmd": "#/bin/bash\n set -eux\n cd '/root/leihs/deploy/../legacy'\n git crypt unlock", "delta": "0:00:00.005585", "end": "2018-06-12 09:31:52.839760", "msg": "non-zero return code", "rc": 1, "start": "2018-06-12 09:31:52.834175", "stderr": "+ cd /root/leihs/deploy/../legacy\n+ git crypt unlock\ngit: 'crypt' is not a git command. See 'git --help'.", "stderr_lines": ["+ cd /root/leihs/deploy/../legacy", "+ git crypt unlock", "git: 'crypt' is not a git command. See 'git --help'."], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/leihs/deploy/deploy_play.retry

#### Steps to reproduce
As deployment instruction on the wiki.

#### Specifications
- Leihs version: 4.18
- Browser version: N/A
- MySQL/PostreSQL version:

**Comment by Dragios** [comment]
Try to manually install `git-crypt` on your control machine first before attempt to deploy again. It should fix your issue.

**Comment by AnthonyHunt** [comment]
I've set this up on the control machine, but now get another error about the shared key.

What's happened with the deployment guide??? it's gone from useful to incoherent??

it no longer specifies how to deploy?  Do we still use a control machine??

**Comment by AnthonyHunt** [comment]
with the new deployment process, it's now falling over with 

TASK [start-services : service] *******************************************************************************************
fatal: [10.101.83.13]: FAILED! => {"changed": false, "msg": "Unable to start service leihs-legacy.service: A dependency job for leihs-legacy.service failed. See 'journalctl -xe' for details.\n"}

and the log trace:

Jun 18 11:59:32 dac-leihs-dply ansible-synchronize[12329]: Invoked with partial=False links=None copy_links=False perms=Non
Jun 18 12:00:00 dac-leihs-dply ansible-file[12559]: Invoked with directory_mode=None force=False remote_src=None path=/root
Jun 18 12:00:01 dac-leihs-dply ansible-command[12589]: Invoked with warn=True executable=None _uses_shell=True _raw_params=
                                                        set -eux
                                                        DEPLOY_DIR='/root/dac-leihs02/leihs/deploy'
                                                        cd $DEPLOY_DIR/../deploy
                                                        $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/deploy.tar.gz re
Jun 18 12:00:06 dac-leihs-dply ansible-file[12682]: Invoked with directory_mode=None force=False remote_src=None path=/root
Jun 18 12:00:07 dac-leihs-dply ansible-command[12704]: Invoked with warn=True executable=None _uses_shell=True _raw_params=
                                                        set -eux
                                                        DEPLOY_DIR='/root/dac-leihs02/leihs/deploy'
                                                        cd $DEPLOY_DIR/../database
                                                        $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/database.tar.gz 
Jun 18 12:00:23 dac-leihs-dply ansible-file[12860]: Invoked with directory_mode=None force=False remote_src=None path=/root
Jun 18 12:00:23 dac-leihs-dply ansible-command[12884]: Invoked with warn=True executable=None _uses_shell=True _raw_params=
                                                        set -eux
                                                        DEPLOY_DIR='/root/dac-leihs02/leihs/deploy'
                                                        cd $DEPLOY_DIR/../legacy
                                                        $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/legacy.tar.gz re
Jun 18 12:01:18 dac-leihs-dply ansible-command[13162]: Invoked with warn=True executable=None _uses_shell=True _raw_params=
                                                        set -eux
                                                        DEPLOY_DIR='/root/dac-leihs02/leihs/deploy'
                                                        cd $DEPLOY_DIR/../system
                                                        $DEPLOY_DIR/bin/lein uberjar removes=None creates=None chdir=None s

**Comment by Dragios** [comment]
https://github.com/leihs/leihs/issues/580#issuecomment-396553151
Answer on paragraph 3.

**Comment by AnthonyHunt** [comment]
Sadly that's not the same problem I am encountering.  I have changed Oracle Java 8, and this has not helped.  I still have the same error with leihs-legacy service not starting.  Apache on the client is also not started.

**Comment by AnthonyHunt** [comment]
More detail.... at this stage I'm just trying to deploy and not to migrate my previous systems.

Jun 18 16:59:57 dac-leihs02 systemd[1]: leihs-migration.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 16:59:57 dac-leihs02 systemd[1]: Failed to start Leihs Migration Service.
-- Subject: Unit leihs-migration.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit leihs-migration.service has failed.
-- 
-- The result is failed.
Jun 18 16:59:57 dac-leihs02 systemd[1]: Dependency failed for Leihs Legacy Service.
-- Subject: Unit leihs-legacy.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit leihs-legacy.service has failed.
-- 
-- The result is dependency.
Jun 18 16:59:57 dac-leihs02 systemd[1]: leihs-legacy.service: Job leihs-legacy.service/start failed with result 'dependency'.
Jun 18 16:59:57 dac-leihs02 systemd[1]: leihs-migration.service: Unit entered failed state.
Jun 18 16:59:57 dac-leihs02 systemd[1]: leihs-migration.service: Failed with result 'exit-code'.

**Comment by Dragios** [comment]
@AnthonyHunt It seems you misunderstood. It is the same problem I encounter before and that is the answer to solve the problem.

>To answer your last question, that seems like a configuration problem: the db_backup_on_deploy option should not be enabled on first deploy as there is no DB to back up yet

So what you need to do is edit the settings for per-host config in file `host_vars/${LEIHS_HOSTNAME}.yml`
![image](https://user-images.githubusercontent.com/18496868/41571198-a333f6bc-73a4-11e8-98fe-292041c9136a.png)
Set `db_backup_on_deploy` from Yes to **No**

**Comment by AnthonyHunt** [comment]
I've tried this set to "No" and also commented out.  Still not working.

**Comment by Dragios** [comment]
Then I not sure what went wrong. Wait for the developer to reply.
