### ISSUE TITLE
Adjustments to new helper

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#583]
1. adjustment: If I type a foreign itemnr. (my pool is not owner or responsible) and press "und weise Felder zu", then I get the error msg. "bitte Gegenstand selektieren". The error msg. should say "Inventarcode nicht gefunden" - same as when scanning this item.

2. adjustiment: If a user types an inventory nr. by hand into the right field and presses "und weise Felder zu", then scans the next item per hand scanner - then the nr. on the right in the text field should disappear. Otherwise this could confuse the user. 

![bildschirmfoto 2018-06-12 um 16 35 23](https://user-images.githubusercontent.com/3356016/41556269-87a36b40-733a-11e8-90db-32a0dc9d85e5.png)

#### Steps to reproduce
1. adjustment: 
1. go to pool
2. go to helper
3. select some fields
4. type a foreign itemnr. in the field on the right
5. try to assign the fields to the item
6. msg. saying "bitte Gegenstand selektieren" appears instead of "Inventarcode nicht gefunden"

2. adjustment:
1. go to pool
2. go to helper
3. select some fields
4. type an itemnr. in the field on the right
5. scan a new item
6. inventorynr. in the right field does not disappear

#### Related issues 
https://github.com/leihs/leihs/issues/557

#### Specifications
- Leihs version: 4.19.0
- Browser version: safari

**Comment by phiku** [comment]
Fixed 2) but could not reproduce 1).
