### ISSUE TITLE
Problems when trying to update to V4

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#585]
Please check the following journal. Are the problems related to our deployment recipe? How can we help? 

Following possibilities have been discussed:

- Update through ZHdK or Panter
- SaaS - migration of data at ZHdK
- ...

[GescheiterteMigrationLEIHS_HSLU.DOCX](https://github.com/leihs/leihs/files/2112572/GescheiterteMigrationLEIHS_HSLU.DOCX)

**Comment by nadjaweisskopf** [comment]
Might be possible to start in July - but will probably end in August - but not start until V5 is live.

**Comment by DerBachmannRocker** [comment]
I have successfully migrated Leihs to the current stable version. I'm not sure if this helps in your case, as you report trouble with 3.x
See [here](https://github.com/leihs/leihs/wiki/Upgrading-3.45.1-to-4.x,-inofficial-guide)

I will probably update the document in the next few days when I continue working on the project.

**Comment by nadjaweisskopf** [comment]
@DerBachmannRocker Thanks for this. I have sent a link to the customer.

**Comment by nadjaweisskopf** [comment]
We have received a dump of the DB. Please check what could have gone wrong and try to solve the problem.
