### ISSUE TITLE
V5 - Sign-in does not work correctly

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#591]
sign-in does not work correctly, there is no useful error page, if information such as email or password are missing.

#### Related issues 
https://github.com/leihs/leihs/issues/339

#### Specifications
- Leihs version: V5
- Browser version: safari

**Comment by DrTom** [comment]
I am putting this one on hold. We will discuss auth services next week. Better we wait for that.

**Comment by nadjaweisskopf** [comment]
tested V5 login, everything looks ok.
