### ISSUE TITLE
Changing to new Mailadress for Staging and test leihs

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#602]
The Mailboxes from Staging and Test leihs was full. Now we want to change the Mailaddress from service.itz@zhdk.ch to testmails.leihs@zhdk.ch. 

After we create the E-Mailaddress, could you change this E-Mailadress in the Adminsection of the instances?

**Comment by nadjaweisskopf** [comment]
We will not change the mail address - the rule should be enough. Mails are deleted after a certain time.
