### ISSUE TITLE
move https://lausig.gitbooks.io/book-manual-test/content to our gitbook

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#603]
Flurin has created the leihs manual on his own gitbook "lausig". He said Max could move the gitbook to a leihs gitbook.

I will then place our help-url to this gitbook.

**Comment by eins78** [comment]
@nadjaweisskopf I can not move books from other accounts Only the current owner can do that, under `$book > settings > danger zone > transfer ownership`.

**Comment by gurmir** [comment]
Documantion are moved to the new link
