### ISSUE TITLE
Refinement 10.7.18 LDAP

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#604]
auth. / verwalt. benutzer trennen in V5 
benutz./ group verw. über Synch - unabhängig von auth. methode werden attribute gesyncht.
synch user und synch group schon umgesetzt
AAI ist keine "schöne" Technologie - wir hatten aber keine grosse Alternative ausser AGW.
authentication/autentisierung mach bind - benutzerloginname und email geht zu ldap und schaut passts, dann erhält er ein ja/nein, mehr nicht

blaue box - über zapi - synch und import:
gruppen synchronisieren
benutzer anlegen
benutzer disablen
attribute erneuern

Mit E-Mail-Adresse prüfen ob Schule gespeichert werden kann und Username - man muss dann nur noch Passwort eingeben. 

email-sign-in wird bei der Überarbeitung der Mail-Technologie aut. umgesetzt. Ist vor allem für Externe SaaS sinnvoll. 

Oranges Kästchen muss bei LDAP noch ein GUI für LDAP-Login beinhalten, bei dem der User sein Passwort und sein Benutzername eingeben muss. Bei Verbindung zu Switch AAI muss das Kästchen kein GUI bieten, da Switch AAI schon ein GUI mitgibt.

Entscheidungen:

- V5: Umsetzung mit Switch AAI lassen wir wie umgesetzt
- V5: leihs-auth nehmen wir aus der leihs-admin API raus und machen eine eigene App. 
- V5: Legacy wird an einer Stelle erweitert, damit und bei jedem Request geprüft wird, ob der User auf einen spezifischen Pool Zugriff hat. 
- Bestehende User erhalten ihre bestehenden Rechte - da wurde nichts geändert und funktioniert bei Einführung V5
- V5.X: API wird gebaut für oranges Kätchen
- V5.X: Oranges Kästchen für bspw. LDAP bind um zu zeigen, dass das funktionieren kann
- LDAP Bind wird nicht in leihs-auth Kästchen umgesetzt sondern im orangen Kästchen
- Für SaaS sind wir dann mit leihs-auth-Kästchen, API und orangem Kästchen gut aufgestellt.

**Comment by hsssystems** [comment]
Gibt es fuer dieses Refinement eine Roadmap bzw. ein Release Date fuer V5 mit Attribute Sync und AAI?
