### ISSUE TITLE
inventory import fails

### ISSUE THREAD

**Issue by lime918** [leihs/leihs#605]
#### Expected behaviour
when selecting import csv in an inventory pool, a csv with model_id that already exists ("TB5800"), and a new inventory_code specified, will be successful

#### Actual behaviour
error message displayed:
NOT FOUND
Couldn't find Model with 'id'=TB5800

 leihs Error 404 on localhost:3210 at 2018-07-13T19:42:04.602Z

#### Steps to reproduce
1) add inventory model with Product=TB5800
2) import csv with contents: 
inventory_code,model_id
POOL2,TB5800
3) fail message will be displayed

#### Specifications
- Leihs version: 4.11.0
- Browser version: Version 67.0.3396.99 (Official Build) (32-bit)
- MySQL/PostreSQL version: psql (PostgreSQL) 10.4 (Ubuntu 10.4-2.pgdg16.04+1)

**Comment by nimaai** [comment]
This feature has been dropped, but will possibly be re-implemented in future.
