### ISSUE TITLE
Band new install fails

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#606]
After my previous issues I have started a fresh with a stock Debian Stretch install.

When deploying to the subordinate server I get this message:

TASK [configure : debug] *******************************************************
ok: [10.101.83.12] => {
    "leihs_deploy_info.data": {
        "build_is_latest_release": true, 
        "commit_id": "90421fc98be987abeb7bf76b9f00fd3cce301bd5", 
        "commit_messages": "", 
        "git_describe_tag": "4.11.0", 
        "time": "2018-07-16T11:53:38Z", 
        "tree_id": "54862315d0d23a8ff38b4ac0605779bd600c1614"
    }
}

fatal: [10.101.83.12]: FAILED! => {"changed": false, "failed": true, "msg": "RepresenterError: cannot represent an object: 90421fc98be987abeb7bf76b9f00fd3cce301bd5"}

**Comment by AnthonyHunt** [comment]
Solved by updating Ansible from 2.2.1.0 to 2.6.x

**Comment by nadjaweisskopf** [comment]
@DrTom can we adjust the documentation and give an information on which ansible version matches our playbooks?
