### ISSUE TITLE
Import v3 to v4 error

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#607]
Working through a number of issues as I'm desperate to get our 4 installations moved across to V4 asap.

I believe I have the v3 to v4 recipe configured correctly; although I've had to hard code a couple of thing into deploy/roles/fetch-v3-data/tasks/main.yml as my ruby path would'nt take (/usr/local/rvm/rubies/ruby-2.3.0/bin) and also my installation folder had production/current appended to it (my current installs don't look like that).

When I run the playbook I get the error:
```
fatal: [dac-leihs02.uni.worc.ac.uk]: FAILED! => {"changed": true, "cmd": "set -eux\n source /etc/profile.d/rbenv-load.sh\n cd /home/leihs/\n export RAILS_ENV=production\n export PATH=\"/usr/local/rvm/rubies/ruby-2.3.0/bin:${PATH}\"\n ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "delta": "0:00:00.155431", "end": "2018-07-16 15:10:20.844314", "msg": "non-zero return code", "rc": 1, "start": "2018-07-16 15:10:20.688883", "stderr": "+ source /etc/profile.d/rbenv-load.sh\n+++ rbenv init -\n++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"\nsource \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"\nrbenv rehash 2>/dev/null\nrbenv() {\n  command=\"$1\"\n  if [ \"$#\" -gt 0 ]; then\n    shift\n  fi\n\n  case \"$command\" in\n  shell)\n    eval `rbenv \"sh-$command\" \"$@\"`;;\n  *)\n    command rbenv \"$command\" \"$@\";;\n  esac\n}'\n+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash\n++++ complete -F _rbenv rbenv\n+++ rbenv rehash\n+ cd /home/leihs/\n+ export RAILS_ENV=production\n+ RAILS_ENV=production\n+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml\nruby: No such file or directory -- bundle (LoadError)", "stderr_lines": ["+ source /etc/profile.d/rbenv-load.sh", "+++ rbenv init -", "++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"", "source \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"", "rbenv rehash 2>/dev/null", "rbenv() {", "  command=\"$1\"", "  if [ \"$#\" -gt 0 ]; then", "    shift", "  fi", "", "  case \"$command\" in", "  shell)", "    eval `rbenv \"sh-$command\" \"$@\"`;;", "  *)", "    command rbenv \"$command\" \"$@\";;", "  esac", "}'", "+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash", "++++ complete -F _rbenv rbenv", "+++ rbenv rehash", "+ cd /home/leihs/", "+ export RAILS_ENV=production", "+ RAILS_ENV=production", "+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "ruby: No such file or directory -- bundle (LoadError)"], "stdout": "", "stdout_lines": []}
```

and if I try to export the database manually with:
    ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml

I get:

```
Warning: fuzzy message was used.
  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'
Warning: fuzzy message was used.
  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'
Warning: fuzzy message was used.
  : msgid 'Delegation'
Warning: fuzzy message was used.
  : msgid 'A package item must belong to a package model'
rake aborted!
SyntaxError: (eval):1: syntax error, unexpected tIDENTIFIER, expecting keyword_end
class ::LeihsDBIOReturn 20 items to check < ActiveRecord::Base
                                ^
/home/leihs/lib/leihs/dbio.rb:13:in `eval'
/home/leihs/lib/leihs/dbio.rb:13:in `rows'
/home/leihs/lib/leihs/dbio.rb:23:in `block in data'
/home/leihs/lib/leihs/dbio.rb:22:in `map'
/home/leihs/lib/leihs/dbio.rb:22:in `data'
/home/leihs/lib/leihs/dbio.rb:29:in `export'
/home/leihs/lib/tasks/leihs/dbio.rake:6:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@global/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.3.0@global/bin/bundle:23:in `<main>'
Tasks: TOP => leihs:dbio:export
```

My database looks fine and passes all the other constancies? 

Note: The server I'm currently upgrading is my test server.  I won't try on my live servers until I know this one passes.  It's also at 3.45.1.

Help appreciated.

Anthony.

**Comment by AnthonyHunt** [comment]
I've fixed the first problem by inserting "gem install bundler --no-rdoc --no-ri" into deploy/roles/fetch-v3-data/tasks/main.yml before the rake.  This gives me an error consistent with the error get when running it locally:

fatal: [dac-leihs02.uni.worc.ac.uk]: FAILED! => {"changed": true, "cmd": "set -eux\n source /etc/profile.d/rbenv-load.sh\n cd /home/leihs/\n export RAILS_ENV=production\n export PATH=\"/usr/local/rvm/rubies/ruby-2.3.0/bin:${PATH}\"\n gem install bundler --no-rdoc --no-ri\n ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "delta": "0:00:06.621391", "end": "2018-07-17 13:59:52.918894", "msg": "non-zero return code", "rc": 1, "start": "2018-07-17 13:59:46.297503", "stderr": "+ source /etc/profile.d/rbenv-load.sh\n+++ rbenv init -\n++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"\nsource \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"\nrbenv rehash 2>/dev/null\nrbenv() {\n  command=\"$1\"\n  if [ \"$#\" -gt 0 ]; then\n    shift\n  fi\n\n  case \"$command\" in\n  shell)\n    eval `rbenv \"sh-$command\" \"$@\"`;;\n  *)\n    command rbenv \"$command\" \"$@\";;\n  esac\n}'\n+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash\n++++ complete -F _rbenv rbenv\n+++ rbenv rehash\n+ cd /home/leihs/\n+ export RAILS_ENV=production\n+ RAILS_ENV=production\n+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ gem install bundler --no-rdoc --no-ri\n+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml\nWarning: fuzzy message was used.\n  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'\nWarning: fuzzy message was used.\n  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'\nWarning: fuzzy message was used.\n  : msgid 'Delegation'\nWarning: fuzzy message was used.\n  : msgid 'A package item must belong to a package model'\nrake aborted!\nSyntaxError: (eval):1: syntax error, unexpected tIDENTIFIER, expecting keyword_end\nclass ::LeihsDBIOReturn 20 items to check < ActiveRecord::Base\n                                ^\n/home/leihs/lib/leihs/dbio.rb:13:in `eval'\n/home/leihs/lib/leihs/dbio.rb:13:in `rows'\n/home/leihs/lib/leihs/dbio.rb:23:in `block in data'\n/home/leihs/lib/leihs/dbio.rb:22:in `map'\n/home/leihs/lib/leihs/dbio.rb:22:in `data'\n/home/leihs/lib/leihs/dbio.rb:29:in `export'\n/home/leihs/lib/tasks/leihs/dbio.rake:6:in `block (3 levels) in <top (required)>'\n/usr/local/rvm/rubies/ruby-2.3.0/bin/bundle:23:in `load'\n/usr/local/rvm/rubies/ruby-2.3.0/bin/bundle:23:in `<main>'\nTasks: TOP => leihs:dbio:export\n(See full trace by running task with --trace)", "stderr_lines": ["+ source /etc/profile.d/rbenv-load.sh", "+++ rbenv init -", "++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"", "source \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"", "rbenv rehash 2>/dev/null", "rbenv() {", "  command=\"$1\"", "  if [ \"$#\" -gt 0 ]; then", "    shift", "  fi", "", "  case \"$command\" in", "  shell)", "    eval `rbenv \"sh-$command\" \"$@\"`;;", "  *)", "    command rbenv \"$command\" \"$@\";;", "  esac", "}'", "+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash", "++++ complete -F _rbenv rbenv", "+++ rbenv rehash", "+ cd /home/leihs/", "+ export RAILS_ENV=production", "+ RAILS_ENV=production", "+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ gem install bundler --no-rdoc --no-ri", "+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "Warning: fuzzy message was used.", "  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'", "Warning: fuzzy message was used.", "  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'", "Warning: fuzzy message was used.", "  : msgid 'Delegation'", "Warning: fuzzy message was used.", "  : msgid 'A package item must belong to a package model'", "rake aborted!", "SyntaxError: (eval):1: syntax error, unexpected tIDENTIFIER, expecting keyword_end", "class ::LeihsDBIOReturn 20 items to check < ActiveRecord::Base", "                                ^", "/home/leihs/lib/leihs/dbio.rb:13:in `eval'", "/home/leihs/lib/leihs/dbio.rb:13:in `rows'", "/home/leihs/lib/leihs/dbio.rb:23:in `block in data'", "/home/leihs/lib/leihs/dbio.rb:22:in `map'", "/home/leihs/lib/leihs/dbio.rb:22:in `data'", "/home/leihs/lib/leihs/dbio.rb:29:in `export'", "/home/leihs/lib/tasks/leihs/dbio.rake:6:in `block (3 levels) in <top (required)>'", "/usr/local/rvm/rubies/ruby-2.3.0/bin/bundle:23:in `load'", "/usr/local/rvm/rubies/ruby-2.3.0/bin/bundle:23:in `<main>'", "Tasks: TOP => leihs:dbio:export", "(See full trace by running task with --trace)"], "stdout": "Successfully installed bundler-1.16.3\n1 gem installed", "stdout_lines": ["Successfully installed bundler-1.16.3", "1 gem installed"]}

**Comment by nadjaweisskopf** [comment]
@AnthonyHunt We are not familiar with the error you describe, which makes it hard for us to give a satisfying answer. Can you please note all steps in detail, until you reach this error? That might give us a clue, where the problem could lie. 
Did you follow the steps described in our Wiki? This article might also give you a hint, what could have gone wrong: https://github.com/leihs/leihs/wiki/Upgrading-3.45.1-to-4.x,-inofficial-guide

**Comment by AnthonyHunt** [comment]
I have been following both those steps and the steps here https://github.com/leihs/leihs-instance/blob/master/GUIDE.md.  All of the steps have been working as documented on the current server build. The problem is currently with the database on the old installation and exporting it.  

Might there be a different way of exporting the database? maybe as SQL and converting it to Postgres?  I can manually copy the attachments over using ssh/sftp.  The most important thing for us is the items.  I can leave the old system running for historys if necessary.

I'm happy to give you remote access to the servers if you want to play?

Anthony.

**Comment by nadjaweisskopf** [comment]
@AnthonyHunt Could you please send us a dump with the MySQL version that you are using. We'll try to export the data and see if it works with our standard-leihs-environment.

**Comment by DrTom** [comment]
We could get to the bottom of this with the help of your dump. You have an additional table by the name `return 20 items to check`. 
```
mysql> show tables;
+---------------------------------+
| Tables_in_leihs_worcester       |
+---------------------------------+
| access_rights                   |
...
| return 20 items to check        |
...
```

We do not know where this is coming from. We suspect it was added manually. We can not program the exporter to handle manually modified DB schemas. Even if there is some need to copy a table temporarily the name here was chosen very poorly. It goes against RoR (and practically all accepted other) conventions. Additional it fooled us since it looks like a part of a programmed expression to expect the problem in the programming stack.
