### ISSUE TITLE
Sort the list of items in the inventory list according to the inventory code

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#611]
#### Expected behaviour
When collapsing the model in the inventory list, the items of this model should be sorted according to the inventory codes. 

Please check if this change has any side effects on other  have to do with the sorting in the hand over or similar. 

#### Actual behaviour
I can not see any sort order in the inventory list when collapsing the models. 

#### Steps to reproduce
1. go to pool
2. go to inventory list
3. collapse a model with several items

#### Specifications
- Leihs version: 4.19.0
- Browser version: safari

<img width="987" alt="bildschirmfoto 2018-07-20 um 07 24 33" src="https://user-images.githubusercontent.com/3356016/43441054-b70671e0-9499-11e8-8d5d-abc7438b2386.png">

Requirement from Armando

**Comment by nadjaweisskopf** [comment]
@nimaai inside the packages the items are not listed alphabetically

![bildschirmfoto 2018-10-24 um 11 24 45](https://user-images.githubusercontent.com/3356016/47421298-94fa0880-d780-11e8-82fe-6faa9f659f9d.png)

**Comment by nimaai** [comment]
> inside the packages the items are not listed alphabetically

@nadjaweisskopf Are you sure we want to have it here too? Items of a package can be of different models and sorting them according to the model name is perhaps better?

**Comment by nadjaweisskopf** [comment]
accepted
