### ISSUE TITLE
V5 - Userliste aufräumen

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#614]
Löschen wenn der User : 

- **Keine Verträge und keine Reservationen hat
- UND nicht eine Delegationen ist**
- Mit Datum versehen - bis zu diesem Datum soll gelöscht werden
- Nur enabled wenn ZHdK-Instanz

**Comment by DrTom** [comment]
Phuuuu, das ist doch nicht so einfach wie gedacht. Es gibt noch zig andere Tabellen die kein `delete on cascade` haben und auf die :users Tabelle zeigen, darunter :entitlement_groups_users :procurement_category_inspectors, und jetzt noch die :users Tabelle selbst wegen der delegators. 

Im Moment wollen wir glaube ich noch nicht überall `delete on cascade` einführen. Zumindest überblicke ich die Konsequenzen nicht. Ich stoppe dieses Vorhaben fürs erste und wir diskutieren das in 2 Wochen wieder.

**Comment by nadjaweisskopf** [comment]
@DrTom ja ok, kein Problem. Ich nimms fürs Refinement auf.

**Comment by nadjaweisskopf** [comment]
Nothing to be done at the moment - we will have a look at the user list after implamantation of V5

**Comment by nadjaweisskopf** [comment]
Nothing to be done just now.
