### ISSUE TITLE
Testing procurement

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#615]
************************************************** 
******************    TESTS OK   ****************** 
************************************************** 
- [x] The user information is not shown in a user friendly design: 
![bildschirmfoto 2018-08-15 um 09 06 48](https://user-images.githubusercontent.com/3356016/44135726-a12afbb6-a06a-11e8-9ba9-ab18eb1041a6.png)
//only for tests - will vanish => https://github.com/orgs/leihs/projects/1#card-12345883
PART OF UI
- [x] The link "view request" in requests of budget preriods which are already finished, does not lead to the request - blank page. 
- [x] As Inspector / Inspector and Requeter - I get an error when I save a template
<img width="803" alt="bildschirmfoto 2018-09-25 um 15 49 39" src="https://user-images.githubusercontent.com/3356016/46018641-a21ccc80-c0da-11e8-9c2a-1d6ea9eddcb7.png">
- [ ] As Admin, don't delete the fields of a request when moving to other categories or budget periods. 
- [ ] When I edit a request which was created from a template, the fields such as model or supplier or price are suddenly editable. 
- [x]  =>Test was not ok -  https://github.com/orgs/leihs/projects/1#card-12652551
<img width="444" alt="bildschirmfoto 2018-09-12 um 10 17 44" src="https://user-images.githubusercontent.com/3356016/45411865-a0ccb800-b675-11e8-9213-0277f503ab82.png">

- [x] viewer only sees his own categories in category filter

- [x] All states for viewer - and mark active budget periods
- [x] active budget periods should be selected for all roles
- [x] If I am not Requester, the green plus should not be shown (even in the inspection phase).  ![bildschirmfoto 2018-09-17 um 10 34 26](https://user-images.githubusercontent.com/3356016/45613054-511b3180-ba65-11e8-8a6c-01fcfb639518.png)
=> new, inspector must be requester to request at all but has special rights: add in inspection phase to own categories.
- [ ] As Admin I should be able to 
- add a new category, 
- update the existing category name
- upload a new picture (status tbd) 
- [x] One filter is missing for the inspector: "Only own categories"
//coming soon => https://github.com/orgs/leihs/projects/1#card-12183237

- [x] If I am inspector without the requester role, I shouldn't see the green plus in the request overview. 
 => can not reproduce. they can enter Requests while in inspection phase, only then the Plus is shown.

![screen shot 2018-09-19 at 08 43 50](https://user-images.githubusercontent.com/134942/45735488-4f2dab80-bbe8-11e8-853a-e34894063c4a.png)

- [x] Remove budget limit per category. 

![bildschirmfoto 2018-09-18 um 15 37 49](https://user-images.githubusercontent.com/3356016/45691383-cd427180-bb58-11e8-8a60-cfeb6e8217c2.png) ![calculate_error](https://user-images.githubusercontent.com/3356016/45628495-83905300-ba94-11e8-99dd-8581aa15d83b.png)
- [x] The inspection fields should not be deleted if the inspector moves the request from one budget phase to another - if the category is not changed (**cannot be reproduced**)

- [x] When filtering requests with status "In Prüfung" I get an error as Admin: In the old version I didn't have the status "In Prüfung" as Admin, (Viewer) or Inspector.
![bildschirmfoto 2018-09-18 um 09 33 41](https://user-images.githubusercontent.com/3356016/45671585-0c0b0400-bb26-11e8-9dcd-eace29df407f.png)

- [x] In certain cases, for example when closing the budget period, requests with a price of CHF 999 are suddenly shown as CHF 10. But we can only reproduce this error as requester only. Admin sees CHF 999 in any case. The amount is calculated with 999 though. 
- [x] We have a very strange behaviour: 
1. gurmir created a request for a request-user
2. Then an inspector edits and adjusts the request
3. Then gurmir moved the request to another category of the same main category
4. the request list now shows to exactly same requests --> see printscreen

![fehler_change_cathegroie](https://user-images.githubusercontent.com/3356016/45625267-bb939800-ba8c-11e8-8b54-c89673668075.png)
- [x] bug with every request that has an attachment! — https://github.com/orgs/leihs/projects/1#card-13049645

<img width="531" alt="bildschirmfoto 2018-09-17 um 13 55 57" src="https://user-images.githubusercontent.com/3356016/45621684-761d9d80-ba81-11e8-889b-434942929817.png">

- [x] Inspection comments are not propagated to the dropdown in the request

![bildschirmfoto 2018-09-17 um 10 37 42](https://user-images.githubusercontent.com/3356016/45613197-cf77d380-ba65-11e8-93d4-f20ed18453dc.png)

- [x] The list of the requesters in the Admin-section "Users" is not completely listed alphabetically. If I add a new user, it is added to the last position and not sorted correctly after a refresh. 

- [x] Typo of Requesters and Procurement Admins should be the same - Main title is "Users"

![bildschirmfoto 2018-09-17 um 10 19 22](https://user-images.githubusercontent.com/3356016/45612431-35af2700-ba63-11e8-9a98-c076fe0cbc2e.png)

- [x] Whole "users" page in Admin section is not translated

- [x] The budget limit (Admin enters the budget limit in the category) doesn't seem to show in the request overview. I'm checking with HUG if we can get rid of these budget limits. 

- [x] After I save the category form, I see the top part of the first category. Please show the whole form or the enter page of the categories. I can't get back to the normal categegory form anymore. I need to refresh the page, to be able to edit a category again. 

![bildschirmfoto 2018-09-17 um 10 04 49](https://user-images.githubusercontent.com/3356016/45611853-4199e980-ba61-11e8-991a-ecb52208b0c4.png)

- [x] The stakeholders did not understand the checkbox "free text" in combination with the model or supplier text field. We need to find a new solution here. *As discussed with Max we could set the field as a text field per default and if the user wan't to choose from the list he needs to chose an option (inside the field).* => Done, but just "flipped" the defaults, User now enters free text by default.

- [x] In the Admin section - categories - the german name for an Inspector is "Prüfer", not "Inspektoren"

- [x] When adding or changing a budget period I get an error => the datepicker was hard to use, especially when entering via text. now it works as expected. 

![bildschirmfoto 2018-09-17 um 09 24 58](https://user-images.githubusercontent.com/3356016/45610253-a0f4fb00-ba5b-11e8-88b4-23f47325d13e.png)

- [x] Following is missing or wrong when exporting to excel:

- [x] Change language from G to E is not possible -- not ok but created new ticket for 5.1

- [x] Can we show the categories a bit smaller? It feels like I have a setting active for elderly people :-)
![bildschirmfoto 2018-08-15 um 09 46 34](https://user-images.githubusercontent.com/3356016/44137311-3cba898e-a070-11e8-86a6-2b3694470dba.png)
//wait for tests
- [x] If the admin is not requester, he can not create a request in requesting phase. In inspection phase he can still create a request. => has to be requester to request. special rights to always create like inspector, but for all categories.
- [x] The Admin should not see the Link "Templates" if he is not inspector
- In the excel, the column tables are missing
- The budget year is missing: 2018 / 2019
- What is "model"?
- "Stückpreis" is actually total
- "Stückpreis" is missing
- "Ersatz/Neu" with false and true is not clear for the user
- Artikel / Herstellernr. is missing
- Lieferant is missing
- Gebäude / Raum are missing
- Reason is missing
- all the special inspector fields are missing such as comment of the inspector, priority of the inspector...

- [x] The supplier was not saved when editing the template as an inspector

<img width="1146" alt="bildschirmfoto 2018-09-12 um 10 50 37" src="https://user-images.githubusercontent.com/3356016/45413565-cf4c9200-b679-11e8-9436-2735e945eb40.png">

- [x] Can we show the field "replacement/new" in red if the user saves without chosing an option? => https://github.com/orgs/leihs/projects/1#card-12375496

![bildschirmfoto 2018-08-28 um 09 18 54](https://user-images.githubusercontent.com/3356016/44706947-81ddfb80-aaa3-11e8-9a21-ff019761700f.png)

- [x]  In Admin section/budget period when saving the budget periods, I do not get a positive response => https://github.com/orgs/leihs/projects/1#card-12347497

- [x]  Moving a request to an earlyer budget period gives an error - Actually it shouldn't be possible to move a request to an earlyer budget period. In the old procurement the closed budget periods where not shown in the list. => https://github.com/orgs/leihs/projects/1#card-12294238
![bildschirmfoto 2018-08-22 um 13 26 30](https://user-images.githubusercontent.com/3356016/44460889-1c0af300-a60f-11e8-8f5d-c46b82f51925.png)

- [x] Also the edit page of the request is large - it filles a whole screen. It all seems to be very big typo and spaces. You can't catch the whole request with the eye. 
//wait for tests => https://github.com/orgs/leihs/projects/1#card-12345946

- [x] Export to CSV / Excel is missing => https://github.com/orgs/leihs/projects/1#card-12187479

- [x]  It shouldn't be possible to press the buttons (delete, move category, move budget phase) if the budget phase has ended. -- still works thogh, buttons are still visible

- [x] The amount calculated for requests with status "new" is not correct. => https://github.com/orgs/leihs/projects/1#card-12790378
old procurement:
<img width="926" alt="bildschirmfoto 2018-08-29 um 14 34 13" src="https://user-images.githubusercontent.com/3356016/44787924-d4e5aa80-ab98-11e8-9fd8-7bced0d8a93e.png">

new procurement:
![fehler_berechnung](https://user-images.githubusercontent.com/3356016/44787953-f3e43c80-ab98-11e8-98a9-a3493919e1df.png)

- [x] When creating a request as inspector in a foreign category in the inspection phase, I get an error. It shouldn't be possible to create a requeset in a foreign category in this phase. => https://github.com/orgs/leihs/projects/1#card-12789765

- [x] it's quite hard to use the filters if the box is so small and doesn't open up like in the old leihs. 
![bildschirmfoto 2018-08-15 um 13 47 04](https://user-images.githubusercontent.com/3356016/44146851-cb2fb93e-a091-11e8-8a9f-f78659fc6bcf.png)
//small priority - we might find something better

- [x] Before, when hovering over a request line, the line changed the colour slightly. We need to see in the test, if the user notices straight away, that the line is clickable. 
//wait for tests

- [x] The main categories are not sorted correctly  => will handle sorting generally in the API 
https://github.com/leihs/leihs-procure/issues/23
NEW: ![bildschirmfoto 2018-08-22 um 13 28 36](https://user-images.githubusercontent.com/3356016/44460961-668c6f80-a60f-11e8-9196-c4f6d53c7bb4.png)
OLD: 
![bildschirmfoto 2018-08-22 um 13 28 36](https://user-images.githubusercontent.com/3356016/44461074-c84cd980-a60f-11e8-886e-288153455abb.png)
 

- [x]  Building and room list should be sorted alphabetically => will handle sorting generally in the API 
https://github.com/leihs/leihs-procure/issues/23

- [x] Upload error when uploading an attachment
![bildschirmfoto 2018-08-15 um 09 23 57](https://user-images.githubusercontent.com/3356016/44136404-fdb46528-a06c-11e8-81c4-2c8f461d4f0e.png)
**//bug - still a problem, test not passed**

- [x] As Admin or inspector I shouldn't be able to change the "request reason" of the request - no matter in which phase I am. => https://github.com/orgs/leihs/projects/1#card-12789765

- [x] Soll: The order quantity can be higher than the approved quantity

- [x] approved quantity needs to be copied to the field order quantity (when typing)

- [x] As inspector it shouldn't be possible to move / delete a request if the request is not in my category

- [x] As an inspector I can't delete the inspectors comment. I delete the comment and save the request. When I reopen the request the comment is filled again. 
- [x] Admin and inspector do not have the green plus to create a request in inspection phase (see excel)

- [x] After I have created a request, I need to scroll to the top in order to navigate to the request list
![bildschirmfoto 2018-08-15 um 09 36 31](https://user-images.githubusercontent.com/3356016/44136989-1b467a20-a06f-11e8-81b6-f6740b192ea9.png)
//Max will implement the aut. scroll to the top and we will see in the tests whether the behaviour is ok or we need to link to the dashboard => https://github.com/orgs/leihs/projects/1#card-12183119

- [x] Frage ist in Englisch, statt auf Deutsch
![bildschirmfoto 2018-08-15 um 09 49 36](https://user-images.githubusercontent.com/3356016/44137397-966d2e1e-a070-11e8-903a-9a0b7b05747d.png)
=> https://github.com/orgs/leihs/projects/1#card-12183146

- [x] The inspectors comment should be mandatory as soon as the the approved amount is less than the requested amount --> see relish: "Give Reason when Partially Excepting or Denying"
- [x] The requests for requesters show "/ITZ" instead of "Nadja Weisskopf / ITZ". The name is missing. In the old procurement it was shown as following: 
![bildschirmfoto 2018-08-28 um 08 51 33](https://user-images.githubusercontent.com/3356016/44705674-97512680-aa9f-11e8-893e-fd952d6361e6.png)

- [x] If I navigate to the request list after creating a request, the new request is not shown unless I refresh the page. 
//Max will check why the new created request is not aut. cashed

- [x] In the current design it is nearly impossible to see the difference between a main category and a sub category when changing the category of a saved request. check how it was in the old procurement. => Increased the spacing for the headers to make them stand out more. they are also not selectable/don't change color on hove. maybe the hover state could be higher contrast, like in the User-Search. I did not add the arrows (very noisy) but if its still not clear enough we can also do that.

- [x] I found it hard to find the category needed. I am a bit overwhelmed with information shown. I see loads of "Ohne Vorlage erstellen" and the category fades to the back. In the procurement before it was much easyer to find a category. If the category did not have a template, you just had the "+". For the user it is easyer this way. 
Now: ![bildschirmfoto 2018-08-15 um 09 11 14](https://user-images.githubusercontent.com/3356016/44135998-75c2735e-a06b-11e8-96d0-c7efc7b1519b.png)
Before: 
![bildschirmfoto 2018-08-15 um 09 20 33](https://user-images.githubusercontent.com/3356016/44136308-a16116ae-a06c-11e8-9213-a042dbd12026.png)
//ok, like before

- [x] It is not clear, where the request starts and where the header of the request is. Can the design help the user to see straight away where the fields of the contract start. 
![bildschirmfoto 2018-08-15 um 09 14 00](https://user-images.githubusercontent.com/3356016/44136091-b8ed52ac-a06b-11e8-85d9-396673ecf2f0.png)
//wait for tests - no change at the moment

- [x] After typing the receiver name, I am asked if I would like to fill in the field automatically. If I press yes, the name is filled in the fields above too. 
![bildschirmfoto 2018-08-15 um 09 18 50](https://user-images.githubusercontent.com/3356016/44136242-55bd3930-a06c-11e8-9d4c-c59f0964ac29.png)
//nadja will talk with B2 if this could be deactivated on the browsers 

- [x] Field "Ersatz/Neu" should not be marked per default - user has to choose a value

- [x] In the inspection phase, it shouldn't be possible to create a request as a requester.
![bildschirmfoto 2018-08-22 um 12 55 07](https://user-images.githubusercontent.com/3356016/44459671-bfa5d480-a60a-11e8-9c2d-90d5be923ca9.png)

- [x] In the inspection phase it shouldn't be possible to change the supplier or the model as requester
![bildschirmfoto 2018-08-22 um 12 57 31](https://user-images.githubusercontent.com/3356016/44459729-f7148100-a60a-11e8-81e6-612bc381f24f.png)
![bildschirmfoto 2018-08-22 um 12 59 01](https://user-images.githubusercontent.com/3356016/44459811-317e1e00-a60b-11e8-958b-709e1906f5f5.png)

-->test ok
- [x] The price should not be a mandatory field
//field min. 0 and not 1 - we'll keep the star and the field is still mandatory

-->test ok
- [x] When choosing a request from a template, it shouldn't be possible to change the setting on "supplier". At the moment, if you deselect "free text" then the supplier is emptied. 
![bildschirmfoto 2018-08-15 um 13 18 20](https://user-images.githubusercontent.com/3356016/44145973-da05afda-a08d-11e8-8cd1-649adcfb312c.png)
//bug - will inform when to retest

**--> it is still possible to choose a room**
- [x] If "Undefined building" is selected in a request, the room should not be anything else than "undefined". At the moment it is possible to choose a rooms, which doesn't make sense. 
![bildschirmfoto 2018-08-15 um 13 20 34](https://user-images.githubusercontent.com/3356016/44146035-1eb18cf8-a08e-11e8-90e1-0e5c55274c0a.png)
//Matus could send the info, when "undefined building" then only "undefined room"

-->test ok / we might want to write 0 CHF
- [x] The sums on the categories in the request overview are missing
//coming soon

-->test ok
- [x] Field Replacement/New is missing
//will come soon

-->test ok
- [x] Please sort the category list alphabetically when creating a request
![bildschirmfoto 2018-08-15 um 13 42 26](https://user-images.githubusercontent.com/3356016/44146682-10a3608e-a091-11e8-881e-784a17450de1.png)
//ok

-->test ok
- [x] Link "Kontakt" does not work - should be linked to 
// Needs Backend (current query is only for admins!)

- [x] Creating a request for another person is missing
//coming soon

-->test ok
- [x] Both priorities should be selected in the filter from the start.
//When resetting the filters both priorities will be selected - Max will inform when I can retest

-->test ok
- [x] The zero "0" can not be deleted when entering an amount: 
![bildschirmfoto 2018-08-15 um 09 33 45](https://user-images.githubusercontent.com/3356016/44136804-76acad9a-a06e-11e8-8363-5e026e88727f.png)
//small priority, Max will check if there is any solution - see in tests
// correction from max: it was my bug, browser behaviour is like we expect!

-->test ok
- [x] I would prefer the user to see the request list straight away when loggin in and then choosing to create a new request. 
![bildschirmfoto 2018-08-15 um 09 31 33](https://user-images.githubusercontent.com/3356016/44136701-06e97b5a-a06e-11e8-8a65-360e77df1241.png)
//ok

**-->test ok**
- [x] Can the list of templates be sorted alphabetically? First numbers, then letters?
![bildschirmfoto 2018-08-15 um 09 11 47](https://user-images.githubusercontent.com/3356016/44135935-44ff64f2-a06b-11e8-8735-2128fd688c3d.png)

-->test ok
- [x] When selecting a model the wrong list is show - instead of showing the model list, the users are shown. 
![bildschirmfoto 2018-08-15 um 09 15 52](https://user-images.githubusercontent.com/3356016/44136136-e2633d2c-a06b-11e8-9109-7174257f1c09.png)
//still open - Max will inform when I can test

-->test ok
- [x] When typing the supplier, the field reacts strange. It shivers when typing with each letter I type. 
//bug - Max will inform when I ca retest

**Comment by eins78** [comment]
@nadjaweisskopf done tasks are checked. some comments:
- when creating new request, everything is sorted by name: Maincategories, Categories, Templates
- number `0` in input field can now be deleted, it simply was a bug
- uploads: they should work now, but somtimes the spinner is not going way (until saving). I need to do further debugging on the real server.
- Request.User aka "Antragssteller" is now a normal field / can also be changed later (if permissions ok). [See scenarios](https://github.com/leihs/leihs-procure/wiki#creating-request-for-another-user)
