### ISSUE TITLE
Testing Procurement - Design

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#618]
TESTS OK

- [x] The requester should not see the label "order amount" in the request

- [x] Bug in following behaviour: 
1. inspector saves a request and enters approved amount same as requested amount
2. inspector edits the request and deletes hte approved amount - then saves
3. inspector gets an error: 
- [x] The wrong price is shown - instead of CHF 2100 the price shown is CHF 21. The calculation is correct thogh. 

<img width="1181" alt="bildschirmfoto 2018-09-12 um 10 45 08" src="https://user-images.githubusercontent.com/3356016/45413242-040c1980-b679-11e8-872a-8efcc57f65ed.png">

- [x] Don't show the label "replacement/new" in the request overview
- [x] They couldn't see on one glimpse that the header of the request belongs to the collapsed request / Title of the request is smaller than the content of the request itself
- [x] They feel there are too many different typos on the overview page
  
- [x] Marco still had to scroll to the top after creating a request. The menu bar was not shown. => added test page in styleguide so we can easily try and debug https://v5.test.leihs.zhdk.ch/procure/dev/playground/redirect-and-scroll-to-top
- [x] As Admin after I typed order amount, approved amount (< requested amount), comment, then saved, I got an error: 
<img width="1176" alt="bildschirmfoto 2018-09-17 um 16 26 00" src="https://user-images.githubusercontent.com/3356016/45629351-7b391780-ba96-11e8-886a-59faad2454f2.png">

- [x] In the request please rename the field "Antrag**s**steller" to "Antragsteller"
- [x] The amounts are not calculated correctly. Should be: CHF 7000 (logged in as Admin)
<img width="1108" alt="bildschirmfoto 2018-09-17 um 16 28 57" src="https://user-images.githubusercontent.com/3356016/45629483-d1a65600-ba96-11e8-8724-5f7aea732636.png"> => Q: did this happen after editing one the requests in the screenshot? If yes it is "just" stale data, otherwise a more serious bug.
- [x] They would wish to have a smaller typo to have a better overview of request lines and totals
- [x] They would wish to see at least the whole request (when collapsed) with it's functions and the save button on one page.
- [x] It's not clear where the collapsed request ends and where the next request line or the next collapsed request starts. 
- [x] All sums of requests, categories and main categories should be in one row - they didn't see the connection between these totals.
- [x] Field "Ersatz/Neu" seems to already be filled out per default. It would be nice, if the round checkboxes could be white so the user understands on first view, that he needs to fill out the checkbox. Same with "Abrechnungsart"
- [x]  All amounts (CHF) should be right aligned.
- [x] The request should be closed after saving an existing request in the overview. 
- [x] Status should be in different colours - same as old procurement

**Comment by eins78** [comment]
ButtonRadio / "Neu/Ersatz" picker:

![screen shot 2018-09-13 at 12 30 40](https://user-images.githubusercontent.com/134942/45483309-e0b49d80-b750-11e8-92d8-50b3b5b48b3b.png)
![screen shot 2018-09-13 at 12 30 44](https://user-images.githubusercontent.com/134942/45483311-e1e5ca80-b750-11e8-96a4-08c09f192af5.png)

**Comment by eins78** [comment]
dashboard heading sizes decreased. images are also a bit smaller.

#### old:

---
<img width="1400" alt="screenshot 2018-09-21 at 17 26 32" src="https://user-images.githubusercontent.com/134942/45890620-b784b480-bdc3-11e8-9d17-a637b7626b63.png">
---

#### new:

---
<img width="1400" alt="screenshot 2018-09-21 at 17 30 21" src="https://user-images.githubusercontent.com/134942/45890781-0f232000-bdc4-11e8-9462-b407f2171c8c.png">
---
