### ISSUE TITLE
Import v3 to v4 part 2.

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#619]
Having gotten past my previous problem, and mis reading another error. I find myself stuck at an error we've previously encountered but at a different place.

I'm now getting this error:
```
Sep 04 14:01:42 dac-leihs02 ruby[13049]: DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Sep 04 14:01:42 dac-leihs02 ruby[13049]: Please use `config.public_file_server.enabled = false` instead.
Sep 04 14:01:42 dac-leihs02 ruby[13049]:  (called from block in <top (required)> at /leihs/database/config/environments/production.rb:25)
Sep 04 14:01:42 dac-leihs02 ruby[13049]: rake aborted!
Sep 04 14:01:42 dac-leihs02 ruby[13049]: StandardError: An error has occurred, this and all later migrations canceled:
Sep 04 14:01:42 dac-leihs02 ruby[13049]: No indexes found on partitions with the options provided.
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /leihs/database/db/migrate/212_renaming_groups.rb:4:in `up'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `load'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: ArgumentError: No indexes found on partitions with the options provided.
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /leihs/database/db/migrate/212_renaming_groups.rb:4:in `up'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `load'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'
Sep 04 14:01:42 dac-leihs02 ruby[13049]: Tasks: TOP => db:migrate
Sep 04 14:01:42 dac-leihs02 ruby[13049]: (See full trace by running task with --trace)
Sep 04 14:01:42 dac-leihs02 ruby[13049]: == 212 RenamingGroups: migrating ==============================================
Sep 04 14:01:42 dac-leihs02 ruby[13049]: -- remove_index(:partitions, [:model_id, :inventory_pool_id, :group_id])
```

which is identical to:
https://github.com/leihs/leihs/issues/581

but this is coming from the V3 to V4 migration script.

**Comment by AnthonyHunt** [comment]
Se my test server is falling over with the above error, with subsequent deployments failing with "legacy.service" failing to start.  I'm guessing theres something quirky in the database?

Server 1 of 3 production servers is failing over with this error:
`TASK [fetch-v3-data : export db_data.yml] ***********************************************************************************************************
fatal: [dac-leihs01.uni.worc.ac.uk]: FAILED! => {"changed": true, "cmd": "set -eux\n source /etc/profile.d/rbenv-load.sh\n cd /home/leihs/leihs/\n export RAILS_ENV=production\n export PATH=\"/usr/local/rvm/rubies/ruby-2.3.0/bin:${PATH}\"\n gem install bundler --no-rdoc --no-ri\n ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "delta": "0:09:12.533175", "end": "2018-09-05 14:23:59.972775", "msg": "non-zero return code", "rc": -9, "start": "2018-09-05 14:14:47.439600", "stderr": "+ source /etc/profile.d/rbenv-load.sh\n+++ rbenv init -\n++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"\nsource \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"\nrbenv rehash 2>/dev/null\nrbenv() {\n  command=\"$1\"\n  if [ \"$#\" -gt 0 ]; then\n    shift\n  fi\n\n  case \"$command\" in\n  shell)\n    eval `rbenv \"sh-$command\" \"$@\"`;;\n  *)\n    command rbenv \"$command\" \"$@\";;\n  esac\n}'\n+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash\n++++ complete -F _rbenv rbenv\n+++ rbenv rehash\n+ cd /home/leihs/leihs/\n+ export RAILS_ENV=production\n+ RAILS_ENV=production\n+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n+ gem install bundler --no-rdoc --no-ri\n+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml\nWarning: fuzzy message was used.\n  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'\nWarning: fuzzy message was used.\n  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'\nWarning: fuzzy message was used.\n  : msgid 'Delegation'\nWarning: fuzzy message was used.\n  : msgid 'A package item must belong to a package model'", "stderr_lines": ["+ source /etc/profile.d/rbenv-load.sh", "+++ rbenv init -", "++ eval 'export PATH=\"/root/.rbenv/shims:${PATH}\"", "source \"/usr/lib/rbenv/libexec/../completions/rbenv.bash\"", "rbenv rehash 2>/dev/null", "rbenv() {", "  command=\"$1\"", "  if [ \"$#\" -gt 0 ]; then", "    shift", "  fi", "", "  case \"$command\" in", "  shell)", "    eval `rbenv \"sh-$command\" \"$@\"`;;", "  *)", "    command rbenv \"$command\" \"$@\";;", "  esac", "}'", "+++ export PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ PATH=/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+++ source /usr/lib/rbenv/libexec/../completions/rbenv.bash", "++++ complete -F _rbenv rbenv", "+++ rbenv rehash", "+ cd /home/leihs/leihs/", "+ export RAILS_ENV=production", "+ RAILS_ENV=production", "+ export PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ PATH=/usr/local/rvm/rubies/ruby-2.3.0/bin:/root/.rbenv/shims:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "+ gem install bundler --no-rdoc --no-ri", "+ ruby -S bundle exec rake leihs:dbio:export FILE=/tmp/export/db_data.yml", "Warning: fuzzy message was used.", "  : msgid 'The item cannot be retired because it's not returned yet or has already been assigned to a contract line.'", "Warning: fuzzy message was used.", "  : msgid 'This contract is not signable because the delegated user is either missing or not part of this delegation.'", "Warning: fuzzy message was used.", "  : msgid 'Delegation'", "Warning: fuzzy message was used.", "  : msgid 'A package item must belong to a package model'"], "stdout": "Successfully installed bundler-1.16.4\n1 gem installed", "stdout_lines": ["Successfully installed bundler-1.16.4", "1 gem installed"]}
	to retry, use: --limit @/dac-leihs01/leihs/deploy/import-v3-into-v4_play.retry
`
and servers 3 & 4 with this error:
`TASK [import-v3-into-v4 : do import] ****************************************************************************************************************
fatal: [10.101.83.33]: FAILED! => {"changed": true, "cmd": "#/bin/bash\n set eux\n cd /leihs/legacy\n export PATH=/home/leihs-legacy/.rubies/ruby-2.4.2/bin:$PATH\n export RAILS_ENV=production\n export FILE=/tmp/import-v3/db_data.yml\n export ATTACHMENTS_PATH=/tmp/import-v3/public/attachments/\n export IMAGES_PATH=/tmp/import-v3/public/images/attachments/\n export PROCUREMENT_ATTACHMENTS_PATH=/tmp/import-v3/public/system/procurement/attachments/files/\n export PROCUREMENT_IMAGES_PATH=/tmp/import-v3/public/system/procurement/main_categories/images/\n bundle exec rake leihs:dbio:import", "delta": "0:00:42.624221", "end": "2018-09-04 17:58:04.518348", "msg": "non-zero return code", "rc": 1, "start": "2018-09-04 17:57:21.894127", "stderr": "rake aborted!\nNoMethodError: undefined method `documentation_link' for #<Setting:0x000055aa41160d78>\n/leihs/legacy/config/initializers/settings.rb:38:in `<top (required)>'\n/leihs/legacy/config/environment.rb:5:in `<top (required)>'\n/home/leihs-legacy/.rubies/ruby-2.4.2/bin/bundle:23:in `load'\n/home/leihs-legacy/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'\nTasks: TOP => leihs:dbio:import => environment\n(See full trace by running task with --trace)", "stderr_lines": ["rake aborted!", "NoMethodError: undefined method `documentation_link' for #<Setting:0x000055aa41160d78>", "/leihs/legacy/config/initializers/settings.rb:38:in `<top (required)>'", "/leihs/legacy/config/environment.rb:5:in `<top (required)>'", "/home/leihs-legacy/.rubies/ruby-2.4.2/bin/bundle:23:in `load'", "/home/leihs-legacy/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'", "Tasks: TOP => leihs:dbio:import => environment", "(See full trace by running task with --trace)"], "stdout": "Languages created: Deutsch, English (UK), English (US), Züritüütsch", "stdout_lines": ["Languages created: Deutsch, English (UK), English (US), Züritüütsch"]}
	to retry, use: --limit @/ises-leihs01/leihs/deploy/import-v3-into-v4_play.retry
`

All of these servers are identical in deployment from the test server. The only that has happened to each is that they have been used (with occasional data from server 1 being copied back to the test server by sql dump).  I don't understand why I'm having so many problems with this. Admittedly the problem before was our own fault!

Anthony.

**Comment by AnthonyHunt** [comment]
Any update folks?

**Comment by eins78** [comment]
@AnthonyHunt Can you please state precisely the relevant version so we can try to guess some possible causes? I mainly mean the leihs version (currently) migrated from and to, as well as the project commit you have checked out.
At first glance, there seems to be a mismatch here: the error from your log is happening in migration Nr. 212, *which is not part of v4.0 or 4.1*. 
The specific error happens because indexes are missing on a table, which either means the DB was manually altered or some steps were skipped while upgrading.

**Comment by AnthonyHunt** [comment]
Hi Eins78,

Thanks for your reply.  I'm also slightly puzzled by the error coming from the newer release as I thought I had specified 4.1 in the initial migration.  I had been following two guides (both here).  The first got replaced with the second a few days in to the transition and I started again.

https://github.com/leihs/leihs-instance/blob/master/GUIDE.md

Which I now note doesn't have an option for specifying which version to use as the base.

I think I had already said that the database itself is from the V1 release which has been migrated along the way to V3.45? (the last update of V3).  There may have been errors in previous migrations that have been missed along the way? but the database passes all of the V3 internal checks.

If I can start again with a new deployment specifying 4.1? in the 

`which ansible-playbook || echo 'install ansible first!'
git clone git@github:yourUserName/leihs-instance my-leihs
cd my-leihs
sh -c 'git submodule update --init leihs && cd leihs && git submodule update --init --recursive'`

?? would this help?

Thanks,

Anthony.

**Comment by eins78** [comment]
@AnthonyHunt You can specify any (git-tagged) leihs version with the following command, after the command you quoted:

    sh -c 'cd leihs && git fetch --tags && git reset --hard "4.1.0" -- && git submodule update --recursive'

You should also check that in:

    git add leihs && git commit -m 'set leihs version to 4.1.0'

**Comment by nadjaweisskopf** [comment]
Please reopen ticket, if problem is not solved.

**Comment by AnthonyHunt** [comment]
Finally got to 4.5.1 with a bit of work and needed to change the postgres template to unicode too. I deployed an upgraded with 

`
sh -c 'cd leihs && git fetch --tags && git reset --hard "4.5.1" -- && git submodule update --recursive'
ansible-playbook leihs/deploy/import-v3-into-v4_play.yml -i hosts
`

The update to 4.6.0 seems to work on my test server but going any further (I've tried 4.7.3, 4.8.0, 4.10.0) results in the dreaded "Unable to start service leihs-legacy.service: Job for leihs-legacy.service failed because the control process exited with error code." error. I'm upgrading with the commands 

`
sh -c 'cd leihs && git fetch --tags && git reset --hard "4.6.0" -- && git submodule update --recursive'
ansible-playbook leihs/deploy/deploy_play.yml -i hosts -v
`

I know before this was because of the backup on deploy issue but this is no longer the case.

Any thoughts?

**Comment by eins78** [comment]
`Unable to start service leihs-legacy.service` means the webapp itself could not be started. It seems to me you were thinking of a similar message, but for the database/migration service (having to do with "backup on deploy".

You can find out what went wrong with `journalctl -xe leihs-legacy.service`.

**Comment by eins78** [comment]
Again, there seems to be a weird mismatch between (source code) version – the log shows an error regarding a missing rake tasks `app:db:create_fields`. This [task was removed in 4.8.0](https://github.com/leihs/leihs_legacy/commit/4bd38c28d8b88a1dca1f35d41175b2519eab3614), *along with the calling code*, so I can't really explain what tries to run this tasks and/or why it is missing in your version 4.5.3 or 4.6.9.

But, taking a step back: Since you have migrated to *a* 4.x version, have you tried importing that directly into a fresh 5.0 instance? If you're lucky (e.g. your database does not have any weird state) that might just work.

**Comment by AnthonyHunt** [comment]
ahhh, that mismatch will be because after 4.7.3 failing I tried 4.8.0 and then this morning 4.10.

I'd be very happy to try!!! Can I go from 4.5.1 to 5 (the db went to 4.5.1 okay but I'm not sure what other migrations are needed along the way)? I've not even looked at 5 yet because getting to 4 was so problematic.

Ant.

**Comment by eins78** [comment]
> I'd be very happy to try!!! Can I go from 4.5.1 to 5 (the db went to 4.5.1 okay but I'm not sure what other migrations are needed along the way)?

Yes, v5 *should* contain all the needed migrations to "import" any previous leihs version. I say "should" because many migrations were combined together, which is a manual process, therefore there could be an error. 

On the other hand, by going step by step between each leihs version you do make sure that really all migrations are run, but you (statistically) increase the chances of things going wrong.

**Comment by AnthonyHunt** [comment]
Can I just do:

sh -c 'cd leihs && git fetch --tags && git reset --hard "5.0.1" -- && git submodule update --recursive' ansible-playbook leihs/deploy/import-v3-into-v4_play.yml -i hosts

I'm not sure how I can go step by step at the moment because of the above error message.

**Comment by eins78** [comment]
No,

you should do a) a first do a fresh deploy of 5.0.1, then b) restore the data from your v4 instance, then do a) again. You can use the `dump-and-fetch_play` to get the v4 dump (it will be in your local deploy directory in the `tmp` folder).

a) 
```
sh -c 'cd leihs && git fetch --tags && git reset --hard "5.0.1" -- && git submodule update --recursive --init'; cd deploy ansible-playbook deploy_play.yml -i hosts
```

b)
```
MY_LEIHS_DUMP=/path/to/dump.psql
sh -c 'cd leihs/deploy ansible-playbook db-restore_play.yml -i hosts -e 'database_dump_restore_file_path=$MY_LEIHS_DUMP'
```

**Comment by AnthonyHunt** [comment]
Scary stuff!!! as big a leap fro 3 to 4!

`sh -c 'cd leihs/deploy ansible-playbook fetch-latest-dump_play.yml  -i hosts'
sh -c 'cd leihs && git fetch --tags && git reset --hard "5.0.1" -- && git submodule update --recursive --init'; cd deploy ansible-playbook deploy_play.yml -i hosts
MY_LEIHS_DUMP=/path/to/dump.psql
sh -c 'cd leihs/deploy ansible-playbook db-restore_play.yml -i hosts -e 'database_dump_restore_file_path=$MY_LEIHS_DUMP''
sh -c 'cd leihs && git fetch --tags && git reset --hard "5.0.1" -- && git submodule update --recursive --init'; cd deploy ansible-playbook deploy_play.yml -i hosts`

that look about right?

I may have a solution to the previous which I'm trying first.  In the deployment/upgrade guide there was a reference to change `roles/ruby-install/tasks/main.yml` because of the libssl-dev libssl1.0-dev thing.  I noticed I was getting a failed as i need to commit changes message.  So I've zapped by install directory and remade my hosts file and started the deployment from scratch. On this occasion 4.7.3 wouldn't set as head because `Fetched in submodule path 'legacy/public/assets', but it did not contain c2317937cbc9f8873b2a108db2f1a86ab6ba5fc5. Direct fetching of that commit failed.` so I'm trying 4.8.0....

Holding my breath.

**Comment by eins78** [comment]
> that look about right?

there seem to be a few misplaced quotes, and the `/path/to/dump.psql` needs to be changed to the correct one, but otherwise it looks ok.

**Comment by AnthonyHunt** [comment]
Thanks.  Incremental updates now appear to be working on my test server. I'm going to bring this to 4.19 during the afternoon and try the 5 upgrade later this evening.  I'll also try a couple of the staged updates on my main servers (now I'm more confident of the reason they stuck on the test server).  Downside is that I need to do a full backup of the VM before hand incase of problems so that I can roll back.

With any luck I'd like to get to v5 on all the server before the end of the week (when Christmas break starts here).

a HUGE thank you for your help today.  I'll update the progress but feeling very happy that we are getting there.

Ant.

**Comment by AnthonyHunt** [comment]
The progressive upgrade to 4.19.5 worked on all of my servers. But not to 5.0.1.

I feel I should open a new issue at this point as technically this one is resolved.
