### ISSUE TITLE
Migration error from 4.6.0 to 4.7.0

### ISSUE THREAD

**Issue by HSLUwem** [leihs/leihs#620]
When migrating from LEIHS 4.6.0 to 4.7.0 via Ansible playbooks, I get the following error messages:

Ansible-Error:
![error_from460to470](https://user-images.githubusercontent.com/32535851/45210084-f0cf0780-b28e-11e8-91fc-39d96c1f468f.JPG)

Output from "journalctl -u leihs*":
[Error_From460to470.txt](https://github.com/leihs/leihs/files/2360389/Error_From460to470.txt)

It looks like there are still incorrect records in the database.

**Comment by nimaai** [comment]
@HSLUwem Could you send us dump of your DB via some secure channel?

**Comment by HSLUwem** [comment]
> 
> 
> @HSLUwem Could you send us dump of your DB via some secure channel?

I have just sent the dump to you via SWITHCFilesender.

**Comment by nimaai** [comment]
@HSLUwem First of all, `4.7.0` is missing one commit for `legacy/public/assets` submodule, so please try directly version `4.8.0`.

The migration fails because there are 20 reservations with status `closed` but `contract_id = NULL`. This is an invalid state according to the business logic and that's why there is a constraint error. 

You can use the following query to find out more details of the concerned reservations:

```sql
select rs.id,
       status,
       contract_id,
       users.firstname || ' ' || coalesce(users.lastname, '') as user_name,
       items.inventory_code,
       models.product || ' ' || coalesce(models.version, '') as model_name,
       inventory_pools.name as pool_name,
       rs.created_at
from reservations rs
join items on rs.item_id = items.id
join models on rs.model_id = models.id
join users on rs.user_id = users.id
join inventory_pools on rs.inventory_pool_id = inventory_pools.id
where
  (status IN ('unsubmitted', 'submitted', 'approved', 'rejected') AND contract_id IS NOT NULL) OR
  (status IN ('signed', 'closed') AND contract_id IS NULL);
```

If you think they can be deleted, then you can do so and try upgrading again (`4.8.0`), otherwise we have to look further...

**Comment by nadjaweisskopf** [comment]
@HSLUwem Did the description above help to migrate to 4.8.0?

**Comment by HSLUwem** [comment]
Ansible-Playbook running without an error and LEIHS 4.8.0 is working but the database is now a fresh one. The run didn't migrate the old data.

Any idea what could be wrong?

**Comment by nadjaweisskopf** [comment]
@HSLUwem do you have any more information? Did you get an error?

**Comment by HSLUwem** [comment]
Updated with the following commands:
git checkout 4.8.0
git submodule update --recursive
ansible-playbook deploy/deploy_play.yml -i hslu-inventory/hosts

No errors in the ansible-run. LEIHS 4.8.0 is running but with an empty database.
Output from "journaltctl -xe | grep leihs":

-- Subject: Unit leihs_create-master-secret.service has begun start-up
-- Unit leihs_create-master-secret.service has begun starting up.
-- Subject: Unit leihs_create-master-secret.service has finished start-up
-- Unit leihs_create-master-secret.service has finished starting up.
Nov 20 09:17:24 as170 ansible-systemd[4010]: Invoked with name=leihs-db-backup.timer enabled=False daemon_reload=False state=stopped user=False masked=None
Nov 20 09:17:24 as170 ansible-systemd[4080]: Invoked with name=leihs-legacy.service enabled=True daemon_reload=False state=started user=False masked=None
-- Subject: Unit leihs-migration.service has begun start-up
-- Unit leihs-migration.service has begun starting up.
Nov 20 09:17:26 as170 ruby[4084]:  (called from block in <top (required)> at /leihs/database/config/environments/production.rb:25)
Nov 20 09:17:27 as170 ruby[4084]: Created database 'leihs'
-- Subject: Unit leihs-migration.service has finished start-up
-- Unit leihs-migration.service has finished starting up.
-- Subject: Unit leihs-legacy.service has begun start-up
-- Unit leihs-legacy.service has begun starting up.
-- Subject: Unit leihs-legacy.service has finished start-up
-- Unit leihs-legacy.service has finished starting up.

**Comment by nimaai** [comment]
@HSLUwem The only possible reason I can think of at the moment is that there is no database `leihs` on the server, that's why it is first created. If this is the case, please ensure there is such a database with all the data and structure of `4.x` version you are trying to upgrade from.

**Comment by nadjaweisskopf** [comment]
We received there dump and there ansible-inventory. I sent the details to @nimaai.

**Comment by nimaai** [comment]
The goal is to test the upgrade to latest 4 version on a local environment.

**Comment by nimaai** [comment]
I could successfully upgrade to latest v4 version `4.19.5`, except for one single problem:

```sql
SELECT *
FROM reservations
WHERE NOT ( (status IN ('unsubmitted',
                        'submitted',
                        'approved',
                        'rejected')
             AND contract_id IS NULL)
           OR (status IN ('signed',
                          'closed')
               AND contract_id IS NOT NULL) );
```

There are 3 `closed reservations` in the DB which cause the migration to crash, because of a DB constraint. I have deleted them manually, then the upgrade succeeded. All of them were `OptionLine`s.

If you don't care so much about them you can delete them too:

```sql
DELETE FROM reservations
WHERE NOT ( (status IN ('unsubmitted',
                        'submitted',
                        'approved',
                        'rejected')
             AND contract_id IS NULL)
           OR (status IN ('signed',
                          'closed')
               AND contract_id IS NOT NULL) );
```

Otherwise you will need to manually assign them to some contract in the DB.

**Comment by nadjaweisskopf** [comment]
nimaai sent mail to HSLU
