### ISSUE TITLE
F+F - only allow German and English

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#626]
set all other "is_active" = false

<img width="1073" alt="bildschirmfoto 2018-09-25 um 16 53 07" src="https://user-images.githubusercontent.com/3356016/46022771-810ca980-c0e3-11e8-897a-4756d0c37a33.png">

**Comment by eins78** [comment]
done

```sql
UPDATE languages SET "active"=FALSE 
WHERE locale_name != 'en-GB' AND locale_name != 'de-CH';
```
