### ISSUE TITLE
Import list of items in leihs

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#628]
[28918_Inventorylist_leihs_Bereinigung.xlsx](https://github.com/leihs/leihs/files/2438113/28918_Inventorylist_leihs_Bereinigung.xlsx)

First need to check with Christian, which column is the one to import.

**Comment by gurmir** [comment]
@nadjaweisskopf Colum to import are Column K

**Comment by nadjaweisskopf** [comment]
@nimaai Please import the list with columns I and K as soon as you find some time.

**Comment by nimaai** [comment]
@nadjaweisskopf Many values in these columns are `#N/A`. What shall i do with those?
