### ISSUE TITLE
E-Mail Templates

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#629]
#### Actual behaviour
Email templates are empty

#### Steps to reproduce
1. go to Admin section
2. go to Email-Templates
3. edit an email template
4. it is empty

Has something gone wrong with the deployment?

#### Specifications
- Leihs version: Production 4.18.0
- Browser version: safari

![bildschirmfoto 2018-10-02 um 16 00 37](https://user-images.githubusercontent.com/3356016/46353384-562ed200-c65c-11e8-8211-3382b911237e.png)

Error, when editing the email templates inside the pool. 

![bildschirmfoto 2018-10-02 um 16 01 41](https://user-images.githubusercontent.com/3356016/46354426-de15db80-c65e-11e8-9eda-0e8a57e30702.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/15a4f0017af2f0fe9d99fb87aa1fca80289f8d56

**Comment by nimaai** [comment]
@nadjaweisskopf fixed on ffzh prod. fixed migration also which applies to all new instances.
