### ISSUE TITLE
Analyse: Keep the marked lines after a page refresh

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#632]
#### Expected behaviour
If I refresh the take back page, I would like the lines to stay marked/selected. 

#### Actual behaviour
As a lending mgr. when taking back items, I mark the lines by selecting the specific line or scanning the item. If I refresh the page though, the markings are gone and I need to start again. 

#### Steps to reproduce
1. go to a take back (as lending or inventory mgr.)
2. select the lines
3. refresh the page
4. the lines are not selected anymore

#### Specifications
- Leihs version: 4.19.3 production
- Browser version: safari

Requirement mentioned by R.B.

**Comment by nadjaweisskopf** [comment]
Ask, if the selection should be saved for other users or just current user on page. 
Ask, if selection should be saved just when refreshing (tab) or also if browser is closed and reopened
What about hand over?

**Comment by nadjaweisskopf** [comment]
Ask, if another user shall see the same selection. So if I scan items, shall these scanned items be visible for other users?

**Comment by nimaai** [comment]
@nadjaweisskopf @eins78 I have rolled out something on http://nimaai.ruby.zhdk.ch. Please try hand over and take back. Test all possibilities you can possibly come up with (separate users, separate browsers, separate tabs within same browser, close tab, close browser, go through whole hand over/take back then refresh, etc. etc.)

https://github.com/leihs/leihs/commit/d3fe146ea9522d01c614108942218ace8a503435

**Comment by eins78** [comment]
mini code review:

- resiliance, needs try/catch(es). not all browsers have `localStorage`, `JSON.parse` can throw, etc. https://github.com/leihs/leihs_legacy/blob/dc0aa38dcedb69eb7fbcc6ccbb162e0337e141b1/app/assets/javascripts/manage/controllers/shared/lines_selection_controller.coffee#L33-L38

- not sure what this means, one of us doesn't quite get it ;) https://github.com/leihs/leihs_legacy/blob/dc0aa38dcedb69eb7fbcc6ccbb162e0337e141b1/app/assets/javascripts/manage/controllers/shared/lines_selection_controller.coffee#L72

- why is the callback called before the next line and not in the `takeback … .done()`? https://github.com/leihs/leihs_legacy/blob/dc0aa38dcedb69eb7fbcc6ccbb162e0337e141b1/app/assets/javascripts/manage/controllers/take_back/take_back_dialog_controller.coffee

- naming nitpick: `localStorageEnabled` could also be interpreted as "this browser has usable localstorage", which is common pattern. maybe `shouldPersistToLocalStorage`?

**Comment by nadjaweisskopf** [comment]
test on nimaai-server

**Comment by nimaai** [comment]
This feature will not be deployed as discussed with Roger. The lending managers share the workstations.
