### ISSUE TITLE
Send contract statistic

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#634]
#### Expected behaviour
The financial department (S.B.) needs the following statistic: 

- Amount of contracts per department for the years 2015 until today with the amount of items and options per contract

mfa has created the first part of the statistic (without items) with following select: SELECT * FROM contracts INNER JOIN users ON contracts.user_id = users.id;

The financial department say they can work with this format: smb://filer.ad.zhdk.ch/applications/Leihs/02_Anforderungen/Statistiken/Query Results.csv

Please send the statistic as soon as possible to @gurmir. He will send it to S.B. from the financial department.

**Comment by nimaai** [comment]
```sql
  select cs.id as contract_id,
         cs.created_at::date as contract_created_at,
         sum(rs.quantity) as quantity,
         us.firstname || ' ' || us.lastname as user_or_delegation_name,
         dus.firstname || ' ' || dus.lastname as delegated_user_name,
         coalesce(us.extended_info, dus.extended_info) as extended_info
  from contracts as cs
  inner join reservations as rs on cs.id = rs.contract_id
  inner join users as us on us.id = cs.user_id
  left join users as dus on dus.id = rs.delegated_user_id
  where cs.created_at::date >= '2015-01-01'
  group by cs.id, us.firstname, us.lastname, us.extended_info, dus.id
  order by cs.created_at desc;
```
