### ISSUE TITLE
Handscanner with cabel isn't scanning well

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#636]
If the lending Managers wants to scan products with the USB-Handscanner, he sometimes doesn't see the productname (details see on the screenshot).

Steps to reproduce:
1. Go to leihs
2. Go to the Invenotry Pool "Ausleihe Toni-Areal"
3. Insert your name in the search Engine field
4. Go to hand out
5. Scan the products (Example INV10189 "LED-Leuchte 70W Bi-Color")

![fehler](https://user-images.githubusercontent.com/37148448/47083964-8193ee00-d212-11e8-9131-5b96893ae234.png)

**Comment by nimaai** [comment]
`INV10189`

**Comment by nimaai** [comment]
Could not be reproduced with this scanner: https://www.barcodesinc.com/honeywell/part-1300g-2.htm

**Comment by nimaai** [comment]
Besides scanning on itself seems to work, see success message.
