### ISSUE TITLE
 Is there some sample data available to load into the database?

### ISSUE THREAD

**Issue by martinmurciego** [leihs/leihs#637]
If someone has saved or exported a backup with sql inserts to import into the database I would like to know better how this software works with real data.

**Comment by nadjaweisskopf** [comment]
@martinmurciego Which data do you want to import? Items and model? Users?

**Comment by martinmurciego** [comment]
Records in all tables to better understand the operation.

**Comment by nadjaweisskopf** [comment]
@martinmurciego Here you have some sample data: Datahttps://github.com/leihs/leihs_legacy/blob/master/features/personas/demo.pgbin
