### ISSUE TITLE
V5 Tests

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#642]
- [x] Afterlogin with nweissko I am navigated to the My-page. 
From there, if I press "lending" I am navigated to the Admin-page instead of to the lending page. 

<img width="576" alt="bildschirmfoto 2018-11-08 um 12 52 45" src="https://user-images.githubusercontent.com/3356016/48197275-98cb8480-e355-11e8-8725-22d3e7c81735.png">

Trying the link for the fourth time leads me to the correct legacy lending page. 

- [x] Can't we set the token timeout to 3minutes or 10 minutes. Why 90 seconds? => We decided to wait for feedback from users

- [x] Bug: 
1. I log in as Admin
2. I navigate to users page
3. I choose the pool "Ausleihe Toni-Areal" from the menu on the top
4. I get an error 
5. After a refresh the correct page is shown
(same error when navigating to Admin)
<img width="1016" alt="bildschirmfoto 2018-11-08 um 13 15 27" src="https://user-images.githubusercontent.com/3356016/48198210-6cfdce00-e358-11e8-8fa8-21192e68563d.png">

- [x] After logging in to as lending mgr. only, I receive an error: After a refresh the error is gone. Is this the known problem?
<img width="1013" alt="bildschirmfoto 2018-11-08 um 13 40 07" src="https://user-images.githubusercontent.com/3356016/48199267-e814b380-e35b-11e8-8d90-edf70db9ecba.png">

- [x] When clicking on pool "Art Education" in Admin section I get following error: 
<img width="1350" alt="bildschirmfoto 2018-11-08 um 14 05 43" src="https://user-images.githubusercontent.com/3356016/48200479-8f471a00-e35f-11e8-88af-02ef9b363eb8.png">

- [x] After navigating to "meine dokumente" from the admin section I get the know error msg. But then I can't navigate back to the admin section. 
<img width="1016" alt="bildschirmfoto 2018-11-08 um 13 15 27" src="https://user-images.githubusercontent.com/3356016/48200569-d6350f80-e35f-11e8-935d-a4e7a99247b2.png">

- [x] Brower updates user password in legacy when changing the role.

**Comment by gurmir** [comment]
Same ticket like https://github.com/leihs/leihs/issues/643
