### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#644]
- [x] For the next Release V5.1 could you please translate this in German "Welches Produkt wird viel ausgeliehen?" More Information see in the following print screen
<img width="469" alt="bildschirmfoto 2018-11-12 um 11 17 32" src="https://user-images.githubusercontent.com/37148448/48341491-74c9b500-e66d-11e8-9ac1-ca5b81156725.png">

**Comment by nimaai** [comment]
@gurmir 

I have changed the translations like this:

```
Which item is busiest?
Was sind die meistbenutzten Gegenstände?

Which model is busiest?
Was sind die meistbenutzten Modelle?
```
This way it's more consistent with the rest of our business logic and UI.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/de1d29ba6bdef4e6d29a58c1dc253e149559bf9e

**Comment by gurmir** [comment]
@nimaai That is good for me.
