### ISSUE TITLE
Check bug

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#648]
<img width="897" alt="bildschirmfoto 2018-11-14 um 19 29 12" src="https://user-images.githubusercontent.com/3356016/48503858-a3998400-e843-11e8-87f4-670aad8bbaf9.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/a90aa60d0e862d73b58629e2d785713202df7dfd
