### ISSUE TITLE
Users are not blocked over night

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#651]
Some Users, who must be blocked in Inventory Pool 'Ausleihe Toni-Areal'  aren't blocked automatically in leihs. More Information see in the Print Screen

![not_blocked_user](https://user-images.githubusercontent.com/37148448/48549278-9e821680-e8cf-11e8-802a-332c4041c102.png)

**Comment by eins78** [comment]
Now all the users that should be blocked at. It seems fixing the mail delivery solved it. Reopen if still an issue.

**Comment by nadjaweisskopf** [comment]
@nimaai Roger suspended all users manually. So the problem is most probably not fixed yet. I need to inform him by tonight, if the problem is not solved. The inventory mgrs need to be informed then, if they have to suspend manually tomorrow again.

**Comment by nimaai** [comment]
@nadjaweisskopf We have fixed the cron job which **reminds and suspends** all late users. This happens still at 3:00 am. He must have suspended them manually before we fixed and re-executed the cron job earlier today.

**Comment by gurmir** [comment]
@nimaai Thats correct. He has suspended the User manually during I have written this Ticket. We will inform the inventory mgrs. that tomorrow it should block automatically the Users who's not given back the borrowed Items
