### ISSUE TITLE
leihs-zhdk-agw-auth finalizing

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#652]
- AGW config 
    - clean up old AGW apps
    - new AGW correct config: URL-Regexes, URL-Examples, Adjust Titel etc

- publish repo, deployment/configuration
    - set correct base url

- make sure log in still works and uses/redirects to correct hostnames

**Comment by nadjaweisskopf** [comment]
New AGW-instance for testing environment
Note: the current testing AGW-instance is used in prod!

**Comment by DrTom** [comment]
Could not reproduce mentioned problems. 
AGW for test and staging done. 
closing

**Comment by nadjaweisskopf** [comment]
test login on staging and test
