### ISSUE TITLE
Scaning the Camp. Card given wrong Badge ID

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#653]
Roger has inform me that when the Lending mgrs. scan the BadgeID from Students in leihs the BadgeID can't reading correct, When he scan the Bacht (only Student Badges) the Badge, put a wrong No. out. 
BadgeID correct. 155xxxxx. But the Users has new a cutted No. like 15-500-000. 

IMPORTANT: Only Student Badges. 

Steps to reproduce:
- Go to Inventory Pool
- Look for Customer / Scan the Badge
- User can't be found.

**Comment by eins78** [comment]
fixed in https://github.com/leihs/zhdk-sync/commit/1a435faf829d1dd1cdff242cf1444e4caa42ae46
