### ISSUE TITLE
Change Gateway for FFZH

### ISSUE THREAD

**Issue by gurmir** [leihs/leihs#655]
If FFZH opens there leihs instance they get an error message from leihs gateway. I asked Roman for more information for the routed IP-Adress.
The IP Adress shows to our leihs gateway. 
Could you change the route for ffzh.leihs.zhdk.ch to leihs.ffzh.ch?

**Comment by nimaai** [comment]
Just to remember: we have to change this also: https://github.com/leihs/leihs_zhdk-inventory/blob/master/settings/ffzh-leihs-prod.yml

**Comment by DrTom** [comment]
Ticket bitte an mich assignen.

**Comment by DrTom** [comment]
Everything done.
