### ISSUE TITLE
Login for at least two users not possible

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#656]
When cweckema and karpf log in, they either get an error page or the login icon of the AGW is downloaded instead of logging in the user. 

1. leihs.zhdk.ch / ausleihe.zhdk.ch (doesn't matter which one)
2. type in username or email
3. login in to AGW --> icon is downloaded or error page "not found" is shown
4. log in with pw --> icon is downloaded

Error in file: 

ERROR: function crypt(integer, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 515

[Archiv.zip](https://github.com/leihs/leihs/files/2598848/Archiv.zip)

**Comment by eins78** [comment]
- redirection problem fixed in 
https://github.com/leihs/leihs/commit/e744e9fabcf281237d32a38f75a38c0a80a7bc8c

- `function crypt(integer, text) does not exist` problem solved but not delivered yet @DrTom
