### ISSUE TITLE
Feature request: Custom property defined in model, but value entered in individual item

### ISSUE THREAD

**Issue by DerBachmannRocker** [leihs/leihs#66]
Scenario: I have 20 VGA cables with 20 differing lengths. As it is now I have no "official" simple way of keeping track of the cable length.

How I would handle the problem at the moment
-create 20 different models with different values for the custom property "length" -> lots of work for minimal gain
-create 1 item of each model
OR (the sane option)
-create 1 model "VGA cable" and enter the info in the "notes" field -> bad, as it is inconsistent and probably not nice for SQL queries, etc.

Solution
Ideal would be the possibility to create custom properties on the model level (key), as we are able to do now already. But additionally include the option to define the value on the individual item level. 

Example in my scenario with the added feature:
-create 1 model "vga cable" with a custom property named "length". Do not define a value for length, instead leave the inputbox for "value" empty and save the model.
-create 20 items "VGA cable", showing all user-defined custom property input boxes for this model. Entering the value for the property "length" there is mandatory for creating the new item.

This could be very flexible and useful for many scenarios, not just cable length!

**Comment by DerBachmannRocker** [comment]
I would vote to close the issue for now. In practice, the problem is not as huge as I thought it would be. I worked around the issue by creating a model for each of the truly relevant lengths of cable. And one additional "miscellaneous lengths" model as catch-all solution for cables where the length does not matter.

**Comment by nadjaweisskopf** [comment]
Will close this ticket for now.
