### ISSUE TITLE
optimise deployment

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#665]
so that deployment doesn't take so long. 

mfa tasks:

1. [x] built-in, fixed ansible version
2. [x] debug issue: [demo deploy from CI fails with syntax error(!?!)](https://ci.zhdk.ch/cider-ci/ui/workspace/trials/e41bfab7-a8cc-4254-94f4-41f782872084/scripts/deploy)

**Comment by eins78** [comment]
- added caching of build artefacts to deploy (best case deploy now 3min instead of >20) https://github.com/leihs/leihs/commit/22b39c85ff16410de462688d4805d27b806e926e
- added built-in ansible https://github.com/leihs/leihs_deploy/commit/3211eeb4eb376bdf3fb70891635cbb6014d26900
