### ISSUE TITLE
Using LDAP for leihs login

### ISSUE THREAD

**Issue by cmtsch** [leihs/leihs#666]
I am interested in doing the authentication for the login into the leihs system using the ldap server of my organization. 
Could you give me some advice on how to best tackle this modification? Specifically I am interested in knowing which files/modules need to be modified.

**Comment by DrTom** [comment]
As of leihs 5.0 there is an API approach to attach any desired authentication system via an "external Authentication-System". It requires an admin configuration in leihs and a service.  General availability and documentation is scheduled for 5.1.  We use it already in production, you can look at our service implementation here as an example: 

* https://github.com/leihs/leihs-zhdk-agw-auth-system/blob/master/zhdk-agw-auth-system.rb
* https://github.com/leihs/leihs-zhdk-agw-auth-system

Also related: 

* https://github.com/leihs/leihs/issues/600

As mentioned documentation and more examples are coming.

**Comment by lkiesow** [comment]
If anyone is still interested, we have created an LDAP based authentication system for Leihs which works with the current 6.x release and also takes care of adding new users when they first log in. If anyone is interested, the project can be found at:

- [elan-ev/leihs-ldap-authenticator](https://github.com/elan-ev/leihs-ldap-authenticator)

**Comment by nadjaweisskopf** [comment]
Thanks a lot for your contribution! This is very much appreciated. I will place the link in our documentation. Could we put your University on the list of Universitities working with Leihs? https://github.com/leihs/leihs/wiki

**Comment by lkiesow** [comment]
Since I'm not technically working for Osnabrück University, and they are still testing Leihs, I'm not sure. But I will ask and let you know (or let them comment here)

**Comment by lkiesow** [comment]
I got the feedback (translated):

> Maybe we can wait 1 or 2 weeks until it's properly up and running.

@nadjaweisskopf, I can ping you in 2 weeks if you want me to.

**Comment by nadjaweisskopf** [comment]
@lkiesow yes sure, thanks

**Comment by nadjaweisskopf** [comment]
@DrTom Could you please enhance the WIKI with the LDAP-adjustment? Thanks

**Comment by lkiesow** [comment]
> Thanks a lot for your contribution! This is very much appreciated. I will place the link in our documentation. Could we put your University on the list of Universitities working with Leihs? https://github.com/leihs/leihs/wiki

@nadjaweisskopf, since I now work for Osnabrück University, I can now decide that we have no problem if you add us to the list of users.

The LDAP authenticator works great for us. The [repository](https://github.com/elan-ev/leihs-ldap-authenticator)  should contain all necessary information.

For documentation, it would be nice if you could also add the additional documentation linked in #1454
