### ISSUE TITLE
Changing the text "Kommentar des Prüfers" deletes the approved amount 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#669]
#### Expected behaviour
When changing or adding a text of an existing request, the amounts should not be changed. 

#### Actual behaviour
If I change the text "Kommentar des Prüfers", the approved amount is deleted after saving. 

#### Steps to reproduce
1. edit an existing request
2. set the amount requested to 1
3. set the amount approved to 0
4. set the amount ordered to 5
5. save the request - the state is set to rejected (which is correct)
6. edit the request again
8. save the request
9. the approved amount is deleted and therefor the request set to the status "new"
10. The approved amount should not be deleted when editing and saving the request

<img width="575" alt="bildschirmfoto 2018-12-05 um 14 41 44" src="https://user-images.githubusercontent.com/3356016/49517911-9f3e1500-f89d-11e8-8fd6-b88483dc6d2b.png">

<img width="569" alt="bildschirmfoto 2018-12-05 um 14 42 10" src="https://user-images.githubusercontent.com/3356016/49517947-b0872180-f89d-11e8-940d-e909109f12a6.png">

#### Specifications
- Leihs version: 5.0
- Browser version: safari

**Comment by nadjaweisskopf** [comment]
@nimaai I adjusted the steps to reproduce, please check again.

**Comment by nimaai** [comment]
Could be reproduced now, for different users (roles) and different browsers.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/453bce206b9e07bc18926e7d93a4042730444905

**Comment by nadjaweisskopf** [comment]
Can not create a request. 

<img width="1161" alt="bildschirmfoto 2019-02-05 um 15 50 54" src="https://user-images.githubusercontent.com/3356016/52281181-dc865800-295d-11e9-9888-794bd73cec53.png">
