### ISSUE TITLE
Check to see which user approved an order

### ISSUE THREAD

**Issue by mforbes620** [leihs/leihs#673]
Hi Everyone:

Is there currently a way to check to see which user approved a particular order? For example, if I want to find out which Manager approved order XX, is there a way to check in the database for who actually issued the approval?

**Comment by nimaai** [comment]
Email an Nadja am 13.12.2018:

Nein, eine Reservation, die zwar schon Teil von der jeweiligen Bestellung sein kann, aber nur anhand des Modellnamens ist es nicht eindeutig. Und die von Dir markierte UUID ist die von Besteller und nicht dem Genehmiger. 

Eindeutig wäre es, wenn man die UUID der Bestellung hätte und danach in den Audits suchen könnte. Die andere benutzerfreundliche Möglichkeit wäre nach dem Zweck der Bestellung und dem Erstelldatum zu suchen.

So oder so, Bestellungen sollten ge-audited werden. Ich setze es mal um, ist nur ein "one-liner".

**Comment by nimaai** [comment]
@mforbes620 If you know roughly on which day the order was approved, you could set the date filters in the audits respectively and search out the reservations with models which are part of the order. Then see which of them were approved <del>submitted</del>approved and what's the name of the user who did it.
