### ISSUE TITLE
Show amount of options in borrow/return section

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#678]
#### Expected behaviour
In return section in borrow, show the amount of options, which are to be returned. For example: 3 x option XY

#### Actual behaviour
The return page only shows that an option needs to be returned but not the amount. In the pick up page the amount is shown: 3 x option XY

#### Steps to reproduce
1. go to borrow section
2. check the return page
3. amount of options to be returned is not shown

#### Specifications
- Leihs version: 5.0.1
- Browser version: all

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/79912064c8518a9f22b8752dfc9e8005ada8692a
