### ISSUE TITLE
Feature request: Ability for clients to delete/cancel their bookings if not yet approved

### ISSUE THREAD

**Issue by transat** [leihs/leihs#68]
If a booking has not yet been approved, clients should be able to cancel the booking.

I still haven't gotten around to understanding how tests work so can't submit my code but I've got this feature happening with the following:

In controllers/borrow/contracts_controller.rb:

``` ruby
  def remove_submitted
      submitted_contracts.each(&:destroy)
      redirect_to borrow_root_path
  end
```

At the end of views/borrow/contracts/submitted/_merged_lines.html.haml:

``` haml
.line-col.col2of9.text-align-right
    = link_to borrow_order_remove_submitted_path, method: :delete, data: { confirm: _("The order will be discarded.") }, class: "button small red" do
        %i.icon-trash
        = _("Delete %s") % _("Order")
```

with line 10 changed from `.line-col.col6of9.text-align-left` to .`line-col.col4of9.text-align-left`

and in config/routes.rb, under `delete  "order/remove", to: "contracts#remove`:

``` ruby
delete  "order/remove_submitted", to: "contracts#remove_submitted"
```

Missing is an automatic email from leihs advising the managers that the order was cancelled and perhaps a quick check to stop a manager from accidentally approving an already cancelled booking.

**Comment by nadjaweisskopf** [comment]
@transat We are currently specifying this requirement.

**Comment by nadjaweisskopf** [comment]
@transat We are currently specifying this requirement.
