### ISSUE TITLE
Show correct version nr. on login page and link to /release

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#680]

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/66bb8923eda4762f35fa9cda6c411ef389a84c63

**Comment by nimaai** [comment]
The login page was not showing the latest release version, because the `my` service was not being stopped/restarted properly in deploy. Fixed in: https://github.com/leihs/leihs_deploy/commit/02174e53b054981e5a0298cd28acd244adfb8ab5
