### ISSUE TITLE
Deployment settings for default language and active / inactive languages

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#688]
Set default language and active languages in deployment recipe.

**Comment by nimaai** [comment]
wiki
- when adding a lang, add to initializer and DB
- in rails underscores are used as separators

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/0d9712fa1b006604b61603cc5e09415a91acfee0

**Comment by nimaai** [comment]
Updated wiki:

1. https://github.com/leihs/leihs/wiki/Developer-Guide#translating-to-a-new-language
2. https://github.com/leihs/leihs/wiki/Languages
