### ISSUE TITLE
New Mail-Service

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#694]
- [x] Service
- [x] DB
- [x] SMTP-Settings
- [x] Mock an SMTP Server for testing
- [ ] PRTG monitoring (later)
- [x] envelope/from headed settings (goal: 1 whitelisted sender email)
- [x] Retry mechanism
- [x] Deploy
- [x] load SMTP settings dynamically when sending an email

Don't touch legacy

**Comment by nimaai** [comment]
```
leihs_prod=# \d emails
                                Table "public.emails"
   Column   |            Type             | Collation | Nullable |      Default
------------+-----------------------------+-----------+----------+--------------------
 id         | uuid                        |           | not null | uuid_generate_v4()
 user_id    | uuid                        |           | not null |
 subject    | text                        |           | not null |
 body       | text                        |           | not null |
 from       | text                        |           | not null |
 trials     | integer                     |           | not null | 0
 code       | integer                     |           |          |
 error      | text                        |           |          |
 message    | text                        |           |          |
 created_at | timestamp without time zone |           | not null |
 updated_at | timestamp without time zone |           | not null |
Indexes:
    "emails_pkey" PRIMARY KEY, btree (id)
Check constraints:
    "check_code" CHECK (trials = 0 AND code IS NULL OR trials <> 0 AND code IS NOT NULL)
    "check_error" CHECK (trials = 0 AND error IS NULL OR trials <> 0 AND code IS NOT NULL)
    "check_message" CHECK (trials = 0 AND message IS NULL OR trials <> 0 AND code IS NOT NULL)

```

@DrTom This is what I suggest as the table structure and algorithm:

1. Given there are rows in the table
2. At the time of next run (for example every 5 minutes):
    1. Select rows to process. Conditions: `(trials = 0) OR (code > 0 AND trials < 2)` (not tried yet or unsuccessful with retries' limit not reached yet)
   2. For those where `trials = 0`: try to send an email; set `trials = 1` and update `code`, `error`, `message` with the response from the SMTP server
   3. For those where `code > 0 AND trials < 2`: try to send again if `now() - updated_at > 30 mins`; increase `trials` by `1` and update `code`, `error`, `message` with the response from the SMTP server
   4. Go to 2.

OK?

**Comment by DrTom** [comment]
I mostly agree.  Do we send mass mails? Then maybe a join table to the user would make sense (trials, erros etc would be in that table). 
The error field could possibly be a (json-)array with a seq of errors because of retries
.

**Comment by nimaai** [comment]
No mass emails.

**Comment by eins78** [comment]
library support `Sender/From`-Headers as wanted: https://github.com/drewr/postal/blob/8a400fd16fa899d1270c47ae0b65a3230a6cb9ab/test/postal/test/message.clj#L299-L314

**Comment by nimaai** [comment]
As discussed with @eins78, suggestion of following implementation improvement:

- Each retry delay should be the double of the previous one. Example: 1st trial after 1 minute -> failed. 2nd trial (1st retry) after 2 minutes -> failed, 3rd trial after 4 minutes -> failed, etc.

Maybe one should make the 1 retry delay configurable.

**Comment by nimaai** [comment]
smtp domain: https://github.com/leihs/leihs-mail/commit/e59c8246d0c634239f4955d48436d1d4a3e8d283

**Comment by eins78** [comment]
tls-related settings:

```
smtp_enable_starttls_auto: true
smtp_openssl_verify_mode: 'peer'
```

rails docs: https://api.rubyonrails.org/classes/ActionMailer/Base.html

- [ ] db constraint: value must be ('none' or 'peer') for `smtp_openssl_verify_mode`
- [ ] new mail service should support those settings (should be simply passed through to mail sender)
  - use STARTTLS if `smtp_enable_starttls_auto` is true
  - verify TLS certificate of SMTP server if `smtp_openssl_verify_mode: peer`

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/cd4544bcacfeb77f0cc41d2590f32dcfb54c39ad
