### ISSUE TITLE
LDAP login for non admin user

### ISSUE THREAD

**Issue by patlicht** [leihs/leihs#695]
#### Expected behaviour
Login with LDAP user is possible if user is NOT in ldap admin group AND user has never logged into Leihs before.

#### Actual behaviour
I'm trying to login to Leihs using the URL https://myhost/authenticator/ldap/login. This only works if the user is in the admin group (configured in /leihs/legacy/config/LDAP.yml as "admin_dn") OR has logged into Leihs before.
After one successful login, I can remove the user from the admin group and the login still works.

I did a tcpdump during my login attempts and the communication does exactly what I would expect:

I'm using user "usrl1020" and password "(my secret password)".

** Searching user "usrl1020"
protocolOp: searchRequest (3)
  searchRequest
    baseObject: OU=AUM,DC=zhaw,DC=ch
    scope: wholeSubtree (2)
    derefAliases: neverDerefAliases (0)
    sizeLimit: 0
    timeLimit: 0
    typesOnly: False
    Filter: (samaccountname=usrl1020)
    attributes: 0 items

-> Returns dn of user
searchResEntry(2) "CN=usrl1020,OU=Kurs,OU=_L,OU=Edu,OU=AUM,DC=zhaw,DC=ch"  | searchResDone(2) success  [1 result]

** Check users password
bindRequest
  version: 3
  name: CN=usrl1020,OU=Kurs,OU=_L,OU=Edu,OU=AUM,DC=zhaw,DC=ch
  authentication: simple (0)
    simple: (my secret password)
                    
-> Bind successful
bindResponse(1) success 

** Checking if user is in Admin group
protocolOp: searchRequest (3)
  searchRequest
    baseObject: CN=ICT-gs-UserAccess,OU=Permissions,OU=ICT_Leihs,OU=Application,DC=zhaw,DC=ch
    scope: wholeSubtree (2)
    derefAliases: neverDerefAliases (0)
    sizeLimit: 0
    timeLimit: 0
    typesOnly: False
    Filter: (member=CN=usrl1020,OU=Kurs,OU=_L,OU=Edu,OU=AUM,DC=zhaw,DC=ch)
    attributes: 0 items
        
-> Option 1: User is NOT in Admin group
LDAPMessage searchResDone(2) success [0 results]
  messageID: 2
    protocolOp: searchResDone (5)
      searchResDone
      
-> Option 2: User is in Admin group
LDAPMessage searchResEntry(2) "CN=ICT-gs-UserAccess,OU=Permissions,OU=ICT_Leihs,OU=Application,DC=zhaw,DC=ch" [1 result]
  protocolOp: searchResEntry (4)
    searchResEntry
      objectName: CN=ICT-gs-UserAccess,OU=Permissions,OU=ICT_Leihs,OU=Application,DC=zhaw,DC=ch
      attributes: 17 items

#### Steps to reproduce
see above

#### Specifications
- Leihs version: 4.19.5
- Browser version: Firefox
- MySQL/PostreSQL version: postgresql-9.6 (9.6.11-1.pgdg18.04+1)

What did I miss?

Best,
Patric

**Comment by DrTom** [comment]
There might be a problem in https://github.com/leihs/leihs_legacy/blob/4252d3ec3a805f34efc9c9b7d484a7ef9c47df92/app/controllers/authenticator/ldap_authentication_controller.rb 
possibly from line 137 on.

Is there something in the rails logfile?

**Comment by patlicht** [comment]
Thanks a lot for your investigation.
I currently do not see any log file in the /leihs. How can I enable it?

Best,
Patric

**Comment by DrTom** [comment]
`journalctl -u leihs-legacy.service`

**Comment by patlicht** [comment]
I tried with a user that is not yet in the database, but I do not see any logs (besides a warning):

Feb 18 08:11:12 svma-s-01149 ruby[51832]: /home/leihs-legacy/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cider_ci-open_session-2.0.1/lib/cider_ci/open_session/encryptor.rb:34: warning: constant OpenSSL::Cipher::Cipher is deprecated

Just to make sure that logging works, I used the same account with a wrong password. This time I see the expected log line:
Feb 18 08:09:19 svma-s-01149 ruby[51832]: ERROR: Can't bind to LDAP server ldap.zhaw.ch as user 'CN=user,OU=zz,OU=xy,DC=zhaw,DC=ch'. Wrong bind credentials or encryption parameters?

**Comment by patlicht** [comment]
Any suggestions on this?

**Comment by DrTom** [comment]
So, authentication fails without rising an error. Unfortunately we can not help here in this way. Someone needs to hack life into your leihs instance and debug what is going on.
