### ISSUE TITLE
Delete login-field when user is deactivated

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#704]
- Vor 2 Wochen wurde eine ganze Klasse (DKV PP) aus Versehen deaktiviert
- Der Sync hat entsprechend die Accounts deaktiviert
- Nun ist die Klasse wieder aktiviert
- Der Sync geht nun nicht mehr, weil das `login` Feld schon vorhanden ist. 

Code: https://github.com/leihs/zhdk-sync/blob/1a435faf829d1dd1cdff242cf1444e4caa42ae46/src/all/leihs/zhdk_sync/users/remove.clj#L55

2 bessere Varianten für deaktivieren:
- wenn der Sync auch das `login`-Feld entfernen würde, dann würde es keinen Fehler geben aber duplizierte Accounts
- wenn Email oder org_id (?) bleiben würden, dann könnte der Sync später diese Accounts zuordnen (ähnlich wie wenn ein Student geht und dann später wiederkommt, mit gleicher Mail wie vorher)

**Comment by DrTom** [comment]
https://github.com/leihs/zhdk-sync/commit/e8bd9c8fa81a62c97f4b4675a1e561e2e52182c1
