### ISSUE TITLE
max. lending time

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#708]
Requirement from SaaS-customer: 
The lending team wants to be able to set a max lending time for orders. They fear that the organisational process to decline orders with a too long time span is too time consuming.

Proposal from SaaS-customer - easyer solution: 
The max lending time can be set per instance. The leihs Admin can set the max. lending time in days.

Example: 
- The max. lending time is set for the whole leihs instance to 14 days
- The student opens the calender of the model XY
- The model XY shows availability from 1. March - 21. March
- **solution 1:** As soon as the student chooses the start date 1. March and end date later than 15. March then the the end date selected is red and the student see's a msg. saying "You can not lend items longer than 14 days"
- **solution 2:** student picks start and end date and when he presses the button "Hinzufügen" then he gets a msg. saying "You can not lend items longer than 14 days".
- **solution 3:** student adds all items to the cart and when submitting the cart he gets a msg. saying "You can not lend items longer than 14 days, please adjust the time span by opening the calender on the line in question"

It would be nicer if the max. lending time could be set by each pool but then we need to find solutions for mixed baskets. So I would try to find solutions for max. lending time per leihs instance. 

@nimaai Could you please have a look at this requirement with the dev. team and inform Franziska about your decision.

**Comment by nimaai** [comment]
We will implement the backend accordingly, which will cover solution 2 & 3.

**Comment by nimaai** [comment]
TODO:

- [ ] DB migration: `settings.max_borrow_time`
- [ ] Validation in controller when creating / changing reservation in borrow
- [ ] Validation in controller when submitting an order in borrow
- [ ] Error message translation
- [ ] Form extension in Admin -> Settings
- [ ] Information Message in Borrow -> Inventory Pools
- [ ] Tests

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/81e0d19558e0bc4404ccf2849101166268080f96
