### ISSUE TITLE
Unclear button function in daily view

### ISSUE THREAD

**Issue by transat** [leihs/leihs#71]
In the daily view, the "Take Back" and "Hand Over" buttons should really be "Take Back / Edit" and "Hand Over / Edit" buttons to make it clearer to new managers what they do.

**Comment by psy-q** [comment]
[Added it to ZHdK's Pivotal Tracker](https://www.pivotaltracker.com/story/show/110957062). Please note that this does not mean this will get done any time soon. If anyone wants to work on this, just comment in here and I will remove it from ZHdK's tracker again.
