### ISSUE TITLE
Sort the items alphabetically

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#710]
Reported by "ZHdK Werkstatt"

#### Expected behaviour
I would want to see the items listed alphabtically in the hand over when adding an item manually. 

#### Actual behaviour
The items (normal items and package items) are not listed alphabetically. 

#### Steps to reproduce
1. go to lending section
2. open a hand over
3. click inside the "add item" field
4. if several items are found, they are not listed alphabetically

#### Specifications
- Leihs version: 5.0.2, production
- Browser version: safari

<img width="709" alt="bildschirmfoto 2019-03-04 um 15 15 15" src="https://user-images.githubusercontent.com/3356016/53738755-5a238200-3e90-11e9-8854-1dbf26dea782.png">

![bildschirmfoto 2019-02-26 um 08 22 09](https://user-images.githubusercontent.com/3356016/53738844-9f47b400-3e90-11e9-8773-6a686dadcd87.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6563819cdcb0e7f5ff8fea2b74740746002310e5

**Comment by nimaai** [comment]
The implementation was reverted: https://github.com/leihs/leihs/commit/6f5d102f0f1a9d7d77d986fc904d8a918aaca906

It should be guaranteed that the same sorting is used on hand over page, in contract, etc. (feedback from Roger).

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9acf22605452ffd56e8109a9c7ca2cad483ab601
