### ISSUE TITLE
current working directory is untracked

### ISSUE THREAD

**Issue by hongfeizhou** [leihs/leihs#717]
fatal: [www.leihs.com -> localhost]: FAILED! => {"changed": true, "cmd": "#/bin/bash\n set -eux\n DEPLOY_DIR='/home/../workspace/my-new-leihs/leihs/deploy'\n cd $DEPLOY_DIR/../database\n $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/database.tar.gz", "delta": "0:00:00.107135", "end": "2019-03-20 10:45:43.637987", "msg": "non-zero return code", "rc": 128, "start": "2019-03-20 10:45:43.530852", "stderr": "+ DEPLOY_DIR=/home/../workspace/my-new-leihs/leihs/deploy\n+ cd /home/../workspace/my-new-leihs/leihs/deploy/../database\n+ /home/../workspace/my-new-leihs/leihs/deploy/bin/git-archive-all -v /home/../workspace/my-new-leihs/leihs/deploy/tmp/database.tar.gz\nfatal: current working directory is untracked", "stderr_lines": ["+ DEPLOY_DIR=/home/../workspace/my-new-leihs/leihs/deploy", "+ cd /home/../workspace/my-new-leihs/leihs/deploy/../database", "+ /home/../workspace/my-new-leihs/leihs/deploy/bin/git-archive-all -v /home/../workspace/my-new-leihs/leihs/deploy/tmp/database.tar.gz", "fatal: current working directory is untracked"], "stdout": "creating superproject archive...", "stdout_lines": ["creating superproject archive..."]}

**Comment by eins78** [comment]
There is not information given to help you out. Please try following the guide in the following repo, and if you still get this problem open a more detailed issue there: https://github.com/leihs/leihs-instance/blob/master/GUIDE.md
