### ISSUE TITLE
Lending Manager Mails

### ISSUE THREAD

**Issue by bseidenspinner** [leihs/leihs#719]
#### Expected behaviour

The customer makes a reservation/booking, the lending manager gets a mail with the information about the new reservation.

#### Actual behaviour

All other mails and reminders to the customer working fine, but messages to the lending manager are still missing. The template ist defined.  

#### Related issues 
https://github.com/leihs/leihs/issues/291

#### Specifications
- Leihs version: 4.11
- Browser version: Firefox 66.0.1
- MySQL/PostreSQL version: 9.6

**Comment by nimaai** [comment]
This can be activated for all inventory pools via `deliver_received_order_notifications` under `/admin/settings`. Sorry for the delayed answer.
