### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by transat** [leihs/leihs#72]
Probably very low priority but it would be great if Leihs could include drop-in themes!

I've relooked our version of Leihs but can't submit what I've done due to my lack of understanding of tests. If you wish, I'm happy to share with you by some other means though. I've got all the custom SASS in its own folder, over-riding the default stylesheets. I did have to change the haml in some pages due to some colours being stated in the haml e.g. "button.green" and "button.red" when it might be best to have used "button.action" and "button.cancel" )

Here are some example:

Log in screen:
![screen shot 2014-10-15 at 10 32 22 am](https://cloud.githubusercontent.com/assets/652507/4638548/2bab0746-53fc-11e4-910e-9e44e76a2df9.png)

Main admin view:

![screen shot 2014-10-15 at 10 33 14 am](https://cloud.githubusercontent.com/assets/652507/4638554/3db40f28-53fc-11e4-8529-b0c3c7b7aa7b.png)

Daily view:

![screen shot 2014-10-15 at 10 37 44 am](https://cloud.githubusercontent.com/assets/652507/4638559/4958848a-53fc-11e4-9be5-265a5407e5eb.png)

Inventory:

![screen shot 2014-10-15 at 10 34 27 am](https://cloud.githubusercontent.com/assets/652507/4638563/5a4fa4a8-53fc-11e4-9287-2a109d9920a3.png)

Inventory Pool Settings:

![screen shot 2014-10-15 at 11 10 12 am](https://cloud.githubusercontent.com/assets/652507/4638764/cd0b9c74-53ff-11e4-8a36-448c27ed42be.png)

Borrow section:

![screen shot 2014-10-15 at 10 37 06 am](https://cloud.githubusercontent.com/assets/652507/4638565/5fa05a24-53fc-11e4-9654-bb3196f6ec04.png)

Open Orders:

![screen shot 2014-10-15 at 10 37 17 am](https://cloud.githubusercontent.com/assets/652507/4638568/6b797d26-53fc-11e4-9aa4-cc28275d4a8c.png)

Daily view calendar and tooltip:

![screen shot 2014-10-15 at 10 42 02 am](https://cloud.githubusercontent.com/assets/652507/4638573/79b6e6e4-53fc-11e4-9618-3c17f094406d.png)

**Comment by psy-q** [comment]
Is your theme still active? Currently we're dicussing moving to Bootstrap, which would require rebuilding lots of our templates but might make it easier for you to supply a theme. Do you think your theme could be implemented as a Bootstrap theme?
