### ISSUE TITLE
Deploy failed at TASK [leihs-my-install : create jar] due to leihs/core/core__init.class or leihs/core/core.clj not found.

### ISSUE THREAD

**Issue by tmulzer** [leihs/leihs#720]
#### Expected behaviour

Deploy finishing successfully.

#### Actual behaviour

Deploy stops with an error in [leihs-my-install : create jar].
The error breaks down to:
`'Caused by: java.io.FileNotFoundException: Could not locate leihs/core/core__init.class or leihs/core/core.clj on classpath.'`

Stack-Trace is:
```
stderr: |-
    + DEPLOY_DIR=/home/[...]/my-leihs/leihs/deploy
    + source /home/[...]/my-leihs/leihs/deploy/bin/.caching-helpers.sh
    ++ export CACHE_DIR=/tmp/leihs_build_cache
    ++ CACHE_DIR=/tmp/leihs_build_cache
    + cd /home/[...]/my-leihs/leihs/deploy/../my
    + /home/[...]/my-leihs/leihs/deploy/bin/lein uberjar
    Compiling leihs.my.back.main
```

There are some files `core__init.class` and `core.clj` .. but none with prefix `[...]\leihs\core\` in the filesystem.

#### Steps to reproduce

Deploy v4.11.0 from github - works with some minor (solvable) issues.
```
git checkout 5.0.3
git submodules update --init
./scripts/deploy
```

#### Specifications
- Leihs version: 5.0.3 or master
- System version: debian stretch (on both sides), openjdk-8-jdk.

**Comment by DrTom** [comment]
Most likely the clj core submodule was not checked out or not updated.
