### ISSUE TITLE
global search finds unrelated items

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#721]
```gherkin
When I search for "Sandsack 12 Kg" in the global search
  And I click on "Gegenstände"
Then I see results for "Sandsack 6 Kg"
```

Expectation: I want to only see "Sandsack 12 Kg" results

**Comment by nimaai** [comment]
It searches in various fields, not only in model name. In this case also in inventory code and there is a 12. @eins78 I guess we leave it as is.

**Comment by eins78** [comment]
ok. we have very similar issues in all the places where we can search (also users), some day we should think about how to handle that in general.
