### ISSUE TITLE
Feature: Reset Password

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#723]
includes: https://github.com/leihs/leihs/issues/694

- [x] DB: table `user_password_resets` with user_id, used_user_param, token, valid_until, created_at. 
  - constraint: only 1 per user. 
  - trigger: remove expired tokens
  

- UI: forms
  - [x] forgot: enter userParam, get "OK" or Error
  - [x] reset: enter token + new password, get "OK" or Error
  - [x] password reset successful

- [x] Backend
  - GET `/forgot-password`
  - POST `/forgot-password`
  - GET `/reset-password`
  - POST `/reset-password`

- [x] scenarios
    - [x] token valid only once! (can be unit test)

Misc. things to think about:
- [x] we need to use `settings.external_base_url`
- [x] we need a setting for "default email sender adress for 'system' emails". Default: `noreply@${LEIHS_EXTERNAL_BASE_URL}`
- [x] send an email to confirm when password was changed
- [ ] audits! (later)
- [x] the reset form should show the same `userParam` (email or login name) as in the initial form, 
  for clarity and integration with password managers.  
- [x] `user.password_email_reset_enabled` (default true) -> nope
- [x] trigger should delete old/expired tokens (on insert is enough)
---

material:

![9553642F-141B-4913-8381-F323FA12D21D](https://user-images.githubusercontent.com/134942/56740470-4bab6580-6771-11e9-8c50-34f7ae60efd1.jpeg)

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Forgot_Password_Cheat_Sheet.md

https://postmarkapp.com/guides/password-reset-email-best-practices

**Comment by eins78** [comment]
draft unit tests for my backend/my:

```
- POST forgot
  - with valid user -> OK (check http, table)
  - with valid email -> OK (check http, table)
  - with invalid user -> NOK (check http, table)
  - with invalid email -> NOK (check http, table)

- POST reset
  - with valid token -> OK (check http, table/auth new pw works)
    - check that 'userParam' is ignored (we can send whatever, but only `user_id` from table is used) 
  - with unknown token -> NOK (check http, table)
  - with expired token -> NOK (check http msg, table)
```

**Comment by eins78** [comment]
simple mail body

```
To do Password reset click this link:
"#{settings.external_base_url}/reset-password?token=#{token}"

Or type the token: #{token}
```

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/cd4544bcacfeb77f0cc41d2590f32dcfb54c39ad
