### ISSUE TITLE
Upgrade FFZH from 4.19.5 to 5.1.0

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#743]
Kontakt aufnehmen und Update planen.
Voraussetzungen:
- Vor dem Install VM-Snapshot machen lassen
- Prod Server upgraden
- Nach dem Update `itzansible` anwenden lassen (linux team)
- Alle User müssen E-Mail gesetzt haben. 
- Das neue Mailing muss auf Instanz funktionieren

**Comment by eins78** [comment]
debian 8 upgrade (jessie to stretch)

```
vim /etc/apt/sources.list
# :%s/jessie/stretch/
rm /etc/apt/sources.list.d/http_debian_net_debian.list

apt-get clean
apt update
apt upgrade       # For regular/minor upgrades
apt dist-upgrade  # For major release upgrades only
apt autoremove --purge 
/sbin/shutdown -r now  
```

**Comment by nimaai** [comment]
Problem Migration 510: `UPDATE users SET email = nullif(trim(email),'');`
wegen: `select * from users where email ilike '%info@ohnetitel.ch%';` => 2 rows

**Comment by nimaai** [comment]
Problem und Fix Migration 501: https://github.com/leihs/leihs_database/commit/479bd2766c9580eb60879da0e1c98646659de4b2
