### ISSUE TITLE
error: Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by avabraxas** [leihs/leihs#745]
#### Expected behaviour
when I update the git submodule i get a server error message.

#### Actual behaviour

# sh -c 'git submodule update --init leihs && cd leihs && git submodule update --init --recursive'
error: Server does not allow request for unadvertised object 7f115ab52880d66ae822239a60a2c7fbfa1ae8f9
Fetched in submodule path 'legacy', but it did not contain 7f115ab52880d66ae822239a60a2c7fbfa1ae8f9. Direct fetching of that commit failed.

#### Steps to reproduce

sh -c 'git submodule update --init leihs && cd leihs && git submodule update --init --recursive'

#### Specifications
- Leihs version: 5.1
- fresh install

**Comment by nimaai** [comment]
@avabraxas Which tag (version) do you exactly try to install? Or what is the commit SHA of `leihs` submodule you are issuing the command for?

**Comment by avabraxas** [comment]
here is the complete log...

root@lnp541:/opt/leihs-test.kapo.zh.ch_hosting# sh -c 'git submodule update --init leihs && cd leihs && git submodule update --init --recursive'
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Total 39 (delta 26), reused 26 (delta 26), pack-reused 12
Unpacking objects: 100% (39/39), done.
From https://github.com/leihs/leihs_legacy
 * [new branch]          mk/stapo   -> origin/mk/stapo
Submodule path 'legacy': checked out '7f115ab52880d66ae822239a60a2c7fbfa1ae8f9'
Submodule 'database' (https://github.com/leihs/leihs_database.git) registered for path 'legacy/database'
Submodule 'node_modules' (https://github.com/leihs/leihs_legacy_node_modules) registered for path 'legacy/node_modules'
Submodule 'public/assets' (https://github.com/leihs/leihs_legacy_assets.git) registered for path 'legacy/public/assets'
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/legacy/database'...
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/legacy/node_modules'...
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/legacy/public/assets'...
Submodule path 'legacy/database': checked out 'd8fe6d97fb74db807e8e6483552d4252e4a42b49'
Submodule path 'legacy/node_modules': checked out 'ebef651ebab717cc0a6c4024978bb5f76fc33ea3'
Submodule path 'legacy/public/assets': checked out 'c1fb75e89ae4b4859cea5f65ef663ee295a1ecec'
Submodule path 'my': checked out '81016eb1d48be5cfb6fd2abb593441a81138d78f'
Submodule 'database' (https://github.com/leihs/leihs_database.git) registered for path 'my/database'
Submodule 'leihs-clj-shared' (https://github.com/leihs/leihs-clj-shared.git) registered for path 'my/leihs-clj-shared'
Submodule 'leihs-ui' (https://github.com/leihs/leihs-ui) registered for path 'my/leihs-ui'
Submodule 'vendor' (https://github.com/leihs/leihs-admin_vendor.git) registered for path 'my/vendor'
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/my/database'...
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/my/leihs-clj-shared'...
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/my/leihs-ui'...
Cloning into '/opt/leihs-test.kapo.zh.ch_hosting/leihs/my/vendor'...
Submodule path 'my/database': checked out 'd8fe6d97fb74db807e8e6483552d4252e4a42b49'
Submodule path 'my/leihs-clj-shared': checked out '30619acce18f6bd02c6ca711ae1c690924b075e0'
Submodule path 'my/leihs-ui': checked out '3895871b2cceb1c4f8e8dcf442ab9004f0579d35'
Submodule path 'my/vendor': checked out '1261a6cfddf9f8ec868c31fe60b50897dbc48c03'
error: Server does not allow request for unadvertised object e1f1e641fe73ff651d5c281aa854e9400c05f693
**Fetched in submodule path 'procure', but it did not contain e1f1e641fe73ff651d5c281aa854e9400c05f693. Direct fetching of that commit failed.
root@lnp541:/opt/leihs-test.kapo.zh.ch_hosting#**

**Comment by nimaai** [comment]
@avabraxas What is the output of `sh -c 'git submodule update --init leihs && cd leihs && git show HEAD` ?

**Comment by avabraxas** [comment]
here the output:

# :/opt/xxxxxxxxxx_hosting# sh -c 'git submodule update --init leihs && cd leihs && git show HEAD'
commit 6cd631be41971cf408d5c4e96b115e833b6f864b (HEAD, tag: 5.0.4)
Author: Matus Kmit <matus.kmit@zhdk.ch>
Date:   Thu Apr 11 11:43:44 2019 +0200

    release: v5.0.4

diff --git a/config/releases.yml b/config/releases.yml
index 126506eba..631dd6b83 100644
--- a/config/releases.yml
+++ b/config/releases.yml
@@ -5,23 +5,14 @@ releases:
 - version_major: 5
   version_minor: 0
   version_patch: 4
-  version_pre: RC.2
+  version_pre: null
   description: |

     **We recommend existing instances to wait for v5.1 to upgrade their system** (First time installations can use V5.0)

     See v5.0.0 for list of breaking changes.

-    - revert: feat: sort by inventory code in assign item
-
-- version_major: 5
-  version_minor: 0
-  version_patch: 4
-  version_pre: RC.1
-  description: |
-
     - feat: legacy: maximum reservation time
-    - feat: manage: sort by inventory code in assign item
     - feat: procure: improve filter UX
     - fix: non-deterministic group allocation in availability
     - fix: legacy: mails and users with no language
#:/opt/xxxxxxxxx_hosting#

**Comment by nimaai** [comment]
@avabraxas I have tagged all submodules with `5.0.4` and pushed the missing commits. Try now your original command.

**Comment by avabraxas** [comment]
thanks now is working. You can close the issue.
Best regards
