### ISSUE TITLE
Can I manually upgrade my database??

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#746]
We have (after a long battle earlier in the year) running 4.19.5 systems.

I have been trying to get 5.x to install and accept our database for a long time with no avail.

Today, I have managed to get 5.0.2 to install as a clean install.  When I try to restore the 4.19.5 database as advised the "migration.service" fails to load.  So there must be an issue with the database(s).

Can I or can someone there? manually upgrade the databases?  

Thanks,

Anthony.

**Comment by nimaai** [comment]
@AnthonyHunt First maybe you could tell us what the error is exactly?

**Comment by AnthonyHunt** [comment]
I can, but it won't be very helpful.  When I run
   ansible-playbook leihs/deploy/db-restore_play.yml -i hosts -e 'database_dump_restore_file_path=$MY_LEIHS_DUMP'

to bring my database back in it fails with:

TASK [start-services : start leihs-admin.service] ********************************************************************************************************************************************
fatal: [10.101.83.248]: FAILED! => {"changed": false, "msg": "Unable to start service leihs-admin.service: A dependency job for leihs-admin.service failed. See 'journalctl -xe' for details.\n"}

PLAY RECAP ***********************************************************************************************************************************************************************************
10.101.83.248              : ok=34   changed=16   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   


Which gives me...


Sep 10 11:32:58 dac-leihs02 sudo[8547]:     root : TTY=pts/1 ; PWD=/root ; USER=leihs-database ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lzyfdlsspslxcrmmrmqhylrscowxouko ; /usr/bin/python /va
Sep 10 11:32:58 dac-leihs02 sudo[8547]: pam_unix(sudo:session): session opened for user leihs-database by root(uid=0)
Sep 10 11:32:58 dac-leihs02 ansible-command[8549]: Invoked with creates=None executable=None _uses_shell=True strip_empty_ends=True _raw_params=set -eux
                                                   export PATH=$HOME/.rubies/ruby-2.6.0/bin:$PATH
                                                   gem install bundler
                                                   cd /leihs/database
                                                   bundle install
                                                    removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Sep 10 11:33:03 dac-leihs02 sudo[8547]: pam_unix(sudo:session): session closed for user leihs-database
root@dac-leihs02 /# journalctl -xe
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:14:in `each'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:14:in `change'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `load'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `<main>'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: Caused by:
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "idx_user_egroup"
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: DETAIL:  Key (user_id, entitlement_group_id)=(96adfbaf-838b-5825-9066-d77de8767cda, 558f8edf-183f-5985-b83c-835e50f04b52) already exists.
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:23:in `block (3 levels) in change'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:22:in `each'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:22:in `block (2 levels) in change'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:21:in `each'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:21:in `block in change'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:14:in `each'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /leihs/database/db/migrate/501_users_clean_up.rb:14:in `change'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `load'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `<main>'
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: Tasks: TOP => db:migrate
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: (See full trace by running task with --trace)
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]:    -> 0.0054s
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: -- execute("UPDATE contracts\n  SET user_id = '96adfbaf-838b-5825-9066-d77de8767cda'\n  WHERE user_id = '1fff5b79-1d21-5481-a83b-296907117
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]:    -> 0.0044s
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: -- execute("UPDATE entitlement_groups_users\n  SET user_id = '96adfbaf-838b-5825-9066-d77de8767cda'\n  WHERE user_id = '1fff5b79-1d21-5481
Sep 10 11:40:02 dac-leihs02 systemd[1]: leihs-admin.service: Job leihs-admin.service/start failed with result 'dependency'.
Sep 10 11:40:02 dac-leihs02 systemd[1]: leihs-migration.service: Unit entered failed state.
Sep 10 11:40:02 dac-leihs02 systemd[1]: leihs-migration.service: Failed with result 'exit-code'.



And also, just to be clear, whilst 5.0.2 is installing from scratch I get this error "Render Error!" when I try to load it in a browser.

**Comment by nimaai** [comment]
This is the problem: 

```
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: Caused by:
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "idx_user_egroup"
Sep 10 11:40:02 dac-leihs02 leihs-migration[16921]: DETAIL: Key (user_id, entitlement_group_id)=(96adfbaf-838b-5825-9066-d77de8767cda, 558f8edf-183f-5985-b83c-835e50f04b52) already exists.
```

Can you check the entitlement group `558f8edf-183f-5985-b83c-835e50f04b52` in the UI and see if there are some duplicate users? The failing migration 501 is namely trying to merge duplicate users (with the same email).

**Comment by AnthonyHunt** [comment]
right... looking into this.  This is my test server and has an old clone of data.  I obviously can't edit my "import" at this stage so will check the "live" database, export and try another import.

**Comment by AnthonyHunt** [comment]
Has dump-and-fetch_play.yml gone?? can't find it? and when I try to create from the code in the repository I get: 

ERROR! the role 'dump-and-fetch-db' was not found in /ises-leihs01/leihs/deploy/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/ises-leihs01/leihs/deploy

The error appears to be in '/ises-leihs01/leihs/deploy/dump-and-fetch_play.yml': line 3, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: dump-and-fetch-db
      ^ here


Can I not do an instant backup now?

**Comment by AnthonyHunt** [comment]
I fear this may all be in vein.

Having gotten a database from a different server to import correctly, I now find that LDAP is no longer supported.  Whilst our site does support Active Directory Connecting to it with an external connector may not be possible.

**Comment by nimaai** [comment]
@AnthonyHunt Have you managed to properly install 4.19.5? If yes and you are willing to send me its dump over a secure channel, then I can try to migrate it for you.
