### ISSUE TITLE
Unable to figure out how to send email from 4.19.5

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#747]
I find it impossible to figure out the email setting is v4.  Some of these have now moved into the database which has made it almost impossible to update.

I have two choices.  I can "bounce" email to another server, but cannot correctly configure LEIHS for this.

I have a gmail account I can connect to but none of the entered details cause email to be sent.

**Comment by nimaai** [comment]
These are the DB settings concerning emails:
```
                   Column                   |           Type           | Collation | Nullable |           Default
--------------------------------------------+--------------------------+-----------+----------+-----------------------------
 smtp_address                               | character varying        |           |          |
 smtp_port                                  | integer                  |           |          |
 smtp_domain                                | character varying        |           |          |
 email_signature                            | character varying        |           |          |
 default_email                              | character varying        |           |          |
 mail_delivery_method                       | character varying        |           |          |
 smtp_username                              | character varying        |           |          |
 smtp_password                              | character varying        |           |          |
 smtp_enable_starttls_auto                  | boolean                  |           | not null | false
 smtp_openssl_verify_mode                   | character varying        |           | not null | 'none'::character varying
 smtp_sender_address                        | text                     |           |          |
 smtp_default_from_address                  | text                     |           | not null | 'noreply@example.com'::text
```

I don't know what you mean with "impossible to update". Before 5.1.0 some of the settings were not editable via UI only through deploy inventory. Since 5.1.0 all the settings are editable in UI (again).

**Comment by AnthonyHunt** [comment]
Everything worked fine on v3.  When updating to V4 we've not been able to get any working.  I've not installed or configure sendmail on the leihs server as it should be sending/bouncing via ruby?

If I try to smtp relay:
smtp_address = myMailServer (which is open for internal relay) FQDM
smtp_port = 25
smtp_domain = blah.com 
default_email = our email address
mail_delivery_method = smtp
smtp_username = empty
smtp_password = empty
smtp_enable_starttls_auto = 0
smtp_openssl_verify_mode = 0
smtp_sender_address = N/A in V4.19.5
smtp_default_from_address = N/A in V4.19.5

I can set up our gmail account too with the correct settings and ports.  Nothing appears to send.  Neither order requests, confirmations or late return emails.

From our v5 issue, could this be related?

**Comment by AnthonyHunt** [comment]
closing as we are moving to v5
