### ISSUE TITLE
Disable access rights and delete badge_id for duplicate users (for old ones)

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#748]
Two tasks:

1. SYNC: When deactivating a user (one with contracts), do the following:
* disable (not delete) all of user's access rights (`access_rights.deleted_at`)
* delete `users.badge_id`

2. Migrate / fix the already existing data in the database accordingly.

**Comment by DrTom** [comment]
1.1 geht zur Zeit noch nicht; die neue Admin API hat kein Zugriff darauf.

**Comment by DrTom** [comment]
1.2 da Fällt mir nur ein alle Badge IDs zu löschen, die keine org ID haben (dalso nicht gesynct werden); Frage @nimaai : gibt es irgend einen struben Worklfow bei dem Badge IDs für nicht ZHdK Benutzer gesetzt werden; die wären dann auch alle weg.

**Comment by eins78** [comment]
Ergebnisse vom Ortsbesuch:

DB, per sofort:
- `badge_id` entfernen löst die meisten probleme
- alle Pool-`access_rights` entfernen wäre auch gewünscht. 
  Weil die meisten User aber per Semesterwechsel kommen, muss der Sync nicht sofort angepasst werden. Die aktuellen Probleme können wir per einmaligem Script/SQL lösen ("entferne alle access_rights von inaktiven usern")

DB, langfristig:
- neues feld `users.secondary_email`. Gut für alle "institutionellen" Leihs-Instanzen – der User kann noch kontaktiert werden, auch wenn er schon weg ist und der sync daher die Email-Adresse entfernt hat (passiert wohl in der Praxis, dass einige noch Equipment haben…)
  - bei uns würde dieses Feld per Sync mit der Privat-Adresse gefüllt werden

UI, mittelfristig:
- inaktive User markieren!
  * Zeilen ausgrauen (am besten überall, mindestens in den Contract-Lines der Suche)
  * evtl. "INAKTIV!!!" in das popover schreiben

**Comment by DrTom** [comment]
Kommentar zu E-Mail speichern: könnte in vielen Fällen helfen. Der Wirklich grosse Mist dabei ist, dass E-Mail Adressen sich 
1. ändern können ( habe ich schon erlebt und musste den Sync dafür anpassen), 
2. wieder verwendet werden
Wenn 2. nicht wäre würde es diese ganze Diskussion und das Problem dahinter überhaupt nicht geben.

**Comment by eins78** [comment]
> grosse Mist dabei ist, dass E-Mail Adressen sich
> 1. ändern können ( habe ich schon erlebt und musste den Sync dafür anpassen),
> 2. wieder verwendet werden

Es geht ja nur um die Privat-Email. Wird für keine System-Funktionen (wie Login etc) genutzt, ist also auch kein "Erkennungsmerkmal" für den Sync. Damit sollten das keine Probleme sein in der Praxis – es darf, ja soll sich sogar ändern. Und Wiederverwendung ist da auch weniger wahrscheinlich und schlimm.

Noch eine Fussnote, evtl. hilfreich zum Verständnis warum `badge_id` entfernen nur _fast_ alle Probleme löst: Es kann ein User per Sync angelegt werden, der (noch) keine Badge-ID hat! Dann scannen sie am Desk erfolglos, tippen dann den Namen und finden beide (aktuell im UI auch nicht zu unterscheiden). Meine Vermutung: Die Badge-ID ist ja eigentlich die Nebis-Nummer, d.h. es gibt erst eine nach Anmeldung in der Bibliothek!

**Comment by nimaai** [comment]
Also nochmals hier die definitiven und unmittelbaren ToDos:
- [ ] "users.badge_id" beim Deaktivieren löschen im Sync (@DrTom )
- [ ] Deaktivierte User in leihs-UI visuell unterscheiden (@eins78 )
- [ ] Liste an Roger mit potenziell problematischen Usern (@nimaai )

**Comment by nimaai** [comment]
@DrTom [OTRS](https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=298098)

**Comment by DrTom** [comment]
solved
