### ISSUE TITLE
TASK [leihs-database-install : install bundler and bundle] 

### ISSUE THREAD

**Issue by avabraxas** [leihs/leihs#752]
hello,

I'm trying to deploy Leihs behind a proxy, when come to the task in title I get the following error.

fatal: [xxxxxxxxxx]l: FAILED! => changed=true
  cmd: |-
    set -eux
     export PATH=$HOME/.rubies/ruby-2.6.0/bin:$PATH
     gem install bundler
     cd /leihs/database
     bundle install
  delta: '0:00:00.277340'
  end: '2019-10-17 14:15:27.570070'
  msg: non-zero return code
  rc: 2
  start: '2019-10-17 14:15:27.292730'
  stderr: |-
    + export PATH=/home/leihs-database/.rubies/ruby-2.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    + gem install bundler
    ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
              Unable to download data from https://rubygems.org/ - Errno::ENETUNREACH: Failed to open TCP connection to rubygems.org:443 (Network is unreachable - connect(2) for "rubygems.org" port 443) (https://rubygems.org/specs.4.8.gz)
  stderr_lines:
  - + export PATH=/home/leihs-database/.rubies/ruby-2.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - + gem install bundler
  - 'ERROR:  Could not find a valid gem ''bundler'' (>= 0), here is why:'
  - '          Unable to download data from https://rubygems.org/ - Errno::ENETUNREACH: Failed to open TCP connection to rubygems.org:443 (Network is unreachable - connect(2) for "rubygems.org" port 443) (https://rubygems.org/specs.4.8.gz)'
  stdout: ''
  stdout_lines: <omitted>

Could you please help me to find a workaround?

Thank you

#### Specifications
- Leihs version: 5.1.3

**Comment by DrTom** [comment]
We have no experience with such a setup. The Ansible-Documentation has some information about setting up proxies: https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html . This can be done from the inventory/environment and needs no change within the leihs deploy repository.
