### ISSUE TITLE
clojure: uberjars must be built with JDK 8

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#756]
error `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;` happens when we build an uberjar with JDK > 8 but run on java 8.

* happens with `lein` and `boot`
* the code in question is not ours but comes via a dep (`manifold.utils`)
* adding jvm opts does not work! `JVM_OPTIONS=-target 1.8 -source 1.8 -Xlint:-options`, see https://github.com/leihs/leihs-borrow/blob/ef7466d263616883ca46bf1f1b6d92e9478d376e/boot.properties#L2
* technical details: 
    * https://jira.mongodb.org/browse/JAVA-2559
    * https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243

I am adding workarounds (enfore JDK 8 when building) that are OK for now but we should find a better solution. maybe just some dependency needs to be updated.

**Comment by DrTom** [comment]
The new Madek media-service prototype builds with JDK11. I suggest du do a "big" upgrade per service once as opposed to just fix this particular issue. Under the hood we should (sometimes must) upgrade various libraries in relation to this upgrade. Here are some:

* database driver 
* clj-pg-types (related to database driver)
* replace clj-time (related clj-pg-types) 
* switch build chain to use depts tool and remove leiningen and boot
* switch javascript compilation to use shadow-clj

**Comment by eins78** [comment]
not a problem anymore
