### ISSUE TITLE
legacy: fix for borrow app db changes

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#761]
added new DB, some specs are broken. maybe even real features…

https://github.com/leihs/leihs_legacy/compare/mfa/feat/new-borrow

example error from spec: https://ci.zhdk.ch/cider-ci/ui/workspace/trials/6ac4dc88-e2ff-4e25-a6d6-a4513e69c29c/scripts/test
`ERROR:  customer_order_id cannot be null for a new order.`

**Comment by nimaai** [comment]
https://github.com/leihs/leihs_legacy/commit/1526343a327c7c7b6775460dd3d167dd06423411

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/ffe56997192b4f9e5595991f641ae00ac7448c5a
