### ISSUE TITLE
DB-Dump on demand (Admin)

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#762]
@DrTom As discussed. The earlier the better.

**Comment by DrTom** [comment]
Did some research about the question about locks. Not much in the documentation hinting to that. It rather seems that `pg_dump` does not lock the db or a table for normal use. All what I could find ist the following: 

> pg_dump takes a reader's lock (AccessShareLock).  This does not prevent
reads or writes of the table.  It does prevent dropping the table,
making schema alterations to it (such as column add/drop), or anything
else that wants an exclusive lock.  I think that VACUUM FULL is the only
thing particularly likely to cause a conflict in a running database.

Seems we could continue with this request.

**Comment by DrTom** [comment]
After some discussion: we will not  implement this.  For data security reasons such a feature would have to be restricted to about the same people having access to the database in other ways (ssh, ansible, psql).
