### ISSUE TITLE
Leihs won't start

### ISSUE THREAD

**Issue by ernst-abraxas** [leihs/leihs#770]
The expected behaviour is to see the Leihs UI in the webinterface, after a correct installation of leihs, by Ansible.

Are the known configuration issues known with leihs 5.x (latest version) installation powered by Ansible

The actual behaviour
The application is not reacheable by webbrowser, Firefox 71.0 or chrome 79.0.3945.88.

#### Steps to reproduce
Everytime I try to restart **systemctl start leihs-legacy.service**
FAILURE: A dependency job for leihs-legacy.service failed. See 'journalctl -xe' for details.

-- Unit leihs-migration.service has begun starting up.
Dec 19 15:19:21 sr0540 leihs-migration[3376]: rake aborted!
Dec 19 15:19:21 sr0540 leihs-migration[3376]: Cannot load `Rails.application.database_configuration`:
Dec 19 15:19:21 sr0540 leihs-migration[3376]: Could not load database configuration. No such file - ["config/database.yml"]
Dec 19 15:19:21 sr0540 leihs-migration[3376]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `load'
Dec 19 15:19:21 sr0540 leihs-migration[3376]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `<main>'
Dec 19 15:19:21 sr0540 leihs-migration[3376]: Caused by:
Dec 19 15:19:21 sr0540 leihs-migration[3376]: Could not load database configuration. No such file - ["config/database.yml"]
Dec 19 15:19:21 sr0540 leihs-migration[3376]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `load'
Dec 19 15:19:21 sr0540 leihs-migration[3376]: /home/leihs-database/.rubies/ruby-2.6.0/bin/bundle:23:in `<main>'
Dec 19 15:19:21 sr0540 leihs-migration[3376]: Tasks: TOP => db:create => db:load_config
Dec 19 15:19:21 sr0540 leihs-migration[3376]: (See full trace by running task with --trace)
Dec 19 15:19:21 sr0540 systemd[1]: leihs-migration.service: Main process exited, code=exited, status=1/FAILURE
Dec 19 15:19:21 sr0540 systemd[1]: Failed to start Leihs Migration Service.
-- Subject: Unit leihs-migration.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit leihs-migration.service has failed.
--
-- The result is failed.
Dec 19 15:19:21 sr0540 systemd[1]: Dependency failed for Leihs Legacy Service.
-- Subject: Unit leihs-legacy.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit leihs-legacy.service has failed.
--
-- The result is dependency.
Dec 19 15:19:21 sr0540 systemd[1]: leihs-legacy.service: Job leihs-legacy.service/start failed with result 'dependency'.
Dec 19 15:19:21 sr0540 systemd[1]: leihs-migration.service: Unit entered failed state.
Dec 19 15:19:21 sr0540 systemd[1]: leihs-migration.service: Failed with result 'exit-code'.
Dec 19 15:19:22 sr0540 ntpd[597]: Soliciting pool server 212.51.144.44
Dec 19 15:19:27 sr0540 ntpd[597]: Soliciting pool server 217.147.208.1
Dec 19 15:19:33 sr0540 ntpd[597]: Soliciting pool server 84.16.67.12

Tips are welcome to get the application running.

#### Specifications
- OS Version="Debian GNU/Linux 9 (stretch)"
- Database = "Postgres 10.11 psql (10.11 (Debian 10.11-1.pgdg90+1)
- Python 2.7.13
- ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
- Openjdk version "1.8.0_232"
- OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
- OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
- Leihs version: 5.x
- Browser version: Firefox 71.0 or chrome 79.0.3945.88

Thanks in Advance
Ernst

**Comment by DrTom** [comment]
The "migration" service apparently has no configuration specifying the database to connect to. This is part of the deploy https://github.com/leihs/leihs_deploy/tree/master/roles/leihs-database-install/tasks. I can not imagine how it is possible to arrive at such a situation without some errors during the deploy.

**Comment by ernst-abraxas** [comment]
Thanks for the tip! I found my problem, there is a definition needed for a proxy server. I tried to add a proxy server in the .yml file in the host_vars folder but the result is the same.

   !!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt to /home/leihs-database/.cache/ruby-install/ruby/versions.txt!
    !!! Failed to download ruby versions!
  stderr_lines:
  - + ruby-install --no-install-deps --no-reinstall ruby 2.6.0
  - '!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt to /home/leihs-database/.cache/ruby-install/ruby/versions.txt!'
  - '!!! Failed to download ruby versions!'
  stdout: '>>> Updating ruby versions ...'
  stdout_lines: <omitted>  

Do you have a tip how to configure the proxy in this configuration?

**Comment by DrTom** [comment]
So it seems `ruby-install` fails probably because of the proxy. . The source of ruby-install is here https://github.com/postmodern/ruby-install and it seems it is using `wget`. Maybe some environment variable specifying the HTTP proxy needs to be exposed?  This is the first thing I would look for. There are also a number of command line options for the tool. Possibly they could be used to work around the problem? Again we don't have any experience with your setup.

**Comment by DrTom** [comment]
Problem seems to be related to local environment and we can not fix this.
