### ISSUE TITLE
Language Bug: legacy app shows english UI which is not even configured for the system 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#777]
There is a strange language bug. It might be interconnected with a particular language setting and cookies and possible more. Here is how it can be reproduced: 

1. configure the only available and default language to german
2. sign out and delete all leihs cookies
3. set the `language_id` for the user in the users table to `NULL` (not sure how to arrive at this state without going directly into the DB, maybe if there used to be an other language configured)
4. sign-in, the my app shows german UI which is confirmed in the users menu
5. when you open the legacy app the UI is presented in english

**Comment by DrTom** [comment]
The cause of the problem was an inconsistent language configuration: two languages were set as default of which one was not even enabled. There should be constraints preventing such configurations.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/71f69fa4a65b0dc581c3454cd7b09475047123de

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/trees/8006041695dda4d2c2c36acc0c61489bdb19f553
