### ISSUE TITLE
graphiql: "The x-csrf-token has not been send!"

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#782]
```
Error: [{"message":"The x-csrf-token has not been send!","extensions":{"code":"API_ERROR","timestamp":"2020-02-19T09:40:02.374Z"}}]
```

**Comment by eins78** [comment]
procure app sets up a  GraphiQL under `/procure/dev/console` which works.
lacinia also serves one, which is not configured and does not work – should be removed.
