### ISSUE TITLE
Preinstalled Image?

### ISSUE THREAD

**Issue by invrspace** [leihs/leihs#783]
Hi Guys,

if I remember right there was a OS Image with preinstalled Leihs available quite some time ago. Unfortunately I can't find it anymore. Could you help me out and tell me where to find it?

Thanks!

**Comment by DrTom** [comment]
I don't know of that. Theoretically this is possible, practically there are security problems: the image would include secrets. Some are system related (like hostkeys you might now about and can fix it) and some others are leihs specific and there is not automated way to reset them. So for now preinstalled images are useless other for trying things. For that purpose there is https://demo.leihs.zhdk.ch/
