### ISSUE TITLE
Restore a backup database

### ISSUE THREAD

**Issue by JoeFrom7000** [leihs/leihs#786]
Hello,

Could you explain simply how to restore a backup database if i need to re-deploy an instance of leihs on one other machine .

I have the file leihs-dump_2020-02-25T10_45_13CET.pgbin

I use release 5.1.8 of leihs-instance

Thanks

**Comment by DrTom** [comment]
The file is a regular Postgresql file. In short: 

- make sure all leihs services are stopped, somethin like `systemctl stop leihs*` 
- use `pg_restore` to restore the mentioned file. Hint: there can arise a problem with older dumps and newer pg versions, if that is the case proceed in two steps: first restore schema, then restore data `pg_restore` has options to do that

**Comment by JoeFrom7000** [comment]
Thanks
