### ISSUE TITLE
ERROR: column "suspended_until" does not exist

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#787]
https://staging.leihs.zhdk.ch/admin/users/e4da3cef-6a05-5b04-9ce6-2154286cfad9/inventory-pools-roles/

<img width="1250" alt="Screenshot 2020-02-25 at 15 26 25" src="https://user-images.githubusercontent.com/3205913/75256185-5d232b00-57e3-11ea-9bca-2c7938c90810.png">

**Comment by DrTom** [comment]
Hast du alles rebased und migriert?

**Comment by nimaai** [comment]
Ist auf Staging. Diese Version: https://github.com/leihs/leihs/commits/ac13baaa919b11192d3c90312af01ff14f465bce

Wie auf Prod...

**Comment by DrTom** [comment]
https://github.com/leihs/leihs/commit/e4eda71365ac274b7e8d88b5b282a5febbac5357
https://ci.zhdk.ch/cider-ci/trees/94294fe50a862b59a7ff24a0e8addf235972197f
