### ISSUE TITLE
Admin: User with full name not found

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#788]
A*** F**ZZ*

**Comment by DrTom** [comment]
Search users two matchers: trigram and ilike on the the `searchable` field.

This is a particular case here:  the login of this person has nothing to do with the name. Therefore trigram search doesn't fit as well as in "normal" cases where the login contains (part) of the name.

Searchable contains "LASTNAME FIRSTNAME" so ilike doesn't mach either. 

Solution: we should (addionally) use "FIRSTNAME LASTNAME" in the searchable field.

**Comment by DrTom** [comment]
https://ci.zhdk.ch/cider-ci/trees/1ac1392297a36c7b4c95d3400b210a8709afa069
