### ISSUE TITLE
Installing with SSH keys?

### ISSUE THREAD

**Issue by helloha82** [leihs/leihs#791]
Is it possible to install with ssh keys? Because I can't seem to do it. The installer needs these two variables in the beginning:

```
export LEIHS_HOSTNAME="leihs.example.com"
export LEIHS_HOST_USER="root"
```

But how do you deal with SSH keys in this instance?

When running the startup script at the end i run into a brick wall...

THX!

**Comment by JoeFrom7000** [comment]
I made a local leihs server - Debian 9 (ip: 192.168.1.100).

ON THE SERVER
----------------
Make sure that open-ssh-server is installed and running.
Edit the file /etc/ssh/sshd_config and uncomment or add this line:
PermitRootLogin yes

Save, close and restart ssh daemon
#service sshd restart


WITH THE CONTROL MACHINE
--------------------------------
open terminal window.
export LEIHS_HOSTNAME="192.168.1.100"
export LEIHS_HOST_USER="root"
ssh-keygen
ssh-copy-id LEIHS_HOST_USER@LEIHS_HOSTNAME

Test ssh connection with the following command:
ssh LEIHS_HOST_USER@LEIHS_HOSTNAME
Edit the file /etc/ssh/sshd_config again and change PermitRootLogin **yes** to PermitRootLogin **prohibit-password**
Save, close and restart ssh daemon
#service sshd restart
exit

ssh again to the server
ssh LEIHS_HOST_USER@LEIHS_HOSTNAME

**Comment by DrTom** [comment]
Not only possible but the recommended way to do it and we do it this way, too. But I don't believe ansible can use env vars in this way. You need to set the parameters in ansibles hosts configuration/file, e.g.:
```
ansible_host: zhdk-leihs-test.ruby.zhdk.ch
ansible_user: root
```
Please also see the ansible documentation.
