### ISSUE TITLE
smtp config for a gmail account

### ISSUE THREAD

**Issue by JoeFrom7000** [leihs/leihs#793]
Hello,

Could you help me to configure the mail settings section under admin account.

The leihs admin has a gmail account. For example mymail@gmail.com

Thanks

Settings under admin login
----------------------------
smtp_address:
smtp_authentication_type:
smtp_default_from_address:
smtp_domain:
smtp_enable_starttls_auto:
smtp_openssl_verify_mode:
smtp_password:
smtp_port:
smtp_sender_address:
smtp_username:

**Comment by DrTom** [comment]
We have no experience with leihs and gmail so we can't help you directly. Generally this should work.  You need to find the proper parameters for gmail. It should be documented by the provider, google in this case.

**Comment by eins78** [comment]
The Rails docs have a configuration example for Gmail: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration-for-gmail
