### ISSUE TITLE
500 error trying to add a model and assign it to a category

### ISSUE THREAD

**Issue by gleeman2** [leihs/leihs#800]
#### Actual behaviour

<!DOCTYPE html> <html> <head> <title>We're sorry, but something went wrong (500)</title> <style type="text/css"> body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; } div.dialog { width: 25em; padding: 0 4em; margin: 4em auto 0 auto; border: 1px solid #ccc; border-right-color: #999; border-bottom-color: #999; } h1 { font-size: 100%; color: #f00; line-height: 1.5em; } </style> </head> <body>  <div class="dialog"> <h1>We're sorry, but something went wrong.</h1> <p>We've been notified about this issue and we'll take a look at it shortly.</p> </div> </body> </html>

#### Steps to reproduce

add a model and assign it to a category

#### Related issues 

Also getting error when adding an image to a model

#### Specifications
- Leihs version: 3.8.0
- Browser version: Firefox, Chrome 80.0.3987.132, Safari
- MySQL/PostreSQL version: mariadb-5.5.60-1.el7_5.x86_64
- RHEL 7.6
- Rails 5.2.3
- ruby 2.3.3p222 (2016-11-21 revision 56859)

**Comment by nimaai** [comment]
leihs versions 3.x and 4.x are not supported anymore as mentioned [here](https://github.com/leihs/leihs/wiki/Deployment). Please install or upgrade to the newest version.
