### ISSUE TITLE
Install fails for mail and postgress

### ISSUE THREAD

**Issue by gleeman2** [leihs/leihs#802]
#### Expected behaviour

Install completes as expected

#### Actual behaviour

Ansible install fails with following error for Postgress and leihs-mail-install

TASK [postgresql : shell] **********************************************************************************
fatal: [theatrecheckout03.mtsu.edu]: FAILED! => changed=true
  cmd: dpkg-query -S 'postgresql-9.6'
  delta: '0:00:00.155855'
  end: '2020-03-26 13:28:20.856605'
  msg: non-zero return code
  rc: 1
  start: '2020-03-26 13:28:20.700750'
  stderr: 'dpkg-query: no path found matching pattern *postgresql-9.6*'
  stderr_lines:
  - 'dpkg-query: no path found matching pattern *postgresql-9.6*'
  stdout: ''
  stdout_lines: <omitted>
...ignoring

TASK [postgresql : stop postgresql service (to free up the port before upgrading)] *************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|succeeded` use
`result is succeeded`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by
 setting deprecation_warnings=False in ansible.cfg.
skipping: [theatrecheckout03.mtsu.edu]

TASK [postgresql : include_tasks] **************************************************************************
included: /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/roles/postgresql/tasks/install.yml for theatrecheckout03.mtsu.edu

TASK [postgresql : start pg service] ***********************************************************************
ok: [theatrecheckout03.mtsu.edu]

TASK [postgresql : make sure pg port is opened] ************************************************************
ok: [theatrecheckout03.mtsu.edu]

TASK [postgresql : add root postgresql user] ***************************************************************
ok: [theatrecheckout03.mtsu.edu]

TASK [postgresql : Create the a database for root] *********************************************************
ok: [theatrecheckout03.mtsu.edu]

TASK [install : dist upgrade] ******************************************************************************
ok: [theatrecheckout03.mtsu.edu]

…….

TASK [leihs-mail-install : include_tasks] ******************************************************************
included: /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/roles/leihs-mail-install/tasks/jar.yml for theatrecheckout03.mtsu.edu

TASK [leihs-mail-install : create jar] *********************************************************************
fatal: [theatrecheckout03.mtsu.edu -> localhost]: FAILED! => changed=true
  cmd: |-
    set -eux
     DEPLOY_DIR='/home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy'
     cd $DEPLOY_DIR/../mail
     $DEPLOY_DIR/bin/boot uberjar
  delta: '0:00:00.008484'
  end: '2020-03-26 08:28:45.028165'
  msg: non-zero return code
  rc: 127
  start: '2020-03-26 08:28:45.019681'
  stderr: |-
    + DEPLOY_DIR=/home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy
    + cd /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/../mail
    + /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/bin/boot uberjar
    /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/bin/boot: line 6: exec: java: not found
  stderr_lines:
  - + DEPLOY_DIR=/home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy
  - + cd /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/../mail
  - + /home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/bin/boot uberjar
  - '/home/ansibleadmin/Downloads/theatrecheckout03.mtsu.edu_hosting/leihs/deploy/bin/boot: line 6: exec: java: not found'
  stdout: ''
  stdout_lines: <omitted>

#### Steps to reproduce

./script/deploy

#### Specifications
- Leihs version: 5
- Browser version: 
- MySQL/PostreSQL version: PS - 10
- Java version on target server 
 openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**Comment by gleeman2** [comment]
Seems that was able to resolve the initial mail issue. The cause was the java version on the Ansible controller. After using alternative and switching to a different version it bypassed and now sit with 

 TASK [leihs-mail-install : copy jar over to server] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are                 using a module and expect the file to exist on the remote, see the remote_src option
fatal: [theatrecheckout03]: FAILED! => changed=false
  msg: |-
    Could not find or access '/home/ansibleadmin/Downloads/theatrecheckout03_hosting/leihs/deploy/.                ./mail/target/leihs-mail.jar' on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option.

Anyone have suggestions to resolve this one?

**Comment by gleeman2** [comment]
We were able to get as far as the jar files being created and am stuck with NPM issues now (npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed). Since this is not part of the original case, ill reopen a new one.

**Comment by korakinos** [comment]
> We were able to get as far as the jar files being created […]

@gleeman2, how did you solve the previous error (about leihs-mail.jar not being found)?

**Comment by anroots** [comment]
My "workaround" - instead of running Ansible on the host, use the Dockerized installer. I suspect my host (Ubuntu 20) is running newer-than-supported software; or install depends on some undocumented dependencies, which are present in Docker.
