### ISSUE TITLE
show a message when the user can login but has no access right

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#803]
- [ ] add page in `my`
- [ ] redirect from legacy

**Comment by nimaai** [comment]
@eins78 What is meant by "add page" in `my` ?

**Comment by eins78** [comment]
> @eins78 What is meant by "add page" in `my` ?

a page that shows a message ("you do not have any access rights"). could also be the users own profile page that shows a error message on top in such cases.
the goal is to communicate to the users what's up, so they don't have to ask (us).

**Comment by nadjaweisskopf** [comment]
Borrow doesn't even give you access to the borrow section if you don't have access to at least one pool.

**Comment by eins78** [comment]
@nadjaweisskopf I still need the text (and translations) of the message that should be shown.

**Comment by eins78** [comment]
current text: 

> You can not use the borrow section because you dont have access rights to any inventory pool!
> Please contact your support or lending desk.

---

<img width="810" alt="Screen Shot 2021-03-25 at 10 40 52" src="https://user-images.githubusercontent.com/134942/112452546-0629b580-8d57-11eb-8e0f-075a103fda7d.png">

**Comment by eins78** [comment]
I also repaired the display of the UUID for the user and added the email, to make this kind of situation easier to solve or debug.

**Comment by nadjaweisskopf** [comment]
@eins78 The solution is perfect for the moment. Thanks. Is this already delivered and ready to test?

**Comment by eins78** [comment]
> @eins78 The solution is perfect for the moment. Thanks. Is this already delivered and ready to test?

Yes! I just forgot to close the issue.

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/6e6fa19f08faa61d03aab15b2137340b7f09f152
