### ISSUE TITLE
error when accessing the leihs pools

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#805]
#### Expected behaviour
When accessing the leihs pools from the user page I would expect to be navigated to the list of inventory pools. 

#### Actual behaviour
I get an error when pressing on the link "31 inventory pool roles"

#### Steps to reproduce
1. go to Admin section
2. edit a user which is at least customer in at least one pool.
3. press on the link at the bottom of the page "xy inventory pool roles"

https://staging.leihs.zhdk.ch/admin/users/f23ca963-a2d5-59db-bef8-9998ba40520d

#### Related issues 
might have to do with the following ticket: https://github.com/leihs/leihs/projects/18#card-30623669

#### Specifications
- Leihs version: staging
- Browser version: safari
- MySQL/PostreSQL version: current

<img width="796" alt="Bildschirmfoto 2020-05-05 um 12 03 11" src="https://user-images.githubusercontent.com/3356016/81055911-ee8cd880-8ec9-11ea-8f65-b508147c80c3.png">

**Comment by DrTom** [comment]
This problem appears only on staging and not test. I remember that we already had a similar bug which was fixed. Most likely staging has some version deployed which still has that bug. 

@nadjaweisskopf can you confirm this works on test?

**Comment by DrTom** [comment]
@nadjaweisskopf when looking at this particular page it seems to have become inconsistent with other components introduced with the new roles. here is a ticket https://github.com/leihs/leihs/issues/814
