### ISSUE TITLE
list of pools has lost its sort order

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#806]
#### Expected behaviour
When I access the list of pools in the drop down on the top right of the page, I would expect to see all pools listed alphabetically

#### Actual behaviour
I am not sure according to which order the pools are sorted.  

#### Steps to reproduce
1. log in to leihs
2. access the pools on the top right of leihs (new nav bar)
3. The pools are not sorted according to the alphabet
#### Specifications
- Leihs version: production
- Browser version: safari
- MySQL/PostreSQL version: current

<img width="781" alt="Bildschirmfoto 2020-05-05 um 13 31 15" src="https://user-images.githubusercontent.com/3356016/81061477-b76ff480-8ed4-11ea-942e-79e7354e4a91.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/0c7dc07d861776ddce2389adb7d7ed50fe5834be
