### ISSUE TITLE
Place a link on users page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#808]
**Add the link** 
D: "Rollen der (Benutzer-)Gruppen verwalten" 
E: "manage Group rights"

**Where**: tab "User"

<img width="756" alt="List of Users" src="https://user-images.githubusercontent.com/3356016/81701674-a42bce80-946a-11ea-8ef3-e3805fb89e73.png">

**Description:**
The link navigates to the page of groups of a specific inventory pool.
f.e. https://test.leihs.zhdk.ch/admin/inventory-pools/bccadb7a-dd2d-5851-9d4b-d338eda47453/groups/

**Related issues:** 
https://github.com/leihs/leihs/projects/18#card-30623669

**Comment by DrTom** [comment]
Different approach for this problem in https://github.com/leihs/leihs/issues/819

**Comment by nadjaweisskopf** [comment]
1. text is not translated
2. In some months the Admin section will not be new anymore. Therefor I would prefer another text. 
3. I will create another ticket for this.
