### ISSUE TITLE
Make title klickable

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#809]
The group name should be a link which leads to the edit page of the group roles related to an inventory pool.

**Link as marked below:** 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/b0b27f01-7e02-45b2-9af9-a0db6c5bbfa4
<img width="800" alt="Details of user" src="https://user-images.githubusercontent.com/3356016/81703555-0e457300-946d-11ea-8a95-6968cd7b83f3.png">

**Link should lead to the following page:** 
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/groups/9b4ab660-8a3f-4a9e-85c5-f9976f987bd0/roles

Related issue: 
https://github.com/leihs/leihs/projects/18#card-30623669

**Comment by DrTom** [comment]
https://github.com/leihs/leihs-admin/commit/1c66c138e8911bf2708c7fbe7e39ab7113349c63

Ein kleiner Twist hier: "Group XYZ" verlinkt sonst überall zu der Gruppe; ich wollte das jetzt an dieser Stelle nicht anders handhaben. Ich habe  "Roles [edit-icon]" davor gehängt und als link genommen
