### ISSUE TITLE
Name links back to legacy

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#810]
When klicking on the name, I am navigated back to the users page on legacy. 

1. https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/b0b27f01-7e02-45b2-9af9-a0db6c5bbfa4
<img width="857" alt="Name is a link" src="https://user-images.githubusercontent.com/3356016/81705339-3b932080-946f-11ea-8836-b0f5d3ecfa91.png">

2. Then klick on the name
3. You are navigated to the edit page of a user in the specific pool: https://test.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/users/b0b27f01-7e02-45b2-9af9-a0db6c5bbfa4/edit

Related issue: 
https://github.com/leihs/leihs/projects/18#card-30623669

**Comment by DrTom** [comment]
Slightly different solution in https://github.com/leihs/leihs/issues/817
reson: links like the above usually link to the inventory pool within the admin service; so that would be confusing
