### ISSUE TITLE
Design enhancements

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#811]
If possible try to make the following design enhancements to help the user find the needed information quicker. 
<img width="828" alt="Design enhancements" src="https://user-images.githubusercontent.com/3356016/81706877-8f523980-9470-11ea-8efe-3489602c1cbd.png">

https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/b0b27f01-7e02-45b2-9af9-a0db6c5bbfa4

Related issue: 
https://github.com/leihs/leihs/projects/18#card-30623669

**Comment by DrTom** [comment]
https://github.com/leihs/leihs-admin/commit/1443b635f79d74b9d6d6f8a5220ef548ee1e8209
