### ISSUE TITLE
Reduce the gap between the columns

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#812]
Can we reduce the gap between the column "Name" and "Roles"? I searched for quite some time until I found the column "Roles". 

https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/groups/

<img width="1197" alt="Bildschirmfoto 2020-05-11 um 17 03 02" src="https://user-images.githubusercontent.com/3356016/81707428-f07a0d00-9470-11ea-869a-a78618a80289.png">

Related issue: 
https://github.com/leihs/leihs/projects/18#card-30623669

**Comment by DrTom** [comment]
Ah, ich hab keine Ahnung warum das Bootstrap hier so auseinander zieht. Ich könnte etwas frickeln aber ich habe die Befürchtung es für andere Fälle damit richtig kaputt zu machen. Besser das schaut sich ein CSS experte an. 
@nadjaweisskopf du kannst es wieder aufmachen und an @eins78 weitergeben.
