### ISSUE TITLE
Can't take back item for user that has no customer role anymore

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#813]
```gherkin
Given I am a lending manager for Pool B
And there is a signed contract for User A in Pool B
And I have removed the role "customer" for User A from Pool B
When I search for User A in Pool B
And I click on "Take Back"
Then I get an error "No Access!"
```

**Comment by nimaai** [comment]
First finding: in legacy one cannot change the direct role of the user if he/she has some items to return. Error message: "Currently has items to return"

**Comment by nimaai** [comment]
For the same User legacy is showing "No access" 

https://staging.leihs.zhdk.ch/manage/5dd25b58-fa56-5095-bd97-2696d92c2fb1/users/d663420c-fabb-59a0-91a4-abb58f1bac86/edit

but Admin is showing "Customer"

https://staging.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/users/d663420c-fabb-59a0-91a4-abb58f1bac86

**Comment by eins78** [comment]
problematic cases that should not happen:
- user without access to pool but open contracts ("items to return")
- user without access but open orders ("items to pick up")

todo:
- [ ] Prod DB: check our prod data to proactively fix those cases before they happen again 
   - SQL query to find users without access but open orders or contracts
   - either fix those manually or do that in SQL as well

- [ ] DB constraints, disallow the problematic cases
    - in same migration also clean up data

- [ ] new admin: don't allow removing access in those cases
    - show message on top of editing form and disable inputs (do not show error message only after saving, it something goes wrong the DB will complain anyways)

- [ ] optional, if somehow we don't want to or can't fix the data (first 2 tasks): adjust `take back` backend to always allow take backs no matter the customers access rights

**Comment by eins78** [comment]
- [ ] legacy: allow take back for non-customers 
- [ ] show non-customer-status (at least on take back) (like suspended)
- [ ] legacy: allow removing access if open orders/contracts (e.g. [remove this spec](https://github.com/leihs/leihs_legacy/blob/4c22eec9dc025791c6bf994e2044fdc684de2dc4/features/manage/manage_users.feature#L134-L150))

**Comment by nadjaweisskopf** [comment]
- status next to the user visible
- it is possible to take back an item even if user is suspended
- it is possible to extend the return date
