### ISSUE TITLE
Add a new tab 'Groups' within inventory_pool manage with explanation and link

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#819]
![Screenshot 2020-05-18 at 16 49 04](https://user-images.githubusercontent.com/526053/82227073-932a0400-9927-11ea-940d-b3c04f996e12.png)

**Comment by DrTom** [comment]
This solves https://github.com/leihs/leihs/issues/808 in a more consistent way

**Comment by nadjaweisskopf** [comment]
@DrTom can i move this ticket to "Released on staging"?
