### ISSUE TITLE
Decide which model picture is to be shown in lists

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#821]
If several pictures for a model exist, the lending managers/inventory managers want to define which picture is the leading picture and is shown in the lists. 

Possible solutions: 
- Possibility to move the pictures up and down (sorting the pictures by mouse). The first picture on the top is shown in the lists. 
- Klick on check box to mark the leading picture
- ...

<img width="1018" alt="Bildschirmfoto 2020-05-19 um 13 40 18" src="https://user-images.githubusercontent.com/3356016/82322137-4ea97180-99d6-11ea-87d7-ccdaa5bc34ea.png">

**Comment by nadjaweisskopf** [comment]
We discussed that the best solutions seems to be a checkbox indicating which picture is the leading picture.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/884b2ae3cc27f162ebb78fe889e69026f62e771c

**Comment by nadjaweisskopf** [comment]
@nimaai I get an error when saving the model with several pictures. We had the same bug in procurement section as far as I remember. 

What I did: 

1. Open a model
2. add several pictures
3. save model
4. error appears

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6633291061f799faca834381f10a119ee12c9b2f
