### ISSUE TITLE
Maintenance period on model / item

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#822]
To be discusses: 

The lending department would like to have the possibility, to set a maintenance period on models. 

F.e.

- model has two items.
- One of the items is in stock
- The other item has been taken back on the 1.6.20 and needs a cleaning period of 1 day.
- So on the 1.6.20 and on the 2.6.20 only one item is available
On the 5.6.20 both items can be handed out again

Solutions: 
- we introduce an additional status fields
- as soon as the inventory pool mgr. has set the maintenance period of all models in the inventory pool settings to f.e. 1 day, then 
- a newly introduced item status is set to "maintenance" 
- and the item can not be lent out anymore. 
- when the period has ended, the status is set back to "normal" 
- and the item can be reserved again.

The lending department believes, they will be needing this behaviour until at least January 2021.

**Comment by nadjaweisskopf** [comment]
We discussed that a field "maintenance" already exists in the database and the code but is not shown in any UI. @nimaai did we say you would check the code to see how this feature could be developed? As far as I remember we said the current maintenance field is for the whole leihs instance, not for an inventory park, is that right?

**Comment by nadjaweisskopf** [comment]
One solution could be: 
We set the maintenance period for all models for all inventory pools (once). The field is to be tested by a developer and @nadjaweisskopf. As soon as the maintenance period is not needed anymore we delete the value.

**Comment by eins78** [comment]
Good news! I did a quick test and it works like we hoped!

We can set the "maintenance period" to any number of days, per Model, for all Pools.
The booking calendar behaves correctly: if I set the m.p. to 1 day, then any reservations (also existing ones!) are handled as if they were 1 day longer. 

---

make a reservation for Monday and Tuesday:
<img width="1021" alt="Screen Shot 2020-06-29 at 14 44 35" src="https://user-images.githubusercontent.com/134942/86007892-59fdad00-ba18-11ea-92de-20d87a43ec48.png">

calendar shows 1 of 2 available for those 2 days:
<img width="937" alt="Screen Shot 2020-06-29 at 14 45 00" src="https://user-images.githubusercontent.com/134942/86007952-70a40400-ba18-11ea-8c48-1d06ef82c924.png">

now when I set the m.p. to 1 day for this Model, calendar shows 1 of 2 available for 1 day longer:
<img width="929" alt="Screen Shot 2020-06-29 at 14 48 25" src="https://user-images.githubusercontent.com/134942/86008049-96310d80-ba18-11ea-9451-32828cc6ef5d.png">

**Comment by eins78** [comment]
@nadjaweisskopf Daten sind bis morgen noch auf `test`, dieses Model hat jetzt "1 tag maintance": https://test.leihs.zhdk.ch/borrow/search?search_term=AVCHD-Kamera%20Sony%20HXR-NX5E

**Comment by eins78** [comment]
@nadjaweisskopf Next steps:
* NW: ask the Pools which Models should get this – if not *ALL* then we need a excel table or something we can express in code like "in those categories". 
* NW: confirm with the Pools that its OK to do it (if 2 Pools use the same Models they will get the same settings)
* DEV: apply the change to prod DB. if we just set it to 1 day for all Models:
    ```ruby
    Model.update_all(maintenance_period: 1)
    ```

**Comment by nadjaweisskopf** [comment]
@eins78 correct, I tested it today too and it really seems to work well. BUT the weekends f.e. are not included in the caluculation of the days. @nimaai is already checking how to solve this problem so the weekends are not counted as maintenance days.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/c8c4922c1bd75ad2de6b5733e279cfe83db121db

UI still missing. Will be done at some later point in time.
