### ISSUE TITLE
Accessing and editing the user page 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#823]
As an adjustment to the current eidt user behaviour we said the user should 
- only be editable by the Admin
- should be accessible for all backend-users

We also need to think about the manually created users though. Until now lending managers could manually create new users. There is no such process as to request a new user by informing an Admin.

**Comment by nadjaweisskopf** [comment]
Should already be as described --> nw should test

**Comment by DrTom** [comment]
I believe this is effective now already. Needs testing.
