### ISSUE TITLE
Make finance fields visible in procurement

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#824]
#### Expected behaviour
- All finance fields (as shown in print screen) shall be visible for ALL users as soon as the inspection phase has started. 
- For the Admins the fields shall be editable in all phases, until the phase has ended. 
- As soon as the budget phase has ended, the fields are not editable anymore.

#### Actual behaviour
The fields are only visible to certain roles. After the budget phase has ended, the fields are not even visible to the Admin. 

#### Steps to reproduce
1. go to procurement as Admin
2. check a request from a budget phase which has ended
3. the finance fields are not visible

<img width="568" alt="Bildschirmfoto 2020-05-26 um 13 31 52" src="https://user-images.githubusercontent.com/3356016/82896811-dce1a280-9f56-11ea-8bd7-1e6510416e0a.png">

#### Specifications
- Leihs version: production
- Browser version: safari
- MySQL/PostreSQL version: current

**Comment by nimaai** [comment]
@nadjaweisskopf If I understood it correctly, I would specify it more:
```edn
:read (or (and requester own-request (or inspection-phase past-phase))
          category-viewer
          inspector
          admin)
```
meaning, that the finance fields are visible if:
* user is a requester viewing his own request AND the period is in inspection phase or past phase
* OR user is viewer of the request's category
* OR user is inspector of any category
* OR user is admin

**Comment by nadjaweisskopf** [comment]
@nimaai correct as mentioned above

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/1161c55d22861f5d51553e26b877a2461f2ccf30

**Comment by nadjaweisskopf** [comment]
@nimaai 
For the normal requester not all information is shown when the inspectio phase has started OR the budet period has ended. 

![Bildschirmfoto 2020-07-17 um 11 54 13](https://user-images.githubusercontent.com/3356016/87774244-93aa2280-c824-11ea-8c51-3f348ea1ad12.png)


![Bildschirmfoto 2020-07-17 um 11 54 33](https://user-images.githubusercontent.com/3356016/87774228-90169b80-c824-11ea-92ab-4e8e5ae77df5.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/6b04550e25d15be0f3467ed92d7a114b709dee8a
