### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#826]
Several labels are not translated

- Groups --> Gruppen
- Mail-Templates --> Mail-Vorlagen
- Manage Fields --> Felder verwalten

<img width="1000" alt="Bildschirmfoto 2020-05-28 um 09 39 12" src="https://user-images.githubusercontent.com/3356016/83112917-29e48680-a0c7-11ea-97a6-ce57d0b7fadb.png">

Related issue: https://github.com/leihs/leihs/issues/769

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f3c476fd66c1a10c6ba55443efe5fa881f06d22e
