### ISSUE TITLE
Change description of tab groups

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#827]
Can we change the description of the tab "groups".

[Group beschreibung.pdf](https://github.com/leihs/leihs/files/4695378/Group.beschreibung.pdf)

Relates to issue: https://github.com/leihs/leihs/projects/18

**Comment by DrTom** [comment]
https://github.com/leihs/leihs_legacy/commit/08fef417f4cbd7b679accc9f37914120801b5041
