### ISSUE TITLE
Enhance the category picker with the category tree

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#829]
**Background:** 
AV-Ausleihe is tidying up the inventory and verifying that the right categories are assigned. When picking the categories in the edit model page, they are not always certain, that they have chosen the right category. Either the category name always needs to contain the name of the main parent, as it has been done until now. Or we could also show the category tree. 

Current solution: 
**Edit model page**

<img width="502" alt="Bildschirmfoto 2020-06-02 um 09 11 20" src="https://user-images.githubusercontent.com/3356016/83491474-1dd73b00-a4b2-11ea-8969-ca0032ba05c8.png">

**Solution:** 
Could we introduce the same category picker as in the hand over page?

 
<img width="747" alt="Bildschirmfoto 2020-06-02 um 09 17 10" src="https://user-images.githubusercontent.com/3356016/83491508-2af42a00-a4b2-11ea-86f6-cd50aaed0f24.png">

**Comment by nadjaweisskopf** [comment]
@nimaai we will discuss this ticket again on thursday

**Comment by neoheat** [comment]
will be solved in https://github.com/leihs/leihs/issues/1806
