### ISSUE TITLE
Expanding and collapsing the category tree

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#830]
Instead of exporting the category tree to excel it would be enough to allow the user to expand or collapse the whole category tree. When expanded, the user then could search for categories by using Ctrl-F. Therefor we would not need to export to another tool. The whole use case could be covered in leihs. 

<img width="1016" alt="Bildschirmfoto 2020-06-02 um 09 21 02" src="https://user-images.githubusercontent.com/3356016/83491817-a3f38180-a4b2-11ea-9258-03830be15310.png">

**Comment by eins78** [comment]
@nadjaweisskopf funktioniert soweit. bin nicht sicher wie explizit die buttons sein sollen, was meinst du (die ohne text haben den als mouseover-tooltips)

---

<img width="1036" alt="Screen Shot 2020-06-29 at 16 58 32" src="https://user-images.githubusercontent.com/134942/86022078-2af03700-ba2a-11ea-8ec2-88e59756d4be.png">

---

<img width="1054" alt="Screen Shot 2020-06-29 at 17 00 03" src="https://user-images.githubusercontent.com/134942/86022096-2f1c5480-ba2a-11ea-898c-34548e315dbc.png">
