### ISSUE TITLE
Link to roles page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#832]
When accessing the link "Inventory-Pool-Roles" I would expect and want to be navigated directly to the edit page of the roles of this group. 

At the moment the link navigates to a page that is no use to the user. 
Link: 
<img width="1116" alt="Link" src="https://user-images.githubusercontent.com/3356016/83728519-c28a8180-a646-11ea-8a87-245a47f40ecb.png">

leads to following page: 
<img width="1312" alt="links to" src="https://user-images.githubusercontent.com/3356016/83728615-eea60280-a646-11ea-9fa5-cba505736957.png">

And should link to the following page in edit mode: 
<img width="1310" alt="final page to link to" src="https://user-images.githubusercontent.com/3356016/83728741-054c5980-a647-11ea-86f4-560f035b469d.png">

related issue: 
https://github.com/leihs/leihs/projects/18

**Comment by DrTom** [comment]
Can't do. There is no association to inventory-pool(s) here.
