### ISSUE TITLE
Enhance the filter

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#833]
As a lending mgr. or inventory mgr. I need to know which groups have access to my inventory pool. I need a filter which shows ALL groups which have access to my inventory pool, no matter which role is defined. 

Filters needed: 
- No Access
- Access (any role)
- customer
- group mgr.
- lending mgr.
- inventory mgr.

<img width="1315" alt="groups with roles" src="https://user-images.githubusercontent.com/3356016/83729166-928fae00-a647-11ea-9717-e0a4dcbb9e9e.png">

related issue: 
https://github.com/leihs/leihs/projects/18

**Comment by DrTom** [comment]
Needs a bit more engineering than just a few minutes.

**Comment by nadjaweisskopf** [comment]
Will move this issue to backlog

**Comment by DrTom** [comment]
https://github.com/leihs/leihs/commit/a3b3206469517275c2272f801b4a7c02fc556496

**Comment by nadjaweisskopf** [comment]
@DrTom It's not quite what would help the inventory-mgr. or lending mgr. The role "any" and "none" are nearly the same. They both don't really help because they show far too many pools. What the managers needs is a role saying "have access (any role)". The second role described in the list of the requirement above. So a filter, which shows all pools that have a role, no matter which one.
But still we can deliver the adjustment. It works fine.

**Comment by nadjaweisskopf** [comment]
@DrTom created a new ticket for the adjustment mentioned above https://github.com/leihs/leihs/issues/877
