### ISSUE TITLE
Link to direct roles

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#834]
When choosing the link "Direct Roles" on the user page, I would expect to be lead to the edit page of the direct roles - same as when pressing on the title "Direct Roles". 

Following link: 
<img width="957" alt="direct roles link" src="https://user-images.githubusercontent.com/3356016/83734156-e6ea5c00-a64e-11ea-9b21-a3daf00497a3.png">

Link leads to: 
<img width="1051" alt="roles for n w" src="https://user-images.githubusercontent.com/3356016/83734260-08e3de80-a64f-11ea-8f13-9b46fa0c8862.png">

I would expect it to lead to direct roles: 
<img width="971" alt="direct roles" src="https://user-images.githubusercontent.com/3356016/83734311-1ac58180-a64f-11ea-8e0f-44c0790d5e4b.png">

If we need this link to navigate to the current page, then we should rename it and solve the error msg. that appears, when changing the roles. As far as I understood this link is not meant for ZHdK-users. 

<img width="1313" alt="Bildschirmfoto 2020-06-04 um 10 46 27" src="https://user-images.githubusercontent.com/3356016/83735611-e2bf3e00-a650-11ea-87fa-0c1f96cd4f44.png">

**Comment by DrTom** [comment]
Done 

Post/Put request to Roles is deprecated. Now it can break depending on the permissions state. Did not fix this part.
