### ISSUE TITLE
Correct name

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#837]
In all calenders in the backend:

Rename "group" in description to "entitlements"
"Gruppen" to "Anspruchsgruppen"

https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/models/02d3c06e-7c77-5755-9492-58026032e879/timeline

<img width="857" alt="Bildschirmfoto 2020-06-04 um 11 34 31" src="https://user-images.githubusercontent.com/3356016/83740687-7ac02600-a657-11ea-9d4c-08b19e644fa3.png">

**Comment by nimaai** [comment]
same as #844
