### ISSUE TITLE
Rename page title

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#840]
Rename to Entitlement Group / Anspruchsgruppe

https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups

<img width="1028" alt="Bildschirmfoto 2020-06-04 um 11 42 10" src="https://user-images.githubusercontent.com/3356016/83741649-c32c1380-a658-11ea-84e6-2a6b8b1bc8b4.png">

**Comment by DrTom** [comment]
Done
