### ISSUE TITLE
Rename and translate success message

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#841]
Translate to "Anspruchsgruppe erstellt"
In English: "Entitlement Group created"

https://staging.leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/groups

<img width="1033" alt="Bildschirmfoto 2020-06-04 um 11 46 25" src="https://user-images.githubusercontent.com/3356016/83741950-1aca7f00-a659-11ea-8a92-df38811f85a8.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f8164dfc4a23d74c9547554fdc2de6db2e212c8e
