### ISSUE TITLE
Show matching contracts when searching for model

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#843]
#### Expected behaviour
If I search for a model in the list of visits (all / hand over / take back) I expect to find all hand overs and take backs, which contain the specific model at least once. 

#### Actual behaviour
The hand over or take back is not found. It seems only the name is relevant. 

#### Steps to reproduce
1. go to pool
2. go to visits
3. go to take backs or hand overs
4. search for a model by typing the model into the search field
5. nothing is found

#### Specifications
- Leihs version: 5.2.0
- Browser version: safari 
- MySQL/PostreSQL version: current

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/62e0141b45a4b84bc7b874f587884aa1fc01a6a6
