### ISSUE TITLE
Translations missing in calender

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#844]
The calender isn't translated to English. See printscreen: 

<img width="686" alt="Bildschirmfoto 2020-06-08 um 16 26 18" src="https://user-images.githubusercontent.com/3356016/84042062-e5999600-a9a4-11ea-817c-0a2c850a2d85.png">

1. go to Pool 
2. open timeline of a model in the english version of leihs
3. check calender translations - the texts are in German

**Comment by nimaai** [comment]
@nadjaweisskopf This would mean some work. Is it worth given it could be removed in future (as discussed)?

**Comment by nadjaweisskopf** [comment]
No, then let's leave it for now.
