### ISSUE TITLE
Rename success message when saving entitlement group

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#845]
Success message when saving an entitlement group should be changed to: 

"Entitlement Group saved"

<img width="1002" alt="Bildschirmfoto 2020-06-08 um 16 41 50" src="https://user-images.githubusercontent.com/3356016/84043831-1084e980-a9a7-11ea-8a33-807be77e9cd0.png">

Related issue: 
https://github.com/leihs/leihs/issues/769

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/f8164dfc4a23d74c9547554fdc2de6db2e212c8e
