### ISSUE TITLE
Don't show description text

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#846]
In the settings page of a pool, I would not show the description saying "Roles for Users and groups ....." because we now introduced a new tab called groups. And leihs users would want to change roles of users or groups via settings page. 

<img width="996" alt="Bildschirmfoto 2020-06-08 um 16 45 38" src="https://user-images.githubusercontent.com/3356016/84044347-bafd0c80-a9a7-11ea-9840-481e3131fcef.png">

Related issue: 
https://github.com/leihs/leihs/issues/769

**Comment by DrTom** [comment]
@nadjaweisskopf  Not sure what to do exactly. Remove the whole paragraph?

**Comment by DrTom** [comment]
Done
