### ISSUE TITLE
legacy availability API fix ?

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#854]
@eins78 wrote: 

I got a fatal error while writing the specs, not sure if still needed but it seemed like a general bug (treating `nil` like an Int)

https://github.com/leihs/leihs_legacy/commit/cd62881d0f6d145798e7d3cb405acab1b2527194

**Comment by nimaai** [comment]
I don't understand how you got a `nil`, because we already sanitize like you propose: https://github.com/leihs/leihs_legacy/blob/259ea5c1923d1fac9abd5d9a83a956cc5faa061a/app/models/availability/main.rb#L209

some steps to reproduce @eins78 ...?

**Comment by eins78** [comment]
> some steps to reproduce @eins78 ...?

iirc it was this spec: https://github.com/leihs/leihs-integration-tests/commit/51a8cfdc3aa2a7ebd3d490e64012854fee4e807d#diff-8362d0f663b41751162698f777fa5abd

I guess its because the scenario is so minimal, there are no workdays, holidays, at all so that would explain a `nil`, maybe.

**Comment by nadjaweisskopf** [comment]
ok to wait for Matus
