### ISSUE TITLE
leihs_external_hostname is undefined and install crash at [start_reverse_proxy : include_tasks] 

### ISSUE THREAD

**Issue by AnthonyHunt1** [leihs/leihs#856]
#### Expected behaviour
Clean install

#### Actual behaviour
Incremental upgrade from 5.0.1 -> 5.1.0 (and above)

#### Steps to reproduce
Clean install on Debian 9 LTS on vm's in a home environment (testing from home without access to work servers). I have set up both hosts in eachothers hosts files and local DNS appears working.

Set head for instance to 8a418d1f838007e5734d82eb0d3ff02242d2fc79.
install 5.0.1 through 5.0.4.
move instance head to 1c7db1290268e57e5180b7ed2d59d451a700a0f3

deploying via:
export LEIHS_HOSTNAME="leihs.example.com"
export LEIHS_HOST_USER="root"
export BOOT_AS_ROOT=yes
./scripts/deploy

all depoyments cease with the error:
TASK [start-reverse-proxy : include_tasks] *********************************************************************************************************************************************
fatal: [192.168.1.172]: FAILED! => 
  msg: '''leihs_external_hostname'' is undefined'

**Comment by AnthonyHunt1** [comment]
This has something to do with the export LEIHS_HOSTNAME="leihs.example.com" variable.  As far as I can tell, it occurs if there is a problem with certificates or you are running without them? There is an option to not redirect to secure in the settings but what is the point if the install cannot complete without certificates?

Tested extensively on Debian 9 LTS at releases 5.1.1, 5.1.2, 5.1.3 & 5.1.10.

**Comment by eins78** [comment]
> This has something to do with the export LEIHS_HOSTNAME="leihs.example.com" variable.

some clarification: exporting the env vars like `LEIHS_HOSTNAME` is only needed for the example commands like from the GUIDE.md that you run directly in your shell. getting a cert from letsencrypt is one of those steps.

When `leihs_external_hostname` is undefined it's really missing in the ansible config – that should be in the `host_vars` created when setting up `leihs-instance` (not the settings file, so it's not the same problem as https://github.com/leihs/leihs-instance/issues/5).
Check the `host_vars` file in `./host_vars/${LEIHS_HOSTNAME}.yml`, should have the correct hostname on top.
