### ISSUE TITLE
Question regarding authentication and user management

### ISSUE THREAD

**Issue by linearlyIndependent** [leihs/leihs#857]
After evaluating multiple options, I have deployed Leihs in my department for inventory management and lending. Overall, we are impressed by the offered functionality and the polished state of Leihs.
However, I have some questions and uncertainties regarding authentication and user management, I hope you can clarify some things for me.

I saw that LDAP authentication was removed in favor of external authentication systems. If I understand correctly, Leihs redirects the user to our self-developed authentication system with a JWT containing the user supplied authentication information. Our system then could authenticate the user based on our LDAP or redirect to the SAML, OAuth, etc. service which then redirects with the result to our system. Our system then redirects the user back to Leihs with the authentication result contained in a JWT to Leihs.

If I understand correctly, in Leihs 4, the user was automatically created in case of LDAP authentication if it did not exist in the Leihs database ([ldap_authentication_controller.rb](https://github.com/leihs/leihs_legacy/blob/v4-master/app/controllers/authenticator/ldap_authentication_controller.rb)). As I understand, in Leihs 5 this has changed also since the external authenticator handles only the authentication. What are the possible ways to add users of LDAP groups to Leihs, what options does Leihs provide for this or what would be a possible solution based on your experience?

#### Specifications
- Leihs version: 5.1.10
- Browser version:
- PostreSQL version: 10

**Comment by eins78** [comment]
> What are the possible ways to add users of LDAP groups to Leihs, what options does Leihs provide for this or what would be a possible solution based on your experience?

You understood correctly. The recommended way to get the users into leihs is to implement a sync job from your users db (i.e. LDAP) to leihs via the Admin-API (see wiki: https://github.com/leihs/leihs/wiki/Admin-API).

At the ZHdK, a sync job runs nightly to manage add/remove/update all the relevant users, groups and group membership of users.
You can take a look at the source code of this, although it is highly specific to our environment: https://github.com/leihs/zhdk-sync

For working with the Admin-API, its good to know that the Admin UI uses the same (REST) API internally – the recommended workflow is to do what you want to achieve in the UI, have a look at the request it does and then automate it.
