### ISSUE TITLE
Lack of documentation how to setup external auth

### ISSUE THREAD

**Issue by Bekman553** [leihs/leihs#858]
Hi,

it would be nice to have more detailed documentation how to setup external authentication (my case is azure ad).

I successfully installed azure ad plugin but now I have no idea what to do next.

Anyone can give me some clue how to setup this in the ui?
Thanks.

**Comment by eins78** [comment]
Because the configuration depends on your specific use case and the external authentication adapter that is used, there is no general documentation but rather a general explanation:
https://github.com/leihs/leihs/wiki/external_authentication

You can find the Admin UI to set it up here (needs system admin permissions), see some example value below: https://leihs.example.com/admin/system/authentication-systems/add

<img width="687" alt="Screen Shot 2020-07-14 at 15 56 22" src="https://user-images.githubusercontent.com/134942/87434340-a0dbcd00-c5ea-11ea-8be9-d8b0cb0752fe.png">

**Comment by Bekman553** [comment]
Thank you for your answer. Sorry to have stupid questions, I don't have much experience with azure ad. Where can I get this "external_sign_in_url"? I registered my app in azure ad, uploaded certificate with public key, but when I'm trying to enter urls from azure endpoints nothing works. Thank you.

**Comment by AnthonyHunt** [comment]
I too am about to connect to AD.  It would be useful to update the documentation with some examples.  For instance, I've just realised (or found out from this post) that you need to include "----BEGIN PUBLIC KEY----" in the key fields.  I presume this is the same for the inventory file?

Also agree with Bekman553 about the AD connector.  Without this post we wouldn't know there was a sign-in url to visit.

I understand that its all being developed and the use case may vary, but even as a long time user/deployer this has been a very undocumented upgrade path.

**Comment by Bekman553** [comment]
Hi,
yes, you must include ----BEGIN PUBLIC KEY---- and -----END PUBLIC KEY----- in inventory file. It has to look like this:

all:
 hosts:
  localhost:
...
   adl_private_key: |
    -----BEGIN EC PRIVATE KEY-----
    my-private-key
    -----END EC PRIVATE KEY---

Be careful about indentation. Otherwise you will end up with openssl error like "short header".

Could you please help me with the sign-in and sign-out url? Like I said. I don't have experience with open-id so I have no idea where to look.

Thnak you,

Martin

**Comment by eins78** [comment]
> Where can I get this "external_sign_in_url"? I registered my app in azure ad, uploaded certificate with public key, but when I'm trying to enter urls from azure endpoints nothing works.

The "external_sign_in_url" is the URL of API endpoint that your app provides, it depends on you registered/deployed it in azure.

**Comment by eins78** [comment]
> For instance, I've just realised (or found out from this post) that you need to include "----BEGIN PUBLIC KEY----" in the key fields. I presume this is the same for the inventory file?

Yes, the keys should be in ["PEM"](https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail) format as stated here: https://github.com/leihs/leihs/wiki/external_authentication_keys

As @Bekman553 said this is whitespace-sensitive. To avoid issues in YAML one option is to "JSON-stringify" it first:

```yaml
some_key: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2fUb1On9Xnnjf8V1AzakbqiA9SOo\nUCO8mUZa+7742fXqjxToTSvWgcO0skT5oZWrE/axWRwXiC7mumlmb12Oag==\n-----END PUBLIC KEY-----\n"
```

**Comment by AnthonyHunt** [comment]
Thanks folks! very helpful!!

I'm guessing that when deploying to the same host as LEIHS the public keys will be the same?

**Comment by AnthonyHunt** [comment]
I think I have this set up? but how can I test authentication is working? Will my old v4 users get updated to Azure when the login the first time? or do I need to move them?

**Comment by AnthonyHunt** [comment]
Ok, the setup so far... I'm deploying the service to the same host as leihs which is a different host where I'm deploying from.

I have deployed aad-authentication with the values (sanitised but full urls, keys and ids):
`all:
  hosts:
    leihsv5-01.url:
      adl_external_base_url: "https://leihsv5-01.url"
      adl_tennant: "id"
      adl_client_id: "id"
      adl_email_attribute: "13"
      adl_leihs_public_key: "-----BEGIN PUBLIC KEY-----\nPublicKey\n-----END PUBLIC KEY-----"
      adl_private_key: "-----BEGIN EC PRIVATE KEY-----\nPrivateKey\n-----END EC PRIVATE KEY-----"
      adl_public_key: "-----BEGIN PUBLIC KEY-----\nPublicKey\n-----END PUBLIC KEY-----"
`
I've set up LEIHS with:

id: aad
name: Azure Auth
type: external
priority: 1
Internal private key: as above
internal public key: as above
external public key: as above
external sign-in url: localhost/authenticators/ms-open-id/sign-in
external sign-out url: localhost/authenticators/ms-open-id/sign-out

I have entered a route to the reverse proxy

when I go to leihsv5.url/authenticators/ms-open-id/sign-in I get 
Unspecified Error in PHZH Open-ID Authentication Service

Thoughts?

**Comment by AnthonyHunt** [comment]
I think I'm getting the error as I'm directly going to the URL.  How can I convert my existing users that were LDAP to the new AD?

Anyone else have a script for syncing AD users?

**Comment by Bekman553** [comment]
Hi,

thank you for the tips. Done that but now I'm ending in Azure's "AADSTS90102: 'redirect_uri' value must be a valid absolute URI." error.

My deployment procedure:

Leihs deployed with proxy settings:
reverse_proxy_custom_config: |
ProxyPass /authenticators/ms-open-id http://localhost:3434/authenticators/ms-open-id nocanon retry=0

Keys generation:
 - Private key: openssl ecparam -out ec_key.pem -name prime256v1 -genkey
 - Public key: openssl ec -in ec_key.pem -pubout -out public-key.pem
 - Certificate for Azure AD: openssl req -new -key ec_key.pem -x509 -nodes -days 365 -out cert.pem
Public key used as both: internal and external.

My Azure AD setup:
- Registered new Azure AD application: Azure AD->App registrations->New registration
- Manage->Authentication–>Web–> Redirect uri: https://leihs.mydomain.cz
- Certificates and secrets - uploaded cert.pem

Deployment:
 - git clone https://github.com/leihs/azure-active-directory-leihs-authentication-system.git
 - hosts vars: 
   - adl_external_base_url: leihs.mydomain.cz
   - adl_tennant: auzre-ad-tenant-id
   - adl_client_id: Copied from Azure AD app->Overview->Application (client) ID
   - adl_email_attribute: mail
   - adl_private_key: |
     -----BEGIN EC PRIVATE KEY----
     key
     -----END EC PRIVATE KEY-----
  - adl_leihs_public_key: |
    -----BEGIN PUBLIC KEY-----
    key
    -----END PUBLIC KEY-----
  - adl_public_key: |
    -----BEGIN PUBLIC KEY-----
    key
    -----END PUBLIC KEY-----
 
Created new authentication system:

Name: azure ad
Check enabled, send email
internal private key: -----BEGIN EC PRIVATE KEY----- key -----END EC PRIVATE KEY-----
internal public key: -----BEGIN PUBLIC KEY----- key -----END PUBLIC KEY----
external public key: -----BEGIN PUBLIC KEY----- key -----END PUBLIC KEY----

external_sign_in_url: http://leihs.mydomain.cz/authenticators/ms-open-id/sign-in
external_sign_out: http://leihs.mydomain.cz/authenticators/ms-open-id/sign-out

Any help?

**Comment by AnthonyHunt** [comment]
I had that too. It’s because the “hostname” field in settings doesn’t have “https://“ in it. I posted a separate issue for this.


Anthony Hunt
Senior Technical Coordinator - Digital Arts Centre
a.hunt@worc.ac.uk | 01905 855320 | EE1086 Edward Elgar


University of Worcester | Henwick Grove | Worcester | WR2 6AJ

For further information about opportunities to study at the University of Worcester please visit our website https://www.worcester.ac.uk

“This email and any files attached are confidential and intended solely for the addressee. If you have received this email in error please notify the sender immediately and destroy all copies. Any views or opinions expressed in this email or attached files are solely those of the individual and not necessarily those of the company. The recipient should check this email and any attachments for the viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.”

________________________________

**Comment by Bekman553** [comment]
I just tired to set external and sign-in and sign out to: 
https://leihs.mydomain.cz/authenticators/ms-open-id/sign-in
external_sign_out: https://leihs.mydomain.cz/authenticators/ms-open-id/sign-out
no change.

**Comment by Bekman553** [comment]
I've got this on testing environment so my Leihs instance is not accessible from public internet. Could that be the reason?

**Comment by AnthonyHunt** [comment]
Ummm, possibly? I found that the url in the address bar was missing the https. When I added this it work as expected. I guess if it’s not an accessible return address  the callback could be an issue? But don’t think you’d get this message? Unless it’s checking external dns?

I found that, like your other issue with the route, that the setting hostname didn’t contain “https”. And that I needed to set this seperatly in host_vars.

**Comment by Bekman553** [comment]
Well, I'm one step further. I exposed my Leihs instance to public net, changed external_base_url to https:// and it seems to be OK. But now I'm getting:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application
What is your redirect url in Azure? I tried to enter:
 https://leihs.mydomain.cz
 https://leihs.mydomain.cz/authenticators/ms-open-id/sign-in
 https://leihs.mydomain.cz/sign-in/external-authentication/azure/request/

nothing works.

**Comment by AnthonyHunt** [comment]
Have a look in the url address bar... this will give you an idea of what LEIHS is sending as the return url. You’ll have to “de-hex” it of course.... for me, LEIHS was sending the url minus “http” or “https” and I had to add it to the “hostname” field in settings.

**Comment by Bekman553** [comment]
So I've got it finally working!

The redirect url must look like this:
https://leihs.mydomain.cz/authenticators/ms-open-id/callback

Thank you guys for help.
