### ISSUE TITLE
New Borrow: Link between Desktop and Mobile version

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#859]
> issue to document the current state and track the discussion on how we want to roll out the mobile version of borrow.

---

URLs look like this. "switching" between them is only done by following links (no cookie, no automatic redirects, etc). 
That also means I can use old and new in 2 tabs in the same browser at the same time.
* old/desktop: `leihs.example.com/borrow/`
* new/mobile: `leihs.example.com/app/borrow/`

---

- link to mobile from desktop version
  - **A**. only when small screen with a banner on top (already done)
  - **B**. always: in the footer next to language selection (not done yet)

- link to desktop from mobile
  - **C**. in the main "app" menu (not done yet)

--

example for **A**:
<img width="434" alt="Screen Shot 2020-07-14 at 12 40 35" src="https://user-images.githubusercontent.com/134942/87417696-db387080-c5d0-11ea-9b86-56fd09f31ddf.png">

example for **B**:
<img width="1072" alt="Screen Shot 2020-07-14 at 12 43 15" src="https://user-images.githubusercontent.com/134942/87417748-ebe8e680-c5d0-11ea-9cd1-ee5afbc21d56.png">

**Comment by nadjaweisskopf** [comment]
we need to decide if we show the link to new borrow depending on your desktop size.

**Comment by eins78** [comment]
I propose to following inventory settings so the details can be decided at deploy-time.

* [x] `LEIHS_DEPLOY_NEW_BORROW_APP`: if the new borrow app should be installed at all (all other settings are only applied if this is turned on)
* [ ] `NEW_BORROW_APP_SHOW_LEGACY_MOBILE_BANNER`: turn on to show the message with link (only on small screens) in the legacy "borrow" app
* [ ] `NEW_BORROW_APP_SHOW_LEGACY_MENU_ENTRY`: turn on to add a link to mobile app in the main menu of all legacy apps
* [ ] `NEW_BORROW_APP_SHOW_LEGACY_FOOTER_ENTRY`: turn on to add a link to mobile app in the footer  of all legacy apps

**Comment by eins78** [comment]
<img width="324" alt="Screen Shot 2022-03-31 at 12 50 38" src="https://user-images.githubusercontent.com/134942/161075739-2b0feb6d-b8e8-4666-8666-dccede5debb9.png">

--

<img width="346" alt="Screen Shot 2022-03-31 at 10 04 54" src="https://user-images.githubusercontent.com/134942/161075746-c1ab2ba9-0c91-4e67-9cfe-64941f6fd5ef.png">

--

**Comment by eins78** [comment]
notes:
* text needs to be translated as well
* banner is shown on every (old borrow) page, not just the homepage

**Comment by eins78** [comment]
* banner is done, with translations. text can still be enhanced (has "new" 2 times in 1 sentence)
* for 'redirect to new borrow by default' the toggle is prepared, but its not implemented. the after-login redirect code is kind of brittle see https://github.com/leihs/leihs/pull/1120

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/8a8c43182c04f2c9081bfa208f0e2ac5baab2115
