### ISSUE TITLE
Wrong logout address

### ISSUE THREAD

**Issue by Bekman553** [leihs/leihs#862]
#### Expected behaviour
After logout user is redirected to correct address.

#### Actual behaviour
User is redirected to non-existing address looking like this:
leihs.example.com/leihs.example.com

After logout log says:
ActionController::RoutingError (No route matches [GET] "/leihs.example.com"):

#### Steps to reproduce
Fresh install of Leihs 5.1.10 with local user. User login and logout.
Two instances tested: One on Ubuntu 18.04 and one on Debian 9.12.

#### Specifications
- Leihs version: 5.1.10
- Browser version: Safari 13.1.1 and Chrome 83.0.4103.116
- MySQL/PostreSQL version: 10.13 (installed via Ansible deployment)

**Comment by Bekman553** [comment]
There is wrong default logout address. You can workaround it by setting "/" as external logout url in password authentication setting.

**Comment by AnthonyHunt** [comment]
I had this problem too.  If you go into the "Admin" settings and check the "hostname" field. Make sure this is fully qualified.

**Comment by AnthonyHunt** [comment]
Have you managed a script for syncing to AD?

**Comment by Bekman553** [comment]
I don't even got working AD login. I really don't have any experience with Azure AD login so I got stuck in login endpoint address. So If you have some step-by-step tutorial I will appreciate this :)

**Comment by AnthonyHunt** [comment]
Have a look at these issues I raised and solved....

https://github.com/leihs/leihs/issues/858#issuecomment-660368197

https://github.com/leihs/azure-active-directory-leihs-authentication-system/issues/8

This should get you AD working.

**Comment by AnthonyHunt** [comment]
I've submitted a separate issue for this as well. It appears that once deployed the settings/hostname can be changed to include https:// and further deployments will work fine.

https://github.com/leihs/leihs/issues/872

**Comment by eins78** [comment]
This was fixed in the template https://github.com/leihs/leihs-instance/commit/9a0f4802e7fe9aed87b3e3df5b2fcdc616ba025a
To

**Comment by eins78** [comment]
This was fixed in the template https://github.com/leihs/leihs-instance/commit/9a0f4802e7fe9aed87b3e3df5b2fcdc616ba025a

To apply it to your existing instance-repo, edit the settings file (`settings/${LEIHS_HOSTNAME}.yml`) by prefixing the `external_base_url` with `https://`.
