### ISSUE TITLE
Lending Booking Calendar: group selection has duplicates

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#864]
Steps:
* In Lending, serach for a User
* Select "Handover"
* In Add/Assign, Search for "Stativ GorillaPod" and add this Option to the Handover
* In the new line for "Stativ GorillaPod", click on "Change Entry"
* In the opened BookingCalendar, open Dropdown "Availability"

Bug: Shows many duplicates.
Should: Show only 1 Entry per Group (id).
I suspect a `DISTINCT` is missing from a query.

<img width="668" alt="Screen Shot 2020-07-17 at 12 38 46" src="https://user-images.githubusercontent.com/134942/87783418-afb5c000-c834-11ea-9f50-7c3351289aaa.png">

**Comment by nadjaweisskopf** [comment]
@eins78  which visit did you open? I couldn't find any duplicates in the ones I opened.

**Comment by eins78** [comment]
I added the example I've found to the steps, see above. The Bug has to do with the connection between Model/Option and Groups, so it only occurs if there are any. It also might only occur with Options (both examples we found are Options).

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ed225ca3c128d674233c7093852f963f2dc5bcae

**Comment by neoheat** [comment]
tested positive
