### ISSUE TITLE
Opening the categories in borrow section takes too long

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#865]
Please check if we can speed up the UX when opening the list of items after chosing a category such as Audio. 

#### Expected behaviour
I would expect to see the list of items after klicking on a category picture in borrow section after appr. max. 7 seconds

#### Actual behaviour
At the moment category AUDIO takes > 35 seconds, which is far too long. 
The AV-Ausleihe think it has to do with the assignments to different categories - the nesting of categories. The AV-Ausleihe went over all assignments. Opening the list of items was always slow but now it's extremely slow. Could the categories be a reason for the slowness?

#### Steps to reproduce
1. go to borrow
2. open category AUDIO
3. wait for a long time

#### Specifications
- Leihs version: 5.2.0
- Browser version: safari / opera
- MySQL/PostreSQL version: newest

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/b022e182bc3e7acd8e15246845dcc9d5d909e004

Done. Pretty quick now.

**Comment by nadjaweisskopf** [comment]
@nimaai it's much quicker now. What we still have is a strange behaviour with loading the pictures (productive and on staging with this release). But I'll create an own ticket for this.
