### ISSUE TITLE
Script for creating users/group from Active Directory AD

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#868]
There's been some recent activity from users deploying using Active Directory (me being one). My final hurdle in this process is ingesting users from AD.  I have looked at the "sync" example for ZHdK but this means very little.

Does anyone have any suggestions or examples?

**Comment by DrTom** [comment]
The new API interface - and in this case particular anything under `/admin/users/` - serves both as a user faced frontend and as an API. Just open the dev console in your browser, open the "Network" tab, start doing stuff like creating, updating, and deleting users and you will get an idea how to use the API. Data is always send as JSON, HTTP verbs are used as you would expect.

**Comment by AnthonyHunt** [comment]
Thanks for the reply. I've literally just posted an issue about the lack of documentation... It's a shame that this part of the process has become more complicated, especially for those that aren't current in multiple programming/web languages. But I of course understand that ZHDK priorities have to come first.
