### ISSUE TITLE
PSQL Help Needed - Move existing users into V5.1.10 "authentication_systems_users"

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#869]
v5 deals with users in a different way. Whilst I await being able to bulk ingest new users in to db I need to bulk move the current users into the database.  I can do this individually by doing this on the client:

psql
\c leihs
select id from users where email='emailaddress';
insert into authentication_systems_users (user_id,authentication_system_id) values ('id from above','aad');

How can I do this for ALL users in the users table?  Yes, I know about the initial admin and local users but I can change those back to 'password' manually... I don't want to manually insert 600 odd users.

Are there any dangers to be aware of here?

**Comment by AnthonyHunt** [comment]
I moved all my users to the authentication_systems_user with the psq:

psql
\c leihs
insert into authentication_systems_users (user_id,authentication_system_id) select id,'aad' from users;
\q

I'd still like to know if theres any other changes I should make?

**Comment by eins78** [comment]
> I'd still like to know if theres any other changes I should make?

It looks like you're only using password authentication for all users (no external authentication systems). If so, there is nothing more to configure if all the users have `password_sign_in_enabled` set.
Note that when upgrading from before 5.1.x all passwords will be reset, so you should inform your users of the new passwort-reset-by-email functionality so they can set a new password for themself.

**Comment by AnthonyHunt** [comment]
They were actually v4 LDAP users. And will be updated from the AD-LDAP with v5. Should I unset password_sign_in_enabled for external users?
