### ISSUE TITLE
Delegation without name and responsible person

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#871]
Should not be possible:

https://github.com/leihs/leihs_legacy/blob/031344b7951db155324b97484bc7c0995bb4a7ec/app/models/user.rb#L11-L13

but it is:
```
select distinct(id)
from users
join delegations_users du on du.delegation_id = users.id
where firstname is null and delegator_user_id is null;

                  id
--------------------------------------
 2249ce71-136d-4071-974c-2c563a1ed8ec
(1 row)
```

- [ ] release notes

**Comment by nimaai** [comment]
There is one contract for this delegation: https://leihs.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/contracts/ca67f394-6b39-4862-bdd7-a90971d6aad5

Email has been written to the respective person for more information. Waiting for the reply.

**Comment by eins78** [comment]
merge needs fixes wrt bundler. wip: https://github.com/leihs/leihs_legacy/commit/9d1719b8e2e01078486e7fd3c22ee1c5ca109f2a

**Comment by eins78** [comment]
doen in https://github.com/leihs/leihs/commit/aabe02460928eadcd37c1d570266abc6ce7dca33
