### ISSUE TITLE
Documentation for Admin API

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#875]
I'm trying to write a script to sync users (in PHP as its something I'm partly familiar with).  The admin API and the example have little comments or explanation.

When adding a user, does LEIHS check if the record already exists? and switch to update record?

What are the URL's to add/update/disable a user? eg: https://server.com/admin/users/new and how are they called? how is the user passed to the api/url? Post?Get?

What's returned? and how?

**Comment by DrTom** [comment]
https://github.com/leihs/leihs/wiki/Admin-API

**Comment by AnthonyHunt** [comment]
This does not answer the questions i asked? This is a bit like being told "you house has electricity, stick your fingers in the socket and figure out how it works".

Can you at least explain how new users vs modifying a user is done? What is the process? Does LEIHS check for the existing user and switch to update? if not? how do we check for the existing user?

Please? this is a difficult enough process as it is.

**Comment by AnthonyHunt** [comment]
can someone explain why this script gives "connection failure"?

`<?php

$token = 'JT3MV6UIBS3G2HLAXO3JR3OTYCL764DI';
$headr = 'Authorization: Token ' . $token;
$url = 'https://leihsv5-01/admin/users/b2c72cd8-a69a-58cd-80bd-1d6581e63cd7';

function callAPI($method, $url, $data, $headers = false){
   $curl = curl_init();
   switch ($method){
      case "POST":
         curl_setopt($curl, CURLOPT_POST, 1);
         if ($data)
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         break;
      case "PUT":
         curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
         if ($data)
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);			 					
         break;
      default:
         if ($data)
            $url = sprintf("%s?%s", $url, http_build_query($data));
   }
   // OPTIONS:
   curl_setopt($curl, CURLOPT_URL, $url);
   if(!$headers){
       curl_setopt($curl, CURLOPT_HTTPHEADER, array(
          'Content-Type: application/json',
       ));
   }else{
       curl_setopt($curl, CURLOPT_HTTPHEADER, array(
          'Content-Type: application/json',
          $headers
       ));
   }
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
   curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
   // EXECUTE:
   $result = curl_exec($curl);
   if(!$result){die("Connection Failure");}
   curl_close($curl);
   return $result;
}

$data = array(
	'address' => null,
	'email' => 'abak1_15@blah,
	'contracts_count' => 117,
	'img32_url' => null,
	'account_enabled' => true,
	'lastname' => 'Alak1',
	'phone' => null,
	'img_digest' => null,
	'org_id' => 'ABAK1_15',
	'extended_info' => array('id' => '15008234', 'mifare' => '222621212923242525', 'barcode' => '049053048048056050051052052000', 'modules' => 'DFPR3103 DFPR3105 DFPR3106 JOIN3002 SCRN3004 SCRN3005 SCRN3006'),
	'city' => null,
	'is_admin' => false,
	'login' => null,
	'updated_at' => '2020-07-14T15:26:50.356Z',
	'firstname' => 'Klan',
	'zip' => null,
	'id' => 'b2c72cd8-a69a-58cd-80bd-1d6581e63cd7',
	'url' => null,
	'password_sign_in_enabled' => true,
	'badge_id' => '15008234',
	'img256_url' => null,
	'inventory_pool_roles_count' => 3,
	'country' => 'GB',
	'created_at' => '2015-09-29T17:10:59.000Z'
);

$make_call = callAPI('PUT', $url, json_encode($data), $headr);
$response = json_decode($make_call, true);
$errors   = $response['response']['errors'];
$data     = $response['response']['data'][0];

echo $response;
echo $errors;
echo $data;

?>`

**Comment by AnthonyHunt** [comment]
My script issue above is fixed. However I need to raise a new issue.
