### ISSUE TITLE
Show more than one model picture

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#879]
When editing a model, only one picture is shown. 
It should be possible to switch between the different pictures of a model.

**Comment by nadjaweisskopf** [comment]
look and feel / online shops etc.

**Comment by eins78** [comment]
done 
<img width="487" alt="Screen Shot 2021-08-05 at 15 47 19" src="https://user-images.githubusercontent.com/134942/128360855-2e074d5e-fb96-4eaf-9db3-a242132b16f0.png">
