### ISSUE TITLE
Error in orders

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#881]
How to reproduce: 
1. go to orders
2. chose an order
3. go back and chose a klick on a second order
4. --> error 

<img width="123" alt="image" src="https://user-images.githubusercontent.com/3356016/89889516-044d2080-dbd2-11ea-8841-cd39c23abaa5.png">

**Comment by nimaai** [comment]
Cannot be reproduced anymore. Might have had something to do with storing the errors in localstorage, which was solved by now.
