### ISSUE TITLE
category view: model name should link to model page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#882]
The edit page should be opened instead of a list of models. 

How to reproduce:
1. chose a category
2. klick on the text of a model 
3. I am lead to a list of models 
4. I would expect to see the edit page of the chosen model

**Comment by eins78** [comment]
- thumbnail has correct link
- text has wrong link

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/8f5922a3c261a4e9fe80be6dc48736136de3d520

**Comment by nadjaweisskopf** [comment]
ca. 3 iterations
