### ISSUE TITLE
Waiting for search results to be loaded

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#883]
It seems an overkill to have to wait for the search result again after I have edited a model and am navigating back to the model list. According to our discussion this is of course because the availability could have changed in the mean time and the search results need to be listed again. 

@eins78 had something in mind which could help though - having a window which is overlapping the search results. But we said we would wait for this request to be done until we finish off all that needs to be done otherwise.

**Comment by eins78** [comment]
@nimaai in the meantime we should cache the search results better. easy to do, remove the line of code that clears the key from the app-db. we re-fetch in the background anyhow.
bonus: we can distinguish between dispatching the search action from a navigation event or when clicking the search button – when clicking the button it is ok to clear the result, user expectation is to get fresh results.

**Comment by nimaai** [comment]
@eins78 In this case we don't clear the results from the app-db. We should just disable showing the loading icon.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/a2def46f1009bf4ea1325728dbe22117ff2e08f3

**Comment by nimaai** [comment]
IMPORTANT: scope the search results according to the filter params used as query variables.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/a68160292b29ab38a301a42729cd6c5e699995ce
