### ISSUE TITLE
booking calender

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#884]
1. https://github.com/leihs/leihs/issues/966
2. issue: If the given amount is higher than the max. available amount, then the user should not be able to klick on the order button.

-> https://github.com/leihs/leihs/issues/554

* don't crash if end date before start data

**Comment by nadjaweisskopf** [comment]
Features of booking calender: 

- view name of item
- Toggle month
- set start and end date
- set amount
- chose pool
- view max available amount
- view weekdays
- view holidays and closed days
- view current day
- close calender
- add to cart
- view error msg. if 
    - pressing on closed days or holidays
    - amount is not available

**Comment by nadjaweisskopf** [comment]
Next step:
- merge all steps
- improve data loading
- check performance

**Comment by eins78** [comment]
performance regression when enabling scrolling could not be solved, we'll disable it for the time beeing (as already in the `DatePicker` in Admin)
