### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#890]
We said we would use the translation concept of procurement. It's easy to implement and easy to use. If we need a better translation system in future then not much harm has been done.

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs-borrow/commit/c5829b84b8a2dda8d82a8a3cce8ca754e30d6646

**Comment by nadjaweisskopf** [comment]
Next steps: 
- decide how the translations are done - same as Procurement?
