### ISSUE TITLE
Set a purpose per line in a hand over

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#891]
#### Abstract
Purposes are set by the users before sending an order. A hand over can contain different orders and therefore different purposes. The purpose of an order is shown on each line. If the lending mgr. adds a model or an option to a hand over, he would like to add a purpose to this line.

There are two different ways, how to implement this requirement:

1. solution appr. 5 days dev.
<img width="781" alt="Bildschirmfoto 2020-08-11 um 15 34 47" src="https://user-images.githubusercontent.com/3356016/89903736-526d1e80-dbe8-11ea-8c46-076de77d432d.png">

2. solution appr. 4 weeks dev.
<img width="957" alt="Bildschirmfoto 2020-08-11 um 15 34 42" src="https://user-images.githubusercontent.com/3356016/89903688-3f5a4e80-dbe8-11ea-86a4-f1961b6ea770.png">

We will start with the first solution and see how it they manage in production.

**Comment by eins78** [comment]
Plan: in handover, when lines are selected that have no purpose yet, the selection menu will have an "add purpose" option. We can then decide if we also want to support editing a single line as well.
The UI can reuse existing parts from "handover" and "edit order".

--
menu with new option:

<img width="1118" alt="Screen Shot 2020-08-11 at 16 27 37" src="https://user-images.githubusercontent.com/134942/89910198-3ec5b600-dbf0-11ea-98d9-c8b9d9428726.png">

---
dialog to be reused:

<img width="1098" alt="Screen Shot 2020-08-11 at 16 27 52" src="https://user-images.githubusercontent.com/134942/89910215-41c0a680-dbf0-11ea-901c-fc30f0f8977b.png">

**Comment by eins78** [comment]
`reservations` now have a `line_purpose` field in the DB which can be edited from handover page.
we should not forget to include them in any contracts as well.

**Comment by eins78** [comment]
There are now 3 different "speech bubble" icons: 
1. Line has no Order and no Purpose
2. Line has no Order but custom Purpose
3. Line belongs to Order (with Purpose)
<img width="1000" alt="Screen Shot 2020-08-12 at 11 50 44" src="https://user-images.githubusercontent.com/134942/90001766-23ab8280-dc92-11ea-838e-4984272f6c1b.png">

**Comment by eins78** [comment]
@nadjaweisskopf @nimaai steps:

```
Open handover view
Add several Items and Options
Select 1 Item line
Open the main dropdown menu and click "Edit Purpose"
Enter Purpose into Modal and Save
Select another Item Line and likewise add different purpose
Select all Item lines
Open the main dropdown menu and click "Edit Purpose"
The text field has a list of all different purposes from the lines 
```

**Comment by eins78** [comment]
* added line-purposes to contract when doing the handover
* removed "empty" speech-bubble-icon when no purpose

**Comment by nadjaweisskopf** [comment]
1. Received following error when deleting my purpose and placing a space instead. Deleting the purpose again and not setting a purpose at all does not work in that case. This is an edge case but we might want to check that it' s possible. 

<img width="720" alt="Bildschirmfoto 2020-08-20 um 11 04 35" src="https://user-images.githubusercontent.com/3356016/90750507-2c750780-e2d5-11ea-9a6d-ccc4b0bd6320.png">

2. In the take backs the bubble is always light grey, as if the comment were entered by me, even if it was entered by the student.

3. The stakeholder would like to differentiate the colours of the bubbles (comment by student and my comment) more. If we stick to greay, then we could chose a lighter grey?

Other then that everything works fine.

**Comment by eins78** [comment]
> 2. In the take backs the bubble is always light grey, as if the comment were entered by me, even if it was entered by the student.

In the takeback view, only the **Contract** purpose is shown. When a Handover is finished, all purposes are combined (from customer's Order, Handover Lines, and extra contract purpose if entered. After this step we can not distinguish anymore where the content came from. We can show the dark icon though, to be more consistent which handover view.

**Comment by eins78** [comment]
> 1. Received following error when deleting my purpose

Deleting the Purpose(s) from the lines by leaving the field empty is now possible (with an empty field as well as just space(s))

> 3. The stakeholder would like to differentiate the colours of the bubbles (comment by student and my comment) more. If we stick to greay, then we could chose a lighter grey?

Icon is now lighter grey 

<img width="957" alt="Screen Shot 2020-08-20 at 12 45 11" src="https://user-images.githubusercontent.com/134942/90761051-18d09d80-e2e3-11ea-9504-c3df15e2c0b8.png">

We _could_ also flip the icon. It is easier to distinguish, but I find that it looks weird, so I left it out.

<img width="954" alt="Screen Shot 2020-08-20 at 12 46 24" src="https://user-images.githubusercontent.com/134942/90761490-c479ed80-e2e3-11ea-90ac-077461261e0e.png">

**Comment by nadjaweisskopf** [comment]
1. ok, I will retest

2. ok as described

3. I would say we use the flipped icon. Inform me as soon as I can retest.

**Comment by nadjaweisskopf** [comment]
@eins78 everything works well now except the logo should be exchanged to the one we use for backend puposes:

- chose the grey logo (backend purpose) instead of the black one and face it the right way.

<img width="960" alt="Bildschirmfoto 2020-08-24 um 14 12 15" src="https://user-images.githubusercontent.com/3356016/91043762-72eb9e80-e614-11ea-87cd-ee8157c4a871.png">

**Comment by eins78** [comment]
<img width="251" alt="Screen Shot 2020-08-24 at 18 19 07" src="https://user-images.githubusercontent.com/134942/91070112-9c1d2680-e636-11ea-8f83-c49e4117db71.png">

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/commit/2c375353980c1e00200c58b8d7047ed78a36a80e
