### ISSUE TITLE
Deployment-Script terminates with "prepairing..." and no effect

### ISSUE THREAD

**Issue by simonspettmann** [leihs/leihs#894]
#### Expected behaviour
Executing the script and deploying up the server.

#### Actual behaviour
The script starts, executes the commands and ends with output: **"prepairing..."**
No matter how long I wait, nothing happens.

Ansible is installed, the server is running with all dependencies installed and a key-based-authentifikation. 

The example configs are copied and changed according to the tutorial.

#### Steps to reproduce
Executing the script...

![image](https://user-images.githubusercontent.com/69795142/90387106-dfe7bd00-e085-11ea-86bd-d443a68cd4f7.png)

#### Related issues 
none

#### Specifications
- Leihs version: 4 (latest)
- Browser version: Google Chrome (Version 84.0.4147.125)

#### Hardware
- Client: Ubuntu VM
- Server: Debian VM

VMs run on seperated Devices, port-forwarding is enabled for SSH and HTTPS.

**Comment by eins78** [comment]
This is an issue with your local installation of python/virtualenv. You can run the following script to get more output and debug the problem:
`cd leihs/deploy && ./bin/virtualenv-install`

**Comment by simonspettmann** [comment]
Unfortunately my company ended the project before I could try out your idea. Anyway, thanks for your reply :)
