### ISSUE TITLE
Search pattern compromised when searching for email address

### ISSUE THREAD

**Issue by AnthonyHunt** [leihs/leihs#896]
#### Expected behaviour
In the "Admin" / "Users" screen - Entering an email that does not exist should return "no results".

#### Actual behaviour
returns unusual results. This means that email cannot be used as a unique field.

#### Steps to reproduce
enter an email address with a similar domain to one already in the system.

#### Specifications
- Leihs version: 5.2.0
- Browser version: Any including API
- MySQL/PostreSQL version: N/A

**Comment by DrTom** [comment]
`/admin/users/` does not have a specific email search field. There is a more general search "term" field which seems to be referred to here.  The search term is a fuzzy like search based on _n-grams_ which is matched against names, login and the supplied email addresses. It does not  perform exact matches.

It would be possible add an email search field or maybe make the existing one a dual purpose field. Either is a rather a new feature than a bugfix.

**Comment by AnthonyHunt** [comment]
Then this is a bug. You cannot search for unique strings. 

If you have tried my report by searching for an email address you will see what I mean.

It is also not a "fuzzy" search as it obviously searches specific fields. For instance, it does not search the "ID" field which, as a key, it should.

**Comment by DrTom** [comment]
No it is not. However https://github.com/leihs/leihs/issues/913

**Comment by AnthonyHunt** [comment]
You're not testing this....

In my installation, I type "Anthony Hunt" into the search box. I get three results. They are all correct.  If I put anything else in the search box I get "no matches". 

Except

When I enter the @ symbol after "Hunt" and type the first three letters of the domain name.... then I get 15 results. Only one matches "hunt@domain". Fuzzies on firstname appear but not surname, but NOT all "Anthony"'s. When I then add "." I get 67 results fuzzies on firstname and surname appear but NOT all "Anthony"'s and "Hunt"'s.

My bug report is obvious that if it is fuzzy entering "Anthony Hunt" would by definition return ALL combinations. If I just enter "Anthony" I get 50 results. If I enter "Hunt" I get 92 results. No where does this relate to the 67 results that you are saying are fuzzy.

And my initial point... this is only happening when "@" and "." are in the search box.
