### ISSUE TITLE
Too many links from new app dropdown to legacy inventory pools

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#899]
I added the ITZ alle Group to the ITZ-Software pool as managers. After that all pools appeared in the navigation dropdown for my user. Only "ITZ-Software" and "Ausleihe Toni" should be there: 

<img width="1850" alt="Screenshot 2020-08-31 at 08 43 27" src="https://user-images.githubusercontent.com/526053/91690350-15040d00-eb66-11ea-888e-7d5b4c806a25.png">

Only the two links which were supposed to be there worked but all others appear too. This seems to happen in all new apps and reloads seem to have no effect.

**Comment by DrTom** [comment]
code to look at (from @eins78): 

https://github.com/leihs/leihs-clj-shared/blob/master/src/leihs/core/user/permissions.clj#L46-L54

**Comment by nimaai** [comment]
can not reproduce it, neither with my nor with your user @DrTom . the query used for the displayed inventory pools is as follows: 
```sql
SELECT inventory_pools.*
FROM inventory_pools
WHERE (inventory_pools.is_active = TRUE
       AND ((EXISTS
               (SELECT 1
                FROM access_rights
                WHERE ((inventory_pools.id = access_rights.inventory_pool_id
                        AND access_rights.user_id = 'uuid')
                       AND (access_rights.role IN ('group_manager',
                                                   'lending_manager',
                                                   'inventory_manager')))))
            OR (EXISTS
                  (SELECT 1
                   FROM group_access_rights
                   INNER JOIN groups ON groups.id = group_access_rights.group_id
                   INNER JOIN groups_users ON groups_users.group_id = groups.id
                   WHERE ((group_access_rights.role IN ('group_manager',
                                                        'lending_manager',
                                                        'inventory_manager'))
                          AND groups_users.user_id = 'uuid')))))
ORDER BY inventory_pools.name 
```
seems right to me.

**Comment by DrTom** [comment]
I can still reproduce the problem on staging. The above query is weird, there is no point for the second OR subquery with groups because `access_right` is already an aggregate containing the access_rights via groups.

**Comment by DrTom** [comment]
@nimaai 
OK, it took me a while staring at it. The second part is wrong. It doesn't bind to the particular inventory pool at all ;-) So if you have just one group access right all pools will be selected. You can also easily reproduce this. 


As mentioned above, `access_rights` is an aggregate there is no point for that second subquery. You could make it right by binding to the inventory pool. But if just remove it everything will be fine.

**Comment by DrTom** [comment]
this should fix it: 
https://github.com/leihs/leihs-clj-shared/pull/1/commits/845eb980e9bf7b7b7d5b6ccb2721bf83f2e18546

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/9dc1b04486de68eded5dd034f04c7af18e47adf3
