### ISSUE TITLE
mails need to be sent to private email after leaving ZHdK

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#901]
#### Expected behaviour
When an employee or student leaves the school, reminder mails should be sent to the private email address.

#### Actual behaviour
The mail address field is empty. Reminder mails do not reach the borrower. 

#### Steps to reproduce
Check an employee which still has an open contract but has left the school. 

#### DOD
Borrower receives the reminder mail even though he/she has left the school. 

#### Specifications
- Leihs version: 5.2.1
- Browser version: all
- MySQL/PostreSQL version: current

**Comment by eins78** [comment]
Problem: "alternate contact email" is picked directly from the `extended_info` blob, the structure of which has changed (ZAPI vs AGW) 
https://github.com/leihs/leihs_legacy/blob/master/app/models/user.rb#L230-L232

old: `extended_info['email_alt']`
new: `extended_info['personal_contact']['email_private']`

We can make a cheap fix that might break it the future by just changing this line of code,
and/or a reliable version by adding a `alternative email for contact` field to the User.

**Comment by DrTom** [comment]
I suggest to do the following: 
1. add a second e-mail field and adjust also the mail service to honor this one
2. write a special ZHdK migration which tries to extract information the extended info hash
3. adjust the sync to fill the second e-mail field

**Comment by nadjaweisskopf** [comment]
- New db field for email // Tom
- migration //Tom
- adjust Admin //Tom
- Adjust legacy mailer //matus oder max
- Adjust sync //Tom

**Comment by eins78** [comment]
done in https://github.com/leihs/leihs/compare/d957bfd403cbb00fa563321ef51aedf0ac730baf..30e4038218b58bbddc0a600dcee581ac797e4bcb

**Comment by DrTom** [comment]
I am reopening this temporarily because of https://github.com/leihs/leihs/issues/916
not urgent; somewhen in the next weeks

**Comment by DrTom** [comment]
Uff, I believe so.
