### ISSUE TITLE
Set a title

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#907]

**Comment by nimaai** [comment]
@nadjaweisskopf @eins78 it's optional, right?

**Comment by eins78** [comment]
> @nadjaweisskopf @eins78 it's optional, right?

In the DB, title and purpose should be required. In the form, we'll ask for title first and prefill the same text for the purpose so it can be left in common cases (like "Austellung Soundso", "Mein Diplomfilm") or extendended if the lending staff needs more info.
To be clear, we also dont rely on the title being visible to lending staff, all the info must be in "purpose" like it is now.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7ce1f18749b7755ca38315f68c0c53bb87cb309e
