### ISSUE TITLE
Template assistent

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#908]
cart needs to be finished first.

Basic To dos:

- [x] Migration: `reservation.status = 'draft'`
- [x] Legacy code: don't break existing
- [x] Legacy code: extend availability to optionally include `draft` reservations
- [x] remove `include_draft` parameter from legacy?
- [x] create drafts only for reservables
- [x] possibility to set start- and end-date
- [x] random data for `draft` reservations for legacy tests
- [x] adjust documentation + new state transition diagram

**Comment by eins78** [comment]
result of discussion:

# templates + reorder simple version

## templates index

* top of list: start/end-date fields, mandatory
* list: per line a [sumbit] button
* creates Reservations with new state "wishful"
* add name of template to CustomerOrder title if empty

## shopping cart

* UX for "wishful" Reservations is identical to "timed out" Reservations

## orders show

* small sub-form with start/end-date fields, mandatory + [reorder] button

# next steps / second version

* A "Preview" page to adjust quantities before wishful Reservations are created
  * like the current first step of templates, but with start/end date and `maxAvailableQuantityInDaterange` per model-line, 
    so that customer can choose between models on the basis of the availability data



---

bonus: reservation stati legend
- unsubmitted = temporary reserved (until order times out), decreases current availability of model
- wishful = not reserved (yet) but saved in DB, no effect on availability of model

**Comment by nimaai** [comment]
Remaining ToDos:
- [ ] remove `include_draft` parameter from legacy?
- [ ] migrate from join table to foreign key on `model_groups.inventory_pool_id` (1-n) (OPTIONAL)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/80abaeab7879355f8756958120fbb905b5a13cbd

**Comment by nadjaweisskopf** [comment]
Check with Stakholders if and how needed.

**Comment by nadjaweisskopf** [comment]
templates are implemented already.
