### ISSUE TITLE
Admin - Cannot delete Users

### ISSUE THREAD

**Issue by ClaesFredo** [leihs/leihs#91]
Hi

This all that happends when attempting to remove a User

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

Sincerely
Claes

**Comment by psy-q** [comment]
What is in the logfile when this happens? It's either log/production.log or log/development.log, depending on the environment you're running leihs in.

**Comment by ClaesFredo** [comment]
Hi

Sorry for taking my time to answer the above. 

I have a log/production.log file. Its last entry was 2015-jan-17. 

Trying to delete the user produces the above message without an entry in the production.log file. 

For what it is worth, I tried changing the file setting to chmod 666 but it did not have any effect. 

/Claes

**Comment by psy-q** [comment]
Are you running behind Phusion Passenger? I'm assuming production mode and a setup with Passenger here. Did you restart the app (`touch tmp/restart.txt`) after making sure the production.log permissions are correct? I believe Rails opens the file handles for logging only at the when the app starts, if it does not succeed it will run without logging.

When the "We're sorry, something went wrong" page appears, Apache will log a 500 error and log/production.log should contain the Ruby stack trace and error message. We need these to diagnose further.

**Comment by nadjaweisskopf** [comment]
If the problem still persists, please reopen this ticket.
