### ISSUE TITLE
Error when using the "Transfer Data and Delete User" option

### ISSUE THREAD

**Issue by linearlyIndependent** [leihs/leihs#912]
#### Expected behaviour
Trying to delete a user "A" in the admin interface Home/Admin/Users/User/Delete. The user is associated with previous orders, so I'm using the "Transfer Data and Delete User" option. After specifying the the user id of user "B" as the target user id, I click "transfer and delete".
Contracts, etc. should be transferred to user "B" and user "A" should be deleted.

#### Actual behaviour
Leihs returns: Request "Transfer Data and Delete User" ERROR 409
`ERROR: update or delete on table "users" violates foreign key constraint "fk_rails_90249e6b2c" on table "customer_orders"
  Detail: Key (id)=(<id_user_a>) is still referenced from table "customer_orders".`

#### Steps to reproduce
See expected behaviour.

#### Specifications
- Leihs version: 5.1.10
- Browser version: Firefox 80.0.1 (64bit/Windows10)
- PostreSQL version: 10

**Comment by DrTom** [comment]
I can confirm this. `customer_orders` is a new(er) field and the transfer feature has not yet  been adjusted to include this.

**Comment by linearlyIndependent** [comment]
In the meantime, is there a workaround other than manually deleting/modifying entries in the database?

**Comment by AnthonyHunt** [comment]
I found that I had to use users specific "ID" from LEIHS (the long hash) rather than an user id, login or email.

**Comment by nadjaweisskopf** [comment]
I'll close this ticket. Accord. to @eins78 this ticket is solved and will be deployed tonight.
