### ISSUE TITLE
Exact e-mail address match for `admin/users/` search term

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#913]
Problem: the fuzzy text term search in `admin/users/` confuses users when entering an email address because they will typically get many results but expect an exact match. 

Solution: perform an exact match query against the two email fields if and only if the search term contains an `@`.

**Comment by nadjaweisskopf** [comment]
I'll close this ticket. Accord. to @eins78 this ticket is solved and will be deployed tonight.
