### ISSUE TITLE
Lending: Handover page is very slow when assigning items to large orders

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#914]
#### Expected behaviour
For large orders, assigning a single item takes no more than 1 second.

#### Actual behaviour
It takes 4 seconds.
- The problems starts if the order has appr. 50 - 60 items.
- Most orders from film-dept. contain > 50 items. 
- Video from lending dept. shows how slow the order is when scanning items (order in video contains 185 items)
- Because it is so slow, the lending dept. is not sure after scanning the items if all items have been scanned and need to count the items and the green lines. 

#### Steps to reproduce
1. open handover for a large order (cast) > 50 items
2. scan one item after the other
3. adding the item nr. to the specific line takes very ling

**Comment by eins78** [comment]
After analyzing it again with @nimaai, we conclude that this solution should be correct in all cases.
There is a tricky edge case: assigning or removing an item from a line for a reservation that has its **end date** in the past, the availability for the model changes. In this case we do not refetch the "correct" data. This is not the problem in practice because those lines can **never** be handed over ("Error: End date can not be in the past").

@nadjaweisskopf Fix (https://github.com/leihs/leihs/commit/dfc785e349c6aa64f731a57c58f8c6580b555af2) can be tested on https://mfa.ruby.zhdk.ch

**Comment by eins78** [comment]
Another idea that would sole this problem (and maybe others) in a very different way that came up while discussing the current solution: Offering a checkbox to disable the automatic reloading of the availability. The user could then choose between having correct warning at all times (but waiting for them) or quickly assigning items with minimal waiting time. I would recommend it only if there are logical issues with the current solution or if there are other situations where this data loading slows down the handover process.

<img width="995" alt="Screen Shot 2020-09-15 at 08 50 05" src="https://user-images.githubusercontent.com/134942/93175938-c3947a00-f730-11ea-960d-fee691914109.png">

**Comment by eins78** [comment]
* done in https://github.com/leihs/leihs/commit/e2999f0ed94abed436b3c5bbcf99406abcc1d9a9
* part of release 5.2.4

**Comment by nadjaweisskopf** [comment]
@nimaai @eins78 Sent another mail to the lending dept. so they test the changes on staging.
