### ISSUE TITLE
Procurement: Orders need to have a unique number

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#915]
**Needs to be tested and implemented until first week of October**

#### Expected behaviour
The orders in procurement need to have a unique number which is easy to read and use in discussions. In every meeting the procurement participants go through the orders. When someone talks about a specific order, he or she wants to have an easy number to communicate which order he or she is talking about. 
After a first discussion with @nimaai it is clear, that the number should not contain elements which change such as 
- status
- category
- etc.

My proposal is that we number the orders as following: 
- YYYY.NNN 
- YYYY = Year, in which the order has been created. If they change the year, we need to change the YYYY to the new year. 
- NNN = Number, starting with 001 for the first order in that year

If the order is moved to another year, we need to do the following: 
- YYYY is adjusted according to the year
- NNN is set to the next higher numer according to the already existing nr. in that year. 

We then might have gaps in the numbers of a year because an order has been moved but that really is an exception.

The contract IDs in lending, the UUIDs and the inventory nr. are too complicated to use in a discussion in one of these procurement meetings. 

#### Actual behaviour
Now they have to use the year, the title of the order and mention who has created the order.

**Comment by nadjaweisskopf** [comment]
@nimaai @eins78 Following final solution has been discussed with the stakeholder: 

- YYYY.NNN f.e. 2021.014
- The unique number is given to an order at the moment it is created.
- The number does not change, no matter which state the order is in. 
- Even if the order is moved to a budget period in the future, the year does not change.
- The year indicates in which year the order has been created. So if the budget period 2023 contains an order with the number 2021.014 then it indicates that the order has already been put on hold for two years.
- In Procurement app the budget period will hardly be anything else then the year (YYYY).

**Comment by nimaai** [comment]
@nadjaweisskopf And what should be the name of the field?

**Comment by eins78** [comment]
> * The year indicates in which year the order has been created. So if the budget period 2023 contains an order with the number 2021.014 then it indicates that the order has already been put on hold for two years.

Nice, after the last discussion I was hoping for that outcome :)

> @nadjaweisskopf And what should be the name of the field?

I'd say `short_id` internally, the display name can be changed quickly in the translations.

**Comment by nimaai** [comment]
Query to check the end result once done:
```SQL
SELECT pr.id, pbp.name, pr.short_id, pr.created_at
FROM procurement_requests pr
JOIN procurement_budget_periods pbp 
  ON pbp.id = pr.budget_period_id
ORDER BY pbp.name ASC, pr.created_at ASC;
```

**Comment by nimaai** [comment]
@nadjaweisskopf @eins78 And the `short_id`s of deleted requests can be reused, right?

**Comment by eins78** [comment]
> @nadjaweisskopf @eins78 And the `short_id`s of deleted requests can be reused, right?

Argh. No, they should not, that would be very confusing. 
But that shouldn't change to much, we don't need to remember all the deleted ones (the 404 error message could say "not found or deleted" to be more clear). Whatever auto-incrementing mechanism you will implement must remember the last used number per period and only increment, not filling any gaps. But because the newest request could be deleted that might be a bit tricky.

**Comment by eins78** [comment]
> In Procurement app the budget period will hardly be anything else then the year (YYYY).

@nimaai I would like to add a constraint to enforce that is really a string we can use in this context. `procurement_budget_periods` can only contain latin letters, numbers, dashes and underscores (`[-_a-zA-Z0-9]`).
Other instances would need to change it manually before upgrading (I don't think there are any, but we can add it to the release notes).

**Comment by nadjaweisskopf** [comment]
I don't think they should be reused either. No gap filling.

**Comment by nimaai** [comment]
@eins78 @nadjaweisskopf 

Another problematic scenario came to my mind:
1. Create 1st budget period "XYZ"
2. Create request for 1st budget period. It gets the short ID "XYZ-001".
3. Rename 1st budget period to "ABC".
4. Create 2nd budget period "XYZ".
5. Try to create a request for 2nd budget period. You get an error message, that short ID "XYZ-001" already exists.

This is because our counters are tight to budget periods, not their names.

**Comment by eins78** [comment]
> Another problematic scenario came to my mind:

yes, this is one of the edge cases I wanted to talk to you about…

> 4. Create 2nd budget period "XYZ".

I think an error should be thrown at this step already. So, renaming BudgetPeriods is ok, but an old name can't be reused (or at least as long as there are requests using that prefix).
Maybe the counter table can be reused, or we need another one to remember them.
We can separate `display name` and `requester number prefix` if that helps with the implementation (usability-wise ZHdK does not need it)

**Comment by eins78** [comment]
Much simpler Option: let BudgetPeriods be renamed however and deal with the potentially inconsistent names/prefixes. Could be less confusing in practice (because we don't expect admins to rename anything during a requesting phase anyhow).

> Another problematic scenario came to my mind:

> 5. Try to create a request for 2nd budget period. You get an error message, that short ID "XYZ-001" already exists.
> 
> This is because our counters are tight to budget periods, not their names.

Solution: Tie them to their names, then? (In that case I would strongly suggest to also do the separation of BudgetPeriod's `display name` and `request number prefix`)

**Comment by nimaai** [comment]
Ok, so let me summarise the changes: 

`procurement_requests_counters` table now has basically two columns:
1. `prefix` (text)
2. `counter` (integer)

`AFTER insert OR update ON procurement_budget_periods` =>
`INSERT INTO procurement_requests_counters (prefix, counter) VALUES (NEW.name, 1)` (`NEW` means the newly created or changed budget period)

And when creating a new request find the prefix matching the (current) budget period's name and continue with the counter of the matched prefix.

@eins78 Right?

**Comment by eins78** [comment]
@nimaai with the last change ("unless prefix exists…") its ok 👍

**Comment by nimaai** [comment]
@eins78 Do we additionally want/need/appreciate following columns:
* `id`
* `created_by_budget_period_id`
* `created_at`

?

**Comment by eins78** [comment]
@nimaai not strictly needed, but if its not too much work it might be helpful in the future, in case we have not through all the different cases (which seems possible).

**Comment by nimaai** [comment]
@eins78 check out https://github.com/leihs/leihs-procure/blob/a1d7a07a685bb98998eb7bd960f446a36d082bfe/server/spec/models/short_id_spec.rb

any other weird cases in mind?

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e03ed9003f58ac8f4cb4f8f2305a9b1a5f5d7cf9

**Comment by nadjaweisskopf** [comment]
test results: 
nok: I received following error after creating an order in budget period 2021. 

![Uploading Bildschirmfoto 2020-10-06 um 15.45.28.png…]()

**Comment by eins78** [comment]
@nadjaweisskopf 
> 1. The mentioned order 2028.010 is exported in the CSV as 2028.01 instead of 2028.010. Is that a setting when opening the CSV or a mistake when exporting?

That a common issue with spreadsheets (Automatic Data conversion, depends on the Spreadsheet Application & settings, especially bad for things that look like dates…). It does not happen on my computer, which has US-English locale so it seems likely that date conversion is at fault.
If you open the file with TextEdit you can see that the data is exported correctly. If it happens in Numbers or Excel, the columns data type needs to be changed from "Automatic" to "Text". For users working in Excel regularly that should be "normal".

**Comment by eins78** [comment]
@nimaai steps to reproduce for Nr. 1: 
* fresh prod DB 202010-05
* create 2 requests in 2022 (gets `2022.003`, bug resets all counters to `3`)
* create a request in 2021 -> gets `2021.004` which already exists.

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/0d7e116519cc61ed15045c53193bf819fb3322fc

**Comment by nadjaweisskopf** [comment]
@nimaai tests are ok. Now the stakeholder ist testing.
