### ISSUE TITLE
Function "Forgot Password" didn't work after restart the legacy-service

### ISSUE THREAD

**Issue by winampdevil** [leihs/leihs#926]
#### Expected behaviour
The function "Forgot Password" at the login screen should send an email with a reset-your-password-link 

#### Actual behaviour
You can click "Forgot Password", enter an e-mail-address and click continue, but you will receive no mail.
Reservation-Mails will work

#### Steps to reproduce
The configuration for the mailsystem is stored in /leihs/legacy/config/settings.yml
I can change values also in the Web-GUI "Admin -> Settings"
If i do a restart of the legacy-service via` systemctl restart leihs-legacy.service` at the shell, the settings.yml will be re-read - and the "Forgot-Password"-function stops working.
If i change a value in the Web-GUI (e.g. default_email) without restarting the legacy-service, the "Forgot-Password"-function works. I can use the same values as set in the settings.yml-file.

Background: 
After running a backup-process, which is pausing our vm, the "Forgot-Password"-function will not work anymore.

#### Specifications
- Leihs version: 5.2.0
- Browser version: Chrome / Firefox
- MySQL/PostreSQL version:

**Comment by nimaai** [comment]
Reset password feature is take care of by `leihs-mail.service`. Try to restart that.

**Comment by winampdevil** [comment]
Restart of ```leihs-mail.service``` didn't help.
Opening "Admin -> Settings -> Click 'Save Settings' " will help, but this is not a real solution

**Comment by winampdevil** [comment]
Reset password is now working.
There was a strange behavior in connection with a mail-relay. Found an authentication error in database-table `public.emails`, which was the hint...
