### ISSUE TITLE
Booking Calendar: fix labels

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#928]
it says "Startdatum" where it should be "Enddatum"
<img width="790" alt="Screen Shot 2020-10-13 at 10 38 06" src="https://user-images.githubusercontent.com/134942/95961773-ceacf980-0e05-11eb-9e7e-482532924c79.png">

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/7dd654ecf82679913a525976693aa625342933f2
