### ISSUE TITLE
Language setting via deploy is broken

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#930]
Broken in two ways: 

1. broken during initial deploy because there is no DB yet (similar to dump before deploy) 
2. there seems to be a problem with the new constraint "exactly one default"; it looks like that only passes if the setting is equal to what is already configured ;-) 

I suggest to remove this setting entirely from the deploy and put a UI and API in the new admin interface.

**Comment by nimaai** [comment]
@DrTom Go for it. That was the long-term plan anyway.

**Comment by nimaai** [comment]
Stuff to check:
- legacy initializer
- deploy inventory
- mail templates
- translations (backend/frontend)

**Comment by DrTom** [comment]
😱

**Comment by DrTom** [comment]
This has been refactored, we have seen no bugs since.
