### ISSUE TITLE
Place link back to inventory park

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#934]
Can we place a link on the group name that navigates back to the lending park? 
https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f/users/

<img width="816" alt="Bildschirmfoto 2020-10-21 um 09 01 37" src="https://user-images.githubusercontent.com/3356016/96684664-39b57d80-137c-11eb-9a27-b310f35f6c15.png">

Related issue: #900

**Comment by DrTom** [comment]
There are links in may titles and all of them link to the corresponding entity in `Admin`. I think it would be confusing to do so. I will add a link to the entitlement-group in Admin and from there to lending. This is one click more; but it is consistent.

**Comment by DrTom** [comment]
https://github.com/leihs/leihs-admin/commit/5b00d131fa531e57bd141bc7faf038caab3123e2
