### ISSUE TITLE
The title doesn't navigate to anywhere

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#936]
https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f

The name of the group seems to be a link. Where should it lead to?

related issue: #900

**Comment by DrTom** [comment]
It links to the "entitlement-group" page itself. Which does not make much sense because this is the page displayed here ;-)

**Comment by DrTom** [comment]
Fixed in https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/155abaa1-b098-4577-8728-6b838624af5e
