### ISSUE TITLE
Filter shows too many results

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#938]
https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f/users/?account_enabled=&is_admin=&org_id=&page=1&per-page=50&term=&membership=direct

The filter "direct members" shows the members added through groups too. I would only expect to see the ones directly added. 

Related issue: #900

**Comment by DrTom** [comment]
Fixed in 

https://github.com/leihs/leihs-admin/commit/3e44b5b7199435020414b12f4d36db3e41f7f4e8

the delegation members filter was equally affected by this bug

**Comment by nadjaweisskopf** [comment]
@DrTom I would excpect the amount of members to be the total of "direct members" and "group members"? This is not the case. Check following group: https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f/users/?account_enabled=&is_admin=&org_id=&page=1&per-page=1000&term=&membership=any
