### ISSUE TITLE
Filter "no" switches to "any"

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#940]
https://tom.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351/entitlement-groups/b985be38-962b-49ea-a601-590b7d8dc84f/users/?account_enabled=false&is_admin=&org_id=&page=1&per-page=50&term=&membership=member

1. when chosing filter "no", it switches automatically to "any". 
2. The filter "any" should show all users, no matter if there account is enabled ot disabled.
3. show the entries in the filter "members" without dashes "-", same as the column titles. 

<img width="217" alt="Bildschirmfoto 2020-10-21 um 11 28 37" src="https://user-images.githubusercontent.com/3356016/96701244-aaff2b80-1390-11eb-91fd-bab80bbfa8cb.png">

related issue: #900

**Comment by DrTom** [comment]
1. is a dedicated issue (because this is general for all users filter) https://github.com/leihs/leihs/issues/943

**Comment by DrTom** [comment]
3. is fixed in https://github.com/leihs/leihs-admin/commit/3e458f8937a4de5368f30a80e4a746d8b48deb45; however we keep the `non-member` hyphen because that is a thing https://www.dict.cc/englisch-deutsch/non-member.html
