### ISSUE TITLE
Allocations in other entitlement-groups number buggy?

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#942]
Check if the second number on the entitlement row considers only allocations within the same pool or not. Number tooltip: **"Allocations in other entitlement-groups considered - still available quantity of borrowable and not retired items"**

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/e334086a2957cc95b5af15084c32e0db62446f20

**Comment by nadjaweisskopf** [comment]
The group names are not shown on staging. In Production they are visible. Does this have anything to do with this change?

![Uploading Bildschirmfoto 2020-11-03 um 11.52.35.png…]()

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/4c39810daacc4f876121f08437a4e1913e7e2cd5
