### ISSUE TITLE
cleanup initial DB seeds

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#945]
- move all "initial data" out of migrations and initializers into a `rake db:seed` tasks and create a minimal `seeds.pbin` dump (but in plaintext format)
  - languages
  - default building and room
  - mail templates
  - settings
  - procure stuff?

- see implementation in Madek: https://github.com/Madek/madek-datalayer/commit/e90f61a100632ee9d1bb70c1e99e9d9fcef1b64c#diff-69b7d2cd8426a9a8d4264335b11eb9268c570d1d1653348585fd16f674a42ebd

- *bonus: if possible, try to run it in a way that when the seeds change, only migrations need to be written*

> discussion: <https://madek.slack.com/archives/C045WGJ3D/p1603708501037800>

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/pull/947
