### ISSUE TITLE
Orders are shown after a very long time - if even on test environments

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#948]
Go to orders page: https://tom.leihs.zhdk.ch/manage/5dd25b58-fa56-5095-bd97-2696d92c2fb1/orders?state%5B%5D=approved&state%5B%5D=submitted&state%5B%5D=rejected

Related issue: https://github.com/leihs/leihs/issues/633

**Comment by eins78** [comment]
fixed in https://github.com/leihs/leihs/commit/4a395409c62a9414a41f1e48f7485c2ac8cbc796
