### ISSUE TITLE
Remove "new" timeline

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#950]
It is buggy and contains duplicate and possibly incomplete implementation of entitlements & availability, which we don't want to maintain. Besides, the feedback so far has been rather negative and doubts exists, to what extent it offers any improvements to the old timeline.

@nadjaweisskopf OK?

**Comment by nadjaweisskopf** [comment]
@nimaai no, nok. For several reasons: 

1. the new timeline has been developed together with Toni-Ausleihe. 
2. They have invested time into this feature. 
3. The reputation would be very bad, if we would drop this timeline
4. The timeline is in use far too long. to be able to go back to the old one. 
5. We can only drop the new timeline if we come up with a new one and at the moment that has no priority.
