### ISSUE TITLE
Scope SMTP Settings in Admin UI

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#958]
TODOs:
- [ ] mittelfristig sollen die ganzen SMTP settings aus dem admin scope raus und unter den system_admin scope, das gehört zu den Sachen, die ich schon angefangen hatte – @DrTom

**Comment by nimaai** [comment]
This seems to be the case already. I have removed the system admin role from my user and now I don't see the SMTP settings under " Home -> Admin -> Settings".

Or did I misunderstand and/or something else needs still to be done? @DrTom

**Comment by eins78** [comment]
was already done in https://github.com/leihs/leihs-admin/commit/98ff4a6de35536765a9d63db0a8990ac2f0818e4
