### ISSUE TITLE
TLS Config updaten

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#960]

**Comment by eins78** [comment]
* generator: https://ssl-config.mozilla.org/#server=apache&version=2.4.25&config=intermediate&openssl=1.1.0l&ocsp=false&guideline=5.6
* commit: https://github.com/leihs/leihs_deploy/commit/f22065443d4976b5f4f8abe04328508778cedc0b

SSL Labs report: 

![Uploading Screen Shot 2020-11-23 at 17.51.39.png…]()

**Comment by eins78** [comment]
@DrTom I edited the config manually for `leihs-gw` @zhdk. Luckily all the vhost had no overriding configs, so I only edited `/etc/apache2/mods-available/ssl.conf` with the following snippet (same as the built-in version):

```
SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLHonorCipherOrder     off
SSLSessionTickets       off
```

<img width="1145" alt="Screen Shot 2020-11-23 at 18 08 53" src="https://user-images.githubusercontent.com/134942/99992691-f6a15c80-2db6-11eb-965e-60b08ba9277f.png">
