### ISSUE TITLE
Import Inventory and Userdata

### ISSUE THREAD

**Issue by md-ufg** [leihs/leihs#961]
Hello.

I am new here and ive setup a test environment of the latest version of leihs to be tested as a working environment for the art university in linz, austria. anyhow. 

i am wondering if theres a mechanism to import existing user and inventory data into the leihs sysem. 

thanks for support.

best
markus

**Comment by DrTom** [comment]
As for the users import: the routes underneath `/admin/`, i.e. `/admin/users/*` are all accessible via a REST API. See also https://github.com/leihs/leihs/wiki/Admin-API. We use this to perform a nightly sync of users and groups. For an example our code is available at https://github.com/leihs/zhdk-sync. 

There is no API for the inventory but there is a csv file based import.

**Comment by md-ufg** [comment]
Thank you. Is this Import Export proceeding somewhere documented in more detail?
I think this is quite an important task running the system.
