### ISSUE TITLE
Filter Groups in Sync 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#963]
This is a ZHdK specific issue. 

Due to expansion and changes in the IAM system we are getting more groups now.  Many of them are not useful in leihs but confusing for users and admins. Examples: `App_Intranet-Personendaten*` and `Verteilerliste*`. Possible approaches: 

* have the ZAPI people apply a filter in their place (as far as I know this is not technically possible yet)
* apply some filtering within our sync

**Comment by DrTom** [comment]
ZAPI Update: some sort of `type` filter is planned for the near future. 

Note we might have to adjust user mapping to groups because they can include group_ids for which the groups are filtered out.

**Comment by DrTom** [comment]
Update: as discussed with ZAPI People, there will be no solution from the ZAPI side in the (near) future; we will implement a filtering capability

**Comment by nadjaweisskopf** [comment]
ZAPI-Sync will not be updated. We'll write it from scratch.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf check the groups in leihs and see which filter works for the sync. Which groups can be left out.
