### ISSUE TITLE
DB-restore problems with public schema on test/staging servers

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#964]
* In older PSQL versions (like on our prod) the `public` schema was included in DB-dumps.
* Newer versions of `pg-restore` do not work around that anymore.
* We added our own workaround to remove the public schema because otherwise the DB could not be restored on `test` (Error: schema `public` does **already** exist)
* Now the same workaround failes for staging (Error: schema `public` does **not** exist)

goal: pin everything to PG v10

steps:
* [x] ansible: only install PG10
* [x] make it work on Debian 9 and 10 (some server are still on 9)
* [x] ansible tasks related to DB setup should be run before any restored (playbook needs to be extended)

**Comment by DrTom** [comment]
**RESET**: the plan is to make sure from and to PG10 works! Everything else will bring us into combinatorial complexity hell!  So we need to make sure there is only PG10 installed because something on the ZHdK boxes seems to interfere here. I mentioned that in chat before: `pg_restore` needs to be also version 10 and you can't trust `pg_restore --version` because of that damn debian dispatcher script.

**Comment by eins78** [comment]
I agree that we should pin everything to PG10. 
The remaining problem: We did that already when we tried last time and it did not work for all servers.

I curently believe the solution is simple (remove the public-schema-workaround from ansible and nothing else), under the following assumption:
Pinning to PG10 did not work for `test` server because some deploy installed a newer version of PG and this case was not "catched" by the ansible task. So this problem could only ever happen on frequently deployed/updated test-servers, but not staging or even prod.

**Comment by eins78** [comment]
update: my assumption was incorrect, new theory is even simpler: the previous fix did not work in all cases, because `postgres` (no version number) package is installed so in practice it depends on the Debian version(!).
Also, because of a know (to me) issue in our playbook we were testing the wrong thing all this time: the restore task is in a separate playbook and the task related to installing PG are not run before the restore (so this playbook can only work if a regular deploy was done before).

**Comment by eins78** [comment]
experimentation has shown that it is not possible to correctly configure the `pg_wrapper` provided by the Debian package for all our use cases (e.g. it works in the shell, but not rake tasks). 
the [stated rationale for the wrapper](https://web.archive.org/web/20201126174647/https://www.digital-experts.de/doc/postgresql-common/architecture.html) solves a problem we have already solved (there are ansible tasks to handle version upgrades).
solution: remove the wrapper (so the symlinks pointing to it are not accidentally used), then symlink our wanted tools in the right version:

```sh
rm /usr/share/postgresql-common/pg_wrapper
ln -fs /usr/lib/postgresql/{{postgres_version}}/bin/{psql,pg_dump,pg_restore} /usr/bin/.
```

**Comment by eins78** [comment]
hopefully last update: removing the `pg_wrapper` is too cumbersome. 
we'll configure it correctly, which works in almost all cases.
but in the ansible tasks we just use the full path (or set `PATH`) for the right version (`/usr/lib/postgresql/{{postgres_version}}/bin/pg_restore`).
