### ISSUE TITLE
PG table partitions

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#967]
https://www.postgresql.org/docs/current/ddl-partitioning.html gives an overview of most important benefits, which are mainly:

1. Better performance in certain situations (for very large data sets and specific queries, the planning and execution does only need to consider relevant partitions; quicker and more lightweight `VACUUM`ing). 
2. Better maintenance of large data sets (explained further below).
3. Possibility of using multiple physical storage devices (using `TABLESPACES`).

There are basically 2 ways to do it:
1. _Declarative partitioning_
2. _Partitioning using inheritance_

They both have their gotchas, pros and cons, but their goal and usage is basically same (or very similar).

In regards to partition(s) maintenance, the _declarative partitioning_ seems to be somewhat easier to do. It means:
1. Setting up the partitions hierarchy initially.
2. Adding new partitions periodically as required (either by hand, by cron job, or by trigger).
3. Detaching/dropping/etc. partitions periodically as required.

For a simple use case and hierarchy not really much. There is one question mark though for already existing tables which would need to be partitioned:
> It is not possible to turn a regular table into a partitioned table or vice versa. However, it is possible to add a regular or partitioned table containing data as a partition of a partitioned table, or remove a partition from a partitioned table turning it into a standalone table.

How would one migrate existing data? I expect there must be some way.

Now removing/dettaching/deleting/archiving partitions or turning them into ordinary tables is the part where it gets interesting, especially in regards to our primary concern.

In regards to detaching a partition PG documentation writes:
> This allows further operations to be performed on the data before it is dropped. For example, this is often a useful time to back up the data using COPY, pg_dump, or similar tools. It might also be a useful time to aggregate data into smaller formats, perform other data manipulations, or run reports.

Ideally one would not need different files and especially file formats (like JSON) outside PG itself for archiving purposes. Having a specific table (and data in general) divided in "most recent and needed" one and "less needed" one, possibly using different schemas (`CREATE SCHEMA archive;`) in the same database, is a good prerequisite for:
- Straightforward granular dumping and restoring strategies (dump/restore from specific schema).
- Maintaning the possibility of access to old data via UI (instead of `grep`ing through JSON files).

Conclusion:
I think it is an interesting and a valuable strategy to keep in mind as the size of our data keeps on growing continuously. A great part our data is centered around an operationally relevant time-frame stretching couple of months. Everything what lies outside of it is basically archive. Performance-wise this approach, though having a reasonably manageable level of complexity, is probably not justified (yet).

**Comment by nimaai** [comment]
FYI @eins78 @DrTom

**Comment by nimaai** [comment]
@DrTom As discussed, food for thought. You can decide if and what we take out if it in practical terms.

**Comment by nadjaweisskopf** [comment]
Good as described. But postponed until we have more time.
