### ISSUE TITLE
Orders Show: Error handling bug

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#969]
Found while reproducing #968 but seems to be unrelated:

Steps:
* Login as my user
* go to `/app/borrow/orders`
* click on "H4 als Audiointerface testen"
* it shows the error from #968 
* click on "← All Orders"
* click on _any other_ order in the list
* bug: shows the same error, relating to the ID of the previously visited order
* when i click the "reload" button in the erorr message, the correct data is loaded and shown (so presumably a problem with getting the data from `app-db`)

---

![Screen Shot 2020-11-30 at 12 54 38](https://user-images.githubusercontent.com/134942/100608172-51353e00-330c-11eb-8a12-7ea77e7fe8a6.png)

**Comment by nimaai** [comment]
Cannot reproduce it. Might have been fixed through https://github.com/leihs/leihs/commit/b71ed70e7d5ba9a7815f2bcac2e146708c7bd5dc.

**Comment by nimaai** [comment]
Can be reproduced:
- produce some error on order show
- go back to orders index
- click on some other order link
- there is mismatch between order id in the url and in the error message

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/24e23e8230c4e813cd9048ecce7b749c93deddd3
