### ISSUE TITLE
Delegations for new Admin

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#970]
Feature: manage delegations in new Admin.

Needs: refactoring of permissions including db fields `protected` for some tables.

**Comment by eins78** [comment]
the "feature" part is almost done but more "cleanup" needed. 

currently delegations can be managed/viewed like user (only the index is filtered correctly), 
and some features are missing from delegations#show.

- [ ] ui: disable the "user#show" page if its a delegation
- [ ] permissions: forbid user-related API methods if its a delegation
- [ ] port over "Suspension" editing for delegations (and possibly other missing features)
