### ISSUE TITLE
Extend ZHdK sync

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#971]
Set the `protected` attribute. 

Depends on deployed https://github.com/leihs/leihs/issues/970

**Comment by eins78** [comment]
@DrTom if the sync sets a user to `is_active=false`, will it stay `protected=true` or should it be changed to `proteced=false`?

**Comment by nimaai** [comment]
Just to be sure, we are talking about `system_admin_protected` right?

**Comment by DrTom** [comment]
Wait for general solution, new sync
