### ISSUE TITLE
Borrow: Bug: Cart Timeout Refresh when in past

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#975]
There is still some logic bug, it happens to me everytime i open an old browser tab after a few days.

steps to reproduce
- make a reservation
- wait until all the dates are in the past
- cart refresh yields date in the past

what should happen:
- refresh timeout should work for dates long in the past
- either cart is refresh or shown as "draft"

---

![Screen Shot 2020-12-11 at 11 41 51](https://user-images.githubusercontent.com/134942/101894637-c6273400-3ba6-11eb-8d7b-dcbe47b1e1c2.png)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/d17a44f352cef7c1c5edb54f631bb0f16fd74694
