### ISSUE TITLE
Manager Roles

### ISSUE THREAD

**Issue by wolfgang-reutz** [leihs/leihs#98]
Hi,

with the new 3.x version we are using i have a problem in understanding the roles:

- a inventory manager can handle the lending, add and edit inventory, controlling the pool - ok that's clear
- a lending manager can handle the lending, but as well add, edit and modify inventory items and models
- what is a group manager for and how are groups supposed to work?

i can't find a solution for my problem:
i need some managers which can handle the lending process, but only that, no editing of inventory and so on. How can i achieve that? the group manager is the closest i could find, but is there a wildcard group possible, like "i'm the manager of group all and all users are automatically a member of that group?"

cheers, wolfgang

**Comment by psy-q** [comment]
This shouldn't be the case, I think you found a bug. Lending managers should only be able to view existing inventory, and change the content of the lending notes field. I can already reproduce it on 3.30.1, I will now try to 3.29.2 and some versions back. If it only affects 3.30.1, we can release an updated version quickly.

**Comment by psy-q** [comment]
I looked through our scenarios and it's probably OK the way it is: Inventory managers can create items that are inventory relevant. Lending managers can create items, but only items that are not inventory relevant.

I am not sure whether lending managers should be able to edit all items, though. I'm checking with the team to find out.

**Comment by psy-q** [comment]
I started describing the [roles](https://github.com/zhdk/leihs/wiki/Roles) a bit on the wiki, hoping that it makes the group manager a bit clear. You are right that it's the least powerful manager, but it's not obvious how that manager could work if you're not already using group partitioning. Do add more questions here, I can answer them on that page so that we can expand our docs.
