### ISSUE TITLE
Build problems with Borrow- and  Mail-Service (Boot) 

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#983]
We have two services build with Boot, they too frequently fail with: "too many links" in Integration and Container tests. 

As we want to replace Boot in the long run anyways we should check if this solves our problem.

**Comment by DrTom** [comment]
See also https://github.com/leihs/leihs/issues/984

and https://ci.zhdk.ch/cider-ci/ui/workspace/tasks/5b0c3fd8-5d16-5eb0-a75b-e486d762073f

**Comment by nimaai** [comment]
I can't remember what the solution was, but this problem doesn't seem to occur anymore.
