### ISSUE TITLE
Build Problems with `build-procure-client`

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#984]
Like Borrow and Mail https://github.com/leihs/leihs/issues/983 `build-procure-client` still seems to have build Problems which are (like the previous) shadowed by local caching. 

Here is an example: https://ci.zhdk.ch/cider-ci/ui/workspace/trials/7508065a-a2c3-4d44-9073-2f77da81e05b/scripts/build-procure-client

First step: investigate.

**Comment by eins78** [comment]
seems like a dependency problem: `build-leihs-ui-for-procure` is needed for `build-procure-client
`
<img width="1005" alt="Screen Shot 2021-01-11 at 10 59 53" src="https://user-images.githubusercontent.com/134942/104167182-3b7f6200-53fc-11eb-84e1-7da5ddd46f97.png">
