### ISSUE TITLE
Flacky borrow integration test

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs#985]
https://ci.zhdk.ch/cider-ci/ui/workspace/trials/c0aa7f5a-6862-4530-ac55-d5507c059bf0/scripts/test

**Comment by DrTom** [comment]
https://ci.zhdk.ch/cider-ci/ui/workspace/tasks/bfdfec25-b064-5270-82d7-4a241092a722 😮

**Comment by nimaai** [comment]
Something strange is happening. We fill in the search field and assure that it is filled in correctly: https://github.com/leihs/leihs-integration-tests/blob/31778051e3d317884f6ac95da62841cf08ce2193/spec/features/borrow/search_and_order.steps.rb#L15-L16
But then it gets cleared somehow and that is why the search result is incorrect. It is not deterministic but happens more often than it doesn't.
I have already tried several things none of which helped.
@mfa any idea? Maybe something wrong in the React component?

**Comment by nimaai** [comment]
[Workaround](https://github.com/leihs/leihs-integration-tests/commit/ab311998ffef52c56b94d4e36569147bfa990eeb#diff-998913468a85865447d79b7d4c35fa8c34ca14a97926d2412c5427793f28baf2) for the time being.

**Comment by eins78** [comment]
the mentioned workaround is stable enough for us atm.
