### ISSUE TITLE
New Audits for legacy

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#987]
Investigate and if possible implement "audited-requests" for legacy. 

The new audits record changes via triggers in the DB. Those records can be combined and bound to a user via requests and transaction ids. 

Here is an example for clojure https://github.com/leihs/leihs-clj-shared/blob/master/src/leihs/core/ring_audits.clj

Essentially: 
* start a new transaction for each changing http-request ; all underlying db-changes should use this transaction
* save a record in `audited_requests` referring the `txid` and the `http-uid` 
* do the same for the response 
* if possible to not use the transaction to save `audited_requests`, and `responses` this way we can capture failed request which usually would rollback everything

**Comment by nimaai** [comment]
>if possible to not use the transaction to save audited_requests, and responses this way we can capture failed request which usually would rollback everything
not getting this @DrTom. could you elaborate little more?

**Comment by DrTom** [comment]
Elaboration on using a different transaction to save request and response: if you look at `persist-response` and `-request` in https://github.com/leihs/leihs-clj-shared/blob/master/src/leihs/core/ring_audits.clj; they are persisted outside the transaction `tx` using a different connection  `@ds/ds` (connection and transaction are interchangeable); if you would use `tx` instead of `@ds/ds` they would be rolled back and we would lose them. For the matter of audits it doesn't matter because nothing gets persisted then. For the matter of finding errors and possibly attacks failed requests are useful. I am not sure how this all translate to rails/ruby though.

**Comment by nimaai** [comment]
`http-uid` header: https://github.com/leihs/leihs_deploy/commit/463d51a6ea83ce6aafebbd9dcb0b5d2582f4b1be

**Comment by nimaai** [comment]
- [ ] use `PATH` instead of `URI`

**Comment by nimaai** [comment]
2 tests:
- [ ] one 200
- [ ] one 500

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/56ffec88a1aa3c398e9c1cfa38fd6071981c648f
