### ISSUE TITLE
Render Error when accessing leihs website for the first time

### ISSUE THREAD

**Issue by sdenz** [leihs/leihs#991]
I am getting a **Render Error** message in my web browser after deployment when accessing leihs website for the first time.

#### Expected behaviour
Create first user.

#### Actual behaviour
Render Error message in web browser.

#### Steps to reproduce
Follow instructions as in https://github.com/leihs/leihs-instance/blob/master/GUIDE.md
Deployment completed successfully.

#### Related issues 
Same issue as #735 and #725
I installed the latest ansible version, but still get the error.

#### Specifications
- Leihs version: 5.2.3
- Browser version: Google Chrome 87.0.4280.88 (same error in Safari or Firefox)
- MySQL/PostreSQL version: PostgreSQL 10.15

**Comment by eins78** [comment]
Please try again with the newest version of Leihs: https://github.com/leihs/leihs-instance/blob/943994496d0017a5dea03026dff08efa0b3e3350/GUIDE.md

If this problem persists, please reopen this issue and include the relevant parts of the server logs that show the error.
