### ISSUE TITLE
Too long inventory codes when creating a new item 

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#992]
#### Expected behaviour
When creating a new item I would expect the item to get a 5-digit code (without the pool identification). 

#### Actual behaviour
In pool IT-Zentrum when creating a new item the item gets a long inventory code with 9 digits (excluding the pool identification).
In all other pools the item gets the correct inventory code. 

The problem only turns up in production, not in staging. And seems to be a problem only in the pool IT-Zentrum.

#### Steps to reproduce
1. go to pool IT-Zentrum on productive environment
2. create a new item
3. check the inventory code - it is too long

#### Specifications
- Leihs version: 5.3.0
- Browser version: safari

**Comment by nimaai** [comment]
Shortname of that particular inventory pool was wrong.

**Comment by nadjaweisskopf** [comment]
Shortname has been adjusted but still the inventorynr. ist too long. Hast the DB accepted the change?
