### ISSUE TITLE
Changes to inventory pool list and page

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#999]
Sort the list when selecting a filter alphabetically: 
https://test.leihs.zhdk.ch/admin/inventory-pools/?page=1&per-page=50&is-active=active&order=%22%22&term=

Place field "name" on the left, field "short name" on the right or place all fields underneath each other
https://test.leihs.zhdk.ch/admin/inventory-pools/8bd16d45-056d-5590-bc7f-12849f034351

Make field "e-mail" left aligned.

**Comment by DrTom** [comment]
Implemented in https://ci.zhdk.ch/cider-ci/commits/?heads-only=true&per-page=12&page=1&git-ref=%224a34f2cd9ce77e0d83c7a6b991211efc7c0f1f60%22

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf test
